### ISSUE TITLE
Serializer error on checkin

### ISSUE THREAD

**Issue by TitouanGisle** [opensourceBIM/BIMserver#1001]
Hello there !

I tried to checkin an ifc file and got his error :
_Error on line 45: (For input string: "7713823082") #7713823082= IFCORGANIZATION('GS','Graphisoft','Graphisoft',$,$);_

I changed the line number to a more reasonable one (and changed accordingly every references to it) and the error passed on to the following line, whose number was just as huge. 
I changed it too, the error passed on to the next line and so on.

So it seems that the line number is too large for the serializer to handle. Is there an easy fix for that, a plugin I missed, or should I be considering writing a small utility program to reduce the line numbers?

**Comment by hlg** [comment]
The current parser uses `int` datatype and those only accepts max 2^31 for the record number. I believe the standard allows for up to 2^63, will double-check. If so the parser should be fixed.

However, renumbering would be the more pragmatic solution. It would also make the file smaller in case you have many of those large record numbers without actually needing them. I did a quick and dirty extrapolation: Before you hit the limit of 2^31 entities, your STEP file will likely be larger than 50 GB. So 2^31 should be sufficient for most cases.

Btw., I think it is the deserializer you are talking about and this should actually be in the IfcPlugins repository.

**Comment by TitouanGisle** [comment]
All right, I made a small utility that made the lineIDs more reasonnable.
I could put the link to it here if others need it, but I'm really not proud of it.

Increasing the max for the parsers/deserializers would be a good thing, it seems that Archicad randomly starts their lineIDs above the 4 Billions.

**Comment by rubendel** [comment]
Unfortunately the standard does not say anything about this, in theory we should be using BigInteger. I think the time has come to move to 64bit though, because if IFC files keep growing like they are we'll actually hit that 100GB limit pretty soon. Also would be pretty cool when BIMserver exports could use the BIMserver oids (64bits as well) as express id's :)

**Comment by rubendel** [comment]
I am checking this in later today, could you perhaps share the model, it would make testing this a bit quicker for me.

**Comment by TitouanGisle** [comment]
Sure !

Here's the original file : 
[Architecte-2.zip](https://github.com/opensourceBIM/BIMserver/files/3349868/Architecte-2.zip)
(with #7713823077 being the first entity)

And here's the one with smaller IDs : 
[smallified.Architecte-2.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/3349895/smallified.Architecte-2.ifc.zip)

**Comment by rubendel** [comment]
Great, the original works fine here too now, so this will be in the next release.

**Comment by TitouanGisle** [comment]
Nice, thanks a bunch !
