### ISSUE TITLE
no visualization 

### ISSUE THREAD

**Issue by SiMein** [opensourceBIM/BIMserver#1002]
Hello Ruben,
I tested some Ifc-examples in the BIMvie.ws and it workes fine.
Now I have a model and there is no visualization. (with another viewer on my dektop it works, so i think the file is ok!?)

"Model Data succsessfully loaded"  but there is no model to see, only the tree on the left.

What is the problem now ? 
Is it possible to get a more sensitive Debugmode expression ?

Operating system : Windows 10
Bimserverjar version : 1.5.147 
Browser : Firefox 67.0.4  (64-bit)

Maybe i can send/post my ifc-file  (61kb)

Thank you

**Comment by hlg** [comment]
Looking again at the same example:

    #670= IFCEXTRUDEDAREASOLID(#669,$,#14,34.36568055487916);
    #674= IFCSHAPEREPRESENTATION(#8,'Pipe (from: 30.0| 62.5|50.0) to (14.0| 92.5|45.0), length: 34.36568055487916)','SweptSolid',(#670));
    #675= IFCPRODUCTDEFINITIONSHAPE('IfcProductRepresentation',$,(#674));
    #681= IFCDISTRIBUTIONFLOWELEMENT('0N3AzSC6r929ijI20rYAor',#5,'Pipe(0.0| 0.0|0.0)',$,$,#673,#675,$);
    
The RepresentationIdentifier of the representation of the IfcDistributionFlowElement does indeed not look right. The representation has one item of type IfcExtrudedAreaSolid, thus the RepresentationType of "SweptSolid" is correct and corresponding RepresentationIdentifier would be "Body". Have a look at the definition tables for these values in the specification for [IfcShapeRepresentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/link/ifcshaperepresentation.htm). There is an Express rule using a function that maps valid RepresentationType values for the different types of RepresentationItems: [FUNCTION IfcShapeRepresentationTypes](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/link/ifcshaperepresentationtypes.htm). However, BIMserver does not evaluate these rules, it just ignores everything it can not handle, including this unknown type, for geometry generation.

In addition, the general usage MVD suggests certain geometry concepts to be used for given elements. For IfcDistributionFlowElement, these seem to be [Axis geometry](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/templates/axis-geometry.htm) and [Clearance geometry](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/templates/clearance-geometry.htm), not the above mentioned [Body SweptSolid geometry](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/link/body-sweptsolid-geometry.htm).

**Comment by tciles** [comment]
Hello,

I have an issue with the visualization part.

```
preloadModel 196611 : 2321 ms
bimviews.js:325:6
translation for REGISTERNEWEXTENDEDDATAONREVISIONHANDLER_BUSY not found, using key
bimserverclient.js:163:5
XHRPOST
http://srv-bim.alpes-controles.lan:8080/bimserver/json
[HTTP/1.1 200  63ms]
GET
http://srv-bim.alpes-controles.lan:8080/bimserver/apps/bimviews/img/eye.png
[HTTP/1.1 200  122ms]
XHRPOST
http://srv-bim.alpes-controles.lan:8080/bimserver/json
[HTTP/1.1 200  103ms]
XHRPOST
http://srv-bim.alpes-controles.lan:8080/bimserver/json
[HTTP/1.1 200  218ms]
translation for GETALLEXTENDEDDATAOFREVISION_BUSY not found, using key
```

I saw 2 notifications: 
REGISTERNEWEXTENDEDDATAONREVISIONHANDLER_BUSY 
GETALLEXTENDEDDATAOFREVISION_BUSY 

but after the viewer stay blank...

I use bim server 1.5.150
I saw that you have produced some versions.

There is a stable version without who fix this problem?

**Comment by SiMein** [comment]
Hallo Rubendel and hlg,

thank you for your feedback, at the end we came to the same conclusion. We will try to fix the matching-Problems (with reference to IFC-standard) and give you some Information about the solution if you interested .
