### ISSUE TITLE
Missing artifact org.opensourcebim:bimserverjar:jar:1.5.158-SNAPSHOT

### ISSUE THREAD

**Issue by celiakessassi** [opensourceBIM/BIMserver#1011]
After I import project from git I have this error

`Missing artifact org.opensourcebim:bimserverjar:jar:1.5.158-SNAPSHOT in Tests/pom.xml of type Maven Dependency Problem`

Steps I followed :

   1) clone with git
    2) import project

I can't get rid of this error

My second error is:

`Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.10:add-source (execution: add-source, phase: generate-sources) in BimServer/pom.xml type 'Maven Project Build Lifecycle Mapping Problem'`

**Comment by rubendel** [comment]
Current git works fine here, Test project pom.xml references
```xml
<dependency>
	<groupId>org.opensourcebim</groupId>
	<artifactId>bimserverjar</artifactId>
	<version>1.5.160-SNAPSHOT</version>
</dependency>
```

Please create a new issue for the second error.

**Comment by celiakessassi** [comment]
thank you the error has gone !
