### ISSUE TITLE
Check In using JSON API is not possible

### ISSUE THREAD

**Issue by david-San** [opensourceBIM/BIMserver#1016]
**Describe the bug**
Hi Ruben,

I have not been able to do checkin using the JSON API. I have tried all documentation and it seems there could be a bug somewhere.

I managed to do the checking, but the file is smaller than when I use the BIMView interface. It seems it is a bout 21 elements short. I can export the file and it seems fine, but it is not possible to see it on the online renderer.

**To Reproduce**
1. Go to the following web page to download the IFC file I am using to do this test. It's very small and simple:

http://openifcmodel.cs.auckland.ac.nz/Model/Details/268

2. Open the BIMserver webpage, enter administrator credential. Create a project "Test" (meter;ifc2x3tc1). Once the project is created, enter in it. Click on the triangle, and check in the file. Drag and drop the file 171210eccentricity_physical.ifc. Deserializer ifc2x3tc1 (Streaming). On the comment I put again the name of the file: 171210eccentricity_physical.ifc. and press "check in new version".

3. Click on the eye next to the project. You can see the beam on the right. 

4. Click on revisions and see the size. It says 75.

5. Now open console: http://127.0.0.1:8082/apps/console/

6. Navigate to checkinSync and fill the data. Using the same POID that the project has. In my case:

{
  "token": "55ea429a566f7e6f04d9dd4a79f89e8107baed8250d4757a1f48e8095a9afc37b57f5a540407e1cced1378173d453386",
  "request": {
    "interface": "ServiceInterface", 
    "method": "checkinSync", 
    "parameters": {
      "poid": 7995393,
      "comment": "171210eccentricity_phisical.ifc",
      "deserializerOid": 589865,
      "fileSize": 3579,
      "fileName": "17121eccentricity_physical.ifc",
      "data": "SVNPLTEwMzAzLTIxOw0KSEVBREVSOw0KRklMRV9ERVNDUklQVElPTigNCi8qIGRlc2NyaXB0aW9uICovICgnVmlld0RlZmluaXRpb24gW0Nvb3JkaW5hdGlvblZpZXddJywgJ0NvbW1lbnQgW0VjY2VudHJpY2l0eSxTVEVQIENhc2VsaWIgQW5hbHlzaXMgbW9kZWxdJyksDQovKiBpbXBsZW1lbnRhdGlvbl9sZXZlbCAqLyAnMjsxJyk7DQoNCkZJTEVfTkFNRSgNCi8qIG5hbWUgKi8gJ0M6L0RvY3VtZW50cyBhbmQgU2V0dGluZ3MvbGlwbWFuL015IERvY3VtZW50cy9DSVMyL0lGQ3Rlc3QvTklTVF9hbmFseXNpc19tb2RlbHMvZWNjZW50cmljaXR5X3BhcmFtLmlmYycsDQovKiB0aW1lX3N0YW1wICovICcyMDEwLTAxLTIyVDE2OjI4OjQ0JywNCi8qIGF1dGhvciAqLyAoJ1Vua25vd24nKSwNCi8qIG9yZ2FuaXphdGlvbiAqLyAoJ1Byb1NURVAgR21iSCcpLA0KLyogcHJlcHJvY2Vzc29yX3ZlcnNpb24gKi8gJ1N0ZWVsVmlzIC0gTklTVCBDSVMvMiB0byBJRkMgVHJhbnNsYXRvciA4LjAzJywNCi8qIG9yaWdpbmF0aW5nX3N5c3RlbSAqLyAnU1RFUCBDYXNlbGliJywNCi8qIGF1dGhvcml6YXRpb24gKi8gJ05vbmUnKTsNCg0KRklMRV9TQ0hFTUEgKCgnSUZDMlgzJykpOw0KRU5EU0VDOw0KDQpEQVRBOw0KIzI9IElGQ0NBUlRFU0lBTlBPSU5UKCgwLiwwLiwwLikpOw0KIzk9IElGQ0lTSEFQRVBST0ZJTEVERUYoLkFSRUEuLCdXMTJYMjInLCMyMDUwLDEwMi4zNjIsMzEyLjQyLDYuNjA0LDEwLjc5NSwkKTsNCiMxMD0gSUZDTUFURVJJQUwoJ1MyMzVKUkcyIGJlYW0gbWF0ZXJpYWwnKTsNCiM0Mj0gSUZDU0lVTklUKCosLkxFTkdUSFVOSVQuLC5NSUxMSS4sLk1FVFJFLik7DQojMTAxPSBJRkNNRU1CRVIoJzNVemZYQVpkJEFJaGlKaUZSTUp3MUYnLCMyMDA1LCdFMScsJ1cxMlgyMicsJCwjMTAyLCMxMDYsJ0UxJyk7DQojMTAyPSBJRkNMT0NBTFBMQUNFTUVOVCgkLCMxMDMpOw0KIzEwMz0gSUZDQVhJUzJQTEFDRU1FTlQzRCgjMiwjMTA0LCMxMDUpOw0KIzEwND0gSUZDRElSRUNUSU9OKCgtMC4wNTk3OCwwLiwwLjk5NjQxKSk7DQojMTA1PSBJRkNESVJFQ1RJT04oKDAuOTk4MiwwLiwwLjA1OTg5KSk7DQojMTA2PSBJRkNQUk9EVUNUREVGSU5JVElPTlNIQVBFKCQsJCwoIzEwNykpOw0KIzEwNz0gSUZDU0hBUEVSRVBSRVNFTlRBVElPTigjMjAxMSwnQm9keScsJ01hcHBlZFJlcHJlc2VudGF0aW9uJywoIzEwOCkpOw0KIzEwOD0gSUZDTUFQUEVESVRFTSgjMTEzLCMyMDU5KTsNCiMxMTA9IElGQ1NIQVBFUkVQUkVTRU5UQVRJT04oIzIwMTEsJ0JvZHknLCdTd2VwdFNvbGlkJywoIzExMSkpOw0KIzExMT0gSUZDRVhUUlVERURBUkVBU09MSUQoIzksIzIwNDksIzIwNDQsNTAwOS4pOw0KIzExMj0gSUZDTUVNQkVSVFlQRSgnM3NZRXk1djFkUEhnRk94VHVMcV9EOScsIzIwMDUsJ1cxMlgyMicsJCwkLCQsKCMxMTMpLCQsJCwuTk9UREVGSU5FRC4pOw0KIzExMz0gSUZDUkVQUkVTRU5UQVRJT05NQVAoIzIwNDAsIzExMCk7DQojMTE0PSBJRkNSRUxDT05UQUlORURJTlNQQVRJQUxTVFJVQ1RVUkUoJzAkYVFib0twcGFKQmN3bmk4RWlMeXgnLCMyMDA1LCdQaHlzaWNhbCBtb2RlbCcsJCwoIzEwMSksIzIwMjMpOw0KIzExNT0gSUZDUkVMREVGSU5FU0JZVFlQRSgnMm9hOGtnVHB5REplSmxldWQ0QnhZUycsIzIwMDUsJ01lbWJlcicsJCwoIzEwMSksIzExMik7DQojMjAwMT0gSUZDUEVSU09OKCQsJ1Vua25vd24nLCQsJCwkLCQsJCwkKTsNCiMyMDAyPSBJRkNPUkdBTklaQVRJT04oJCwnUHJvU1RFUCBHbWJIJywkLCQsJCk7DQojMjAwMz0gSUZDUEVSU09OQU5ET1JHQU5JWkFUSU9OKCMyMDAxLCMyMDAyLCQpOw0KIzIwMDQ9IElGQ0FQUExJQ0FUSU9OKCMyMDAyLCdVbmtub3duJywnU1RFUCBDYXNlbGliJywnVW5rbm93bicpOw0KIzIwMDU9IElGQ09XTkVSSElTVE9SWSgjMjAwMywjMjAwNCwkLC5OT0NIQU5HRS4sJCwkLCQsMTI2NDE5NTcyNCk7DQojMjAxMD0gSUZDUFJPSkVDVCgnMnVWVFVqNTV0a0lBS2dvdzVzYmx6RycsIzIwMDUsJ0VjY2VudHJpY2l0eSxTVEVQIENhc2VsaWIgQW5hbHlzaXMgbW9kZWwnLCQsJCwkLCQsKCMyMDExKSwjMjA2MCk7DQojMjAxMT0gSUZDR0VPTUVUUklDUkVQUkVTRU5UQVRJT05DT05URVhUKCQsJ01vZGVsJywzLDEuMEUtNSwjMjA0MCwkKTsNCiMyMDIwPSBJRkNTSVRFKCcxc2pZR1R0TGRpSEJpTmpGV2lCM0dQJywjMjAwNSwnU2l0ZScsJCwkLCMyMDIyLCQsJCwuRUxFTUVOVC4sJCwkLCQsJCwkKTsNCiMyMDIxPSBJRkNSRUxBR0dSRUdBVEVTKCcwQzV0dXBWOVZvR3hDYzJOeklWemV2JywjMjAwNSwkLCQsIzIwMTAsKCMyMDIwKSk7DQojMjAyMj0gSUZDTE9DQUxQTEFDRU1FTlQoJCwjMjA0MCk7DQojMjAyMz0gSUZDQlVJTERJTkcoJzFZQThEUDdpcE1KQW0wdG1IVkFzWUwnLCMyMDA1LCdCdWlsZGluZycsJCwkLCMyMDI1LCQsJCwuRUxFTUVOVC4sJCwkLCQpOw0KIzIwMjQ9IElGQ1JFTEFHR1JFR0FURVMoJzEyTWNPendlZWtJdTBqbzg1TUhEVzEnLCMyMDA1LCQsJCwjMjAyMCwoIzIwMjMpKTsNCiMyMDI1PSBJRkNMT0NBTFBMQUNFTUVOVCgjMjAyMiwjMjA0MCk7DQojMjA0MD0gSUZDQVhJUzJQTEFDRU1FTlQzRCgjMjA0MSwjMjA0NCwjMjA0Mik7DQojMjA0MT0gSUZDQ0FSVEVTSUFOUE9JTlQoKDAuLDAuLDAuKSk7DQojMjA0Mj0gSUZDRElSRUNUSU9OKCgxLiwwLiwwLikpOw0KIzIwNDM9IElGQ0RJUkVDVElPTigoMC4sMS4sMC4pKTsNCiMyMDQ0PSBJRkNESVJFQ1RJT04oKDAuLDAuLDEuKSk7DQojMjA0OD0gSUZDRElSRUNUSU9OKCgwLiwwLiwtMS4pKTsNCiMyMDQ5PSBJRkNBWElTMlBMQUNFTUVOVDNEKCMyMDQxLCMyMDQyLCMyMDQzKTsNCiMyMDUwPSBJRkNBWElTMlBMQUNFTUVOVDJEKCMyMDUxLCMyMDUyKTsNCiMyMDUxPSBJRkNDQVJURVNJQU5QT0lOVCgoMC4sMC4pKTsNCiMyMDUyPSBJRkNESVJFQ1RJT04oKDEuLDAuKSk7DQojMjA1Mz0gSUZDRElSRUNUSU9OKCgwLiwxLikpOw0KIzIwNTQ9IElGQ0RJUkVDVElPTigoLTEuLDAuKSk7DQojMjA1NT0gSUZDRElSRUNUSU9OKCgwLiwtMS4pKTsNCiMyMDU2PSBJRkNESVJFQ1RJT04oKC0xLiwtMS4pKTsNCiMyMDU5PSBJRkNDQVJURVNJQU5UUkFOU0ZPUk1BVElPTk9QRVJBVE9SM0QoJCwkLCMyMDQxLDEuLCQpOw0KIzIwNjA9IElGQ1VOSVRBU1NJR05NRU5UKCgjNDIsIzIwNjIsIzIwNjMsIzIwNjQsIzIwNjUsIzIwNjYsIzIwNjcsIzIwNjgpKTsNCiMyMDYyPSBJRkNTSVVOSVQoKiwuUExBTkVBTkdMRVVOSVQuLCQsLlJBRElBTi4pOw0KIzIwNjM9IElGQ1NJVU5JVCgqLC5NQVNTVU5JVC4sLktJTE8uLC5HUkFNLik7DQojMjA2ND0gSUZDU0lVTklUKCosLlRJTUVVTklULiwkLC5TRUNPTkQuKTsNCiMyMDY1PSBJRkNTSVVOSVQoKiwuQVJFQVVOSVQuLCQsLlNRVUFSRV9NRVRSRS4pOw0KIzIwNjY9IElGQ1NJVU5JVCgqLC5QUkVTU1VSRVVOSVQuLCQsLlBBU0NBTC4pOw0KIzIwNjc9IElGQ1NJVU5JVCgqLC5GT1JDRVVOSVQuLCQsLk5FV1RPTi4pOw0KIzIwNjg9IElGQ1NJVU5JVCgqLC5USEVSTU9EWU5BTUlDVEVNUEVSQVRVUkVVTklULiwkLC5ERUdSRUVfQ0VMU0lVUy4pOw0KRU5EU0VDOw0KDQpFTkQtSVNPLTEwMzAzLTIxOw0K",
      "merge": "false"
    }
  }
}

7. Hit send: Response:

{
  "response": {
    "exception": {
      "__type": "ServerException",
      "message": "org.bimserver.interfaces.objects.SLongActionState cannot be cast to org.bimserver.interfaces.objects.SLongCheckinActionState"
    }
  }
}

8. Go the project. Even though there was an error the file was checkin but partially. If you to Revisions, it says it is 54 in size. You can see the tree but cannot see the 3D of the file in the interface. If you download the file, it seems it is exactly as the original one.

9. Could you please tell me how to solve this?

Thank you so much in advance. 

**Expected behavior**
Both size to be the same when doing the checkin via interface or via REST. The application I am working on can only access via REST. I need to be able to see the 3D of the element.

**Screenshots**
1 | 16 minutes ago | Administrator | 171210eccentricity_physical.ifc | 75
2 | 12 minutes ago | Administrator | 171210eccentricity_phisical.ifc | 54

**Additional context**
I tried all other methods and it is still the same issue. I tried using Postman and my app. Always is the same. It seems I am missing 21 bytes in the checkin always. I am using BIMserver 1.5.125 on macOS, Java 8.

**Comment by rubendel** [comment]
1. Just to be clear, BIMserver does not have a REST interface.
2. The size in the revisions table is the amount of objects in the model, not the filesize, which would make no sense since BIMserver does not store the IFC files as files, as you have probably read in the documentation.

Can you try again in the latest release? I just did the same thing and it results in two models of 75 objects.

**Comment by david-San** [comment]
Sorry for using the wrong name. I meant using the JSON API.

You are right, I checked using version 1.5.157 and it seems to do the checkin process correctly. 

Unfortunately, as a result of the change, my application is now completely broken. I have to figure out what happened.

**Comment by motjokk** [comment]
In my experience, it is best to use the checkinFromUrlSync method.

**Comment by hlg** [comment]
This seems to have been resolved in 1.5.157.
