### ISSUE TITLE
Geometry not generated correctly IFC2X3

### ISSUE THREAD

**Issue by muren400** [opensourceBIM/BIMserver#1022]
Hi,

the Geometry in [this file](https://github.com/opensourceBIM/BIMserver/files/3473182/Balken_FGG.zip) (Balken_FGG.ifc) is not created correctly only the three cylinders on the bottom are generated.

Its supposed to look like this:
![image](https://user-images.githubusercontent.com/13089452/62557367-26052080-b877-11e9-96d8-82671618ad33.png)

But in bimvie.ws and BimSurfer its diplayed like this:
![image](https://user-images.githubusercontent.com/13089452/62557487-62388100-b877-11e9-9ee4-9ab7e9e5f1e3.png)

When its exported as IFC4 its generated correctly
![image](https://user-images.githubusercontent.com/13089452/62557683-b6dbfc00-b877-11e9-8372-046f9d4fb7e5.png)

Is this an issue with IfcOpenShell?

Greetings,
muren

**Comment by rubendel** [comment]
I can reproduce this, also tested whether this might be a problem in BIMserver geometry generation code, I don't think it is, so my best guess is also IfcOpenShell. Will send this file to the IfcOpenShell developer and report back here.

**Comment by hlg** [comment]
The file contains a faceted BREP with 1380 faces, each bounded by a triangular polyloop. According to the geometry report, the IfcOpenShell plugin generates only 940 triangles for the full file.

I have manually removed half of the faces from the BREP and voila, we see a different set of triangles missing from the geometry generation, with the ones previously missing now included. There seems to be an issue with the large set of faces either during extracting the geometry or while passing it to the render engine.

![image](https://user-images.githubusercontent.com/356986/109551716-3328d680-7ad1-11eb-9a5d-fb4e22427694.png)

**Comment by hlg** [comment]
This is too weird. Actually, it is enough to remove one single face, for example the first in the set (#140). It must not be a particular one, though it does not work with every face.

**Comment by hlg** [comment]
There seems to be some issue when IfcOpenShell processes the geometry to calculate the volume. When quantity calculation is disabled, the visualization looks complete. By the numbers, some triangles are still missing, but there are no visible wholes.

**Comment by muren400** [comment]
Thanks a lot! That did the trick. Is it possible, to turn off quantity calculation? We dont really need that and I haven't figured out yet, how to turn it off.

**Comment by hlg** [comment]
You can set the flag in global plugin settings of the IfcOpenShell plugin.

In BIMvie.ws:
_Server / Installed Plugin Bundles / Plugin Bundle IfcOpenShell-BIMserver-plugin / Plugin IfcOpenShell / Setting Calculate Quantities_

Via API:
`PluginInterface.setPluginSystemSettings`
