### ISSUE TITLE
Java Client Query

### ISSUE THREAD

**Issue by RobertStancu** [opensourceBIM/BIMserver#1023]
Hi, 

I am trying to upload a project to the bimServer and then query objects with their geometry, more exactly the "ObjectPlacement" attribute that shows a cartesian point, like in the example from bimvie.ws:

{
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "includes": [
    "ifc4stdlib:ContainedInStructure",
    "ifc4stdlib:OwnerHistory",
    "ifc4stdlib:Representation",
    "ifc4stdlib:ObjectPlacement"
  ]
}

This how I'm trying to replicate the query using the Java client (and by looking at the code snippets from the project):

```
QueryPart queryPart = query.createQueryPart();
                queryPart.addType(packageMetaData.getEClass("IfcWall"), true);
                Tiles tiles = new Tiles();
                tiles.add(0);
                tiles.setMaximumThreshold(1000);
                tiles.setMaxDepth(0);
                queryPart.setTiles(tiles);
                Include include1 = queryPart.createInclude();
                include1.addType(packageMetaData.getEClass("IfcProduct"), true);
                include1.addField("geometry");
                Include include2 = include1.createInclude();
                include2.addType(GeometryPackage.eINSTANCE.getGeometryInfo(), false);
                include2.addField("data");
```

This works but if I try to add include.addField("ObjectPlacement") I don't get the same results as in the example query. Would someone be kind enough to explain me how it should be written?

Thank you in advance.

**Comment by rubendel** [comment]
In this case it's not a `field`, it's an `include`. You can add those by doing:

```
queryPart.addInclude("ifc4-stdlib:ObjectPlacement")
```

**Comment by RobertStancu** [comment]
Thank you, rubendel
