### ISSUE TITLE
IFC Splitter 

### ISSUE THREAD

**Issue by geolocus** [opensourceBIM/BIMserver#1025]
Hey,

I've been trying to use ifc2b3dm code by Erfaan. Originaly it splitts IFC into parts with no problem but whenever Ive tried updateing code for extra ifc Type splitting it doesnt really download anything.

![paveikslas](https://user-images.githubusercontent.com/43907761/62823931-64604f80-bb97-11e9-8441-68ed4266abc4.png)

Any idea what kind of triggering is missing if I add extra etc. FlowFitting, FlowSegment types? 

[ifcconverter.zip](https://github.com/opensourceBIM/BIMserver/files/3489069/ifcconverter.zip)

thank you in advance!

**Comment by rubendel** [comment]
Pretty sure you are on the wrong issue tracker :) No idea what you are talking about.

**Comment by geolocus** [comment]
uh, yeah. Sorry it's outside code.
