### ISSUE TITLE
Ifc checkin error

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMserver#1029]
Hello,

I checkin ifc file and get an error:
![error](https://user-images.githubusercontent.com/44858488/63166381-87bf4a80-c02e-11e9-96dc-bc4bf549c1d2.PNG)

In ifc have _#88944=IFCCIRCLEHOLLOWPROFILEDEF(.AREA.,$,#148266,0.,-NAN(IND).);
_

I use BimServer 1.5.162.
Is possible fix this?

Thanks

**Comment by rubendel** [comment]
It is definitely possible to fix this, you should ask the developers of the software that exported this file though as -NAN(IND) is not a valid floating point literal in IFC/Express.
