### ISSUE TITLE
Window opening is not subtracted from the wall

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#1036]
Hi,
Can you please check why the window opening is not subtracted from the wall?
Please have a look at the attached pictures and the IFC file.
Regards,
Jo

![WallWindowSolibri](https://user-images.githubusercontent.com/16973608/65186454-03ffe000-da6a-11e9-981c-4cc526899b3c.PNG)
![WallWindow](https://user-images.githubusercontent.com/16973608/65186498-124dfc00-da6a-11e9-9a23-219696591144.PNG)
[WallWindowOpening.zip](https://github.com/opensourceBIM/BIMserver/files/3628409/WallWindowOpening.zip)

**Comment by rubendel** [comment]
I can reproduce this, will discuss with IfcOpenShell developer

**Comment by rubendel** [comment]
This should be fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/ae6dfce7e384589c6a202aa9b50cb9117762bc41 thanks to @aothms! Will test it as soon as new binaries have been built and will then include it in te next version of the IfcOpenShell BIMserver plugin.

**Comment by hlg** [comment]
This is fixed with next version of IfcOpenShell BIMserver plugin (IOS commit sha 517b819).
