### ISSUE TITLE
Json Queries: Include porperty set values in response

### ISSUE THREAD

**Issue by muren400** [opensourceBIM/BIMserver#1037]
Hi,

in the examples for the JSON Queries I've seen, that it's possible, to filter the results by using their properties. Like this:

{
  "version": 2,
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "properties": {
    "Pset_WallCommon": {
      "IsExternal": true
    }
  }
}

Is it also possible, to include a specific property and its value in the queried result?
So if I wanted to include the Property "Category" the result would look something like this?

{
    "_i":1,
    "_t":"IfcBuildingElementProxy",
    "_s":1,
    "Category": "some random value"
}

I'm building a tree view for the Models on the Server. The treenodes are supposed to be categorized by some property value, for example a property called "Category". What I'm doing right now is to load all the Properties for the objects and then iterate through all of them until I find the right one.

This procedure requires a lot of data being downloaded and processed and since its possible to filter objects by a specific property value, I thought it might be possible to include a specific property, rather than querying all of them?

**Comment by rubendel** [comment]
The results of queries are always structured according to the IFC schema (serialized as either ifc-step or json). So what you ask is not possible (IfcBuildingElementProxy does not have a field called "Category"). Basically, the query language does not allow you to command the structure of the returned data, only the content.

It is however possible to get the properties in the result, but they will be structured as they are in the IFC file.

For example this query:
```
{
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "include": "ifc2x3tc1-stdlib:AllProperties"
}
```

Will give you all the walls and all their properties.

And the next query will filter the walls on your requirement:

```
{
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "properties": {
    "Pset_WallCommon": {
      "IsExternal": true
    }
  },
  "include": "ifc2x3tc1-stdlib:AllProperties"
}
```

It is up to you to get the final results out.

**Comment by muren400** [comment]
All right. Thanks for the Answer. I kind of expected something like that, but I wanted to ask anyway. I guess I'll look a bit into the Query Engine Plugins.

Closing this issue.

**Comment by acrimat** [comment]
I'm just wondering... Is there a way to not get all properties but only specific ones. For example defined by their property name.

Thanks in advance.

**Comment by hlg** [comment]
In theory, you could query starting from the property, but you would only get entities (objects or types) that have a property with this name assigned. In IFC2x3 this is not possible, but in IFC4, because the inverse attribute for "HasProperties" was added only in IFC4 ("PartOfOPset"). The query would look like this (for IfcProperty with name "IsExternal").

```
{
"type": {
    "name": "IfcProperty",
    "includeAllSubTypes": true
},
"name": "IsExternal",
"includes": [{
   "type": "IfcProperty",
   "fields": ["PartOfPset"],
   "includes": [{
      "type": "IfcPropertySet",
      "fields": ["DefinesOccurrence"],
      "includes": [{
	  "type": "IfcRelDefinesByProperties",
	  "fields": ["RelatedObjects"]
     }]
  }]
}]
}
```

In practice this does not work though, because BIMserver treats the name value as identifier (equivalent to OID or GUID) and will only include the first such entity of type IfcProperty in the  result plus everything that is referenced from there, that is all property sets using this property and all entities related to those properties in the above example.
