### ISSUE TITLE
Error trying to setup BimServer

### ISSUE THREAD

**Issue by ragiz** [opensourceBIM/BIMserver#1038]
Hi Everyone
we are having problem installing BIM Server 1.5.162, after clicking Setup in the Finish step in the installation wizard, we get this error:

Setting up...
	Setting up admin account...
		Admin account successfully setup
		Setting up email...
		Email successfully setup
	Checking internet connection _from_ your BIMserver...
		Internet connection OK
	Not installing extended data schemas
	Installing plugins...
		Installing bimviews...
		Successfully installed BIMvie.ws (org.opensourcebim:bimviews:0.0.160)

		Installing bimsurfer3...
		Successfully installed BIMsurfer 3 (org.opensourcebim:bimsurfer3:0.0.252)

		Installing ifcopenshellplugin...
		javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

		Setup aborted

1. Install Apache Tomcat 9.0.10 Server 
2. deploy the bimserverwar-1.5.162.war to C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps
3. Open the web interface and follow the wizard and after clicking setup
4. you See error

The Expected behavior is for Setup to complete successfully.

![Capture](https://user-images.githubusercontent.com/55576391/65307144-d2813480-db8f-11e9-8889-bd7e7d2319d7.PNG)

**Comment by rubendel** [comment]
Can you share the BIMserver log file?

**Comment by ragiz** [comment]
Hi Ruben, 
thank you for the prompt reply,
Issue was caused by the firewall, resolved by opening some closed ports by our IT security for the server

regards
RZ
