### ISSUE TITLE
The setup porcess seems stop during installation of bimviews 

### ISSUE THREAD

**Issue by yokoyamy** [opensourceBIM/BIMserver#1039]
**Describe the bug**
The setup process is freezing at bimviews installation.
               

		.....................
                VALIDATION_JSON_2_0 installed OK
		Extended Data Schemas installed OK
	Installing plugins...
		Installing bimviews...

**To Reproduce**

Downloading bimserver war file which version is over 1.5.138
Deployed under tomcat's `webapps` folder
Access bimserver  via web browser
Start the setup process.
The Setup process seems stop after staritng installation of bimvews

It means the setup porcess will be finished successfully, as long as processing version before 1.5.125 

**Expected behavior**
The setup process will be finished .

**Comment by rubendel** [comment]
Unfortunately BIMserver at the moment relies on maven central for installing plugins, the last few days they have had problems with downtime/timeouts, this is also why we can't do any releases currently. I suspect this is the problem, OR that your firewall/proxy is not configured to allow these connections.

**Comment by yokoyamy** [comment]
Which port shuld be opend, if this is firewall/proxy issue?

**Comment by rubendel** [comment]
If you look in the BIMserver log file you probably see some URL's. I'd say port 80 and 443 should be enough.

**Comment by yokoyamy** [comment]
Cloudl you tell me tha PATH to  BIMserver log file ? I didn't coufigure it myself.

My BimServer is behind revers-proxy.
Setting of httpd is here...
both 1.5.138 and  1.5.125 is same settings.

###############################
#
# bimserver1.5.m
#
##############################
ProxyPass /bimserver1.5.m/stream wss://localhost:8443/bimserverwar-1.5.138/streamProxyPassReverse /bimserver1.5.m/stream wss://localhost:8443/bimserverwar-1.5.138/stream
ProxyPass /bimserver1.5.m https://localhost:8443/bimserverwar-1.5.138

###############################
#
# bimserver1.5.n
#
##############################
ProxyPass /bimserver1.5.n/stream wss://localhost:8443/bimserverwar-1.5.125/stream
ProxyPassReverse /bimserver1.5.n/stream wss://localhost:8443/bimserverwar-1.5.125/stream
ProxyPass /bimserver1.5.n https://localhost:8443/bimserverwar-1.5.125

**Comment by rubendel** [comment]
A reverse proxy has nothing to do with outgoing connections. Please read the documentation, the bimserver log file is always in [BIMSERVER_HOME]/logs/bimserver.log. If you don't know where your BIMserver home directory is, please read the documentation again.

**Comment by yokoyamy** [comment]
There are tow logs. 
First one is for 1.5.138 which is failed ,second one is for 1.5.125 which is succeeded.
[bimserver.1.5.138.log](https://github.com/opensourceBIM/BIMserver/files/3661198/bimserver.1.5.138.log)
[bimserver1.2.125.log](https://github.com/opensourceBIM/BIMserver/files/3661199/bimserver1.2.125.log)

**Comment by yokoyamy** [comment]
1.5.16 was installed sucessfully. It took long time to start installation as you pointed .
