### ISSUE TITLE
Load IfcProduct with properties by specific property set name or property name

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMserver#1041]
Hello,

is possible use query language for loading IfcProduct with properties by 
IfcPropertySet name or IfcProperty name, not by value of properties? For example all IfcProduct with only Pset_WallCommon property set name. I found only query for loading by property value.

Thanks

**Comment by rubendel** [comment]
Sorry for the late reply, no that's not currently possible.
