### ISSUE TITLE
Hanging on login page for some machines

### ISSUE THREAD

**Issue by maakkoush** [opensourceBIM/BIMserver#1043]
Hi,

After login, the BIMviews hangs on login page with login successful message on some machines only. Others work fine. Any ideas how to troubleshoot?

**Comment by rubendel** [comment]
Closing, too little information/effort

**Comment by maakkoush** [comment]
This is the first time I open an issue, what do you mean too little information? I just need to know if its a known issue? Shall we troubleshoot tomcat logs or are there specific internet options settings per machine? Any help here?

**Comment by rubendel** [comment]
Try to give enough information, for example which versions of BIMserver, BIMvie.ws etc... Which OS, JVM version, what's in the BIMserver log, what's in the JavaScript Console...

**Comment by maakkoush** [comment]
Hi,

Please find the needed info below. Plus I could not find anything in the tomcat logs not bim server logs under bimserver application.
[cid:image001.png@01D5834F.E9023A30]

BIM server version:
[cid:image002.png@01D58367.00839070]

Regards,
Mona

**Comment by maakkoush** [comment]
Hi,

I would appreciate any assistance here please.

Thanks,
Mona

From: Mona Akkoush
Sent: Tuesday, October 15, 2019 2:44 PM
To: 'opensourceBIM/BIMserver' <reply@reply.github.com>
Subject: RE: [opensourceBIM/BIMserver] Hanging on login page for some machines (#1043) (DarRef: Not Referenced)

Hi,

Please find the needed info below. Plus I could not find anything in the tomcat logs not bim server logs under bimserver application.
[cid:image001.png@01D58981.8FA8F9A0]

BIM server version:
[cid:image002.png@01D58981.8FA8F9A0]

Regards,
Mona

**Comment by rubendel** [comment]
Please give more info

**Comment by maakkoush** [comment]
Unfortunately, this is the only info I could access. Can you please assist whether this is a known issue? Should I check something in the browser settings? At the Tomcat level?

**Comment by rubendel** [comment]
Dude I asked for "which versions of BIMserver, BIMvie.ws etc... Which OS, JVM version, what's in the BIMserver log, what's in the JavaScript Console..." of which you provided none

**Comment by maakkoush** [comment]
Hi,

I already sent these earlier. One more thing, please advise how can we accelerate support on BIM Sever? Is there any official support we can subscribe to or is it only through GitHub?

From: Mona Akkoush
Sent: Tuesday, October 15, 2019 2:44 PM
To: 'opensourceBIM/BIMserver' <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [opensourceBIM/BIMserver] Hanging on login page for some machines (#1043) (DarRef: Not Referenced)

Hi,

Please find the needed info below. Plus I could not find anything in the tomcat logs not bim server logs under bimserver application.
[cid:image001.png@01D5899D.77BDDCE0]

BIM server version:
[cid:image002.png@01D5899D.77BDDCE0]

Regards,
Mona

**Comment by maakkoush** [comment]
Hi,

Why did you close it again?
I sent the needed info, Please advise whether you’re not receiving them or they are not enough?

Regards,
Mona

**Comment by rubendel** [comment]
Just look in the thread (don't use email), there is no usable information

**Comment by maakkoush** [comment]
Just noticed that they don’t appear on Github. I thought you can view the images by email. Will attach them to the blog.

**Comment by maakkoush** [comment]
Attaching info. 
![1](https://user-images.githubusercontent.com/56578703/67569387-67e78980-f737-11e9-8281-d931958d96c1.png)
![bimserverVersion](https://user-images.githubusercontent.com/56578703/67569392-6a49e380-f737-11e9-9c9a-93fa7b2b8fce.png)
