### ISSUE TITLE
database initialisation error when starting bimserver

### ISSUE THREAD

**Issue by celiakessassi** [opensourceBIM/BIMserver#1044]
Whenever I run bimserver I have this error.

> 15:17:53 INFO  [main]: Non-empty database directory found "tmptestdata/home/database"                   (BerkeleyKeyValueStore.java:85) 
> 14:43:24 ERROR [main]:                                                                                  (BimServer.java:805) 
> org.bimserver.database.berkeley.DatabaseInitException: A database initialisation error has occured ((JE 7.5.11) tmptestdata/home/database Can not register tmptestdata/home/database or its sub-directories to WatchService. UNEXPECTED_EXCEPTION: Unexpected internal Exception, may have side effects. Environment is invalid and must be closed.)
> 	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:120)
> 	at org.bimserver.BimServer.start(BimServer.java:664)
> 	at org.bimserver.AbstractLocalDevBimServerStarter.start(AbstractLocalDevBimServerStarter.java:75)
> 	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:37)
> 14:43:24 ERROR [main]: BIMserver did not startup correctly                                              (AbstractLocalDevBimServerStarter.java:111) 

This Error occurs when I start bimserver.

I tested bimserver 1.5.73 and 1.5.162 both jar and source code.
the java versions I tested 8 and 11 
it always stucks in the same error

**Comment by rubendel** [comment]
How big is your database? Which OS? Are  you running on a VM perhaps. There is a limit to the amount of disk watches that can be set, maybe that's been met. Does it work with a clean home directory?

**Comment by rubendel** [comment]
Since you also get this error on a clean home directory (and thus an empty database), I suspect this has something to do with file system rights. Which folder is used for the home directory? And what are the access right on it?

**Comment by celiakessassi** [comment]
the home directory is /home/scii/eclipse-workspace/BIMserver-1.5.173/BimServerJar/tmptestdata/home 
the right access for tmptestdata is drwxrwxrwx 
I suspected that also at first because je.info.0 and je.lck are empty but can't see why this happens.

**Comment by rubendel** [comment]
I don't know what else to try, there is very little information on the internet about the specific BerkeleyDB JE exception. I'll leave this issue open in case more people encounter the same problem or know of a solution.

**Comment by hlg** [comment]
I use BIMserver all the time with Ubuntu 18.04, never encountered this issue. I just double-checked with both OpenJDK 8 and 11 and BIMserver jar 1.5.162.

You seem to have the home directory in your eclipse-workspace. Not sure if this could raise issues. Maybe try a different place and/or check if there are any locks on database files in the home directory with `lslk` and `lsof`?

**Comment by number133** [comment]
I've had the same issue on Ubuntu 18.04, but the problem doesn't seem to be distro specific.
My problem was that I didn't have not enough watch limit.
[This](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers) helped me.

**Comment by hlg** [comment]
Is this still an issue?

**Comment by hlg** [comment]
Here are the places from this thread that offer answers to the problem:

* Guard Listen gem [Readme](https://github.com/guard/listen/blob/master/README.md#increasing-the-amount-of-inotify-watchers)
* Internet archive crawler [issue comment](https://github.com/internetarchive/heritrix3/issues/559#issuecomment-1557912505)
* Ask Ubuntu [question and answer](https://askubuntu.com/questions/299689/tail-inotify-cannot-be-used-reverting-to-polling-too-many-open-files/1377649#1377649)

They suggest to edit `/etc/sysctl.conf` (or file in `/etc/sysctl.d/` depending on the OS) and increase `fs.inotify.max_user_watches`, potentially also `max_queued_events` and `max_user_instances`, then reload sysctl configurations.

If you encounter the issue and the above does not help, feel free to reopen this issue.
