### ISSUE TITLE
Queries using "validifc" keyword return nothing

### ISSUE THREAD

**Issue by ThornM9** [opensourceBIM/BIMserver#1046]
**Describe the bug**
Using the "validifc"/"includes" keywords in a JSON query seems to result in an empty return value. 

**To Reproduce**
This bug appears in v1.5.162, the latest stable release. This behaviour happens when using the client.download() method
An example query that shows this behaviour is shown below:
`{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  },
  "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ],
  "oid":1573405
}`
This is a simplified version of the query that I am executing but still demonstrates the lack of return value. This query resembles some of the example queries in the wiki very closely, so I'm not entirely sure why it doesn't work.
https://github.com/opensourceBIM/BIMserver/wiki/JSON-Queries

In comparison, the below similar query without the "includes" and "validifc" clauses returns some data.
`{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  },
  "oid":2097693
}`

**Expected behavior**
I expect the query to return a valid IFC file. The client.download method should serialise this data into either an IFC file or a JSON file depending on the specified serialiser.

**Comment by rubendel** [comment]
The `validifc` namespace has been renamed to `ifc2x3tc1-stdlib`.
