### ISSUE TITLE
IfcPolygonalFaceSet not working

### ISSUE THREAD

**Issue by kurb70** [opensourceBIM/BIMserver#1048]
Dear all!

I run bimserverjar-1.5.172.jar on macOS 10.14.6 (18G103) locally with
- OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
- OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

I was able to make a basic BIMserver setup and was also able to check in an simple IFC4 model created with Archicad 23.

When I try to view this 3D model in Firefox 71.0b5 I get an empty canvas. There are several warnings at the webbrowser console. Screenshot attached.

Any ideas to solve this?

BR Kurt

<img width="1311" alt="Screenshot 2019-10-31 at 19 43 06" src="https://user-images.githubusercontent.com/1941141/67976630-c076c500-fc16-11e9-81ac-a94306d40400.png">

**Comment by rubendel** [comment]
Just tried 1.5.172 on macOS with firefox, works here. First, let's determine whether this is a problem with the IFC file, or with your setup. Can you try a different browser on the same machine? Can you try a different IFC file, for example https://github.com/opensourceBIM/TestFiles/blob/master/TestData/data/AC11-Institute-Var-2-IFC.ifc?

**Comment by kurb70** [comment]
Thanks for checking.

The project AC11-Institute-Var-2-IFC is displayed in Firefox and Safari. I noticed it is an IFC2x3 project.

I used an IFC4 file. This [SimplyTwoRooms ARC -- IFC4 RV BIMt.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/3804259/SimplyTwoRooms.ARC.--.IFC4.RV.BIMt.ifc.zip) file, created with Archicad 23 AUT, is also not displayed in Safari.

**Comment by rubendel** [comment]
Ok so it's not a browser/OS problem. Just talked to the developer of IfcOpenShell, this type of geometry is currently not supported but they are working on it. Needless to say no timetable can be given for this to work in BIMserver, we will update IOS as soon as it's available.

**Comment by kurb70** [comment]
Tx for your investigation.

I‘m curious: What kind of geometry is the problem?
Does a single occurrence result in the whole model not being displayed?

**Comment by rubendel** [comment]
By the looks of it all or at least most of the geometry is exported as "IfcPolygonalFaceSet", which is relatively new (just read Solibri implemented this in september 2019). It was added in IFC4Add2 (2016), but adoption seems to have been slow. I am guessing Archicad 23 is one of the first to use it in IFC exports. Here is a related issue: https://github.com/IfcOpenShell/IfcOpenShell/issues/604

**Comment by rubendel** [comment]
Renaming this issue to reflect the actual issue.

**Comment by hlg** [comment]
This is probably resolved by now.

**Comment by hlg** [comment]
Solved in later versions of IfcOpenShell.
