### ISSUE TITLE
ifc checkin error

### ISSUE THREAD

**Issue by 767503672** [opensourceBIM/BIMserver#1049]
hello 
I import the file times wrong.
[WallOnly.ifc] org.bimserver.shared.VirtualObject.setAttribute(Lorg/eclipse/emf/ecore/EStructuralFeature;Ljava/lang/Object;)V,

How to solve this mistake?

**Comment by rubendel** [comment]
Closing, no version info, no logs -> no help

**Comment by 767503672** [comment]
i use 1.5.174 bimserver version  
plugins version 
 
![{J)X5HVC)) FF49I65_}NSW](https://user-images.githubusercontent.com/56863642/68107019-747d9600-ff1e-11e9-858b-8e5e47fd5ea0.png)

**Comment by 767503672** [comment]
> Closing, no version info, no logs -> no help

i use 1.5.174 bimserver version  
plugins version 
 
![{J)X5HVC)) FF49I65_}NSW](https://user-images.githubusercontent.com/56863642/68107019-747d9600-ff1e-11e9-858b-8e5e47fd5ea0.png)
