### ISSUE TITLE
How to decode specific characters

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMserver#1050]
Hello,

is possible correct decode strings like:
in ifc file ->                                REALIZA\X\C8N\X\DD PROJEKT
after upload to bim server ->    REALIZAÈNÝ PROJEKT
correct value ->                         REALIZAČNÝ PROJEKT

Thanks for information

**Comment by rubendel** [comment]
Why would you want BIMserver to decode it incorrectly? Would it not make more sense to fix the bug in the software that wrote this file?

Relevant documentation: https://www.unicode.org/wg2/iso10646/edition5/charts/iso10646-5th-CodeCharts.pdf
