### ISSUE TITLE
Information Disclosure

### ISSUE THREAD

**Issue by rupeshvirat** [opensourceBIM/BIMserver#1051]
I have found a vulnerability on a website named http://bimserver.org . Current the websites up and running, however any attacker could access critical contents of the website through login into woredpress..

Details :
High Level Vulnerabilities :

The websites critical directories are can be viewed from the browser by Directory traversal methodology. Refer attached Screenshot_1 and Screenshot_2.
http://bimserver.org/wp-content/uploads/
http://bimserver.org/wp-includes/
Mitigation : Restrict critical directories by providing password which will make them more 
![Screenshot 1](https://user-images.githubusercontent.com/57387320/68185468-9717b980-ffc7-11e9-8c82-873dc168bd89.PNG)
![Screenshot 2](https://user-images.githubusercontent.com/57387320/68185469-9717b980-ffc7-11e9-8d05-82db0526856e.PNG)
[Vulnerability Report.docx](https://github.com/opensourceBIM/BIMserver/files/3807615/Vulnerability.Report.docx)

secure. If not authentication, restrict the directories accessible on the internet. Also disable the directory listing.

Also found some following out dated plugins: Refer Attached Vulnerability Report.
buddypree : Mitigation:- Update to latest version 5.0.0
jetpack : Mitigation:- Update to latest version 7.8
wp-super-cache : Mitigation:- Update to latest version 1.7.0

Please refer attached Vulnerabilities_Report for more details.

Thanks & Regards,
Rupesh Kokare
Security Researcher
kokare.rupesh.rupesh@gmail.com

**Comment by rupeshvirat** [comment]
Hello @rubendel,

Can you please tell me why this ticket is closed?

Thanks,
Rupesh

**Comment by rubendel** [comment]
Use the search function

**Comment by rupeshvirat** [comment]
But this is the valid vulnerability. can you please provide me the exact reason for close this?

**Comment by rubendel** [comment]
There are loads of these automatically created issues: https://github.com/opensourceBIM/BIMserver/issues?utf8=%E2%9C%93&q=disclosure.

As has been said **multiple times**, this issue tracker is for the Open Source BIMserver, not for the website bimserver.org.

**Comment by rupeshvirat** [comment]
Hello Ruden,

Please check on the BIMserver responsible page where you do not mentioned
which domain is in scope and which one is out scope.

Thanks & Regards,
Rupesj

**Comment by rubendel** [comment]
No idea what you are talking about

**Comment by rupeshvirat** [comment]
Hello,

You need to check your program page on  bugcrowd
