### ISSUE TITLE
JSON: Unable to extract IfcWalls from the model (ServiceInterface.download)

### ISSUE THREAD

**Issue by usmannn** [opensourceBIM/BIMserver#1055]
version 1.5.162

Hi, I'm not sure if this is the right forum to ask this but I am trying to query walls from an IFC model using JSON. Here is what I have got:

Console Application QUERY:

{
  "token": "9f8092e7f37a329352ad2dc08604d2f1b93449787ce90269a6b3cb5f2ba06d5fbc68eb74e82f43446d470f7b5fe0f22e",
  "request": {
    "interface": "ServiceInterface", 
    "method": "download", 
    "parameters": {
      "roids": ["65539"],
      "query": "{ 'type': { 'name': 'IfcWall', 'includeAllSubTypes': true } }",
      "serializerOid": 196646,
      "sync": "false"
    }
  }
}

RESPONSE:

{
  "response": {
    "result": 20
  }
}

ROID is obtained from the response after checkin the IFC file to the server
serializerOid is obtained by calling getSerializerByContentType("application/json")

Am I doing something wrong in here?

**Comment by rubendel** [comment]
I don't think anything is going wrong here (but a copy-paste from the BIMserver log would help if there are any errors). You can use the result (the number 20 in this case) with any of the download methods.

You can use either `ServiceInterface.getDownloadData` or the DownloadServlet (`/download`) to download the actual serialized content.

**Comment by usmannn** [comment]
Have already tried sending GET request hoping to get the serialized content like this:

http://localhost:8082/download?token=9f8092e7f37a329352ad2dc08604d2f1b93449787ce90269a6b3cb5f2ba06d5fbc68eb74e82f43446d470f7b5fe0f22e&topicId=20

but nothing in response.

![image](https://user-images.githubusercontent.com/11565137/68686594-db600800-0539-11ea-9a98-a59a5d2aec9e.png)

**Comment by rubendel** [comment]
Anything in the BIMserver log file?

**Comment by usmannn** [comment]
So I queried getServerLog(). Response output is attached in the file.
[log.txt](https://github.com/opensourceBIM/BIMserver/files/3837039/log.txt)

**Comment by rubendel** [comment]
Got it (you could too if you read the log file): Single quotes are not allowed in JSON.

**Comment by usmannn** [comment]
Oh, I noticed this from the WIKI page (not from the log). But with double quotes, the response says "Invalid JSON"

![image](https://user-images.githubusercontent.com/11565137/68688285-7b1e9580-053c-11ea-9c43-0638028431be.png)

**Comment by usmannn** [comment]
Okay so I have figured it out. First, you were right about the quotes. Needed to add backslashes with the quotes in the query like this: `{   \"type\": {     \"name\": \"IfcWall\",     \"includeAllSubTypes\": true   } }`

I am able to get the response from the GET ~/download request now.

Now, a wall object in the response looks like this:

`{
            "_i": 263031,
            "_u": "4df45ec9-4bfb-4e2b-9d7d-36906401c40c",
            "_r": "1",
            "_t": "IfcWallStandardCase",
            "_s": 1,
            "GlobalId": "0KJoyEs7n3vfBhsEocHNQx",
            "_rOwnerHistory": {
                "_i": 66374,
                "_t": "IfcOwnerHistory"
            },
            "Name": "Basic Wall:Generic - 200mm:360236",
            "_rHasAssociations": [
                {
                    "_i": 328222,
                    "_t": "IfcRelAssociatesMaterial"
                }
            ],
            "ObjectType": "Basic Wall:Generic - 200mm:249",
            "_rIsDefinedBy": [
                {
                    "_i": 262623,
                    "_t": "IfcRelDefinesByProperties"
                },
                {
                    "_i": 66036,
                    "_t": "IfcRelDefinesByType"
                }
            ],
            "_rObjectPlacement": {
                "_i": 393598,
                "_t": "IfcLocalPlacement"
            },
            "_rRepresentation": {
                "_i": 262561,
                "_t": "IfcProductDefinitionShape"
            },
            "_rgeometry": {
                "_i": 132968,
                "_t": "GeometryInfo"
            },
            "Tag": "360236",
            "_rConnectedFrom": [
                {
                    "_i": 65937,
                    "_t": "IfcRelConnectsPathElements"
                },
                {
                    "_i": 131473,
                    "_t": "IfcRelConnectsPathElements"
                }
            ],
            "_rContainedInStructure": [
                {
                    "_i": 66097,
                    "_t": "IfcRelContainedInSpatialStructure"
                }
            ]
        }`

So how do I interpret it? For example, I am interested in know the start and end points (XYZs) of that wall.

**Comment by usmannn** [comment]
I think it has to do with "serializer". May be I need to use some geometry serializer.

**Comment by usmannn** [comment]
Okay so I have started getting some coordinate information by adding `"includes": ["ifc2x3tc1-stdlib:ObjectPlacement" ]` in the query. 
Full query looks like: `{ "type": { "name": "IfcWall", "includeAllSubTypes": true}, "includes": ["ifc2x3tc1-stdlib:ObjectPlacement" ] }`

and I am using **"Json (Streaming)"** serializer. Still not sure which serilizer to select. My IFC file is Ifc2x3 though.

Query result is attached in a txt file. How do I interpret it to extract let's say the end points of the wall. Assuming it's a simple axis aligned wall, I would like to know start (XY) and end (XY) positions of the that wall.

[query_result.txt](https://github.com/opensourceBIM/BIMserver/files/3837483/query_result.txt)

**Comment by usmannn** [comment]
Turns out that I need to explicitly ask for the geometry in my request. The response wouldn't have any geometry information if not asked for. Here is the query I am using:

```
{
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "include": {
    "type": {
      "name": "IfcWall",
      "includeAllSubTypes": true
    },
    "field": "geometry",
    "include": {
      "type": "GeometryInfo",
      "field": "data"
    }
  }
}
```
The above query is working fine and I am able to extract wall geometry (e.g. min/max bounds). 
Just wondering if there is any other robust way of doing this?

**Comment by usmannn** [comment]
I think I am getting closer. Bumped into another issue:

I am calling the **Download** method from a HTTP request with the following query:

```
{
  "token": "9f8092e7f37a329352ad2dc08604d2f1b93449787ce90269a6b3cb5f2ba06d5fbc68eb74e82f43446d470f7b5fe0f22e",
  "request": {
    "interface": "ServiceInterface",
    "method": "download",
    "parameters": {
      "roids": [
        "589827"
      ],
      "query": "{\"type\": {\"name\": \"IfcWall\",\"includeAllSubTypes\": true},\"include\": {\"type\": {\"name\": \"IfcWall\",\"includeAllSubTypes\": true},\"field\": \"geometry\",\"include\": {\"type\": \"GeometryInfo\",\"field\": \"data\"}}}",
      "serializerOid": "262182",
      "sync": "false"
    }
  }
}
```

But I am getting an exception in the response:

```
{
  "response": {
    "exception": {
      "__type": "ConvertException",
      "message": "Missing __type field in {"type":{"name":"IfcWall","includeAllSubTypes":true},"include":{"type":{"name":"IfcWall","includeAllSubTypes":true},"field":"geometry","include":{"type":"GeometryInfo","field":"data"}}}"
    }
  }
}
```

Not sure why?

**Comment by usmannn** [comment]
Fixed. Needed to encode query to base64.

**Comment by usmannn** [comment]
So here is the thing, when I am requesting Wall geometry through "Postman" utility it's working fine. And in the second step, using the topicId, I am able to get the geometry.

However, the same request when being send from a C# application, resulting in a topicID which isn't producing any output. Response from the second step (GET resquest) is empty. 

The only difference is that in the Postman utility, I am using the query without encoding, whereas in .Net application, it's encoded in base64.

**Comment by usmannn** [comment]
Turns out that the issue was with quotes.

**Comment by rubendel** [comment]
For clarification, the reason why the query part of the request has to be a String and cannot just be a continuation of the JSON structure of the API request is that the whole BIMserver API has to be available as both JSON/SOAP/ProtocolBuffers. Because of that the whole API has to be typed/strict and cannot be dynamic (which the queries are). Hope that makes sense.
