### ISSUE TITLE
The homepage for bimserver.org is down

### ISSUE THREAD

**Issue by sigurdne** [opensourceBIM/BIMserver#1056]
Seems to have been down for some days now
https://www.isitdownrightnow.com/bimserver.org.html

Regards

**Comment by qwer1324** [comment]
Yeah already send them a mail about that, didnt got a response yet...
Following Sites are down too:
- http://bimsurfer.org
- http://www.opensourcebim.org/

**Comment by qwer1324** [comment]
- http://bimserver.org/ is up again

http://bimsurfer.org and http://www.opensourcebim.org/ are still down
