### ISSUE TITLE
Sequence of objects displayed incorrectly IFC2X3 

### ISSUE THREAD

**Issue by cvc-ru** [opensourceBIM/BIMserver#1057]
In the attached file is the forest belt along the road. This is the line along which 3 different 3DS tree models are regularly repeated.
![F1](https://user-images.githubusercontent.com/48197753/69042870-03041400-0a03-11ea-91f2-03051905e563.JPG)
Autodesk Navisworks and BIM Vision show the entire forest belt.
![f2](https://user-images.githubusercontent.com/48197753/69042881-07c8c800-0a03-11ea-8ebf-433b3e9b6ded.JPG)

BIMServer shows only one tree at a time, without repeating them along the line of the forest belt.
![F3](https://user-images.githubusercontent.com/48197753/69042999-42326500-0a03-11ea-9724-2e2169a70a34.JPG)
Please fix.

IFC file:
[bug.zip](https://github.com/opensourceBIM/BIMserver/files/3857991/bug.zip)

**Comment by rubendel** [comment]
I can reproduce this in BIMserver 1.5.177-SNAPSHOT. I have "fixed" it in BIMserver locally just to see what would happen, it seems as though IfcOpenShell also has a hard time with it.

The problem seems to be that there are multiple IfcRepresentation objects with the RepresentationIdentifier "Body" linked in a single IfcProductRepresentation. Looking at the spec this seems to be valid, but I don't think it is very common.

Will post more after consulting with the developer of IfcOpenShell.

Regardless of whether this is valid, I think a nicer export would create one IfcProduct per tree, and reuse the geometry for equal trees.

**Comment by rubendel** [comment]
After consulting with @aothms, the main developer of IfcOpenShell, our conclusion is that the IFC file is indeed **invalid**. There are multiple IfcProducts referring to the same IfcLocalPlacement, which is prohibited by the standard [1]. That could also be the reason why Solibri is also unable to open this file.

That is not to say that this file would work if the above mentioned fault was fixed. IfcOpenShell will not support multiple `IfcRepresentation` with the same `RepresentationIdentifier` linked to the same `IfcProductRepresentation`, and therefore BIMserver won't be able to come up with the "correct" geometry.

For now, I won't commit my fix to support this, as there is no point. If we come across this issue more times, we'll re-evaluate this decision. For now, the best option would be to persuade GeometryGym to reorganize the exporting code to align more with mainstream IFC usage, as there are plenty ways to correctly export this model.

[1] http://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcgeometricconstraintresource/lexical/ifcobjectplacement.htm

**Comment by hlg** [comment]
Even though reuse of placements is definitely prohibited in IFC2x3, the cardinality has been relaxed in IFC4 [1]. I am looking at the file and specification in detail, because I suspect the splitting of representation items of the same identifier, type and context across different representations might not be allowed.

[1] http://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcobjectplacement.htm

**Comment by hlg** [comment]
Unfortunately, there seems to be no formal proposition stating this, but taking together all the definitions and semantics it boils down to have all items of one context grouped in one representation of a product. (In valid IFC, representation contexts map uniquely to a combination of representation identifier and type.)

1. For `IfcProductRepresentation.Representations` we have the following definition: _Each member defines a valid representation of a particular type within a particular representation context._ So, each representation should be a full representation of the product. If you have multiple representations, semantically they are alternatives, not components.

2. Each alternative representation pertains to a specific representation context. And representation items should be grouped in representations by the context they belong to. This is specified in ISO 10303-43 were the IFC spec refers to and draws the definition of `IfcRepresentation` from: _A representation is a collection of one or more representation items that are related in a specified representation context. The relationship of representation item to representation context is the basis for distinguishing which representation item entities are related._

For the given example, even if not invalid, the IfcOpenShell interpretation to use only one of the representations seems legit. If this is not what you want, there are two options to fix:

-  a) As Ruben suggested, each occurrence of a tree could be a separate product (with one representation and one representation item).
-  b) Each group of trees stays one product, but all representation items for the single trees in one group are combined in a single representation ([example attached](https://github.com/opensourceBIM/BIMserver/files/3878969/forest.zip)).

If you would want to break down one shape representation into parts with different function without introducing additional products, you could use `IfcShapeAspect`. But this is not applicable here. Here we have no aspects, but a mere aggregation of equal parts.

I still try to get hold of ISO 10303-43 to find more evidence and also take this to the buildingsmart formus to confirm.

**Comment by cvc-ru** [comment]
Thanks for the consultation! The developers redid the export model. Now all the trees and the road fence are displayed in BIMserver.
But the display quality is terrible.
![s-bimserver](https://user-images.githubusercontent.com/48197753/71541110-c95cec00-2964-11ea-91bc-9433a8d219af.JPG)
 And in other programs - a normal picture(BIM Viewer).
![s1](https://user-images.githubusercontent.com/48197753/71541101-b9450c80-2964-11ea-8c9e-5c26d013552b.JPG)
Tell me - can this be fixed?
The ifc model in the archive is attached.
[bug2.zip](https://github.com/opensourceBIM/BIMserver/files/4006861/bug2.zip)

BIMserver ver  1.5.180

**Comment by rubendel** [comment]
I can confirm this is also what it looks like in BIMserver HEAD with BIMvie.ws. However, this is what the same model looks like in BIMsurfer 3 (with BIMserver HEAD):

![image](https://user-images.githubusercontent.com/377978/71575724-639c6b80-2aee-11ea-968d-64fdb50f2d48.png)

So I don't think this is a BIMserver problem, but more a BIMsurfer V1 problem, please create a new issue on the BIMsurfer V1 issue tracker.
