### ISSUE TITLE
Support for BCF editing

### ISSUE THREAD

**Issue by number133** [opensourceBIM/BIMserver#1060]
**Describe the bug**
Is it possible to add BCF editing for GUI? How can it be done if possible?

**Comment by rubendel** [comment]
Sure everything can be done, just hire a developer and explain what you want. It is however not something that will be done in BIMserver, as BIMserver is a "Server", not a GUI.

**Comment by number133** [comment]
I understand that. I just wanted some pointers we can possible work with.
Are there ways BIMsurfer or BIMvie.ws can be extended? 
Or can it be done as a plugin or through API from another app?

**Comment by rubendel** [comment]
BIMvie.ws is not designed to be extended, both from a technology point of view (it's technology stack is most definitely not somethings you'd want to build on these days (JQuery, pre-EcmaScript 6 syntax, etc...)) as functional wise (it's meant to be demo of what can be done with the BIMserver API, not to be an end-user application).

BIMsurfer is also not designed to be extended, but it is designed to be embedded. BIMsurfer however does not know anything about the semantics of IFC models, it only bothers with geometry.
