### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by sotlog** [opensourceBIM/BIMserver#1068]
How can I connect a cms with the bimserver so that i can display the ifc models on my site. Is there any code in php or html that shows online the ifc model that is stored to bimserver?

**Comment by rubendel** [comment]
If by "displaying the model" you mean showing the 3D representation, you can use https://github.com/opensourceBIM/BIMsurfer for that. It comes with HTML examples.

Keep in mind though that implementing this with BIMserver does require a bit of effort on your part, which, judging on the effort that went into this issue title, might not be sufficient.

**Comment by jorgeluisacostaalonso** [comment]
Hello @rubendel  I take this opportunity to do my question!

+ BimSurfer allows users to show only a piece of the IFC model.
   What are searching to do is to show only selected occurence from a website without download the entired IFC model

Thanks in advance!!!

**Comment by rubendel** [comment]
Please don't hijack issues.
