### ISSUE TITLE
Get properties of objects

### ISSUE THREAD

**Issue by stoneman14** [opensourceBIM/BIMserver#1069]
Hello, I would like to have a little information:
What is the easiest way to retrieve the properties of objects (like a door)?
I created properties in Revit for objects. Then I exported my project in IFC format. So I have my properties in my IFC file, so I made several requests to get the objects and then several requests "getReferences" until the desired properties.
I work with BimSurfer and BimServerAPIJavascript

Is there an easier method?

thank you in advance

cordially

**Comment by GiacomoManzoli** [comment]
You can try with the query interface.

This one loads all the `IfcObject`s with their properties and quantities with just one request, but you have to do some processing on the returned data in order to associate every object with its properties/quantities.

```json
{
    "includes": [
        {
            "type": {
                "name": "IfcObject",
                "includeAllSubTypes": true
            },
            "fields": ["IsDefinedBy"],
            "includes": [
                {
                    "type": "IfcRelDefinesByProperties",
                    "fields": ["RelatingPropertyDefinition"],
                    "includes": [
                        {
                            "type": "IfcElementQuantity",
                            "fields": ["Quantities"]
                        },
                        {
                            "type": "IfcPropertySet",
                            "fields": ["HasProperties"]
                        }
                    ]
                }
            ]
        }
    ]
}
```
