### ISSUE TITLE
Help! For some ifcfiles, info from server says rendertime is very very long.

### ISSUE THREAD

**Issue by snowxinyu** [opensourceBIM/BIMserver#1070]
Maybe I can send the file via email for debugging.

**Comment by rubendel** [comment]
Sure, you can send your IFC file to ruben@logic-labs.nl

**Comment by snowxinyu** [comment]
E-mail sent. Looking forward to feedback to the result.

**Comment by rubendel** [comment]
Thanks, the particular file you sent processed in 3 minutes on my machine, which I think is acceptable, but probably does not scale to 10x or 100x models. There was one IfcBuildingElementProxy that took about 2:30, this one resulted in 75.008 triangles. That is quite a lot, but not unusual. Unfortunately BIMserver (and IfcOpenShell) do not parellellize below the IfcProduct level, so we cannot take advantage of multiple cores for large individual objects. Hence during 2:30 only one core was utilized.

If you do not require quantities to be calculated, you can disable them. For this model, the processing time went down quite a bit to 33 seconds, maybe that works for you. If you are interested in an analysis of one of your bigger models, feel free to sent those as well.

See: https://github.com/opensourceBIM/BIMserver/wiki/How-to-disable-quantity-generation

**Comment by snowxinyu** [comment]
I run BIMServer in  VM and it took 5min+. Another IFC file has been sent. This time that file took about 7:30 without calculating  quantities.

**Comment by rubendel** [comment]
About 7 minutes here too.
Biggest objects:

678.168 triangles: 6:45
490.244 triangles: 4:28

Memory usage was pretty high here too, about 11G for the biggest object.

![image](https://user-images.githubusercontent.com/377978/70332059-0986ee00-1841-11ea-85e7-9004862614b3.png)

At the moment there is not much we can do about it as we depend on IfcOpenShell. You might want to make sure that for models with even bigger objects your system has enough memory, as soon as disk swapping kicks in you're done.

**Comment by snowxinyu** [comment]
7 minutes is acceptable.
Unfortunately, one file which contains a large number of repeated representation took 23m 16s without calculating quantities. 
ps: INFO "Reused(by mapping): 131.55 GB". 
And one project contains many models like this. Maybe, batch processing on the server is a better solution for user.
Thanks very much for your work. I will do some work to figure out that is there a way to optimize.

**Comment by rubendel** [comment]
Wow, at least the 131.55 GB is reused :) How much is the final size in that case? If you only use the geometry for visualization, I think there should be a faster and less memory-heavy way to calculate this, but it might have to be done without IOS.
