### ISSUE TITLE
Help! IFC model dislocation 

### ISSUE THREAD

**Issue by MouMouDe** [opensourceBIM/BIMserver#1074]
**Describe the bug**
Component dislocation of IFC file in graphics platform

**To Reproduce**
IFC file（Pipes and elbows） with shared coordinates exported from Revit，which may lead to component dislocation in the graphics platform. Excuse me, how to deal with it?

**Expected behavior**
Normal connection of pipe and elbow

**Screenshots**
![image](https://user-images.githubusercontent.com/20085822/71060712-302e1880-21a1-11ea-83a6-9e4be5be856f.png)

**Additional context**
IFC file（Pipes and elbows） without shared coordinates  exported from Revit can be displayed normally

**Comment by rubendel** [comment]
Both files load fine here in the latest version of BIMserver and viewers. Which version of BIMserver are you using and which version of which "graphics platform"?

**Comment by MouMouDe** [comment]
Sorry,I haven't checked my mailbox recently!
Thank you very much for your help，We have two graphics platforms, 
one is based on bimserver（1.5.99）and viewers based on Autodesk after secondary development ,
the other is based on  python using ifcopenshell to parse IFC files.
the two both had the same problem 
Would you mind giving me a copy of the data you parsed based on the Two IFC files I gave you before？such as transform,bounds_boxing,colors,verts,normals,indices......
Best wishes to you!










At 2019-12-19 20:01:55, "Ruben de Laat" <notifications@github.com> wrote:

Both files load fine here in the latest version of BIMserver and viewers. Which version of BIMserver are you using and which version of which "graphics platform"?

**Comment by rubendel** [comment]
Sorry that's a bit too much work outside the realm of BIMserver support. You could use a more recent version of BIMserver.

**Comment by MouMouDe** [comment]
Maybe can you send me the graphic files of these two IFC files










At 2020-01-06 16:05:26, "Ruben de Laat" <notifications@github.com> wrote:

Sorry that's a bit too much work outside the realm of BIMserver support. You could use a more recent version of BIMserver.
