### ISSUE TITLE
Can’t use download with a "MessagingSerializerPlugin" .

### ISSUE THREAD

**Issue by KevinFournier** [opensourceBIM/BIMserver#1075]
Hello,

### Context

- I am using Unity3D and I am trying to get data from BIMServer.
- I am just trying to get the data, not to display 3d object, for now.
- I am using serializer plugins available with the installation of BIMServer (Ifc2x3tc1, gltf, binarySerializers, json, etc.).
- I am using C# and I request BIMServer with the json API.
- I had no problem to download data with those serializers :
  - ifc2x3tc1--> get a readable ifc file
  - gltf 2 --> get a readable glb file
  - json (with and without geometry)

### Problem

Just before beginning I use the convention below to differentiate the types and methods I talk about in the issue :
_json api methodes_
**Classes**
**_Interfaces_**

I tried different download from the server using the _ServiceInterface.download_ query from the api.
I used different serializers based on the response from the _PluginInterface.getAllSerializers_.

It works well but not with the **BinaryGeometryMessagingSerializer(Plugin)**; an exception is raised inside the [**DownloadByNewJsonQueryDatabaseAction** class (line 94)](https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/database/actions/DownloadByNewJsonQueryDatabaseAction.java), where a cast is done.
It is because here, the plugin referenced inside the download query is cast as a **_SerializerPlugin_** but the **BinaryGeometryMessagingSerializerPlugin** does not implement it, it implements **_MessagingSerializerPlugin_**. 

I understand that those interfaces are two different type of plugin but in the api a request to _PluginInterface.getAllSerializers_ return the **BinaryGeometryMessagingSerializer** (and its streaming version).
I found out that a call to _PluginInterface.getAllSerializerPluginDescriptors_ does not return the descriptor for implementation of **_MessagingSerializerPlugin_** so it is possible to filter the serializer.

Despite that, I still have few questions:
- The _ServiceInterface.download_ query should return an error when not using an **SerializerPlugin**, shouldn’t it?
- Is there any other mean to get data from a **_MessagingSerializerPlugin_** through download ?

Note that I just start using BimServer. Excuse me if I misunderstood something.

Kévin F.

**Comment by hlg** [comment]
Is this still an issue?

**Comment by hlg** [comment]
It took me a second read and a look into the source code, but this is actually an issue and the OP  is correct in asking for a proper error message or acceptance of a `BinaryGeometryMessagingSerializer` OID as parameter to the `ServiceInterface.download` method. You can actually pass the streaming version `BinaryGeometryMessagingStreamingSerializer` and it will be processed correctly - BIMsurfer does this, for example. Just the non-streaming is not consumed well.

**Comment by hlg** [comment]
Sorry for the back and forth, but I just realized that the `BinaryGeometryMessagingSerializer` plugin is already deprecated. Thus we will only fix this with a respective error message.
