### ISSUE TITLE
inBoundingBox property for BBox overlap

### ISSUE THREAD

**Issue by JPVOAGC** [opensourceBIM/BIMserver#1076]
Hi there,
I have been playing with inBoundingBox property and it works well for returning objects that are completely within the 3D Box. In doing this I cannot extract large objects like ifcSlab.
Is there a way to select object with BBOX [overlap](https://en.wikipedia.org/wiki/Spatial_relation)/intersect ?
I'm running BIMServer 1.5.172. thanks for your help.
Regards,
.JP

**Comment by JPVOAGC** [comment]
`partial: true` works great for me. Thank you very much for your quick answer.

**Comment by JPVOAGC** [comment]
One more thing: is there a possibility to cut object geometries at the limit of the bounding box?

**Comment by rubendel** [comment]
Nope, the query language can only filter data, not modify it
