### ISSUE TITLE
Hard delete project on BIM server 1.5

### ISSUE THREAD

**Issue by JPVOAGC** [opensourceBIM/BIMserver#1077]
Hello,
In my understanding, any delete of project or subproject is "soft" and never get entirely removed from the DB. When deleting a project you can never recreate one with the same name.
Is there a way to clean deleted project and remove all existance of its data and history? 

Thank you for your support

**Comment by rubendel** [comment]
No, there have been multiple issues about this, it's not supported.

**Comment by aurelien-gille** [comment]
Hi,
If it's just a naming issue for your next projects can't you rename your project ? Like rename ProjectName->ProjectNameDeletedAtTIME before deleting it.
It won't reduce your database size but you'll be able to recreate a new project ProjectName

**Comment by JPVOAGC** [comment]
OK I implemented a rename. What would you recommend to reduce database size? Is there an archiving system? Thanks

**Comment by JPVOAGC** [comment]
Rename will do the job. Thanks

**Comment by Chris-12** [comment]
Hello JPVOAGC, did you implement a rename project on the trunk, or did you do it on your own ? 
Regards,
Chris

**Comment by JPVOAGC** [comment]
Hello, I implemented a rename. I didn't want to dive into the implementation of a hard delete with berckley DB.

**Comment by Chris-12** [comment]
Hello,
At which level did you implemented it ? Is it sharable ?
Regards,
Chris

**Comment by Chris-12** [comment]
Ho, May be you used ServiceInterface.updateProject ?

**Comment by hlg** [comment]
Yes, `ServiceInterface.updateProject` will do the trick.
