### ISSUE TITLE
Q: Startup Paramters for the JAR Starter

### ISSUE THREAD

**Issue by qwer1324** [opensourceBIM/BIMserver#1078]
Hello Guys,
Just a question **not a issue**:
Is there a way to start the "JAR Starter" with parameters?
I want the BIMServer to start at the Startup of my Server in case it went down.
I dont want to open "Issues" for Questions is there a Forum for this Project?

Greetings Steffen

**Comment by rubendel** [comment]
That is what the WAR is for, the JAR is just for evaluation purposes. The WAR you run in an application container like Tomcat, which has init scripts on most OSes.

In this project, it's fine to create issues for questions.

**Comment by qwer1324** [comment]
Ahh ok Thank you @rubendel <3
