### ISSUE TITLE
BIMServer War 1.5.180 setup failed at plugin installation 

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#1080]
**Describe the bug**
installation of 1.5.180 war package produced packages not found errors

**To Reproduce**
1. install war file for 1.5.180 in tomcat.
2. open the setup page
3. configure the setup to finish.

**Expected behavior**
no installation errors.

**Screenshots**
<img width="1026" alt="Screenshot 2019-12-21 at 8 32 29 PM" src="https://user-images.githubusercontent.com/7524731/71307992-78fc0080-2431-11ea-8f81-547ea92af096.png">

**Additional context**
have tried this on various linux versions and latest mac os

**Comment by tornado96** [comment]
hi, halmsx,  I have the same issue , would you please show me the solution? thx a lot!

**Comment by volubilis** [comment]
Hello I am having the same issue. Your help is welcome

**Comment by halmsx** [comment]
> hi, halmsx, I have the same issue , would you please show me the solution? thx a lot!

> Hello I am having the same issue. Your help is welcome

hey guys. sorry, just noticed your replies... my issue was caused by the changes to maven repo which affected versions 180 and earlier. installing versions 181 and above fixed the problem.
