### ISSUE TITLE
Approache used to add GeometryInfo to genereated IFC specification classes

### ISSUE THREAD

**Issue by MohamedSami95** [opensourceBIM/BIMserver#1083]
Hello,

I was wondering what approach did you use to add, generate and relate the class GeometryInfo to the IFC specification (IFCProduct).

Thank you very much and happy new year.

**Comment by rubendel** [comment]
The steps involved are:
- Add another migration step (in the `org.bimserver.database.migrations.steps` package) with a sequential number. In this migration step you tell BIMserver which schema changes to apply.
- Increase the `Database.APPLICATION_SCHEMA_VERSION` version
- Run `org.bimserver.database.migrations.CodeMigrator`. This will generate most of the new classes, you might have to refresh your IDE's view after this.
- Unfortunately not all files can be regenerated like this, EMF does not allow for it. What you do is go to the BimServer/models folder and open the `models.genmodel` file. You need the EMF plugin for Eclipse which comes with a special viewer for this type file. For the models you have changed, you run "Generate models".
- After this you can start your BIMserver, you'll have to migrate any existing database by typing "migrate" into the console (or use the API call).

Please keep in mind that this whole system exists to keep database migrations working, as soon as you deviate from the main BIMserver branch, it will be hard to apply patches/updates.
