### ISSUE TITLE
How to query property with many values ?

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMserver#1087]
Hello all,
in query 
```
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "properties": {
    "IsExternal": true
  }
}
```
we query for one value but, I cant get to have an expression with many properties values.
Something like the one below returns only last condition :
```
{  "version": 2,
  "properties": {
    "Entity Handle": {
      "Value":"20694F9"
    },
    "Entity Handle": {
      "Value":"20694FF"
    }
  }
}
```
Is there a way to perform so ?
I also have seen there is (or will be) "or" operator, but not available for properties ?
```
{
  or: [{
    type: "IfcWall"
  }, {
    type: "IfcWallStandardCase"
  }]
}
```
Thanks.
Chris.

**Comment by rubendel** [comment]
Sorry, there is no "or" operator yet, maybe in version 3.
