### ISSUE TITLE
  A little doubt   

### ISSUE THREAD

**Issue by jaychou09** [opensourceBIM/BIMserver#1088]
Sorry, the server has been set up, using version 1.5.162. The Java client USES the coordinate 1.5.162 when interacting with each other. What are the parameters in the checkIn method in the BimServerClient? I do not understand, there is no relevant API to explain, better for friendly development

**Comment by shangjieL** [comment]
me too

**Comment by rubendel** [comment]
Make sure to also download the sources, your IDE will then show you the names of the arguments of the methods, which I think are pretty self explanatory.

**Comment by rubendel** [comment]
P.S. for your next issue, please try to describe the problem in short

**Comment by jaychou09** [comment]
its ok
