### ISSUE TITLE
Can't produce a valid IFC with wall opening from query

### ISSUE THREAD

**Issue by JPVOAGC** [opensourceBIM/BIMserver#1089]
I make a query on this file (little house):
[SampleHouse.zip](https://github.com/opensourceBIM/BIMserver/files/4059435/SampleHouse.zip)

`{
  "doublebuffer": true,
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "includes": [
    {
      "type": {
        "name": "IfcWall",
        "includeAllSubTypes": true
      },
      "fields": [
        "IsDefinedBy"
      ],
      "includes": [
        {
          "type": "IfcRelDefinesByProperties",
          "fields": [
            "RelatingPropertyDefinition"
          ],
          "includes": [
            {
              "type": "IfcPropertySet",
              "fields": [
                "HasProperties"
              ]
            }
          ]
        }
      ]
    },
    "ifc2x3tc1-stdlib:ContainedInStructure",
    "ifc2x3tc1-stdlib:OwnerHistory",
    "ifc2x3tc1-stdlib:Representation",
    "ifc2x3tc1-stdlib:ObjectPlacement"
  ]
}
`
On BimViews, the 3D view contains walls with openings for doors and windows:
![Query_Result](https://user-images.githubusercontent.com/49522341/72350599-081dd080-36df-11ea-842d-c28a21a463b1.PNG)

When I use the download button I get this file:
[QueryTest.4.zip](https://github.com/opensourceBIM/BIMserver/files/4059486/QueryTest.4.zip)

With "TeklaBim sight" free viewer I see the walls with no openings. In "Bim Vision" I can't see anything
![IFC_Result](https://user-images.githubusercontent.com/49522341/72350734-49ae7b80-36df-11ea-96df-5106ef487cc5.PNG)

I'm running BIMServer 1.5.172. 
Am I making a mistake in my query? I've tried many other query but I never managed to extract wall with opening.
Thanks a lot for your help.

**Comment by rubendel** [comment]
The reason why this works in BIMvie.ws is because BIMserver stores only one version of the (generated) geometries of objects, and for walls, or other elements with voids, it's always the geometry with the openings removed.

By combining 2 examples available in the BIMvie.ws query tab, you can get to this:
```json
{
  "doublebuffer": true, // Required because there are different paths to the same objects
  "type": {
    "name": "IfcWall", // Query all walls (and subtypes)
    "includeAllSubTypes": true
  },
  "includes": [
    "ifc2x3tc1-stdlib:ContainedInStructure", // These 4 includes make sure the containment hierarchy, owner history (required), Representation (actual geometry definitions) and it's placement are included in the results
    "ifc2x3tc1-stdlib:OwnerHistory",
    "ifc2x3tc1-stdlib:Representation",
    "ifc2x3tc1-stdlib:ObjectPlacement", {
      "type": "IfcWallStandardCase", // For every IfcWallStandardCase, we also follow the openings reference
      "field": "HasOpenings",
      "include": {
        "type": "IfcRelVoidsElement",
        "field": "RelatedOpeningElement",
        "includes": [{
          "type": "IfcOpeningElement",
          "field": "HasFillings",
          "include": {
            "type": "IfcRelFillsElement",
            "field": "RelatedBuildingElement",
            "includes": [
              "ifc2x3tc1-stdlib:ContainedInStructure", // Window/doors and other fillings also have geometry, so we include it here, if you only want the openings and not the filling, leave this out
              "ifc2x3tc1-stdlib:OwnerHistory",
              "ifc2x3tc1-stdlib:Representation",
              "ifc2x3tc1-stdlib:ObjectPlacement" 
           ]
          }
        },    
        "ifc2x3tc1-stdlib:ContainedInStructure", // Openings themselves also have geometry
        "ifc2x3tc1-stdlib:OwnerHistory",
        "ifc2x3tc1-stdlib:Representation",
        "ifc2x3tc1-stdlib:ObjectPlacement" 
        ]
      }
  }]
}
```

It's quite a large query, in a future release we might try to get rid of some duplication.

A smaller example with just the openings removed:
```json
{
"doublebuffer": true,
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "includes": [
    "ifc2x3tc1-stdlib:ContainedInStructure",
    "ifc2x3tc1-stdlib:OwnerHistory",
    "ifc2x3tc1-stdlib:Representation",
    "ifc2x3tc1-stdlib:ObjectPlacement", {
      "type": "IfcWallStandardCase",
      "field": "HasOpenings",
      "include": {
        "type": "IfcRelVoidsElement",
        "field": "RelatedOpeningElement",
        "includes": [
        "ifc2x3tc1-stdlib:ContainedInStructure",
        "ifc2x3tc1-stdlib:OwnerHistory",
        "ifc2x3tc1-stdlib:Representation",
        "ifc2x3tc1-stdlib:ObjectPlacement" 
        ]
      }
  }]
}
```

P.S. for your next issue, please try to format the JSON, so it's more readable.

**Comment by JPVOAGC** [comment]
Thank you very much for this Rubendel! 
If there is any documentation or readings I could do to learn by myself how to query data, please let me know. 
Sorry for the JSON formatting, I'll remember for next time. 
Thanks again.
