### ISSUE TITLE
No plugin bundle available for your version of BIMserver - version

### ISSUE THREAD

**Issue by cr0bis** [opensourceBIM/BIMserver#1092]
When installing the server - tried on versions 1.5.180 and 1.5.162, tomcat 9 and windows..

> Installing bimviews...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews
> 		Installing bimsurfer3...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer3
> 		Installing ifcopenshellplugin...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcopenshellplugin
> 		Installing ifcplugins...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcplugins
> 		Installing binaryserializers...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.binaryserializers
> 		Installing console...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.console
> 		Installing gltf...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.gltf
> 		Installing mergers...
> 		No plugin bundle available for your version of BIMserver: org.opensourcebim.mergers

**Comment by rubendel** [comment]
Could be related to https://github.com/opensourceBIM/BIMserver/issues/1090

**Comment by rubendel** [comment]
Could you try again with the new release? https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.181
