### ISSUE TITLE
bimserverjavascriptapi used cross domain

### ISSUE THREAD

**Issue by mliesmons** [opensourceBIM/BIMserver#1099]
Hi,

I've been searching high and low, but cannot seem to solve my CORS issue when using the javascriptapi from another domain the bimserver is served from.

My Tomcat has its CORS configured to allow any domain, but when https://subdomain1.domain.com/bimserver/json gets called from https://subdomain2.domain.com/bimsurfer3/apps/minimal.html, I get a CORS error, and indeed, the response does not contain an Access-Control-Allow-Origin header.

Anyone an idea how I can make the bimserver API add CORS headers?

Any help greatly appreciated.

Kr,
Michel.

**Comment by rubendel** [comment]
The BIMserver JSON endpoint actually adds the `Origin` of the request to each response its `Access-Control-Allow-Origin`, unless it has specifically been disallowed in the BIMserver settings (which by default none are). So I am pretty sure it's Tomcat that is removing them.

**Comment by mliesmons** [comment]
Hi Ruben,

Thanks for the response.

We installed the latest versions of bimserver (1.5.181), bimsurfer3 (0.0.271) and bimserverapi (0.0.176).

We notice in the web.xml of bimserver a CORS entry:
        <filter>
                <filter-name>cross-origin</filter-name>
                <filter-class>com.thetransactioncompany.cors.CORSFilter</filter-class>
                <init-param>
                        <param-name>allowedOrigins</param-name>
                        <param-value>*</param-value>
                </init-param>
                <init-param>
                        <param-name>allowedMethods</param-name>
                        <param-value>*</param-value>
                </init-param>
                <init-param>
                        <param-name>allowedHeaders</param-name>
                        <param-value>*</param-value>
                </init-param>
        </filter>
        <filter-mapping>
                <filter-name>cross-origin</filter-name>
                <url-pattern>/js/*</url-pattern>
        </filter-mapping>

We entered our origin in the white listed domains: portal-dev.genievision.com:443

Our tomcat has a single CORS filter:
<filter>
  <filter-name>CorsFilter</filter-name>
  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
  <init-param>
    <param-name>cors.allowed.origins</param-name>
    <param-value>*</param-value>
  </init-param>
<filter-mapping>
  <filter-name>CorsFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>

Yet we still get:
Access to XMLHttpRequest at 'https://bimserver-dev.genievision.com/BIMServer181/json' from origin 'https://portal-dev.genievision.com' has been blocked by CORS policy.

Any help greatly appreciated.

Kr,
Michel.

**Comment by mliesmons** [comment]
Hi,

I finally managed to get it working.

Our Tomcat is protected using BASIC authentication.
Turns out that CORS sends a pre-flight OPTIONS request that the server is supposed to answer, and that needs anonymous access.

First thing I had to change was the web.xml of Tomcat to allow OPTIONS to be clled anonymously:
 ```
<web-resource-collection>
  <url-pattern>/*</url-pattern>
  <http-method-omission>OPTIONS</http-method-omission>
 </web-resource-collection>
```

Second I needed to apply CORS responses for all resources /*, not just /js/* in de web.xml of BIMServer:
```
 <filter-mapping>
  <filter-name>cross-origin</filter-name>
  <url-pattern>/*</url-pattern>
 </filter-mapping>

```
Third I needed to add Basic Autherization headers when calling /json and /stream endpoints in bimserverclient.js and bimserverapiwebsocket.js

HTH.

kr,
Michel.

**Comment by mliesmons** [comment]
Hi Ruben,

I tested the latest versions of the Server (182), Surfer (272) and Java Script API (176) in above explained, remote setup.

I notice that the viewer on the server itself manages to render  revision, while the remote solution crashes into debugger at several moments. In the end the model is shown but rotating and zooming does not work.

Below exception returns all the time, any idea what could be the cause?

kr,
Michel.

`TypeError: Cannot read property 'nonce' of undefined
    at FrozenBufferSet.computeVisibleRangesAsBuffers (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\abstractbufferset.js:496:15)
    at TilingRenderLayer.renderBuffer (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\renderlayer.js:557:35)
    at TilingRenderLayer.renderFinalBuffers (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\renderlayer.js:479:11)
    at c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\tilingrenderlayer.js:226:11
    at Octree.traverse (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\octree.js:80:9)
    at TilingRenderLayer.renderBuffers (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\tilingrenderlayer.js:215:16)
    at TilingRenderLayer.render (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\renderlayer.js:455:9)
    at Viewer.pick (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\viewer.js:802:30)
    at Viewer.enableSectionPlane (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\viewer.js:731:23)
    at CameraControl.canvasMouseDown (c:\R\gemineye\ClientPortal\public\bimsurfer3\viewer\cameracontrol.js:151:38)`

**Comment by hlg** [comment]
Is this still an issue?

**Comment by zaqifathis** [comment]
Could you please check if the issue still occurs with the latest BIMserver version (1.5.185)? I will close this issue for now, as we are actively improving the latest version for now. However, feel free to reopen it if the problem persists

**Comment by hlg** [comment]
Thank you for the solution to the original issue, @mliesmons. We may be add this to the documentation. Maybe this could also be contributed as a feature to the [javascript client library](https://github.com/opensourceBIM/BIMserver-JavaScript-API).

The second question is more a [BIMsurfer](https://github.com/opensourceBIM/BIMsurfer) question. There has been quite some development after version 0.0.272 and up to 0.0.273. Maybe it has been resolved. If this still appears again, please post it over there.
