### ISSUE TITLE
Missing elements in 3d model

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMserver#1100]
Hello,

I can show ifc file [tzb_ifc4.zip](https://github.com/opensourceBIM/BIMsurfer/files/4091172/tzb_ifc4.zip) with bim surfer 3 and bim server 1.5.172. In 3d model missing few elements, show images:

BimSurfer3
![tzb_surfer3](https://user-images.githubusercontent.com/44858488/72807559-fb0d5e00-3c57-11ea-92ea-a8af5ccba2ae.PNG)
Solibri
![tzb_solibri](https://user-images.githubusercontent.com/44858488/72807727-517a9c80-3c58-11ea-843e-8b78a8e9132e.PNG)

Thanks for help

**Comment by hlg** [comment]
This issue will be resolved with the next plugin version for IfcOpenShell: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/732da2348c6eaeda446f4d058ad5c94d4a2ce0e5. As an immediate workaround, the engine version can be changed in a running BIMserver instance through the IfcOpenShell plugin's settings. The setting _Commit Sha_ would have to be changed to "3bbdc3f".

**Comment by JanoSlivka** [comment]
This issue is not solved by IfcOpenShell plugin's "3bbdc3f". Elements are still missing.

**Comment by hlg** [comment]
Yes, you are right, even with the very latest IfcOpenShell version (commit SHA 81ad689), there are about 28 entities failing. This seems only partially solved.

**Comment by zaqifathis** [comment]
Tested with the latest IfcOpenShell-BIMserver plugin (commit 179e960). Total about 28 elements/entities (``IfcDuctFitting``, ``IfcDuctSegment``, ``IfcPipeFitting``) are still missing. 


![image](https://github.com/user-attachments/assets/56edab51-17a6-48c8-b7cf-13c17e1d76ac)


and I get this error message from Geometry generation report: 

```
at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:833)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by hlg** [comment]
There is a new issue to include this particular IfcOpenShell setting in the render engine configuration potentially: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/issues/17.
