### ISSUE TITLE
Number of objects in database and geometry generation report

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1102]
Looking at the number of objects per revision, I realized a mismatch between the numbers reported from the database (LowLevelInterface.count) and in the geometry generation report (ifcModel.objects). There seem to be some extra objects in the geometry generation report, for instance the KIT FZK House (IFC4) has 44249 and 44259 objects respectively. For the IFC2x3 version these numbers are 82335 and 82346.

Looking at the code I saw that for the geometry report, apparently the number of lines is used, including header and other non-entity lines. I verified by adding some empty lines which increased the number. I believe this is not a serious issue, but could cause confusion.

**Comment by rubendel** [comment]
Apart from the mentioned IfcPlugins commit, there was another off-by-one bug in BIMserver itself: https://github.com/opensourceBIM/BIMserver/commit/e3e3d98e345b0a279299e3a770aff2d687f26265
