### ISSUE TITLE
Missing geometry on large ifc

### ISSUE THREAD

**Issue by aurelien-gille** [opensourceBIM/BIMserver#1106]
Hello,
I've a large .ifc file where some walls are missing on my N1 storey. (

![0001](https://user-images.githubusercontent.com/1969437/74140773-079d2a80-4bf6-11ea-8b78-1249e695eabb.PNG)

I've splitted the file with the IFC Split add-on for Bim Vision to have this storey only and reloaded it on bim server and the walls appear on the smaller ifc. 

![0002](https://user-images.githubusercontent.com/1969437/74140775-08ce5780-4bf6-11ea-99ad-a0f58c28608f.PNG)

I tried to reload the geometry with and without the server setting "**Geometry reuse**" and "**Optimize mapped items**" 

BimServer 1.5.182
IfcOpenShellPlugin 0.5.91
Files : [CA BimServer.zip](https://github.com/opensourceBIM/BIMserver/files/4180271/CA.BimServer.zip)

**Comment by rubendel** [comment]
Thanks for sending the IFC files. Currently I am not able to replicate this. A few more questions:
- When uploading (the full model) multiple times, do you see exactly the same output?
- When you are missing entities, could you have a look at the JavaScript console to see whether any errors are reported?
- Could you perhaps try BIMsurfer 3 and see whether this shows the same geometry? This will help in figuring out whether this is a viewer or a BIMserver issue.

**Comment by aurelien-gille** [comment]
> When uploading (the full model) multiple times, do you see exactly the same output?

I tried multiple times and on other stations (VM included) There's a lot of object (I can miss some) but it seems missing parts are the same every time

> When you are missing entities, could you have a look at the JavaScript console to see whether any errors are reported?

`11:02:32 INFO  [pool-1-thread-1]: Pool size: 7                                                                     (CommonsRenderEnginePool.java:37) 
11:06:17 INFO  [pool-1-thread-1]: Rendertime: 03m 45s, Reused (by hash): 1,08 MB, Reused (by transformation): 0 B, Reused (by mapping): 124,03 MB, Total: 220,13 MB, Final: 95,02 MB (StreamingGeometryGenerator.java:655) 
11:06:17 ERROR [pool-1-thread-1]: [CA AIA FULL.2.ifc] Number of erroneous files: 3                                 (StreamingGeometryGenerator.java:657) 
11:06:17 WARN  [pool-1-thread-1]: [CA AIA FULL.2.ifc] Number of representations skipped:                           (StreamingGeometryGenerator.java:661) 
11:06:17 WARN  [pool-1-thread-1]: 	FootPrint: 3                                                                    (StreamingGeometryGenerator.java:663) 
`

>Could you perhaps try BIMsurfer 3 and see whether this shows the same geometry? This will help in figuring out whether this is a viewer or a BIMserver issue.

BIMsurfer suffer more missing geometries : 
![aia](https://user-images.githubusercontent.com/1969437/76514046-943a4300-6457-11ea-9028-e7e033bc927f.jpg)

**Comment by rubendel** [comment]
Thanks, and the Java**Script** consoles? Could you post the GUID of a specific element that is always missing?

**Comment by aurelien-gille** [comment]
Oh sorry, 

```WebSocket closed 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
-bimserverapiwebsocket.js:148:11

Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». 
-bimviews

unreachable code after return statement 
-scenejs.js:11108:8

Connecting websocket bimserverapiwebsocket.js:22:11
preloadModel 65539 : 5871 ms - chronomètre arrêté
- bimviews.js:325:14
```

IfcWallStandardCase "**2v7LmBOHXCDuoKJhbAvQeN**" is missing (seems to be present on the browse tab but without geometry)

**Comment by rubendel** [comment]
Hmm, so far I have no idea, this is what I see here for the specific GUID:
![image](https://user-images.githubusercontent.com/377978/76518488-753faf00-645f-11ea-8eae-ceef78540ccd.png)

**Comment by aurelien-gille** [comment]
Could it be a parameter based problem ? (Heap Size / "Geometry generation" settings / Plugin version) ?

**Comment by aurelien-gille** [comment]
When reloading the project (I still need to make the full size project to work the one with only one storey has no use for me) I search a bit more on the report side and find 3 ifc files générated on checkin alongside the generationreport.

I can't open them on any ifc viewer. Even on BimView, the checkin work, it generate geometry buy I can't use the 3D panel.
Note : the 3d component include on every object on the "Browse" panel seems to work

[2020-03-31-15-52-53 (AIA_EXE_1--_ARC_--_ZZ_MAQ_000_A.ifc).zip](https://github.com/opensourceBIM/BIMserver/files/4409598/2020-03-31-15-52-53.AIA_EXE_1--_ARC_--_ZZ_MAQ_000_A.ifc.zip)

**Comment by hlg** [comment]
This issue will be resolved with the next plugin version for IfcOpenShell: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/732da2348c6eaeda446f4d058ad5c94d4a2ce0e5. As an immediate workaround, the engine version can be changed in a running BIMserver instance through the IfcOpenShell plugin's settings. The setting _Commit Sha_ would have to be changed to "3bbdc3f" or even "517b819".
