### ISSUE TITLE
Issues with latest Release BIMserver 1.5.162

### ISSUE THREAD

**Issue by Raghavaraman** [opensourceBIM/BIMserver#1108]
**Summary**
When trying to run the latest release, I am unable to install any of the remote plugins. It says No plugin bundle available. If i run the latest pre-release BIMserver 1.5.182 , I am able to download all the plugins. Kindly let me know if the pre-release is stable for continuous use.

**Log of Issue**
```
Setting up...
	Setting up admin account...
		Admin account successfully setup
	Skipping email setup...
	Checking internet connection _from_ your BIMserver...
		Internet connection OK
	Installing all extended data schemas...
		IFC_STEP_2X3TC1 installed OK
		.........
		Extended Data Schemas installed OK
	Installing plugins...
		Installing bimviews...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

		Installing bimsurfer3...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer3

		Installing ifcopenshellplugin...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcopenshellplugin

		Installing ifcplugins...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcplugins

		Installing binaryserializers...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.binaryserializers

		Installing console...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.console

		Installing gltf...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.gltf

		Installing mergers...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.mergers

		All remote plugins successfully installed
```
**Expected behavior**
```
Setting up...
	Setting up admin account...
		Admin account successfully setup
	Skipping email setup...
	Checking internet connection _from_ your BIMserver...
		Internet connection OK
	Installing all extended data schemas...
		IFC_STEP_2X3TC1 installed OK
               ....
		Extended Data Schemas installed OK
	Installing plugins...
		Installing bimviews...
		Successfully installed BIMvie.ws (org.opensourcebim:bimviews:0.0.184)

		Installing bimsurfer3...
		Successfully installed BimSurfer (org.opensourcebim:bimsurfer3:0.0.272)

		Installing ifcopenshellplugin...
		Successfully installed IfcOpenShell-BIMserver-plugin (org.opensourcebim:ifcopenshellplugin:0.5.91)

		Installing ifcplugins...
		Successfully installed IfcPlugins (org.opensourcebim:ifcplugins:0.0.99)

		Installing binaryserializers...
		Successfully installed BinarySerializers (org.opensourcebim:binaryserializers:0.0.93)

		Installing console...
		Successfully installed Console (org.opensourcebim:console:0.0.67)

		Installing gltf...
		Successfully installed Gltf (org.opensourcebim:gltf:0.0.59)

		Installing mergers...
		Successfully installed Mergers (org.opensourcebim:mergers:0.0.65)

		All remote plugins successfully installed
```

**Additional context**
Although the latest pre-release is able to find the plugins in maven, it would be great if the latest release also is able to install the plugins.

**Comment by number133** [comment]
It's related to https://stackoverflow.com/questions/59763531/maven-dependencies-are-failing-with-a-501-error

Links to the maven central used in 1.5.162 aren't supported now.

**Comment by number133** [comment]
I did build bimserver locally from revision 1.5.162 replacing all mentions of http://repo1.maven.org/maven2 and http://central.maven.org/maven2 with https://repo1.maven.org/maven2

**Comment by bewegende-Architektur** [comment]
Hello,

im running into the same issue in bimserverwar-1.5.184.
After increasing the heapsize to 1500 MB, some of the plugins are available.
Is this issue maybe connected to the heapsize?

Greetings,
Chris

**Comment by hlg** [comment]
This issue is about versions: Previously, the last release tagged as "latest" was [v1.5.162](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.162) and it had issues with plugin installation due to changes in Maven. I am tagging the latest minor release as "latest" and the Maven plugin issues should be resolved for those.

@bewegende-Architektur  It may well be, that you run out of memory during plugin installation if your max heap limits are too low, but this is not related to this issue.
