### ISSUE TITLE
JAR and WAR files 

### ISSUE THREAD

**Issue by ihabhamzi** [opensourceBIM/BIMserver#1111]
Dear Sir, 

I cannot find JAR or WAR files to download - is it not available here any more ?

Thanks

**Comment by number133** [comment]
You mean assets from https://github.com/opensourceBIM/BIMserver/releases ?

**Comment by rubendel** [comment]
Latest release: https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.182
