### ISSUE TITLE
Missing element

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#1112]
Hi Ruben,
can you please check why the SilentQube is not displayed. Thanks.
Regards,
Jo
![SilentQube_Solibri](https://user-images.githubusercontent.com/16973608/74952421-8406e900-5400-11ea-8d24-76f7a24b0d13.PNG)
![SilentQube_BIMserver](https://user-images.githubusercontent.com/16973608/74952429-88cb9d00-5400-11ea-9d9b-99333c5f9fb7.PNG)
[SilentQube.zip](https://github.com/opensourceBIM/BIMserver/files/4231668/SilentQube.zip)

[generationreport.zip](https://github.com/opensourceBIM/BIMserver/files/4231671/generationreport.zip)

**Comment by rubendel** [comment]
I can reproduce this. Attached is the IFC subfile that BIMserver generated for just the IfcFurnishingElement. The subfile also works fine in other viewers (which is no guarantee that it's correct). The strange thing is that it opens correctly in Blender with the IfcOpenShell plugin. But IfcConvert throws no errors, but also does not create an .obj file (only a .obj.tmp file).

The geometry looks very simple (although there is a lot of it).

IfcConvert: IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
GeomServer: IfcGeomServer-v0.6.0-b4ce5be-win64.exe

Settings: Layersetslicing and quantity calculation disabled

@aothms Any ideas?

**Comment by hlg** [comment]
This issue will be resolved with the next plugin version for IfcOpenShell: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/732da2348c6eaeda446f4d058ad5c94d4a2ce0e5. As an immediate workaround, the engine version can be changed in a running BIMserver instance through the IfcOpenShell plugin's settings. The setting _Commit Sha_ would have to be changed to "3bbdc3f".
