### ISSUE TITLE
Unable to deploy war file for BIMserver 1.5.177

### ISSUE THREAD

**Issue by maakkoush** [opensourceBIM/BIMserver#1113]
I have downloaded BIMserver1.5.177.zip, then created a war file by trying for both directories, the root and on BIMserverwar subfolder. The war file was created but upon deploying to Tomcat 9.0.31, it deploys properly but when trying to browse the app, I get the following error 

HTTP Status 404 – Not Found

Type Status Report

Message /bimserver15177/

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by halmsx** [comment]
try this version https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.178 and download file bimserverwar-1.5.178.war

**Comment by maakkoush** [comment]
Hi,

I deployed it, but it gets stuck at the loading page
[cid:image001.png@01D5F842.688033E0]

**Comment by rubendel** [comment]
Please provide more information. At least the output in the JavaScript console, and the bimserver.log file.

**Comment by maakkoush** [comment]
Attached as requested.

**Comment by rubendel** [comment]
Please don't respond by email, it does not work with attachments, and makes the issue quite unreadable.

**Comment by maakkoush** [comment]
Hi..attached again..thanks
[bimserver.log](https://github.com/opensourceBIM/BIMserver/files/4323136/bimserver.log)

**Comment by maakkoush** [comment]
I uploaded the log to github

**Comment by rubendel** [comment]
Thank you. So when you open this log file, the first error that appears goes something like this:
```
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
```

If you then subsequently search for this string in the issue tracker, you'll end up at the following issue:

https://github.com/opensourceBIM/BIMserver/issues/1065#issuecomment-559702434

Which is fixed, you just have to use a newer version...
