### ISSUE TITLE
BIMServer Installed Probelm

### ISSUE THREAD

**Issue by 86704463** [opensourceBIM/BIMserver#1117]
**Probelm Describe**
Required dependency net.sourceforge.jexcelapi:jxl is not installed
Required dependency net.java.dev.jna:jna is not installed
When I choose to install the local plug-in, I will have various problems like the above.
version : bimserverjar-1.5.92

**Comment by halmsx** [comment]
hav u tried the latest version?

**Comment by rubendel** [comment]
Closing, too little information provided.
