### ISSUE TITLE
How i can manage the heap issue in the bim server - how i can configure it 

### ISSUE THREAD

**Issue by ihabhamzi** [opensourceBIM/BIMserver#1120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please do not create screenshots of log files etcetera, copy and paste the actual text.

**Additional context**

**Comment by rubendel** [comment]
Do you seriously expect any effort on our side when clearly you don't want to put any effort in it on your side?
