### ISSUE TITLE
add graphic elements dynamically without creating new revision

### ISSUE THREAD

**Issue by fabriceblache** [opensourceBIM/BIMserver#1122]
Hello
I would like to add graphic elements dynamically without creating new revision. I interrogate an external database with a plugin that I have created so I would like to access the model of my BIM to add the graphic elements from the database. How to proceed ?

Best regards,
Fabrice

**Comment by rubendel** [comment]
Do I understand correctly that you only want those graphic elements to be visible in the 3D view? In that case we should move this issue to the corresponding viewer project (please state what viewer you are using).
