### ISSUE TITLE
bimserver now only showing wireframes

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#1124]
**Describe the bug**
it was working well before. all the sudden it starts showing only wireframes. so far cant find errors relating to it in log

**To Reproduce**
1. select a project
2. view the model

**Expected behavior**
supposed to be showing proper model with walls and all.

**Screenshots**
<img width="923" alt="Screenshot 2020-03-11 at 9 35 35 PM" src="https://user-images.githubusercontent.com/7524731/76422648-8695a680-63e0-11ea-918f-6256c717e82d.png">

**Additional context**
bimserver 1.5.182
java 1.8.0_231
chrome latest browser

**Comment by hlg** [comment]
Click the button with the wrench-icon in the upper right (tool tip says "Change between triangles / lines") and reload.

**Comment by halmsx** [comment]
> Click the button with the wrench-icon in the upper right (tool tip says "Change between triangles / lines") and reload.

thanks so much. been using this for 2 years and never noticed this feature!

**Comment by wisoo** [comment]
I reinstalled bimserver at least a dozen times because of this -_-
