### ISSUE TITLE
Model checkers dropped in favor of the new query language?

### ISSUE THREAD

**Issue by orwa84** [opensourceBIM/BIMserver#1125]
On this page here "https://github.com/opensourceBIM/JavaModelChecker" there is an indication that the new query language might be an alternative or as a replacement of the ModelChecker plugin type.

Hence I would like to know if what is called a "query engine plugin" has **replaced** the "model checker plugin"?

Orwa.

**Comment by rubendel** [comment]
No, "Query Engine Plugins" are even older and not supported anymore. The new query/filter language is not implemented as a plugin but it's in BIMserver core. Model Checkers are not actively developed anymore and I think in the future will be removed.
