### ISSUE TITLE
View/compare/merge different revisions of the same IFC model?

### ISSUE THREAD

**Issue by orwa84** [opensourceBIM/BIMserver#1126]
This is not a bug but rather a question.

Using the bimviews frontend, is it possible to view past revisions of the IFC model?

Is it possible to use Model Comparers to compare different revisions?

Last, is it possible to selectively merge two or more revisions using a Model Merger?

In case neither one of these things was possible using the bimviews front-end, would it be possible to do using the API from the Console frontend? If yes, can you describe the function calls required to accomplish any of the above? Thanks a lot.

Regards.
Orwa.

**Comment by rubendel** [comment]
1. Yes, if you are talking about viewing it in 3D. For a project with multiple revisions, click on the little black triangle next to it in the tree and it will show you a context menu with the first option being the revision, simply click another revision at that will be loaded.
2. Yes, but please be advised that the currently implemented Model Compare methods are just examples of how to implement the ModelCompare plugin interface, not production-ready implementations without errors.
3. Yes, same comment applies about the stability. You can simply call the download method with multiple models (roids) and those will be merged with whatever merge plugin you have selected to be the default for the given user.

BIMvie.ws does not supply a free-form selection of models, so 3. is not available, and 2 neither.
