### ISSUE TITLE
Json Serializer

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#1129]
Running Bimserver 1.5.182. Json Serializer seems to be missing. The non streaming variant. 
![NoNonStreamingJson](https://user-images.githubusercontent.com/33512457/76977093-239e9500-6935-11ea-9461-9d0122918f7d.png)

**Comment by rubendel** [comment]
The non-streaming variant has been removed. Is there a specific use-case for using the non-streaming version?

**Comment by motjokk** [comment]
I was using it to get query results in json format. Are the non streaming de-/serializers generaly being removed?

**Comment by rubendel** [comment]
If it depends on me: yes. Unless someone comes up with a specific use case not possible with the streaming ones.

**Comment by motjokk** [comment]
I have no issues with this anymore. And have no good argument for keeping non streaming.
