### ISSUE TITLE
bimviews plugin offline installation failed

### ISSUE THREAD

**Issue by totaljfb** [opensourceBIM/BIMserver#1143]
**Describe the bug**
Failed to install bimviews in offline plugin mode
Reference:
https://github.com/opensourceBIM/BIMserver/wiki/Installing-without-internet-connection

**To Reproduce**
1. deploy bimserver 1.5.182 war file on Tomcat 8.5.42
2. click on bimserver app after the deployment in the Tomcat application manager to start bimserver setup
3. setup the bimserver and go to the Plugins section, uncheck all default checked plugins, click on "upload JAR files of plugins", then select the following jar files:
bimviews-0.0.184.jar
pluginbase-1.5.182.jar
bimsurfer3-0.0.272.jar
bimserverapi-0.0.176.jar
Then click next and click next and then click "Install" 
4. error message is "Failed to collect dependencies at org.opensourcebim:plugin:jar:1.5.182

![1](https://user-images.githubusercontent.com/17803244/84400561-33461680-abd0-11ea-89c4-97860b67fe2c.png)
![2](https://user-images.githubusercontent.com/17803244/84400569-350fda00-abd0-11ea-9d20-5b034f4dfc0c.png)

I checked the bimserver.log it seems the bimserver is still trying to connect internet to collect dependencies even I choose to install in offline mode
[bimserver.log](https://github.com/opensourceBIM/BIMserver/files/4765543/bimserver.log)

**Comment by mikejernil** [comment]
Make sure you have cleared out your 'webapps' folder and only the BIMserver files are present. I encountered this when i hadnt deleted the files that came as default tomcat webapp.

**Comment by totaljfb** [comment]
I added a proxy on JVM and added the maven repository address to the whitelist, the issue has been resolved.

**Comment by fpedeboscq** [comment]
> Thank you @mikejernil I added a proxy on JVM and added the maven repository address to the whitelist, the issue has been resolved.

@totaljfb could you give me some more explanations on how you proceed to add the proxy and the adress to the whitelist on the JVM. I have the same issue. I try to use bimserver with bimvie on ubuntu 16?
