### ISSUE TITLE
NullPointerException on BinarySerializer

### ISSUE THREAD

**Issue by korab8** [opensourceBIM/BIMserver#1145]
So, I finally got it together and up & running. BIMServer with all the plugins. Now I am getting a NullPointerException when loading the 3D view. The model loads, just when I click the little "eye" button it crashes with a NullPointerException.

Below find the full stacktrace:

`13:55:55 WARN  [pool-1-thread-1]: [Duplex.ifc] Number of representations skipped:                                  (StreamingGeometryGenerator.java:661) 
13:55:55 WARN  [pool-1-thread-1]: 	WalkingLine: 2                                                                  (StreamingGeometryGenerator.java:663) 
13:55:55 WARN  [pool-1-thread-1]: 	Boundary: 2                                                                     (StreamingGeometryGenerator.java:663) 
13:56:05 ERROR [pool-1-thread-3]:                                                                                  (BimServer.java:240) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeGeometryData(BinaryGeometryMessagingStreamingSerializer.java:974)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeData(BinaryGeometryMessagingStreamingSerializer.java:771)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeMessage(BinaryGeometryMessagingStreamingSerializer.java:275)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

What could be causing this? I am using BinarySerializers on master branch.

**Comment by korab8** [comment]
Update: If i try and Install the plugins via the BimServer.jar installation process it works just fine. When I try to setup in Eclipse, it shows the same error. I have tried it with different IFCs.

**Comment by bjsolla** [comment]
Hi, I configured BimServer following the installation instructions via wiki (https://github.com/opensourceBIM/BIMserver/wiki/Eclipse),
but when I try to visualize in 3d an ifc file on BIMvie.ws the loading remains
![BIMvie](https://user-images.githubusercontent.com/66369004/86569319-819bca80-bf6e-11ea-8317-ccb3168298e0.jpg)

, and the eclipse console gives me this error
Logging to C:\Hbim3\BIMserver\BimServerJar\tmptestdata\home\logs\bimserver.log
09:20:38 INFO [main]: Starting BIMserver (Windows 10, 1.8.0_191, 64bit, Xmx: 14,89 GB) (BimServer.java:248)
09:20:42 INFO [main]: Version: 1.5.183-SNAPSHOT (BimServer.java:336)
09:20:42 INFO [main]: Using "tmptestdata\home" as homedir (BimServer.java:345)
09:20:47 INFO [main]: No database directory found, creating "tmptestdata\home\database" (BerkeleyKeyValueStore.java:98)
09:20:47 INFO [main]: Successfully created database dir "tmptestdata\home\database" (BerkeleyKeyValueStore.java:101)
09:20:56 INFO [main]: Non-empty database directory found "tmptestdata\home\database" (BerkeleyKeyValueStore.java:87)
09:20:57 INFO [main]: Checking for stale records, this can take some time... (BimServer.java:813)
09:20:57 INFO [main]: Done checking for stale records (17 ms) (BimServer.java:843)
09:20:58 INFO [main]: Changing server state to NOT_SETUP (ServerInfoManager.java:116)
09:20:58 INFO [main]: Initializing database dependant logic... (BimServer.java:1113)
09:20:58 INFO [main]: Done initializing database dependant logic (37ms) (BimServer.java:1284)
09:20:59 INFO [main]: Using overruled system setting for commit sha (IfcOpenShellEnginePlugin.java:101)
09:20:59 INFO [main]: Downloading from https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-b4ce5be-win64.zip (IfcGeomServerClient.java:186)
09:20:59 INFO [main]: Unzipping to tmptestdata\home\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe (IfcGeomServerClient.java:188)
09:21:00 INFO [main]: IfcOpenShell Last Modified: Fri, 05 Jul 2019 03:01:37 GMT (IfcGeomServerClient.java:195)
09:21:02 INFO [main]: Using tmptestdata\home\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe (IfcOpenShellEnginePlugin.java:109)
09:21:02 INFO [main]: Setting default render engine for user system to IfcOpenShell (BimServer.java:1015)
09:21:03 INFO [main]: Setting default render engine for user admin@bimserver.org to IfcOpenShell (BimServer.java:1015)
09:21:03 INFO [main]: Changing server state to RUNNING (ServerInfoManager.java:116)
09:35:32 INFO [pool-1-thread-1]: Pool size: 4 (CommonsRenderEnginePool.java:37)
09:35:49 INFO [pool-1-thread-1]: Rendertime: 17.238s, Reused (by hash): 380,92 KB, Reused (by transformation): 0 B, Reused (by mapping): 0 B, Total: 1,41 MB, Final: 1,04 MB (StreamingGeometryGenerator.java:655)
09:35:53 ERROR [pool-1-thread-2]: (BimServer.java:240)
java.lang.NullPointerException: null
at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeGeometryData(BinaryGeometryMessagingStreamingSerializer.java:974)
at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeData(BinaryGeometryMessagingStreamingSerializer.java:771)
at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeMessage(BinaryGeometryMessagingStreamingSerializer.java:275)
at org.bimserver.servlets.Streamer$1.run(Streamer.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
How can I solve the problem?
Thank you

**Comment by korab8** [comment]
@bjsolla try pulling from the BimSurferV1-Before2019 repository.

**Comment by bjsolla** [comment]
it works
 thank you so much for your help

**Comment by hlg** [comment]
@korab8, has this been solved then?

**Comment by korab8** [comment]
Yes it has been solved
