### ISSUE TITLE
"ifc2x3tc1-stdlib:ContainedInStructure" doesn't seem to work for IfcSpace

### ISSUE THREAD

**Issue by DEPAULISHugo** [opensourceBIM/BIMserver#1154]
The query "ContainedInStructure" works perfectly for most of the types, but it doesn't work for IfcSpace.

To get the IfcSpace objects with their parents, I used the following query :
{
        "type": {
            "name": "IfcSpace",
            "includeAllSubTypes": true
        },
       "include": "ifc2x3tc1-stdlib:ContainedInStructure"
}
But I only get the IfcSpace objects.

Is it possible to get around the problem ?

**Comment by hlg** [comment]
The `IfcSpace` entities are not _contained_ in the structure, but they are _part of_ the spatial structure. In a way, they are usually the leaf nodes of the hierarchical spatial structure. Thus you need to use `ifc2x3tc1-stdlib:Decomposes` to get their spatial decomposition "parents". Only those entities of type `IfcProduct` which are not of the subtype `IfcSpatialStructureElement` can be obtained with `ifc2x3tc1-stdlib:ContainedInStructure`.

**Comment by DEPAULISHugo** [comment]
Thanks a lot for your quick answer ! It really helps me !

Must I close the issue ?

**Comment by hlg** [comment]
Yes, please close it, if it is solved.
