### ISSUE TITLE
Method: getArea

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#1156]
Hi,

The getArea returns the calculated total surface area. 

Largest face area | 54.57
Largest face direction | -2.44122473706858e-17,0,1
Bounding box size along Z axis | 2.50
Bounding box size along Y axis | 4.73
Bounding box size along X axis | 11.55
Surface area along Z axis | 54.57
Surface area along Y axis | 29.15
Surface area along X axis | 12.51
Total shape volume | 136.43
Total surface area | 190.52

To get the area of a IfcSpace, The "Surface area along Z axis" should work well for square meters. But I can not find a way to get it.

Do you think I instead should use QuantityTakeOffAddOnView?

**Comment by hlg** [comment]
You can get it with `ServiceInterface#getGeometryInfo`. There is a field `additionalData` which is a JSON string containing the calculated values. I think whether and how these are populated depends on the geometry engine. From IfcOpenShell you get a value with key SURFACE_AREA_ALONG_Z. With `ServiceInterface#getArea` you only get the total surface area. Of course if your data has it, you can also use GrossFloorArea and NetFloorArea from the Qto_SpaceBaseQuantities property set.

**Comment by motjokk** [comment]
Thank you for clearing this up. Maybe the `getArea()` should be renamed` getTotalSurfaceArea()`.

**Comment by hlg** [comment]
The area property is also populated by the geometry engine. I think I would not prescribe a narrowed meaning by changing the name. If you feel your immediate issue is solved, please consider to close it.
