### ISSUE TITLE
Missing __type field (ConvertException)

### ISSUE THREAD

**Issue by gpierard** [opensourceBIM/BIMserver#1157]
when I try to POST using R and httr, I am getting the following issue:

```
$response$exception$__type
[1] "ConvertException"

$response$exception$message
[1] "Missing __type field in {\"types\":[{\"name\":\"IfcSite\",\"includeAllSubTypes\":true},{\"name\":\"IfcProject\",\"includeAllSubTypes\":true}]}"
```

Is there something wrong with my query? I tried to escape the double quotes with \ but without success. thanks

```
getquery_ <- POST("https://XXXX/bimserver/json",
                    body = '{
  "token":"xxxx",
   "request": {
    "interface": "org.bimserver.ServiceInterface", 
    "method": "download", 
    "parameters": {
      "roids": [xxx],
      "query":{"type":"IfcSite"},
      "serializerOid": xxx,
      "showOwn": true,
      "streaming": true,
      "sync": false,
      "zip": true
    }
  }
}', httr::authenticate(user2, password2, type = "basic"))
content(getquery_)
```

Note that when I change the query string to '{}' it works well.

**Comment by hlg** [comment]
The query itself looks fine. You can use any of the following. (Note that the types specified as JSON objects only really make sense for types that have subtypes, with `includeAllSubTypes`.)

    {"type": "IfcSite"}
    {"types": ["IfcProject","IfcSite"]}
    {"types": [{"name": "IfcProject"}, {"name": "IfcSite"}]}
    {"type": {"name": "IfcSite"}

If you compose the request JSON, you want to include the query as a String, not as a JSON object. Then you need to escape the quotes. Your request payload would look something like this:

    {"token":"xxxx",
     "request": {
        "interface": "org.bimserver.ServiceInterface", 
        "method": "download", 
        "parameters": {
            "roids": [xxx],
            "query": "{\"type\": \"IfcSite\"}",
            "serializerOid": xxx
        }
    }}

**Comment by gpierard** [comment]
Solved it, thanks for the response. In R, you need to DOUBLE escape the marks to forcefully include the escape char in the request. The below works. 

Another thing, no space or newline characters are allowed in the query !!!

```
#see body above, only the query changes
"query":"{\\"type\\":{\\"name\\":\\"IfcProduct\\",\\"includeAllSubTypes\\":true},\\"includes\\":[\\"ifc2x3tc1-stdlib:ContainedInStructure\\",\\"ifc2x3tc1-stdlib:OwnerHistory\\",\\"ifc2x3tc1-stdlib:ObjectPlacement\\"]}",

```

Cheers

**Comment by hlg** [comment]
Good to hear you solved it.

Actually space or newline characters are allowed in the query. But the query has to be a valid JSON string, hence newline must be escaped as `\n`, tabulators as `\t`, literal spaces are fine though. For R, you probably want to double escape, otherwise it will sneak in an unescaped line break and leave you with an invalid JSON string for the query.
