### ISSUE TITLE
Failed to install plugin due to files not existing

### ISSUE THREAD

**Issue by Yasvana** [opensourceBIM/BIMserver#1164]
The plugin installation during the webpage setup failed.

The webpage setup output :
`Installing bimviews...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews
`

The bimserver.log :
`53068 [DefaultMetadataResolver-5-1] WARN  o.e.a.i.i.DefaultUpdateCheckManager - Failed to create parent directories for tracking file /.m2/repository/org/opensourcebim/console/resolver-status.properties
`
I don't know where to check the file.

Where is the configuration for the filepath ?

Thanks in advance.

**Comment by motjokk** [comment]
You have to create a .m2 folder on the root if your filesystem. Tomcat9 is sandboxed by default by Debian. Create a override.conf and give all your folders readwrite access.

**Comment by hlg** [comment]
@motjokk, I can't see whether the OP uses Tomcat9 on Debian.

@Yasvana, which version of BIMserver are you using? How are you running it, from the JAR, WAR or IDE?

**Comment by motjokk** [comment]
> 
> 
> @motjokk, I can't see whether the OP uses Tomcat9 on Debian.
> 

what does OP stand for? output?

**Comment by hlg** [comment]
> what is OP a abbreviation for? output?

OP ~ original post / original poster

**Comment by Yasvana** [comment]
Thanks @motjokk @hlg for your posts.

My environment is :

- Debian
- Tomcat9 installed from debian repository and run with the 'tomcat' user
- War version from the github release page is 1.5.182 and deployed from the tomcat manage page

I will create the folder with rights for user tomcat and update the /etc/systemd/system/tomcat9.service.d/override.conf.

I will let you know the result once done.


BTW, I have another environment where I've changed the tomcat startup script to use a local user instead of 'tomcat', set few tomcat folders rights to give access to the local user. This setup works, but from my point of view, not enough smooth for simple maintenance and scaling.

**Comment by hlg** [comment]
Ok, @motjokk was right. Tomcat9 apparently uses file system root as home folder, which could be seen as an indication.

BIMserver looks for or creates the Maven repository (.m2) in the user's home folder. This folder is configured via the `user.home` system property. If you want to have the repository somewhere else, you can also use a dedicated home folder with elevated permissions for the tomcat user (including sandboxing exclusion) and start tomcat with the `user.home` property set to that folder via java options, e.g. `-Duser.home=...`. No need for a dedicated local user.

**Comment by motjokk** [comment]
Solved and close?

**Comment by Yasvana** [comment]
Finally, I've just created the home directory for the user 'tomcat' (i've tried mkhomedir_helper wihtout success):
- mkdir /home/tomcat
- chown tomcat:tomcat /home/tomcat
- modify the /etc/passwd from `tomcat:x:998:998:Apache Tomcat:/:/usr/sbin/nologin` to `tomcat:x:998:998:Apache Tomcat:/home/tomcat:/usr/sbin/nologin`

Now i'm able to install the war and do the setup with online installation of the plugins.

Thanks again guys @motjokk @hlg for your help !
