### ISSUE TITLE
cesiumloader error

### ISSUE THREAD

**Issue by holinz** [opensourceBIM/BIMserver#1168]
Thanks for help.
at this.loadGltf = function(roid, query, callback){
		o.bimServerApi.getSerializerByPluginClassName("org.bimserver.gltf.BinaryGltfSerializerPlugin", function(serializer){
has nothing error info ,but it cannot into the function(serializer){
the promise inside error info is 
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.o (<anonymous>:1:83)
    at http://localhost:8082/apps/bimserverjavascriptapi/bimserverclient.js:718:5
    at XMLHttpRequest.xhr.onload (http://localhost:8082/apps/bimserverjavascriptapi/bimserverclient.js:587:5)

**Comment by holinz** [comment]
![image](https://user-images.githubusercontent.com/8493103/99147656-aee74a80-26bd-11eb-84f7-2975a2d1f40b.png)

**Comment by holinz** [comment]
i have resolve the problem.but what is the roid ,is it the project id,like this "http://localhost:8082/apps/bimviews/?page=Project&poid=393217", is it roid=393217??
![image](https://user-images.githubusercontent.com/8493103/99148951-d510e880-26c5-11eb-89e7-cb3df6de5ebe.png)

**Comment by hlg** [comment]
Each project has zero, one or more revisions. POID is the ID of the project, ROID the ID of a particular revision.

Please post future questions about the [CesiumLoader](https://github.com/opensourceBIM/CesiumLoader) and [BIMserver-JavaScript-API](https://github.com/opensourceBIM/BIMserver-JavaScript-API) in the respective repositories.

**Comment by hlg** [comment]
In BIMvie.ws, you can see the ROIDs on the _Revisions_ tab in the _Id_ column, as a tooltip over the consecutive revision ID.

Through the API you can retrieve the ROIDs and query information on revisions in various ways:

* `ServiceInterface.getProjectByPoid`:
  The result (information on given project) will contain an attribute `lastRevisionId` and a list attribute `revisions` with the respective ROIDs.
* `ServiceInterface.getAllRevisionsOfProject`:
  This will return a list with ROID and additional information for all revisions in a given project.
* `ServiceInterface.getRevision`:
  This will return additional information on a particular revision by ROID.
