### ISSUE TITLE
Wiki links to dead issue tracker

### ISSUE THREAD

**Issue by DuncanLithgow** [opensourceBIM/BIMserver#1169]
The wiki
https://github.com/opensourceBIM/BIMserver/wiki

directs issues to
http://issues.bimserver.org

I'm thinking that's a mistake maybe.

I'm trying to create a page about BIMserver, help and corrections welcome.
https://wiki.osarch.org/index.php?title=BIMServer

**Comment by hlg** [comment]
Yes, that was an outdated URL, thanks for noting.
