### ISSUE TITLE
Waitinglist not empty, this usually means some objects were referred, but not included in the model

### ISSUE THREAD

**Issue by muren400** [opensourceBIM/BIMserver#1171]
Hi,

when there are unresolved references in an IFC file, the BIMserver throws this exception and stops the checkin process completely:

```org.bimserver.shared.exceptions.BimServerClientException: Waitinglist not empty, this usually means some objects were referred, but not included in the model```

Is it possible to just ommit these objects with unresolved references and still import the rest of the model?
Especially if these objects aren't referenced anywhere in the rest of the model themselves?

**Comment by hlg** [comment]
Technically this would be possible for sure. But as you noted, any entities referencing the missing ones transitively would need to be excluded. I am not in favour of including this as a feature for two reasons: 1. Currently, BIMserver accepts only valid IFC (except for violated constraints in EXPRESS rules). If we start to accept invalid IFC, where should we draw the line between acceptable and inacceptable errors? 2. The "fix" of the model by removing these referencing entities does likely not restore a useful model according to its author's intentions. It may even leave the model in a semantically inconsistent state or introduce violations to constraints in EXPRESS rules. We have no way to check this, so these removals would need to be logged with the revision.

If you are interested, you could try to implement a respective deserializer that does just that.

**Comment by hlg** [comment]
Do you have a particular use case for this feature?
