### ISSUE TITLE
Get Geometry using the API in Unity

### ISSUE THREAD

**Issue by Cod45ather** [opensourceBIM/BIMserver#1174]
Hi so I am new to C# and Unity, and I am currently trying to get the geometry using the API into Unity so, later on, use it to display the model in Unity.  (Like in BIMvie.ws)

**The request I used to get the geometry:**
![image](https://user-images.githubusercontent.com/47830174/101921553-cf7bc500-3bd5-11eb-8cb9-328a059e6588.png)

The response I get:
![image](https://user-images.githubusercontent.com/47830174/101921656-e8847600-3bd5-11eb-86d6-9d7682ad0cdf.png)

My question is how do I get the vertices since I just get the "nrVertices" in the response? Maybe I need to use another query?
Any suggestions will be appreciated.

**Comment by hlg** [comment]
You can do it this way. The field `_rdata` contains a reference to an object of type `GeometryData` which in turn has fields `_rvertices`, `_rindices` and `_rnormals` with references to objects of type `Buffer` which finally contain the respective binary data base64 encoded.

It might be more efficient if you write dediated serializer that transforms the data to your desired output format.

**Comment by hlg** [comment]
Btw, BIMvie.ws uses (an older version of) BIMsurfer which in turn uses the binary serializer.
I think this is answered with this and the last comment.
