### ISSUE TITLE
Error when loading project in bimsurfer3

### ISSUE THREAD

**Issue by dcapeletti** [opensourceBIM/BIMserver#1177]
Hello, when I go to http://localhost:8080/apps/bimsurfer3/apps/dev.html and click on the project, the following message appears:
**Unable to initialize WebGL. Your browser or machine may not support it.**

However if I go to https://get.webgl.org/ it tells me that my browser has support for webgl.

Does this happen to you? How can I solve my problem?
Attached is a picture of the error.

Using Firefox 68.10.0esr (64-bit) on Debian 9.

![BimSurfer error webgl](https://user-images.githubusercontent.com/5890886/101940965-182b8200-3bc6-11eb-8096-95acd2bf31d8.png)

**Comment by hlg** [comment]
Discussing this issue in the BIMsurfer repository: https://github.com/opensourceBIM/BIMsurfer/issues/80
