### ISSUE TITLE
Deleting project doesn't delete it's dependencies

### ISSUE THREAD

**Issue by DavideJensen** [opensourceBIM/BIMserver#1180]
With the usage of BIMvie.ws (tried with both 1.5.138 and 1.5.182) and also with the usage of the java library bimserverclientlib (version 1.5.138) I've noticed that after deleting a project that has children or parents, their reference in other projects remain unchanged. Then if I try to recreate a project with the same name it says that the project is already existing with that name even if it doesn't appear in the list anymore. I have also tried to refresh the page and restart the tomcat with the bimserver webapp. 

To reproduce in BIMvie.ws:
* Create a new project called ParentProj
* Create a sub project of ParentProj called ChildProj
* Delete the sub project
* Notice that the sub project doesn't exist anymore but the ParentProj still says `1 Sub Project`
* Try to create a sub project with the name ChildProj
* Notice the error notifying the existence of a ChildProj

To reproduce via java library:
* Create a new Project with the Bimserver client interface addProject function
* Create a sub Project with the Bimserver client interface addProjectAsSubProject function
* Delete the subproject with the Bimserver client interface deleteProject function
* Create a sub Project with the Bimserver client interface addProjectAsSubProject function with the same name as the previously deleted one and notice the error of already existing project

I would expect the projects to be deleted and the reference to them to be deleted as well.

Some screenshots on BIMvie to showcase the behavior:

Projects created:
![Screenshot from 2021-01-07 16-20-17](https://user-images.githubusercontent.com/4254522/103910413-15f50e80-5105-11eb-8829-ea58e890e35e.png)

Projects listed from the main page
![Screenshot from 2021-01-07 16-20-26](https://user-images.githubusercontent.com/4254522/103910442-1ee5e000-5105-11eb-9c75-418a9ebb9664.png)

After deletion of the sub project with the actions dropdown the parent project still says there is 1 child project
![Screenshot from 2021-01-07 16-20-38](https://user-images.githubusercontent.com/4254522/103910456-22796700-5105-11eb-817c-94965b679b35.png)

This happens when trying to create a new subproject with the same name of the deleted one:
![Screenshot from 2021-01-07 16-29-34](https://user-images.githubusercontent.com/4254522/103910855-9c115500-5105-11eb-8e72-c7da8700de76.png)

Is there a way i can cleanup the references to the deleted projects?

**Comment by hlg** [comment]
These are not just references. With "delete", a project is not actually removed from the database, but merely deactivated. You can still "undelete" it. This is by intention and similar questions have been asked and answered multiple times before, see for example #1077.

**Comment by DavideJensen** [comment]
Alright sorry and thanks!
