### ISSUE TITLE
BIMServer 1.5.138 plugin version list

### ISSUE THREAD

**Issue by lie16** [opensourceBIM/BIMserver#1181]
I know that BIMServer 1.5.138 cannot install plugin. Can you please tell me the correct plugin version being used at BIMServer 1.5.138?

**Comment by hlg** [comment]
We don't keep track of plugin compatibility and don't provide support for older development versions.

The dependencies are registered in Maven's pom.xml. If you manually want to lookup the version of a plugin which depends on BIMserver 1.5.138, you would have to find the plugin which has a dependency on org.opensourcebim:shared:1.5.138. For example, for IfcPlugins you would find [version 0.0.63](https://github.com/opensourceBIM/IfcPlugins/blob/0dfba253af305e88815d590ce01641fb157d3337/IfcPlugins/pom.xml#L54-L59). You can go through the pom files at Maven central or in the Github plugin repository or search through the commit messages in the Github plugin repo.

That being said, I would strongly recommend to update your client code to use a later version. May I ask why you are bound to using such an old version?

**Comment by lie16** [comment]
Thank you for your info. I already install most plugin manually except IfcPlugins 0.0.63, is this plugin replaceable with previous version?
I'm using this version because of OpenMaint optional software requirement require version 1.5.138.

**Comment by hlg** [comment]
Again, we do not provide support for older development versions. Your best bet is to got with the plugin version released together with the BIMserver version you try to get working. If that does not work, older plugin versions are less likely to work, but you can try of course.

A similar question with regard to OpenMaint was already discussed in #1133 with a definite answer. Please ask the OpenMaint/CMDbuild maintainers Teknoteka to update their client code to a newer BIMserver version.

**Comment by lie16** [comment]
thank you
