### ISSUE TITLE
Can't install plugins for BIMServer 1.5.182

### ISSUE THREAD

**Issue by DaLiangLee** [opensourceBIM/BIMserver#1182]
BIMServer 1.5.182

Now I am using these versions:

![image](https://user-images.githubusercontent.com/21189061/104998136-afa5af80-5a65-11eb-986b-b13e381aa4c1.png)

1. Cannot install pluginbase-1.5.68

![image](https://user-images.githubusercontent.com/21189061/104998245-d19f3200-5a65-11eb-93df-78615e9aa488.png)

2.Cannot install ifcengine-0.0.16.jar(It always shows "Installing plugin bundle from file..")
![image](https://user-images.githubusercontent.com/21189061/104998358-090dde80-5a66-11eb-84e4-5ae3d038abe3.png)

3.Can import ifc model but can't reader it..  i don't what happen todo
![image](https://user-images.githubusercontent.com/21189061/104998510-525e2e00-5a66-11eb-832d-2765e393c8f1.png)

These questions have troubled me for a long time, and I look forward to getting a reply, thank you

If the model can be displayed normally, I need to study how to upload/display/delete the model through .net core in the next step. Is there a tutorial on this? Thanks a lot

The project I am working on needs to upload, display and delete the BIM. My manager suggested that I use the BIM server. 

I am a C# developer and I really hope to get answers, thank you

**Comment by DaLiangLee** [comment]
now
3D not show

![image](https://user-images.githubusercontent.com/21189061/106115176-71a63b00-618b-11eb-89b6-a552c82077fa.png)
![image](https://user-images.githubusercontent.com/21189061/106115226-7ec32a00-618b-11eb-8a55-9ebefa6c9fb0.png)

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/106115343-a74b2400-618b-11eb-9624-26000331ddcd.png)
![image](https://user-images.githubusercontent.com/21189061/106115378-b03bf580-618b-11eb-9b2e-b0e8200c4301.png)
![image](https://user-images.githubusercontent.com/21189061/106115407-b631d680-618b-11eb-8a86-f511caf56d80.png)

**Comment by DaLiangLee** [comment]
最终我找到了解决方案： 那个博主提供了他们成功打包的IfcGeomServer-v0.6.0-b4ce5be-win64.exe
替换路径 \home\tmp\org.opensourcebim.ifcopenshellplugin 下exe文件，保持名称不变

**Comment by hlg** [comment]
Please edit your last comment to English.

Do I understand correctly, that your remaining issue was to be able to display the project in 3D view and you solved it by updating the IfcOpenShell plugin?

**Comment by hlg** [comment]
The 3D view issue seems to be resolved.
