### ISSUE TITLE
Question: checkin/upload bypass geometry conversion?

### ISSUE THREAD

**Issue by khelkun** [opensourceBIM/BIMserver#1184]
**Question**
Is it possible to bypass the geometry conversion done by IfcOpenShell during the checkin/upload?
(I've been looking into the wiki and the issues, but I didn't find anything related to this)

May be uninstalling IfcOpenShell plugin?

**Reason**
Since the checkin takes a base64 encoded string in the POST request body, I followed the wiki recommendation and used the upload endpoint to directly upload my files.

Those files are quite huge models (between 100 and 200Mb ifc files), so the server integration takes a while. I'm only interested in BIMserver to query the model metadata so I wish I could bypass the geometry conversion and storage.

**Comment by hlg** [comment]
Sure, you can disable geometry generation on checkin, if you don't need triangulated geometry (but just the original IFC data which is a bit more than metadata though) or if you only need geometry at a later point, not directly after checkin. There are two ways to do that.

1. switch off geometry generation on checkin: `ServiceInterface.setGenerateGeometryOnCheckin(false)`
2. use the NOP (No Operation) Render Engine: `PluginInterface.setDefaultRenderEngine(nopEngineOid)`

Note that 1. is a server-wide setting, while 2. is a per-user setting.

The NOP engine is installed by default and should be used as default render engine if you have not installed any other render engine. When you uninstall a render engine plugin, make sure you adjust users settings for the default engine, it is not done automatically.

With the geometry generation on checkin enabled, but carried out by NOP render engine, there will be some overhead originating from collecting the relevant IFC entities, handing them to the engine and creating the report, but this shouldn't cost much compared to the real rendering, as done by IfcOpenShell.

**Comment by khelkun** [comment]
@hlg thank you very much! It seems I didn't search well enough in the settings and the API.
So I actually did both (server-wide and per-user settings) through the bimvie.ws "Server > Server Settings > Geometry generation" & "User's settings > Render Engines". It seems to work as expected and the conversion is faster (no surprise).

**Comment by khelkun** [comment]
@hlg I don't know much about Ifc data format. So I'd like to ask you a few more about this geometry storage. For my 90Mb sample ifc model, in my bimvie.ws project:
1. If I query all objects as JSON, then I get arount 6500 json objects entries.
2. If I download the whole revision of the project as JSON, then I get more than 1 400 000 object entries
If I look inside this last JSON it seems I have plenty of this kind of objects:
```json
{
	"_i": 3342637,
	"_u": "7664b4a4-8f46-40b4-ae59-de52da4edce8",
	"_r": "1",
	"_t": "IfcMaterial",
	"_s": 1,
	"Name": "Color RGB 255-255-255",
	"_rHasRepresentation": 
	[
		{
			"_i": 3277010,
			"_t": "IfcMaterialDefinitionRepresentation"
		}
	]
}
```
And:
```json
{
	"_i": 21906981135,
	"_u": "dd930e00-1566-462c-8d72-7c4b8b3d7b22",
	"_r": "1",
	"_t": "IfcPolyLoop",
	"_s": 1,
	"_rPolygon": 
	[
		{
			"_i": 16033448366,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16034955694,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16033251758,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16033186222,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16034103726,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16035021230,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16034496942,
			"_t": "IfcCartesianPoint"
		},
		{
			"_i": 16033513902,
			"_t": "IfcCartesianPoint"
		}
	]
}
```
Those seem to me to be related to the 3D geometry and rendering (materials) which is not useful to me since I'm only interested in "metadata". So is there a way I could avoid storing this data please?

**Comment by hlg** [comment]
These are the original IFC entities, contained in your sample file. None of that is generated by the BIMserver. If you browse through the IFC file in BIMvie.ws or open the IFC in any other software, you will see these material and point entities as well. It is possible to have IFC files without geometry and materials information, but you would have to prepare that beforehand or require the author of the IFC to include less information.

On checkin, we always store the whole IFC file. Then, as you already saw, with a query you can select only those entities that you are actually interested in. This results in smaller payload, which is much more manageable than the whole bulk of data in an IFC file. That is exactly why you might want to use BIMserver (instead of a regular parser).

I am not sure what you mean by "metadata", but if you indeed only want to know the author, creating application and such, then BIMserver might be a bit over the top.

**Comment by khelkun** [comment]
Thanks. Yes "metadata" is not really meaningful. My model is a museum building with its safety equipment (fire alarms, sensors, 
fire extinguishers, ...). I'm basically interested in all objects and rooms of the building and their attributes: everything which is not related to their geometry or rendering materials.

I just had a quick look on the web to find a tool that could remove all the geometry and material data from an Ifc model, but I've not found anything so far.
