### ISSUE TITLE
The wiki -> BIMsurfer Serializers links are Invalid

### ISSUE THREAD

**Issue by aFtBfF** [opensourceBIM/BIMserver#1188]
**Describe the bug**
https://github.com/opensourceBIM/BIMserver/wiki/BIMsurfer-Serializers
The wiki -> BIMsurfer Serializers links are Invalid. All links are not work.Please update them.

**Expected behavior**
The wiki -> BIMsurfer Serializers links are Invalid. All links are not work.Please update them.

**Screenshots**
![image](https://user-images.githubusercontent.com/22255835/107141713-b5f0c280-6965-11eb-93db-6892b4e1ce86.png)

**Comment by hlg** [comment]
Thanks, I have updated the links and also the interface code. These wiki pages would also need some update on streaming and JSON serializers. There are certainly many more places in the documentation that are incomplete or outdated.

No need to post the 404 page screenshot, everyone knows how that looks ;)
