### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by mathrobi** [opensourceBIM/BIMserver#1194]
I'm new at github and am not sure where to post a question.
Is BIMserver connected to BIMserver.center? Is BIM server.center some kind of an evolution of BIMserver?
Sorry if this question seems off topic or stupid...I am a bit ileterate when it comes to programming so a lot of the information I find here is quite intimidating.

**Comment by hlg** [comment]
No. BIMserver.center has nothing to do at all with the Opensource BIMserver.
