### ISSUE TITLE
Prombles using BIMServer Split/decomposition Larger IFC files to each component, stored as a small IFC file.

### ISSUE THREAD

**Issue by wjiarao** [opensourceBIM/BIMserver#1197]
**Describe the bug**
Hello, this promble may not a bug I have met.
I've used BIMServer/BIMview.ws, trying to decomposition larger IFC file to each component, the IFC file I see attach file,
BimServer API is used to download an IFC file for each constituent component of the model by recursively sending queries based on oids and ifc types.
 query language used in BIMServer was follows:
{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  },
"includes":[
"validifc:ContainedInStructure",
"validifc:OwnerHistory",
"validifc:Representation",
"validifc:ObjectPlacement",
"validifc:AllProperties"
],
"oid":"Objects's oid"
}

But I can'nt get all "Objects's oid", and I'm not use java language and not know this language, when someone put similiar solves.
How can I accomplish this tasks using BIMServer? Anyone who can help me? Thanks very much.

[12building_second0421.zip](https://github.com/opensourceBIM/BIMserver/files/6439902/12building_second0421.zip)

**Comment by jingyangking** [comment]
Hello, may I ask if the downloaded IFC component can be displayed properly? The component I downloaded from bimserver cannot be converted by ifcconvert, and when opened in Revit, it also shows "cannot be opened". It is unclear what is causing this issue

**Comment by hlg** [comment]
In BIMvie.ws, you can see the OIDs in the "Browse" tab. If you want to get the OIDs programmatically, you could also use the low level interface, for example method `LowLevelInterface.getDataObjectsByType` with any programming language, not just Java. You can also write your own serializer which outputs only the OIDs - which would require Java though.

@jingyangking this question is not directly related and also discussed in your other post #1317, ignoring it here.
