### ISSUE TITLE
Error deploying BIMserver WAR in Tomcat 10

### ISSUE THREAD

**Issue by padenict** [opensourceBIM/BIMserver#1198]
I installed Tomcat 10 on Win10 64bit-machine.
I can access GUI manager.
When I try to upload and deploy, Tomcat hungs.
I also tried autodeployment features putting BIMserver 1.5.182 WAR in "webapps" folder and restarting Tomcat. It deploys, but when I try and start from GUI manager, I get "FAIL - Application at context path [/bimserver] could not be started".
Here in attachment you find Tomcat logs.
[logs.zip](https://github.com/opensourceBIM/BIMserver/files/6443505/logs.zip)

**Comment by hlg** [comment]
The announcement of the [Tomcat 10.0.5 release](http://tomcat.apache.org/#Tomcat_10.0.5_Released) states: "Applications that run on Tomcat 9 and earlier will not run on Tomcat 10 without changes". You could try Tomcat 9 or follow the suggestion for automatic conversion mentioned in the announcement.

With regard to the failing upload in Tomcat manager: Read the logs! There is a size limit and the BIMserver war exceeds it. You can configure the limit to a higher value in one of the config files. Personally, I don't find the manager app very useful and usually don't deploy it.

**Comment by padenict** [comment]
Configuration file is webapps\manager\WEB-INF\web.xml
apart this, with Tomcat 9, BIM Server started successfully.
