### ISSUE TITLE
Event Log Service Not Showing in Local Services

### ISSUE THREAD

**Issue by ArahamLag** [opensourceBIM/BIMserver#1206]
Hello BIMServer team,
Could you please indicate to me how can I add the event log service to a created new project within the BIMServer version 1.5.182?
In general, how can add the internal and external services because they're not loading or showing within the BIMview.ws? ....I'm particularly interested now in the event log service.

I'll appreciate very much your help/follow up, 
Please see attached screenshot.

Thank you
![ErrorSc](https://user-images.githubusercontent.com/61122601/123380103-08213180-d55d-11eb-93cf-7ece11ae9ecc.jpg)

**Comment by hlg** [comment]
Do you mean the event log service in the [DemoPlugins bundle](https://github.com/opensourceBIM/DemoPlugins)? I am not sure whether these plugins have been maintained and updated to the recent BIMserver API. I keep this issue open as a reminder to review the demo plugins and either update or archive and perhaps replace them.

**Comment by ArahamLag** [comment]
Thank you very much for your follow-up,  yes you're right, this is exactly what I meant, I've been looking for an option to enable the event log service in the most recent release/version of BIMServer, but I couldn't find it.  If you could please update me on this or give some directions on how to enable it, I'll appreciate it very much. I'll stay tuned. Kindest Regards

**Comment by hlg** [comment]
You would have to install the plugin bundle first, if you have not yet. You should find it under _Server / Available Plugin Bundles_.

**Comment by ArahamLag** [comment]
Hello, thanks for the reference, yes I installed all the ones that came together with BIMServer, please see the images below:

![image](https://user-images.githubusercontent.com/61122601/123841060-1b295e00-d8dd-11eb-8ba2-e0800f9c79c4.png)
![image](https://user-images.githubusercontent.com/61122601/123841347-6f344280-d8dd-11eb-8c3b-fda5b1e21cc7.png)

Is there any other option to install it? what about the URL option? what URL should I use?

**Comment by hlg** [comment]
There should be more than those, not during initial install, but in the available plugin bundle list. Which version are you using? Anything particular about your setup? Errors in logs? Did you perhaps change the server setting "Repository Server"? In case you don't remember, you could try with a fresh setup with fresh home folder.

Alternatively, if you don't manage to restore the available plugin bundles list, you can follow the instructions in the wiki on [Installation without internet connection](https://github.com/opensourceBIM/BIMserver/wiki/Installing-without-internet-connection). It would be the same procedure: find the plugin bundle jar, either dowload it and use the file for upload or directly provide URL of the jar without the download/upload indirection.

**Comment by ArahamLag** [comment]
Thanks for your useful follow-up comments, I'm using BIMServer version 1.5.182. I believe I did not change the repository server setting, but I'll be following your instructions trying to restore the bundle list or reinstall it according to your recommendation. 
Kindest Regards

**Comment by ArahamLag** [comment]
Hello HLG, 

Based on your previous recommendations, I was able to install the event log service. Thank you very much for that.......However, I still have one issue that is preventing the event log service to work properly

I believe that the problem is that the Event Log Service is not identifying properly the Write Extended Data Parameter,  I'm getting it as "undefined" as shown in the image below:
![image](https://user-images.githubusercontent.com/61122601/124674543-f27b0880-de88-11eb-916f-00b0634b2bc3.png)

When it should be addressing to an URL/Extended Schema, as shown in Schaijk's youtube video, please see the image below:
![image](https://user-images.githubusercontent.com/61122601/124674875-949af080-de89-11eb-82a9-19e76403f45f.png)

Finally, when I try to specify a new Extended Data Schema, I'm getting the following error:
![image](https://user-images.githubusercontent.com/61122601/124675106-feb39580-de89-11eb-8484-36641da27283.png)

Could you please let me know if I' am missing something in the setup so that the internal services can work properly?

I appreciate your support and time, 

Kindest Regards

**Comment by hlg** [comment]
The error you see in the last step is from trying to access the non-existent data schema with name "http://bimserver.org/eventlog". A frontend used in production should not show the link to undefined but rather a message. You can not create the schema by following this link, nor can you edit or remove existing schemas. Instead go to _Server / Extended Data Schemas / Add new_ to add a new schema with name "http://bimserver.org/eventlog" and content type "text/csv".

**Comment by ArahamLag** [comment]
Hi HLG, 
I greatly appreciate your time and support, it's working now, so I'll start testing its functionalities, thank you very much.
Kindest Regards,
