### ISSUE TITLE
Display 3D model from IFC4 RV file

### ISSUE THREAD

**Issue by kurb70** [opensourceBIM/BIMserver#1207]
Hello Everyone,

after a while I have once again
exported an IFC4 RV and imported it into BIMserver.
Project was created with Archicad 24

I used BIMserver (Version 1.5.182)
macOS (with OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9, mixed mode)

Nothing is displayed in the 3D view. The view remains empty.

I have also tried to display the IFC4 project with https://view.ifcopenshell.org/.
It seems that the import process cannot be completed.
[IFC4 and BIMserver degug report_2021-07-04.zip](https://github.com/opensourceBIM/BIMserver/files/6759625/IFC4.and.BIMserver.degug.report_2021-07-04.zip)
[IFC4 and BIMserver degug report_2021-07-04.zip](https://github.com/opensourceBIM/BIMserver/files/6759626/IFC4.and.BIMserver.degug.report_2021-07-04.zip)
[SimplyTwoRooms ARC -- IFC4 RV BIMvs.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/6759630/SimplyTwoRooms.ARC.--.IFC4.RV.BIMvs.ifc.zip)

For comparison I also imported another 2x3 project.
Here the object is displayed in 3D.

Here an excerpt from
BIMserver geometry generation report (v1.2), Section Jobs

Main type: IfcWindow
Uses mapping: true
triangles: 0
Total time: 974ms
CPU time: 0ms
Max memory 0

```
java.lang.Exception: Missing objects in model (9 (66699))
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:833)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by kurb70** [comment]
Sorry posting IFC4 and BIMserver debug report_2021-07-04.zip twice. I was confused that the files were rejected by GitHub the first time.

**Comment by kurb70** [comment]
BTW This is a screenshot from the IVC4 model i tried to display.
![SimplyTwoRooms ARC](https://user-images.githubusercontent.com/1941141/124379591-41be0f00-dcb8-11eb-87db-914e322b205f.png)

**Comment by hlg** [comment]
For me, geometry seems to be properly generated, both in BIMserver and https://view.ifcopenshell.org/. There are some irregularities in the roof part, but those seem to stem from the modelling (I can also see them in FZK viewer).

![image](https://user-images.githubusercontent.com/356986/124455164-89f93200-dd89-11eb-95f7-ff3de7fd5b4b.png)

Can you try a more recent version of IfcOpenShell by changing the plugin setting "Commit Sha" to 517b819?

**Comment by kurb70** [comment]
Thank you for the investigation.

I can confirm that the model is now displayed on https://view.ifcopenshell.org/.
Maybe I made a mistake at that time.

I would like to do the IfcOpenshell version change.
Unfortunately I can't find the configuration file. Where in the BIMserver instance should this file be located?

**Comment by hlg** [comment]
In BIMvie.ws it is _Server / Installed Plugin Bundles / IfcOpenShell-BIMserver-plugin / Plugins / IfcOpenShell / Settings_. Through the API, there is _PluginInterface.getPluginSettings_ and _PluginInterface.setPluginSettings_

**Comment by kurb70** [comment]
Many, many thanks. With this change, the model is displayed. 
I was already "despairing". ;)
