### ISSUE TITLE
32bit libifcengine.so: Segmentation fault and undefined symbol

### ISSUE THREAD

**Issue by StephanPirnbaum** [opensourceBIM/BIMserver#121]
Hello,
I 've an issue regarding the libifcengine.so for 32bit Linux systems.

At the moment I have to use the Version of Nov 15, 2013 (f9a990e), this one works fine.

But with all versions newer than that, I don't get it to work.

Using version of Nov 20, 2013 (c13b67e), I get an NativeException stating this message:
Exception in thread "main" org.xvolks.jnative.exceptions.NativeException: Library libifcengine.so not found : libifcengine.so: undefined symbol: rdf_overRuleCache

The path I am using is exactly the same compared to the working version (triple checked it), so that's not the problem. 

Using newest version from Apr 10, 2014 (758a8bc), it finds the library but I get a segmentation fault:
#
A fatal error has been detected by the Java Runtime Environment:
#
SIGSEGV (0xb) at pc=0xa6084455, pid=4634, tid=4134656832
#
JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
Java VM: Java HotSpot(TM) Server VM (25.20-b23 mixed mode linux-x86 )
Problematic frame:
C  [libifcengine.so+0xff455]  getUri(STRUCT__MODEL*, char const*, int*)+0x15
#
Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
An error report file with more information is saved as:
hs_err_pid4634.log
#
If you would like to submit a bug report, please visit:
http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
#

Nothing changed in the code, only switched the libs. It seems to me, that it is only a problem on Linux, because a teammate has no problems with the newest version on windows.

It would be great, if you can find the reason so that I am able to use the latest lib.

Best regards,
Stephan

**Comment by berlotti** [comment]
closing because of long inactivity
