### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isDone' of undefined

### ISSUE THREAD

**Issue by mercury20160104** [opensourceBIM/BIMserver#1210]
Uncaught TypeError: Cannot read property 'isDone' of undefined
    at bimserverapipromise.js:69
    at Array.forEach (<anonymous>)
    at BimServerApiPromise.chain (bimserverapipromise.js:68)
    at Project.loadDetails (eval at globalEval (bimviews.js?_v=0.0.184:338), <anonymous>:507:12)
    at eval (eval at globalEval (bimviews.js?_v=0.0.184:338), <anonymous>:39:12)
    at bimserverclient.js:964
    at bimserverclient.js:713
    at XMLHttpRequest.xhr.onload (bimserverclient.js:587)
DevTools failed to load source map: Could not load content for http://localhost:8082/apps/bimviews/deps/bimsurfer-v1/lib/hammer/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by hlg** [comment]
Please describe what you did, what you expected to happen and what happened instead. The error message as such does not constitute an issue.

Such errors can appear when you select something in the tree while not having the 3D tab open. In BIMvie.ws (remember it is just a demo application) tree selection only works in connection with the 3D view (https://github.com/opensourceBIM/BIMserver/issues/1172#issuecomment-773128072).
