### ISSUE TITLE
OpenStudio can't connect BIM Server

### ISSUE THREAD

**Issue by keleisi2001** [opensourceBIM/BIMserver#1211]
I try so many times but OpenStudio still can't connect BIM Server. Maybe "address" or "post" has wrong? But my BIM Server is running smoothly. I really don’t know which software has the problem.

Screenshots:

![1](https://user-images.githubusercontent.com/55388367/128494118-5c710c78-29ad-42f7-a4ea-32c6cdade7d3.png)
![2](https://user-images.githubusercontent.com/55388367/128494131-cb3c9899-47fd-4e7f-8797-0491879c5db2.png)
![3](https://user-images.githubusercontent.com/55388367/128494186-392e9cee-517d-4f0f-8d78-7bf30bdbba37.png)
![4](https://user-images.githubusercontent.com/55388367/128494197-f8d18eba-4b65-4dde-bbdb-a81ec83aa67f.png)
![5](https://user-images.githubusercontent.com/55388367/128494208-67b28714-3ff6-4b21-9296-ba10647c66a1.png)

**Comment by hlg** [comment]
If BIMserver does not report any error, then it is probably an OpenStudio issue. For example it could require a different version. Please seek assistance through them. You need more detailed information (logs or the like) about the error reported in OpenStudio.
