### ISSUE TITLE
Install IfcEngine plugin failed on BIMServer 1.5.182

### ISSUE THREAD

**Issue by twisker** [opensourceBIM/BIMserver#1228]
**Describe the bug**
In a newly setup BIM Server, after installing numbers of plugins, such as bimserverapi, bimviews, console, ifcplugins, ifcopenshellplugin, etc, I tried to install IfcEngine-0.0.16.jar, but got this error message:
Receiver class org.bimserver.ifcengine.JvmRenderEnginePlugin does not define or inherit an implementation of the resolved method 'abstract org.bimserver.models.store.ObjectDefinition getSystemSettingsDefinition()' of interface org.bimserver.plugins.Plugin.

**To Reproduce**
1. docker run -it -e JAVA_OPTS='-Xmx4g' -v <local folder path>:/usr/local/bimserver/home -p 8080:8080 --name bimserver asti/bimserver:1.5.182
2. Process the normal setup
3. Install the following plugins with offline-mode
    bimserverapi-0.0.176.jar
    bimsurfer3-0.0.272.jar
    bimviews-0.0.184.jar
    binaryserializers-0.0.93.jar
    console-0.0.67.jar
    gltf-0.0.59.jar
    ifcopenshellplugin-0.5.91.jar
    ifcplugins-0.0.99.jar
    mergers-0.0.65.jar
4. Finish Setup
5. Go to BIMVie.ws
6. Install ifcengine-0.0.16.jar from file
7. See the error

**Expected behavior**
Installed IfcEngine

![image](https://user-images.githubusercontent.com/16277077/145556495-5e92b490-149b-461e-94f4-a2eab7414209.png)

**Comment by hlg** [comment]
The [IfcEngine](https://github.com/opensourceBIM/IfcEngine) Read.me says: This plugin is not maintained anymore by the open source BIM collective, but by [RDF](http://rdf.bg/product-list/ifc-engine/). At the moment it does not work with BIMserver 1.5. You may want to contact RDF, author of the IfcEngine library wrapped in the plugin, in case you need that particular render engine. Alternatively, use the render engine plugin based on IfcOpenShell. This library is under active development and you have the plugin already installed.
