### ISSUE TITLE
Log4j

### ISSUE THREAD

**Issue by Steema1** [opensourceBIM/BIMserver#1231]
Hello everyone,
could anyone tell me how to update the log4j library in BimServer?
Thanks in advance for the help.
Greetings.

Dario

**Comment by hlg** [comment]
AFAIK BIMserver uses logback, not log4j. Where did you see log4j being used?

**Comment by Steema1** [comment]
thanks for the quick response. 

I did a quick search and saw that there are points in the code that call log4j: https://github.com/opensourceBIM/BIMserver/search?q=log4j

being log4j a component with a high criticality and not being a java expert I wanted to understand if it was necessary to proceed with an update of the component.

Greetings.

Dario

**Comment by hlg** [comment]
I think these are leftovers from pre-logback times, mainly obsolete configuration. Will remove them to avoid future confusion or worries. Velocity may need an update to 2.x where it starts to use SLF4J, currently velocity logging is likely broken, as it should not find Log4J on the classpath.

**Comment by Steema1** [comment]
Hello hlg,
many thanks for the valuable information.
Best regards
Dario

**Comment by hlg** [comment]
Good practice to close resolved issues! I would like to keep it open as a reminder for the housekeeping.

**Comment by Steema1** [comment]
Sorry, I'm not familiar with issues management...
Many thanks

Dario

**Comment by hlg** [comment]
No worries, no offense, nothing wrong. In general, it is very much appreciated if you close an issue you have opened yourself once it has been solved or clarified. Just in this particular case I would like to keep it open.
