### ISSUE TITLE
Could not find 'validifc' namespace in predefined queries

### ISSUE THREAD

**Issue by SteffanDavies** [opensourceBIM/BIMserver#1234]
I am attempting to query BIMserver using the following query:

```
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]
}
```
This results in the "Could not find 'validifc' namespace in predefined queries".

![image](https://user-images.githubusercontent.com/50405969/149319811-cd020162-5f0b-4ff8-8557-ead7f647ba5e.png)

If I remove the "includes portion the query, it will correctly return the "ifcWall" object. 

![image](https://user-images.githubusercontent.com/50405969/149319948-46ea1c3a-4c93-4446-a6ea-d38c46873a1d.png)

Can someone explain why "validifc fails?

**Comment by hlg** [comment]
This has already been answered: https://github.com/opensourceBIM/BIMserver/issues/1046#issuecomment-544988400. Use "ifc2x3tc1-stdlib" or "ifc4-stdlib" instead of "validifc", depending on your IFC schema version.
