### ISSUE TITLE
Empty file download while using glTF serializers

### ISSUE THREAD

**Issue by PaoloBertuzzo** [opensourceBIM/BIMserver#1239]
Hello,
we are using 1.5.182 version of BIM server. We are implementing download feature using Java client (ver, 1.5.182). While all serializers are producing correct files, glTF serializers produce empty download data.

We're using this kind of approach

			long topicId = client.getServiceInterface().download(new HashSet<Long>() {{
				this.add(Long.parseLong(revisionId));	
			}}, query, serializerId, false);

serializerId is retrieved by plugininterface serializers service. Any suggestion on this? BIMView.ws glTF download works without problems at all.

Thanks

**Comment by hlg** [comment]
Please provide a bit more context: What's the value of your `query`? How are you initiating and processing the actual data download? Do binary serializers work? Have you tried to use the convenience methods below?

    BimServerClient#download(long roid, long serializerOid, OutputStream outputStream)
    BimServerClient#download(long roid, long serializerOid, Path file)

**Comment by PaoloBertuzzo** [comment]
It works using the convenience method. Thanks for support.
