### ISSUE TITLE
the problem about class file version 55.0

### ISSUE THREAD

**Issue by 252651980** [opensourceBIM/BIMserver#1244]
Dear sir,

I try use Eclipse to compiler the project BIMserver with JDK1.8. There is a problem about the eclipse jar compiler by JDK11 like 'java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/CoreException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0'. How shoud I solve it？

Thanks

**Comment by hlg** [comment]
Apparently there are Eclipse dependencies updated to versions compiled with Java 11. If you want get a version that runs on 8, you'd need to do some detective work to figure out where this is coming from, exclude the newer version and explicitly depend on an older version - similar to [this approach](https://stackoverflow.com/questions/68039780/how-to-get-eclipse-libraries-compiled-on-java-8#comment121463492_68039780). I suppose the suspect is org.eclipse.jdt.core, which I would like to remove anyhow (#1233).

**Comment by 252651980** [comment]
Thanks

**Comment by hlg** [comment]
You may try to downgrade org.eclipse.jdt to version 3.10.0 as done in commit e4c3904fc2413517a9e096a3154dd2506d9f88f8. This version supposedly still works with Java 8.
