### ISSUE TITLE
bimserver logo

### ISSUE THREAD

**Issue by DuncanLithgow** [opensourceBIM/BIMserver#1245]
Not really a bug - but where to file it?

There is a logo for BiMserver on https://bimserver.org/ and I'm just wondering if there is a folder in this repository somewhere with the files. I'm just adding it to https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory#OpenBIM_Management and notice that it's a nasty PNG not a lovely SVG or something so I'm cropping out the text manually.

Anyway, I suggest a directory for graphics which includes the logo. If there already is one then sorry I couldn't find it.

**Comment by hlg** [comment]
There are various places with image folders and copies of the logo. It is also contained in BIMvie.ws, for example. Here is one location here in the core BIMserver repository: [BimServer/www/img/bimserver.png](https://github.com/opensourceBIM/BIMserver/blob/9c9d4748eef697b527604dc42140c43ce17c758a/BimServer/www/img/bimserver.png). There are no vector graphics versions. Thanks for adding BIMserver to the list.
