### ISSUE TITLE
How to upload an extended IFC file in bimserverwar-1.5.182 

### ISSUE THREAD

**Issue by hsfxliangxiwen** [opensourceBIM/BIMserver#1249]
Hello!
I want to upload an extended IFC file in bimserverwar-1.5.182, but I don't know which file of bimserverwar I should change. And the issue is as the picture.
I have extended the IfcConstrEquipElementType in the IFC file.
![QQ图片20220309165018](https://user-images.githubusercontent.com/101248925/157407065-d0ebb2e6-03e0-48dc-8ed3-8678a8680c18.png)

**Comment by zaqifathis** [comment]
hi @hsfxliangxiwen , have you finally found why that happen and how you solved it?

**Comment by hlg** [comment]
Currently, the Opensource BIMserver supports storage of data following the schemas  [IFC 4 ADD2 TC1](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/) and [IFC 2x3 TC1](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/). IfcConstrEquipElementType is defined in neither of those two. We are not supporting deployment of custom schemas in the BIMserver beyond the options to extend the schema with user-defined properties and types given within the official schema definitions.
