### ISSUE TITLE
JsonQueryObjectModelConverter#toJson: ignores QueryPart#addGuid

### ISSUE THREAD

**Issue by mhendrikxce** [opensourceBIM/BIMserver#1255]
I believe the GUID filter of QueryPart is ignored.

**To reproduce:**
1. Create a Query with a QueryPart that adds a GUID using addGuid
2. Pass query to ClientIfcModel#queryNew with a IfcModelChangeListener that prints all added
3. Notice that all components are loaded

**Problem analysis**
The issue is that JsonQueryObjectModelConverter#toJson skips the QueryPart's GUID's.

Adding:
```java
if (queryPart.hasGuids()) {
    ArrayNode guidsNode = OBJECT_MAPPER.createArrayNode();
    queryPartNode.set("guids", guidsNode);
    for (String guid : queryPart.getGuids()) {
        guidsNode.add(guid);
    }
}
```

under the block processing the oids in the toJson method seems to resolve the issue.

**Comment by hlg** [comment]
Looks plausible. Thanks for reporting!
I'd add it right after the OIDs part.
https://github.com/opensourceBIM/BIMserver/blob/9c9d4748eef697b527604dc42140c43ce17c758a/PluginBase/src/org/bimserver/database/queries/om/JsonQueryObjectModelConverter.java#L97-L103

**Comment by mhendrikxce** [comment]
Thanks for the fast reply and follow-up!

**Comment by mhendrikxce** [comment]
Read for review: https://github.com/opensourceBIM/BIMserver/pull/1257
