### ISSUE TITLE
BIMserver starter: broken plugin installation

### ISSUE THREAD

**Issue by mhendrikxce** [opensourceBIM/BIMserver#1259]
**Description**
1. Download 1.5.182 and extract to new folder to prevent existing data being used
2. Start jar and select "Start"
3. On new installation, select checkboxes to install plugins (e.g. BIMVie.ws)

On install will get issue:

Failed to collect dependencies at org.opensourcebim:pluginbase:jar:1.5.182 -> org.eclipse.emf:org.eclipse.emf.codegen:jar:2.14.0 -> org.eclipse.platform:org.eclipse.core.runtime:jar:3.12.0 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0)

Problem is that org.osgi.service group ID no longer seems to exist this is referenced via org.eclipse.equinox.preferences-3.10.0.jar. 3.10.0 was deployed yesterday, so it is now picking that one. A solution would be to patch the pluginbase pom.xml to exclude the invalid org.osgi.service group ID by using 3.9.100 instead.

**Comment by GiacomoManzoli** [comment]
Also the version 1.5.181 is affected by the same issue

**Comment by hlg** [comment]
Yeah, seems to be an issue with the org.eclipse.equinox.preferences dependencies. They added a dependency on org.osgi.service.prefs, which was not there in earlier versions (<3.10) and misnamed the org. I would like to remove the dependency on org.eclipse.emf.codegen anyway: #1233.

**Comment by mhendrikxce** [comment]
Convincing the pom.xml to use 3.9.100 proved too much for my Maven experience. There are other indirect dependencies that force it to be >= 3.10.

Opted for the workaround:
1. Go to your maven folder
2. Find the artifact: e.g. c:\Users\YOUR\.m2\repository\org\eclipse\platform\org.eclipse.equinox.preferences\3.10.0\org.eclipse.equinox.preferences-3.10.0.pom
3. Fix the groupID:

    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.prefs</artifactId>
      <version>[1.1.0,1.2.0)</version>
    </dependency>

**Comment by mhendrikxce** [comment]
This should fix it. The dependency tree now shows it uses 3.9.100. As you can see, this required a LOT of exclusions. Next, I replaced this in the jar.

I found out that this does not help us though as the installer checks out its own copy of the pluginbase (repository\org\opensourcebim\pluginbase\1.5.182) instead of re-using the one bundled in the jar. So it will end up with an unpatched pom.

Is it an option to upload a new version to https://mvnrepository.com/artifact/org.opensourcebim/pluginbase with exclusions as I did in the code below?

`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<name>PluginBase</name>
	<description>Base project for BIMserver plugin development. Some plugins mights also need the Shared library</description>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>pluginbase</artifactId>
	<packaging>jar</packaging>
	<parent>
		<groupId>org.opensourcebim</groupId>
		<artifactId>parent</artifactId>
		<version>1.5.182</version>
	</parent>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<resources>
			<resource>
				<directory>generated</directory>
			</resource>
			<resource>
				<directory>src</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>generated</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
	
	

		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.equinox.preferences</artifactId>
			<version>3.9.100</version>
		</dependency>
		
			<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.core.resources</artifactId>
			<version>3.11.1</version>
			<exclusions>
			<exclusion>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.expressions</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.runtime</artifactId>
			</exclusion>
			</exclusions>
    </dependency>
	
	
			<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.core.expressions</artifactId>
			<version>3.5.100</version>
									<exclusions>

				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>eclipse.core.runtime</artifactId>
			</exclusion>
						<exclusion>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.runtime</artifactId>
			</exclusion>
						</exclusions>

    </dependency>
	
	
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.core</artifactId>
			<version>3.12.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.text</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.resources</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.runtime</artifactId>
				</exclusion>
				
			</exclusions>
		</dependency>
	
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.text</artifactId>
			<version>3.7.0</version>
						<exclusions>

				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.equinox.preferences</artifactId>
				</exclusion>
				</exclusions>
		</dependency>
	
			<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.core.runtime</artifactId>
			<version>3.12.0</version>
	  			<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.equinox.preferences</artifactId>
				</exclusion>
			</exclusions>
    </dependency>
	
	
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.2</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<version>4.5.7</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-api</artifactId>
			<version>1.0.2.v20150114</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-transport-file</artifactId>
			<version>1.0.2.v20150114</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-transport-http</artifactId>
			<version>1.0.2.v20150114</version>
			<exclusions>
				<exclusion>
					<artifactId>httpclient</artifactId>
					<groupId>org.apache.httpcomponents</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-spi</artifactId>
			<version>1.0.2.v20150114</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-connector-basic</artifactId>
			<version>1.0.2.v20150114</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.aether</groupId>
			<artifactId>aether-impl</artifactId>
			<version>1.0.2.v20150114</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-repository-metadata</artifactId>
			<version>3.3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-settings-builder</artifactId>
			<version>3.3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-aether-provider</artifactId>
			<version>3.3.9</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>26.0-jre</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.10</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.10.1</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.13</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.9</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.tycho</groupId>
			<artifactId>org.eclipse.jdt.core</artifactId>
			<version>3.14.0.v20171206-0802</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<version>2.15.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<version>2.15.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.xmi</artifactId>
			<version>2.15.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.codegen</artifactId>
			<version>2.14.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.text</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.runtime</artifactId>
				</exclusion>

				<exclusion>
					<groupId>org.eclipse.jdt</groupId>
					<artifactId>org.eclipse.jdt.core</artifactId>
				</exclusion>

			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.codegen.ecore</artifactId>
			<version>2.15.0</version>
				<exclusions>
				<exclusion>
					<groupId>org.eclipse.jdt</groupId>
					<artifactId>org.eclipse.jdt.core</artifactId>
				</exclusion>
								<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.text</artifactId>
				</exclusion>
			<exclusion>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.runtime</artifactId>
			</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.birt.runtime</groupId>
			<artifactId>org.eclipse.core.resources</artifactId>
			<version>3.8.101.v20130717-0806</version>
		</dependency>
		<dependency>
			<groupId>org.opensourcebim</groupId>
			<artifactId>buildingsmartlibrary</artifactId>
			<version>1.0.13</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0.4</version>
		</dependency>
	</dependencies>
	<licenses>
		<license>
			<distribution>repo</distribution>
			<name>GNU Affero General Public License 3</name>
			<url>https://www.gnu.org/licenses/agpl-3.0.en.html</url>
		</license>
	</licenses>
</project>
`

**Comment by hlg** [comment]
> I found out that this does not help us though as the installer checks out its own copy of the pluginbase

Actually, this should have changed with commits ec4505d9d4cede9f033d9bc08c and 9b381821e963eb9b367 which are not in 1.5.182 though. If you use a development snapshot and apply your workaround it should just work fine.

> Is it an option to upload a new version to https://mvnrepository.com ... with exclusions as I did in the code below?

No, I don't think these exclusions should be made a permanent solution. The proper way is to wait for the jar with the wrong group specification being fixed. As many downstream packages are affected, this has already happened quickly, there is a fixed version 3.10.1 for org.eclipse.equinox.preferences and thus there should not be any problem anymore because Maven will grep the latest, fixed, version. Can you please verify and close if successful?

**Comment by mhendrikxce** [comment]
> Actually, this should have changed with commits https://github.com/opensourceBIM/BIMserver/commit/ec4505d9d4cede9f033d9bc08c8ee95a3db22d24 and https://github.com/opensourceBIM/BIMserver/commit/9b381821e963eb9b3679c0b26f2b11a145822600 which are not in 1.5.182 though. If you use a development snapshot and apply your workaround it should just work fine.

I'll try that. Thanks!

> Can you please verify and close this issue if successful?

3.10.1 should indeed do the trick. I see that it is downloaded in my repository. It however seems to prefer 3.10 over 3.10.1 as it only looks at major/minor. Checking if that is a configuration issue on my end.
