### ISSUE TITLE
Missing walls in 3d model

### ISSUE THREAD

**Issue by misho048** [opensourceBIM/BIMserver#1282]
Hi, 

I have trouble with [THIS](https://github.com/opensourceBIM/BIMserver/files/10207353/ASR.DEK_2022-12-06_2.zip) model. There are some walls missing.
I am using bimSurfer3 (0.0.272) and bim server 1.5.182

(on the left is BimVision, and on the right is BimSurfer)   
![image](https://user-images.githubusercontent.com/40466737/207030282-68706d63-f4cc-46fa-8192-c91e5fa2fdff.png)
****

**Comment by hlg** [comment]
Please upgrade IfcOpenShell geometry engine to commit sha `2f3c79a`, which is the latest available. The steps are described in this issue: https://github.com/opensourceBIM/BIMserver/issues/1207#issuecomment-878117652.
