### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by michelespinella** [opensourceBIM/BIMserver#1284]
Good day,
     do you plan a new release of bimserver this year? Are you actively developing bimserver or you plan to abadon the project?

Thanks and regards
Michele Spinella

**Comment by hlg** [comment]
This will just be a maintenance release, finally. I don't plan to abandon the BIMserver project.

**Comment by dlabz** [comment]
> I don't plan to abandon the BIMserver project.

Respect.
