### ISSUE TITLE
shared hosting

### ISSUE THREAD

**Issue by bewegende-Architektur** [opensourceBIM/BIMserver#1285]
Hello everyone,

is it possible to run a bimserver in a shared hosting environment? when pointing the domain to the extracted war, the setup shows up but is not installing. I am experimenting with the jar-file on desktop and would like to check out, if a bimserver could run in shared hosting like ionos. Does anyone have experience with this?

Thanks in advance!

Greetings,
Chris

**Comment by hlg** [comment]
Which Ionos offer are you talking about? You need a server environment where you can execute Java bytecode. If you have a shared web hosting package, this is usually not the case. Correct me if I'm wrong, but it sounds like you expect the war to be somewhat like a website archive that can be served by a web server. This is not the case.

**Comment by bewegende-Architektur** [comment]
Thank you very much for your quick answer. Yes, I tought there is maybe a trick to run it in a shared webhosting environment. I guess I have found a fitting environment from ionos and going to test it there.

Thank you very much :)
