### ISSUE TITLE
Can he run on a virtual machine with arm architecture

### ISSUE THREAD

**Issue by akak48** [opensourceBIM/BIMserver#1297]
Hello,
Can the BIMserver run on a virtual machine with arm architecture? My operating system is Centos7.9
![image](https://github.com/opensourceBIM/BIMserver/assets/45613208/99ad1ab3-52f4-4059-95e5-63c717b04f04)

**Comment by hlg** [comment]
You should be able to run BIMserver on any OS as long as there is a suitable JVM for it.
