### ISSUE TITLE
3D model cannot be displayed

### ISSUE THREAD

**Issue by akak48** [opensourceBIM/BIMserver#1298]
Hello，
I am prompted in the browser that the project was successfully imported, but the 3D model cannot be displayed. Why is it？
The backend service reported  errors, as shown in the figure.I have tried both ARM architecture virtual machines and x86 architecture virtual machines，The operating system is Centos7.9
Thanks.
![image](https://github.com/opensourceBIM/BIMserver/assets/45613208/f4b01f51-2eaf-4aa4-b7a3-09e4be64673a)
![image](https://github.com/opensourceBIM/BIMserver/assets/45613208/72494a80-bd96-44ce-b847-cfe6b8a12829)

**Comment by akak48** [comment]
Installed Plugin Bundles
![image](https://github.com/opensourceBIM/BIMserver/assets/45613208/474592f2-9bf2-416d-bcab-e0e522b33bed)

**Comment by thaopham03** [comment]
Hello @akak48,

Your 3D model issue on Centos operating system can be resolved if looking at [IfcOpenshell-Bimserver-plugin](https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin?tab=readme-ov-file#occasional-problems-and-solutions) readme. Moreover, somebody already mentioned this issue on [#633](https://github.com/opensourceBIM/BIMserver/issues/633) with solutions.

Please let me know if you resolve this issue already or have any other questions.
