### ISSUE TITLE
official BIMserver docker

### ISSUE THREAD

**Issue by Chep2** [opensourceBIM/BIMserver#1304]
Hello. Is there an official BIMserver docker?

**Comment by hlg** [comment]
No, there is no "official" docker image. There is a basic docker file [here](https://github.com/dd-bim/BIMServer-docker-image) for example and also some images on dockerhub. If you just want to test BIMserver locally, you wouldn't need Docker, just go with the JAR distribution. If you want to run a shared server, the basic Docker file probably won't get you far anyway.
