### ISSUE TITLE
No default render engine has been selected for this user

### ISSUE THREAD

**Issue by myfulltexts** [opensourceBIM/BIMserver#1309]
BIMServer-v1.588, when check in a .ifc file, the server throw no default render engine.
Anybody kwon this issue?
<img width="719" alt="08b5f169c35dd701c86abd0ad8b1d02" src="https://github.com/opensourceBIM/BIMserver/assets/33918535/dfb7d90e-73ce-42de-a109-09ebe0981dc8">

**Comment by hlg** [comment]
Usually this error indicates that you have not configured a render engine for the user. There is a choice of the default NOP engine, if you do not need triangulated geometry or a render engine plugin, for example IfcOpenShell, if you need triangulated geometry. 

BIMserver version 1.588 does not exist. Do you mean 1.5.88? This version is outdated and might have issues which were already fixed in later versions. If the error appears in version 1.5.184 and after selecting the NOP engine, please follow up to this post, otherwise the issue should be closed. 

Please do not post stack traces as images, but as text (with "code" markup).

**Comment by myfulltexts** [comment]
Yes, BIMserver-v1.5.88, thanks.
By the way,the version 1.5.88 can work together with bimviews-0.087 and bimsurfer-0.042. if I update to version 1.5.184, how to get the machted version of the plugins?

**Comment by hlg** [comment]
Short answer: For BIMserver 1.5.184, go with bimviews-0.0.186 and bimsurfer3-0.0.274. Long answer below.

The compatibility information is stored with the plugins. They depend on a particular BIMserver version and declare that dependency in their pom.xml. For example the [bimviews-0.0.186 POM](https://github.com/opensourceBIM/bimvie.ws/blob/bimviews-0.0.186/pom.xml/pom.xml) declares a dependency on org.opensourcebim:pluginbase:1.5.184 to indicate it works with BIMserver version 1.5.184. Usually, the latest version of a plugin will either work with that latest BIMserver version or with a previous version, never with a future version. If a plugin declares dependency on only a previous BIMserver version, that means it has not been tested and updated with newer BIMserver versions by the maintainer. Depending on the interfaces the plugin uses and whether they have changed in the meantime, it might still work or not.

You can let BIMserver do the work of grabbing the version information in the POMs and comparing them to its own version: Just use the methods `PluginInterface.getAvailablePluginBundles` or `PluginInterface.getInstalledPluginBundles`. These will give you information on the latest version and max. 3 latest available versions. If "Strict plugin checking" is enabled in server settings, then these latest versions are guaranteed to be compatible, unless you work with a BIMserver snapshot version, where the strict checking is bypassed.

Note that the old [org.opensourcebim:bimsurfer][https://github.com/opensourceBIM/BIMsurfer-before2019/) plugin is not maintained anymore after version 0.0.64 (BIMserver 1.5.125) and you may want to use [BIMserver 3](https://github.com/opensourceBIM/BIMsurfer/) instead.

**Comment by myfulltexts** [comment]
Thanks for patiently answering my questions.

**Comment by hlg** [comment]
Is there an actual persisting issue or can this be closed?
