### ISSUE TITLE
Vulnerability : Server-Generated ACAO Header From Client-Specified Origin

### ISSUE THREAD

**Issue by sgwgsw** [opensourceBIM/BIMserver#1312]
https://github.com/opensourceBIM/BIMserver/blob/6daa43afdda3d25ebbd41e0d0de89361063e7142/BimServer/src/org/bimserver/servlets/JsonApiServlet.java#L53

The client's Origin header is reflected in the Access-Control-Allow-Origin header from the server, granting any domain access to CORS resources behind. There should be a white-list in the configuration that lists allowed Origin headers.

Client headers, such as Origin, should never be trusted. Hackers can control these headers when sending specially crafting links which will load some JS when clicked; once triggered, CORS requests can be executed with Origin headers set to attacker-controlled servers to steal data.

More info on vulnerability - https://portswigger.net/web-security/cors#server-generated-acao-header-from-client-specified-origin-header

**Comment by hlg** [comment]
Generic vulnerability report does not apply: There is indeed a whitelist which ist checked before setting the origin header.

**Comment by hlg** [comment]
Generic vulnerability report does not apply: There is indeed a whitelist which ist checked before setting the origin header.
