### ISSUE TITLE
Mavenize BIMserver codebase

### ISSUE THREAD

**Issue by lewismc** [opensourceBIM/BIMserver#143]
Hi Folks,
I recently checked out the codebase after not having touched it in a year or so.
Was surprised to see that there was no obvious mechanism for automating Java code compile and install from command line.
I propose to Mavenize the codebase making it a piece of cake to build, test, install, etc code from command line.

**Comment by orlade** [comment]
Is there any progress on this issue? My team has written a [BIMserver plugin](https://github.com/urbanetic/geotree-bimserver-plugin) with our internal Nexus repo as a source for the BIMserver Java libraries, but we can't build it publicly, on Travis for example. Deploying the libraries on Apache Central would be a great help for Java devs using BIMserver!

**Comment by lewismc** [comment]
Hi @orlade, I have a local patch which I will flush as a PR ASAP. I lost traction on this through Christmas and will get it posted here ASAP.
I am also extremely interested in consuming the BimServer .ifc xml parsing logic code as a jar which I intend to wrap as an Apache Tika parser. This was my original motivation to open an work on this issue.
I'll update here when finished. Thanks

**Comment by orlade** [comment]
Sorry to be a pest, but I'm coming back to our codebase again and getting Maven errors. Took me a minute to remember this was why. Any updates on this issue?

**Comment by rubendel** [comment]
Hi, mavenizing (or maybe "gradling") the codebase is actually on our roadmap now, but it's still a few months away if nobody does it earlier.
