### ISSUE TITLE
what the different id stands for?

### ISSUE THREAD

**Issue by reomomoon** [opensourceBIM/BIMserver#151]
There are so many interfaces in bimserver.org platform,most of them need oid, tid, roid ,or uoid input as parameters,but i am confused the followings, first，what the difference between oid and roid,and how can i get them quickly？Second, i get tid from startTransaction for getStringAttribute,but i am asked for an oid, what is this oid represented?

**Comment by rubendel** [comment]
Every object in BIMserver has an oid (ObjectID). This is true for IFC specific objects (like IfcProject, IfcWall etc...), but also for the objects BIMserver uses for administration of meta data, like Project, User, Revision etc... To make it easier to distinguish the ObjectID's, the ids of the meta data usually are called differently:

```
Project -> poid
Revision -> roid
User -> uoid
Transaction -> tid
```

So startTransaction will give you a tid (Transaction ID), which you will have to use for subsequent calls like getStringAttribute. The oid argument of the getStringAttribute refers to the object you want to get the string attribute from. For example this could be the oid of an IfcWall.
