### ISSUE TITLE
what is the best way to traversal model components?

### ISSUE THREAD

**Issue by reomomoon** [opensourceBIM/BIMserver#152]
i guess the Bimsie1LowLevelInterface offers most of the ways to modify model,but if i want to modify any of the object for example some beams of the first floor,how can i get them first? 
i kown bimql is an open query language as a plugin, i read one related paper last days and viewed the bimql.org to find some instance,and i test the examples in java but failed, is there any progress of BIMQL？
or maybe i can chose to  write java codes by myself? if so, do you have any advice for me ?

**Comment by rubendel** [comment]
BIMQL development is pretty much non existent at this moment, it would be nice if anyone picked it up. If you want to use the Java could, the most useful suggestion I think would be to learn to code in Java and have a look at the examples. If the example code does not work, please state more information like version number, log messages etc...

The Bimsie1LowLevelInterface should give have enough methods to build a client-side implementation that is more intuitive. We have done this for Java and JavaScript, which language do you use? To determine which floor is the first floor you'd want to get all of them first, and write you logic to determine which one is the first, that would be IFC specific (so make sure to read the IFC documentation as well).

**Comment by reomomoon** [comment]
Thanks for your response, JavaScript is the language I used to use,cause I'm concerned more about the front end of web，like BIMviews. Now  I want to modify the model and reorganise the tree database.I tried many ways.First i checked the bimserverapi.js and found the related APIs to call,but failed to get more details about each element,and then I checked  the source code of BIMServer, and found some useful java files,but i failed to call the internal service from front end,and now  i  maybe try to develope a plugin? I don't konw.Can you tell me how can  you get each element's attribute? Which means how can I acquire any element's attributes of the model,like the floor information,the type,the id ?(cause i want to get the elements like, All coulmns of floor 1, and chose several of them to show on the model)

**Comment by berlotti** [comment]
please have a look at the new query language implementation
