### ISSUE TITLE
How to query dimensions of the walls in the given design?

### ISSUE THREAD

**Issue by m2-bilal** [opensourceBIM/BIMserver#153]
Hi everyone,

Happy New Year.

I'm newbie to BIMserver and wants to fetch the width, height, and length of all the walls in the specified building design. How this can be achieved either through BIMQL or Java code and how to start about this. I've configure the latest version of BIMserver code in Oracle JDeveloper and have tested listing all the projects using Java code given on-line which was successful.

Any advice/hint/guidance will be highly appreciated.

Many Thanks

Kind Regards,

**Comment by berlotti** [comment]
have a look at the new query language in 1.4
