### ISSUE TITLE
Version: 1.3.6 does not deploy

### ISSUE THREAD

**Issue by timoutwente** [opensourceBIM/BIMserver#158]
Just tried to deploy version 1.3.6 (war) for the last two hours and run into very strange behavior. I can deploy the version just fine as ROOT, but if I try to deploy it in another folder, such as bimserver, I get a Http: 404 error.... 

This is for tomcat7 package version on Ubuntu server, I also tried with a manual tomcat install. 

There is nothing pointing to specific problems in the logs either.

**Comment by rubendel** [comment]
Which version of 1.3.6 is this, there should be a date in the filename as well?

**Comment by timoutwente** [comment]
Ruben -

sorry, I do not have this version any longer.... Guess you will need to
close this issue. My bad!

Timo

**Comment by rubendel** [comment]
Actually I have been able to reproduce this in newer versions as well and am working on a solution, will keep you posted

**Comment by rubendel** [comment]
There is a new build that fixes the 404 error
