### ISSUE TITLE
Deserializer Problem

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#159]
![image](https://cloud.githubusercontent.com/assets/10719871/5913694/74117294-a623-11e4-88f6-e38c8548a780.png)

     why can't choose Deserializer?? there is no options?   
     when i click checkin or download
     the error is :"Method getAllDeserializersForProject not found on org.bimserver.PluginInterface".

![image](https://cloud.githubusercontent.com/assets/10719871/5914101/31a2cb72-a62a-11e4-8172-0e0796d6492c.png)

   And i don't know how to use bimviewer view my model on browser ,help!!

**Comment by dlabz** [comment]
Usually, this would indicate that plugins didn't load correctly. If you are running BIMServer on linux, you should check file permissions.

**Comment by howlDream** [comment]
My BIMServer is on windows7.  My BIMServer version:(bimserver-1.3.4-FINAL-2014-10-17.jar ) ,
BIMViews version:(bimviews-1.3.11-FINAL-2015-01-16.jar)
I just according to the "Quick Guide" page to install BIMServer.   I don't know where is wrong.  %>_<%

**Comment by rubendel** [comment]
This version of BIMvie.ws does not work with BIMserver 1.3.4. Not that https://github.com/opensourceBIM/bimvie.ws/releases/tag/bimviews-1.3.9-FINAL-2014-11-21 is the latest BIMvie.ws release, the others are pre-releases.

**Comment by howlDream** [comment]
Thank you very very much！！ solved
