### ISSUE TITLE
Best Configuration to generate geometry and view in 3D

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#160]
Hi,
I am curious to know how I can make my BIMServer run super fast to generate geometry and then browser start loading those files in 3D view. 
I asking BIMServer to do tasks like sending IFC files to BIMServer and BIMServer will start generating geometry as soon as it receives IFC file. I want to make this process fast. My general IFC files size are more then 150MB. Currently it takes 45 mins to generate the geometry only and for view it takes 15 mins to view in 3D. 

Can some one check and suggest me solutions? I am using BIMServer 1.3.4 
Best configuration means what all server configurations I can do to work fast. I have attached screen shot.
![Uploading Screenshot from 2015-01-27 15:36:18.png . . .]()

**Comment by coryasilva** [comment]
You should probably be caching the binary JSON.  I recommend using BimServer as a service behind a Caching server and a reverse proxy.  That is how you will achieve "Super Fast" IMO.

**Comment by howlDream** [comment]
i can't see your screen shot.....

**Comment by vpanchal** [comment]
![image](https://cloud.githubusercontent.com/assets/846490/5932706/3e532786-a6d9-11e4-8827-ae340d28d93c.png)

Here is the screen-shot , I want to which all options I can use to have best and Super fast geometry generation.
![screenshot from 2015-01-27 15 36 18](https://cloud.githubusercontent.com/assets/846490/5932715/61c7839c-a6d9-11e4-85e5-4b97f94df7b6.png)

**Comment by vpanchal** [comment]
Hi,
To be clear on my understanding, Does it means that I should use that option of Cache output files ? 
But in my case the flow is different for ex.
Customer will upload IFC files in our system and as soon IFC uploaded it will be added a DB entry now I have Jboss schedular which does a task of geometry generation of IFC files in back ground. Now if customer will try to view that file in viewer which is BIMVie.ws  It start rendering the 3D view.

I want to make geometry generation task faster the which I have currently.

**Comment by coryasilva** [comment]
I do not think that the "cache output files" will work.  I was suggesting something more laborious like making you own caching server.

**Comment by rubendel** [comment]
Obviously converting the IFC geometry to triangles is the bottleneck here. I assume you are using the IfcOpenShell plugin to generate the geometry. You could change to the other implementation, which is also included in BIMserver, that one is a bit faster (IFC Engine DLL).

Unfortunately both "Render Engines" are currently single-core. We are looking into not sending the complete IFC file to the Render Engines (only geometry related objects), but that probably won't make a big difference. Another option I will look into later is to apply a model optimization before sending it to the "Render Engine", hopefully eliminating double work.

Caching of the output files will only work for the Serializers. The new type of serializer (MessagingSerializer) won't cache the data as it's not a file but a message-stream. Also the benefits of caching are not that great for geometry.

Running a server with SSD also makes things quite a bit faster.

**Comment by vpanchal** [comment]
Hey Ruben,
Thank you for proper explanations.
Are you talking about JvmRenderEnginePlugin , the other IFC Engine DLL?

**Comment by vpanchal** [comment]
Hey Ruben,
I tried that DLL plugin and it works like charm, I can tell you the status. The file which I tried to generate geometry for 1IFC file which has 172MB and high complexity components. It took 45 mins to generate geometry using IfcOpenShell engine and with IFC Engine DLL engine it took 4 mins and I am shocked. 
Thank you for making my day. 
Is there any Impact on DB or do I need to take care of anything else please let me know?

**Comment by vpanchal** [comment]
Hi All,
After few test of BIMServer installed on tomcat server the memory goes up and it doesn't come down? What can be the issue?
After the memory goes max level BIMServer stop responding. I have attached screen shot for more info.
![screenshot from 2015-01-30 15 31 40](https://cloud.githubusercontent.com/assets/846490/5974118/809523b0-a896-11e4-8d08-3ef11eb15973.png)

**Comment by dlabz** [comment]
@vpanchal : From my experience, the 3D model generated using IFC Engine DLL is probably missing quite a few elements. If I recall right, number of HVAC elements aren't rendered at all. 
It's very likely that those are the elements that slow down ifcOpenShell the most, as they tend to have thousands of vertices (high resolution angular pipe). The IFC DLL Engine simply skips them, giving you illusion of speed.

**Comment by rubendel** [comment]
@vpanchal To keep things organized, please open a new issue for the memory problems

As for the HVAC elements, I'll ask the developer of the IfcEngine DLL if this is a known issue.
