### ISSUE TITLE
BIMViews UI problem

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#161]
when I Launch Webbrowser  the Browser shows:    GETLOGGEDINUSER_BUSY

Anyone knows the problem ??

This happened when i change Web Moudle from Bimviews to another,and change it back. then i can't enter the BImserver.....

**Comment by rubendel** [comment]
You might have to clear your browser cache, as all of a sudden another application is being served on the same URL. Als after changing a web module, you need to restart BIMserver.

**Comment by howlDream** [comment]
Thank you！！☺
