### ISSUE TITLE
Should Bimsie1LowLevelInterface.createObject  assign a GUID to created object?

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#165]
Currently, object created is only assigned on oid. Leaving up to the user to generate guid's seems a bit messy, since guids are unique and relative to the oid.

**Comment by rubendel** [comment]
I think it would be nice to have this as an optional feature. There are probably cases where the client application wants to provide the GUID (as it might be their unique identifier, generated earlier). My suggestion would be to add another argument to the call createObject; "generateGuid" of type boolean. Of course this should only work for objects that have a a GUID property.

One reason for not doing this would be that the Bimsie1LowLevelInterface would become a little bit schema-specific, while right now it could be used for any schema.

**Comment by dlabz** [comment]
That makes sense. 
Though, since bimsie standard implements number of calls to query objects by GUID, but doesn't provide an option to generate, assign, or even check GUID's against the model, it seems that the decision was left to developers. Or it's a flaw in the standard. 
Assigning the GUID automatically does, technically, conform to the standard, and it's certainly possible to assign a specific GUID using a subsequent call, but I see how a piece of code written with that assumption might not work for software that doesn't assume the same. 
I had an idea to provide GUID generator interface, or even a service, but the problem remains.  

Seems that the only way to properly implement it is to generate a random GUID, and use Bimsie1LowLevelInterface.getDataObjectByGuid, to make sure it's actually unique. 

Relying on the GUID fixer service seems like a solution at first glance, but it only attaches a suffix to the duplicate GUID, which may be lost when compressing/decompressing it to enc64.

Or I'm over-thinking it...

**Comment by rubendel** [comment]
The GUID fixer service is just meant to be an example of a service.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/commit/bfef4005652c351f7fc36d0937d3fad9eb649997
