### ISSUE TITLE
BIMServer memory usage issue. 

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#166]
Hi All,
After few test of BIMServer installed on tomcat server the memory goes up and it doesn't come down? What can be the issue?
After the memory goes max level BIMServer stop responding. I have attached screen shot for more info.
![screenshot from 2015-01-30 15 31 40](https://cloud.githubusercontent.com/assets/846490/5987570/d571d0c8-a958-11e4-8674-e959844a47b4.png)

**Comment by berlotti** [comment]
I noticed you figured it out ;-)
