### ISSUE TITLE
No serializers

### ISSUE THREAD

**Issue by timoutwente** [opensourceBIM/BIMserver#168]
Version: 1.3.4
Date: 17-10-2014

I add a new project selecting ifc 2.3x, but the project that is created has no schema selected. Even worse, if I try to 'Checkin' I cannot select a deserializer. No projects can be checked in.

**Comment by rubendel** [comment]
This is most probably caused by using a version of BIMvie.ws that is not compatible with BIMserver 1.3.4-17-10-2014, which version of BIMvie.ws are you using? Do you see any errors in the JavaScript console?

**Comment by timoutwente** [comment]
Ruben -

yes I fixed this. The stack I am using is now:

1.3.4. 17-10-2014 bimserver

bimviews-11.3.11-FINAL-2015-01-17.jar

Thanks for your help!
Timo
