### ISSUE TITLE
1.4.0-FINAL-2015-02-19 not working on tomcat

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#179]
Neither of war versions work. 
tomcat8 version has no /stream servlet, so gui crashes on install.
no errors shown in log

tomcat7 version crashes with 
```
FAIL - Application at context path / could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
```

tested on ubuntu 14.10 and win7 x64

**Comment by rubendel** [comment]
This was fixed in 1.4.0-beta-2015-02-21
