### ISSUE TITLE
IFC4 Missing Attributes

### ISSUE THREAD

**Issue by arch1501** [opensourceBIM/BIMserver#183]
IfcPolyloop and IfcFace instances have no attributes.

**Comment by rubendel** [comment]
A little more information would be nice. Which version of BIMserver, anything in the log files? Can you share the IFC file you are using?

**Comment by arch1501** [comment]
With current prerelease!
Empty attribute list for at least
#38= IFCFACE(());
#20= IFCPOLYLOOP(());
#6991= IFCSTYLEDITEM(#5125,(),$);
Reproduced with IFC2x3 project downloaded as IFC4.

**Comment by arch1501** [comment]
And I forgot the broken boolean values now in both SPR serializers!

**Comment by rubendel** [comment]
The conversion from Ifc2x3tc1 to IFC4 is just an example that tries to do as much as possible automatically, manually written code will be necessary to create a useful implementation. The same for the other way around.

**Comment by rubendel** [comment]
Closing the issue as it is now clear this is about a converted project, not just IFC4

**Comment by arch1501** [comment]
This means for you conversion is not a functionality of the bim server?

**Comment by rubendel** [comment]
Correct, just like merging, the interfaces are there, the implementations are just examples of implementing the interface
