### ISSUE TITLE
Converting IFC2X3.EXP file to JAVA source error problem

### ISSUE THREAD

**Issue by chenmyGitHub** [opensourceBIM/BIMserver#184]
Hello, I was engaged in BIM geometry information to calculate the personnel, the need for IFC.exp file extension, and rebuild the Java source, but the source what I generation is different with BIMServer, 
what is the reason? Thank you very much!

my step is：
1.BuildingSmartLibrary change exp file to ecore
2.Generation JAVA source by ecore file
3.Importe the java source to BIMServer, but there is many error。

Thanks for your reply。

**Comment by rubendel** [comment]
I don't really understand what you are trying to do. The generated code is already in Git, why do regenerate it? In what way is the code different from the code generated earlier?
