### ISSUE TITLE
Support for binary fields

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMserver#186]
Something for the backlog.

The BIMserver has no support for BINARY fields. There's only two in the schema, IfcPixelTexture.Pixel and IfcBlobTexture.RasterCode, none of which ever used in real life.

However, when I do upload a model with a texture I get the following error message:
Error on line 67: Unknown feature IfcPixelTexture.Pixel

This is not surprising looking at the code, there is no code to handle binary attributes.
https://github.com/opensourceBIM/BIMserver/blob/52fd873ed2248a646ec9e935ea819ca2ddc94b0f/IfcPlugins/src/org/bimserver/ifc/step/deserializer/IfcStepDeserializer.java#L403
Binaries follow this simple grammar rule:

    BINARY = """" ( "0" | "1" | "2" | "3" ) { HEX } """" .

But the error obtained seems to suggest something already fails earlier on.

Here's a file:
https://raw.githubusercontent.com/aothms/IFC-files/patch-1/ifcopenshell/IfcTextureTest.ifc

**Comment by rubendel** [comment]
It's a known issue, shouldn't be too hard to fix, I think the database layer already supports binary, so only the serializers/deserializers should have to be fixed. See also: https://github.com/opensourceBIM/BIMserver/issues/16

**Comment by aothms** [comment]
Ah sorry. That's a clear duplicate. Well at least there is a test file now. I might be able to work on it at some point, but not in the very near future.

**Comment by rubendel** [comment]
Yeah thanks for the test file!

**Comment by rubendel** [comment]
This is implemented now. I am a bit confused by the documentation though. Your testfile has values of 9 hexadecimal characters. Are you sure that's right? Or should the component-count maybe be 4?

**Comment by aothms** [comment]
Cool! That's great news. You're right, count should be 4. Sorry about that.

"the encoding of a binary consists of k/4+1 hexadecimal digits."
That first leading hex digit specifies how many leading zeros to chop off.
