### ISSUE TITLE
Unicode support for project names (bimvie.ws + bimserver)

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMserver#189]
support characters for project names in bimserver.
See forum topic: 
http://support.opensourcebim.org/hc/communities/public/questions/201885339-UNICODE-support

**Comment by rubendel** [comment]
Pretty sure I fixed this before, probably missed it while merging 1.3/1.4. Fixed now in git master, will be in next release.

https://github.com/opensourceBIM/BIMserver/commit/efc8244f2bad6ea1dd5b672bb3fded686397bb50
