### ISSUE TITLE
getSuggestedDeserializerForExtension（） problem??

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#191]
My version：10-03-2015.
Run "TestUploadDir.java"  in the source code.
The Code:
public class TestUploadDir {
	private BimServerClient client;

	public static void main(String[] args) {
		new TestUploadDir().start();
	}

	private void start() {
		try {
			BimServerClientInterface client = LocalDevSetup.setupJson("http://localhost:8082");
			client.getSettingsInterface().setGenerateGeometryOnCheckin(false);
			File directory = new File("D:\\Testfiles");
			SProject project2 = client.getBimsie1ServiceInterface().getProjectByPoid(196609L);
			System.out.println("project:"+project2.getName());
			for (File f : directory.listFiles()) {
				process(f, project2);
				
			}
		} catch (ServiceException e) {
			e.printStackTrace();
		} catch (PublicInterfaceNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private void process(File directory, SProject parentProject) throws ServerException, UserException, PublicInterfaceNotFoundException, IOException {
		if (directory.isDirectory()) {
			SProject project = null;
			if (parentProject == null) {
				project = client.getBimsie1ServiceInterface().addProject(directory.getName(), "ifc2x3tc1");
				System.out.println("first!!!");
			} else {
				project = client.getBimsie1ServiceInterface().addProjectAsSubProject(directory.getName(), parentProject.getOid(), "ifc2x3tc1");
				System.out.println("second!!!");
			}
			for (File file : directory.listFiles()) {
				process(file, project);
				System.out.println("run!!!");
			}
		} else {
			String lowerCase = directory.getName().toLowerCase();
			if (lowerCase.endsWith("ifc") || lowerCase.endsWith("ifcxml") || lowerCase.endsWith("ifczip")) {
				System.out.println(lowerCase);
				SDeserializerPluginConfiguration deserializerForExtension = client.getBimsie1ServiceInterface().getSuggestedDeserializerForExtension(directory.getName().substring(directory.getName().lastIndexOf(".") +1), parentProject.getOid());
				System.out.println("Checking in " + directory.getAbsolutePath() + " - " + Formatters.bytesToString(directory.length()));
				try {
					client.checkin(parentProject.getOid(), "", deserializerForExtension.getOid(), false, true, directory);
				} catch (UserException e) {
					e.printStackTrace();
				}
			} else {
				System.out.println("Ignoring " + directory.getAbsolutePath());
			}
		}
	}
}
Console Result:

project:test2
Exception in thread "main" java.lang.NullPointerException
	at org.bimserver.test.TestUploadDir.process(TestUploadDir.java:82)  
      //  getSuggestedDeserializerForExtension()
	at org.bimserver.test.TestUploadDir.start(TestUploadDir.java:52)
	at org.bimserver.test.TestUploadDir.main(TestUploadDir.java:38)
in.ifc

How to solve ?????

**Comment by rubendel** [comment]
Fixed in https://github.com/opensourceBIM/BIMserver/commit/14644c870a0577a258ff8aa8c7398c3b97a6bbfd
