### ISSUE TITLE
Test   download()  and downloadQuery()   

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#194]
package org.bimserver.test;

import java.util.List;

import org.bimserver.LocalDevSetup;
import org.bimserver.interfaces.objects.SLongActionState;
import org.bimserver.interfaces.objects.SProject;
import org.bimserver.interfaces.objects.SQueryEnginePluginConfiguration;
import org.bimserver.interfaces.objects.SSerializerPluginConfiguration;
import org.bimserver.interfaces.objects.SUser;
import org.bimserver.plugins.services.BimServerClientInterface;
import org.bimserver.shared.PublicInterfaceNotFoundException;
import org.bimserver.shared.exceptions.ServiceException;

public class  MyTest{
	public static void main(String[] args) {
		try {
			BimServerClientInterface client = LocalDevSetup.setupSoap("http://localhost:8082");
			List<SProject> project=client.getBimsie1ServiceInterface().getProjectsByName("test2");
			SProject project1=project.get(0);
			long Poid=project1.getOid();
			SQueryEnginePluginConfiguration query1=client.getPluginInterface().getDefaultQueryEngine();
			long qeid=query1.getOid();
			System.out.println("qeid= "+qeid);
			String code=client.getServiceInterface().getQueryEngineExample(qeid, "Return all rooted entities");

			long roid=project1.getRid();
			System.out.println("roid= "+roid);
			SSerializerPluginConfiguration Serializer1=client.getPluginInterface().getDefaultSerializer();

			long serializerOid=Serializer1.getOid();
			SUser user=client.getServiceInterface().getUserByUserName("xxxx@xx.com");
			long uoid=user.getOid();
			
			if(client.getServiceInterface().userHasCheckinRights(uoid, Poid))
			{
				long topicId=client.getBimsie1ServiceInterface().download(roid, serializerOid, true, true);
				long topicId2=client.getBimsie1ServiceInterface().downloadQuery(roid, qeid, code, true, serializerOid);
				SLongActionState AState=client.getRegistry().getProgress(topicId);
				SLongActionState AState2=client.getRegistry().getProgress(topicId2);
				System.out.println("Title= "+AState.getTitle());
				System.out.println("Title2= "+AState2.getTitle());
			}
		} catch (ServiceException e) {
			e.printStackTrace();
		} catch (PublicInterfaceNotFoundException e) {
			e.printStackTrace();

RESULT:
qeid= 196684
roid= 12
Title= Revision with roid 12 not found
Title2= Revision with roid 12 not found

ERROR:
20-03-2015 09:35:53 ERROR org.bimserver.longaction.LongAction - 
org.bimserver.shared.exceptions.UserException: Revision with roid 12 not found
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:109)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Unknown Source)

why can't find the roid 12 ?

**Comment by rubendel** [comment]
Rid and Roid are not the same. If you want the latest roid from a project, use project.lastRevisionId
