### ISSUE TITLE
No PackageMetaData found for ifc2x3tc1

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#195]
version：BimServer -3-10
....
  IfcModelInterface model = client.getModel(project1, roid, false, false);
......

Exception in thread "main" java.lang.RuntimeException: No PackageMetaData found for ifc2x3tc1
	at org.bimserver.emf.MetaDataManager.getPackageMetaData(MetaDataManager.java:53)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:177)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:1)
	at org.bimserver.test.MyTest2.main(MyTest2.java:31)

**Comment by rubendel** [comment]
Did you include the plugin that provides the ifc2x3tc1 schema? https://github.com/opensourceBIM/BIMserver/wiki/Eclipse#adding-the-plugins-property

**Comment by howlDream** [comment]
Thank your reply!  Which file have the ifc2x3tc1 schema, can you tell me detailedly?
I have included all the plugins by the  << -plugins "C:\Users\My Name\Plugins">>  
.Are bleow the plugins?
![asd](https://cloud.githubusercontent.com/assets/10719871/6795553/a6b846f8-d21c-11e4-9ff2-e45fa97b93b0.png)

And when I run bimserver by LocalDevBimServerStarter.java      
the Exception is:   No schema plugins found
![we](https://cloud.githubusercontent.com/assets/10719871/6795598/cd3d9d68-d21d-11e4-8e0e-8fcaa250ee4c.png)

Than you!

**Comment by rubendel** [comment]
buildingSMARTLibrary should contain the schema. You are referring to the jar files, not sure if that works, can you use the BIMserver root directory (containing all the Eclipse projects)?

**Comment by howlDream** [comment]
Thank you！！solved！

**Comment by mguimard** [comment]
Hi, I'm facing a similar problem. This code ends with java.lang.RuntimeException: No PackageMetaData found for ifc2x3tc1

First I started the BIM server the logs seems to be OK : 

    23-09-2015 16:23:58 INFO  org.bimserver.BimServer - Starting BIMserver
    23-09-2015 16:23:58 INFO  org.bimserver.BimServer - Using "/path/to/bimserver/home" as homedir
    23-09-2015 16:24:02 INFO  org.bimserver.BimServer - Version: 1.4.0 - Mon Sep 14 00:00:00 CEST 2015
    23-09-2015 16:24:05 INFO  nl.tue.buildingsmart.emf.BuildingSmartLibraryIfc2x3tc1SchemaPlugin - IFC-Schema successfully loaded from /path/to/bimserver/home/tmp/IFC2X3_TC1.exp
    23-09-2015 16:24:05 INFO  nl.tue.buildingsmart.emf.BuildingSmartLibraryIfc4SchemaPlugin - IFC-Schema successfully loaded from/path/to/bimserver/home/tmp/IFC4.exp
    23-09-2015 16:24:05 INFO  org.ifcopenshell.IfcOpenShellEnginePlugin - Using exe/64/linux/IfcGeomServer
    23-09-2015 16:24:05 INFO  org.bimserver.cobie.plugin.idm.COBieIDM - Reading ignore file COBieIgnore.xml
    23-09-2015 16:24:05 INFO  org.bimserver.cobie.plugin.idm.COBieIDM - COBieIDMPlugin will ignore the following entities:  IfcBeamType,IfcColumnType,IfcCurtainWallType,IfcCovering,IfcCoveringType,IfcMemberType,IfcPlateType,IfcRailingType,IfcRampFlightType,IfcRampType,IfcSlabType,IfcStairFlightType,IfcStairType,IfcWallType,IfcDuctFittingType,IfcJunctionBoxType,IfcPipeFittingType,IfcCableCarrierSegmentType,IfcCableSegmentType,IfcDuctSegmentType,IfcPipeSegmentType,IfcFastenerType,IfcSpaceType,IfcAnnotation,IfcBeam,IfcBeamStandardCase,IfcColumn,IfcColumnStandardCase,IfcCurtainWall,IfcMember,IfcMemberStandardCase,IfcPile,IfcFooting,IfcPlate,IfcPlateStandardCase,IfcRailing,IfcRamp,IfcRampFlight,IfcRoof,IfcSlab,IfcSlabElementedCase,IfcSlabStandardCase,IfcStair,IfcStairFlight,IfcWall,IfcWallElementedCase,IfcWallStandardCase,IfcFlowFitting,IfcFlowFittingType,IfcFlowSegment,IfcFlowSegmentType,IfcCableCarrierSegment,IfcCableSegment,IfcDuctSegment,IfcPipeSegment,IfcElementAssembly,IfcBuildingElementPart,IfcFastener,IfcMechanicalFastener,IfcReinforcingBar,IfcReinforcingMesh,IfcFeatureElement,IfcFeatureElementAddition,IfcProjectionElement,IfcFeatureElementSubtraction,IfcOpeningElement,IfcOpeningStandardCase,IfcVoidingFeature,IfcSurfaceFeature,IfcVirtualElement,IfcDistributionPort,IfcStructuralActivity,IfcStructuralAction,IfcStructuralCurveAction,IfcStructuralLinearAction,IfcStructuralPointAction,IfcStructuralSurfaceAction,IfcStructuralPlanarAction,IfcStructuralReaction,IfcStructuralCurveReaction,IfcStructuralPointReaction,IfcStructuralSurfaceReaction,IfcStructuralItem,IfcStructuralConnection,IfcStructuralCurveConnection,IfcStructuralPointConnection,IfcStructuralSurfaceConnection,IfcStructuralMember,IfcStructuralCurveMember,IfcStructuralCurveMemberVarying,IfcStructuralSurfaceMember,IfcStructuralSurfaceMemberVarying
    23-09-2015 16:24:05 INFO  org.bimserver.cobie.plugin.idm.COBieIDM - Reading ignore file COBieIgnorePlusProxyObjects.xml
    23-09-2015 16:24:05 INFO  org.bimserver.cobie.plugin.idm.COBieIDM - COBieIDM IgnoreProxyObjects will ignore the following entities:  IfcBeamType,IfcColumnType,IfcCurtainWallType,IfcCovering,IfcCoveringType,IfcMemberType,IfcPlateType,IfcRailingType,IfcRampFlightType,IfcRampType,IfcSlabType,IfcStairFlightType,IfcStairType,IfcWallType,IfcDuctFittingType,IfcJunctionBoxType,IfcPipeFittingType,IfcCableCarrierSegmentType,IfcCableSegmentType,IfcDuctSegmentType,IfcPipeSegmentType,IfcFastenerType,IfcSpaceType,IfcAnnotation,IfcBeam,IfcBeamStandardCase,IfcColumn,IfcColumnStandardCase,IfcCurtainWall,IfcMember,IfcMemberStandardCase,IfcPile,IfcFooting,IfcPlate,IfcPlateStandardCase,IfcRailing,IfcRamp,IfcRampFlight,IfcRoof,IfcSlab,IfcSlabElementedCase,IfcSlabStandardCase,IfcStair,IfcStairFlight,IfcWall,IfcWallElementedCase,IfcWallStandardCase,IfcFlowFitting,IfcFlowFittingType,IfcFlowSegment,IfcFlowSegmentType,IfcCableCarrierSegment,IfcCableSegment,IfcDuctSegment,IfcPipeSegment,IfcElementAssembly,IfcBuildingElementPart,IfcFastener,IfcMechanicalFastener,IfcReinforcingBar,IfcReinforcingMesh,IfcFeatureElement,IfcFeatureElementAddition,IfcProjectionElement,IfcFeatureElementSubtraction,IfcOpeningElement,IfcOpeningStandardCase,IfcVoidingFeature,IfcSurfaceFeature,IfcVirtualElement,IfcDistributionPort,IfcStructuralActivity,IfcStructuralAction,IfcStructuralCurveAction,IfcStructuralLinearAction,IfcStructuralPointAction,IfcStructuralSurfaceAction,IfcStructuralPlanarAction,IfcStructuralReaction,IfcStructuralCurveReaction,IfcStructuralPointReaction,IfcStructuralSurfaceReaction,IfcStructuralItem,IfcStructuralConnection,IfcStructuralCurveConnection,IfcStructuralPointConnection,IfcStructuralSurfaceConnection,IfcStructuralMember,IfcStructuralCurveMember,IfcStructuralCurveMemberVarying,IfcStructuralSurfaceMember,IfcStructuralSurfaceMemberVarying,IfcBuildingElementProxyType,IfcBuildingElementProxy
    23-09-2015 16:24:05 INFO  org.bimserver.templating.TemplateEngine - Using "home/morgan/Apps/bimserver/bimserver-1.4.0-FINAL-2015-09-14/home/templates/" as template dir
    23-09-2015 16:24:05 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - Non-empty database directory found "/home/morgan/Apps/bimserver/home/database"
    23-09-2015 16:24:06 INFO  org.bimserver.ServerInfoManager - Changing server state to RUNNING
    23-09-2015 16:24:12 INFO  org.bimserver.JarBimServer - Server started successfully


Then I try a sample code which connects the server, creates a project and try to parse the model.

 PluginManager pluginManager = new PluginManager();

        MetaDataManager metadataManager = new MetaDataManager(pluginManager);

        BimServerClientFactory factory = new JsonBimServerClientFactory(metadataManager,"http://localhost:8082");
        // New client
        BimServerClientInterface bimServerClient = factory.create(new UsernamePasswordAuthenticationInfo("foo@bar.com", "foo"));

        // Create a project
        SProject project = bimServerClient.getBimsie1ServiceInterface().addProject("test" + Math.random(), "ifc2x3tc1");

        // Look for a deserializer
        SDeserializerPluginConfiguration deserializer = bimServerClient.getBimsie1ServiceInterface().getSuggestedDeserializerForExtension("ifc", project.getOid());

        // Checkin file
        bimServerClient.checkin(project.getOid(), "test", deserializer.getOid(), false, true, new File("myFile.ifc"));

        // Refresh project
        project = bimServerClient.getBimsie1ServiceInterface().getProjectByPoid(project.getOid());

        // Load model without lazy loading (complete model at once)
        IfcModelInterface model = bimServerClient.getModel(project, project.getLastRevisionId(), true, false);

I tried to start the server with and without the option -plugins path/to/plugins which contains the bimserver-1.4.0-FINAL-2015-09-14-buildingSMARTLibrary jar file. But the error is still the same.

I obviously missed something but I can't figure it out. Is there any other options to start the server with ? or any additional plugins to add to make it work ?

**Comment by rubendel** [comment]
It seems to me the BIMserver is running fine, but the code you use to connect to BIMserver is missing the schema. You create a PluginManager, but don't seem to load anything. It's not doing anything with the "plugins" parameter so it seems.

**Comment by mguimard** [comment]
Ok i'll try to load manually the needed plugin with the PluginManager API. This code is adapted from https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient. What is the BimServer version used by this examples ?

**Comment by rubendel** [comment]
Hi, I have updated the wiki page to match the latest released BIMserver.

https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient

**Comment by mguimard** [comment]
Hi, thanks for your help. I'm still having the issue. The server starts well, all plugins are loaded (server logs). I tried to load plugins within the git repository with the LocalDevPluginLoader.loadPlugins method, is this the proper way to load them ?

Here's the code I'm trying to make it work : 

    File[] pluginDirectories = new File[]{new File("/home/git/BIMserver")};

    PluginManager e = LocalDevPluginLoader.createPluginManager(new File("home"));
    LocalDevPluginLoader.loadPlugins(e,pluginDirectories);
    e.loadPluginsFromJar(new File("bim-client/lib/bimserver-1.4.0-FINAL-2015-09-23-buildingSMARTLibrary.jar"));

    MetaDataManager metaDataManager = new MetaDataManager(e);
     e.setMetaDataManager(metaDataManager);

    JsonBimServerClientFactory factory = new JsonBimServerClientFactory(metaDataManager, "http://localhost:8082");

    BimServerClientInterface bimServerClient = factory.create(new UsernamePasswordAuthenticationInfo("admin@bimserver.org", "admin"));

    // Create a new project
    SProject newProject = bimServerClient.getBimsie1ServiceInterface().addProject("test"+Math.random(), "ifc2x3tc1");

    // This is the file we will be checking in
    File ifcFile = new File("files/Stairs.ifc");

    // Find a deserializer to use
    SDeserializerPluginConfiguration deserializer = bimServerClient.getBimsie1ServiceInterface().getSuggestedDeserializerForExtension("ifc",newProject.getOid());

    // Checkin
    long roid = bimServerClient.checkin(newProject.getOid(), "test", deserializer.getOid(), false, true, ifcFile);

    // this line fails with No PackageMetaData found for ifc2x3tc1
    IfcModelInterface model = bimServerClient.getModel(newProject, roid, false, false);

Any hints ?

**Comment by timoutwente** [comment]
I am struggling with the same problem. Even worse if I connect from a remote instance using the LocalDevSetup.setupJson class, I get the same exception: 

No PackageMetaData found for ifc2x3tc1

**Comment by rubendel** [comment]
Hi, there are a few issues I think (combining my response to http://support.opensourcebim.org/hc/communities/public/topics/200051228-BIMserver-).

1. The MetaDataManager/PluginManager setup is confusing, I'll come up with a more usable solution
2. LocalDevSetup is (like it says in its comments, a convenience method for connecting to a locally running BIMserver, I'll add that it's also just for running in your IDE, with all the sources loaded) and with the default credentials.
3. It's not entirely clear to me if you guys are using the bimserve-client-lib download, or running from source (GIT).

**Comment by rubendel** [comment]
If you are using the downloaded version of the client, I just added a few missing dependencies (you probably are not using the download as you would have gotten errors about those missing dependencies). New build will be ready in 10 minutes.

Also updated the wiki page with one example, if you use the downloaded client. Will improve later. https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient

**Comment by timoutwente** [comment]
I can now connect without problems. However, there seems to be still a problem with lazily loading a model: 

IfcModelInterface model = client.getModel(project, project.getLastRevisionId(), true, false);

Exception in thread "main" java.lang.NullPointerException
	at org.bimserver.emf.SharedJsonDeserializer.processObject(SharedJsonDeserializer.java:289)
	at org.bimserver.emf.SharedJsonDeserializer.read(SharedJsonDeserializer.java:82)
	at org.bimserver.client.ClientIfcModel.processDownload(ClientIfcModel.java:298)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:287)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:95)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:180)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:74)
	at TestClass.main(TestClass.java:62)

**Comment by mguimard** [comment]
Works perfectly for me now many thanks

**Comment by rubendel** [comment]
Great, thanks for the feedback

**Comment by mguimard** [comment]
Using `client.getModel(project, project.getLastRevisionId(), false, false);` works but leads to empty IfcProject list when calling `model.getAll(Ifc2x3tc1Package.eINSTANCE.getIfcProject());`

However, when viewing the project in the webviewer, the file has been correctly uploaded and I can browse its structure.

Using `client.getModel(project, project.getLastRevisionId(), true, false);` leads to the same error than @timoutwente

**Comment by rubendel** [comment]
Hmm didn't test this all the way through, new build: https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-09-28

**Comment by mguimard** [comment]
Lazy loading now works well thanks. However `List<IfcProject> projects = model.getAll(Ifc2x3tc1Package.eINSTANCE.getIfcProject());` still results in an empty list. Is there any stuff to do before calling taht method ?

**Comment by rubendel** [comment]
Can you open a new issue for this please?

**Comment by howlDream** [comment]
good idea !

**Comment by rubendel** [comment]
New issue: https://github.com/opensourceBIM/BIMserver/issues/246
