### ISSUE TITLE
default web module setting is reset after BIMserver restart

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#196]
Selecting bimvews as the default webmodule will only be valid for the session, but will reset to "Default Web GUI" after restart.

issue present on:
BIMserver 1.4.0 10-03-2015 on tomcat7, ubuntu
Current master branch in eclipse on win64

**Comment by rubendel** [comment]
I think it only resetted after removing the database, but it's fixed now in GIT master
