### ISSUE TITLE
How to add a JSP file into the Tomcat ?

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#197]
I wrote a JSP file, I wonder how to make it work on the Tomcat  in the BimServer. 
Anybody  can help?

**Comment by rubendel** [comment]
I think if you add them to the www directory in the BIMserver project it should work when deployed on Tomcat. But why don't you just deploy a separate application with your JSP's?

**Comment by howlDream** [comment]
I tried,but it didn't work!  I dont' konw how the Tomcat work and how to deploy on Tomcat in Bimserver .  I used to open Tomcat in MyEclipse by the start button . So I 'm confused

**Comment by rubendel** [comment]
If you want to deploy things on Tomcat, I suggest you read the Tomcat documentation, it's a bit out of scope to support that here, sorry
