### ISSUE TITLE
Embedded BIMServer usage question.

### ISSUE THREAD

**Issue by carlosmmarques** [opensourceBIM/BIMserver#203]
Hello, 

I've ran into a couple of issues regarding the usage of embedded BIMServer (as suggested in the [Wiki](https://github.com/opensourceBIM/BIMserver/wiki/Embedding)):

* The method suggested is no longer supported - the [BimServer.class](https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/BimServer.java) constructor method has been replaced by the current method which takes a BIMServerconfig instance as a parameter;

* The CodeFetcher class in [InterfaceList.java](https://github.com/opensourceBIM/BIMserver/blob/master/Shared/src/org/bimserver/shared/InterfaceList.java) - In the public "get" method, the "url" property is defined using a hardcoded path to the "Shared/src" folder. This can be a problem while embedding the server. I used reflection to get the current instance's path (not a good solution). Will dig further into this.

**Comment by rubendel** [comment]
- I have updated the documentation on the wiki for 1.4: https://github.com/opensourceBIM/BIMserver/wiki/Embedding
- Hmm yes maybe this should be configurable. Are you embedding BIMserver by including the jar file in your IDE, or do you checkout the whole BIMserver project?

**Comment by carlosmmarques** [comment]
Thanks for the reply and update on the wiki.

I checked out the entire BIMServer project.
