### ISSUE TITLE
Project deletion rights

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMserver#208]
AFAICT, in order to delete a project, you need either to be an admin user, or AllowUsersToCreateTopLevelProjects needs to be set to true [1]

[1] https://github.com/opensourceBIM/BIMserver/blob/52fd873ed2248a646ec9e935ea819ca2ddc94b0f/BimServer/src/org/bimserver/database/actions/DeleteProjectDatabaseAction.java#L54

I administer a BIMserver in which several teams collaborate within their own project and organize it with subprojects to their liking. This is working great so far :) However, now if their organization evolves they would want to delete one or more subprojects, which they cannot, since they are not admins neither have they rights to create toplevel projects.

Is it likely this is going to change? Can another "subproject deletion setting" be introduced? Or should I just play with the options that are available to me now? Thanks.

**Comment by rubendel** [comment]
Cleaning up old issues :) This is not likely to change anytime soon. Almost anyone seriously using BIMserver (connecting their own application server with BIMserver through the BIMserver API) is now using it the way you use a database, with just one admin user.
