### ISSUE TITLE
IfcTriangulatedFaceSet

### ISSUE THREAD

**Issue by geope** [opensourceBIM/BIMserver#209]
In bimserver I tried to checkin an ifc4 file with IfcTriangulatedFaceSet and i obtained
"Error on line 7: Unknown feature IfcTriangulatedFaceSet.Normals" where in line 7 and next i have
#92= IFCTRIANGULATEDFACESET(#90,$,$,((0,1,2),(0,2,3),(4,0,3),..., $);
#90= IFCCARTESIANPOINTLIST3D(...);
#...
In  IFCTRIANGULATEDFACESET the normal list is optional, i don't export it and i replace it with the $ character.
Do you have any idea how to solve the problem ? Thanks in advance. Giorgio

**Comment by rubendel** [comment]
Can you share the particual IFC file (you can email to bug@bimserver.org if you want)?

**Comment by rubendel** [comment]
Thanks for sharing the file. The file seems to be valid. The normals attribute is a two-dimensional array, something that had not been used in Ifc2x3tc1. This will be fixed before the final 1.4 release.

**Comment by rubendel** [comment]
Fixed in master branch. It will upload without problems, but both the engines are not able to generate the geometry at this time.

**Comment by geope** [comment]
Ruben,

thanks for the update.
We know that our ifc is not completely correct and we are working to fix 
it.
Can i ask you if you know a ifc tester which can help us to obtain a 
correct ifc ?

thanks and kind regards,
Giorgio

On 14/05/2015 13:41, Ruben de Laat wrote:
>
> Fixed in master branch. It will upload without problems, but both the 
> engines are not able to generate the geometry at this time.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opensourceBIM/BIMserver/issues/209#issuecomment-102009917>.
>

-- 
*Giorgio Peterlunger*
DIGICORP Ingegneria S.r.l.
Via Duino, 1/1 I - 33100 Udine Italy
Phone +39 0432 511556 - fax +39 0432 511592
giorgio.peter@digicorpingegneria.com
http://www.digicorpingegneria.com

**Comment by rubendel** [comment]
Nope, there's not much software out there supporting IFC4 unfortunately.
