### ISSUE TITLE
Bimserver SMTP connection does not support Plain connection upgrade to TLS (STARTTLS connection)

### ISSUE THREAD

**Issue by Lawri-van-Buel** [opensourceBIM/BIMserver#211]
Bimserver only support 2 of the 3 commen type of SMTP connections
The 3 types are
 - SMTP (Plain text), World can read your mail.
 - SMTPS (Secure Socket connection), Encrypted from the start.
 - SMTP+TLS (STARTTLS), connection is made through plain SMTP, than the connection is secured with TLS (all trafic after that is secured)

Bimserver lacks support for the last type (STARTTLS). I found an article on how to enable it for java [on stackoverflow](http://stackoverflow.com/questions/411331/using-javamail-with-tls) but I do not have to time now to implement this. can this be added to the Bimserver core?

**Comment by LawriVanBuel-iDEVit** [comment]
I believe #76 is also due to this issue.

**Comment by rubendel** [comment]
Checked in code that should do this, but it's not tested, if you could find the time to do that, that would be great. It's in Git Master.
