### ISSUE TITLE
Bimsie1ServiceInterface.download

### ISSUE THREAD

**Issue by igunawardana** [opensourceBIM/BIMserver#213]
Hi,

I am calling the above service from a rest client, and following is my request,

{
  "token": "123456788765432be43aedd66d2703e52527dda0ff770c386ed3a692815982b2a0416ae97f26fe2bd842fdb",
  "request": {
    "interface": "Bimsie1ServiceInterface", 
    "method": "download", 
    "parameters": {
      "roid": "524291",
      "serializerOid": "3080230",
      "showOwn": "true",
      "sync": "false"
    }
  }
}

And it returns, 
{
  "response": {
    "result": 11
  }
}

Calling this service doesn't start downloading the file, I tried with setting following request headers too,
Accept-Encoding: gzip, deflate

What is the proper way of calling this service?

**Comment by dlabz** [comment]
The returned value is a topicId.  

You can check if the download preparing has completed by calling:  
```
{
  "token": "23456788765432be43aedd66d2703e52527dda0ff770c386ed3a692815982b2a0416ae97f26fe2bd842fdb",
  "request": {
    "interface": "Bimsie1NotificationRegistryInterface", 
    "method": "getProgress", 
    "parameters": {
      "topicId": "11"
    }
  }
}
```

once it completes, you need to build the download link and navigate to it to start download:  
```
http://127.0.0.1:8080/download?token=123456788765432be43aedd66d2703e52527dda0ff770c386ed3a692815982b2a0416ae97f26fe2bd842fdb&longActionId=11&serializerOid=3080230&topicId=11
```   

Also,  communication with BIMserver is done by SOAP protocol, not REST.

**Comment by igunawardana** [comment]
I got the following response for the request as you suggested,
{
response: {
result: {
__type: "SLongActionState"
end: null
errors: [0]
infos: [0]
oid: -1
progress: 0
rid: 0
stage: 2
start: 1433326780845
state: "STARTED"
title: "Done preparing"
warnings: [0]
}-
}-
}
Just for the clarification,
In download link longActionId=what? is it the same id as topicId or it should be the id of the above mentioned response (SLongActionState); But here I got -1 as the oid. I tried with placing the topicId and it worked.

**Comment by dlabz** [comment]
You use same topicId to get progress and download. In this case it's 11, and you set it in both  &topicId=11, for tracking download progress and &longActionId=11 to refer to the generated file.  

oid: -1 is just a placeholder for request that do refer an oid, and -1 simply tells that oid value isn't relevant, while maintaining the same response structure.

**Comment by igunawardana** [comment]
Thank you for the detailed information.
