### ISSUE TITLE
Model merger guide

### ISSUE THREAD

**Issue by igunawardana** [opensourceBIM/BIMserver#214]
I want to use a model merger and wondering how to use it, I could find the default model merger as follows,
{
  "response": {
    "result": {
      "__type": "SModelMergerPluginConfiguration",
      "description": "Basic merger",
      "enabled": true,
      "name": "Basic Merger",
      "oid": 393296,
      "pluginDescriptorId": 1769526,
      "rid": 1,
      "settingsId": 5046363,
      "userSettingsId": 131080
    }
  }
}

But how can I merge files? Is there a service to be called to get this done? I couldn't find any clue on this.

**Comment by dlabz** [comment]
Model merging is done by uploading IFC files to two or more sub-projects of a project, than downloading the top project.  
Work on merging plugins seems to be abandoned and merging doesn't produce a valid IFC file.

**Comment by igunawardana** [comment]
Thank you for the update.

**Comment by dishesh** [comment]
@igunawardana  @dlabz 
I can do the same in bimVie.ws page but how can I implement the same in my custom webapp where I want to get merged model  ?

Is it possible to merge only selected models to view ?
How can we load merged model directly using service or any other interface ?

**Comment by dlabz** [comment]
I’m not following the advancement, of BIMserver lately, but I guess idea remains the same. 

BIMserver is just that: a server. It provides you with an API for all it’s functionality. In fact, BIMvie.ws is (or at least was) just an illustration how to use the BIMserver. 

There shoul’d be a BIMsie plugin preinstalled with your BIMserver, that exposes all functionality needed for uploading, merging and rendering models.

**Comment by dlabz** [comment]
@dishesh 
P.S. This should get you started: https://github.com/opensourceBIM/BIMserver/wiki/Service-Interfaces
