### ISSUE TITLE
Clarification about Model Checker

### ISSUE THREAD

**Issue by igunawardana** [opensourceBIM/BIMserver#215]
Hi,

According to this [1] article Model Checker is used in two locations,  "before data is stored in the database, and before a notification to a remote service". I have a doubt about the validateModelChecker service, which can be found in the api. What is the usage of this service?
Does this service only validate the model checker not the models right?

Links:
[1] : http://bimserver.org/2014/04/28/release-1-3-0-final/

**Comment by rubendel** [comment]
Yes it does only check the model checker itself (the only model checker that is available right now will do this by compiling the Java code for it).
