### ISSUE TITLE
The bimviews plugin can't be set into the default web model.

### ISSUE THREAD

**Issue by 2120120928** [opensourceBIM/BIMserver#216]
Now I am building the latest open source bimserver with the build.xml from the github. After building, the server can run in my local computer, and I "Copy the bimvie-[version].jar file into the plugins subfolder under the bimserver-[version] folder". However, the default web model isn't the bimviews, the Web page remains on the page "Loading Bimviews" after I connect to the bimserver.
![default](https://cloud.githubusercontent.com/assets/12455505/8174824/0ef288e4-1414-11e5-999a-f4e6d8727a9c.PNG)
I don't know how to change the defaut web model. Hope someone can give me some advices.

**Comment by dlabz** [comment]
Seems  issue #196 is back...

**Comment by 2120120928** [comment]
OK, Thanks very much. I have tried again, and I found that the default web model changed to bimviews while I restarted the jar file after I delete the files under the database.
