### ISSUE TITLE
Change SMTP Port

### ISSUE THREAD

**Issue by wuestenfux** [opensourceBIM/BIMserver#217]
Hi there,

when i change the SMTP Port in the ServerSettings, and try to add a new User it says, that he couldn't connect via Port 25 (which is obviously wrong).
Any suggestion how to add an User or change the Port?

Thanks
ch

**Comment by rubendel** [comment]
Which version of BIMserver?

**Comment by wuestenfux** [comment]
Version 1.4.0

**Comment by rubendel** [comment]
When you view the server settings again, is the port changed?
