### ISSUE TITLE
tesselation

### ISSUE THREAD

**Issue by geope** [opensourceBIM/BIMserver#218]
I import an ifc4 file with tesselation presentation but i cannot see anything in bimvie.
Do yuo have any idea ? I send you the sample. 
(Another element i cannot see is PIPESEGMENT)

thanks in advance.

**Comment by aothms** [comment]
Hi,

BIMserver uses a library called IfcOpenShell for it's geometry interpretation. At the moment of latest release most IFC4 geometry types were not implemented yet. By now they are. You can either build a copy of the IfcOpenShell executable called IfcGeomServer yourself to incorporate the newest features or wait for the next release.

Kind regards,
Thomas
http://ifcopenshell.org
