### ISSUE TITLE
downloadByOids, downloadByTypes Services doesn't work as expected

### ISSUE THREAD

**Issue by igunawardana** [opensourceBIM/BIMserver#220]
1. I called the above services it returns the topic id.
2. Send the topic id to getProgress and the response comes as follows,
{
  "response": {
    "result": {
      "__type": "SLongActionState",
      "end": null,
      "errors": [],
      "infos": [],
      "oid": -1,
      "progress": 0,
      "rid": 0,
      "stage": 1,
      "start": 1435667546944,
      "state": "STARTED",
      "title": "Starting download",
      "warnings": []
    }
  }
}

3. Then I tried getDownloadData service but it just returned empty result as follows,
{
  "response": {
    "result": {}
  }
}

4. And I also tried using following url to download the expected data, but nothing recieved,
http://ip:port/bimserver/download?token={token}&longActionId=4&serializerOid=2687014&topicId=4

5. But I tried the same steps by calling download service and it worked.

What can be the reason behind this? Am I doing something wrong? Or the data that I am expecting is not there? I gave the IFCDOOR as a type to downloadByTypes, as it was there in ifc file which was checked in.

**Comment by dlabz** [comment]
There is a few things you might be doing wrong:  

1. response from getProgress should look like this when download is ready: 
```
{"response":{"result":{
"__type":"SLongActionState",
"end":null,
"errors":[],
"infos:[],
"oid":-1,
"progress":0,
"rid":0,
"stage":2,
"start":1435673937837,
"state":"STARTED",
"title":"Done preparing",
"warnings":[]
}}}
```

2. If you are using Javascript api with BIMserver 1.4.0, there is an issue which was fixed after FINAL release. You could try setting includeAllSubTypes to false in your initial request, to go around the issue, or get the updated bimserverapi.js

**Comment by igunawardana** [comment]
Thank you for the quick reply,

I am not using the javascript api, I am just calling services from api client application provide in bimview. 1.4.0-RC-2015-03-14 is the version of the bimserver I am currently using. How to get the 
"stage":1,
"state": "STARTED",
"title": "Starting download",

TO

"stage":2,
"state":"STARTED",
"title":"Done preparing",

I had been waiting for hours and tried but still the stage is 1. And "includeAllSubtypes": "false", is set in download request.

**Comment by dlabz** [comment]
You should check the BIMserver log for errors.

**Comment by igunawardana** [comment]
Found the following Null Pointer error when calling the downloadByTypes service.

01-07-2015 07:28:33 ERROR                                                                                  (org.bimserver.longaction.LongAction.java:187)
java.lang.NullPointerException
01-07-2015 07:28:33 ERROR                                                                                  (org.bimserver.BimServer.java:222)
java.lang.NullPointerException
        at org.bimserver.longaction.LongAction.changeActionState(LongAction.java:90)
        at org.bimserver.longaction.LongAction.error(LongAction.java:190)
        at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:67)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
        at java.lang.Thread.run(Unknown Source)


And the request I sent is,
{
  "token": "{token}",
  "request": {
    "interface": "Bimsie1ServiceInterface", 
    "method": "downloadByTypes", 
    "parameters": {
      "roids": ["327683"],
      "schema": "ifc2x3tc1",
      "classNames": ["IFCDOOR"],
      "serializerOid": "2687014",
      "includeAllSubtypes": "false",
      "useObjectIDM": "false",
      "deep": "false",
      "sync": "false"
    }
  }
}

Can this be because of, unavailability of IFCDOOR ?, but I double check the checked in file has IFCDOOR object as follows,

#7022= IFCDOOR('1hOSvn6df7F8_7GcBWlRGQ',#38,'M_Single-Flush:1250mm x 2010mm:1250mm x 2010mm:146596',$,'1250mm x 2010mm',#14080,#17208,'146596',2.009999999999999,1.25);

**Comment by rubendel** [comment]
IFCDOOR should be camelcased
