### ISSUE TITLE
Websocket error after setup

### ISSUE THREAD

**Issue by kieranc** [opensourceBIM/BIMserver#221]
Apache Tomcat/8.0.23
Java 1.7.0_79-b14
Debian 8.1 Linux 3.16.0-4-amd64
BIMserver 1.4.0-FINAL war
Firefox 38.0.5

I've been trying to get BIMserver WAR running in a usable state for a few weeks now but I keep coming up against this error, regardless of what I try. Setup completes successfully despite the error, I am logged in but all I see is "Loading BIMviews... ". When the error occurs, nothing is logged to catalina.out or bimserver.log.
I'm using BIMserver 1.4.0-FINAL, I've tried tomcat7, tomcat8 and jetty8 installed from apt on debian stable, plus tomcat7 and tomcat8 downloaded from apache on debian unstable.
I can launch and use the JAR version sucessfully on the same machine.
I've read the FAQ on websocket errors and none of them apply to me. I've tried several browsers, operating systems, computers etc. 

My process is as follows:
apt-get install tomcat8
wget bimserver-1.4.0.war
set JAVA_HOME and JAVA_OPTS in /etc/defaults/tomcat8
copy bimserver-.1.4.0.war to /var/lib/tomcat8/webapps/ROOT.war
start tomcat
access bimserver admin page, complete setup, receive 'Websocket error' (in red, at the top of the screen)

I would really like to evaluate this software properly but it's proving difficult.

**Comment by coryasilva** [comment]
Are you going through a web proxy/firewall or is this on a LAN?

**Comment by kieranc** [comment]
Nope, all local.

**Comment by coryasilva** [comment]
In the browser's developer tools > network.  Does the server ever respond to the upgrade connection request?

**Comment by kieranc** [comment]
The last request is for http://ipaddesss:8080/stream, and results in a 404 error... Seems like it could be the problem.

**Comment by dlabz** [comment]
As far as I know, tomcat8 build isn't working. Try using tomcat7

**Comment by kieranc** [comment]
Wow, thanks for taking the time to respond, but that really seems like information which ought to be written down somewhere. Using tomcat7 from apache and the tomcat7 build of 1.4.0, I've got past the Websocket error.

Thanks again!

**Comment by ysangkok** [comment]
I get the same problem with Jetty Runner 9.
