### ISSUE TITLE
bimviews view problem

### ISSUE THREAD

**Issue by ulrick** [opensourceBIM/BIMserver#224]
Hello all!
I've installed the bimserver 1.4.0-FINAL (execute the .jar file) in windows7 for a local test. When I run my server, I can use bimview to navigate into pages but when I move to another PC trying to   connect to the bimserver, I just have this message :  "loading bimviews". (see screenshot)
Can anybody help me please?

![bimviews2015-07-17 08_41_32](https://cloud.githubusercontent.com/assets/5559181/8742096/ed92c298-2c61-11e5-9f34-f438f1ef7681.png)

**Comment by rubendel** [comment]
Do you see anything in the browser's console?

**Comment by ulrick** [comment]
I get this : "Uncaught ReferenceError: SceneJS is not defined".
I can get the projects page if I put this directly in  the browser : http://localhost:8082/?page=Projects

**Comment by niwakame** [comment]
Have the same problem using the BIMserver master branch.

I did run a submodules recursive update, but the bimsurfer directory in AdminGui/js was missing.
After adding it manually from the BIMsurfer repository, it still fails with the same SceneJS error.

Error occurs in [index.html Line 123](https://github.com/opensourceBIM/BIMserver/blob/master/AdminGui/index.html#L123)

**Comment by fern1978** [comment]
I have the same problem. I'm sucesfully installed bimserver in tomcat, and I can work in my locahost but... when I try to connect from the outside... Loading BIMviews... and nothing else. Anyone has got the solution?

**Comment by rubendel** [comment]
Did you enter the right address on which the server runs in server settings?

**Comment by fern1978** [comment]
Yes, I've tried by placing in server settings localhost:8080 and also the external IP:8080 and it doesn´t works, I have opened and nat the external IP to that local port (I'm also have tried with 8082) 
Are there some additional ports to be opened... maybe to allow java connections?

Thanks!

**Comment by rubendel** [comment]
Yes you should allow Java on the given port, no other ports are used. Did you include http:// in the address? Does BIMserver bind on the external IP? Did you configure Tomcat to listen on the public IP?

**Comment by fern1978** [comment]
Finally i did it. Thanks a lot ! - the external ip should be included both in the BIMserver Starter and in server settings when you're logged. This works for me with the tomcat7-1.4.0.jar - Thanks again!

But...the previous is working as an independent server running in :8082, but stills doesn´t works integrated in tomcat with the .war file. How can I access to the BIMserver Starter settings when I use it as a webapp?  I don't know if I've been unclear...

Anyway, congratulations for your work.

**Comment by rubendel** [comment]
Have a look in the tomcat server.xml configuration file (and the related documentation), you can specify the ip/port combination to bind to.

**Comment by signalsaeed** [comment]
Dear rubendel, thanks for your information, but How to add BIMvie.ws to BIMserver and in which folder? can you please write the exact address we should write in run configuration of eclipse? and after running BIM server, we should just see the "loading views.."? how to add our projects to its environment?

**Comment by sundiyone** [comment]
![image](https://cloud.githubusercontent.com/assets/2330438/25735904/46f6d55e-31a1-11e7-8749-3105e48c5e82.png)
![image](https://cloud.githubusercontent.com/assets/2330438/25735937/7c97fdb4-31a1-11e7-8d8a-72eaa37aa16a.png)
