### ISSUE TITLE
BIM local development

### ISSUE THREAD

**Issue by ulrick** [opensourceBIM/BIMserver#226]
Hello!
I've cloned the BIMserver project and configured it in eclipse. I started and runned it, but in the browser, when I put "localhost:8080/admin", I just have this information : "Loading BIMviews...".
I'am blocked and don't know what to do to continue.

![bimviews2015-07-17 08_41_32](https://cloud.githubusercontent.com/assets/5559181/8772110/3e019844-2ec9-11e5-92b5-437f626b2643.png)

**Comment by niwakame** [comment]
That's the same problem as #224, I suppose

**Comment by berlotti** [comment]
could you provide the log file?

**Comment by ulrick** [comment]
I have this in the browser console :
Uncaught ReferenceError: SceneJS is not defined   admin:123
(anonymous function) @ admin:123 
@ admin:28j 
@ admin:29

**Comment by rubendel** [comment]
Did you also check out BIMvie.ws?

**Comment by ulrick** [comment]
Sorry I don't speak much english. what do you mean by 'check out' BIMvie.ws? How can I do it?

**Comment by rubendel** [comment]
Well what do you expect to see in you browser? If it is BIMvie.ws you expect, then you should check it out (or clone as it's called in GIT terminology). Also make sure you add the BIMvie.ws plugin to your eclipse run configuration.

**Comment by rubendel** [comment]
There was a bug in BIMsurfer/BIMviews, should work now

**Comment by signalsaeed** [comment]
Dear rubendel, thanks for your information, but How to add BIMvie.ws to BIMserver and in which folder? can you please write the exact address we should write in run configuration of eclipse? and after  running BIM server, we should just see the "loading views.."? how to add our projects to its environment?

**Comment by niwakame** [comment]
1. Check out BIMserver
2. Check out BIMvie.ws [This one](https://github.com/opensourceBIM/bimvie.ws), _not_ [that one](https://github.com/opensourceBIM/bimvie.ws-viewer) into a separate directory
3. Run BIMserver once to generate run configuration, e.g. LocalDevBimServerStarter
4. Enter run configurations
5. Switch to "Arguments" tab
6. Edit "Program arguments" to
  -plugins "/path/to/BIMServer" -plugins "/path/to/bimvie.ws" (no trailing slash)

And now you'll have a working BIMvie.ws, which should be detected during startup. If you want to be sure it's detected, edit PluginManager.java to include a **System.out.println** here:
```java
public void loadAllPluginsFromEclipseWorkspaces(File directory, boolean showExceptions) throws PluginException {
		...
		if (new File(directory, "plugin/plugin.xml").exists()) {
			System.out.println("Found plugin xml in directory: "+directory);
			if (showExceptions) {
				loadPluginsFromEclipseProject(directory);
			} else {
				loadPluginsFromEclipseProjectNoExceptions(directory);
			}
		}
		...
```

So, this is working now, but I'm still missing the /admin page where I can set the initial credentials. Therefore, I can't login to BIMvie.ws :(

**Comment by rubendel** [comment]
Thanks for the clear description, this all sounds good. BIMvie.ws should actually be active at the root path. So http://localhost:8080. Can you try to clear your browser cache?
