### ISSUE TITLE
BIMserver 1.4 with Wildfly 9.0

### ISSUE THREAD

**Issue by atibaut** [opensourceBIM/BIMserver#228]
I tried to run BIMserver within the AS WildFly. The .war file is deployed without errors, but with some (I think non-critical) warnings. The server launches with the set-up page. When I enter my new user details and confirm I got the "WebSocket error". 
Screenshot is here:
<img width="813" alt="screenshot 2015-07-24 11 32 31" src="https://cloud.githubusercontent.com/assets/2762514/8871775/1cf90e70-31f8-11e5-8bfa-0a33de33bd50.png">

WildFly log is here:
Herango:bin andrejt$ /bin/bash standalone.sh 
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /Users/andrejt/Projects/Programiranje/wildfly-9.0.0.Final

  JAVA: java

  JAVA_OPTS:  -server -XX:+UseCompressedOops  -server -XX:+UseCompressedOops -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
11:26:10,441 INFO  [org.jboss.modules] (main) JBoss Modules version 1.4.3.Final
11:26:12,529 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
11:26:12,580 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Full 9.0.0.Final (WildFly Core 1.0.0.Final) starting
11:26:13,334 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 24) WFLYCTL0028: Attribute 'job-repository-type' in the resource at address '/subsystem=batch' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
11:26:13,343 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 21) WFLYCTL0028: Attribute 'enabled' in the resource at address '/subsystem=datasources/data-source=ExampleDS' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
11:26:14,038 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
11:26:14,053 INFO  [org.xnio] (MSC service thread 1-7) XNIO version 3.3.1.Final
11:26:14,061 INFO  [org.xnio.nio] (MSC service thread 1-7) XNIO NIO Implementation Version 3.3.1.Final
11:26:14,082 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 53) WFLYSEC0002: Activating Security Subsystem
11:26:14,082 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 54) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
11:26:14,087 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 37) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
11:26:14,090 INFO  [org.jboss.as.security] (MSC service thread 1-3) WFLYSEC0001: Current PicketBox version=4.9.2.Final
11:26:14,101 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 44) WFLYJSF0007: Activated the following JSF Implementations: [main]
11:26:14,101 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 38) WFLYCLINF0001: Activating Infinispan subsystem.
11:26:14,135 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 46) WFLYNAM0001: Activating Naming Subsystem
11:26:14,144 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 56) WFLYWS0002: Activating WebServices Extension
11:26:14,146 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 55) WFLYUT0003: Undertow 1.2.8.Final starting
11:26:14,146 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0003: Undertow 1.2.8.Final starting
11:26:14,160 INFO  [org.jboss.as.connector] (MSC service thread 1-1) WFLYJCA0009: Starting JCA Subsystem (IronJacamar 1.2.4.Final)
11:26:14,165 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 33) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
11:26:14,180 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-6) WFLYJCA0018: Started Driver service with driver-name = h2
11:26:14,265 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
11:26:14,265 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-8) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
11:26:14,266 INFO  [org.jboss.remoting] (MSC service thread 1-7) JBoss Remoting version 4.0.9.Final
11:26:14,357 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 55) WFLYUT0014: Creating file handler for path /Users/andrejt/Projects/Programiranje/wildfly-9.0.0.Final/welcome-content
11:26:14,382 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0012: Started server default-server.
11:26:14,394 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0018: Host default-host starting
11:26:14,469 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0006: Undertow HTTP listener default listening on /127.0.0.1:8080
11:26:14,581 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
11:26:14,682 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-5) WFLYDS0013: Started FileSystemDeploymentService for directory /Users/andrejt/Projects/Programiranje/wildfly-9.0.0.Final/standalone/deployments
11:26:14,685 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0027: Starting deployment of "bimserver-1.4.0-2015-07-20.war" (runtime-name: "bimserver-1.4.0-2015-07-20.war")
11:26:14,772 INFO  [org.jboss.ws.common.management] (MSC service thread 1-7) JBWS022052: Starting JBoss Web Services - Stack CXF Server 5.0.0.Final
11:26:17,995 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jsr-275-1.0-beta-2.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/geoapi-2.3-M1.jar  does not point to a valid jar for a Class-Path reference.
11:26:17,997 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jsr-275-1.0-beta-2.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/geoapi-pending-2.3-M1.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,005 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-api-2.2.12-b140109.1041.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-core-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,006 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry istack-commons-runtime-2.19.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-core-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,006 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry txw2-2.2.10-b140310.1920.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-core-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,006 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-core.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-impl-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,007 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-core.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-xjc-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,007 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-impl.jar in /content/bimserver-1.4.0-2015-07-20.war/WEB-INF/lib/jaxb-xjc-2.2.10-b140310.1920.jar  does not point to a valid jar for a Class-Path reference.
11:26:18,552 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-7) WFLYSRV0018: Deployment "deployment.bimserver-1.4.0-2015-07-20.war" is using a private module ("org.apache.cxf.impl:main") which may be changed or removed in future versions without notice.
11:26:18,552 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-7) WFLYSRV0018: Deployment "deployment.bimserver-1.4.0-2015-07-20.war" is using a private module ("org.apache.cxf.impl:main") which may be changed or removed in future versions without notice.
11:26:18,739 WARN  [org.jboss.as.ee] (MSC service thread 1-3) WFLYEE0007: Not installing optional component org.springframework.web.context.request.async.StandardServletAsyncWebRequest due to an exception (enable DEBUG log level to see the cause)
11:26:33,973 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 63) Initializing Mojarra 2.2.11-jbossorg-1 20150505-1501 for context '/bimserver-1.4.0-2015-07-20'
11:26:40,235 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 63) WFLYUT0021: Registered web context: /bimserver-1.4.0-2015-07-20
11:26:40,262 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "bimserver-1.4.0-2015-07-20.war" (runtime-name : "bimserver-1.4.0-2015-07-20.war")
11:26:40,340 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
11:26:40,341 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
11:26:40,341 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 9.0.0.Final (WildFly Core 1.0.0.Final) started in 30128ms - Started 284 of 465 services (221 services are lazy, passive or on-demand)

Can you advice me how to solve the problem? 

Best regards,
Andrej

**Comment by berlotti** [comment]
We don't use or test on JBoss/Wildfly. 
I know Sam Wu uses it a lot in combination with BIMserver. Maybe he can help you:  https://www.linkedin.com/in/samjwu
