### ISSUE TITLE
BIMViews in 1.4.0-FINAL-2015-05-14 breaks example1.js from BIMSurfer library

### ISSUE THREAD

**Issue by shazada** [opensourceBIM/BIMserver#229]
In privious versions the example1.js from BIMSurfers worked well. Now when using it and loading, the method geometryLoader.setLoadTypes(project.lastRevisionId, project.schema, toLoad); Gives an error TypeError: o.options.types.map is not a function.

This method brakes it:
var types = o.options.types.map(function(type){
					return type.name;
				});

So I rewrote this:
var types = [];
				$.each(o.options.types, function(key, value){
					types.push(key);
				});
And no error what so ever, but no view aswell :(

After I click around an select/deselect elements I get the following errors:

ReferenceError: assignment to undeclared variable event PickFlyOrbit_37c148a0f35b1e18fceb45c41e589aa1.js:1:8528
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture and its width or height is equal to zero. scenejs.js:1:86613
uncaught exception: Incomplete framebuffer: FRAMEBUFFER_INCOMPLETE_ATTACHMENT <unknown>
Error: WebGL: clear: incomplete framebuffer scenejs.js:1:249845
Error: WebGL: clear: incomplete framebuffer scenejs.js:1:87784
Error: WebGL: clear: incomplete framebuffer scenejs.js:1:249845
Error: WebGL: readPixels: incomplete framebuffer scenejs.js:1:87960
Error: WebGL: clear: incomplete framebuffer scenejs.js:1:87784
Error: WebGL: clear: incomplete framebuffer scenejs.js:1:249845
Error: WebGL: readPixels: incomplete framebuffer scenejs.js:1:87960

**Comment by berlotti** [comment]
indeed the example of BIM Surfer is not compatible with BIMserver 1.4

**Comment by starcn16888** [comment]
Very regrettable

**Comment by rubendel** [comment]
example1 is working again, with latest BIMserver release
