### ISSUE TITLE
Bimsie1LowLevelServiceImpl getReferences throw ClassCastException and NPE

### ISSUE THREAD

**Issue by pandreev** [opensourceBIM/BIMserver#230]
Trying to cast org.eclipse.emf.ecore.util.EObjectEList to java.util.List in List<IdEObject> list = (List<IdEObject>) object.eGet(object.eClass().getEStructuralFeature(referenceName)) throws ClasscastException.

Also object.eGet(object.eClass().getEStructuralFeature(referenceName)) throws NPE as object.eClass().getEStructuralFeature(referenceName) can be null.

**Comment by rubendel** [comment]
A little more information would be useful, on what kind of object do you call this method, and what is the name of the reference?
