### ISSUE TITLE
REQUEST: Importing 2D geometry from IfcOpenShell

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#235]
IfcOpenShell recently added generation of 2D geometry:  
http://blog.ifcopenshell.org/2015/07/creating-2d-svg-floor-plans-from-ifc.html

Extending BIMserver to use new functionality would allow generation of floor plans and sections / elevations.

**Comment by bb14521** [comment]
How to import ifc file in BIMserver  and view it ?
