### ISSUE TITLE
Collision (Clash) detection in bimserver

### ISSUE THREAD

**Issue by igunawardana** [opensourceBIM/BIMserver#238]
Hi,

I'm interested about the collision detection feature integrated in BIMServer. Following blog post http://bimserver.org/2012/12/20/first-release-candidate-version-1-2/ explains about the clash detection feature, and it is a plugin. But I am interested to know which component does the clash detection part, is it a separate component like mvdXMLChecker?
Can a plugin be exposed as a service?

Thanks in adavance
Isuru

**Comment by rubendel** [comment]
We decided to remove this feature from BIMserver some time ago. Clash detection was part of the interface between BIMserver and the "RenderEngine" plugins (like RDF Engine and IfcOpenShell), but IfcOpenShell never had clash detection, and RDF engine does not have it anymore as well.

This has also left the ClashDetectionServicePlugin non-working.

**Comment by aothms** [comment]
Clash detection is on the IfcOpenShell roadmap for version 0.8.0:
https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/b5e3ee85/#b6b2

Kind regards,
Thomas

**Comment by niharikapothani** [comment]
Missing NotificationsUrl status when adding the clash detection service to a project file in BIM server1.5.51?

Please help
