### ISSUE TITLE
Trying to deploy BIMserver to remote linux server

### ISSUE THREAD

**Issue by connoralexander** [opensourceBIM/BIMserver#239]
Hi,

I've been trying to deploy the latest BIMserver 1.4 (final release) to a Digital Ocean box running Ubuntu 14.04 through Tomcat 8. Every time I deploy the war file through tomcat, once it has finished unpacking and deploying I lose the connection to the port and seem to be unable to see either the BIMserver or tomcat splash page. Every time the connection is now refused. All config files in tomcat seem to be pointing correctly and netstat doesn't show anything unusual on the ports...

Has anyone successfully deployed the latest bimserver on the latest tomcat with ubuntu 14.04? Will there be any updates to the wiki or developers guide?

I followed the guide for the older versions of BIMserver and tomcat and even that consistently failed. Help would be appreciated.

**Comment by rubendel** [comment]
I have had problems with Tomcat 8, can you try Tomcat 7? Also, what's in the log files?

**Comment by connoralexander** [comment]
I can try tomcat 7 yes, I will give it a go. I have managed to get everything working up until the BIMserver setup page now (I was running out of memory before and had to change the web.xml) however it only works for a bit and if I try and set it up i have a websocket error. Is this the problem you were getting?

Log files aren't saying anything I can find... the only thing is a json package isnt being delivered I can see from chromes developer window

**Comment by rubendel** [comment]
Well the running out of memory was in the log files right? Yes the websocket error probably is being caused by a broken Tomcat8 build, will have a look at that soon.

**Comment by connoralexander** [comment]
Yeah the memory error was in logs, I meant about this websocket error sorry.. Ok I'll try tomcat 7 today. Thanks for your help!

**Comment by connoralexander** [comment]
i am getting the same issue with the websocket with tomcat 7 as well. I'm guessing something within the BIMserver is conflicting with the websocket API that comes with tomcat? Can you shed any light on this?

**Comment by rubendel** [comment]
Did you use the Tomcat7-specific build? I'll release a working Tomcat8 version today.

**Comment by connoralexander** [comment]
Hey, yeah I used the bimserver build with tomcat7 in the title. I can try with another one? Ideally I want to be using the latest tomcat and bimserver, of course. That is fantastic you're releasing the tomcat8 ver. today :) what sort of time? Should I wait around for it today?

**Comment by connoralexander** [comment]
I've seen you've updated for websockets fix :D - will you be creating a new release compilation today too? or should I clone the repo?

**Comment by rubendel** [comment]
Still working on it, github seems to have updated their releases API, so can't do an automated build... will be after the weekend I guess...

**Comment by connoralexander** [comment]
ahhh ok that's cool man, thanks for your efforts! I have been persisting with the ubuntu14.04 + tomcat8 + bimserver 1.4.0 builds to try and sort it out. Had a brief bit of luck writing a new ENV for a tomcat classpath but didn't succeed. Currently the only error I'm getting in logs is (hence writing the classpath in):

11-Sep-2015 15:29:29.142 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath

maybe this might help?

**Comment by rubendel** [comment]
You should not have to do anything with ENV, the latest build works with both Tomcat 8 and Tomcat 7.0.47. That's not an error, it says "INFO".

**Comment by bb14521** [comment]
Is it working on Ubuntu 14.04 ?
I am also trying to deploy the BIMserver on ubuntu 14.04. i have problem with  tomcat config file server.xml and startup script. after downloading WAR file, it should be automatically extracted acc. to startup script but it doesn't happen. 
any body can tell me where is the problem ?
   
 /opt/tomcat7/conf/server.xml      http://pastebin.com/tGkaT1vW

/etc/init.d/tomcat7                        http://pastebin.com/w5ttwVrx

**Comment by rubendel** [comment]
It is working on Ubuntu 14.04. Did you have a look at the Tomcat log file? Is it even running? As I told you in another issue you created about the exact same problem, these are all Tomcat related issues, read the documentation/search the internet to get it working.

**Comment by connoralexander** [comment]
I have made a Dockerfile to install the BIMserver inside a docker container which sets everything up for you. 
https://github.com/BIMscript/docker-bimserver
https://hub.docker.com/r/bimscript/docker-bimserver/
If you just install ubuntu 14.04 and docker then run the code in the description whilst ssh'd into the server it should have BIMServer and tomcat8 set up.

**Comment by rubendel** [comment]
Nice!

**Comment by bb14521** [comment]
On Wed, Sep 30, 2015 at 2:27 PM, Connor Alexander
<notifications@github.com> wrote:
>
> I have made a Dockerfile to install the BIMserver inside a docker container which sets everything up for you.
> https://github.com/BIMscript/docker-bimserver
> https://hub.docker.com/r/bimscript/docker-bimserver/
> If you just install ubuntu 14.04 and docker then run the code in the description whilst ssh'd into the server it should have BIMServer and tomcat8 set up

Thank you for reply.
Sorry i couldn't get you, can you tell me what and how i have to do exactly ?


-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by bb14521** [comment]
I am facing error  "Please specify a TOMCAT_USER environment variable" (still searching )
I am trying as u mention, simple i am ssh for remote server and enter the dockerfile 
i have attached the screenshots exactly what i did.

**Comment by connoralexander** [comment]
spin up a new server with ubuntu14.04, then update and install docker with

$ curl -sSL https://get.docker.com/ | sh

then, with docker installed (check with $ docker ps) run:

$ docker run -d \
    -e TOMCAT_USER=xxx \
    -e TOMCAT_PASSWORD=xxx \
    -p 8080:8080 \
    bimscript/docker-bimserver

either leaving the 'xxx' as is or replace the 'xxx' on the username and password with whatever username and password you want for tomcat (not your IP which is what you've put in)

Then in a browser go to: IP:8080/BIMserver and it will load it up. (you will have to wait for 5 mins whilst tomcat installs and deploys itself and bimserver)

**Comment by bb14521** [comment]
Thanks for  your  appreciation Mr. Connoralexander. 
I am facing the error from this script.  
"Post http:///var/run/docker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
![screenshot from 2015-10-03 10 35 00](https://cloud.githubusercontent.com/assets/5606588/10261537/7eb82ed0-69ba-11e5-8ca3-35569eea584a.png)

**Comment by bb14521** [comment]
Now is the problem with  
"Unable to find image 'bimscript/docker-bimserve:latest' locally
Pulling repository docker.io/bimscript/docker-bimserve
Error: image bimscript/docker-bimserve:latest not found"



![q](https://cloud.githubusercontent.com/assets/5606588/10261814/4999a05e-69c8-11e5-877a-738b6cdf8c4a.png)

**Comment by bb14521** [comment]
What is looks like while installing ? 

![l](https://cloud.githubusercontent.com/assets/5606588/10261826/f9147c2a-69c8-11e5-9371-6141390b158b.png)

**Comment by bb14521** [comment]
Yeah! its working 
![screenshot from 2015-10-03 13 05 49](https://cloud.githubusercontent.com/assets/5606588/10261935/c61e65d6-69cf-11e5-8db8-0549a9189986.png)


Thank you very much,  Mr.connoralexander and  Mr.rubendel.

**Comment by bb14521** [comment]
How to remove it completely from the server. i want to install fresh copy of it in my server.

**Comment by rubendel** [comment]
Remove the .war file. If you defined your BIMserver home directory, also remove that.

**Comment by connoralexander** [comment]
If you have installed it with the dockerfile you can see the docker container and docker image with

$ docker ps
$ docker images

then remove them with $ docker rm XXXX or $ docker rmi XXXX where XXXX is the container/image

see the docker documentation for details

**Comment by bb14521** [comment]
I have installed it using the dockerfile. but i have delete the ROOT.war manually from /var/www/bbr/ROOT.war  and remove tomcat. 
i got this error while sudo docker ps or images 
![screenshot from 2015-10-12 23 35 37](https://cloud.githubusercontent.com/assets/5606588/10434900/026d4f22-713a-11e5-9ea3-3b529690fcbb.png)

**Comment by bb14521** [comment]
On Mon, Oct 12, 2015 at 1:48 PM, Connor Alexander
<notifications@github.com> wrote:
>
> If you have installed it with the dockerfile you can see the docker container and docker image with
>
> $ docker ps
> $ docker images
>
> then remove them with $ docker rm XXXX or $ docker rmi XXXX where XXXX is the container/image
>
> see the docker documentation for details


Got it, thank you

-- 



--------------------------

**Comment by bb14521** [comment]
i have install BIMserver on ubuntu 14.04 using tomcat 8

https://bhushanbharat.wordpress.com/2015/10/13/install-bimserver-on-ubuntu-14-04/

**Comment by rubendel** [comment]
Cool, thanks, added to the wiki: https://github.com/opensourceBIM/BIMserver/wiki/Install-on-Ubuntu

**Comment by bb14521** [comment]
Thank you very much Mr. Ruben de Laat.

On Sun, Oct 18, 2015 at 12:20 PM, Ruben de Laat <notifications@github.com>
wrote:

> Cool, thanks, added to the wiki:
> https://github.com/opensourceBIM/BIMserver/wiki/Install-on-Ubuntu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opensourceBIM/BIMserver/issues/239#issuecomment-148985533>
> .
>



-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521
