### ISSUE TITLE
Select JVM path in Launcher on OSX

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMserver#241]
Hi,

I'm failing to start the BIMserver on OSX, probably due to spaces in the path to the newly installed JVM. Oracle does not let me install to a path without spaces. Could not copy the text so can only provide a screen-shot.

<img width="1680" alt="screen shot 2015-09-11 at 11 39 40" src="https://cloud.githubusercontent.com/assets/1096535/9812196/f4ae04ca-587b-11e5-86d8-d467976b3b76.png">

Kind regards,
Thomas

**Comment by rubendel** [comment]
I tried to fix this, but I can't test it, as on my mac, I am not able to move the JDK to a path _with_ spaces ;). Can you try the next build?

**Comment by aothms** [comment]
Many thanks. Unfortunately it's not my system and I have been told the problem still persists with the latest build, but I don't think I will get a chance to investigate more. Maybe use ProcessBuilder(List<String> command) to start the process, so that the space escaping does not have to be done manually?

**Comment by rubendel** [comment]
Thanks for the tip, implemented ProcessBuilder, created new release:

https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-09-14

**Comment by rubendel** [comment]
Do you know if this is working now?

**Comment by aothms** [comment]
I have another student checking this, will get back to you. Many thanks for the commit!

**Comment by aothms** [comment]
In the end I have advised the student to install the JDK on OSX, as the stand-alone JRE was still causing problems, the empty class path we have emailed about. The JDK is installed into a path without spaces, but not sure if that's related. Using the JDK runtime works well apparently.
