### ISSUE TITLE
Getting project list from IFC2X3TC1 file

### ISSUE THREAD

**Issue by mguimard** [opensourceBIM/BIMserver#246]
Hi, I'm using the latest bim-client and bim-server from download area (bimserver-1.4.0-FINAL-2015-09-28).

I'm loading an IfcModel

    client.getModel(project, project.getLastRevisionId(), false, false)

Then I try to get the project list

    List<IfcProject> projects = model.getAll(Ifc2x3tc1Package.eINSTANCE.getIfcProject());

This list is always empty.

I also tried to get the IfcProduct list in the same way 

        List<IfcProduct> products = model.getAllWithSubTypes(IfcProduct.class);

This is also empty.

I tried with various Ifc2x3 models, and all of them give the same result.
Browsing the projects in the webviewer shows the right structure.

Am I missing something ?

**Comment by rubendel** [comment]
Strange, can you share your full code? Because I am getting IfcProject/IfcProducts here.

**Comment by mguimard** [comment]
Sure, here's the code :

    package com.foo.bar;

    import org.bimserver.LocalDevPluginLoader;
    import org.bimserver.client.json.JsonBimServerClientFactory;
    import org.bimserver.emf.IfcModelInterface;
    import org.bimserver.emf.MetaDataManager;
    import org.bimserver.emf.Schema;
    import org.bimserver.interfaces.objects.SDeserializerPluginConfiguration;
    import org.bimserver.interfaces.objects.SProject;
    import org.bimserver.models.ifc2x3tc1.Ifc2x3tc1Package;
    import org.bimserver.models.ifc2x3tc1.IfcBeam;
    import org.bimserver.models.ifc2x3tc1.IfcProduct;
    import org.bimserver.models.ifc2x3tc1.IfcProject;
    import org.bimserver.plugins.PluginException;
    import org.bimserver.plugins.PluginManager;
    import org.bimserver.plugins.services.BimServerClientException;
    import org.bimserver.plugins.services.BimServerClientInterface;
    import org.bimserver.shared.BimServerClientFactory;
    import org.bimserver.shared.ChannelConnectionException;
    import org.bimserver.shared.PublicInterfaceNotFoundException;
    import org.bimserver.shared.UsernamePasswordAuthenticationInfo;
    import org.bimserver.shared.exceptions.ServiceException;
    
    import java.io.File;
    import java.io.IOException;
    import java.util.List;
    
    public class Tmp {
    
        public static void main(String[] args) throws PluginException, ServiceException, ChannelConnectionException, PublicInterfaceNotFoundException, IOException, BimServerClientException {

            // Client-side, we also use a PluginManager, for example to be able to use the (IFC) schemas
            PluginManager pluginManager = LocalDevPluginLoader.createPluginManager(new File("home"));

            // Create a MetaDataManager, and initialize it, this code will be simplified/hidden in the future
            MetaDataManager metaDataManager = new MetaDataManager(pluginManager);
            pluginManager.setMetaDataManager(metaDataManager);
            metaDataManager.init();

            // Initialize all loaded plugins
            pluginManager.initAllLoadedPlugins();

            // Create a factory for BimServerClients, connnect via JSON in this case
            BimServerClientFactory factory = new JsonBimServerClientFactory(metaDataManager, "http://localhost:8082");

            // Create a new client, with given authorization, replace this with your credentials
            BimServerClientInterface client = factory.create(new UsernamePasswordAuthenticationInfo("admin@bimserver.org", "admin"));

            SProject project = client.getBimsie1ServiceInterface().addProject("tmp-" + Math.random(), Schema.IFC2X3TC1.getEPackageName());

            // Look for a deserializer
            SDeserializerPluginConfiguration deserializer = client.getBimsie1ServiceInterface().getSuggestedDeserializerForExtension("ifc", project.getOid());

            File ifcFile = new File("files/foo.ifc");

            client.checkin(project.getOid(), "test", deserializer.getOid(), false, true, ifcFile);

            // Refresh project
            project = client.getBimsie1ServiceInterface().getProjectByPoid(project.getOid());


            // Load model without lazy loading (complete model at once)
            IfcModelInterface model = client.getModel(project, project.getLastRevisionId(), false, false);

            List<IfcProject> projects = model.getAll(Ifc2x3tc1Package.eINSTANCE.getIfcProject());
            List<IfcProduct> products = model.getAllWithSubTypes(IfcProduct.class);
            List<IfcBeam> beams = model.getAllWithSubTypes(IfcBeam.class);

            if (projects.size() != 1){
                throw new RuntimeException("The IFC model should have only one IfcProject");
            }

         }
    }

**Comment by rubendel** [comment]
Do you have a log4j.xml configuration file on your path? If not, try adding one, the logs might show more information.

**Comment by mguimard** [comment]
Thanks for your help, turning log4j in debug mode shows the error :

    ERROR ClientIfcModel - 
    org.bimserver.plugins.deserializers.DeserializeException: No SchemaDefinition available
    	at org.bimserver.emf.SharedJsonDeserializer.read(SharedJsonDeserializer.java:58)
    	at org.bimserver.client.ClientIfcModel.processDownload(ClientIfcModel.java:298)
    	at org.bimserver.client.ClientIfcModel.getAllWithSubTypes(ClientIfcModel.java:411)
    	at org.bimserver.ifc.IfcModel.getAllWithSubTypes(IfcModel.java:310)
    	at com.foo.bar.Tmp.main(Tmp.java:67)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by rubendel** [comment]
Ok, please update the first part of your code to the example on https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient. Sorry, forgot to mention that I updated that page as well. Main line:

```
// Load all plugins available on the classpath
pluginManager.loadPluginsFromCurrentClassloader();
```

**Comment by mguimard** [comment]
Done, there's a missing dep (antlr)

   Exception in thread "main" java.lang.NoClassDefFoundError: antlr/collections/AST

**Comment by timoutwente** [comment]
Yes. The dependencies are missing the antlr lib. I added it via maven:

<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr4</artifactId>
			<version>4.1</version>
		</dependency>

and it works perfectly!

This is wonderful. You rock Ruben!

**Comment by rubendel** [comment]
Ah thanks, fixed in git, will make a new release

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-09-29
