### ISSUE TITLE
how to contribute to Wiki

### ISSUE THREAD

**Issue by bb14521** [opensourceBIM/BIMserver#247]
I am unable to find the file  wiki, i have to make some changes in Install on ubuntu Documentation

**Comment by rubendel** [comment]
Let me know what needs changing and I'll change it. We don't intend to give out write permissions too easily.

**Comment by bb14521** [comment]
On Wed, Sep 30, 2015 at 2:10 PM, Ruben de Laat <notifications@github.com> wrote:
>
> Let me know what needs changing and I'll change it. We don't intend to give out write permissions too easily.


Make a change in the "install Tomacat"  wget link is not working. and
in  next line  download with name " -O tomacat7.zip " and unzip with "
unzip apache7.zip.


-- 



--------------------------
Bharat Bhushan Rathore

http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by rozsasarpi** [comment]
Change suggestion to the wiki:

1.
Page: https://github.com/opensourceBIM/BIMserver/wiki/Get-Started-Quick-Guide
Current: On you mac Oracle advises to install the JDK...
Suggestion: On Mac, Oracle advises to install the JDK...

2. The get started guide for standalon BIMServer is outdated:
https://github.com/opensourceBIM/BIMserver/wiki/Get-Started-Quick-Guide

Suggestion: update step 6 and above
