### ISSUE TITLE
server client in C#

### ISSUE THREAD

**Issue by geope** [opensourceBIM/BIMserver#249]
Good evening,
we have a client application in C# that uses a rest api to request data from bimserver. We use JSON as exchange standard, the bim server (1.4.0-FINAL-2015-09-29) contains a simple model (house) and it's running on Windows 8.1 with JRT. When we request Bimsie1ServiceInterface.getDownloadData, using the server Ifc4 (or Ifc2x3) serializer, we obtain  a stream of characters unrecognizable, not the row sequence in step standard. Do you have any idea about our problem ?
Thanks in advance.
Giorgio

**Comment by coryasilva** [comment]
I think you are receiving binary json.  You may want to look at the BimSurfer source code:
https://github.com/opensourceBIM/BIMsurfer/blob/master/api/DataInputStream.js

**Comment by dlabz** [comment]
Actually, it might even be compressed IFC file. Magic number for gzip is 1f 8b, and 10 bit header should be followed by the file_name.ifc  

BIMserver will compress any stream, if client request header has Accept-Encoding set:
```
Accept-Encoding:gzip, deflate, sdch
```

**Comment by geope** [comment]
Here is a sample of the response we get from the bimserver:
[RestSharp.RestResponse] = "StatusCode: OK, Content-Type: application/json; charset=UTF-8, Content-Length: 29324)"
Content = "{\"response\":{\"result\":{\"__type\":\"SCheckoutResult\",\"file\":\"SVNPLTEwMzAzLTIxOwpIRUFERVI7CkZJTEVfREVTQ1JJUFRJT04gKCgnSUZDNCcpLCAnMjsxJyk7CkZJTEVfTkFNRSAoJ0M6XFxGaWxlVGVzdFxcSUZDXFx0ZW1wLmlmYycsICcyMDE1LTA2LTIyVDE1OjQzOjA1JywgKCcnKSwgKCcnLCAnJyksICc...
ContentEncoding = ""
ContentLength = 29324
ContentType = "application/json; charset=UTF-8"
Cookies	Count = 0	
ErrorException = null
ErrorMessage = null
Headers = Count = 9
RawBytes = {byte[29324]}
Request = {RestSharp.RestRequest}
ResponseStatus = Completed
ResponseUri = {http://diwin2012r2dns.cloudapp.net:8082/json}
Server = "Jetty(9.2.5.v20141112)"
StatusCode = OK
StatusDescription = "OK"

Is the content commpressed json ?

**Comment by dlabz** [comment]
Headers indicate it's a non-compressed, UTF-8 encoded JSON.  

If you post the data received, I could decode the header and tell you what data received is.

**Comment by dlabz** [comment]
OH!

That file is enc64 encoded to string, than wrapped in JSON. I replied from the phone earlier, and didn't see tje response...

**Comment by rubendel** [comment]
All binary data is encoded base64, in this case the "file" data, this is quite inefficient, but we want to allow developers to use all functionality via the standard interfaces (JSON, PB and SOAP).

However specifically for downloading serialized data, there is another way, which is a lot more efficient. You can use the "/download" URL for this. This is used in bimserver/bimvie.ws as well.

**Comment by geope** [comment]
Thanks to all for the replay and the suggestions.
