### ISSUE TITLE
SMTP in BIM server 

### ISSUE THREAD

**Issue by bb14521** [opensourceBIM/BIMserver#250]
Can we add SMTP server or any other mailing server on BIMserver. 
when i click reset password. it has to be send email on the user E-maill ID.

**Comment by rubendel** [comment]
Have a look at "Server Settings"

**Comment by bb14521** [comment]
On Mon, Oct 5, 2015 at 12:37 PM, Ruben de Laat <notifications@github.com> wrote:
>
> Have a look at "Server Settings"


Already explore it.  there was the problem with my postfix, so now i
am trying to reconfigure it.
which mailing server is best  for that ?


-- 



--------------------------
Bharat Bhushan Rathore


http://techbbr.blogspot.in/
https://github.com/bb14521
