### ISSUE TITLE
Import Ifc file on BIMserver 

### ISSUE THREAD

**Issue by bb14521** [opensourceBIM/BIMserver#251]
I am unable to import ifc file on BIMserver .  
Can i get any help ?

**Comment by kaurav** [comment]
Hi
I have installed BIMServer successfully. but I got stuck in importing .Ifc openshell file. Neither I found any way to import that file nor any plugin.

**Comment by rubendel** [comment]
@bb14521 Please be more specific, any error messages? Up to what point does it work?

@kaurav What do you mean with .ifc openshell file? Also, explain what happens, saying 
"stuck" could mean anything in this context.

**Comment by bb14521** [comment]
On Tue, Oct 6, 2015 at 12:27 PM, Ruben de Laat <notifications@github.com> wrote:
>
> @bb14521 Please be more specific, any error messages? Up to what point does it work?
>


I have installed BIMserver but i don't know what to do next.  my
requirement import ifc file in BIMserver.
i have been told by someone to make changes in the python directory
/usr/lib/python2.7/dists-package/  and import openshell package.
I didn't get anything.

--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by kaurav** [comment]
On Tue, Oct 6, 2015 at 12:27 PM, Ruben de Laat <notifications@github.com> wrote:
> @kaurav What do you mean with .ifc openshell file?

I just need to import ifc file.


-- 
--
Avi kaur
Blog: https://avikashyap620.wordpress.com
"There is no lacking of opportunity, The thing is you do not want to see It"

**Comment by rubendel** [comment]
@bb14521 BIMserver is written in Java, there is no need to do anything with python

@kaurav You still haven't given any information about where you get stuck, what have you tried?

**Comment by berlotti** [comment]
@bb14521 @kaurav have you seen this: https://github.com/opensourceBIM/BIMserver/wiki/Get-Started-Quick-Guide ?

**Comment by bb14521** [comment]
On Tue, Oct 6, 2015 at 3:46 PM, Léon van Berlo <notifications@github.com> wrote:
>
> @bb14521 @kaurav have you seen this: https://github.com/opensourceBIM/BIMserver/wiki/Get-Started-Quick-Guide ?


I am extremely sorry sir. Someone misguided me. He was working with
FreeCAD. I have gone through the Quick guide, but didn't find the way.
Please guide me in right direction.


-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by berlotti** [comment]
Did you install the bimvie.ws plugin?

**Comment by kaurav** [comment]
On Tue, Oct 6, 2015 at 3:41 PM, Ruben de Laat <notifications@github.com> wrote:

> @kaurav You still haven't given any information about where you get stuck, what have you tried?

My BIMserver is perfectly working on my laptop. I want to know how to
import ifc file in BIMserver. I have added a project in BIMserver with
name room. and I want to import ifc file of room from my computer to
BImserver.






-- 
--
Avi kaur
Blog: https://avikashyap620.wordpress.com
"There is no lacking of opportunity, The thing is you do not want to see It"

**Comment by berlotti** [comment]
So I guess you are using bimvie.ws, since you have created a project.
Now click on the triangle besides the project name. You will get a small menu with the option 'checkin model'.

**Comment by bb14521** [comment]
On Tue, Oct 6, 2015 at 4:32 PM, Léon van Berlo <notifications@github.com> wrote:
>
> So I guess you are using bimvie.ws, since you have created a project.
> Now click on the triangle besides the project name. You will get a small menu with the option 'checkin model'.

i am already try this. i got error like this

org.bimserver.utils.TokenizeException: No ( found in /* description */
('ViewDefinition [PresentationView]', 'Comment [Ironworkers Training
Structure (1),SDS/2 Detailed model]'),/* implementation_level */ '2;1



-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by bb14521** [comment]
On Tue, Oct 6, 2015 at 4:32 PM, Léon van Berlo <notifications@github.com> wrote:
>
> So I guess you are using bimvie.ws, since you have created a project.
> Now click on the triangle besides the project name. You will get a small menu with the option 'checkin model'.


Yeah ! i am done. problem was in the server, its not properly
installed. i just reinstall opensource BIMserver and now  its working
fine. but there are issue with some ifc file they are not properly
render(i think that ifc file corrupted)

 Thank you Mr. Leon van Berlo and  Mr.Ruben de Laat.


--

**Comment by bb14521** [comment]
Try to upload a file, got error:

com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'I'
(code 73) in prolog; expected '<' at [row,col {unknown-source}]: [1,1]

why i am got  this error ? .

How to select Deserializer, Schema and units?

On Tue, Oct 6, 2015 at 2:43 PM, Bharat Bhushan <bb14521@gmail.com> wrote:
> On Tue, Oct 6, 2015 at 4:32 PM, Léon van Berlo <notifications@github.com> wrote:
>>
>> So I guess you are using bimvie.ws, since you have created a project.
>> Now click on the triangle besides the project name. You will get a small menu with the option 'checkin model'.
>
>
> Yeah ! i am done. problem was in the server, its not properly
> installed. i just reinstall opensource BIMserver and now  its working
> fine. but there are issue with some ifc file they are not properly
> render(i think that ifc file corrupted)
>
>  Thank you Mr. Leon van Berlo and  Mr.Ruben de Laat.
>
>
> --



-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by rubendel** [comment]
What file did you try to upload? What is the extension? It should be .IFC. If it is IFC, a deserializer should have been selected automatically. Now you just tried to deserialize a file using the IFC XML deserializer.

**Comment by bb14521** [comment]
On Wed, Oct 7, 2015 at 1:21 PM, Ruben de Laat <notifications@github.com>
wrote:
>
> What file did you try to upload? What is the extension? It should be
.IFC. If it is IFC, a deserializer should have been selected automatically.
Now you just tried to deserialize a file using the IFC XML deserializer.

Yeah! its ifc file  here is the link of ifc file with name BIMhouse.ifc
http://lab.gdy.club/~bharat/



-- 



--------------------------
Bharat Bhushan Rathore

http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by bb14521** [comment]
And why its select deserialize automatic ?

On Thu, Oct 8, 2015 at 11:09 AM, Bharat Bhushan <bb14521@gmail.com> wrote:

>
> On Wed, Oct 7, 2015 at 1:21 PM, Ruben de Laat <notifications@github.com>
> wrote:
> >
> > What file did you try to upload? What is the extension? It should be
> .IFC. If it is IFC, a deserializer should have been selected automatically.
> Now you just tried to deserialize a file using the IFC XML deserializer.
>
> Yeah! its ifc file  here is the link of ifc file with name BIMhouse.ifc
> http://lab.gdy.club/~bharat/
>
>
>
> --
>
>
>
> --------------------------
> Bharat Bhushan Rathore
>
> http://techbbr.blogspot.in/
> https://github.com/bb14521
>



-- 



--------------------------
Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by rubendel** [comment]
Because that makes life easier... If you think a valid IFC gets rejected by BIMserver, please send the IFC file to bug@bimserver.org and we'll have a look.

**Comment by kaurav** [comment]
On Tue, Oct 6, 2015 at 4:32 PM, Léon van Berlo <notifications@github.com> wrote:
>
> So I guess you are using bimvie.ws, since you have created a project.
> Now click on the triangle besides the project name. You will get a small menu with the option 'checkin model'.

Yes, It has started working now. Thank you for your help :). It has
started rendering now.



--
Avi kaur
Blog: https://avikashyap620.wordpress.com
"There is no lacking of opportunity, The thing is you do not want to see It"
