### ISSUE TITLE
Invalid token 

### ISSUE THREAD

**Issue by bb14521** [opensourceBIM/BIMserver#256]
Suddenly my BIMserver is not working .. it gives a error while starting invaild token. 

 here is a  link to my BIMserver http://lab.gdy.club:8080/BIMserver 

i have check the .log file its terminate the process without any error.

**Comment by rubendel** [comment]
If this happened after resetting your BIMserver, it could have been this bug: https://github.com/opensourceBIM/BIMserver/commit/0741f6c94b78eeffcef1dc9c70ea5d99f49d44e3
