### ISSUE TITLE
Can't query entities or extract geometry

### ISSUE THREAD

**Issue by abdoulayediak** [opensourceBIM/BIMserver#262]
Hi all,

I'm very new to BIMserver, and I struggled a little bit to understand how it works, but now it's OK, I have the BIMvie interface, I can load and see my IFC models properly in my web browser.

What I am trying to do next is to query some entities in a model, for example IfcDoor, and extract them by exporting them in a Collada file, since I mainly need their geometries. To do so, I go to the "Query" tab of the interface, I choose BimQL Engine and I load the example producing the following code:

<b>
Select $Var1
Where $Var1.EntityType = IfcDoor
</b>

Then when I click on the Query button and choose Collada as Serializer, it seems to proceed on some extraction, but at the end it produces a small file of 17 KB named "null.dae" (sometimes "query.dae"), in which there is some text similar to a Collada file but, no geometry at all. I tried several other serializers (json, ifc, etc) but the error message on the log was always the same:

<b><i>
ERROR nl.wietmazairac.bimql.BimQLQueryEngine - GeometryInfo not found
</i></b>

I went through the FAQ but I couldn't find similar issue. So I am wondering what is wrong between my way of using BimQL, the IFC models I have (I tried many) or maybe just the setup of my serializers. 

Thank you for helping and also for this great project that is BIMserver.

Cheers,
Abdou

**Comment by rubendel** [comment]
The BIMQL query only queries for the objects of type IfcDoor and it's directly related properties/objects. Geometry can be a whole tree of objects so if you want geometry you have to explicitly query for geometry. Unfortunately BIMQL is not capable of doing that.

To debug the error message, it would be useful to know which version of BIMserver you are running, so we can try to reproduce.

**Comment by abdoulayediak** [comment]
Thank you for the answer.

So it means that I cannot expect exporting a collada file with such queries?
Is it possible to export an IFC file with only IfcDoors or IfcSpaces for example?

I'm using the version 1.4.0.

**Comment by rubendel** [comment]
Yes you can export the IfcDoor and IfcSpace, but it will just be the objects, not necessarily the right geometry. Can you please give the full file name including the date of your BIMserver release?

**Comment by abdoulayediak** [comment]
I'm using the jar file named Bim 1.4.0-FINAL-2015-10-25

**Comment by abdoulayediak** [comment]
Sorry wrong manipulation. 
bimserver-1.4.0-FINAL-2015-10-25.jar

**Comment by rubendel** [comment]
There was a bug in BIMQL where in combination with collada as a serializer it would not export anything. This has been fixed and will be in the new release, which I'll make today.
