### ISSUE TITLE
Password request: e-mails empty

### ISSUE THREAD

**Issue by leifgen** [opensourceBIM/BIMserver#263]
Hi,

I just set up my first BIMserver (1.4.0-2015-10-25), running on an Ubutu 14.0.4.3 LTS based server, following this https://bhushanbharat.wordpress.com/2015/10/13/install-bimserver-on-ubuntu-14-04/ guide. 

Everything is working well so far, except sending e-mails. Mails are sent and delivered, but there is absolutely no content (no single sign) in their body. Only the origin e-mail address is shown. I tested it with different SMTP servers, always with the same result. Due to this it is not possible to add new users. 

May this be an error in the above mentioned version or am I missing some settings? 
Can anybody help me with a solution or a hint, where to start searching? Thanks. 

Best regards,
Christian

**Comment by rubendel** [comment]
Just tested the same version and I am getting emails with content. Which email client are you using?

**Comment by leifgen** [comment]
Thank you for testing and the fast reply. I am using MS Outlook 2013 with an Exchange server. Just tried Android E-Mail and Webmail with the same result: no subject and no body/content.

I tried it with a mail server in our local network as well as with one located at the webhoster of my private website. Do I need to use a mail server installed at the BIMserver hosting OS (same IP) or does the SMTP server require any specific settings?


Von: Ruben de Laat [mailto:notifications@github.com]
Gesendet: Dienstag, 3. November 2015 13:06
An: opensourceBIM/BIMserver <BIMserver@noreply.github.com>
Cc: Leifgen, Christian <leifgen@iib.tu-darmstadt.de>
Betreff: Re: [BIMserver] Password request: e-mails empty (#263)


Just tested the same version and I am getting emails with content. Which email client are you using?

**Comment by rubendel** [comment]
Does not sound like a problem with SMTP, since you are receiving messages. The SMTP server does not need to be on the same machine, most users would use something like mailgun.

It sounds like a problem with the email templates. Is there nothing in the server log about it? Did you change anything with regards to the homedir? Are you using a custom location for it?

**Comment by leifgen** [comment]
Sorry, I didn't look at the logfiles properly. It looks, like you are right with your suggestion:

ERROR ResourceManager : unable to find resource 'password_reset_email_subject.template' in any resource loader. (velocity.java:164)
ERROR (org.bimserver.templating.TemplateEngine.java:52) 
[...]
[Same for email_body]


The homedir is set to

/var/bimserver/home/

Another point that is not working is the set host. I used a name like "helloworld" as Domain in the above mentioned setting up process. If I try to access bimviews via http://helloworld:8080 it doesn't work, whereas entering the IP does as well as localhost is working.

Can you tell me, what I must have done wrong during the setup process? 

Sorry, if my problems are a bit noobish, but I am not a programmer, I'm civil engineer with focus on informatics in civil engineering.

**Comment by rubendel** [comment]
Using a custom homedir is a very good idea, unfortunately not one that had been tested lately. The email templates were not being copied, which caused this error. This has been fixed now, I'll make a new release later today. Thanks for the very clear description.

As for the domaine name, this has to really resolve to an IP address, so unless you edited your hosts file to resolve "helloworld" to "127.0.0.1", or have custom DNS server (which you probably don't), this is not going to work.

As long as you are running locally, just keep it to localhost/127.0.0.1, or your public IP if you want the server to be accessible from the outside. If you register a domain name (a real one, including a TLD) you can then change it to that domain.

**Comment by leifgen** [comment]
Updated to todays relese and e-mails are sent perfectly. 

Thank you very much, Ruben!
