### ISSUE TITLE
BIMserver Dockerfile

### ISSUE THREAD

**Issue by px3l** [opensourceBIM/BIMserver#264]
Hi Ruben,

Sorry for opening this as an issue it's not really an issue haha. Here is the link to the Dockerfile I made, the one we used in our demo at the Hackathon. If it could become the official BIMserver Dockerfile as we discussed it would be really helpful for developers and we can keep this one up to date.

https://github.com/BIMscript/docker-bimserver
https://hub.docker.com/r/bimscript/docker-bimserver/

Thanks Ruben!

**Comment by berlotti** [comment]
Hi guys,

Could you provide a statement about your intentions with this?
Do you intent to keep it updated and maintain it during new releases?

Thank you for your response.
Léon

**Comment by px3l** [comment]
Hey Leon,

I hope you're well! Can I get your email address again, I seem to have lost it after changing email domains! I do intend to keep this file updated and maintained for the foreseeable future, though I am having some issues with it at the moment! Any help is appreciated!

https://github.com/jenca-cloud/docker-bimserver/issues/1

**Comment by berlotti** [comment]
sure, it's leon.vanberlo@tno.nl 
Great to hear your good intentions!
