### ISSUE TITLE
Reporting Security Vulnerabilities

### ISSUE THREAD

**Issue by adeelbhae** [opensourceBIM/BIMserver#265]
Hi BIM Team,

Reporting Security Vulnerabilities in your website http://bimserver.org/

Vulnerabilities:
 > Admin page is found with a generic "Admin", while it should be hide or not accessible from public to whom which not concern.
> Admin page have no captcha words or rate of limitations for attempting, which may Bypass through Brute force Attack.
> When we click on Forgot your password, it display hints for an attacker to guess the email because it is displaying a msg account not found.
> The Last one which I found it is disclosing critical information of the servers like (Server ip, Port, OS, webserver details etc)

Please look in to this, awaiting for your acknowledgement,

Regards,
Adeel Imtiaz

![admin panel](https://cloud.githubusercontent.com/assets/5087238/11015673/cd9f3b4e-8588-11e5-9a46-bf6b4b0e7ffa.JPG)
![guessing](https://cloud.githubusercontent.com/assets/5087238/11015674/cd9f4062-8588-11e5-8dc3-336f08397b44.JPG)
![internal information](https://cloud.githubusercontent.com/assets/5087238/11015675/cda47aaa-8588-11e5-9634-14ceaf9aa917.JPG)

**Comment by berlotti** [comment]
thanks.
