### ISSUE TITLE
Can't connect to BIMserver using BIMvie.ws

### ISSUE THREAD

**Issue by dbarthelemy** [opensourceBIM/BIMserver#266]
Hi,
I am currently testing BIMserver to see if we can use it for our own application.
I am using the BIMserver Starter and I am able to connect from the same machine using BIMvie.ws.

As soon as I try to connect from another machine (same local network), BIMvie.ws failed to connect with the following error: "Error Error: Script error for: bimserverapi_BimServerApi http://requirejs.org/docs/errors.html#scripterror"

After some investigations, I saw that x.getbimserveraddress reports "localhost" instead of the actual server address.
I try to set BIMserver Starter Address setting with both IP and the Server host name, same problem persist. Each time I adapt the URL from the client to use the IP or the Server host name.

Note That I am running the bimserver-1.4.0-FINAL-2015-11-04.jar on a Mac OS 10.10.5 with Server additions.
Thanks

**Comment by rubendel** [comment]
Have you changed the address of your server in "Server settings"?

**Comment by dbarthelemy** [comment]
Yes, I did.

**Comment by berlotti** [comment]
could you provide some more info? log files, error messages?
