### ISSUE TITLE
Can't download more than once with BIMvie.ws

### ISSUE THREAD

**Issue by INeededFakeAccount** [opensourceBIM/BIMserver#268]
I can't download with any serializer more than once. For example, if I first pick COLLADA, it works. However, if I then try to download using COLLADA serializer or any other serializer, it gets stuck to "Preparing download...".

No errors are shown in console. Web-page only says "Endpoint with id 2 not found". Downloading works again only if I restart BIMServer.

I'm running BIMServer on Windows 10, with 64-bit Java 8 update 65. I tried BIMServer releases 1.4.0-FINAL-2015-11-04 and 1.4.0-FINAL-2015-10-25

Steps to reproduce:
1. Download JAR
2. Start server
3. Create Administrator account
4. Create project
5. Checkin IFC-file using File Uploader (I tried two different IFC-files)
6. Go to revisions and use Download-action (for example, COLLADA)
7. Use Download-action again

**Comment by berlotti** [comment]
We found some errors in the caching function. Could you try again using the latest version of the code?
