### ISSUE TITLE
Can not start bimserver-1.4.0-FINAL-2015-08-25

### ISSUE THREAD

**Issue by leolee1987** [opensourceBIM/BIMserver#269]
When I start bimserver-1.4.0-FINAL-2015-08-25.jar on a cloud server which runs Windows Server 2008 R2, it always stop here, any suggestion for me?
![image](https://cloud.githubusercontent.com/assets/7720897/11200969/fb0ffefe-8d14-11e5-876e-f0fd18cb86e3.png)

Thanks!
Leo

**Comment by leolee1987** [comment]
And if I click the Stop button, and start again, the following exception will be raised.
![image](https://cloud.githubusercontent.com/assets/7720897/11201040/8aca0242-8d15-11e5-97dd-f8472dd3f89f.png)

**Comment by rubendel** [comment]
Can't reproduce this, but I have never tried on Window Server 2008. Why do you run the JAR on a server? Can you try the WAR?

**Comment by leolee1987** [comment]
Thanks! The same problem appears when I deployed the WAR package. I have deployed it on another server.

**Comment by rubendel** [comment]
The exact same message? About the environment being locked happened?

**Comment by leolee1987** [comment]
Yeah！

**Comment by rubendel** [comment]
It means that another process is already using the database. Are you sure no previous versions of BIMserver are running?

**Comment by leolee1987** [comment]
When I started BIMServer the first time, it can't be started successful, and when i click the Stop button, the java.exe process can not be killed automatically. Actually, the java.exe process also can not be killed manually. So, when I start the Server again, the environment being locked happened.

**Comment by berlotti** [comment]
the process tries to create directories on your sever. Windows Server 2008 doesn't always allow this be default from 'external' applications. It probably detects the creation of directories and locks something. Check your security settings of Windows Server 2008.

Did you try the WAR file with Tomcat, or maybe the WSO2 application server?
