### ISSUE TITLE
BIMviews on MS IIS

### ISSUE THREAD

**Issue by kajoergensen** [opensourceBIM/BIMserver#270]
Hi,
I would like to run eksperiments with the BIMviews JavaScript client in order to add other pages to the application.
Should it not be possible to run the BIMviews (v. 1.3.11-FINAL-2015-11-17) client on the IIS web server or must I install and use Tomcat? In IIS I get the error: the resource file plugin.version not found (status of 404 .... not found). In addition the BIMsurfer resources ar missing. Chrome browser is used. 
BIMserver is running (v. 1.4.0-FINAL-2015-11-04) and 'Launch Webbrowser' works even after putting the 11-11 jar file in the plugin folder.
Best regards,
Kaj
[bimserver.log.txt](https://github.com/opensourceBIM/BIMserver/files/36932/bimserver.log.txt)

**Comment by rubendel** [comment]
BIMvie.ws is included in the BIMserver build, so you don't have to use your own version. If you want to run your own version of BIMvie.ws anyways, start by copying the content of the version that came with BIMserver 1.4.0-FINAL-2015-11-04 to your webserver. Version 1.3.11-FINAL-2015-11-17 is not compatible with BIMserver 1.4.0-FINAL-2015-11-04. Make sure you also change in the settings.js file the getStaticServerAddress function, it should return the address of your BIMserver (not changing this causes the "the resource file plugin.version not found" error.

**Comment by kajoergensen** [comment]
Ok, but please provide some more guidance.
BIMserver (v. 1.4.0-FINAL-2015-11-04) is started from 'C:\Bimserver' and the inbuilt BIMvie.ws is on 'http://localhost:8082'. Works fine. My IIS server 'BimServerLocal' is created on this port 'http://localhost:8083' with default address at 'C:\Bimserver'.
I have downloaded the source code to 'C:\BIMserver\SourceCode\BIMserver-1.4.0-FINAL-2015-11-04' and, as I understand, you mean the 'AdminGui', in which I must modify the file 'js\settings.js'. 
What must be changed? 
1) is '$.getJSON("http://extend.bimserver.org/serverlist", ...' correct? 
2) what should be entered in '$.getJSON("x.getbimserveraddress", ...'? 
3) anything else?
Please guide me a bid more.

**Comment by rubendel** [comment]
AdminGUI is a subset of BIMvie.ws. You want to extract the bimviews-2015-11-04.jar file, which you can find in the plugins folder. Just replace
```javascript
	getStaticServerAddress: function(callback){
		$.getJSON("x.getbimserveraddress", function(data){
			callback(data.address);
		}).fail(function(){
			callback(null);
		});
	},
```
with
```javascript
	getStaticServerAddress: function(callback){
		callback("http://[yourbimserver address]");
	},

```

Another way of course would be to clone the BIMvie.ws repository and work from there, that way you can also push back bugfixes and new features...

**Comment by kajoergensen** [comment]
Super, it works.
However, the following error is still occurring:
GET http://localhost:8083/SourceCode/bimviews-2015-11-04/plugin.version 404 (Not Found)(anonymous function) @ ?page=Projects:394
It seems not to harm - until now.
Many thanks.

**Comment by kajoergensen** [comment]
Unfortunately, it does not work as I thaught. The 'File not found' error is always reported, coming from 'index.html', these two lines:
		myRequest.open("GET", Global.baseDir + "plugin.version", true);
		myRequest.send();
However, it is possible to login, open a project, load a model and explode the tree structure until I click on an object (e.g. IfcWallStandardCase). Then an error occurs, see attached log file. 
[bimserver.log.txt](https://github.com/opensourceBIM/BIMserver/files/56921/bimserver.log.txt)
I have used the model AC11-FZK-Haus-IFC.ifc an I am specifically studying the properties and quantities.
I have tried several times to locate the error but, now, I give up. Any suggestions? Please help.

**Comment by kajoergensen** [comment]
Hi there,
Any chance to get help with this. In short to use BIMviews source code at port 8083 connected to BIMserver at port 8082. The 'settings.js' file is modified as specified above.

    getStaticServerAddress: function(callback){
        callback("http://localhost:8082");
    },

**Comment by rubendel** [comment]
Those errors are unrelated. 

For the first one, replace this code
```
var myRequest = new XMLHttpRequest();
		myRequest.onreadystatechange = function() {
			if (myRequest.readyState != 4)  {
				return;
			}
			if (myRequest.status != 200)  {
				Global.version = new Date().getTime();
				loadResources();
				return;
			} else {
				Global.version = JSON.parse(myRequest.responseText).version;
				loadResources();
			}
		};
		myRequest.open("GET", Global.baseDir + "plugin.version", true);
		myRequest.send();
```

by

```
Global.version = "someversion";
loadResources();
```

The second one has to do with caching, you can disable caching in "Server" | "Server Settings" | "Cache output files".

**Comment by kajoergensen** [comment]
Done, thank you. But, I am sorry, no luck.
After disabling cache, the page opens as usual and a the project list comes up. But, when I click on the expand arrow of a leaf project, it is waiting to carry out 'Getting model data ...'. 
This message is reported:
Uncaught SyntaxError: Unexpected end of input    VM204:1
xhr.onload @ bimserverapi_BimServerApi.js?bust=12345:437
The last call is like this:
http://localhost:8082/download?token=98476f5e706f1eeba2039d17f0c1f3469bebccfd3b1f602808dfc82570be73ba2650ea9e48d7744e725a8c4753ffa1f2&longActionId=32&serializerOid=3932198&topicId=32

**Comment by rubendel** [comment]
Any errors in the server log?

**Comment by kajoergensen** [comment]
The last two lines is:
16-12-2015 15:52:12 INFO  org.bimserver.JarBimServer - Server started successfully
16-12-2015 15:53:00 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 480

**Comment by kajoergensen** [comment]
Any chance to get a solution?

**Comment by rubendel** [comment]
Can you paste the actual response of which the browser says "Unexpected end of input"?

**Comment by rubendel** [comment]
Just a heads up, this checkin is because I didn't like that you had to edit index.html for this to work. Don't use this version with your version of BIMserver though, because it won't work.

**Comment by kajoergensen** [comment]
Thank you very much for your effords to help. I have looked through the many changes that you have made, but, being rather unexperienced, I am unable to understand what to do. A complete new source code now?
Must I give up this attempt to use BIMviews as a separate source code at port 8083 and make connection to BIMserver at port 8082? If not, I am sorry to say that I need more detailed guidance. Would you allow me to set up a Skype call in order to get a solution?

**Comment by rubendel** [comment]
Skype call conclusion: wait for next release.
