### ISSUE TITLE
can't understand bimserver and bimvie.ws's relationship

### ISSUE THREAD

**Issue by wlhm1984** [opensourceBIM/BIMserver#271]
now i can run bimserver  and use http://127.0.0.1:8080 can view ,also i can upload ifc file ,but i can't find how to view the ifc file through ie or google by bimsurfer or bimvie.ws,can you give me some advice or instruction,i look all instruction about this still have no idea. thanks!

**Comment by rubendel** [comment]
If you mean Internet Explorer with "ie", it's not supported and never will be. There is no integration between google and BIMserver, I don't see how that would work.

Did you click on the "eye" icon in the tree on the left?

**Comment by wlhm1984** [comment]
i'm sorry,may be i had express wrong.i want to know how to view the ifc file online. i read some instruction about bimserver,it sames that can use bimsurfer or bimvie.ws to view ifc file online.
