### ISSUE TITLE
Question : GeometryData affected by transformations ?

### ISSUE THREAD

**Issue by mguimard** [opensourceBIM/BIMserver#274]
Hi, 

I'm writing a BimServer plugin (extending `EmfSerializer`) to serialize geometries in the format we need. This works quite well, but I'm wondering if `GeometryData.getNormals` and `GeometryData.getVertices` methods provide data already affected by IfcRoot transformations (translation/rotation).

If so, how can I prevent this ?

**Comment by rubendel** [comment]
Nope those should be untransformed, all transformation happens by applying GeometryInfo.transformation.

**Comment by mguimard** [comment]
Ok thank you for anwsering
