### ISSUE TITLE
Question about memory

### ISSUE THREAD

**Issue by mguimard** [opensourceBIM/BIMserver#276]
Hello, according to https://github.com/opensourceBIM/BIMserver/wiki/Get-Started-Quick-Guide

    As a rule of thumb, set the heap size according to: 15MB per 1MB of IFC file, 
    e.g. for 30MB of IFC file, the heap size should be at least 5GB

30MB * 15 = 450 MB
Something I am missing or just a typo ?

**Comment by Lawri-van-Buel** [comment]
Wow, That is an old recommendation. I believe it originally was 300MB IFC ==> 5GB Heap (4,5 GB + 512MB for java and reserve). I do not know how accurate it is for version 1.4 but I use  a ratio of 1:20 in development.

**Comment by rubendel** [comment]
1:20 sounds about right yes, but depends a lot on the amount of geometry that is being generated by the model.
