### ISSUE TITLE
Cannot find module 'bimserverapi_BimServerApiPromise

### ISSUE THREAD

**Issue by lengyueChen** [opensourceBIM/BIMserver#277]
I am following the guide here:
https://github.com/opensourceBIM/BIMserver/wiki/JavaScriptClient 
and I am use this chunk of code to load the target js file in order to use the bimserver api
 requirejs.config({
        baseUrl: address + "/js", // address should be the address of your bimserver, including optional port
        urlArgs: "bust=" + version // the version you use here will be used for caching
    });

```
requirejs(["bimserverapi_BimServerApi", "bimserverapi_BimServerApiPromise"], function(BimServerApi, BimServerApiPromise) {
    if (address.endsWith("/")) {
        address = address.substring(0, address.length - 1);
    }
    if (BimServerApi != null) {
        var bimServerApi = new BimServerApi(address, notifier);
        bimServerApi.init(function(){
            // This function gets called on success, you can use bimServerApi now
        });
    } else {
        // error
    }
}, function (err) {
    // Error
});
```

Below is the error messages I got:

{ [Error: Tried loading "bimserverapi_BimServerApi" at http://localhost:8082/js/bimserverapi_BimServerApi.js?bust= then tried node's require("bimserverapi_BimServerApi") and it failed with error: Error: Cannot find module 'bimserverapi_BimServerApi']
  originalError: { [Error: Cannot find module 'bimserverapi_BimServerApi'] code: 'MODULE_NOT_FOUND' },
  moduleName: 'bimserverapi_BimServerApi',
  requireModules: [ 'bimserverapi_BimServerApi' ],
  requireMap: 
   { prefix: undefined,
     name: 'bimserverapi_BimServerApi',
     parentMap: undefined,
     unnormalized: false,
     url: 'http://localhost:8082/js/bimserverapi_BimServerApi.js?bust=',
     originalName: 'bimserverapi_BimServerApi',
     isDefine: true,
     id: 'bimserverapi_BimServerApi' },
  requireType: 'define' }

{ [Error: Tried loading "bimserverapi_BimServerApiPromise" at http://localhost:8082/js/bimserverapi_BimServerApiPromise.js?bust= then tried node's require("bimserverapi_BimServerApiPromise") and it failed with error: Error: Cannot find module 'bimserverapi_BimServerApiPromise']
  originalError: { [Error: Cannot find module 'bimserverapi_BimServerApiPromise'] code: 'MODULE_NOT_FOUND' },
  moduleName: 'bimserverapi_BimServerApiPromise',
  requireModules: [ 'bimserverapi_BimServerApiPromise' ],
  requireMap: 
   { prefix: undefined,
     name: 'bimserverapi_BimServerApiPromise',
     parentMap: undefined,
     unnormalized: false,
     url: 'http://localhost:8082/js/bimserverapi_BimServerApiPromise.js?bust=',
     originalName: 'bimserverapi_BimServerApiPromise',
     isDefine: true,
     id: 'bimserverapi_BimServerApiPromise' },
  requireType: 'define' }

I am actually using Express to do an experiment of calling bimserer api. Below is the code of app.js:

var express = require('express');
var app = express();
var requirejs= require('requirejs');
var requirejs= require('requirejs');
app.get('/', function (req, res) {

```
var bim = {};
bim.bimServerAPI = null;
var address = "http://localhost:8082";
var notifier = null;
var version = '1.4.0';

requirejs.config({
    baseUrl: address + "/js", // address should be the address of your bimserver, including optional port
    urlArgs: "bust=" + version // the version you use here will be used for caching
});

requirejs(["bimserverapi_BimServerApi", "bimserverapi_BimServerApiPromise"], function(BimServerApi, BimServerApiPromise) {
    if (address.endsWith("/")) {
        address = address.substring(0, address.length - 1);
    }
    if (BimServerApi != null) {

        var bimServerApi = new BimServerApi(address, notifier);
        bimServerApi.init(function(){
            console.log("success");
            // This function gets called on success, you can use bimServerApi now
        });
    } else {
        console.log("ERROR");
        // error
    }
}, function (err) {
    console.log("ERROR2");;
    console.log(err);
    // Error
});
```

});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);
});

And pakage.json:

{
  "name": "testbim",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cheerio": "^0.19.0",
    "jQuery": "^1.7.4",
    "jquery": "^1.11.3",
    "jsdom": "^7.1.1",
    "requirejs": "^2.1.22"
  }
}

Any suggestions? Thanks a lot !

**Comment by rubendel** [comment]
So far I have not managed to get this working on NodeJS, although most of the work is done (moving to require js and removing jquery dependencies) I think.

When I have time I'll have a look at it again. The node package was just to try it out, if I manage to figure out how to edit the description I'll update it with "not working".

**Comment by jdimyadi** [comment]
We get a similar error using BIMvie.ws. It just started happening.

When we launch the browser, we get this error message:

Error Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror

Clearing the home directory, restarting BIMserver, and so forth did not help.

**Comment by jdimyadi** [comment]
We are running BIMserver on Windows 10.

**Comment by jdimyadi** [comment]
And we are running bimserver-1.4.0-FINAL-2015-11-04.jar

**Comment by rubendel** [comment]
The API has now changed to ES6 with modules, please create a new issue if this problem still persists.
