### ISSUE TITLE
IFC merge file

### ISSUE THREAD

**Issue by RemcoBal** [opensourceBIM/BIMserver#278]
I have megerd with the BIMserver.
De nieuw ifc file works fine in Solibri but not in Tekla BIMsight

I have tried all three merging options (Basic Merger / Intelligent GUID Based Fusion / Intelligent Name Based Fusion), all with the same result.

**Comment by RemcoBal** [comment]
IFC test files

[project_2.txt](https://github.com/opensourceBIM/BIMserver/files/52544/project_2.txt)
[project 2-project 1.txt](https://github.com/opensourceBIM/BIMserver/files/52543/project.2-project.1.txt)
[project_1.txt](https://github.com/opensourceBIM/BIMserver/files/52545/project_1.txt)

**Comment by berlotti** [comment]
Hi Remco,

The model merge algorithm doesn't guarantee a valid IFC output.
This is impossible because of the nature of IFC.

Léon

**Comment by dishesh** [comment]
@RemcoBal @berlotti  

I can do the same in bimVie.ws page but how can I implement the same in my custom webapp where I want to get merged model ?

Is it possible to merge only selected models to view ?
How can we load merged model directly using service or any other interface ?

**Comment by berlotti** [comment]
When downloading/checkout of data, you can provide a list of revision IDs (roid - Long). These revisions will be merged using the current modelmerger

**Comment by dishesh** [comment]
@berlotti  
Hi Thanks for the reply. I tried the way you asked. It gives error of
`Java.lang.HashSet can not be converted to Java.lang.long` 

I have tried passing values using Array as well as JSON.

**Comment by rubendel** [comment]
Please post the complete request your are sending to the server
