### ISSUE TITLE
Question : access ground geometry information

### ISSUE THREAD

**Issue by mguimard** [opensourceBIM/BIMserver#283]
Hi, 

I'm writting a plugin to extract every thing from an IFC file. I'm currently extracting projects, sites, buildings, building storey and products, all of them working great. But I'm stuck trying to extract the ground geometry. Do they have a specific class name ? Is there a way to access them with this method by specifying the right class :

    model.getAll(IfcProject.class);

When I upload my IFC file on some online services, I can see them in the structure tree, and they are named "FootPrint". I'm obviously missing something, I can't find a way to access them for a couple of hours now.. Would really appreciate some help !

**Comment by rubendel** [comment]
Not sure what you mean with "ground", maybe IfcSite is what you are looking for?

**Comment by mguimard** [comment]
Hi, by ground I was meaning the grass in this example : 

![image](https://cloud.githubusercontent.com/assets/3205135/11895537/f9ca32ac-a57f-11e5-8ba4-d9697e7517bb.png)

And yes it seems to be the geometry of the IfcSite, I will try to get geometry information from this object. Thank you for this hint
