### ISSUE TITLE
Modification templates SConverterGenerator.jet 

### ISSUE THREAD

**Issue by bbrangeo** [opensourceBIM/BIMserver#284]
Hello,

Add in SConverterGenerator.jet : 

import org.bimserver.models.geometry.GeometryData;
import org.bimserver.models.geometry.GeometryFactory;
import org.bimserver.models.geometry.GeometryInfo;
import org.bimserver.models.geometry.GeometryPackage;
import org.bimserver.models.geometry.Vector3f;

**Comment by berlotti** [comment]
Hi bbrangeo,

We've noticed you created and deleted a pull request. 
Please elaborate or contact us on support@bimserver.org
