### ISSUE TITLE
Unable to Checkin IFC files

### ISSUE THREAD

**Issue by px3l** [opensourceBIM/BIMserver#289]
Got the BIMserver up and running well. Can create a new project, a sub-project etc but when I go to checkin an IFC it hangs on 'uploading' with no network activity..  is this working for anyone else?

**Comment by px3l** [comment]
![screenshot from 2016-01-06 16-15-20](https://cloud.githubusercontent.com/assets/11406845/12147426/b8e7d8b4-b490-11e5-8c12-f2368917e968.png)

**Comment by rubendel** [comment]
Which version of BIMserver?

**Comment by px3l** [comment]
The latest release, 1.4.0-FINAL-2016-01-05

**Comment by fern1978** [comment]
For me works fine, 1.4.0-FINAL-2016-01-06

**Comment by rubendel** [comment]
I have removed both releases now, 2016-01-05 did not work because BIMvie.ws is out of sync with BIMserver. 2016-01-06 had the wrong version number (will be a 1.5 pre-release).

It's too much of a hassle trying to recreate the 1.4 for Java 7, so bumping the requirements to Java 8 as of now.

**Comment by px3l** [comment]
Hi Ruben,

Ok so the release there now from 4th November (bimserver-1.4.0-FINAL-2015-11-04) is the latest one and running on Java 8? Will you be releasing another version soon? If so I will wait to update the Dockerfile.

**Comment by rubendel** [comment]
Yes that one will only run on Java 8, but I am changing the requirements of BIMserver to Java 8 anyways, so the new build will also require it.

**Comment by px3l** [comment]
Thats ok matey, java 8 is fine! When's the ETA on the new build?

**Comment by rubendel** [comment]
You can just use https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-11-04

**Comment by px3l** [comment]
ok perfect
