### ISSUE TITLE
BIM Server & Java 8

### ISSUE THREAD

**Issue by joshercartifes** [opensourceBIM/BIMserver#290]
Hi, I would like to ask about how to run the BIM Server under Java 8 because when I start the BIM Server, it fails. I have worked with previous versions of the BIM Server without troubles, although after an update of the JVM, the server does not start. See snapshots:

![exscript](https://cloud.githubusercontent.com/assets/16591711/12168652/f21c5120-b533-11e5-9387-6c88303f3d37.png)

![bimserver](https://cloud.githubusercontent.com/assets/16591711/12168651/f21b2886-b533-11e5-92e0-ff428e1716fe.png)

![output](https://cloud.githubusercontent.com/assets/16591711/12168650/f2183586-b533-11e5-8e3f-b2e4575fc574.png)

Thanks in advance

**Comment by rubendel** [comment]
This issue is a continuation of http://support.opensourcebim.org/hc/communities/public/questions/205056866-BIMServer-Java-8-0?page=1#answer-208525963.

The error could not be more clear I think. "Could not reserve enough space for 2185216KB object heap". Why are you giving 1024m to the Jar runner?

**Comment by joshercartifes** [comment]
That is a simply example of what happens, I have tried to give more space, in particular 2500m and the message is similar: "Could not reserve enough space for 2560000KB object heap"

**Comment by rubendel** [comment]
The message indicates that the system does not have the amount of memory available that you are trying to give to the JVM. So try a lower amount of heap (XMX).

**Comment by joshercartifes** [comment]
If I try with a lower amount, the message is again "Could not reserve enough space for 2185216KB object heap"

**Comment by rubendel** [comment]
And you are chaning the "Max Heap Size" parameter right?

**Comment by joshercartifes** [comment]
Yes, although in the example I forgot to modify the value, because just in the before trial I set the value of 2133m in the Xmx. I am going to try in a different machine with Java 7

**Comment by rubendel** [comment]
For other people reading this issue, Java 8 is now required for BIMserver.
