### ISSUE TITLE
 org.apache.maven.plugins:maven-gpg-plugin compile error

### ISSUE THREAD

**Issue by bbrangeo** [opensourceBIM/BIMserver#291]
Hi,

I have a problem to compile :

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project PluginBase: Exit code: 127 -> [Help 1]

I added :

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <configuration>
        <skip>true</skip>
    </configuration>
</plugin>
```

Boris

**Comment by rubendel** [comment]
We are in the middle of migrating to Maven, so the git master won't work for another week or so.
