### ISSUE TITLE
new releases do not deploy

### ISSUE THREAD

**Issue by timoutwente** [opensourceBIM/BIMserver#296]
Hallo Ruben, 

just tried to deploy the newest version of the bimserver using my docker setup and it failed. Sp I reverted back to this old version that works like a charm: 

bimserver-1.4.0-FINAL-2015-09-29.war

Dockerfile:

FROM 		tomcat:jre8
MAINTAINER 	Timo Hartmann <hartmann@contecht.eu>
RUN 		apt-get update && \
		apt-get install wget && \
		wget  -O /usr/local/tomcat/webapps/bimserver.war https://github.com/opensourceBIM/BIMserver/releases/download/1.4.0-FINAL-2015-09-29/bimserver-1.4.0-FINAL-2015-09-29.war 

ENTRYPOINT	["/usr/local/tomcat/bin/catalina.sh", "run"]

Timo

**Comment by rubendel** [comment]
Hello Timo, not sure which version you tried, anything named 1.5 is just for testing the build system, it won't be released in another few months.

**Comment by Lawri-van-Buel** [comment]
Timo, just wondering. Why are you redefining the entrypoint?
Peronally I use 
 - Baseimage:  tomcat:8.0.30-jre8
 - Bimserver:  [bimserver-1.4.0-FINAL-2015-11-04](https://github.com/opensourceBIM/BIMserver/releases/download/1.4.0-FINAL-2015-11-04/bimserver-1.4.0-FINAL-2015-11-04.war)

**Comment by timoutwente** [comment]
Dear Lawri -

I do not have an answer to your question about the entry point. I just copied this from my docker book. But it seems to work without.  Also: the tomcat:8.0.30-jre8 base image works like a charm. Seems the tomcat:jre8 base image was the problem. 
Maybe we should establish a place on the side  to share Dockerfiles? 

Thanks for your help Lawri!
Timo

**Comment by timoutwente** [comment]
just a short ammendment. Actually I need to redefine the entry point to be able to start the image as a demon: 

ENTRYPOINT      ["/usr/local/tomcat/bin/catalina.sh", "run"]

**Comment by px3l** [comment]
https://hub.docker.com/r/jenca/docker-bimserver/

**Comment by timoutwente** [comment]
Here are two docker images: 
https://hub.docker.com/r/timohartmann/bimserver_test/
https://hub.docker.com/r/timohartmann/bimserver/

**Comment by Lawri-van-Buel** [comment]
@timoutwente, your docker files in the hub have no attached source (ergo, we can not validate or recreate your images) can you add them? helps a great deal to know how someone build a package on the hub. ;) , you can look at the one @px3l posted. It has all the documentation bells and whistles you would like (and a bit more... )

**Comment by timoutwente** [comment]
Hallo Lawri -

I do understand, but these are really quick and dirty, made without a docker file. So I regret that I have more documentation. Hope I find the time down the road to improve on them. In the end, these work well for us. 

Timo
