### ISSUE TITLE
The upload of a simple IfcXML file to Bimserver fails

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#298]
Hello BIMserver team,

we have tried to upload the follwing file to ower BIMserver:
[Testfile.zip](https://github.com/opensourceBIM/BIMserver/files/109861/Testfile.zip)

The checkin fails with this message: "Cannot checkin empty model"

Can anybody say, which Ifc-elements are required inside an IfcXml file?

Klaus

**Comment by rubendel** [comment]
The elements that are required you should be able to see in the IFC4 documentation. Just tried your file in BIMserver 1.4, got the same messsage. This is the first IFC4 XML file I have seen, so it's hard to say whether the file is invalid or BIMserver does not handle it ok (I am guessting the latter).

For the BIMserver 1.5 release we will make sure IFC4 XML works. For 1.4 please try the STEP version, that we have tested.

**Comment by klacol** [comment]
Thans for the quick answer.

Ok, we will try to save in STEP format. Since the standard format of our CAFM Connect Editor (see http://www.cafm-connect.org/display/HOME/Download+CAFM-Connect+Editor , only german language :-( ) is IfcXML we have to extend this tool.

A native support for IfcXML in Bimserver 1.5 would be very nice.

**Comment by rubendel** [comment]
Cleaning up old issues. I really don't think using XML for IFC data is the way to go. So unless somebody else is picking this up, I plan to slowly remove XML support from the plugins.
