### ISSUE TITLE
xss in register page

### ISSUE THREAD

**Issue by Gamhody** [opensourceBIM/BIMserver#300]
Hello as i see your site in bugcrowd i would repor a xss vulnerability in http://myb.im/..

go to http://myb.im/ then go to search and type payload : "><img src=x onerror=prompt(3)>
javascript will excute .. 
xss code lead to steal cookies for your customers .. and hijacking their accounts..
you can use htmlentites to filter html&

thanks 
Mostafa ElGamhody
Mail:gamhody89@gmail.com
![33](https://cloud.githubusercontent.com/assets/17075044/12833932/86d411fc-cbac-11e5-8234-b3a2f83eb3af.png)

**Comment by Lawri-van-Buel** [comment]
This is not the place to report security issues, especially not when ther enot about the Bimserver, report this to the mybi.im team on the e-mail they state on there site. (from there site)
> The MyBimID is still in beta testing. Please send an e-mail to report@myb.im when you see something strange.
