### ISSUE TITLE
Under HTTPS proxy, cannot find module 'bimserverapi_BimServerApiPromise"

### ISSUE THREAD

**Issue by francescomattu** [opensourceBIM/BIMserver#303]
I presume this issue is very similar to: https://github.com/opensourceBIM/BIMserver/issues/277
but in a different context.

I have installed the war (https://github.com/opensourceBIM/BIMserver/releases/download/1.4.0-FINAL-2015-11-04/bimserver-1.4.0-FINAL-2015-11-04.war) on tomcat7 behind apache2 with https.
The address that I am calling is: **https:**//www.mydomain.com/bimserver/
Immediately I receive the following Error:

Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror

On the console of Firefox I receive this info:

Mixed Content: The page at 'https://www.mydomain.com/bimserver/' was loaded over HTTPS, but requested an insecure script 'http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApi.js?bust=bimviews-1.3.12'. This request has been blocked; the content must be served over HTTPS.e.load @ /bimserver/js/require.js?_v=bimviews-1.3.12:34
bimserverapibootstrap.js?_v=bimviews-1.3.12:25 Error: Script error for: bimserverapi_BimServerApi(…)
/bimserver/js/require.js?_v=bimviews-1.3.12:34 Mixed Content: The page at '**https:**//www.mydomain.com/bimserver/' was loaded over HTTPS, but requested an insecure script '**http:**//www.mydomain.com/bimserver/js/bimserverapi_BimServerApiPromise.js?bust=bimviews-1.3.12'. This request has been blocked; the content must be served over HTTPS.e.load @ /bimserver/js/require.js?_v=bimviews-1.3.12:34
bimserverapibootstrap.js?_v=bimviews-1.3.12:25 Error: Script error for: bimserverapi_BimServerApiPromise(…)

I think the solution is simply to change somewhere the path of certain script, but where?
Thank you for your effort.

**Comment by rubendel** [comment]
Are you sure that is also the exact address that you have specified as the "Site address" in the BIMserver settings?

**Comment by francescomattu** [comment]
Uhm, I didn't specify this parameter. When I deploy the war there is no settings file (as it is generated for the jar install) generated. Should it appear in the "homedir" added in the server context?

**Comment by francescomattu** [comment]
If you are referring to the "Site address" property in the configuration screen, I didn't tell this before in the posts, but I do not land to this screen at all. I can do only if I use the local Jar version. In the case of install as war under tomcat, I am not able to arrive to this configuration screen, neither I can find a settings.xml on the server.

**Comment by rubendel** [comment]
When deploying a WAR file, all settings that are stored in settings.xml in the JAR version are configured in your container's settings (settings like Xmx, address to bind to etc...). So that's why there is no settings.xml for the WAR deployment.

I indeed mean the "Site address" in the configuration screen, but you can also set it by calling "SettingsInterface"."setSiteAddress" via SOAP, JSON or ProtocolBuffers.

Do you get any errors when trying to access the configuration screen?

**Comment by francescomattu** [comment]
Hello Ruben, thank you for your answer.

**_FIRST ATTEMPT_**:
1. I browse: https://www.mydomain.com/**bimserver** (as root directory).
2. The system returns the following on the screen (without showing me the configuration page):
**Error Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror
**
That's it. No configuration screen shown.

In FIREFOX the web console says:
Blocked loading mixed active content "http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApi.js?bust=bimviews-1.3.12"[Learn More] require.js:34:0
Error: Script error for: bimserverapi_BimServerApi
http://requirejs.org/docs/errors.html#scripterror
Stack trace:
B@https://www.mydomain.com/bimserver/js/require.js?_v=bimviews-1.3.12:8:252
ga/h.onScriptError@https://www.mydomain.com/bimserver/js/require.js?_v=bimviews-1.3.12:30:244
 bimserverapibootstrap.js:25:2

Blocked loading mixed active content "http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApiPromise.js?bust=bimviews-1.3.12"[Learn More] require.js:34:0
Error: Script error for: bimserverapi_BimServerApiPromise
http://requirejs.org/docs/errors.html#scripterror
Stack trace:
B@https://www.mydomain.com/bimserver/js/require.js?_v=bimviews-1.3.12:8:252
ga/h.onScriptError@https://www.mydomain.com/bimserver/js/require.js?_v=bimviews-1.3.12:30:244

Additionally I have a call:
GET https://www.mydomain.com/bimserver/x.getbimserveraddress STATUS CODE 200 OK
and the response is:
{"address":"http://www.mydomain.com/bimserver"}
that it looks wrong, as it should be {"address":"http**_s_**://www.mydomain.com/bimserver"}

**_SECOND ATTEMPT_**:
Additionally I tried to force in FIREFOX the "disable protection" and the webconsole shows:
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApi.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApiPromise.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApi.js [Mixed Content]
[HTTP/1.1 302 Found 65ms]
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_BimServerApiPromise.js [Mixed Content]
[HTTP/1.1 302 Found 65ms]
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_BimServerWebSocket.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_Model.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_Ifc2x3tc1.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_Ifc4.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/js/bimserverapi_Translations_EN.js?bust=bimviews-1.3.12" on a secure page[Learn More] require.js:34:0
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_BimServerWebSocket.js [Mixed Content]
[HTTP/1.1 302 Found 37ms]
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_Model.js [Mixed Content]
[HTTP/1.1 302 Found 37ms]
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_Ifc2x3tc1.js [Mixed Content]
[HTTP/1.1 302 Found 64ms]
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_Ifc4.js [Mixed Content]
[HTTP/1.1 302 Found 64ms]
GET 
http://www.mydomain.com/bimserver/js/bimserverapi_Translations_EN.js [Mixed Content]
[HTTP/1.1 302 Found 63ms]
Loading mixed (insecure) active content "http://www.mydomain.com/bimserver/json" on a secure page[Learn More] bimserverapi_BimServerApi.js:433:0
OPTIONS 
http://www.mydomain.com/bimserver/json [Mixed Content]
[HTTP/1.1 302 Found 36ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.mydomain.com/bimserver/json. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.mydomain.com/bimserver/json. (Reason: CORS request failed). <unknown>

**_FINALLY_**:
Then if I move back to the non-HTTPS configuration (changing the proxy settings) and with the same installed package I access to http://XXX.XXX.XXX.XXX:8080/bimserver ,
everything works fine. I am able to reach the configuration page, I can set the admin credential, I can see the home page once logged in. So the installation package works like a charm if not behind https.

Please ask me which additional info you need to evaluate this case or how can I contribute.

**Comment by rubendel** [comment]
Can't you change the "Site address" to the httpS one while browsing it with HTTP, then change to HTTPS?
