### ISSUE TITLE
Multiple Vulnerabilities 

### ISSUE THREAD

**Issue by tayyabqadir877** [opensourceBIM/BIMserver#306]

**Comment by tayyabqadir877** [comment]
Any updates ?

**Comment by Lawri-van-Buel** [comment]
Well, for starters, this is NOT the place to disclose security issues (especially in detail)

Secondly, this is not about the Bimserver product. but a Website being used by the [Open source BIM collective](opensourcebim.org) to 'promote' Bimserver. 
If (as you claim) your a 'web security researcher', you should know not to disclose security information on any public fora. You should contact the people hosting the website or who made the website or who's website it is. This is not a Github page.

**Comment by tayyabqadir877** [comment]
whoops sorry 
i am deleting this report
