### ISSUE TITLE
create glTF serializer

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMserver#308]
because... you know...

**Comment by dlabz** [comment]
This wasn't done due compatibility problem between the way data is stored in BIMserver and the glTF.
In particular, BIMserver stores color and transparency in per-vertex-color stream, while glTF requires definition of materials. Same issue is holding back ThreeJS serializer. 

In most cases, window is one IFC object, but only glass is transparent, and such case isn't supported when converting data from GeometryData to glTF.

I guess the root cause is the way IfcOpenShell handles materials, since there is nothing in IFC specification that favors the current method.

**Comment by aothms** [comment]
Thanks for commenting on this. AFAICT the surface style information is actually stored mostly according to what Collada/glTF expects. The IfcOpenShell collada serializer uses the same input for its collada generation [1]. Per object this is a list of materials and a list of indices that for every triangle index into this list of materials. The only difference with how this is stored in the BIMserver is that the list of materials is converted into a flat list of (r,g,b,a)-tuples that signify the diffuse component of the materials and transparency [2]. One entry in this list per surface style. I can imagine that somewhere down the line when the geometry is fed to SceneJS this information is baked into vertex colors (not sure if and when) but it should be evenly easy to segment the mesh according to the material indices and associate materials accordingly.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/ColladaSerializer.cpp#L54
[2] https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/blob/master/src/org/ifcopenshell/IfcGeomServerClientEntity.java#L16

**Comment by dlabz** [comment]
@aothms :+1: GeometryData.materialIndices property seems to be the right tool for the job.    

Though, I still think that BIMserver would be better off with right implementation of per-object materials, as per-vertex colors essentially doubles the amount of data that is stored and streamed.

**Comment by rubendel** [comment]
glTF has no problem storing the vertex-colors, you just need to add different shaders for the different styles (model-wide-reusable-material-based or vertex-color-based). A basic implementation has been implemented here: https://github.com/opensourceBIM/GltfSerializers.

As far as I can remember, SceneJS was not able to handle it any other way (the way Thomas describes for example). glTF actually seems to be more flexible here as you can write your own shader code and basically do anything.

BIMserver stores the data per vertex (and for some reason also stores the original material indices). I'll have a look and see whether it might be better to store the original material indices + materials. Not sure if the other ifc engine is going to support it this way.
