### ISSUE TITLE
Custom SMTP port

### ISSUE THREAD

**Issue by meistro57** [opensourceBIM/BIMserver#312]
Custom SMTP port doesn't work. Trying to use 587 as this is used by Office365 but it reverts to port 25

**Comment by rubendel** [comment]
How are you changing the port?

**Comment by rubendel** [comment]
And have you also changed the protocol to SMTPS (which I assume Office365 uses)

**Comment by meistro57** [comment]
Neither SMTP or SMTPS. Whatever port I put in the port field gets
overridden by the dropdown for SMTP or SMTPS. Off hand I believe its port
587 or 465.

**Comment by rubendel** [comment]
There was a bug in BIMserver which caused the port not to be used under certain conditions, has been fixed in 1.5
