### ISSUE TITLE
Store material indices + materials instead of flat vertex colors

### ISSUE THREAD

**Issue by rubendel** [opensourceBIM/BIMserver#314]
See: https://github.com/opensourceBIM/BIMserver/issues/308

Less data could be stored in the BIMserver database if we do this. Conversion to vertex colors for the formats that require it can be done on the fly in some shared code.

Note, these materials are per-object, not for the whole model.

TODO: First check how RDF engine will supply this data.

**Comment by antarktikali** [comment]
I'm confused regarding the already existing material indices(getMaterialIndices()). So at the moment they don't mean anything?

Also implementing per face materials can make it better in cases such as windows where you have the frame and the glass, in terms of opacity.

**Comment by rubendel** [comment]
This has now been implemented differently. The colors are now stored in 4 bytes (quantized), saving 4 times the space. The optimization of using materials I don't think is necessary anymore, fields have been removed as well.
