### ISSUE TITLE
Not able to connect to bimserver from bimsurfer

### ISSUE THREAD

**Issue by madhu-singh** [opensourceBIM/BIMserver#316]
Hi 
I am using bim server bimserver-1.3.4-FINAL-2014-10-17.jar (as i read https://github.com/opensourceBIM/BIMserver/issues/229 which says no bim surfer is compatible with bimserver version 1.4.0) for the implementation of stand alone bim server. I successfully installed bimserver. then i installed bim surfer BIMsurfer-bimsurfer-0.0.13. but when i try to connect bim server from bim surfer after clicking on connect button it becomes diable. Can you plz guide me what i am doing wrong or if it is version compatibility problem, then which versions of bimserver and bimsurfer are compatible with each other.
![bimsurfer](https://cloud.githubusercontent.com/assets/13217607/13837311/ca96a974-ec2f-11e5-940c-ac944c140352.png)
![serversetting](https://cloud.githubusercontent.com/assets/13217607/13837319/d817d5fa-ec2f-11e5-8893-ff172841f96e.png)

**Comment by carlosips** [comment]
If you are using example1.html, check javascript console. I know where is the error but I dont know how fix it.

**Comment by rubendel** [comment]
BIMsurfer is not supported anymore because we focus on a new version (V2)

**Comment by gijskoning** [comment]
What is another option to connect remotely with the bimserver?
