### ISSUE TITLE
Download file name is null

### ISSUE THREAD

**Issue by jdimyadi** [opensourceBIM/BIMserver#317]
The filename of any first download from the BIMserver (via BIMview.ws) is always null, e.g. null.ifcxml, instead of using the default project name. This seems to fix itself after subsequent downloads as the variable for the filename has been populated.

Not sure if this has been fixed in the latest version of BIMserver, but we are running a server hosted version and I'm not able to figure out which version we are running from the client (approx dated Jun 2015).

**Comment by rubendel** [comment]
Pretty sure this has been fixed in 1.5
