### ISSUE TITLE
Could not transfer artifact org.antlr:antlr:jar:3.5.2

### ISSUE THREAD

**Issue by ljj8oo8** [opensourceBIM/BIMserver#319]
hi,I am a newcomer，when i building BIMSERVER parent-1.5.41 version,hava a error:**Failed to execute goal on project pluginbase: Could not resolve dependencies for project org.opensourcebim:pluginbase:jar:1.5.38-SNAPSHOT: Could not transfer artifact org.antlr:antlr:jar:3.5.2 from/to central (http://repo1.maven.org/maven2): Connection reset** ,the buildingsmartlibrary-1.0.11 dependency antlr-complete-3.5.2 this jar dependency antlr-3.5.2,but the maven repo can not find it, the antlr.org state **ANTLR v4 is written in ANTLR v3.5.2 and StringTemplate 4.0.8. In antlr-4.5.3-complete.jar, you'll find everything you need to run the ANTLR tool and make its generated parsers work.** ,so how do this work？ alert the buildingsmartlibrary pom.xml or download antlr-3.5.2.jar  add project build path

**Comment by rubendel** [comment]
"Connection reset" usually indicates connection problems. The mentioned library actually is on repo1.maven.org/maven2 (http://repo1.maven.org/maven2/org/antlr/antlr-complete/3.5.2/). So I suggest to try again.

**Comment by ljj8oo8** [comment]
@rubendel  thank you for you help ,this issue is my internet is error ,i use vnp is build suc~
