### ISSUE TITLE
BIMserver-1.4.0-FINAL-2015-11-04 and BimViews

### ISSUE THREAD

**Issue by dorak1** [opensourceBIM/BIMserver#320]
I would like to know that is the compatible version of BimViews and BIMSurfer for BIMserver-1.4.0-FINAL-2015-11-04.
I use bimvie.ws-1.3.11-FINAL-2015-11-17 and everything seems to work except for the 3d view. What should be the version of bimsurfer?
Thanks

**Comment by dorak1** [comment]
Any help please?

**Comment by garview** [comment]
download BIMserver-1.4.0-FINAL-2015-11-04.jar or BIMserver-1.4.0-FINAL-2015-11-04.war ,unzip it.
Then u will get it in 'plugins' folder
