### ISSUE TITLE
Unable to get the model loaded on bimviews 

### ISSUE THREAD

**Issue by jashnaafsal** [opensourceBIM/BIMserver#321]
Hi,

I am installing the bimserver on my MacBook Pro, 2.7 GHz Intel Core i5 OS X Yosemite 10.10.2. I have install the jdk 8 on my mac. Then I installed the bimserver by double clicking on the jar file of the version 'bimserver-1.4.0-FINAL-2015-11-04'. The bimserver installed file and i am able to view the web launched from BIMServer starter.
When I try to check in the ifc file, I can see the following error printed in the BIM Starter window. The model is not loading the web browser. It just shows 'model data loaded successfully' and Loading 0/0.

13-04-2016 13:06:20 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: org/bimserver/objectidms/jaxb.properties (in bimserver-1.4.0-FINAL-2015-11-04-filebasedobjectidm.jar)
13-04-2016 13:06:20 ERROR org.bimserver.plugins.PluginManager - 
org.bimserver.plugins.PluginException: java.nio.file.NoSuchFileException: lib/64/libIFCEngine.dylib
	at org.bimserver.ifcengine.JvmRenderEnginePlugin.init(JvmRenderEnginePlugin.java:73)
	at org.bimserver.plugins.PluginManager.initAllLoadedPlugins(PluginManager.java:495)
	at org.bimserver.BimServer.start(BimServer.java:347)
	at org.bimserver.JarBimServer.start(JarBimServer.java:67)
	at org.bimserver.JarBimServer.main(JarBimServer.java:36)
Caused by: java.nio.file.NoSuchFileException: lib/64/libIFCEngine.dylib
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544)
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.bimserver.ifcengine.JvmRenderEnginePlugin.init(JvmRenderEnginePlugin.java:47)
	... 4 more

**Comment by rubendel** [comment]
IfcEngine in this version is probably not working on OSX. You can change the engine to "IfcOpenShell", goto "User Settings" | "Render Engines" and select IfcOpenShell, then checkin your file again, hopefullt that works.

**Comment by jashnaafsal** [comment]
Hi Rubendel,

I tried changing to IfcOpenShell, though the error is not there now, but still the model is not loading. Here is what I can see on the bimstarter window:

13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellModel - Took 0.15 seconds to obtain representations for 0 entities
13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellEngine - Closing IfcOpenShell engine
13-04-2016 14:38:13 INFO  org.bimserver.GeometryGenerator - Rendertime: 155ms, Reused: 0 B, Total: 0 B, Final: 0 B
13-04-2016 14:38:16 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 0
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheManager - Start caching 917507.json
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheOutputStream - Renaming temp file 215911265.__tmp to 215911265
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheManager - Done caching 917507.json
13-04-2016 14:38:16 INFO  org.bimserver.servlets.Streamer - 1 messages written 44 B

There are some file not found error in the beginning. So I am pasting the entire log here:

No expanding necessary
OS: Mac OS X
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx4294m
-Xss1024k
-XX:MaxPermSize=256m
-classpath
lib:lib/activation.jar:lib/antlr-2.7.7.jar:lib/antlr-3.1.1-runtime.jar:lib/antlr-3.1.1.jar:lib/aopalliance-1.0.jar:lib/asm-3.3.1.jar:lib/bimserver-1.4.0-FINAL-2015-11-04-client-lib.jar:lib/bimserver-1.4.0-FINAL-2015-11-04-ifc.jar:lib/bimserver-1.4.0-FINAL-2015-11-04-shared.jar:lib/bimserver-1.4.0-FINAL-2015-11-04-xsltserializer.jar:lib/bimserver-1.4.0-FINAL-2015-11-04.jar:lib/catalina.jar:lib/classmexer.jar:lib/commons-beanutils-1.8.3.jar:lib/commons-beanutils-bean-collections-1.8.3.jar:lib/commons-beanutils-core-1.8.3.jar:lib/commons-cli-1.2.jar:lib/commons-codec-1.9.jar:lib/commons-collections-3.2.1.jar:lib/commons-fileupload-1.2.1.jar:lib/commons-io-1.4.jar:lib/commons-lang-2.4.jar:lib/commons-logging-1.1.1.jar:lib/commons-pool-1.5.2.jar:lib/cors-filter-1.5.jar:lib/cxf-core-3.0.3.jar:lib/cxf-manifest.jar:lib/cxf-rt-bindings-coloc-3.0.3.jar:lib/cxf-rt-bindings-corba-3.0.3.jar:lib/cxf-rt-bindings-object-3.0.3.jar:lib/cxf-rt-bindings-soap-3.0.3.jar:lib/cxf-rt-bindings-xml-3.0.3.jar:lib/cxf-rt-databinding-aegis-3.0.3.jar:lib/cxf-rt-databinding-jaxb-3.0.3.jar:lib/cxf-rt-databinding-jibx-3.0.3.jar:lib/cxf-rt-databinding-sdo-3.0.3.jar:lib/cxf-rt-databinding-xmlbeans-3.0.3.jar:lib/cxf-rt-features-clustering-3.0.3.jar:lib/cxf-rt-frontend-jaxrs-3.0.3.jar:lib/cxf-rt-frontend-jaxws-3.0.3.jar:lib/cxf-rt-frontend-js-3.0.3.jar:lib/cxf-rt-frontend-simple-3.0.3.jar:lib/cxf-rt-javascript-3.0.3.jar:lib/cxf-rt-management-3.0.3.jar:lib/cxf-rt-rs-client-3.0.3.jar:lib/cxf-rt-rs-extension-providers-3.0.3.jar:lib/cxf-rt-rs-extension-search-3.0.3.jar:lib/cxf-rt-rs-security-cors-3.0.3.jar:lib/cxf-rt-rs-security-jose-3.0.3.jar:lib/cxf-rt-rs-security-oauth-3.0.3.jar:lib/cxf-rt-rs-security-oauth2-3.0.3.jar:lib/cxf-rt-rs-security-sso-saml-3.0.3.jar:lib/cxf-rt-rs-security-xml-3.0.3.jar:lib/cxf-rt-rs-service-description-3.0.3.jar:lib/cxf-rt-security-3.0.3.jar:lib/cxf-rt-transports-http-3.0.3.jar:lib/cxf-rt-transports-http-hc-3.0.3.jar:lib/cxf-rt-transports-http-jetty-3.0.3.jar:lib/cxf-rt-transports-http-netty-client-3.0.3.jar:lib/cxf-rt-transports-http-netty-server-3.0.3.jar:lib/cxf-rt-transports-jms-3.0.3.jar:lib/cxf-rt-transports-local-3.0.3.jar:lib/cxf-rt-transports-udp-3.0.3.jar:lib/cxf-rt-ws-addr-3.0.3.jar:lib/cxf-rt-ws-mex-3.0.3.jar:lib/cxf-rt-ws-policy-3.0.3.jar:lib/cxf-rt-ws-rm-3.0.3.jar:lib/cxf-rt-ws-security-3.0.3.jar:lib/cxf-rt-wsdl-3.0.3.jar:lib/cxf-services-sts-core-3.0.3.jar:lib/cxf-services-ws-discovery-api-3.0.3.jar:lib/cxf-services-ws-discovery-service-3.0.3.jar:lib/cxf-services-wsn-api-3.0.3.jar:lib/cxf-services-wsn-core-3.0.3.jar:lib/cxf-tools-common-3.0.3.jar:lib/cxf-tools-corba-3.0.3.jar:lib/cxf-tools-java2ws-3.0.3.jar:lib/cxf-tools-misctools-3.0.3.jar:lib/cxf-tools-validator-3.0.3.jar:lib/cxf-tools-wadlto-jaxrs-3.0.3.jar:lib/cxf-tools-wsdlto-core-3.0.3.jar:lib/cxf-tools-wsdlto-databinding-jaxb-3.0.3.jar:lib/cxf-tools-wsdlto-frontend-javascript-3.0.3.jar:lib/cxf-tools-wsdlto-frontend-jaxws-3.0.3.jar:lib/cxf-xjc-boolean-3.0.2.jar:lib/cxf-xjc-bug671-3.0.2.jar:lib/cxf-xjc-dv-3.0.2.jar:lib/cxf-xjc-javadoc-3.0.2.jar:lib/cxf-xjc-runtime-3.0.2.jar:lib/cxf-xjc-ts-3.0.2.jar:lib/ehcache-2.8.5.jar:lib/FastInfoset-1.2.13.jar:lib/geoapi-2.3-M1.jar:lib/geoapi-pending-2.3-M1.jar:lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar:lib/geronimo-javamail_1.4_spec-1.7.1.jar:lib/geronimo-jaxws_2.2_spec-1.2.jar:lib/geronimo-jms_1.1_spec-1.1.1.jar:lib/geronimo-jta_1.1_spec-1.1.1.jar:lib/geronimo-servlet_3.0_spec-1.0.jar:lib/gson-2.2.4.jar:lib/guava-18.0.jar:lib/guice-2.0.jar:lib/hawtbuf-1.9.jar:lib/httpclient-4.3.6.jar:lib/httpclient-cache-4.3.2.jar:lib/httpcore-4.3.3.jar:lib/httpmime-4.3.2.jar:lib/ifcNamespaces.jar:lib/jackson-annotations-2.5.0.jar:lib/jackson-core-2.5.1.jar:lib/jackson-databind-2.5.1.jar:lib/jasypt-1.9.2.jar:lib/java-getopt-1.0.13.jar:lib/javassist.jar:lib/javax-websocket-client-impl-9.2.5.v20141112.jar:lib/javax-websocket-server-impl-9.2.5.v20141112.jar:lib/javax.annotation-api-1.2.jar:lib/javax.websocket-api-1.0.jar:lib/javax.ws.rs-api-2.0.1.jar:lib/jaxb-api-2.2.11.jar:lib/jaxb-core-2.2.10-b140310.1920.jar:lib/jaxb-impl-2.2.10-b140310.1920.jar:lib/jaxb-xjc-2.2.10-b140310.1920.jar:lib/jcl-over-slf4j-1.7.7.jar:lib/jdom-1.0.jar:lib/je-6.4.9.jar:lib/jettison-1.3.7.jar:lib/jetty-alpn-client-9.2.5.v20141112.jar:lib/jetty-alpn-server-9.2.5.v20141112.jar:lib/jetty-annotations-9.2.5.v20141112.jar:lib/jetty-cdi-9.2.5.v20141112.jar:lib/jetty-client-9.2.5.v20141112.jar:lib/jetty-continuation-9.2.5.v20141112.jar:lib/jetty-deploy-9.2.5.v20141112.jar:lib/jetty-http-9.2.5.v20141112.jar:lib/jetty-io-9.2.5.v20141112.jar:lib/jetty-jaas-9.2.5.v20141112.jar:lib/jetty-jaspi-9.2.5.v20141112.jar:lib/jetty-jmx-9.2.5.v20141112.jar:lib/jetty-jndi-9.2.5.v20141112.jar:lib/jetty-plus-9.2.5.v20141112.jar:lib/jetty-proxy-9.2.5.v20141112.jar:lib/jetty-quickstart-9.2.5.v20141112.jar:lib/jetty-rewrite-9.2.5.v20141112.jar:lib/jetty-schemas-3.1.jar:lib/jetty-security-9.2.5.v20141112.jar:lib/jetty-server-9.2.5.v20141112.jar:lib/jetty-servlet-9.2.5.v20141112.jar:lib/jetty-servlets-9.2.5.v20141112.jar:lib/jetty-util-9.2.5.v20141112.jar:lib/jetty-webapp-9.2.5.v20141112.jar:lib/jetty-xml-9.2.5.v20141112.jar:lib/jimfs-1.0.jar:lib/jna.jar:lib/joda-time-1.6.jar:lib/joda-time-2.2.jar:lib/JOpenId-1.08.jar:lib/js-1.7R2.jar:lib/jsr173_1.0_api.jar:lib/junit-4.8.2.jar:lib/jxl.jar:lib/log4j-1.2.16.jar:lib/log4j.xml:lib/mail.jar:lib/mina-core-2.0.9.jar:lib/neethi-3.0.3.jar:lib/nekohtml-1.9.14.jar:lib/oauth-20100527.jar:lib/oauth-provider-20100527.jar:lib/openid4java-0.9.8.jar:lib/openmali.jar:lib/opensaml-2.6.1.jar:lib/openws-1.5.1.jar:lib/org.eclipse.core.contenttype_3.4.200.v20120523-2004.jar:lib/org.eclipse.core.jobs_3.5.200.v20120521-2346.jar:lib/org.eclipse.core.resources_3.8.0.v20120522-2034.jar:lib/org.eclipse.core.runtime_3.8.0.v20120521-2346.jar:lib/org.eclipse.emf.codegen.ecore_2.9.1.v20130902-0605.jar:lib/org.eclipse.emf.codegen_2.9.0.v20130902-0605.jar:lib/org.eclipse.emf.common_2.9.1.v20130827-0309.jar:lib/org.eclipse.emf.ecore.xmi_2.9.1.v20130827-0309.jar:lib/org.eclipse.emf.ecore_2.9.1.v20130827-0309.jar:lib/org.eclipse.emf_2.6.0.v20130902-0605.jar:lib/org.eclipse.equinox.common_3.6.100.v20120522-1841.jar:lib/org.eclipse.equinox.preferences_3.5.0.v20120522-1841.jar:lib/org.eclipse.jdt.core_3.8.1.v20120531-0637.jar:lib/org.eclipse.osgi_3.8.0.v20120529-1548.jar:lib/protocolbuffers2.5.jar:lib/quartz-1.8.3.jar:lib/resolver.jar:lib/rome-1.0.jar:lib/servlet-api-3.1.jar:lib/slf4j-api-1.6.2.jar:lib/slf4j-log4j12-1.6.2.jar:lib/spring-aop-3.2.6.RELEASE.jar:lib/spring-beans-3.2.6.RELEASE.jar:lib/spring-context-3.2.6.RELEASE.jar:lib/spring-core-3.2.6.RELEASE.jar:lib/spring-expression-3.2.6.RELEASE.jar:lib/spring-web-3.2.6.RELEASE.jar:lib/stax2-api-3.1.4.jar:lib/stringtemplate-3.2.jar:lib/tar.jar:lib/tomcat-coyote.jar:lib/tomcat-juli.jar:lib/tomcat-util.jar:lib/velocity-1.7.jar:lib/websocket-api-9.2.5.v20141112.jar:lib/websocket-client-9.2.5.v20141112.jar:lib/websocket-common-9.2.5.v20141112.jar:lib/websocket-server-9.2.5.v20141112.jar:lib/websocket-servlet-9.2.5.v20141112.jar:lib/woodstox-core-asl-4.4.1.jar:lib/wsdl4j-1.6.3.jar:lib/wss4j-bindings-2.0.2.jar:lib/wss4j-policy-2.0.2.jar:lib/wss4j-ws-security-common-2.0.2.jar:lib/wss4j-ws-security-dom-2.0.2.jar:lib/wss4j-ws-security-policy-stax-2.0.2.jar:lib/wss4j-ws-security-stax-2.0.2.jar:lib/xbean.jar:lib/xbean_xpath.jar:lib/xercesImpl-2.8.1.jar:lib/xml-resolver-1.2.jar:lib/xmlbeans-2.6.0.jar:lib/xmlbeans-qname.jar:lib/xmlpublic.jar:lib/xmlschema-core-2.1.0.jar:lib/xmlsec-2.0.2.jar:lib/xmltooling-1.4.1.jar
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=/Users/afsalnishad/Desktop/home
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Logging to: /Users/afsalnishad/Desktop/home/logs/bimserver.log
13-04-2016 14:36:30 INFO  org.bimserver.BimServer - Starting BIMserver
13-04-2016 14:36:30 INFO  org.bimserver.BimServer - Using "/Users/afsalnishad/Desktop/home" as homedir
13-04-2016 14:36:34 INFO  org.bimserver.BimServer - Version: 1.4.0 - Wed Nov 04 00:00:00 IST 2015
13-04-2016 14:36:38 INFO  nl.tue.buildingsmart.emf.AbstractSchemaPlugin - IFC-Schema successfully loaded from IFC2X3_TC1.exp
13-04-2016 14:36:39 INFO  nl.tue.buildingsmart.emf.AbstractSchemaPlugin - IFC-Schema successfully loaded from IFC4.exp
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.ttl (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.rdf (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.n3 (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.rdf (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.n3 (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.ttl (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: file:ont-policy.rdf (in ifctordf.jar)
13-04-2016 14:36:39 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: file:etc/ont-policy.rdf (in ifctordf.jar)
Filtering : INTEGER; -> INTEGER
Filtering : LOGICAL; -> LOGICAL
Filtering : LOGICAL; -> LOGICAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : REAL; -> REAL
Filtering : REAL; -> REAL
Filtering : REAL; -> REAL
Filtering : REAL; -> REAL
Filtering : LOGICAL; -> LOGICAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : REAL; -> REAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : INTEGER; -> INTEGER
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : REAL; -> REAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : LOGICAL; -> LOGICAL
Filtering : LOGICAL; -> LOGICAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BINARY(32); -> BINARY
Filtering : LOGICAL; -> LOGICAL
Filtering : LOGICAL; -> LOGICAL
Filtering : LOGICAL; -> LOGICAL
Filtering : REAL; -> REAL
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : BOOLEAN; -> BOOLEAN
Filtering : LOGICAL; -> LOGICAL
Filtering : INTEGER; -> INTEGER
Filtering : INTEGER; -> INTEGER
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : STRING; -> STRING
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : INTEGER; -> INTEGER
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
Filtering : BOOLEAN; -> BOOLEAN
removing property 2 from property list: ContainedInStructure_IfcAnnotation
removing property 2 from property list: RelatedElements_IfcRelContainedInSpatialStructure
removed inverses of property: ContainedInStructure_IfcAnnotation
removing property 4: ContainedInStructure_IfcElement
removed inverses of property: RelatedElements_IfcRelContainedInSpatialStructure
removing property 2 from property list: HasAssociations_IfcPropertyDefinition
removing property 2 from property list: RelatedObjects_IfcRelAssociates
removed inverses of property: HasAssociations_IfcPropertyDefinition
removing property 4: HasAssociations_IfcObjectDefinition
removed inverses of property: RelatedObjects_IfcRelAssociates
removing property 2 from property list: LayerAssignments_IfcRepresentation
removing property 2 from property list: AssignedItems_IfcPresentationLayerAssignment
removed inverses of property: LayerAssignments_IfcRepresentation
removing property 4: LayerAssignments_IfcRepresentationItem
removed inverses of property: AssignedItems_IfcPresentationLayerAssignment
removing property 3: RelatedElements_IfcRelContainedInSpatialStructure
removing property 4: ContainedInStructure_IfcGrid
removed inverses of property: RelatedElements_IfcRelContainedInSpatialStructure
Ended reading the EXPRESS file and building internals
13-04-2016 14:36:46 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: org/bimserver/objectidms/jaxb.properties (in bimserver-1.4.0-FINAL-2015-11-04-filebasedobjectidm.jar)
13-04-2016 14:36:46 ERROR org.bimserver.plugins.PluginManager - 
org.bimserver.plugins.PluginException: java.nio.file.NoSuchFileException: lib/64/libIFCEngine.dylib
	at org.bimserver.ifcengine.JvmRenderEnginePlugin.init(JvmRenderEnginePlugin.java:73)
	at org.bimserver.plugins.PluginManager.initAllLoadedPlugins(PluginManager.java:495)
	at org.bimserver.BimServer.start(BimServer.java:347)
	at org.bimserver.JarBimServer.start(JarBimServer.java:67)
	at org.bimserver.JarBimServer.main(JarBimServer.java:36)
Caused by: java.nio.file.NoSuchFileException: lib/64/libIFCEngine.dylib
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544)
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.bimserver.ifcengine.JvmRenderEnginePlugin.init(JvmRenderEnginePlugin.java:47)
	... 4 more
13-04-2016 14:36:46 INFO  org.ifcopenshell.IfcOpenShellEnginePlugin - Using exe/64/osx/IfcGeomServer
13-04-2016 14:36:46 INFO  org.bimserver.templating.TemplateEngine - Using "Users/afsalnishad/Desktop/bimserver-1.4.0-FINAL-2015-11-04 (1)/home/templates/" as template dir
13-04-2016 14:36:46 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - Non-empty database directory found "/Users/afsalnishad/Desktop/home/database"
13-04-2016 14:36:47 INFO  org.bimserver.ServerInfoManager - Changing server state to RUNNING
13-04-2016 14:36:56 INFO  org.bimserver.JarBimServer - Server started successfully
13-04-2016 14:37:21 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 0
13-04-2016 14:37:21 INFO  org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
13-04-2016 14:37:21 INFO  org.ifcopenshell.IfcOpenShellModel - Took 0.08 seconds to obtain representations for 0 entities
13-04-2016 14:37:21 INFO  org.ifcopenshell.IfcOpenShellEngine - Closing IfcOpenShell engine
13-04-2016 14:37:21 INFO  org.bimserver.GeometryGenerator - Rendertime: 129ms, Reused: 0 B, Total: 0 B, Final: 0 B
13-04-2016 14:37:24 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 0
13-04-2016 14:37:24 INFO  org.bimserver.cache.DiskCacheManager - Start caching 851971.json
13-04-2016 14:37:24 INFO  org.bimserver.cache.DiskCacheOutputStream - Renaming temp file 152931169.__tmp to 152931169
13-04-2016 14:37:24 INFO  org.bimserver.cache.DiskCacheManager - Done caching 851971.json
13-04-2016 14:37:25 INFO  org.bimserver.servlets.Streamer - 1 messages written 44 B
13-04-2016 14:38:13 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 0
13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellModel - Took 0.15 seconds to obtain representations for 0 entities
13-04-2016 14:38:13 INFO  org.ifcopenshell.IfcOpenShellEngine - Closing IfcOpenShell engine
13-04-2016 14:38:13 INFO  org.bimserver.GeometryGenerator - Rendertime: 155ms, Reused: 0 B, Total: 0 B, Final: 0 B
13-04-2016 14:38:16 INFO  org.bimserver.ifc.IfcModel - Nr inverse fixes: 0
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheManager - Start caching 917507.json
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheOutputStream - Renaming temp file 215911265.__tmp to 215911265
13-04-2016 14:38:16 INFO  org.bimserver.cache.DiskCacheManager - Done caching 917507.json
13-04-2016 14:38:16 INFO  org.bimserver.servlets.Streamer - 1 messages written 44 B

**Comment by rubendel** [comment]
Can you maybe share the IFC file you are using? I don't have a working mac at the moment so can't test for any OSX related issues, but I can see whether my pc comes up with any geometry.

**Comment by jashnaafsal** [comment]
[BeamUnitTestsVaryingCardinal.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/216791/BeamUnitTestsVaryingCardinal.ifc.zip)

**Comment by jashnaafsal** [comment]
We were successfully able to load this ifc and view the 3D model on my team mates Linux(Ubuntu) machine.

**Comment by rubendel** [comment]
Ah this is an IFC4 file. IfcOpenShell does not handle those at the moment. RdfEngine should be able to do so but apparently doesn't for this file on OSX. Tested the file with RdfEngine on windows and it shows the beams. I'll pass this to the RdfEngine developer, and check with the IfcOpenShell developer when IFC4 will be supported.

**Comment by jashnaafsal** [comment]
Thanks for letting me know! I hope the ifc4 files starts working with RdfEngine on OSX soon. How will we know if there is a patch for it?

**Comment by pipauwel** [comment]
Hi Ruben.
The RDFEngine supports IFC4. Only the BIMServer Connector is by default set to IFC2x3. So this is something that wpuld thus need to be modified. Thank you for filing this issue!
Pieter

Op 13-apr.-2016 12:14 PM schreef Ruben de Laat <notifications@github.com>:

Ah this is an IFC4 file. IfcOpenShell does not handle those at the moment. RdfEngine should be able to do so but apparently doesn't for this file on OSX. Tested the file with RdfEngine on windows and it shows the beams. I'll pass this to the RdfEngine developer, and check with the IfcOpenShell developer when IFC4 will be supported.

**Comment by rubendel** [comment]
You can manually update the libifcengine.dylib file once there is a new version, or wait for a new release of the RdfEngine BIMserver plugin.

Pieter, are you saying this specific version of RDFEngine supports IFC4 of OSX? What do you mean with "the BIMserver Connector"?

**Comment by pipauwel** [comment]
Ruben,

With "the BIMserver Connector", I simply mean the IfcToRdfPlugin.java file in my project. The Init() function there defaults to ifc2x3tc1:

SchemaPlugin schemaPlugin = pluginManager.getFirstSchemaPlugin("ifc2x3tc1", true);

We can easily fix this, if you (BIMServer) are okay with this.

Pieter



________________________________
Van: Ruben de Laat <notifications@github.com>
Verzonden: woensdag 13 april 2016 13:26
Aan: opensourceBIM/BIMserver
CC: Pieter Pauwels
Onderwerp: Re: [opensourceBIM/BIMserver] Unable to get the model loaded on bimviews (#321)


You can manually update the libifcengine.dylib file once there is a new version, or wait for a new release of the RdfEngine BIMserver plugin.

Pieter, are you saying this specific version of RDFEngine supports IFC4 of OSX? What do you mean with "the BIMserver Connector"?

-

**Comment by rubendel** [comment]
I think there is a mixup of the namings, this topic is not about the IfcToRdfPlugin project. With RDF engine I mean the engine that the company RDF created (rdf.bg).

**Comment by pipauwel** [comment]
Oh, perhaps yes indeed!? Sorry! Those FileNotFound messages do not look familiar to me. Only the portion below is familiar (Filtering STRING; etc.). So the error resolves to the libifcengine.dylib file, right?




________________________________
Van: Ruben de Laat <notifications@github.com>
Verzonden: vrijdag 15 april 2016 14:32
Aan: opensourceBIM/BIMserver
CC: Pieter Pauwels
Onderwerp: Re: [opensourceBIM/BIMserver] Unable to get the model loaded on bimviews (#321)


I think there is a mixup of the namings, this topic is not about the IfcToRdfPlugin project. With RDF engine I mean the engine that the company RDF created (rdf.bg).

-
