### ISSUE TITLE
IfcGeomServer.exe

### ISSUE THREAD

**Issue by Kestukas** [opensourceBIM/BIMserver#324]
Hey, just trying to start reviewing this project .
newest version has strange error, 
when i upload icf , i get alot IfcGeomServer.exe stopped working errors on server 2012 ,and alot 
21:55:49 INFO  [pool-4-thread-10]: Entity not found IfcFlowFitting 7617/27852975  
errors.

checked on most version of windows, seems only windows 10 not had it, or i was lucky :)

**Comment by garview** [comment]
I met the same problem, whether it was win7 or win8, always popping up a lot of " IfcGeomServer.exe stopped working" error window

**Comment by rubendel** [comment]
Just had this happen on a laptop with not a lot of memory, which I suspect causes it. Will have a look at minimizing the amount of error popups to 1.

**Comment by garview** [comment]
After checkin an ifc file, There was no error message on the console but windows 7 alerted lots of error window like that:
![Uploading QQ截图20160705102227.png…]()
![Uploading QQ截图20160705102259.png…]()


After read issue #361  , i replaced the IfcOpenShell plugin from 0.5.15 to 0.5.9 and the error disappeared.(using BimServer 1.5.49)
So it shouldn't be a memory problem.

**Comment by rubendel** [comment]
Cool, thanks for reporting

**Comment by rubendel** [comment]
In an effort to resolve this, can you please state:
- Your operating system and it's version
- 32 or 64 bit operating system
- Amount of system memory. Amount of memory assigned to BIMserver.
- Full Java version
- Do you have any development tools installed?
