### ISSUE TITLE
plugin folder not created

### ISSUE THREAD

**Issue by woyzeck** [opensourceBIM/BIMserver#325]
I just cloned BIMserver and did a mvn clean compile - worked like a charm.

Unfortunately I have issues with the plugin folder as BIMserver complains at startup that no such folder could be found. Setting the plugins folder to `-p plugins "/Users/xxx/Documents/Development/BIMserver"` as suggested doesn't do much as there's no plugin folder there by default.

Is there anything that I have to do in order to get the plugin folder there ? Of course I could add it manually, but the docs don't mention that step.

**Comment by rubendel** [comment]
The syntax of the command should be ```-plugins /Users/xxx/Documents/Development/BIMserver```, so no ```-p```. However, in the newest version (GIT master) you don't have to include BIMserver itself anymore because no plugins are being loaded from it.

**Comment by woyzeck** [comment]
Sorry, typo.

I'm slightly confused. Where should the -plugins parameter point to given that I only checked out BIMserver (including all modules) and bimvie.ws ?

I can start the server (LocalDevBimServerStarter), but the log shows...
`WARN  [main]: No plugin directories given, this BIMserver will probably not work as expected`

As soon as I access http://localhost:8080 I get a 404.

**Comment by rubendel** [comment]
Hmm you should not be getting a 404, even without any plugins. Lets solve that first. Are there any other error messages? Which GIT branch are you using?

**Comment by woyzeck** [comment]
None that I could see in the server startup logs:

`Connected to the target VM, address: '127.0.0.1:58747', transport: 'socket'
Logging to /Users/nrumm/Documents/Development/BIMserver/home/logs/bimserver.log
10:17:01 INFO  [main]: Starting BIMserver (BimServer.java:211)
10:17:01 INFO  [main]: Using "home" as homedir (BimServer.java:213)
10:17:09 INFO  [main]: Version: 2.0.1-SNAPSHOT (BimServer.java:293)
10:17:17 INFO  [main]: No email templates found (BimServer.java:588)
10:17:17 INFO  [main]: Non-empty database directory found "home/database" (BerkeleyKeyValueStore.java:85)
10:17:21 INFO  [main]: Changing server state to RUNNING (ServerInfoManager.java:112)
EclipsePluginClassloader /Users/nrumm/Documents/Development/bimvie.ws
  DelegatingClassLoader
    DelegatingClassLoader
      FileJarClassLoader bimsurfer-0.0.3.jar`

When I access http://localhost:8080 with the browser, I just get a 404, generated by RootServlet:
`InputStream resourceAsStream = getServletContext().getResourceAsStream(requestUri);
				if (resourceAsStream != null) {
					IOUtils.copy(resourceAsStream, response.getOutputStream());
				} else {
					response.setStatus(404);
					try {
						response.getWriter().println("404 - Not Found");
					} catch (IllegalStateException e) {
					}
				}`

I'm on HEAD.

**Comment by rubendel** [comment]
There is something going wrong with the home directory I think, the message "No email templates found (BimServer.java:588) " should also not be there. Can you try and delete your homedirectory and let BIMserver create it again?

**Comment by woyzeck** [comment]
Ah, thank you so much. Your hint related to the email templates lead me on the right path.

I use IntelliJ instead of Eclipse and it seems that the project's Maven-setup confused the IDE. The problem was that the classpath settings and the home folder were not in sync. Once I changed the home folder to BIMserver/BIMserver (so pointing into the BIMserver module) everything worked.

Thank you !
