### ISSUE TITLE
delete revisions

### ISSUE THREAD

**Issue by maxife** [opensourceBIM/BIMserver#327]
Hi !!
We are a team of french students working on BIMserver to create an interaction with a bacnet system (for example changing the color of the roof according to the outside temperature). We are able to create a new revision that contain the changing we want and we are able to visualize it. But it creates a new revision each time and it could lead to some size problems in the future. We want to delete old revisions but we didn't find how to do it. Did you have any lead on this ?

**Comment by rubendel** [comment]
Hi, this has been a design decision from the start of the project. The idea is the same as for example GIT.

Modifying the model for alternative visualizations might not be the best way to go anyway. You could also for example upload extended data with the visualization information to the revision. BIMvie.ws understands data formatted according to this schema: https://github.com/opensourceBIM/BIMserver-Repository/wiki/3D-Visualization-Effects
