### ISSUE TITLE
how to solve large ifc file

### ISSUE THREAD

**Issue by ljj8oo8** [opensourceBIM/BIMserver#329]
hi,i should use BimServer to my project,but in my project the ifc file is very big,the single file is 600M+,i try to check in 600M+ IFC file ,13HEAP size server setup,it spend three hours,it's so long,what should I do？ add thread? i want to konw which part spend much time on the BimServer,how to optimize,please gvie me some  adivce!

**Comment by rubendel** [comment]
The long time is probably spent generating the geometry. You can try an alternative Render Engine to make that faster. It could also be slow because of the amount of memory, if it's still too low, garbage collection in the JVM is going to take a lot of time too.

**Comment by ljj8oo8** [comment]
@rubendel , i try to alternative  GeometryGenerator.java file, i find the maxSimultanousThreads 
always equals 1 when i check in any size ifc file,why? when i  try set maxSimultanousThreads =2+,the system spend time  is less,but the data less too,i do not fully understand the GeometryGenerator.java file，can you tell me why this is

**Comment by rubendel** [comment]
You can change this setting in Server Settings

**Comment by ljj8oo8** [comment]
@rubendel ,this Max Render Engine Processes is beta,i'm run in BIMserver-1.4.0-FINAL-2015-11-04,this Features is not correct running,here is the test log

_MaxRenderEngineProcesses=1
17:49:27 INFO  GeometryGenerator - Rendertime: 416.712m, Reused:    202.16 MB, Total:    228.89 MB, Final:     26.73 MB
17:50:08 INFO  BerkeleyKeyValueStore - writes: 1120570

MaxRenderEngineProcesses=2
17:33:12 INFO  GeometryGenerator - Rendertime: 127.393m, Reused:    202.13 MB, Total:    227.44 MB, Final:     25.32 MB
17:34:01 INFO  BerkeleyKeyValueStore - writes: 2239567
![2](https://cloud.githubusercontent.com/assets/15099158/14848620/2473a992-0ca1-11e6-8e04-ca5fa11dea54.png)
![3](https://cloud.githubusercontent.com/assets/15099158/14848627/26f800d2-0ca1-11e6-8c34-68ff885fb1c2.png)


MaxRenderEngineProcesses=4
17:37:15 INFO  GeometryGenerator - Rendertime: 98.351m, Reused:    202.13 MB, Total:    227.44 MB, Final:     25.32 MB
17:37:58 INFO  BerkeleyKeyValueStore - writes: 3358562_


Increase the number of threads, the more data is lost while writing data to the database becomes more，one thread  data correct

**Comment by rubendel** [comment]
In 1.4 this was indeed a beta feature, which did not work correctly. In 1.5 this will work.
