### ISSUE TITLE
Sub-project name change

### ISSUE THREAD

**Issue by cornhegne** [opensourceBIM/BIMserver#330]
if i make a typo while adding a new sub-project, then i have to delete it and then add a new one.

would you please add a "rename" feature to allow me to change the name of a sub project.

**Comment by berlotti** [comment]
![schermafdruk 2016-04-26 15 11 19](https://cloud.githubusercontent.com/assets/356921/14819224/60b11eca-0bc1-11e6-8f5f-efe627a96971.png)

**Comment by berlotti** [comment]
go to the project; click the tab 'subprojects'; click on 'actions' behind the subproject you want to delete; you will get an option to delete the subproject

**Comment by cornhegne** [comment]
i do not want to "delete" the subproject. I want to "rename" the subproject.

**Comment by cornhegne** [comment]
Also how do i re-open an issue that was incorrectly closed.

**Comment by berlotti** [comment]
This can be done with the 'updateProject' call in the API/serviceinterface. 
At the moment this call is not implemented in the Bimvie.ws GUI.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/bimvie.ws/issues/52
