### ISSUE TITLE
Problem with setup of release 1.5

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#332]
Hi Ruben,
thank you for publishing the new dev release 1.5 of bimserver. I downloaded and installed it on Tomcat.

Unfortunately I get this message on the setup page and could not finish the setup:

```
Required dependency org.opensourcebim:bimserverapi is not installed
Setup aborted
```

Am I doing something wrong?

**Comment by klacol** [comment]
Hi again,

today I tried again from scratch to setup V 1.5. Now I can describe the problem better.

After extracting the content of the file bimserverwar-1.5.45.war into the Tomcat folder I have to fix the file setup.html; then stop the App and start it again.
(OT: see also https://github.com/opensourceBIM/BIMserver/pull/331)

After that, the setup wizard starts smoothly and I can edit the setup configuration and click "Setup". After that the server is set up but I get this message  

`
Required dependency org.opensourcebim:bimserverapi is not installed
Setup aborted
`
After that I am redirected to this page:

![image](https://cloud.githubusercontent.com/assets/10479772/14862072/28d84330-0cb0-11e6-9877-f3ad4cfc2cd7.png)

Now I am stuck and cannot use the server.

**Comment by rubendel** [comment]
Hi, there was not only a type in this code, but also the order of dependencies was wrong after adding the console webmodule.

I'll make a new release later, but for now, please copy-and-paste the following over the ```stage3``` function in setup.html:

```
this.stage3 = function(){
		o.logInfo("Installing plugins...\n");
		
		var pluginsToInstall = {
			ifcplugins: {repository: "http://central.maven.org/maven2", groupId: "org.opensourcebim", artifactId: "ifcplugins"},
			binaryserializers: {repository: "http://central.maven.org/maven2", groupId: "org.opensourcebim", artifactId: "binaryserializers"},
			bimserverapi: {repository: "http://central.maven.org/maven2", groupId: "org.opensourcebim", artifactId: "bimserverapi"},
			console: {repository: "http://central.maven.org/maven2", groupId: "org.opensourcebim", artifactId: "console"}
		};
		cd.find(".plugins input[type=\"checkbox\"]:checked").each(function(index, checkbox){
			var artifactId = $(checkbox).attr("class");
			if (artifactId == "bimviews") {
				pluginsToInstall["bimsurfer"] = {
					repository: "http://central.maven.org/maven2",
					groupId: "org.opensourcebim",
					artifactId: "bimsurfer"
				};
			}
			pluginsToInstall[artifactId] = {
				repository: "http://central.maven.org/maven2",
				groupId: "org.opensourcebim",
				artifactId: artifactId
			};
		});
		
		installRequiredPlugins(pluginsToInstall, function(){
			o.logSuccess("All plugins successfully installed");
			if (pluginsToInstall["bimviews"] != null) {
				var link = $("<a>Open BIMvie.ws</a>");
				link.click(function(){
					document.location = $(".setup .siteAddressInput").val() + "/apps/bimviews";
				});
				cd.find(".finish pre").append("<br/>");
				cd.find(".finish pre").append(link);
			}
		});
	};
```

**Comment by klacol** [comment]
Hi, thanks! That worked.

Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Installing plugins...

Installing IfcPlugins...
Successfully installed IfcPlugins (org.opensourcebim:ifcplugins:0.0.13)

Installing BinarySerializers...
Successfully installed BinarySerializers (org.opensourcebim:binaryserializers:0.0.13)

Installing BIMServer JavaScript API...
Successfully installed BIMServer JavaScript API (org.opensourcebim:bimserverapi:0.0.94)

Installing Console...
Successfully installed Console (org.opensourcebim:console:0.0.3)

Installing BIMsurfer...
Successfully installed BIMsurfer (org.opensourcebim:bimsurfer:0.0.15)

Installing BIMvie.ws...
Successfully installed BIMvie.ws (org.opensourcebim:bimviews:0.0.44)

Installing IfcOpenShellPlugin...
Successfully installed IfcOpenShellPlugin (org.opensourcebim:ifcopenshellplugin:0.5.11)

All plugins successfully installed

Open BIMvie.ws

**Comment by klacol** [comment]
Now I get the Login page, but then I get this error:

This version of BIMserver (1.5.45) has not been tested with this version of BIMvie.ws
Method login not found on org.bimserver.AuthInterface (suggestion: Bimsie1AuthInterface)

What should I do next?

**Comment by rubendel** [comment]
Ah yes, BIMvie.ws is already out of sync with BIMserver 1.5 because the Bimsie1* interfaces have been renamed/removed. At the moment BIMserver (1.5) always downloads the latest versions of plugins, which causes this error. At the end of today I'll make a new release.

**Comment by klacol** [comment]
Great, with BIMserver 1.5.47 it workes now.
https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.47

Thanks

**Comment by rubendel** [comment]
Great, thanks for the feedback
