### ISSUE TITLE
Location of database

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#338]
Hi,

I have a question about the location of the database files. As I know, all the models are stored in the Berkeley DB Java Edition. In the server setting I see that DB files are stored in the temp folder of Tomcat:

...Tomcat 8.0\temp\19-V15\WEB-INF\database

The database is stored in a folder which can easily be deleted, since it is stored under a folder named "temp".

Can I somewhere configure another location for the database, or shoul I backup it from there?

Thanks
Klaus

**Comment by rubendel** [comment]
Yes, it is a good idea to move it somewhere else, please see https://github.com/opensourceBIM/BIMserver/wiki/Install-on-Ubuntu#setting-the-homedir

**Comment by klacol** [comment]
ok, thanks. It workes like a charm.
