### ISSUE TITLE
Question : how to parse the data in GeometryData?

### ISSUE THREAD

**Issue by gstslxd** [opensourceBIM/BIMserver#344]
Hi,
I'm writing a java client to connect to the bimserver 1.5.47. I use `BinaryGeometryMessagingStreamingSerializer` to get the dataInputStream. This works quite well, but I'm wondering how to parse normal and vertice from the `GeometryData.getNormals` and `GeometryData.getVertices` that stored in a byte array.
thank you.

**Comment by rubendel** [comment]
Those are little-endian arrays of type float (4 bytes per float). They are being indexed by the indices.

**Comment by gstslxd** [comment]
Thank you for your fast reply. Now I have get the data I need to create a geometry.

**Comment by gstslxd** [comment]
oh, sorry. I only parse the value such as indices, vertices in GeometryData, but for the transformation  in geometryInfo, I used the code below to parse it.
```
byte[] transformation = new byte[16 * 8];				
dataInputStream.readFully(transformation);				
geometryInfo.setTransformation(transformation);					
byte[] newbyte = new byte[8];
for(int i=0;i<transformation.length/8;i++){				
	newbyte=Arrays.copyOfRange(transformation, i*8, (i+1)*8);
	double dou = LittleEndianBinUtils.byteArrayToDouble(newbyte);
	System.out.println("the "+i+" value of matrix is ："+dou);					
}
```
But I get the result:
the 0 value of matrix is ：3.03865E-319
the 1 value of matrix is ：0.0
the 2 value of matrix is ：0.0
the 3 value of matrix is ：0.0
the 4 value of matrix is ：0.0
the 5 value of matrix is ：3.03865E-319
the 6 value of matrix is ：0.0
the 7 value of matrix is ：0.0
the 8 value of matrix is ：0.0
the 9 value of matrix is ：0.0
the 10 value of matrix is ：3.03865E-319
the 11 value of matrix is ：0.0
the 12 value of matrix is ：2.047569450854E-312
the 13 value of matrix is ：2.733015882744E-312
the 14 value of matrix is ：0.0
the 15 value of matrix is ：3.03865E-319
so the object in IFC model are not placed in the right place.
![1](https://cloud.githubusercontent.com/assets/16719875/15451859/ddb2ed74-200a-11e6-9e66-03f122e4e476.png)
I have searched other issues like:
https://github.com/opensourceBIM/BIMserver/issues/106
https://github.com/opensourceBIM/BIMserver/issues/274
But they don't help me. 
How to parse the transformation matrix?
thank you very much.

**Comment by rubendel** [comment]
That looks a bit overcomplicated, try this
```
		ByteBuffer buffer = ByteBuffer.wrap(transformationByteArray);
		buffer .order(ByteOrder.LITTLE_ENDIAN);
		DoubleBuffer doubleBuffer = buffer .asDoubleBuffer();
		for (int i = 0; i < 16; i++) {
			double doSomethingWithThis = doubleBuffer.get(i);
		}
```

**Comment by gstslxd** [comment]
Thank you again for your fast reply. It's amazing and it works. 
I'm sorry for my crossposting.
