### ISSUE TITLE
No plugin context found for org.bimserver.serializers.JsonSerializerPlugin

### ISSUE THREAD

**Issue by wuyandefeixue** [opensourceBIM/BIMserver#345]
My English is not very good, hope forgive me!

From this connection of https://github.com/opensourceBIM, I download BIMserver(BIMserver-parent-1.5.48) and bimvie.ws(bimvie.ws-bimviews-0.0.47).

Modify maven setting and maven install all child project,so I got a jar file(bimserverstarter-1.5.48-bimserverstarter-1.5.48.jar)

Run this jar file,and launch it successfully.
(14:03:46 INFO  [main]: Server started successfully )

Running chrome browser，enter http://localhost:8082, found a page of step, In the final step, I got 
an error about this.

1.jar file:
java.lang.Exception: No plugin context found for org.bimserver.serializers.JsonSerializerPlugin

2.browser:
Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Installing plugins...

Installing IfcPlugins...
No plugin context found for org.bimserver.serializers.JsonSerializerPlugin
Setup aborted

**Comment by wuyandefeixue** [comment]
I have solved this problem

**Comment by rubendel** [comment]
That is great. Do you mind sharing how you solved it, in case other people stumble across the same issue?
