### ISSUE TITLE
One question to the uniqueness of OID

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#346]
Hi,

in this article you describe very detailed the diffent identifiers of the bimserver:
https://github.com/opensourceBIM/BIMserver/wiki/Terminology

We store the OID in our internal database, and it has to be persistent forever.

One question for clarification: You write: "With unique we mean unique within the instance of the BIMserver". What is exactly the instance of the bimserver? Is is the database of one installtion (context) on the TomCat Host?

Thanks
Klaus

**Comment by rubendel** [comment]
Yes it's the database. As long as you use the same database the OID's will be unique and unchanged.

**A note on database migrations**
In theory released versions of BIMserver should always be capable of migrating the database to newer schema's, so you won't ever have to delete your database. Though in practice, the database structure changes drastically between big releases (1.3 -> 1.4, 1.4 -> 1.5) which usually results in running a script that moves data from the old server to the new server, in that case new OID's will be generated.

**Comment by klacol** [comment]
Ok, thanks for clarification. The database migration will be the biggest challenge. Are there plans to use e.g. persistent GUID's as external persistand identifiers, oder some other concept?

The usage of the API is based on the identifiers and everyone you connect bimserver to it own app will loose connection otherwise.

Could you please past a link to the migration code, so that we can have a look what we can do to not be forced to stuck with an old version of bimserver.

**Comment by rubendel** [comment]
There are basically 2 types of database migration.

**Automatic schema migration steps**
These are pieces of code, identified by a number. This number is both stored in the database and in the code. When these numbers are different (for example database version 5, BIMserver code 6), BIMserver will try to upgrade the database by applying the changes defined in step 6.

This works well as long as basic changes are being done, like adding another entity, adding fields, removing fields etc... When changes are done to the database structure/access pattern that cannot be defined in the migrations steps, BIMserver will not be able to migrate, and the only other option is to write manual code to move data from an old server to a newer (this is what I mentioned in my previous post).

The code for this can be found here https://github.com/opensourceBIM/BIMserver/tree/master/BimServer/src/org/bimserver/database/migrations/steps

**Manual migration**
An example of this is the code that migrates (a limited amount of data) between BIMserver 1.3 and 1.4: https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/BimServerImporter.java

This code basically connects to a given BIMserver, downloads a list of projects, revisions, users etc... and recreates those in the new server. This was enough for the project we needed it for, but you could add more. As you can see, this code is not (like the automatic migrations) standardized in any way. It's just a piece of code written specifically for the purpose. It's not said that a comparable migration will be written for 1.4->1.5.

_Important note: This way of migration will not (and cannot) retain your old oid's_

**Which version are not auto migratable**
1.3 -> 1.4
1.4 -> 1.5

We will try to make 1.5 auto migratable to 1.6 or whatever comes after it. But when certain improvements popup that are too important but brake the migration, we will probably do it. When the platform is more stable/used we probably won't be able to get away with that, from that moment on you can rely on oid's for linking with other systems.
