### ISSUE TITLE
Cash detection in BimServer

### ISSUE THREAD

**Issue by garview** [opensourceBIM/BIMserver#347]
Hi,
Have seen the issue #238 , also made some tests. It seems the feature cash detection do not work.
How to enable cash detection in  BIMserver-1.4.0-FINAL-2015-09-14?
Hope to give some guidance.
best reguards.

**Comment by rubendel** [comment]
I'll quote from the referenced issue "We decided to remove this feature from BIMserver some time ago"

**Comment by klacol** [comment]
Hi, cash detection , or clash detection? cash detection would be also a nice feature.
Only a joke, sorry, never mind :-)

**Comment by garview** [comment]
It seems that I have made a very stupid mistake?
I did see that  "We decided to remove this feature from BIMserver some time ago".
However, in  #238, I saw the BimServer remove this feature because "but IfcOpenShell never had clash detection". And then in the next user aothms answer, it is understood that ifcopenshell has provided the function of collision conflict.
The way to remove reason function has disappeared, so I thought the collision function should be used to.
I'm a new a person in Bim. Maybe this is a little stupid.
However, in the case of ifcopenshell provides collision detection, why "the ClashDetectionServicePlugin non-working left"?
kind regards.

**Comment by rubendel** [comment]
You did not understand correctly, it's on IfcOpenShell's roadmap (https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/b5e3ee85/#b6b2). Since the current version is 0.5.0, that feature probably won't be implemented in the next 2 years.

There is however a new project that will implement a Java based clashdetection service as a BIMserver plugin. https://github.com/opensourceBIM/ClashDetectionService. If you have any resources to spare it might be useful to contribute to that project.

**Comment by garview** [comment]
Thank you rubendel, untie my doubts and misunderstandings. I'll try it out.

**Comment by niharikapothani** [comment]
Hello ,  
I need to run clash detection on IFC file. I see that the clash detection plugin is available at https://github.com/opensourceBIM/ClashDetectionService. But How can I add this clash detection plugin in BIM SERVER 1.4 ?

**Comment by rubendel** [comment]
That version of ClashDetection will only work on BIMserver 1.5. Also make sure you read the initial page of that project: https://github.com/opensourceBIM/ClashDetectionService

**Comment by niharikapothani** [comment]
Can I run clash detection on IFC file in BIM server 1.4? and how ?
