### ISSUE TITLE
communicating with BIMserver using the same user in multiple sessions

### ISSUE THREAD

**Issue by ilyakuznetsov** [opensourceBIM/BIMserver#348]
Hi, we are extending our web application to provide our users with possibility to commit/download models to/from BIMserver and also to visualize them using BIMsurfer.

We want to use always the same user to communicate with BIMserver, therefore it is for sure possible, that some sessions will be active or run simultaneously, for example during commit a model, geometry data of some model will be queried using the same user (token). 

The question is, if such setup is buggy and could lead to some problems or maybe have you already experience with it? 
What should we be aware of? any tips appreciated! 
thx in advance

**Comment by rubendel** [comment]
A very late reply...

This is definitely possible, a few things to look out for:
- Updates to the same project are not possible simultaneously, BIMserver will try a few times but fails after 10 tries, which could make things very slow
- If you want to use websockets (e.a. asynchronous feedback), make sure you generate new tokens (they can all be tokens for the same user account).
