### ISSUE TITLE
Items in server settings are not stored in the database

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#350]
There are three items in the server settings which are not stored properly in the database:

Server name
Site description
Server icon

I can put some data in, and change the field; then I get the meeage "Server settings successfully updated". But when I load the server settings page again, the values are not displayed again.

**Comment by rubendel** [comment]
Which versions of BIMserver/BIMvie.ws are this? Because both of them need to be up-to-date for this to work. Just tested with GIT head versions and seems to work here.

**Comment by klacol** [comment]
BIMserver: 1.5.48 (Schema 23)
BIMvie.ws: 0.0.48

**Comment by rubendel** [comment]
Ah yes these new fields are in schema version 24. This is working in the (just released) BIMserver 1.5.49 with the latest BIMvie.ws release.

Somewhere before the 2.0 release I'll try and implement some actual dependency-version checking. Not exactly sure how yet.

**Comment by klacol** [comment]
It workes now with BIMserver 1.5.49
Thank you!
