### ISSUE TITLE
URL in to webservice console is wrong

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#351]
On the page .../apps/bimviews/?page=ServerInfo&subpage=webservices one can click on "JSON" to get to the webservice console.

This link directs to .../apps/bimviews/console.html and is dead
This link is working: ../apps/console

The link on the subpage webservices should be corrected.

OT:
On the server 1.4 the link is ../console.html and has to be changed by the webservice clients.

**Comment by rubendel** [comment]
Thanks, for now I have just removed this link. It was not a webservice-specific link anyways (always linked to console.html with no arguments). Also we can't be sure that the "Console" app is installed.

**Comment by klacol** [comment]
ok, that's right. Thanks.
