### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by janiamul** [opensourceBIM/BIMserver#353]
Hi, I am new to BIMserver. I have installed the BIMserver and checked in a few ifc2x3 files successfully using both, BIMvie.ws and the console. Now I am trying to download the same files. While I am able to download the files using BIMvie.ws, I am not able to download the file using the console. I am using the method "downloadRevisions". 

Here's the Request being sent:
"request": {
    "interface": "ServiceInterface", 
    "method": "downloadRevisions", 
    "parameters": {
      "roids": ["393219"],
      "serializerOid": 524326,
      "sync": "false"
    }
  }

Response:
{
  "response": {
    "result": 42
  }
}

BIMserver Starter log:
14:41:33 INFO  [Download]: Reading from cache SmileyWest.ifc       (DiskCacheManager.java:101) 

BIMvie.ws Server log: 
Duration        Description           State          Progress
45 minutes    Done preparing    Running     (keeps moving)

**Comment by rubendel** [comment]
Calling the "downloadRevisions" method returns a "topicId", which is a number specific for this download action. You can use this id to actually get the data, but this feature has not been implemented in "console.html". The method for downloading is called "ServiceInterface.getDownloadData" and it requires the "topicId".

**Comment by janiamul** [comment]
Thanks Ruben,
I used the IFC2x3tc1 deserializer to check in an IFC2x3 file and am using the IFC2x3tc1 serializer for the "downloadRevisions" method. While what you suggested is working, the method "getDownloadData" fetches data which looks like:
SVNPLTEwMzAzLTIxOwpIRUFERVI7CkZJTEVfREVTQ1JJUFRJT04gKCgnQXJjaGlDQUQgMTEuMDAgUmVsZWFzZSAxIGdlbmVyYXRlZC....

how do I get the data in this format below?
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(some text);
FILE_NAME(some text);
FILE_SCHEMA(('IFC2X3'));
ENDSEC;

DATA;
#1= IFCORGANIZATION('GS','Graphisoft','Graphisoft',$,$);
#5= IFCAPPLICATION(#1,'11.0','ArchiCAD 11.0','ArchiCAD');
...

**Comment by rubendel** [comment]
The data will be base64 encoded, so you can base64 decode to get the IFC data.

Another option is to use the download servlet, which will be more efficient for large files as no base64 encoding will be done. The URL for that looks like this:

[your bimserver address]/download?token=[your token]&serializerOid=[serializer oid]&topicId=[topicId]

**Comment by janiamul** [comment]
Thanks Ruben,
the download servlet works like a charm... your support is much appreciated.
