### ISSUE TITLE
Bug : XSS in Jetpack plugin

### ISSUE THREAD

**Issue by Sumitcfe** [opensourceBIM/BIMserver#357]
Hey,
 It seems like you are using an unpatched Jetpack version.
 Your changelog says so
http://bimserver.org/wp-content/plugins/jetpack/changelog.txt

It is known to be vulnerable to XSS
 Check it https://jetpack.com/2016/05/27/jetpack-4-0-3-critical-security-update

Please update your plugin.

Thanks.
Sumit  Jain

**Comment by rubendel** [comment]
We are not using jetpack, these automatically reported issues are not appreciated.
