### ISSUE TITLE
Can not load the login page http://<bimsever>/bimserver/?Login  

### ISSUE THREAD

**Issue by webdada** [opensourceBIM/BIMserver#359]
Page:
Error Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror
Loading BIMviews...

Javascript Console Log:

http://localhost/bimserver/js/bimserverapi_BimServerApi.js?bust=bimviews-1.3.12 Failed to load resource: net::ERR_CONNECTION_REFUSED
bimserverapibootstrap.js?_v=bimviews-1.3.12:25 Error: Script error for: bimserverapi_BimServerApi(…)
http://localhost/bimserver/js/bimserverapi_BimServerApiPromise.js?bust=bimviews-1.3.12 Failed to load resource: net::ERR_CONNECTION_REFUSED
bimserverapibootstrap.js?_v=bimviews-1.3.12:25 Error: Script error for: bimserverapi_BimServerApiPromise(…)

Sam 
dada.sam@gmail.com

**Comment by rubendel** [comment]
Well that's not an actual address, did you replace it with a URL of a running BIMserver?
