### ISSUE TITLE
there is have some  issue for BIMserver-1.4.0-FINAL-2015-11-04

### ISSUE THREAD

**Issue by ljj8oo8** [opensourceBIM/BIMserver#363]
hi,there is some bug in my using 
1.project name bug:create name a project delete it,if i will create name a project again it's failed
2.check in IFC file name  Chinese garbled
3.if  assume my computer ip=192.168.1.1,i set BIMserver ip=192.168.1.1,the system can't display IFC model what ever user to localhost or local ip,system show error TypeError: o.viewer.scene.findNode is not a function,but i was used to  ip access suc in other computer

**Comment by rubendel** [comment]
1. This is as designed
2. Just tested an IFC file with Chinese characters in the filename, no issues here. More information would be useful, for example what the filename was.
3. If you bind to 192.168.1.1, BIMserver won't be available on 127.0.0.1

**Comment by ljj8oo8** [comment]
@rubendel  Thank you for your answer
