### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#364]
Hi @rubendel 
Is there any information about the structure of the src of the project?
How I can change in source code colors of the rendered ifc file (which class)?

**Comment by rubendel** [comment]
BIMserver does not assign colors to objects. Objects either have colors assigned to them in the original IFC file, or get assigned a color by the client that is used (for example BIMvie.ws/BIMsurfer).

**Comment by VladMala** [comment]
thnx @rubendel ! 
Could you specify where is it assigned in BIMvie.ws?

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMsurfer/blob/master/api/Constants.js#L54

**Comment by VladMala** [comment]
thnx a lot @rubendel
