### ISSUE TITLE
bimviews build

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#365]
Hi @rubendel ! Just final question :)
How to make the server bimserverstarter-1.5.49-bimserverstarter-1.5.49.jar on installing plugins process make use the local jar of bimviews-0.0.48.jar which was built with changes of BimSurfer project?
What is the right way to build the  bimviews-0.0.48.jar - is it correct to build first BimSurfer jar with unique version (eg 0.0.23-SNAPSHOT) and after that change pom of bimvie.ws-bimviews-0.0.48 and mvn install on it?

**Comment by rubendel** [comment]
If you only made changes in BIMsurfer, that's the only project you would have to "build". At the moment, dependencies are not being checked on version numbers (they should, but it's too much work at the moment to maintain).

Also, at the moment, it is only possible to install plugins that have been deployed on a maven repository (well actually there is a second method, which requires running from your IDE, probably not what you want). We plan on adding at least a method to upload your own plugins, and will probably add an implementation to BIMvie.ws as well, but that might take a few more months.

**Comment by VladMala** [comment]
thnx @rubendel ! is mvn install enough for building BIMsurfer?

**Comment by rubendel** [comment]
First you should run grunt (npm). After that run maven (release:prepare release:perform), but be prepared to do a lot of configuration before you can actually deploy to maven (which is out of BIMserver support-scope).

**Comment by VladMala** [comment]
hi @rubendel!   I know that you use BerkleyDB to parse ifc files. is it possible to store some new data to this local db? which part of logic can i use to save some data to db from new input added to biemvie.ws? Thanks in advance!

**Comment by rubendel** [comment]
Could you please open a new topic for each different issue/question?
