### ISSUE TITLE
BIM server is not working behind IIS (SSL-Offloader ).

### ISSUE THREAD

**Issue by rantidev1** [opensourceBIM/BIMserver#366]
When installing SSL certificate in Tomcat and accessing BIM Server over HTTPS connection , it works fine. However deploying BIM Server on Tomcat and using IIS as an SSL-Offloader , there is an websocket error while accessing it over https connection.

Is there any specific version of IIS which is supported by BIM Server or anything needs to be done
either on IIS or on BIM Server.  

Thanks in advance.

**Comment by rubendel** [comment]
I only have used NGINX for SSL-offloading and that works just fine. Had to a a little bit of configuration for the websockets though, probably the same on IIS. Make sure the SiteAddress in BIMserver is the address on which it will be available, not what it's "running on".

You are talking about a websocket error, would be useful to know what the actual error is...

**Comment by rantidev1** [comment]
Hi Ruben, 

While trying to access bimserver  over https  using IIS as an SSL-Offloader , I got login page successfully and there was no error in console. But after filling in the credentials i got Web Socket error , please check below:

![bim_server_web_socket_error](https://cloud.githubusercontent.com/assets/9971904/16377604/4f37904e-3c67-11e6-9c3f-b7743810a6dd.png)

**Comment by rubendel** [comment]
Which version of IIS are you using and did you check the whether it actually supports WebSockets? Did you try without SSL on IIS?

**Comment by rantidev1** [comment]
We are using IIS 8.5 on Windows Server 2012 R2 , and it supports web sockets. When i tried to access BIMServer over HTTP with IIS , still got the same result as mentioned in my previous comment.

**Comment by coryasilva** [comment]
@rantidev1 Just saw this thread.  I extensively tested this with IIS8.5/ARR and it simply will not handle ws/wss: protocols.  I would strongly encourage you to use nginx; it may be daunting at first but after a few hours of exploration you will love it.
