### ISSUE TITLE
API for db use

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#368]
hi @rubendel! I know that you use BerkleyDB to parse ifc files. is it possible to store some new data to this local db (do you have api for it)? which part of logic can i use to save some data to db from new input added to biemvie.ws? Thanks in advance!

**Comment by rubendel** [comment]
We use BerkeleyDB JE to **store** the data yes. BDB is just a key-value store that maps keys to values in a way that the keys are always sorted. On top of this we use EMF which generates Java classes to make interacting with the database easier.

Just have a look in the code, anywhere where you see  a DatabaseSession being created, some interaction with the database is going to happen. There are many access patterns and they are not documented (and considered internal).

Example
```java
	try (DatabaseSession session = getBimServer().getDatabase().createSession()) {
		User newUser = databaseSession.create(User.class);
		newUser.setName("test");
		newUser.setUsername("test@bimserver.org");
		databaseSession.store(newUser);
		databaseSession.commit();
	}
```

In the previous example a new instance of the type "User" is created. If you want to store custom data you'll have to generate your own types.
