### ISSUE TITLE
addStringAttribute in API throws exception

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#369]
hi @rubendel 
How can I add new attribute and value to object?

addStringAttribute on commit transaction in API throws exception (LowLevelInterface)
Added attrubute: new, value: value
{
  "response": {
    "exception": {
      "__type": "UserException",
      "message": "No attribute with the name new found in class IfcWallStandardCase"
    }
  }
}

**Comment by rubendel** [comment]
The error message seems to indicate that you tried adding a attribute with the name "new". I don't know of any fields names "new", so I guess that's the problem here.

To what object (type) and which field are you trying to add a value?
