### ISSUE TITLE
how to install query engines in 1.5.47

### ISSUE THREAD

**Issue by tornado96** [opensourceBIM/BIMserver#373]
HI, I installed bimserver 1.5.47, and my question is  know how to install query engines? thanks!

**Comment by rubendel** [comment]
If you have also installed BIMvie.ws you can navigate to Server | Available Plugins and install plugins from there. You can try to install the BimQL query engine, but it is not maintained at the moment so probably does not work.

**Comment by aahoo** [comment]
If the following query is BimQL, it is working for at least the predefined queries:

```
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "properties": {
    "ThermalTransmittance": {
      "comparator": ">",
      "value": 0.2
    }
  }
}
```
@rubendel may I ask why BimQL has been abandoned? What is the alternative solution for querying in BIMserver?
