### ISSUE TITLE
Maven dependencies - /Tests

### ISSUE THREAD

**Issue by LUC-ian** [opensourceBIM/BIMserver#374]
Hi Ruben,

The Maven dependencies of the /Tests seems to be outdated: 

https://github.com/opensourceBIM/BIMserver/blob/master/Tests/pom.xml

please check the lines 43 and 48 where the version have to be "1.5.52-SNAPSHOT" instead of "1.5.50-SNAPSHOT"

Thanks,
Lucian

**Comment by rubendel** [comment]
Thanks
