### ISSUE TITLE
checkin not possible -  socket timeout

### ISSUE THREAD

**Issue by manuzy** [opensourceBIM/BIMserver#375]
I installed BIMserver 1.4 on Amazon AWS Ubuntu 14.04 / Java 8 / Tomcat 8 and it seems to work in general, but the checkin of a model is not possible. the upload never finishes and it doesn't throw an error in the frontend. 
The Logfile shows an error (see below) 
![voila_capture 2016-07-03_02-28-39_pm](https://cloud.githubusercontent.com/assets/18074255/16592309/5f52b3c6-42e0-11e6-9a43-ed6c3597e5fb.png)
(https://cloud.githubusercontent.com/assets/18074255/16592292/4d758a20-42e0-11e6-9d36-df1d307ef711.png)

Best Manuel

org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:887) at org.bimserver.utils.MultiplexingInputStream.read(MultiplexingInputStream.java:45) at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) at java.io.InputStreamReader.read(InputStreamReader.java:184) at java.io.BufferedReader.fill(BufferedReader.java:161) at java.io.BufferedReader.readLine(BufferedReader.java:324) at java.io.BufferedReader.readLine(BufferedReader.java:389) at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:181) ... 25 more 03-07-2016 14:26:48 ERROR (org.bimserver.servlets.UploadServlet.java:146) org.bimserver.shared.exceptions.ServerException: java.net.SocketTimeoutException at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:228) at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:136) at org.bimserver.servlets.RootServlet.service(RootServlet.java:112) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: org.bimserver.plugins.deserializers.DeserializeException: java.net.SocketTimeoutException at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:191) at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:133) at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:215) ... 23 more Caused by: java.net.SocketTimeoutException at org.apache.tomcat.util.net.NioBlockingSelector.read(NioBlockingSelector.java:202) at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:250) at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:231) at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:133) at org.apache.coyote.http11.InternalNioInputBuffer$SocketInputBuffer.doRead(InternalNioInputBuffer.java:177) at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:110) at org.apache.coyote.http11.AbstractInputBuffer.doRead(AbstractInputBuffer.java:414) at org.apache.coyote.Request.doRead(Request.java:476) at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:350) at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:395) at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:375) at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:190) at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:977) at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:887) at org.bimserver.utils.MultiplexingInputStream.read(MultiplexingInputStream.java:45) at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) at java.io.InputStreamReader.read(InputStreamReader.java:184) at java.io.BufferedReader.fill(BufferedReader.java:161) at java.io.BufferedReader.readLine(BufferedReader.java:324) at java.io.BufferedReader.readLine(BufferedReader.java:389) at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:181) ... 25 more 03-07-2016 14:30:01 INFO Fetching online version info (org.bimserver.version.VersionChecker.java:78)

**Comment by rubendel** [comment]
How big is this file? Can you possibly share it? How much memory have you assigned to BIMserver?

**Comment by manuzy** [comment]
I tried several demo files. eg. the demo file (see attachment) has 2,4 MB
[Duplex_A_20110505.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/356149/Duplex_A_20110505.ifc.zip)

I Have JAVA heap memory of Max	241.69 MB and 239 MB is used. is that the problem? how much is required here?

**Comment by rubendel** [comment]
You need at least 1GB assigned to BIMserver.
