### ISSUE TITLE
After "Checkin...",find an error called "IfcGeomServer.exe"

### ISSUE THREAD

**Issue by wuyandefeixue** [opensourceBIM/BIMserver#377]
![1](https://cloud.githubusercontent.com/assets/17920500/16645460/b3a1a974-4456-11e6-8939-3bb86faef84a.jpg)
![3](https://cloud.githubusercontent.com/assets/17920500/16645477/c2d76c1c-4456-11e6-9368-44e8e3a30383.jpg)

Environment:
         default
                    bimserver:              BIMserver-parent-1.5.51
                    ifcplugins:               IfcPlugins-ifcplugins-0.0.14
                    binaryserializers:    BinarySerializers-binaryserializers-0.0.14
                    bimserverapi:         BIMserver-JavaScript-API-bimserverapi-0.0.95
                    console:                 Console-console-0.0.3
            other
                    bimsurfer:              BIMsurfer-bimsurfer-0.0.22
                    bimviews:               bimvie.ws-bimviews-0.0.50
                    ifcopenshellplugin: IfcOpenShell-BIMserver-plugin-ifcopenshellplugin-0.5.15

After the preparatory work,modify pom.xml all plug-in project of "Dependencies" tab
Pointing to project in the workspace.Some other operations ensure proper project.
![5](https://cloud.githubusercontent.com/assets/17920500/16645815/30402152-4459-11e6-8b55-df56e1de1087.png)

Configuring "Arguments" -plugins in the "Java Application" and run the project.

After "Checkin.." an ifc file,there will be "ifcGeomServer.exe" errors, such as the top two graphs.

My English is not good, hope forgive me,thank you.

**Comment by wuyandefeixue** [comment]
Add that, 3d model finally able to show up, that is able to click on the eye, showing 3d model.

**Comment by rubendel** [comment]
Can you try version 0.5.9 of IfcOpenShell as suggested in this issue: https://github.com/opensourceBIM/BIMserver/issues/324

**Comment by wuyandefeixue** [comment]
Thank you,
Use version 1.5.9 of IfcOpenShell,I need to modify only a few compatibility issues of code.
Error does not occur.
I'm sorry,answer you so late.

**Comment by rubendel** [comment]
In an effort to resolve this, can you please state:
- Your operating system and it's version
- 32 or 64 bit operating system
- Amount of system memory. Amount of memory assigned to BIMserver.
- Full Java version
- Do you have any development tools installed?
