### ISSUE TITLE
Required dependency org.antlr:antlr-complete is not installed

### ISSUE THREAD

**Issue by tornado96** [opensourceBIM/BIMserver#379]
hi,when I install BimQL, it comes error like this:
Required dependency org.antlr:antlr-complete is not installed
how to fixed it ?thanks!!!

**Comment by rubendel** [comment]
Which version of BIMserver? I think this is fixed in the newest 1.5 developers release.

**Comment by Toutoun** [comment]
Hi, I downloaded BIMserver-1.5.51.jar.
I wanted to install the plugin BimQL and I have same error : 
   "Required dependency org.antlr:antlr-complete is not installed"
Yet It's present in the "LIB" directory.

Excuse me for my english !
Thanks

**Comment by rubendel** [comment]
Hi I had no problem with it this morning in 1.5.52 (installing the plugin that is, did not test BimQL itself)

**Comment by Toutoun** [comment]
Hi ! Yes I had no problem with BIMserver 1.5.52 to install BimQL. 
Thanks

**Comment by rubendel** [comment]
Great
