### ISSUE TITLE
How production ready is BIMserver?

### ISSUE THREAD

**Issue by Michal-sk** [opensourceBIM/BIMserver#380]
Hi guys, i am wondering how production ready BIMserver is. Is there anybody running it in production?

**Comment by Michal-sk** [comment]
The use case would be viewing of IFC files, from outside BIMserver. Additionally we would als like to use the properties on elements trough the webservice.

So mostly viewing and maybe writing to the IFC trough the webservice.

**Comment by dlabz** [comment]
I asked this 3 years ago, and it was 98% ready. Spent another 3 years trying, but eventually gave up. It's a great learning platform, but too academic for knee-deep use.

**Comment by Michal-sk** [comment]
Thats the feeling i'm getting from most of the OpenSource BIM Collective.  TNO and the developing parties did a nice initial job. but it feels as if the funding dried out / it did not get enough traction.

Maybe some core contributors could shed some light on this?

**Comment by aothms** [comment]
To answer your initial question, almost all products with the [OpenSource BIM Collective](http://opensourcebim.org/) are being used in production. Also, almost all of them are under very active development, e.g [[1]](https://github.com/opensourceBIM/BIMserver/graphs/contributors) [[2]](https://github.com/IfcOpenShell/IfcOpenShell/graphs/contributors), so funding drying out is not an issue and I personally see traction increasing every day.

That said, the goals of these products might not always align perfectly with every industry stakeholder. For example, the ambition to modularize the development of the BIMserver and its refactoring to remain manageable over time, might discomfort some users that are solely interested in a web-based visualization platform. That doesn't mean this is not a relevant use of the BIMserver, it is simply a matter of prioritization.

In my personal opinion, it is also a matter of being vocal in the community and recognize that while these initiatives have a relatively large reach and awareness in the industry, they are being developed by a relatively small group of developers. On the one hand this means things might move not always as quickly as desired, on the other hand this means that you can actually influence the development direction significantly. The community is very receptive to pull requests here on github.

Lastly, many of these projects are backed by institutions or individuals that you can contact for paid consultancy work.

(closing this topic as it is not really an issue, but feel free to continue the discussion)

**Comment by Michal-sk** [comment]
Good to read your reply. At this moment i am in the process on how to switch from a vendor lockin (Revit) to IFC, and i would see Bimserver playing a big part in this. We already have the product in production so we can't switch to quickly, but once the transition will begin i am planning to contribute as well.

Our main use would be a viewer and reading / writing to the elements properties. Additionally (in the future) we would like to be able to merge IFC files. Would you say bimserver is a good fit for these purposes?

**Comment by aothms** [comment]
Perfect. That sounds like a good fit. By means of subprojects the BIMserver has been one of the first to support merging IFC files.
