### ISSUE TITLE
Rerendering function

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#381]
hi @rubendel !
Could you please specify which function(method) runs in javascript onclick on eye toggle projecttree.html
(it rerenders with different coloring or hides objects)?

**Comment by rubendel** [comment]
That would be https://github.com/opensourceBIM/bimvie.ws/blob/master/projecttree.html#L357

**Comment by rubendel** [comment]
Next time please post BIMvie.ws related questions in the BIMvie.ws repository
