### ISSUE TITLE
Clash Detection 

### ISSUE THREAD

**Issue by erikbeserra** [opensourceBIM/BIMserver#382]
How do you set up the clash detection service? I have installed the plugin from available plugin bundles and have add the service to one of my projects but is says missing notification url. How does the clash detection work and how is it used in the BIM server?

**Comment by dlabz** [comment]
The Creation is a clash of imagination and reality.

**Comment by rubendel** [comment]
Please use the search function: https://github.com/opensourceBIM/BIMserver/issues/347
