### ISSUE TITLE
Initial setup hangs: Invalid JSON request:

### ISSUE THREAD

**Issue by kilmarnock** [opensourceBIM/BIMserver#384]
Hi!
After installing bimserver  1.5.51 on tomcat8 java8, I fill out the web form, click setup and the interface tells me: 

```
Setting up...
Setting up admin account...
```

and hangs there. The log says: 

```
ERROR [http-nio-80-exec-5]: Invalid JSON request:                                                        (JsonApiServlet.java:72) 
```

That is basically the whole story. I tried ie, firefox, chromium.

**Solution**
It works if you do not change the server name on the Welcome setup page and use a simple password **without numbers**. Triple-checked the without-numbers statement, did not check special characters.

**Comment by kilmarnock** [comment]
If you try to change password afterwards 
```
user-> ChangePassword
```
log says:
```
 ERROR [http-nio-80-exec-3]: Missing parameter: requestPasswordChange -> includeSiteAddress                   (JsonHandler.java:123)
```
GUI says the same.

**Comment by kilmarnock** [comment]
it welcomes you with
```
ERROR_REMOTE_METHOD_CALL
```
and it is not possible to add a user:
```
ERROR [http-nio-80-exec-5]: Invalid JSON request:                                                            (JsonApiServlet.java:72) 
```
It is the same error as before. :-(

**Comment by rubendel** [comment]
Ok there are a lot of different issues in this topic:
- Changing the password was not working due to a bug in BIMvie.ws. I fixed this and referenced this issue. Will make a new build of BIMvie.ws later today
- Both 1.5.51 and 1.4.0 do not work on Tomcat 7.
- ERROR_REMOTE_METHOD_CALL I think would usually indicate that there is no connection at all... Is it still running?
- The numbers in the password issue sounds almost unbelievable, can you reproduce this without the proxy server as well? Maybe your proxy server cannot handle numbers?

**Comment by kilmarnock** [comment]
> ERROR_REMOTE_METHOD_CALL I think would usually indicate that there is no connection at all... Is it still running?
Yes, it is. The log says:
``` 
01-08-2016 12:24:26 ERROR Invalid JSON request:                                                            (org.bimserver.servlets.JsonApiServlet.java:75) 
01-08-2016 12:24:26 ERROR Invalid JSON request:                                                            (org.bimserver.servlets.JsonApiServlet.java:75) 
01-08-2016 12:24:26 INFO  WebSocket open                                                                   (org.bimserver.servlets.websockets.jsr356.Jsr356Impl.java:63) 
01-08-2016 12:24:26 INFO  WebSocket open                                                                   (org.bimserver.servlets.websockets.jsr356.Jsr356Impl.java:63) 
```
While pressing the setup button. The GUI still says:
`ERROR_REMOTE_METHOD_CALL`
