### ISSUE TITLE
Problem getting existing project with revision ID (roid)

### ISSUE THREAD

**Issue by oGuzee** [opensourceBIM/BIMserver#385]
Hey,

we want to grab some objects from an existing proejct via low-level-api.
The problem is we get an unknown error: 
```
org.bimserver.shared.exceptions.ServerException: Unknown error: null
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:78)
	at org.bimserver.generated.LowLevelInterfaceImpl1.getDataObjectsByType(LowLevelInterfaceImpl1.java)
	at bimserverclientdemo.Main.main(Main.java:93)

```

```
List<SDataObject> dataObjectsByType = lowlevelinterface.getDataObjectsByType(newProject.getLastRevisionId(), "ifc2x3tc1", "IfcRelContainedInSpatialStructure", false);
```

AND

```
org.bimserver.shared.exceptions.UserException: No revision with roid 2 found
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:72)
	at org.bimserver.generated.LowLevelInterfaceImpl1.getDataObjectsByType(LowLevelInterfaceImpl1.java)
	at bimserverclientdemo.Main.main(Main.java:93)
```

```
List<SDataObject> dataObjectsByType = lowlevelinterface.getDataObjectsByType((long)2, "ifc2x3tc1", "IfcRelContainedInSpatialStructure", false);
```

We already have some revisions, 5 to be precise. 

Where our mistake? Is there any? Or do we have to take another way?

Thank you

**Comment by rubendel** [comment]
Hi, the "roid" are usually larger numbers. When you have a "Revision" object, use the .oid, not the .id. The .id is just an incrementing number starting at 1. The roid is the Object-ID of the Revision object, and therefore unique within the database. That is also why it can be used without providing the ProjectID (poid).

**Comment by oGuzee** [comment]
@rubendel 

how do i get the revision as an object? didn't find it.

**Comment by oGuzee** [comment]
@rubendel 

but how do i get the revision object? didnt find it

**Comment by rubendel** [comment]
So how exactly did you expect BIMserver to know which project/revision you wanted to get the objects from (by type)?

ServiceInterface.getProjectByPoid (and similar methods) will give you Project objects. A Project object has a lastRevisionId field, which is an "roid".

**Comment by oGuzee** [comment]
@rubendel did you see my edit of my post?

**Comment by rubendel** [comment]
I had not, your code is good now. I found a bug in getDataObjectsByType which I have fixed in GIT head. 

Please be advised that the getDataObject* methods will be removed in a future version of BIMserver as they are too specific (you can't for example combine different types of queries). This functionality will be replaced by a new query language.

**Comment by oGuzee** [comment]
Just for your information: I changed the bool value from false to true in .getDataObjectsByType(param.). works fine.

**Comment by rubendel** [comment]
Ah great, thanks for mentioning. I tested with false too, so in the next release that will work too.
