### ISSUE TITLE
Clash Detection on 1.5.51

### ISSUE THREAD

**Issue by erikbeserra** [opensourceBIM/BIMserver#386]
I had asked about the clash detection yesterday and got forwarded to a issue that had discussed it for 1.4. Does Clash detection work on 1.5.51? There is a plugin on github, does this plugin work for 1.5.51 or does it need to be worked on? Also what is the built in clash detection internal in bim server and does that work?

**Comment by rubendel** [comment]
It does not work on 1.5.51 (or any other 1.5 version). With working I mean that it does some actual clashdetection that is usable in an actual building project. I'll refer (again) to the project page which also states this: https://github.com/opensourceBIM/ClashDetectionService.

There is no built-in clashdetection in BIMserver.
