### ISSUE TITLE
New properties for object

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#390]
hi @rubendel !
Could you please explain hot to add to Object (lets say IfcWall) new property that normally is shown in  property.html javascript code of my ifc model.
I think this code is used to show these special properties
(not Name, Owner History or GUID): 
`object.getIsDefinedBy(function(isDefinedBy){`

				if (isDefinedBy.getType() == "IfcRelDefinesByProperties") {
					isDefinedBy.getRelatingPropertyDefinition(function(propertySet){
						if (propertySet.getType() == "IfcPropertySet") {
							containerDiv.find("table tbody tr.noprop").remove();
							othis.showPropertySet(propertySet);
						}
					});
				}
			}); 
How to get those properties of object in javascript function in bimsurfer.min.js:

`this.readObject = function(a, b) {`

in peace instead of a.getType() use some a.getProperty() function:

               if (a.gid = e, null != d.viewer.scene.findNode(e))
                    return void console.log("Node with id " + e + " already existed");
                var b = BIMSURFER.Constants.materials[a.getType()]
                  , c = !1;
                null == b && (console.log("material not found", a.getType()),
                b = BIMSURFER.Constants.materials.DEFAULT),
                b.a < 1 && (c = !0);
?

**Comment by rubendel** [comment]
Please take some time to correctly format your post, you can use the "Preview" button to see how it will look.

**Comment by VladMala** [comment]
@rubendel, yep. did it.

**Comment by VladMala** [comment]
@rubendel, there is a module PluginBase. There you have ifc2x3tc1.ecore file and generated interface Ifc2x3tc1Package and Ifc2x3tc1PackageImpl - implementation that are used for object files like IfcRootImpl methods like getGlobalId()... Is it the right direction? Is it possible to add and generate new methods for IfcRootImpl? How to find the right properties of ifc file? Are they in Lists of     EList<EStructuralFeature> getEStructuralFeatures(); in EClass?

**Comment by rubendel** [comment]
You don't need to generate new classes/fields. For the properties tab the dynamic properties of IFC are used. Have a look at http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifckernel/lexical/ifcpropertyset.htm for more info.

There is no straight-forward way to get/set those types of properties. You'll have to navigate/recreate the structure , for example (IfcProduct -> IsDefinedBy -> IfcRelDefinesByProperties -> RelatingPropertyDefinition -> IfcPropertySet -> HasProperties -> IfcPropertySingleValue).

**Comment by VladMala** [comment]
@rubendel thnx a lot! You are always really helpful! Will try navigate.

**Comment by jorgeluisacostaalonso** [comment]
@rubendel Hello! I newer on IFC, I want to learn more about! but It's a little difficulty with the lack of docs that I found. Have you some reference/ books something to share which could help me!

Thank you

**Comment by akuckartz** [comment]
@jorgeluisacostaalonso Please do not highjack issues for such questions.
