### ISSUE TITLE
How to get objects from ids

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#391]
Hi, @rubendel !
Could you please explain how in js from array of ids _rIsDefinedBy of object "IfcWall" get array of
objects IsDefinedBy?

**Comment by rubendel** [comment]
No need to use _rIsDefinedBy, you can just call getDefinedBy on the object, this will get the data from the server and create objects for you.

```
object.getDefinedBy(function(definedBy){
  console.log(definedBy);
});
```

**Comment by VladMala** [comment]
thnx @rubendel a lot!
