### ISSUE TITLE
Download IfcDoor format "Ifc2x3" then nothing shows in a 3D viewer (ex: BIMvision)

### ISSUE THREAD

**Issue by Toutoun** [opensourceBIM/BIMserver#392]
Hi,

I downloaded bimserver-1.4.0-FINAL-2015-11-04.jar, and I loaded several projects. I tried the query to retrieve only the doors. The result is always the same when I open my file with BIMvision nothing is displayed, I have just the project name in the tree. Yet when I open it with a text editor I have all informed (IfcDoor, IfcCartesianPoint ...).

I don't see why it doesn't work !
Thanks

**Comment by rubendel** [comment]
I assume you are using BimQL. There are known problems with BimQL in version 1.4. Some explanation of that: https://github.com/opensourceBIM/BIMserver/issues/129#issuecomment-87994536
