### ISSUE TITLE
Bug: ConcurrentModificationException in AbstractModelMerger.mergeScales

### ISSUE THREAD

**Issue by garview** [opensourceBIM/BIMserver#393]
Environment:
BimServer1.4-2015-11-04
Windows7  64

Project Structure:
HHS was a top project, which had 2 subprojects——architect and MEP. The architect.ifc and MEP.ifc could be found in “ifc-files”. 
I got the merged model in this way:

> DownloadByOidsDatabaseAction action = new DownloadByOidsDatabaseAction(bimServer, databaseSession, AccessMethod.INTERNAL, roids , oids,serializerOid, authorization ,null,Deep.NO);
model = action.execute();

roids: the roids set both architect.ifc and MEP.ifc
oids : the oids set of IfcObjects both architect.ifc and MEP.ifc

Run the code and then got the error msg:

> java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
	at org.bimserver.merging.AbstractModelMerger.mergeScales(AbstractModelMerger.java:42)
	at org.bimserver.merging.BasicModelMerger.merge(BasicModelMerger.java:19)

This error will be disappeared after deleting(line 44-48 in AbstractModelMerger):

> if (ideObject instanceof IfcRoot) {
						String name = ((IfcRoot) ideObject).getName();
						if (name != null && name.equalsIgnoreCase("dummy"))
							continue;
					}

Is it a good way to solve the problem by removing these lines of code?
Kind Regards.

**Comment by rubendel** [comment]
I tried to reproduce this in 1.5 with the same model (and new query language, because downloadByOids has been removed in that version). Found some other bugs, but this one did not happen. So I think you are fine changing this in 1.4 if it works for you, but for now I'll leave it in the 1.5 codebase.

The dummy code is there to allow people to tell the merger which object to ignore while merging.

**Comment by garview** [comment]
Thanks for quick and helpful reply.
Kind Regards.
