### ISSUE TITLE
RenderEngineModel renderEngineModel = renderEngine.openModel(in)

### ISSUE THREAD

**Issue by wuyandefeixue** [opensourceBIM/BIMserver#394]
Since it is too slow for the run() method in GeometryGenerator class use "RenderEngineModel renderEngineModel = renderEngine.openModel (in);" ,
I choose to use "RenderEngineModel renderEngineModel = renderEngine.openModel (new File (filePath));" ,meanwhile modified the checkin(xxx) method in ServiceImpl class ,namely， add "inputStream.close()"to the end of "IfcModelInterface model = deserializer.read(inputStream, fileName, 0, null);" .
After that, there is a more than 80 percent promotion on Generating Geometry for IFC files, however there is also bring about a question that some uploaded files throw an error in the process of  Generating Geometry,which cause the geometry cannot be generated.
I wonder that whether due to the difference of return data between "renderEngine.openModel(in)" and "renderEngine.openModel(new File (filePath))" ?

**Comment by rubendel** [comment]
Can you please use markdown code tags to improve formatting of your issue?

Which version of BIMserver?
Where does this "filePath" come from?
I am pretty sure that the improvement in speed is due to the fact that the rendering partially taking place.

**Comment by wuyandefeixue** [comment]
Sorry about  this.My English is not very good.

Since it is too slow for the ## run() method in # GeometryGenerator class use "_RenderEngineModel renderEngineModel = renderEngine.openModel (in);_" ,I choose to use "_RenderEngineModel renderEngineModel = renderEngine.openModel (new File (filePath));_" ,meanwhile modified the ## checkin(xxx) method in # ServiceImpl class ,namely， add "_inputStream.close();_"to the end of "_IfcModelInterface model = deserializer.read(inputStream, fileName, 0, null);_" .

After that, there is a more than 80 percent promotion on Generating Geometry for IFC files, however there is also bring about a question that some uploaded files throw an error in the process of  Generating Geometry,which cause the geometry cannot be generated.
I wonder that whether due to the difference of return data between "_renderEngine.openModel(in)_" and "_renderEngine.openModel(new File (filePath))_" ?

- The version of BIMserver is bimserver-1.4.0-FINAL-2015-11-04

- filePath come from "_Path file = userDirIncoming.resolve(cacheFileName);_" for the ## checkin(xxx) method in # ServiceImpl class.
(Add a construction method in # CheckinDatabaseAction class.
Change _CheckinDatabaseAction checkinDatabaseAction = new CheckinDatabaseAction(getBimServer(), null, getInternalAccessMethod(), poid, getAuthorization(), model, comment, fileName, merge);_ to _CheckinDatabaseAction checkinDatabaseAction = new CheckinDatabaseAction(getBimServer(), null, getInternalAccessMethod(), poid, getAuthorization(), model, comment, fileName, file.toUri().getPath().substring(1), merge);_)

**Comment by wuyandefeixue** [comment]
@rubendel 
Can you help me to solve this problem?

**Comment by rubendel** [comment]
Can you try to do both changes independently of each other, this way you can measure which of the 2 actually "improves the speed". Did the files throw an error before your changes? In that case, I am (again) pretty sure that your changes are causing the problems.

In BIMserver 1.5 the geometry generating will happen in parallel, so any extra processor core available will make the process faster. Might be a good idea to try it.
