### ISSUE TITLE
3D ifc file loading until 50% stop loading

### ISSUE THREAD

**Issue by Siddle111** [opensourceBIM/BIMserver#395]
Hi Everybody;
i am running tomcat7 in ubuntu system with BIMserver 1.32 FINAL 2014.08.21 and plugin BIMview -1.310-Final-2014-12.07.jar 
vmware machine conf. RAM 2GB
sometimes it shows google javascript loadin to continue 
i wish any can help me to fix this 
Thank you

![localhost_access_log 2016 08 07](https://cloud.githubusercontent.com/assets/17134344/17468159/a58d4004-5d57-11e6-8df1-187beb06b076.png)
![localhost_access_log 2016-08 07](https://cloud.githubusercontent.com/assets/17134344/17468161/a592ecf2-5d57-11e6-935c-b4b3c33b1683.png)
![logfilescreenshot](https://cloud.githubusercontent.com/assets/17134344/17468160/a590b3ba-5d57-11e6-8884-34a8e21a0c10.png)
![bimserver plugin bimvie ifc file loading](https://cloud.githubusercontent.com/assets/17134344/17468960/66c3a112-5d5f-11e6-8d14-0e762a788402.png)
![bimuploading ifc error](https://cloud.githubusercontent.com/assets/17134344/17468947/3cf1226a-5d5f-11e6-89c8-7444d5339b7c.png)

Please use ``` your code ``` to escape code and use the "Preview" button to see whether your issue is readable. Also, when relevant, please note your BIMserver version.

**Comment by rubendel** [comment]
This is a very old version of BIMserver. You could try using Google Chrome as a browser (it's the only one we test on).

**Comment by Siddle111** [comment]
Thank your very much Ruben de Laat
 now i able run bimserver in my machine

Thanks a lot for your acknowledgement and cooperation every step
