### ISSUE TITLE
plugin deployment

### ISSUE THREAD

**Issue by oGuzee** [opensourceBIM/BIMserver#396]
We don't understand how our own  ruleengine plugin ( a service plugin quite similar like the ifcvalidator ) will be deployed in the bimserver.
we downloaded the latest source code version 0.0.6 changed the names and compiled and packaged as a jar-archive.
we copied the jar in the plugins-folder and started the bimserver.  
but we don't get a entry for installing our plugin.
how we can register our plugin?

thank you

**Comment by rubendel** [comment]
Which version of BIMserver?

**Comment by lkmoe** [comment]
Hi,
I'm currently using BIMserver version 1.5.53 and am interested in this too.
Did you find/implement a way to load plugins without putting them in a maven repository or loading them from the local Eclipse yet (as indicated in #322)?

Thanks and regards!
