### ISSUE TITLE
Unable to get 3D images in BIM Server

### ISSUE THREAD

**Issue by DishaJha** [opensourceBIM/BIMserver#397]
I am working on a project wherein I need to use the 3D image of an IFC file in the BIM Server. 

My system is Mac OSX Yosemite 10.10.5 with 4GB of RAM and has both Chrome and Firefox running, with javascript and webGL enabled. Could you please suggest what else could be the possible issue of not being able to view the 3D image in the UI. Rest of the things are in place, like querying, user settings; it's just that I am unable to see the final image that is to be produced.

**Comment by rubendel** [comment]
Are there any errors in euther the BIMserver logfile, or in the browser's JavaScript console?

**Comment by DishaJha** [comment]
I believe it is not, because the same files are working fine in an Ubuntu system of the company. Also, the javascript is working fine on the browsers.

**Comment by DishaJha** [comment]
10-08-2016 10:31:20 INFO  org.bimserver.BimServer - Starting BIMserver
10-08-2016 10:31:20 INFO  org.bimserver.BimServer - Using "/Users/abhisar/DISHA BIM SERVER/home" as homedir
10-08-2016 10:31:28 INFO  org.bimserver.BimServer - Version: 1.4.0 - Wed Nov 04 00:00:00 IST 2015
10-08-2016 10:31:33 INFO  nl.tue.buildingsmart.emf.AbstractSchemaPlugin - IFC-Schema successfully loaded from IFC2X3_TC1.exp
10-08-2016 10:31:34 INFO  nl.tue.buildingsmart.emf.AbstractSchemaPlugin - IFC-Schema successfully loaded from IFC4.exp
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.ttl (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.rdf (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: location-mapping.n3 (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.rdf (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.n3 (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: etc/location-mapping.ttl (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: file:ont-policy.rdf (in ifctordf.jar)
10-08-2016 10:31:34 INFO  org.bimserver.plugins.classloaders.FileJarClassLoader - File not found: file:etc/ont-policy.rdf (in ifctordf.jar)


These are the initial logs that i got on the console, could you please guide me on what are the files it is looking for?

**Comment by rubendel** [comment]
The error would probably be in the render engine that is being used. The render engine is only used when checking-in the IFC file. So any errors in the logfile would occur on checkin. Could you try that and see whether there are any errors in the server log?
