### ISSUE TITLE
Unable to start BIMServer

### ISSUE THREAD

**Issue by javierwang** [opensourceBIM/BIMserver#398]
I tried to setup the BIMserver on my local machine (iMac) using the newest release (57 MBbimserverjar-1.5.53-bimserverstarter-1.5.53.jar). Yet I still not figure out how to resolve the following issue: 

-----
No expanding necessary
OS: Mac OS X
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx17179m
-Xss1024k
-classpath
.:lib:lib/activation-1.1.jar:lib/aether-api-1.0.2.v20150114.jar:lib/aether-connector-basic-1.0.2.v20150114.jar:lib/aether-impl-1.0.2.v20150114.jar:lib/aether-spi-1.0.2.v20150114.jar:lib/aether-transport-file-1.0.2.v20150114.jar:lib/aether-transport-http-1.0.2.v20150114.jar:lib/aether-util-1.0.2.v20150114.jar:lib/antlr-2.7.7.jar:lib/antlr-3.5.2.jar:lib/antlr-complete-3.5.2.jar:lib/antlr-runtime-3.5.2.jar:lib/aopalliance-1.0.jar:lib/aopalliance-repackaged-2.4.0-b34.jar:lib/app-1.3.200-v20130910-1609.jar:lib/asm-5.0.1.jar:lib/asm-commons-5.0.1.jar:lib/asm-tree-5.0.1.jar:lib/bimserver-1.5.53.jar:lib/bimserverclientlib-1.5.53.jar:lib/buildingsmartlibrary-1.0.11.jar:lib/c3p0-0.9.1.1.jar:lib/cdi-api-1.0.jar:lib/common-3.6.200-v20130402-1505.jar:lib/commons-cli-1.3.1.jar:lib/commons-codec-1.9.jar:lib/commons-collections-3.2.2.jar:lib/commons-fileupload-1.3.jar:lib/commons-io-2.2.jar:lib/commons-lang-2.4.jar:lib/commons-lang3-3.4.jar:lib/commons-logging-1.2.jar:lib/commons-pool2-2.4.2.jar:lib/contenttype-3.4.200-v20140207-1251.jar:lib/cors-filter-2.5.jar:lib/cxf-core-3.1.6.jar:lib/cxf-rt-bindings-soap-3.1.6.jar:lib/cxf-rt-bindings-xml-3.1.6.jar:lib/cxf-rt-databinding-jaxb-3.1.6.jar:lib/cxf-rt-frontend-jaxws-3.1.6.jar:lib/cxf-rt-frontend-simple-3.1.6.jar:lib/cxf-rt-javascript-3.1.6.jar:lib/cxf-rt-transports-http-3.1.6.jar:lib/cxf-rt-ws-addr-3.1.6.jar:lib/cxf-rt-ws-policy-3.1.6.jar:lib/cxf-rt-wsdl-3.1.6.jar:lib/gson-2.5.jar:lib/guava-19.0.jar:lib/guice-4.0-no_aop.jar:lib/gunit-3.5.2.jar:lib/hamcrest-core-1.1.jar:lib/hk2-api-2.4.0-b34.jar:lib/hk2-locator-2.4.0-b34.jar:lib/hk2-utils-2.4.0-b34.jar:lib/httpclient-4.5.1.jar:lib/httpcore-4.4.3.jar:lib/httpmime-4.5.1.jar:lib/jackson-annotations-2.6.0.jar:lib/jackson-core-2.6.4.jar:lib/jackson-databind-2.6.4.jar:lib/java-getopt-1.0.13.jar:lib/java-property-utils-1.9.1.jar:lib/javassist-3.12.1.GA.jar:lib/javassist-3.18.1-GA.jar:lib/javax-websocket-client-impl-9.3.7.v20160115.jar:lib/javax-websocket-server-impl-9.3.7.v20160115.jar:lib/javax.annotation-api-1.2.jar:lib/javax.inject-1.jar:lib/javax.inject-2.4.0-b34.jar:lib/javax.json-1.0.4.jar:lib/javax.mail-1.5.5.jar:lib/javax.servlet-api-3.1.0.jar:lib/javax.websocket-api-1.1.jar:lib/javax.ws.rs-api-2.0.jar:lib/jaxb-core-2.2.11.jar:lib/jaxb-impl-2.2.11.jar:lib/jcl-over-slf4j-1.6.2.jar:lib/jdom-2.0.2.jar:lib/je-6.4.9.jar:lib/jersey-client-2.22.2.jar:lib/jersey-common-2.22.2.jar:lib/jersey-container-servlet-2.22.2.jar:lib/jersey-container-servlet-core-2.22.2.jar:lib/jersey-guava-2.22.2.jar:lib/jersey-media-jaxb-2.22.2.jar:lib/jersey-server-2.22.2.jar:lib/jettison-1.3.7.jar:lib/jetty-annotations-9.3.7.v20160115.jar:lib/jetty-http-9.3.7.v20160115.jar:lib/jetty-io-9.3.7.v20160115.jar:lib/jetty-jndi-9.3.7.v20160115.jar:lib/jetty-plus-9.3.7.v20160115.jar:lib/jetty-security-9.3.7.v20160115.jar:lib/jetty-server-9.3.7.v20160115.jar:lib/jetty-servlet-9.3.7.v20160115.jar:lib/jetty-util-9.3.7.v20160115.jar:lib/jetty-webapp-9.3.7.v20160115.jar:lib/jetty-xml-9.3.7.v20160115.jar:lib/jobs-3.6.0-v20140424-0053.jar:lib/json-20140107.jar:lib/jsr250-api-1.0.jar:lib/jul-to-slf4j-1.7.14.jar:lib/junit-4.10.jar:lib/logback-classic-1.1.3.jar:lib/logback-core-1.1.3.jar:lib/maven-aether-provider-3.3.9.jar:lib/maven-artifact-3.3.9.jar:lib/maven-builder-support-3.3.9.jar:lib/maven-core-3.3.9.jar:lib/maven-model-3.3.9.jar:lib/maven-model-builder-3.3.9.jar:lib/maven-plugin-api-3.3.9.jar:lib/maven-repository-metadata-3.3.9.jar:lib/maven-settings-3.3.9.jar:lib/maven-settings-builder-3.3.9.jar:lib/neethi-3.0.3.jar:lib/org.apache.oltu.oauth2.authzserver-1.0.1.jar:lib/org.apache.oltu.oauth2.client-1.0.1.jar:lib/org.apache.oltu.oauth2.common-1.0.1.jar:lib/org.apache.oltu.oauth2.dynamicreg.client-1.0.1.jar:lib/org.apache.oltu.oauth2.dynamicreg.common-1.0.1.jar:lib/org.apache.oltu.oauth2.dynamicreg.server-1.0.1.jar:lib/org.apache.oltu.oauth2.resourceserver-1.0.1.jar:lib/org.eclipse.core.resources-3.8.101.v20130717-0806.jar:lib/org.eclipse.emf.codegen-2.11.0-v20150806-0404.jar:lib/org.eclipse.emf.codegen.ecore-2.11.0-v20150806-0404.jar:lib/org.eclipse.emf.common-2.11.0-v20150805-0538.jar:lib/org.eclipse.emf.ecore-2.11.1-v20150805-0538.jar:lib/org.eclipse.emf.ecore.xmi-2.11.1-v20150805-0538.jar:lib/org.eclipse.jdt.core-3.9.1.v20130905-0837.jar:lib/org.eclipse.sisu.inject-0.3.2.jar:lib/org.eclipse.sisu.plexus-0.3.2.jar:lib/osgi-3.10.0-v20140606-1445.jar:lib/osgi-resource-locator-1.0.1.jar:lib/plexus-cipher-1.4.jar:lib/plexus-classworlds-2.5.2.jar:lib/plexus-component-annotations-1.6.jar:lib/plexus-interpolation-1.21.jar:lib/plexus-sec-dispatcher-1.3.jar:lib/plexus-utils-3.0.22.jar:lib/pluginbase-1.5.53.jar:lib/preferences-3.5.200-v20140224-1527.jar:lib/protobuf-java-2.6.1.jar:lib/quartz-2.2.2.jar:lib/registry-3.5.400-v20140428-1507.jar:lib/rome-1.5.1.jar:lib/rome-utils-1.5.1.jar:lib/runtime-3.9.100-v20131218-1515.jar:lib/shared-1.5.53.jar:lib/slf4j-api-1.7.14.jar:lib/ST4-4.0.8.jar:lib/stax-api-1.0.1.jar:lib/stax2-api-3.1.4.jar:lib/stringtemplate-3.2.1.jar:lib/validation-api-1.1.0.Final.jar:lib/velocity-1.7.jar:lib/websocket-api-9.3.7.v20160115.jar:lib/websocket-client-9.3.7.v20160115.jar:lib/websocket-common-9.3.7.v20160115.jar:lib/websocket-server-9.3.7.v20160115.jar:lib/websocket-servlet-9.3.7.v20160115.jar:lib/woodstox-core-asl-4.4.1.jar:lib/wsdl4j-1.6.3.jar:lib/xml-resolver-1.2.jar:lib/xmlbeans-2.6.0.jar:lib/xmlschema-core-2.2.1.jar
org.bimserver.JarBimServer
address=localhost
port=8888
homedir=/Users/javierwang/Public/BIMServerHome
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/bimserver/JarBimServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
-----

What I did first is to use MAMP to start an Apache Server. 
Then, I launch the .jar file from the BIMServer release page. 

Am I missing a step here? Could you give me some hint how to deploy a local BIMServer on a mac? Any suggestions will be much appreciated! Thanks.

-Javier

**Comment by rubendel** [comment]
Java version 6 is two versions too old. You need Java 8 for BIMserver
