### ISSUE TITLE
What is the effect or function of the code below?

### ISSUE THREAD

**Issue by wuyandefeixue** [opensourceBIM/BIMserver#399]
**BIMServer version**：BIMserver-1.4.0-FINAL-2015-11-04
**Project**：IfcPlugins
**Class**：IfcStepDeserializer
**Method**：org.bimserver.ifc.step.deserializer.IfcStepDeserializer.readString(String)

### **_What is the effect or function of the code below?_**

`while (result.contains("\\S\\")) {`
`　　int index = result.indexOf("\\S\\");`
`　　char x = result.charAt(index + 3);`
`　　ByteBuffer b = ByteBuffer.wrap(new byte[] { (byte) (x + 128) });`
`　　CharBuffer decode = Charsets.ISO_8859_1.decode(b);`
`　　result = result.substring(0, index) + decode.get() + result.substring(index + 4);`
`}`

**Comment by aothms** [comment]
An IFC-SPF (ifc step) file can only contain western characters, ASCII `0x20 .. 0x7e` to be precise. To include different characters control sequences have to be used.

* `\S` to specify characters from the extended characters from a ISO_8859 alphabet
* `\P` to specify an alphabet,  `\PB` for ISO 8859-2, for example
* `\X2\` and `\X4\` for unicode.

You can read more here: http://www.buildingsmart-tech.org/implementation/get-started/string-encoding or better yet, obtain a copy of the standard, ISO 10303-21.

**Comment by wuyandefeixue** [comment]
but if have this string will give an error.
`\X2\3010\X0\S\X2\30114F5391CF52066790\X0\-\X2\5206533A\X0\`
use _Open IFC Tools_ is not wrong.

**Comment by aothms** [comment]
I would expect there needs to be a regular character after the `\S`. Like `h\S\ttel` would yield `hôtel` because 't' + 128 = 'ô'. In your example `\X2\` immediately follows `\S`. Some parsers are more permissive and allow some kinds of syntax errors.

**Comment by rubendel** [comment]
Looks like this is fixed in 681648613a277f830b8da13b0cd849f72faba1bd
