### ISSUE TITLE
how to add schedule code in Starter and package it correctly in BimServer-1.4.0-Final-2015-11-04?

### ISSUE THREAD

**Issue by garview** [opensourceBIM/BIMserver#400]
**_Objective:_**
BimServer1.4.0 always can not work after a week running , so I add a little bit schedule code to make sure the BimServer could restart once a week automatically. But there is some question.
**_Some try:_**
When I add some code which contains some Quartz class, and then package it via ant. As a result, ant console tell me that package operation failed and package org.quartz does not exists. Not only quartz has this problem, if you use the  slf4j  in the "starter" source folder will also encounter the same problem.
So I copy classpath configuration from BimServer(in common.build.xml) to BimServerJar (in bimserver.build.xml).
Before:
`<javac destdir="builds/BuildJar" debug="on" srcdir="../../BimServer/starter"  includeantruntime="false"/>`
After:
`<javac destdir="builds/BuildJar" debug="on" srcdir="../../BimServer/starter"  includeantruntime="false">
    <classpath>
	<path>
								<fileset refid="sharedlib" />
								<fileset refid="lib" />
								<fileset refid="buildlib" />
							</path>
						</classpath>
		</javac>`
Sorry for the shit typesetting.
After this modification, package operation seems to be ok. But when I double click the bimserver.jar, windows alert an error window about "JNI error……" and of course, bimserver.jar can not work properly.
**_question:_**
how to add my own code in org.bimserver.starter.Starter.java(code in BimServer/starter) and package it correctly in BimServer-1.4.0-Final-2015-11-04?

**Comment by rubendel** [comment]
I would go for another route here. Just use the WAR file and have your OS schedule Tomcat to restart every week. Also I would definitely have a look at the 1.5 version because for example package management has changed to maven, and I don't think there are any memory issues (which is probably why you have to restart it after a week).

**Comment by garview** [comment]
It works, thank you Ruben.
BTW, the current version of BimServer1.5 looks much more stable(BimServer1.5.53+IfcOpenShellPlugin0.5.9), and is no longer as before.
In this case, the Maven's management and the more excellent performance is very attractive. I will gradually try to use the latest BimServer.
Kind Regards.
