### ISSUE TITLE
How to render a model with the parameter (uname,password,localhost,poid) in BimServer1.5.53?

### ISSUE THREAD

**Issue by garview** [opensourceBIM/BIMserver#401]
Version: BimServer1.5.53+IfcOpenShellPlugin0.5.9+bimviews0.5.52+bimsurfer0.0.23

Since I'm not a front-end developer with a low level in js, so there is some trouble for me to extract the methods of bimview/bimsurfer by reading source code directly.
What I want is to embed the 3D model into my own web page.
The example1.html in bimsurfer was a good example if it could work properly.
Any useful doc or  code example would be appreciated.
Kind Regards.

**Comment by garview** [comment]
I found the API-1.png in bimsurfer and would try it first.
Apologize for my carelessness.

**Comment by garview** [comment]
The API-1.png in bimsurfer seems to be great. But...
I wrote an example html file and copy the ResourceLoad code script in index.html of Bimview. All the js file   download successfully.
Then I wrote the code as API-1.png suggested and just found "BimSurfer is not defined".
So let me come back to the initial question: Is there any useful doc or code example?
Kind Regards.

**Comment by rubendel** [comment]
All the docs that are available are on github, I agree it's not much. V2 is in development, when it's done (no clue when that will be) there will be documentation as well.

**Comment by garview** [comment]
Waiting for the day comes expectantly.
regards
