### ISSUE TITLE
FAIL - Application at context path /bimserverwar-1.5.53 could not be started

### ISSUE THREAD

**Issue by Siddle111** [opensourceBIM/BIMserver#402]
Tomcat 8.5.4 version can't run BIMserverwar-1.5.3.war start deploy in the in the tomcat ubuntu system.

Please help me how to fixed it

With regards.

**Comment by rubendel** [comment]
Please help me help you by providing at least the log files

**Comment by Siddle111** [comment]
I am really sorry for not to attached that now i have attached 

Thank you

**Comment by rubendel** [comment]
And what's in the BIMserver log file?
