### ISSUE TITLE
BIM server creation error

### ISSUE THREAD

**Issue by Rub3ns87** [opensourceBIM/BIMserver#403]
Dear all,

Recently I have downloaded the bimserverjar-1.5.53-bimserverstarter-1.5.53.jar file, in order to create a BIM server. However, the following error appeared:
"(...)
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=C:\Users\Rubens\Downloads\bimserverjar-1.5.53-bimserverstarter-1.5.53
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object"

I also downloaded a Java Development Kit (jdk1.8.0_101) as was suggested in this tutorial :
https://www.youtube.com/watch?v=Ryui60tky04

When I open the BIM server starter application (.jar), I defined the following settings:
JVM - "C:\Program Files\Java\jdk1.8.0_101"
Home Directory - "(...)\bimserverjar-1.5.53-bimserverstarter-1.5.53
Adress - Local Host
Port - 8082
Max Heap Size - 500m
Stack Size - 1024k

Can anyone help me setting my BIM server? By the way, can someone also tell me if it possible to add IFC properties if I set my BIM server? What I want to do is to add properties to IFC objects but the only solution that I have found to do so is by using ArchiCAD. Do you know any other way?

Thanks!

**Comment by rubendel** [comment]
Can you try "default" for the JVM. I think there is a bug when using anything other than "default".

Also use more Heap Size, 500m is not enough.

**Comment by Rub3ns87** [comment]
That solved it rubendel! Thank you very much. By the way, do you know if it possible to add information to IFC objects by using BIM server?

**Comment by rubendel** [comment]
Good, no problem. That would be a new issue, but I am pretty sure you can find this in the documentation. https://github.com/opensourceBIM/BIMserver/wiki/Low-Level-Calls
