### ISSUE TITLE
Walls are not shown in BIMserver 1.4 anymore

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#404]
Suddenly after one commit, the wall of a model are not shown in BIMviews anymore.

BIMserver 1.4.0

With F12 we see this error: "Cannot read property 'trans' of null". This seems to be an following error of requesting negative OID's from BIMserver.

Does anybody know a solution for this error?

**Comment by ilyakuznetsov** [comment]
Details:
the error occures on loading of 3D-View in bimviews, in GeometryLoader, function processGeometry(), line 170 (var enabled = object.trans.mode == 0;)
object is null.
Analyzing requests sent to BimServer I have found out that some calls to "downloadByOids" send negative oids. Maybe an overflow?
The initial JSON query response has no negative oids.

**Comment by rubendel** [comment]
I think this could be a bug that has been fixed in https://github.com/opensourceBIM/BIMsurfer/pull/122/commits/aef6abc5fe8010cdb6fe3bea749c71f99f3f00fc

It can happen on servers that have quite a lot of model-data, which causes the object id's to become larger than 2^32. JavaScript could interprete these large numbers as negative I think.

**Comment by rubendel** [comment]
Interesting to know in this case is: Did this problem manifest itself in the newly uploaded model only, or dit uploading it also cause existing models to disfunction? If the latter is the case this is a serious bug, if not, it's probably easily fixable by applying the fix in the mentioned issue.

**Comment by ilyakuznetsov** [comment]
thank you a lot! Only the newly uploaded models are affected.
and the solution in opensourceBIM/BIMsurfer@aef6abc has fixed the problem.

**Comment by rubendel** [comment]
Great, thanks for the confirming.

**Comment by ilyakuznetsov** [comment]
Unfortunately, the solution ist not enough: some geometry data are going to be lost if we read 8 Bytes as proposed in  in opensourceBIM/BIMsurfer@ aef6abc.
I have checked the output data and found out, that the higher 4 Bytes are filled with ones (0xFFFFFFFF) or zeros (0x00000000) for the old models (committed before we had Problems with higher oids). In newer models there are sometimes different values.
The higher 4 Bytes for BimServer oids  seems to be filled with zeros and for geometry ids - with ones.

Solution: to add the higher 4 Bytes as proposed only if the value differs from 0 and 0xFFFFFFFF.

(Code of the function readLong (DataInputStream.js):
readLong: function() {
     var value = this.dataView.getUint32(this.pos, true);
      var secondHalf = this.dataView.getUint32(this.pos + 4, true);
      // throw the next 4 bytes if the value is 0 or filled with 1s
	    if (secondHalf > 0 && secondHalf != 0xFFFFFFFF) {
	        value += 0x100000000 * secondHalf;
	    }
        	this.pos += 8;
		return value;
    }

**Comment by rubendel** [comment]
Not sure if this is going to be the best solution in the long term, but if it works for you that's great. Some stuff has changed in the endianness as well lately so could be something to do with that. We will test large amounts of models again before the next release to make sure this works for everyone.

**Comment by ilyakuznetsov** [comment]
great, thanks!
