### ISSUE TITLE
WebSocket error when connecting from a client computer on a LAN

### ISSUE THREAD

**Issue by SyafiqSiva** [opensourceBIM/BIMserver#408]
Hello,

We are testing BIMserver in a local area network environment with a Windows 7 computer as the "Server".
Using the downloaded bimserverjar-1.5.55 and double-clicking it, we are able to install and perfectly connect from the same "Server" using BIMvie.ws and Firefox 48.0.2.

As soon as we try to connect from another "client computer" (in the same local network) using Firefox and the "Server" URL,  BIMserver connects and displays with the Server Info screen successfully. However, as soon as I sign in with a username and password I get the "WebSocket error".

I have also attached two screen shots for you info.

Appreciate your assistance on the above matter.

Many thanks
SyafiqSiva

![bimview 1](https://cloud.githubusercontent.com/assets/22090343/18375009/8ec671ec-7684-11e6-9df3-89c3bd237698.jpg)
![bimview 2](https://cloud.githubusercontent.com/assets/22090343/18375014/9e4a1042-7684-11e6-9445-648964d6fa1f.jpg)

**Comment by rubendel** [comment]
So far I cannot reproduce this with the same version and same browser and 2 computers. Just to double check: Did you change the "Address" field to the non localhost address in the JAR Starter. And did you  change "Server Settings" | "Site Address" to that address as well?

The JavaScript console might give more info about the websocket error, for example to which host/port combination it is trying to connect.

**Comment by SyafiqSiva** [comment]
Yes, changed both the "address" field at the JAR Starter, and at the "Server Settings" | "Site Address" to the same IP address. 
Recreated the whole thing again... using the previous/older bimserver-1.4.0-FINAL-2015-11-04... same Websocket error. 

Regards 
SyafiqSiva 

----- Original Message -----

**Comment by rubendel** [comment]
So is there anything useful in the JavaScript console? Also the network information tab might give some info.

**Comment by SyafiqSiva** [comment]
Will continue the testing using the Java console etc. on Tuesday. Cheers.

**Comment by SyafiqSiva** [comment]
It was the proxy that was causing the problem. So, added the "server" IP to "client" Firefox's No Proxy for configuration.... Solved!

Many thanks Ruben.

**Comment by rubendel** [comment]
Ah, great, thanks for letting us know what it was.

**Comment by rubendel** [comment]
Updated the documentation on this: https://github.com/opensourceBIM/BIMserver/wiki/Web-socket-error
