### ISSUE TITLE
How to publish artifacts

### ISSUE THREAD

**Issue by Isshss** [opensourceBIM/BIMserver#409]
Can you tell me how to publish plugin to http://central.maven.org/maven2?

I installed gpg, generated keys and upload the key to a server hkp://pool.sks-keyservers.net.

the setting.xml is https://github.com/Isshss/DIMviews/blob/master/settings.xml
the pom.xml is https://github.com/Isshss/DIMviews/blob/master/pom.xml

 but the results of deploy to 'https://oss.sonatype.org/content/repositories/snapshots/' are:
 Rule "signature-staging" failures
[ERROR]     \* Missing Signature: '/com/github/Isshss/dimviews/0.0.2/dimviews-0.0.2-icon.png.asc' does not exist for 'dimviews-0.0.2-icon.png'.
.........

**Comment by rubendel** [comment]
This is a question about maven, I think there are better places to find a solution for this.

**Comment by Isshss** [comment]
thank you
