### ISSUE TITLE
How to update plugin

### ISSUE THREAD

**Issue by Isshss** [opensourceBIM/BIMserver#410]
Hi Ruben,

I finished uploading artifacts to http://central.maven.org/maven2 and the plugin can be installed on Bimserver.
I have a new question now: How to update plugin in Bimserver?
I used console to do a test. I can view console link in http://localhost:8080/ after installing the console plugin. If uninstall the console plugin, the link is still there, even the link is dead. The installed plugin bundles interface is upated but the main interface (http://localhost:8080/) isn't. If I re-install the console plugin, the link in the main interface will be active.

Do I need to uninstall the old plugins and then install new version?

**Comment by rubendel** [comment]
In the "Server Settings" | "Installed Plugin Bundles" view you should be able to update your plugin when a new version is available on maven. The observation that the plugin is still available after de-installing it is probably a bug, I will have a look at that.

**Comment by Isshss** [comment]
Thank you
