### ISSUE TITLE
Checkin errors

### ISSUE THREAD

**Issue by SyafiqSiva** [opensourceBIM/BIMserver#411]
Hi Ruben,
Using Version: 1.5.56.... when "checkin" of ifc file is being done (esp larger ones), errors begin to appear during the "checkin" process. Have attached a screen capture. 
In an earlier posting (#324), a workaround to downgrade the IfcOpenShell plugin from 0.5.15 to 0.5.9 was suggested. Does this workaround still holds true?

Many thanks.
SyafiqSiva

![ifcgeomserver error1](https://cloud.githubusercontent.com/assets/22090343/18738061/be9ed8dc-80ca-11e6-9c36-222b05edc8a7.jpg)

**Comment by rubendel** [comment]
The thing is I never ever get this error message on any of my machines, but I have seen it on other people's. The suggestion to use an older version came from someone else, so I'd suggest to just try it and see.

**Comment by rubendel** [comment]
In an effort to resolve this, can you please state:
- Your operating system and it's version
- 32 or 64 bit operating system
- Amount of system memory. Amount of memory assigned to BIMserver.
- Full Java version
- Do you have any development tools installed?

**Comment by SyafiqSiva** [comment]
Hi Ruben,
As requested:-
    Operating system and it's version = Win 7 pro (SP 1)
    32 or 64 bit operating system = 64bit
    Amount of system memory = 16GB
    Amount of memory assigned to BIMserver = Max Heap Size:8567m / Stack Size:1024k
    Full Java version = 8 Update 101 (build 1.8.0_101-b13) 64bit
    Do you have any development tools installed? No.

Many thanks
SyafiqSiva

**Comment by SyafiqSiva** [comment]
Hi Ruben,

Just my two cents.... the problem could be caused by the "streaming" Deserializer.

In version 1.4.0-FINAL the default is **Ifc2x3tc1 Step Deserializer**, does not generate any Ifc GeomServer errors.

In version 1.5.6 the default is **Ifc2x3tc1 (streaming)**, generates multiple Ifc GeomServer errors.

But when changed (manual selection) to **Ifc2x3tc1** sans streaming, did not generate any Ifc GeomServer errors during checkin.

Cheers
SyafiqSiva

**Comment by rubendel** [comment]
Hi SyafiqSiva, thanks for the info, I'll have a look at that.

**Comment by rubendel** [comment]
This is solved
