### ISSUE TITLE
bimserver-1.4.0-FINAL-2015-11-04 cannot open on localhost on Mac

### ISSUE THREAD

**Issue by jdimyadi** [opensourceBIM/BIMserver#412]
On El Capitan 10.11.6 when running BIMserver from the jar file, the server starts correctly, but when launching the web browser we get:

This site can’t be reached
127.0.0.1 refused to connect.

We have tried using different ports without any success.

Note: we're running Java 1.8 Update 102

**Comment by rubendel** [comment]
Are you using the correct port as well (80282 by default)?

**Comment by flaviusb** [comment]
Yes, we tried using the default port without success. We also tried setting the port to different values, to no success.

This same jar works perfectly on Arch Linux, though.

**Comment by jdimyadi** [comment]
It seems that ports are, by default, not being listened to. So, have tried $ nc -l 8081, which opens the port and the browser seems to be trying to connect to it, but eventually timed out.

**Comment by jdimyadi** [comment]
It may not be related to BIMserver. We will try to do a clean set-up of the machine on Friday and see if it solves the problem

**Comment by rubendel** [comment]
Ok let us know, at the moment I don't have access to a mac so can't test the new releases on it.

**Comment by rubendel** [comment]
If I remember correctly there has been a bug on OSX for which I added an extra checkbox in the JAR file a few years ago "Force Ipv4". On some machines (maybe all of them now) the default localhost address is a Ipv6 one, you might want to try that.
