### ISSUE TITLE
how to get data from BimServer in accordance with webGL standard

### ISSUE THREAD

**Issue by tianbl** [opensourceBIM/BIMserver#416]
which method of  BimServerClient(with java language) should I call to get data in accordance with webGL standard

**Comment by rubendel** [comment]
I'll quote wikipedia on this one

> WebGL (Web Graphics Library) is a JavaScript API for rendering interactive 3D computer graphics and 2D graphics within any compatible web browser without the use of plug-ins.

In short, it's not a data-format so I don't understand your question.

**Comment by urlpha** [comment]
yeha
!
