### ISSUE TITLE
Method download not found on org.bimserver.ServiceInterface

### ISSUE THREAD

**Issue by mansch** [opensourceBIM/BIMserver#417]
With the latest plugin versions (BIMServer JS API 0.0.101, BIMsurfer 0.0.27, BIMvie.ws 0.0.62) the error message in the title appears while trying to display the model (in BIMviews and also similar problems in my app).
Because during installation the latest plugin versions will be pulled actually the 1.5.58 installation does no longer work out of the box.

You need to change the installed plugin-versions to an older one to get it working again.

**Comment by carloslubbers** [comment]
Hi @mansch, what plugin versions did you downgrade to to get it working? I downgraded the JS API (0.0.100), BIMsurfer (0.0.26) and BIMvie.ws (0.0.62), but I'm still getting the same error.

**Comment by rubendel** [comment]
Last week I have removed the ```download``` method, but then renamed ```downloadByNewJsonQuery" to ```download```. So the arguments to call the new ```download``` call have changed. I'll make a new build for BIMserver. Builds for the other projects were already done.

**Comment by mansch** [comment]
@carloslubbers works for me:
BIMServer JS API 0.0.99
BIMsurfer 0.0.26
BIMvie.ws 0.0.62

**Comment by carloslubbers** [comment]
Thanks for the quick replies. It seems to work fine in BIMserver 1.5.60.
