### ISSUE TITLE
BIMserver Checkout

### ISSUE THREAD

**Issue by phuck7** [opensourceBIM/BIMserver#419]
Dear all,

Working on BIMserver 1.5.58, I'm in internship and I have to create a Qt application in order to exchange with BIMserver.
I managed to checkin ifc files and to ckeckout ifc files with my Qt application.

To checkout, I use : 
downloadRevisions method with a roid (RevisionOid) and a serializerOid (I use ifc2x3tc1 serializer without streaming). This method return a topidId that I use in getDownoadData method.

But in the new version of BIMserver 1.5.6, I don't find downloadRevisions method in the console.
So how should I do to checkout a revision with the console ?

Thank you in advance,

Pierre H.

**Comment by rubendel** [comment]
There is a bit more information in this issue about the removed/renamed methods: https://github.com/opensourceBIM/BIMserver/issues/418#issuecomment-254495741

Basically to recreate the same functionality you can now do
```java
ServiceInterface.download([roid], query, serializerOid, sync);
```

The query variable here should be (to just download everything)
```json
{
  includeAllFields: true
}
```

Of course other queries are possible as well, for example to get everything of a certain type:
```json
{
  type: "IfcSlab"
}
```

The query language is still under development, I'll try to write some documentation soon.

**Comment by phuck7** [comment]
I'm sorry but I get : 
```
{
  "response": {
    "exception": {
      "__type": "ServerException",
      "message": "org.bimserver.shared.exceptions.ServerException"
    }
  }
}
```

I use oid : 524326 (Ifc2x3tc1 without streaming) and the good roid.

Thanks in advance,

Pierre H.

**Comment by rubendel** [comment]
What's in the server's log?

**Comment by carloslubbers** [comment]
The query should probably be `{\"includeAllFields\": true }`, the (escaped) quotes are required.

**Comment by phuck7** [comment]
Yep that's good thank you, I managed. I had problem with the the query. Thanks carloslubbers !
