### ISSUE TITLE
3d Model not showing

### ISSUE THREAD

**Issue by elijasa** [opensourceBIM/BIMserver#425]
Hi,
i run the latest preview bimserver of the desktop version 1.5.61. My Problem is that the model isnt visualized.
I tried several ifc files, allways the same result.

this is my render engine
![image](https://cloud.githubusercontent.com/assets/23400965/20215615/b6131a94-a815-11e6-865f-c8831b8cb1f7.png)

And this is the result i am getting..... No js Errors!

![image](https://cloud.githubusercontent.com/assets/23400965/20215482/d03392ec-a814-11e6-81eb-00dc512179bb.png)

What is wrong?

**Comment by rubendel** [comment]
Can you try the other IFC engine? I think this one does not work anymore. I'll remove it from the repository.

**Comment by elijasa** [comment]
I have tried the other engine as well before, now i found out what went wrong.
I had to  reimport the ifc with the ifcopenshell render engine.

Thank you for your support Ruben!
