### ISSUE TITLE
Cannot download ifcxml\

### ISSUE THREAD

**Issue by dominicwyf** [opensourceBIM/BIMserver#426]
Hi there,

Here is a problem, I cannot download ifcxml file after i have successfully checked in ifc file. if I choose to zip&download, the file would be empty.

**Comment by rubendel** [comment]
When you wrote your issue, there should have been the following message, maybe you missed it.

Please use ``` your code ``` to escape code and use the "Preview" button to see whether your issue is readable. Also, when relevant, please note your BIMserver version.
When posting logfiles, please post the actual text, and not screenshots of the log files. Also logfiles with no error messages whatsoever are usually not very useful.

**Comment by dominicwyf** [comment]
Sorry for your inconvenience, my BIMserver version is 1.5.61.

The attchment is my log file.
[log.txt](https://github.com/opensourceBIM/BIMserver/files/590933/log.txt)

Thank you.

**Comment by rubendel** [comment]
Thanks for reporting. I have fixed the error in git master. It will be available in the next build, which will probably be made at the end of this week.

In order to get an idea of the use cases of IfcXml, can I ask what you want to use it for and why you prefer IfcXml over IfcStep?

**Comment by dominicwyf** [comment]
Thank you so much. 

The reason is because i need to put ifc file to neo4j database which is a graph database. I think if i convert ifc to ifcXml will be more easiser.

Cheers

**Comment by rubendel** [comment]
Ah oke cool, have fun with that ;)

https://github.com/opensourceBIM/IfcPlugins/commit/9901eba069dc6b0537d9c6a44be2b55d516d9479

**Comment by dominicwyf** [comment]
Hi Ruben,

I am wondering why this ifcplugins is not in the BIMserver open source, but when i was installing bimviews, i still can see ifcplugins was installing. Do I need to install the other ifcplugins after i have installed bimviews?

**Comment by rubendel** [comment]
Not entirely sure what you mean. This fix I made will be available in the next release of IfcPlugins. After it's released you will be able to click "Update" on the plugin BIMvie.ws's "Installed plugins" page.
