### ISSUE TITLE
drop the plugin jars to the "home/plugins" directory is not working

### ISSUE THREAD

**Issue by leohsu91** [opensourceBIM/BIMserver#429]
Hi, I recently used the BIMserver Project. Thanks for your great job.
Maybe becasuse of my poor network(I'm in China - -.). when I setup the BIMserver, the last page of installing plugins will stuck.
![image](https://cloud.githubusercontent.com/assets/8965956/20421336/317077c6-ad9e-11e6-97c0-8fa3ad7d1ca5.png)
 So I download the plugin jars and put them into the "home/plugins" directory. but it doesn't work.
![image](https://cloud.githubusercontent.com/assets/8965956/20421372/63a3e6d8-ad9e-11e6-88f0-0357c4b90e46.png)
The BIMserver can't identify the jars I putted.  What should I do to make it work? 
Thanks a lot!

**Comment by dominicwyf** [comment]
Hi, 我最近也在弄这个项目，如果你不介意，我们可以探讨一下。方便的话私下给我mail或者Q？
谢了谢了~

**Comment by leohsu91** [comment]
@dominicwyf  加我微信xu-liguo

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/issues/413#issuecomment-250467760
