### ISSUE TITLE
Python Boilerplate

### ISSUE THREAD

**Issue by aahoo** [opensourceBIM/BIMserver#430]
This is not an issue, rather a question.
Is there any boilerplate available to connect to BIMserver using Python?

**Comment by rubendel** [comment]
A quick search here on github resulted in these two repositories, not sure how up-to-date those are though.

https://github.com/ylcnky/BIMServer_PythonClient
https://github.com/aothms/python-bimserver-client

**Comment by aahoo** [comment]
Thanks @rubendel. I should have thought of that myself.

PS: I also want to say thanks to everyone who contributed to the Open Source BIM project. Without this, I cannot imagine how I could start my research on BIM.
