### ISSUE TITLE
BIMserver v1.5.xx upgrade process

### ISSUE THREAD

**Issue by bastienmenis** [opensourceBIM/BIMserver#432]
What is the process to update between minor releases of v1.5, in order to maintain the current database and settings?

I am using the .war package with Tomcat. I assume I need to copy the new version to a separate directory, then copy some files from the previous install directory? If so, which ones?

**Comment by rubendel** [comment]
There is none at the moment, the database-upgrade system is only in use for actual releases, it's too much of a hassle to maintain for (almost) weekly releases.

**Comment by bastienmenis** [comment]
Fair enough. And is it possible to copy or export/import the database manually?

**Comment by rubendel** [comment]
Yes you could run two BIMservers (old version and new version) and use the API to copy all sorts of data (users, projects etc...). Timestamps and oid's will of course be different.

There is a bit of code in the repository that did just that (and even fixed the timestamps manually) for the 1.3 to 1.4 migration. This code can be found here: https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/BimServerImporter.java

You can trigger it by calling https://thisisanexperimentalserver.com/apps/console/?interface=ServiceInterface&method=importData

> This code was ony written for a specific project we had to migrate, so it is by no means a complete copy, and also it might not even work, but you can use it as en example if you really cannot lose your database.

**Comment by klacol** [comment]
Ok, thanks for the clarification, That our process too.
