### ISSUE TITLE
checkinFromUrl error 

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#438]
Hi Ruben,

when I use the ```checkinFromUrl``` api, there is an error happened mostly.  And it sometimes can be successful.

the error log as follow:

ERROR [LongStreamingCheckinAction] o.b.d.a.StreamingCheckinDatabaseAction [StreamingCh
eckinDatabaseAction.java:325]                                                                                 
org.bimserver.plugins.deserializers.DeserializeException: Unexpected end of stream reading first line 
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.
java:183) ~[na:na]  

I use the Deserializer  "Ifc2x3tc1 (Streaming)" and project schema "ifc2x3tc1"  .  Then I changed the Deserializer to "Ifc2x3tc1 " ,this error seems disappear. 

Did I used the wrong Deserializer  ?

**Comment by rubendel** [comment]
Which version of BIMserver? Does it reliably never work with the streaming deserializer, and always for the regular deserializer?

**Comment by rubendel** [comment]
Since this only happened with the streaming deserializers, and not consistently, I suspect this is the same issue as https://github.com/opensourceBIM/BIMserver/issues/452 which should now be fixed.

**Comment by yanzhenxing** [comment]
thank you, I'll have a try
