### ISSUE TITLE
Query bimserver

### ISSUE THREAD

**Issue by Claudiaa07** [opensourceBIM/BIMserver#439]
I have the question about combining 2 queries :  
 
query2 = "{\"type\":\"IfcWall\",\"includeAllSubtypes\":true,\"includes\":[\"validifc:ContainedInStructure\",\"validifc:OwnerHistory\",\"validifc:Representation\",\"validifc:ObjectPlacement\"]}"

query2 = "{\"type\":\"IfcDoor\",\"includeAllSubtypes\":true,\"includes\":[\"validifc:ContainedInStructure\",\"validifc:OwnerHistory\",\"validifc:Representation\",\"validifc:ObjectPlacement\"]}"
query2 = "{\"type\":\"IfcWall\",\"includeAllSubtypes\": true,\"include\":{\"type\":\"IfcWall\",\"field\":\"HasOpenings\",\"include\":{\"type\":\"IfcRelVoidsElement\",\"field\":\"RelatedOpeningElement\"}}}"
 
Because I want to visualize the walls (like the first query) but where there are openings of the windows and doors ..
Now with the second query you can see it in the bimserver but you can't visualize it in an other program (like FZKViewer).
 
Thank you, Claudia

**Comment by rubendel** [comment]
The following query will query all walls. For every wall it will include all geometric representations. For every wall it will also include the opening(s) and its representation(s). For viewing in BIMvie.ws you can ommit the 2 blocks of 4 includes because geometry is downloaded separately.

```json
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "includes": [{
    "type": "IfcWall",
    "field": "HasOpenings",
    "include": {
      "type": "IfcRelVoidsElement",
      "field": "RelatedOpeningElement",
      "includes": [
        "validifc:ContainedInStructure",
        "validifc:OwnerHistory",
        "validifc:Representation",
        "validifc:ObjectPlacement"
      ]
    }
  }, 
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]
}
```

**Comment by aahoo** [comment]
[here](https://github.com/IndustryFoundationClasses/Questions/issues/9) I asked about the possibility of identifying external walls. @aothms gave a nice answer in which it is possible to trace the `IfcPropertySingleValue`s with `IsExternal` set to `true`.  I could do it with [IfcOpenShell](https://gist.github.com/aahoo/c97248816510bf9892a2e8bdf90d1626) but it is not the most efficient way for querying. @rubendel I wonder if this is possible with the BIMserver query method.
