### ISSUE TITLE
how to optimize the performance on mobile equipment or low-end pc

### ISSUE THREAD

**Issue by Brian-Walker** [opensourceBIM/BIMserver#440]
This may be a big question here， but we currently come across this situation that a big BIM model（300MB IFC file size minimum） needs to be showed on some low-end PC or even on Ipad air2， we did some tests and the outcomes were  frustrating,  the safari was crashed after loading about 8000 objects and it’s also pretty slow and lagging on a i5 Laptop with Nvidia GT550M display card。

It's very appreciated if anyone could us give some suggestions, should we somehow do some code optimization ，or rewrite a whole new lazy-loading system or develope a local IFC client on IOS ? 

we're starting to use 1.4-final version very recently,  so pardon my poor understanding of BIMserver, thanks

**Comment by rubendel** [comment]
You can filter the objects you are showing, you probably don't always have to show all objects

We have been thinking about a mechanism that loads/unloads objects based on the position/orientation of the camera, but even if we manage to implement it, it would not be ready within the next year.

A native implementation would probably be able to load more objects, but I would not expect performance to be more than 4 times better. That said, BIMsurfer has not been developed towards (or even tested on) mobile devices.

**Comment by Brian-Walker** [comment]
thanks
