### ISSUE TITLE
Allow to ajax download using binary serialization

### ISSUE THREAD

**Issue by DrorSegev** [opensourceBIM/BIMserver#441]
Hi,
Since our organization forbidden any kind of websokcets I am totally need to rewrite BIM Surfer module.
I can handle everything but I need to find a way to download Geometry with LittleEndian encoding (this is currently being done on all binary serializers) . The download servlet all to download via GET but do not allow to control which serializer to use...

Is it possible to add serializerOID the this servlet and create the download stream  according to it?

Thanks
Dror

**Comment by rubendel** [comment]
You always have to call the "download" method first and with the returned "topicId" you can use the download servlet. The call to "download" also requires a serializer oid, and BIMserver will remember it for you.
