### ISSUE TITLE
chmod +x /opt/tomcat8/bin/*.sh

### ISSUE THREAD

**Issue by ClarkRob** [opensourceBIM/BIMserver#443]
Hi all

I'm trying to install BIMServer to Ubuntu Server 16.04 using the instructions at https://bhushanbharat.wordpress.com/2015/10/13/install-bimserver-on-ubuntu-14-04/

All is well, until I get to the instruction `chmod` +x `/opt/tomcat8/bin/*.sh` in the INSTALL TOMCAT8 section

The "bin" directory mentioned cannot be found.  And indeed, when I check the directory structure, the directories created are /images and /lib.  There is no /bin directory and no .sh files within any of the existing directories.

As a result, I can't move forward with the installation.  

Am I missing something really obvious here?   New to using Ubuntu.  Thank you for any assistance.

**Comment by rubendel** [comment]
So what directories are in /opt? Maybe you have to rename the tomcat8 folder name to "tomcat8"?
