### ISSUE TITLE
Problem displaying geometry with specific IFC

### ISSUE THREAD

**Issue by DrorSegev** [opensourceBIM/BIMserver#445]
[moshe1.zip](https://github.com/opensourceBIM/BIMserver/files/651948/moshe1.zip)

This simple IFC (exported from revit 2017 with no errors) is loaded to BimServer with no problem 
but do not display Geometry.
Tested it in Bim Vision and looks fine.

Anything I do wrong?

Dror

**Comment by rubendel** [comment]
I can reproduce this, nu clue as to why it's not showing the model

**Comment by berlotti** [comment]
fixed in recent version

<img width="1396" alt="screenshot 2017-04-29 22 31 08" src="https://cloud.githubusercontent.com/assets/356921/25558664/97900e2e-2d2b-11e7-8641-ff435363ffaa.png">
