### ISSUE TITLE
compile error,Failure to find org.opensourcebim:parent:pom:1.5.64-SNAPSHOT

### ISSUE THREAD

**Issue by wlhm1984** [opensourceBIM/BIMserver#446]
i hava checked out this,on eclipse  has no errors. but when i use maven compile the shared project,always failed:
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opensourcebim:shared:jar:1.5.64-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.protobuf:protobuf-java:jar -> version 2.6.1 vs 3.1.0 @ org.opensourcebim:shared:[unknown-version], C:\Users\wlhm\git\BIMserver\Shared\pom.xml, line 51, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Shared 1.5.64-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.547 s
[INFO] Finished at: 2016-12-16T10:22:46+08:00
[INFO] Final Memory: 7M/184M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shared: Could not resolve dependencies for project org.opensourcebim:shared:jar:1.5.64-SNAPSHOT: Failed to collect dependencies at org.opensourcebim:pluginbase:jar:1.5.64-SNAPSHOT: Failed to read artifact descriptor for org.opensourcebim:pluginbase:jar:1.5.64-SNAPSHOT: Failure to find org.opensourcebim:parent:pom:1.5.64-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by rubendel** [comment]
What is the maven command you try to execute and on which project?

**Comment by wlhm1984** [comment]
mvn install

**Comment by rubendel** [comment]
I get the same results when I try to do mvn install on the "Shared" project. Somehow it seems to try and download snapshot builds from the online maven repository. It should just use the snapshot version in Eclipse. No clue why it's doing that.

**Comment by wlhm1984** [comment]
what can i do the following,can you give me some suggestions,thanks very much!
i just want to running it by eclipse.

**Comment by cocarry** [comment]
I find a error (maybe) . In the version of bimserverjar-1.5.63, in the folder of "Tests",  in the file "pom.xml", in the line of 40-48, the original file is "<version>1.5.63-SNAPSHOT</version>". But when debuging, it is always wrong. If you change it to "<version>1.5.63-SNAPSHOT</version>", There is no error.
