### ISSUE TITLE
Deserialize a ifc file and serialize with jsonserilizer but i get different model and it can't work...

### ISSUE THREAD

**Issue by Kestrong** [opensourceBIM/BIMserver#447]
Sorry,my english is poor,so there maybe some mistakes in my words.
The situation is I get a ifc and i don't want it to associate to user or project ,i just want to deserialize it to a ifcmodelinterface model and use the jsonserializer to serialize it ,then give the model with object to bimview to present.But I fail. For Example ,using your bimser as normal to deal with a test.ifc it return a 112 length objects to 3dview page(use chrome console.log(data)), but in my way to deal with it,i get 423 length.
**There are my codes below(part of important):** 
// connect the remote server to get file
                URL url = new URL("http://ip:port/hymakebim/upload/43dea3b8b2bf42c3b413524a34626b04_V1.ifc");
                URLConnection openConnection = url.openConnection();
                InputStream input = openConnection.getInputStream();
                
                //transfer to local dir
                Path homeDirIncoming = FileSystems.getDefault().getPath("D:/bimserver/home/incoming/");
                Path file = homeDirIncoming.resolve("43dea3b8b2bf42c3b413524a34626b04_V1.ifc");
                OutputStream outputStreamD = Files.newOutputStream(file);
                InputStream inputStreamD = new MultiplexingInputStream(input, outputStreamD);
                
                // deserialize the file from ifc to model
                Deserializer deserializer = getBimServer().getDeserializerFactory().createDeserializer(720937L);
                deserializer.init(getBimServer().getDatabase().getMetaDataManager().getPackageMetaData("ifc2x3tc1"));
                IfcModelInterface model = deserializer.read(inputStreamD, "43dea3b8b2bf42c3b413524a34626b04_V1.ifc", 0, null);
                // init the model
                model.setObjectOids();
                model.indexGuids();

//serilize the model to json format
                PluginManager pluginManager = getBimServer().getPluginManager();
                DownloadParameters downloadParameters = new DownloadParameters(getBimServer(), DownloadType.DOWNLOAD_JSON_QUERY);
                downloadParameters.setSerializerOid(3932198L);
                Serializer serializer2 = getBimServer().getSerializerFactory().create(null, "keshicong", model, pluginManager.requireRenderEngine(), downloadParameters);
                
               // SDownloadResult checkoutResult = serviceMap.getBimsie1ServiceInterface().getDownloadData(downloadId);
                //set the datasource with given serializer to write out
                SDownloadResult checkoutResult =new SCheckoutResult();
                 checkoutResult.setFile(new DataHandler(new EmfSerializerDataSource(serializer2)));
((EmfSerializerDataSource) dataSource) .writeToOutputStream(outputStream, progressReporter);

**use the output data to bimview:**

.......
this.query = function(query, callback){
		var promise = new Promise();
		var fullTypesLoading = {};
		query.queries.forEach(function(subQuery){
			if (subQuery.type != null) {
				fullTypesLoading[subQuery.type] = true;
				othis.loadedTypes[subQuery.type] = {};
				if (subQuery.includeAllSubTypes) {
					var schema = othis.bimServerApi.schemas[othis.schema];
					othis.bimServerApi.getAllSubTypes(schema, subQuery.type, function(subTypeName){
						fullTypesLoading[subTypeName] = true;
						othis.loadedTypes[subTypeName] = {};
					});
				}
			}
		});
		othis.waitForLoaded(function(){
			othis.bimServerApi.jsonSerializerFetcher.fetch(function(jsonSerializerOid){
				bimServerApi.callWithFullIndication("Bimsie1ServiceInterface", "downloadByJsonQuery", {
					roids: [othis.roid],
					jsonQuery: JSON.stringify(query),
					serializerOid: jsonSerializerOid,
					sync: true
				}, function(laid){
					var url = bimServerApi.generateRevisionDownloadUrl({
						laid: laid,
						topicId: laid,
						serializerOid: jsonSerializerOid
					});
					othis.bimServerApi.notifier.setInfo("Getting model data...", -1);
					$.getJSON(url, function(data, textStatus, jqXHR){
						**console.log("query url", url);
						console.log("query", data);**
						data.objects.forEach(function(object){
							var wrapper = othis.objects[object._i];
							if (wrapper == null) {
								wrapper = othis.createWrapper(object, object._t);
								othis.objects[object._i] = wrapper;
								if (fullTypesLoading[object._t] != null) {
									othis.loadedTypes[object._t][wrapper.oid] = wrapper;
								}
							} else {
								if (object._s == 1) {
									wrapper.object = object;
								}
							}
//							if (othis.loadedTypes[wrapper.getType()] == null) {
//								othis.loadedTypes[wrapper.getType()] = {};
//							}
//							othis.loadedTypes[wrapper.getType()][object._i] = wrapper;
							if (object._s == 1) {
								callback(wrapper);
							}
						});
//						othis.dumpByType();
						bimServerApi.call("ServiceInterface", "cleanupLongAction", {actionId: laid}, function(){
							promise.fire();
							othis.bimServerApi.notifier.setSuccess("Model data successfully downloaded...");
						});
					});
				});
			});
		});
		return promise;
	};
......
waiting for your reply,many thanks!

**Comment by rubendel** [comment]
If you reorganize your post you probably increase the chances of getting a reply, this is unreadable.

**Comment by Kestrong** [comment]
@rubendel All the problems have been solved.It is because I do not generate the geometry well,I do not store geometry so my geometryData has no id,when the geometryGenerator run it reuse some data for wrong objects.Sorry for my ugly post and thanks for your reply.
