### ISSUE TITLE
why my objects were in the wrong place ?

### ISSUE THREAD

**Issue by Kestrong** [opensourceBIM/BIMserver#448]
i deserialize a ifc into model and serialize it into json，also generate geometry but the ifcslab and ifcbeam display in the wrong place. 
![qq 20161224185526](https://cloud.githubusercontent.com/assets/24601462/21466533/8fc259c4-ca0a-11e6-9041-96251d4d2f34.png)

**Comment by rubendel** [comment]
What software do you use to display the json?
