### ISSUE TITLE
Unexpected end of stream reading first line

### ISSUE THREAD

**Issue by hujb2000** [opensourceBIM/BIMserver#452]
hi, I find this bug  exists in  the version  from 1.5.61 to 1.5.64  of BIMServer when I upload two ifc files to address almost at the same time. In the process I select the ifc deserializer is ifc2x3tc1 (streaming) and the below logs show the process：

`Logging to E:\workspace_bimserver2\BIMserver\home\logs\bimserver.log
20:23:58 INFO  [main]: Starting BIMserver                                                               (BimServer.java:213) 
20:23:58 INFO  [main]: Using "home" as homedir                                                          (BimServer.java:215) 
20:24:00 INFO  [main]: Version: 1.5.64-SNAPSHOT                                                         (BimServer.java:295) 
20:24:02 INFO  [main]: No email templates found                                                         (BimServer.java:588) 
20:24:02 INFO  [main]: Non-empty database directory found "home\database"                               (BerkeleyKeyValueStore.java:85) 
20:24:03 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:112) 
20:24:12 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1286) 
20:24:12 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1286) 
20:24:12 INFO  [main]: Skipping strict dependency checking for dependency bimsurfer                     (PluginManager.java:1286) 
20:24:51 INFO  [LongStreamingCheckinAction]: writes: 100000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:52 INFO  [LongStreamingCheckinAction]: writes: 200000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:53 INFO  [LongStreamingCheckinAction]: writes: 300000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:54 INFO  [LongStreamingCheckinAction]: writes: 400000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:54 INFO  [LongStreamingCheckinAction]: writes: 500000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:54 INFO  [LongStreamingCheckinAction]: writes: 600000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:55 INFO  [LongStreamingCheckinAction]: writes: 700000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:55 INFO  [LongStreamingCheckinAction]: writes: 800000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:56 INFO  [LongStreamingCheckinAction]: writes: 900000                                                                   (BerkeleyKeyValueStore.java:572) 
20:24:56 INFO  [LongStreamingCheckinAction]: writes: 1000000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:57 INFO  [LongStreamingCheckinAction]: writes: 1100000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:57 INFO  [LongStreamingCheckinAction]: writes: 1200000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:58 INFO  [LongStreamingCheckinAction]: writes: 1300000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:58 INFO  [LongStreamingCheckinAction]: writes: 1400000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:59 INFO  [LongStreamingCheckinAction]: writes: 1500000                                                                  (BerkeleyKeyValueStore.java:572) 
20:24:59 INFO  [LongStreamingCheckinAction]: writes: 1600000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:01 INFO  [LongStreamingCheckinAction]: writes: 1700000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:02 INFO  [LongStreamingCheckinAction]: writes: 1800000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:03 INFO  [LongStreamingCheckinAction]: writes: 1900000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:04 INFO  [LongStreamingCheckinAction]: writes: 2000000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:05 INFO  [LongStreamingCheckinAction]: writes: 2100000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:06 INFO  [LongStreamingCheckinAction]: writes: 2200000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:07 INFO  [LongStreamingCheckinAction]: writes: 2300000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:09 INFO  [LongStreamingCheckinAction]: writes: 2400000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:10 INFO  [LongStreamingCheckinAction]: writes: 2500000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:10 INFO  [LongStreamingCheckinAction]: writes: 2600000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:11 INFO  [LongStreamingCheckinAction]: writes: 2700000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:12 INFO  [LongStreamingCheckinAction]: writes: 2800000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:13 INFO  [LongStreamingCheckinAction]: writes: 2900000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:14 INFO  [LongStreamingCheckinAction]: writes: 3000000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:14 INFO  [pool-2-thread-8]: Entity not found IfcDoor 502/1310882                                             (StreamingGeometryGenerator.java:362) 
20:25:15 INFO  [LongStreamingCheckinAction]: writes: 3100000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:16 INFO  [LongStreamingCheckinAction]: writes: 3200000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:18 INFO  [LongStreamingCheckinAction]: writes: 3300000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:22 INFO  [LongStreamingCheckinAction]: writes: 3400000                                                                  (BerkeleyKeyValueStore.java:572) 
20:25:44 INFO  [pool-3-thread-2]: Entity not found IfcDoor 502/6553762                                             (StreamingGeometryGenerator.java:362) 
20:26:58 INFO  [LongStreamingCheckinAction]: Rendertime: 110436ms, Reused:     71.74 MB, Total:    131.88 MB, Final:     60.15 MB (StreamingGeometryGenerator.java:569) 
20:26:58 INFO  [LongStreamingCheckinAction]: Saveable color data:     16.60 MB                                                (StreamingGeometryGenerator.java:570) 
20:27:10 INFO  [LongStreamingCheckinAction]: Rendertime: 106745ms, Reused:     71.74 MB, Total:    131.88 MB, Final:     60.15 MB (StreamingGeometryGenerator.java:569) 
20:27:10 INFO  [LongStreamingCheckinAction]: Saveable color data:     16.60 MB                                                (StreamingGeometryGenerator.java:570) 
20:27:32 ERROR [LongStreamingCheckinAction]:                                                                                  (StreamingCheckinDatabaseAction.java:334) 
org.bimserver.plugins.deserializers.DeserializeException: Unexpected end of stream reading first line
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:183) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:164) ~[na:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:182) [classes/:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:75) [classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) [classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:685) [classes/:na]
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61) [classes/:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
20:27:32 ERROR [LongStreamingCheckinAction]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: Unexpected end of stream reading first line
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:335) ~[classes/:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:75) ~[classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) ~[classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:685) ~[classes/:na]
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61) ~[classes/:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Unexpected end of stream reading first line
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:183) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:164) ~[na:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:182) ~[classes/:na]
	... 6 common frames omitted`

**Comment by rubendel** [comment]
Thanks for reporting. The new deserializers are streaming the data directly from the incoming I/O stream to the database, but when concurrent modifications happen in the database, actions will be repeated. The repeated actions were not reading from disk the second time, which they should since the original stream has already been read at that time. I think this is fixed now, it can be a bit slow though because the whole operation is tried again.
