### ISSUE TITLE
Streaming Serializers missing

### ISSUE THREAD

**Issue by landraud** [opensourceBIM/BIMserver#454]
Hello, I tried to perform an install behind a proxy.
I tried installing plugins using installPluginBundleFromFile

            ArrayList<String> pluginList = new ArrayList();
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.ifcplugins-0.0.15.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.binaryserializers-0.0.19.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.bimserverapi-0.0.108.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.console-0.0.4.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.bimsurfer-0.0.31.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.bimviews-0.0.70.jar");
            pluginList.add("C:/tmp/jarsBIM/org.opensourcebim.ifcopenshellplugin-0.5.17.jar");
                        
            for (String each : pluginList){
            	try{
            		DataSource fds = new FileDataSource(each);
                    DataHandler handler = new DataHandler(fds);
                    client.getPluginInterface().installPluginBundleFromFile(handler);
                    System.out.println("Plugin " + each + " successfully installed !");
            	} catch (Exception e){
            		e.printStackTrace();
            	}
            }

It worked fine, but then I had to manually add serailizers/deserialiers/Render Engine with BIMvie.ws

When trying to browse a project, I obtain below error:
No plugin found for this user with classname org.bimserver.serializers.JsonStreamingSerializerPlugin
even if JsonSerializer is installed ( from org.opensourcebim.ifcplugins:0.0.15)

my concern now is that I cannot select JsonStreamingSerializerPlugin in available serializers. 

I have noticed (without proxy) that this plugin was normally installed during setup Process with installForAllUsers attribute.

Is there a way to enable this plugin and make it available in UI of BIMvie.ws?

Regards, 

Loïc

**Comment by rubendel** [comment]
I'll have a look at that later. Just wondering, if you can install BIMserver + plugins on a machine with a working internet connection, can you not just copy the home directory from that machine to the machine that only has proxy-internet?

**Comment by rubendel** [comment]
Added 2 options to installPluginBundleFromFile and installPluginBundleFromUrl in which you can tell BIMserver to install all plugins for all users/for new users
