### ISSUE TITLE
Why regenerate IFC file from DB at the phase of "generating geo" on checkin?

### ISSUE THREAD

**Issue by agdsdl** [opensourceBIM/BIMserver#456]
When checking in an IFC file to a project,
I've noticed such code: 
```
ifcSerializer.init(proxy, null, null, bimServer.getPluginManager(), packageMetaData);

ByteArrayOutputStream baos = new ByteArrayOutputStream();
IOUtils.copy(ifcSerializer.getInputStream(), baos);
```
in `StreamingGeometryGenerator.java::Runner::run`.

This will read IFC objects from DB and translate them into an IFC file.
It's such a wast of time especially when using a network DB such as Mysql.

Two questing about this:
- Why not use the IFC file I uploaded directly?
- How to reduce the time of reading from network DB?

Thanks!

**Comment by rubendel** [comment]
A few reasons:
- The checkin process is a streaming process in the next release, this means we have to write the objects to the database right away.
- The database has an efficient query algorithm which allows us to send IFC files to the IfcEngine that for example do not contain any properies/properysets and other data that is irrelivant for the IfcEngine (which will only do geometry). Also the IFC data is splitted so we can run X amount of IfcEngine processes at the same time, making full use of all CPU cores. Another advantage is that this way we get to have an indication of how far along the total process of generating geometry is.
- The process of serialization/deserialization is quite trivial, especially compared to the amount of time that is being spent generating the acual geometry (I'd say less than 1% CPU is used for serialization/deserialization)

You cannnot use a MySQL database with BIMserver, or any other networked database for that matter.

**Comment by agdsdl** [comment]
@rubendel Thank you for your detailed answer! 
May the next release be able to use networked database?

**Comment by rubendel** [comment]
Nope, https://github.com/opensourceBIM/BIMserver/issues/422
