### ISSUE TITLE
Multiple instances of BIMServer

### ISSUE THREAD

**Issue by pakizito** [opensourceBIM/BIMserver#458]
I'm trying to make a multi docker container out of the BIM server sharing the same DB. (for redundancy and scalability)
I'm trying to override some properties of the Berkeley DB in a je.properties but it seems I cannot override the Exception
EnvironmentLockedException

I'm using 1.5.64 version.

Is there a way to achieve this?

Thank you very much.

With kind regards,
Rodrigo

**Comment by rubendel** [comment]
You cannot just run multiple processes that access the same on-disk berkeley-db database. The first one will lock the database and that is exactly the error you are getting when starting the second one. How do expect to achieve scalability/redundancy with multiple BIMservers on the same machine?

**Comment by pakizito** [comment]
true.
How could I then make the DB available for all the instances?
Thank you very much for the fast reply.
With kind regards,
Rodrigo

**Comment by pakizito** [comment]
Would it be possible to use another datastore? like a distributed datastore, like inMem datastores like hazelcast, etc... is this something you considered already?
How do you propose to scale things up? (not vertically but horizontally)
My only concern is that if the server goes down, I'll have the service unavailable for quite sometime...
Let me say you have done an amazing job!! Congrats!
With kind regards,
Rodrigo

**Comment by rubendel** [comment]
Please have a look at this post: https://github.com/opensourceBIM/BIMserver/issues/422

**Comment by pakizito** [comment]
Hi Ruben,
Thank you very much for the fast reply.
I see that I'm not the only one with the same idea :).

For now it will be one instance then... 
I'll see how I could achieve redundancy...

Again, thank you very much for all the effort and good work!!

With kind regards,
Rodrigo
