### ISSUE TITLE
convertFromSObject returns PluginConfiguration instead of ObjectIDMPluginConfiguration

### ISSUE THREAD

**Issue by niwakame** [opensourceBIM/BIMserver#462]
**Where**:
https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/webservices/impl/PluginServiceImpl.java#L232 (b22c2b8c8681c14d81a53c4220e2fb477f9c1913)

**Result**: 
Project not compiling

For the time being, implicit cast to **ObjectIDMPluginConfiguration** works for me, but there may be a better way to solve this, as it introduces another include:
```java
try {
    session.executeAndCommitAction(new UpdateObjectIDMDatabaseAction(session, getInternalAccessMethod(), (ObjectIDMPluginConfiguration)getBimServer().getSConverter().convertFromSObject(objectIDM, session.get(objectIDM.getOid(), OldQuery.getDefault()), session)));
}
```

**Comment by niwakame** [comment]
1.8.0 (111)

**Comment by rubendel** [comment]
That is weird, I have never had that happen. Maybe it's a compiler issue. Which compiler do you use?

**Comment by lLenn** [comment]
I had the same error with version 1.8.0 (121) and the compiler is javac of the same version

**Comment by hlx001** [comment]
i have same qusetion. my bimserver version is 1.5.76.  my jdk version is jdk1.8.0_131. can you tell me why?
![2017-06-20_110518](https://user-images.githubusercontent.com/12635528/27314783-7406dafa-55a8-11e7-85b0-5d9bb699460a.png)
![2017-06-20_110536](https://user-images.githubusercontent.com/12635528/27314785-74d90660-55a8-11e7-9e31-30a61866d532.png)

**Comment by rubendel** [comment]
Did you clone the git repository? I don't understand why all project names are lowercase.

**Comment by hlx001** [comment]
i have clone the git repository. and then i add other module(like bimviews )。
![2017-06-20_134525](https://user-images.githubusercontent.com/12635528/27318409-c5e4d47e-55be-11e7-830e-1f292abf3e63.png)
