### ISSUE TITLE
Get Revision id of a checkin

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#467]
I'm wondering if there is any chance to get the revision id that is created for a specific checkin. When I checkin a new revision on a project, I only get a topicId to check the progress. But can I somehow get the RevisionId that was created with that specific request? Is the revision somehow linked to the topic id?

Thanks for any help on this.

**Comment by rubendel** [comment]
Of course, the Project object is updated when you checkin a new revision. You can call getProjectByPoid after checking in to get the latest version of the Project object. It's property "lastRevisionId" will refer to the ObjectID of the Revision object (also called roid).

**Comment by stestaub** [comment]
Thank you. That should work for my case. Still it may be good if the response of the upload already returns the newly created Revision object (may additionally to the topic id). The reason is, that may an other upload is done between checkin and requesting the project. Or can this be handled with the transactions? 

Currently, its not very dangerous as this case would be pretty unlikely, So I'll close this for now.

**Comment by rubendel** [comment]
There is a good reason why it doesn't return a new roid (Revision ObjectID). The process of checking in is potentially asynchronous (depending on the value of the sync parameter).

That asynchronicity is actually the reason it does return a topicId, so you have a handle to get information about the progress/results of this process.

Your point about potential checkins between your checkin and and updating the project info is an interesting one though, I'd like to think about it and keep this issue open for it.

**Comment by berlotti** [comment]
Could we write a test script to force this situation to happen?

**Comment by stestaub** [comment]
That would be a good Idea. I'll try to provide one next week. If you don't
mind I would write it in ruby.

Am 29.04.2017 22:24 schrieb "Léon van Berlo" <notifications@github.com>:

**Comment by rubendel** [comment]
Using this issue to describe my current plan to solve this, any feedback is appreciated.

Currently the order of calls would usually be:
- `ServiceInterface.initiateCheckin`, which will give you a topicId
- (Optional) `NotificationRegistryInterface.registerProgressHandler`, so we can get progress information pushed towards us via a websocket
- `ServiceInterface.checkinInitiated`, which starts the actual checkin
- (Optional, multiple times) `NotificationRegistryInterface.getProgress(topicId)`, until the progress is at 100%. This is only done when not using the websocket (basically polling).

The `NotificationRegistryInterface.getProgress(topicId)` call gives back a `SLongActionState` object, which contains progress information, but also any possible error messages. This is also the message pushed over the websocket on progress updates.

I think for checkin, a subclass should be created of `SLongActionState`, called `SLongCheckinActionState`, which also contains a bit of information on the created revision (like roid, maybe a few more fields).

Also I'd like to split the current `ServiceInterface.checkinInitiated` method call into two calls:
- `ServiceInterface.checkinInitiatedSync` (returning directly a `SLongCheckinActionState`, possibly also making `ServiceInterface.initiateCheckin` obsolete)
- `checkinInitiatedAsync` (returning the topicId, just as it is now)

This would greatly simplify checkin for developers not bothering with async, and to get back to the original issue, would directly give you the roid of the revision created.

**Comment by rubendel** [comment]
This has been implemented as described now. Async is not completely working as it should be, but that's something for later.
