### ISSUE TITLE
geometry info to excel

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#470]
hello, I'm running the last version of BIMserver (master 1.5.68-SNAPSHOT)
I'm testing the plugin Geometry info to excel.

For all IFC (different size, different ifc provider) I have tested, I have an error :
org.bimserver.client.GeometryException: Parts not supported

Each time, the process is running, but it stopped after this error.
please, see the error log :
16:57:05 INFO  [qtp783218541-219]: Renaming temp file 5f89d55c5780f52fdad00d964da91be1.__tmp to 5f89d55c5780f52fdad00d964da91be1 (NewDiskCacheOutputStream.java:59) 
16:57:05 INFO  [Thread-35]: # Objects: 426340                                                                (SharedJsonDeserializer.java:121) 
16:57:05 INFO  [qtp783218541-219]: Done caching 5f89d55c5780f52fdad00d964da91be1                                    (NewDiskCacheManager.java:150) 
16:57:05 INFO  [qtp783218541-33]: -76.7495346069336, -1.2268742322921753, -20.0                                    (BinaryGeometryMessagingStreamingSerializer3.java:192) 
16:57:05 INFO  [qtp783218541-33]: 121.11077117919922, 59.51751470565796, 26.709855556488037                        (BinaryGeometryMessagingStreamingSerializer3.java:197) 
org.bimserver.client.GeometryException: Parts not supported
	at org.bimserver.client.ClientIfcModel.processGeometryInputStream(ClientIfcModel.java:430)
	at org.bimserver.client.ClientIfcModel.loadGeometry(ClientIfcModel.java:341)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:303)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:115)

thanks by advance

**Comment by rubendel** [comment]
If this is still relevant, this has been fixed, will be in 1.5.109. No "parts" are used anymore.
