### ISSUE TITLE
Why the performace decreased exponentially?

### ISSUE THREAD

**Issue by hujb2000** [opensourceBIM/BIMserver#471]
hi, @rubendel , Recently I found the performace descreased exponentially   from  BimServer version 1.5.64 to 1.5.67,   I checkined [the same ifc file](http://pan.baidu.com/s/1gfMHtNt) and selected the same deserializer(IFC2x3tc1) , It's render time almost is 70 seconds at version 1.5.64  but it will costs 300 second at version 1.5.67, Could you tell me why?  Do you have plan for having benchmarks for performace and stability? 

>
19:55:09 INFO  [org.bimserver.ServiceInterface.addProject]: addProject endd                                                                  (ServiceImpl.java:890) 
19:55:16 INFO  [LongStreamingCheckinAction]: writes: 100000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:17 INFO  [LongStreamingCheckinAction]: 462 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:18 INFO  [LongStreamingCheckinAction]: writes: 200000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:18 INFO  [LongStreamingCheckinAction]: 480 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:19 INFO  [LongStreamingCheckinAction]: writes: 300000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:19 INFO  [LongStreamingCheckinAction]: 407 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:20 INFO  [LongStreamingCheckinAction]: writes: 400000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:21 INFO  [LongStreamingCheckinAction]: 417 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:22 INFO  [LongStreamingCheckinAction]: writes: 500000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:22 INFO  [LongStreamingCheckinAction]: 284 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:22 INFO  [LongStreamingCheckinAction]: writes: 600000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:23 INFO  [LongStreamingCheckinAction]: 273 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:23 INFO  [LongStreamingCheckinAction]: writes: 700000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:24 INFO  [LongStreamingCheckinAction]: 325 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:24 INFO  [LongStreamingCheckinAction]: writes: 800000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:24 INFO  [LongStreamingCheckinAction]: 277 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:25 INFO  [LongStreamingCheckinAction]: writes: 900000                                                                   (BerkeleyKeyValueStore.java:589) 
19:55:25 INFO  [LongStreamingCheckinAction]: 310 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:26 INFO  [LongStreamingCheckinAction]: writes: 1000000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:26 INFO  [LongStreamingCheckinAction]: 359 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:27 INFO  [LongStreamingCheckinAction]: writes: 1100000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:27 INFO  [LongStreamingCheckinAction]: 434 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:28 INFO  [LongStreamingCheckinAction]: writes: 1200000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:28 INFO  [LongStreamingCheckinAction]: 300 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:29 INFO  [LongStreamingCheckinAction]: writes: 1300000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:29 INFO  [LongStreamingCheckinAction]: 296 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:30 INFO  [LongStreamingCheckinAction]: writes: 1400000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:30 INFO  [LongStreamingCheckinAction]: 323 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:30 INFO  [LongStreamingCheckinAction]: writes: 1500000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:31 INFO  [LongStreamingCheckinAction]: 344 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:32 INFO  [LongStreamingCheckinAction]: writes: 1600000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:32 INFO  [LongStreamingCheckinAction]: 363 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:55:34 INFO  [LongStreamingCheckinAction]: writes: 1700000                                                                  (BerkeleyKeyValueStore.java:589) 
19:55:35 INFO  [LongStreamingCheckinAction]: 337 ms sync                                                                      (BerkeleyKeyValueStore.java:596) 
19:58:15 WARN  [pool-2-thread-1]: Entity not found IfcDoor 29/14025181                                             (StreamingGeometryGenerator.java:355) 
20:00:42 INFO  [LongStreamingCheckinAction]: Rendertime: 307506ms, Reused:     71.76 MB, Total:    131.89 MB, Final:     60.13 MB (StreamingGeometryGenerator.java:584)

**Comment by rubendel** [comment]
I have decided to flush to disk every 100.000 writes because it will free up a lot of memory in between. We have had more complaints about memory usage than about speed, it's a tradeoff. However I don't think this could be the sole reason for it being 4 times slower. We also changed to a newer version of IfcOpenShell, so it's hard to say which of the 2 it is.

**Comment by rubendel** [comment]
Obviously this is an open source project, so you are welcome to help out with any type of automated performance/stability testing.

**Comment by hujb2000** [comment]
Yes, we want to make a contribution happly, However, the amount of BimServer code is large and we know little about it.      Could you please provide us  a first draft of the original design and a roadmap so that we can know more about it and  evaluate our ability to do something under your leadership.

**Comment by rubendel** [comment]
There is no design and also no roadmap, so I can't help you with that. All the info that is available is on the wiki.
