### ISSUE TITLE
Please recommend a better set of parameters about JVM parameters  optimization

### ISSUE THREAD

**Issue by hujb2000** [opensourceBIM/BIMserver#472]
Hi, @rubendel ,Could  you recommend a better set of parameters about JVM parameters optimization. Now We found that memory has been increased to 100% and caused service almost no respons.

**Comment by rubendel** [comment]
Please state your version etcetera and what you are doing on this BIMserver. When memory is at 100%, most of the CPU time will be spent on garbage collection. So you might want to try and increase the amount of heap memory.

**Comment by hujb2000** [comment]
hi, @rubendel 
I find this issue exist in version from 1.5.64 to 1.5.68-SNAPSHOT when I do stress testing by checkinFromUrl interface to address ifc（deserializer is Ifc2x3Stream）,  serial operation，
I found that about 7000 IfcGeomServer were not exited resulting in 64G memory consumption

7282 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7284 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7286 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7288 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7290 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7292 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7294 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7296 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7298 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7300 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7302 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7304 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7306 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7308 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7310 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7312 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7314 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7316 ?        00:00:00 IfcGeomServer                                                                                                                                                                                
 7318 ?        00:00:00 bash                                                                                                                                                                                         
 7324 ?        00:00:00 tail

**Comment by rubendel** [comment]
What platform are you on?

**Comment by hujb2000** [comment]
Linux and CommonsPoolingRenderEnginePoolFactory

**Comment by rubendel** [comment]
Sorry, do you mean to say you changed the code to use another pooling engine?
