### ISSUE TITLE
How to permanently delete a Project

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#473]
Is there any possibility to permanently delete a Project? The problem is, that there is a unique name constraint which also applies to deleted projects. It would be nice if we could somehow permanently delete a project so the name can be used again.

**Comment by rubendel** [comment]
There have been a lot of requests for this. So far our philosophy has been that data should never be allowed to be lost. That's why deleted projects are not really deleted and can always be restored.

When restoring a project, you could violate the unique constraint on project names. Maybe it's an idea to change the project name for projects being restored to something like "Project name_restored". I'll leave this topic open for others to comment on this as well.

**Comment by stestaub** [comment]
I agree with the point that project data should never be lost. (at least in production environments) The suggestion to change the project name on restore sounds good, may even postfix with restore date-time. I think as a workaround, I will change the project name before deleting to "project name - deleted at dd.mm.yyyy hh:mm:ss" With that, the deleted project is better identifiable for restoring and the unique constraint will not be violated anymore.

**Comment by Chris-12** [comment]
Hello,
I have the same problem.
Though, how can one restore old deleted projects, so that the appear back in the BIMvie.ws 's list of projects ? I didn' find any function in the console, nor in ServiceInterface or any other.
Regards,
Chris.

**Comment by rubendel** [comment]
https://thisisanexperimentalserver.com/apps/console?interface=ServiceInterface&method=undeleteProject

**Comment by Chris-12** [comment]
Thanks a lot Rubendel,
Regards

**Comment by Chris-12** [comment]
Apart of that, is there a way to "purge" database from unused project, a especially unused old project versions ? The fact is that after long use of creating/deleting projects, and adding new versions to existing projects, database's size is really increasing.
The only solution we have seen so far is to re-install the whole the Bimserver from scratch, which is quite a heavy a solution.

**Comment by rubendel** [comment]
Not at the moment. Wouldn't be too hard to implement though. Just out of curiosity, what do you consider to be a database that is too large? What negative aspects of it do you encounter?

**Comment by Chris-12** [comment]
Well, just for development purpose, database reaches 3Go for instance.. Even-though I consider this is not a lot yet by itself It could be much more increased at production-time.
We have some clients with a lot of drawings and a pretty high level of drawings updates, which will probably lead to a large amount of stored versions. Usually clients do not like increasing size things beyond necessary values without a good reason, nor to store no more used data..
So it should be necessary to have, something like whether to fix a max amount/ number of versionnings, or to be able to purge DB by projects or globally.
what do you think ?

**Comment by rubendel** [comment]
The way the database works will not allow for removing older revisions, limiting the amount of revisions would be strange I think, also I don't think it is a good idea.

Removing complete projects for me would be the only possible option, yet at the moment not something high the priority list. But it's an open source project ;).

**Comment by Chris-12** [comment]
Yes, removing completely projects would be a good thing for us. We would appreciate you could put it on your stack. Thanks again.

**Comment by betavr** [comment]
Just ran into an issue related to this. I deleted the demo project, then tried to redownload it, but I get a "Project name must be unique" message.

**Comment by olivierfaure** [comment]
Is there an option in Bimvie.ws to rename the project ?

**Comment by stestaub** [comment]
Yes in the dropdown beside the project name

![image](https://cloud.githubusercontent.com/assets/1165753/25740343/66fe9b18-3186-11e7-9990-226ea1aeb5d1.png)

**Comment by xie-qianyue** [comment]
Hello @rubendel , out team need to implement this functionality (delete a project permanently), by [my way](https://github.com/opensourceBIM/BIMserver/issues/564), we can delete a project in a 10s GB database. But in a database whose volumn is 100s GB, it seems too slow. Can you show me the right way to do so?

**Comment by rubendel** [comment]
I cannot because we don't support this.

**Comment by kevinZhangSFI** [comment]
tt
