### ISSUE TITLE
no ifc rendering but no error

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#474]
Hello,
sometimes, when I upload ifc file, there is no rendering (3D view) even if the file is correctly checkin and there is no error.
I'm running version 1.5.63 on my server.

those model are correctly shown on version bimserver-1.4.0-FINAL-2015-11-04 or in any bim desktop viewer

I want to add a zip file of my model but github indicate that it does not support the format...

Olivier

**Comment by rubendel** [comment]
Can you try the latest version?

**Comment by oliviersaintgobain** [comment]
that's ok with last version
