### ISSUE TITLE
got stuck on loading geometries while viewing successfully checkedin ifc models 

### ISSUE THREAD

**Issue by alanfoxye** [opensourceBIM/BIMserver#475]
hi there. I'm a new user maybe got something wrong with the BIMServer. I'm now using bimserverjar-1.5.67.jar. I downloaded Schependomlaan project after setup the BIMServer.I got the treeviews all right, but saw blank 3D view. And when I use BIMsurfer demo, I can see the projects list on BIMServer, but still can not get 3D view. I tried some other ifc models checked in successfully and got the same viewing result.

Using chrome I got these:

[WARN] [xeogl.Canvas 2]: Failed to get a WebGL 2 context - defaulting to WebGL 1.
warn @ xeogl.js?bust=1487651109000:11102
xeogl.js?bust=1487651109000:11102 [WARN] [xeogl.Input 4]: Browser event not supported: orientationchange
warn @ xeogl.js?bust=1487651109000:11102
Notifier.js?bust=1487651109000:21 success Arguments[2]
Notifier.js?bust=1487651109000:25 info Arguments[2]
Notifier.js?bust=1487651109000:21 success Arguments[1]
BimSurfer.js?bust=1487651109000:234 Started loading geometries

then it got stuck on loading geometries......

**Comment by berlotti** [comment]
Looks like you don't have WebGL Support.
Try https://get.webgl.org/
