### ISSUE TITLE
Missing __type field in the query

### ISSUE THREAD

**Issue by penriister** [opensourceBIM/BIMserver#477]
Hello @rubendel,

I am still trying to get the model download working from my C# code from BIMserver 1.5x , but the BIMserver gives me missing __type field error when requesting the download. 
Like this:
{"response":{"exception":{"__type":"ConvertException","message":"Missing __type field in {\"type\":\"IfcProduct\",\"includeAllSubTypes\":true}"}}}
Login, requesting of project revision oid and serializer oid works normally. Since this error does not come when using BIMvie.ws, I think I miss some stage which should be executed before  requesting the download.    What would that be?

Regards, 
Pentti Riikonen

**Comment by rubendel** [comment]
What method are you trying to execute? Apparently the method you are calling requires a __type field, all methods that have complex objects as their arguments require you to define the type. The error message does not have anything to do with the query.

**Comment by penriister** [comment]
@rubendel, 

I have been recording requests and responses between the browser running bimviews and the BIMserver.  It seems to me, that the model shown on web browser is constructed using the Json streaming serializer, not the BinaryGeometrySerializer.   Also, I did not notice any WebSocket requests used when the model was requested.  In Json streaming serializer data the  geometry vectors like  transformation, indices, vertices, normals are coded in some way. How can i decode those?

Regards,
Pentti Riikonen

**Comment by rubendel** [comment]
The process in BIMvie.ws goes like this:
- BIMvie.ws sends a query and downloads the results as IfcJson (not a standard format, just what "JsonStreamingSerializerPlugin" writes)
- All objects that have geometry are then queried again, but the results are this time serialized in a binary format and sent via WebSocket, this only includes indices, vertices, normals etc.... At the moment this is done with "BinaryGeometryMessagingStreamingSerializerPlugin3".

So, I am pretty sure that if you are visualizing in 3D, you'll see websocket frames come along. Also pretty sure the indices, vertices, normals etc.. are not in the JSON, that would be way too slow. The transformation actually is I think, but it's also sent in binary (and that's what BIMvie.ws uses).

Hope this helps.

Again, if you tell me which method you are calling, I'll tell you what the __type should be.

**Comment by penriister** [comment]
My request is this
{"request": {"interface":"org.bimserver.ServiceInterface","method":"download","parameters":{ "downloadType":"download","streaming":false,"roids":[131075],"serializerOid":"1310758","zip":false,"showOwn":"false","sync":"false","query":{ "type": "IfcProduct", "includeAllSubTypes": true}}},"token":"5b51e3a30744d96eb14b321492a2311382a0358896f76c46e412057dec81d6f009da4e5340f4c97dc8d5e8a1cb9f5e23"}

And response is this
{"response":{"exception":{"__type":"ConvertException","message":"Missing __type field in {\"type\":\"IfcProduct\",\"includeAllSubTypes\":true}"}}}

**Comment by rubendel** [comment]
Please have a look at https://github.com/opensourceBIM/BIMserver/wiki/Downloading-models

You have to base64 encode the query. In theory, the query could be any type of serializable query language, the fact that it is JSON makes it a bit tricky to understand because BIMserver's RPC method is also JSON.

**Comment by penriister** [comment]
Yes this is supposed to be the step one of the download process, since  I am expecting to get the topicId as response. Anyway, this missing  __type field error is now solved.  It was a silly mistake, the query  needs to be in side quotes.
Original problem of getting the model  downloaded from the bimserver 1.5x still remains.

**Comment by rubendel** [comment]
What is the original problem's description?

**Comment by penriister** [comment]
I need to get model downloaded as  BinaryGeometrySerialized data in my C# project. I have managed to do this with the BIMserver 1.4, but the version 1.5 fails, since the binary file contains no data.
