### ISSUE TITLE
BIMserver download json data storaged in distributed mass storage system, how do you think?

### ISSUE THREAD

**Issue by leohsu91** [opensourceBIM/BIMserver#478]
Hi,Ruben.

I want to put the BIMserver serialize data (json data) into distributed storage system. In this case, I don't have to maintain the BerkeleyDB. When I wanna analysis internal structure of ifc models, I can deserialize the json data into BerkeleyDB....

 
Is this feasible?

**Comment by rubendel** [comment]
Not sure what there is to maintain with BDB. Yes you can deserialize the json data into BDB, you can use the JsonDeserializerPlugin plugin for that.

In my opinion the tools that come with BIMserver (for example the Java based client) are pretty useful for doing analysis on IFC models, but if you think you can do more with MongoDB (which I assume will be your "distributed" database of choice) by all means do that.
