### ISSUE TITLE
Bug report:Error on line 120446: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#480]
Hi, Ruben,

I find a bug about the  method "StringUtils.nextString"

When I checkin an ifc file, which contain the item as follow:

```
#120440=IFCPROPERTYSINGLEVALUE('ProductCode',$,IFCLABEL('LDR-500-500-400-400-450-1-50/50-*'),$);
```

when the LongStreamingCheckinAction run, the exception happens in the location of class IfcStepStreamingDeserializer, line 345,
```
int nextIndex = StringUtils.nextString(realData, lastIndex);
```

I test this code, when the realData equals to "'ProductCode',$,IFCLABEL('LDR-500-500-400-400-450-1-50/50-*'),$" and the lastIndex equals to 16. The expected result should be 62, but it return 64.

**Comment by yanzhenxing** [comment]
Another case, I checkin a file and convert successfully. When I use bimviews to location the 3d views, the query json request receives the result "No ExtendedDataSchema found where name = VIS_3D_JSON_1_0" and no model data to be downed.

**Comment by berlotti** [comment]
please provide the original IFC file
