### ISSUE TITLE
getIsDefinedBy() in PropertyObject.java:72 is not working

### ISSUE THREAD

**Issue by scholtenhuisleon** [opensourceBIM/BIMserver#483]
I try to run the following loop in my class to export objects to an excel spreadsheet 

`
public static void exportWallAreaPerPhase() throws ServerException, UserException, BiffException, IOException,
			RowsExceededException, WriteException, BimServerClientException, PublicInterfaceNotFoundException {
		// implement a timer
		Long startTime = new Long(System.currentTimeMillis());

		QueryMain m = new QueryMain();
		ClientIfcModel model = m.getModel(projectName);

		List<IfcBuildingStorey> objects = model.getAllWithSubTypes(IfcBuildingStorey.class);

		// get the first storey object
		IfcBuildingStorey storey = objects.get(0);

		System.out.println();
		System.out.println();
		System.out.println(storey.getName());

		// create the map to hold the length per phase
		HashMap<String, Double> lengthPerPhase = new HashMap<String, Double>();

		// get the first storey element
		List<IfcRelContainedInSpatialStructure> contained = storey.getContainsElements();
		for (IfcRelContainedInSpatialStructure c : contained) {
			for (IfcObject el : c.getRelatedElements()) {
				// select only walls
				if (el instanceof IfcWallStandardCase || el instanceof IfcWall) {
					PropertyObject qo = new PropertyObject(el);
					qo.printProperties(); // prints wall properties to console
					String phase = qo.getQuantity("Phase Created");
					String lengthStr = qo.getQuantity("Length");
					System.out.println(lengthStr);

					// no property set, ignore wall
					if (phase != null && lengthStr != null) {
						Double length = Double.parseDouble(lengthStr);
						// already a wall with this phase: add length to value
						if (lengthPerPhase.containsKey(phase)) {
							Double aggregatedLength = lengthPerPhase.get(phase);
							aggregatedLength = aggregatedLength + length;
							lengthPerPhase.put(phase, aggregatedLength);
						}
						// create new HashMap entry
						else {
							lengthPerPhase.put(phase, length);
						}
					}
				}
			}
		}

		// write HashMap to Excel
		Iterator<String> keyIt = lengthPerPhase.keySet().iterator();

		// start at row 2 to spare heading
		int row = 2;
		while (keyIt.hasNext()) {
			String phase = keyIt.next();
			Label labelCell = new Label(1, row, phase);
			sheet.getSheet().addCell(labelCell);

			Number number = new Number(2, row, lengthPerPhase.get(phase).doubleValue());
			sheet.getSheet().addCell(number);
			row++;
		}

		Long time = (System.currentTimeMillis() - startTime) / 1000;
		System.out.println("query took " + time.toString() + " seconds!");
	}
`

In debugging mode, the function 

`PropertyObject qo = new PropertyObject(el);`

first enters getPropertiesContainer()  and then getIsDefinedBy(). This ends up in a 'suppressed unchecked warning' returning null. 

Using either IfcObject or IfcProduct in the code does not seem to make much of a difference

May there be a bug in the versions that I use (1.5.64 server, 1.5.67 client)?

**Comment by rubendel** [comment]
Compile warnings have nothing to do with runtime return values. getPropertiesContainer I guess is part of the PropertyObject class, which you didn't include, so I can't see what it is doing.

**Comment by scholtenhuisleon** [comment]
This is the PropertyObject class. 
[PropertyObject.txt](https://github.com/opensourceBIM/BIMserver/files/810477/PropertyObject.txt)

When going to getPropertiesContainer its creates a list:

`List<IfcRelDefines> defs = object.getIsDefinedBy();`

Then, IfcObjectImpl.class supresses an unchecked warning. 

To me it seems that get.IsDefinedBy(); does not to work. 

Does this help to understand the problem?
