### ISSUE TITLE
BIMServer Collada export not working

### ISSUE THREAD

**Issue by pakizito** [opensourceBIM/BIMserver#487]
When I install the Collada plugin (0.0.8) to export to gltf (for example), I get 0 bytes from the bimserver.
I see no errors in the log and all the option of: org.bimserver.collada.* give 0 bytes as a result.
example: org.bimserver.collada.JSONOpenGLTransmissionFormatBinaryOpen3DGCSerializerPlugin
I tried this with BimVie.ws and directly via java json client.
Any idea of what could this be?

Thank you very much for the help.

**Comment by rubendel** [comment]
Please have a look at the front page of the Collada plugin: https://github.com/opensourceBIM/Collada
Also please post any issues there.
