### ISSUE TITLE
model not displayed correctly if checked in with the ifc2x3 deserializer (1.5.69)

### ISSUE THREAD

**Issue by raindog** [opensourceBIM/BIMserver#489]
Hi! [This](https://github.com/opensourceBIM/BIMserver/files/864269/redhouseoveryonder.ifc.zip) model, when checked-in with the ifc2x3tc1 deserializer, is not displayed correctly. 
![schermata 2017-03-23 alle 11 05 20](https://cloud.githubusercontent.com/assets/20765/24242679/c954b04e-0fb8-11e7-8f15-ec9cacb4502d.png)

With the streaming version of the deserializer everything seems ok.
![schermata 2017-03-23 alle 11 04 53](https://cloud.githubusercontent.com/assets/20765/24242703/dbe0057e-0fb8-11e7-8f88-e636ba42e2ef.png)

I'm using the 1.5.69 BIMserver version with the latest default plugins.
If you need any further information, let me know.

**Comment by raindog** [comment]
Hi! [This](https://github.com/opensourceBIM/BIMserver/files/864269/redhouseoveryonder.ifc.zip) model, when checked-in with the ifc2x3tc1 deserializer, is not displayed correctly. 
![schermata 2017-03-23 alle 11 05 20](https://cloud.githubusercontent.com/assets/20765/24242679/c954b04e-0fb8-11e7-8f15-ec9cacb4502d.png)

With the streaming version of the deserializer everything seems ok.
![schermata 2017-03-23 alle 11 04 53](https://cloud.githubusercontent.com/assets/20765/24242703/dbe0057e-0fb8-11e7-8f88-e636ba42e2ef.png)

I'm using the 1.5.69 BIMserver version with the latest default plugins.
If you need any further information, let me know.

**Comment by rubendel** [comment]
Hi, I have "fixed" this by limiting the amount of threads to 1 for the non-streaming geometry generator (https://github.com/opensourceBIM/BIMserver/commit/0dc5ed0245261228b720f98054c6701c6553689f).

I you do not want to wait for a new release, you can effectively achieve the same by setting the "Max Render Engine Processes" in "Server Settings" to "1".

The streaming deserializer is a lot faster and uses less memory, any reason why you want to use this?

**Comment by raindog** [comment]
Hi Ruben,
I also use the the streaming deserializer, it's great. I just stumbled upon this issue and reported it.
There is absolutely no urgency of action for the whole thing.
Thank you.

**Comment by rubendel** [comment]
Alright, then the fix should be enough. That way we can keep the old deserializer for comparing the results with the streaming version.
