### ISSUE TITLE
http://localhost:8086/bimvie.ws-master/plugin.Version, not found,please help...

### ISSUE THREAD

**Issue by JK-Xia** [opensourceBIM/BIMserver#490]
Hello,rubendel
Recently i was try to run this program, i tried many bimviews version, but some bugs i can not login to the main board site, we have no idea what is this problem come from. please give us some advices.

many thanks!

JackX
ShenZhen China

**Comment by rubendel** [comment]
Are you running a BIMserver?

**Comment by JK-Xia** [comment]
yes,the bugs at the index.html, i can not click the login button, here it's the bugs report `myRequest.open("GET", Global.baseDir + "plugin.version", true);
myRequest.send(); `   404 not found!

**Comment by JK-Xia** [comment]
`http://localhost:8086/bimviews/plugin.version Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8086/bimviews/x.getbimserveraddress Failed to load resource: the server responded with a status of 404 (Not Found)
VM98:10 Uncaught TypeError: Cannot read property 'call' of null
    at new Login (eval at globalEval (jquery-2.1.3.min.js?_v=1489392844909:2), <anonymous>:10:21)
    at HTMLDivElement.<anonymous> ((index):195)
    at Function.each (jquery-2.1.3.min.js?_v=1489392844909:2)
    at n.fn.init.each (jquery-2.1.3.min.js?_v=1489392844909:2)
    at Object.<anonymous> (jquery-2.1.3.min.js?_v=1489392844909:4)
    at j (jquery-2.1.3.min.js?_v=1489392844909:2)
    at Object.fireWith (jquery-2.1.3.min.js?_v=1489392844909:2)
    at x (jquery-2.1.3.min.js?_v=1489392844909:4)
    at XMLHttpRequest.<anonymous> (jquery-2.1.3.min.js?_v=1489392844909:4)`

**Comment by rubendel** [comment]
What version of BIMserver, BIMvie.ws etc... are you using? Are you running BIMvie.ws as a plugin to BIMserver?

**Comment by JK-Xia** [comment]
BIMserver : 1.5.68-SNAPSHOT,BIMvie.ws :2015-11-04,bimsurfer:4.0.0 ,this is all i using now.

**Comment by rubendel** [comment]
There is no bimsurfer 4.0.0, why are you using such an old version of BIMvie.ws? Usualyl only the last versions of all projects work together.

**Comment by JK-Xia** [comment]
i just download the new version, i am trying to run , but still hard to working good. i am trying...

**Comment by JK-Xia** [comment]
Hello ,rebendel
Good day,  i tried the last version, but a lot problem its coming from the index.html ,
such like : 
index.html-224 BIMserverClient undefind,
settings.js-56 Failed to load resource: the server responded with a status of 404 (Not Found), this is important !!

**Comment by rubendel** [comment]
Did you install the BimServerJavaScriptApi?

**Comment by JK-Xia** [comment]
I am sorry , we did not install this , are we have to install this?

**Comment by JK-Xia** [comment]
Hi,Rubendel,
Could you please tell me what is the step put on the eclipse and running ? which projects i have work together,sorry for my english.
Best regards!
Jack

**Comment by rubendel** [comment]
I have updated the documentation a bit, hope that helps: https://github.com/opensourceBIM/BIMserver/wiki/Eclipse

**Comment by JK-Xia** [comment]
can not download competently,stop at 23% ,do not wat happen , 3 pc are the same .

**Comment by JK-Xia** [comment]
Hello,Rebendel 
Good news its we can run the projects as fine, but when we checking the big size ifc file , projects was very slowly , we have to waiting for 5 mints more,the file size 60Mb,and also we have a lot bugs in the js files.
do you have some advice for us ? 
thanks
Regards
Jack

**Comment by rubendel** [comment]
The process is slow, we always try to improve the speed, but it is what it is, there are not secret switches to make it faster. "A lot of bugs" isn't really going to help resolve the issues.

**Comment by JK-Xia** [comment]
Ok,thanks, will keep work on this projects,will help others on this projects.

**Comment by fangge889** [comment]
@rubendel 
Hi,rubendel,thanks for you team's work.
I run for jetty have a exception，as follows：
javax.servlet.ServletException: No bimserver context attribute
	at org.bimserver.servlets.RootServlet.init(RootServlet.java:61)

**Comment by rubendel** [comment]
Are you running the WAR in jetty?

**Comment by fangge889** [comment]
running “BimServer“  in jetty

**Comment by fangge889** [comment]
running “BimServer“ in jetty will be 
"Problem accessing /BimServerWar/x.getbimserveraddress. Reason:
    NOT_FOUND"

**Comment by JK-Xia** [comment]
Good day,rubendel
We have changed some code for the surfer clickSelect.js, we want change the color when we click the model and change color depends the data.state of database, we found a part or code  such like:  this.highlighted.insert('node', BIMSURFER.Constants.highlightSelectedObject); 
please give some advice for the ctrol color!

**Comment by JK-Xia** [comment]
thannks
