### ISSUE TITLE
How to get  IFC data stored into database like Mysql

### ISSUE THREAD

**Issue by Carraway93** [opensourceBIM/BIMserver#492]
Hi, Rubendel
I want to get data stored in database like Mysql, I have read the wiki about database versioning ,and it mentioned the Berkeley DB, but I want to use Mysql ,is there a possibility to use Mysql instead of Berkeley DB? And how to get this work done?
Thank you very much!

**Comment by rubendel** [comment]
No, not possible. We tried this 8 years ago. The object-model of IFC is not mappable to the relational model of MySQL (or any other relational database) in a usable way. Some of the problems are classified as the [Object-relational_impedance_mismatch](https://en.wikipedia.org/wiki/Object-relational_impedance_mismatch).
