### ISSUE TITLE
How to use other serializer like JsonStreamingSerializer when download the visiable model data

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#493]
Hi, Rubendel

How to use other serializer like JsonStreamingSerializer when download the visiable model data.
I try this by modify the serializerId in the download request, but it failed. And the npe occured
```
java.lang.NullPointerException: null  
at org.bimserver.servlets.Streamer$1.run(Streamer.java:104)
```

I debug it and found that when LongStreamingDownloadAction initialized ,the messagingStreamingSerializer is not initialized. So I wonder the purpose of it. 
May I have some idea of that?

Thank you very much!

**Comment by webdada** [comment]
If you try the process manually via BIMServer user interface (Bimvie.ws) - does the download work ? Is the downloaded Json file valid ?
