### ISSUE TITLE
Unable to download Binary glTF for Schependomlaan

### ISSUE THREAD

**Issue by ronanmcnulty** [opensourceBIM/BIMserver#497]
vcmp.eu poid: 3211265
org.bimserver.emf.IfcModelInterfaceException: Oid already stored: 950 org.bimserver.models.geometry.impl.Vector3fImpl@5698ffaa (old: org.bimserver.models.geometry.impl.Vector3fImpl@2939382a

**Comment by rubendel** [comment]
This has been fixed in https://github.com/opensourceBIM/BIMserver/commit/2f570c6b3a7927e1ae95e94f0fa13921e6eed8a3
