### ISSUE TITLE
BIM Query does not produce valid IFC files. For example IFCWalls 

### ISSUE THREAD

**Issue by webdada** [opensourceBIM/BIMserver#498]
I am using the latest BIMServer release but the issue has been consistent for all the BIMServer releases I tested back to BIMServer 1.4. In general, the BIM Query model, either by way of Javascript, Java or the new JSON format, has not worked well with standard IFC file.

The issue is that the BIM query will produce a new IFC file for download, but the new IFC files are not valid IFC files. 

How to reproduce:

1. Upload the standard  AC11-Institute-Var-2-IFC.ifc file to a project.
2. Select Query -> All Walls, select IFC2x3 streaming, zip file. 
3. Open the new IFC file in DDS viewer, solibri or Revit etc, they will report error or show nothing. 

DDS viewer will produce the follow error logs.

I am including both the original AC11-Institute-Var-2-IFC.ifc file, and the new exported All_Walls.ifc file. 

The file C:\Users\sam.wu\Downloads\All_Wall.ifc contains the following errors:

Missing Non-optional member: 
OwnerHistory
#1=IFCWALLSTANDARDCASE('2UZhzWc8v0fA0sfv__WgLn',$,'Wand-002',$,$,$,$,'DAC6A5FB-0527-4DD0-83-E9-B940B02D4AFA');
Missing Non-optional member: 
OwnerHistory
#2=IFCWALLSTANDARDCASE('0gf4zLSNHARQiAvK3qkBDz',$,'Wand-006',$,$,$,$,'B9FC1F23-9F08-498E-A4-F6-819633958617');
Missing Non-optional member: 
OwnerHistory
#3=IFCWALLSTANDARDCASE('1LnXM52pj1uP_ZpDnRRCRj',$,'Wand-007',$,$,$,$,'42A20C80-3D11-43F9-95-94-AF51474C574A');
Missing Non-optional member: 
OwnerHistory
#4=IFCWALLSTANDARDCASE('1aejkGBNz2FuRzjxv1SLrw',$,'Wand-001',$,$,$,$,'A7AB5DFD-18E6-44FA-8B-EB-F90ACA0426DE');
Missing Non-optional member: 
OwnerHistory
#5=IFCWALLSTANDARDCASE('2oOoWKmmfChQTLCBzuB3$b',$,'Wand-010',$,$,$,$,'A406D554-C7E0-472C-AF-97-1AB36D628BA7');
Missing Non-optional member: 
OwnerHistory
#6=IFCWALLSTANDARDCASE('3wT8Lkj1j8dRPSJbjoKEaq',$,'Wand-015',$,$,$,$,'43F3F8BA-D989-4AAB-B7-71-3A25BADD0A7C');
Missing Non-optional member: 
OwnerHistory
#7=IFCWALLSTANDARDCASE('11b8rH4vrDfP5iUZizUh0h',$,'Wand-014',$,$,$,$,'18D3B880-EECA-4EA4-8D-61-F2A61CFBD984');
Missing Non-optional member: 
OwnerHistory
#8=IFCWALLSTANDARDCASE('2pXh2vfXHEb9m$yGEotBP_',$,'Wand-016',$,$,$,$,'4FE8167C-87F5-4591-93-7B-B239F869FD38');
Missing Non-optional member: 
OwnerHistory
#9=IFCWALLSTANDARDCASE('3QvvbxsHP1IRaR5M7CZy9i',$,'Wand-018',$,$,$,$,'98BB193E-B0E9-4EFB-94-34-D6265121D4D6');
Missing Non-optional member: 
OwnerHistory
#10=IFCWALLSTANDARDCASE('2JXm8iNNv7LfVrBi4zO_Vd',$,'Wand-019',$,$,$,$,'35C73C96-4BA7-4334-A6-A1-102EFD27E980');
Missing Non-optional member: 
OwnerHistory
#11=IFCWALLSTANDARDCASE('2J8eOGmDvFBugacRXH1u$T',$,'Wand-021',$,$,$,$,'EBB14F4C-AF8F-4127-AF-68-6F6DBEBB3DEE');
Missing Non-optional member: 
OwnerHistory

**Comment by webdada** [comment]
Github is having issue with zip file upload.

You can find the AC11-Institute-Var-2-IFC.ifc file here:
https://github.com/opensourceBIM/TestFiles/tree/master/TestData/data

**Comment by coryasilva** [comment]
http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifcwallstandardcase.htm

The second parameter in IfcWallStandardCase is not optional (instead required) and its name is `OwnerHistory`.

**Comment by berlotti** [comment]
Hi,

BIMserver is an IFC database. 
You can checkin and checkout files, but the main goal of the database is to hold the data. 
You can query data, filter, validate, etc.
Operations that you perform on your data do indeed not necessarily produce a valid IFC file when you download them as a file. 

Remember BIMserver is not a fileserver, nor is its goal to produce IFC files.

**Comment by webdada** [comment]
I think one of use case of a BIM server is to produce selected part of BIM model (MVD, individual floors, all Walls, type of systems) as valid IFC file.

Please note the downloaded file does have IFCZIP extension - I think it is a reasonable expectation that the ifc file to be a valid IFC. It will be like a COBIe exporter not producing valid COBIe file.

Something that I am certainly interested in contributing but this is a surprise for me that this is by design.

Regards,

Sam




Sent from myMail for iOS


Monday, March 27, 2017, 12:24 PM -0400 from Léon van Berlo  <notifications@github.com>:

**Comment by webdada** [comment]
Thanks Cory - yes the downloaded IFC file is not valid IFC file



Sent from myMail for iOS


Monday, March 27, 2017, 11:33 AM -0400 from Cory Silva  <notifications@github.com>:

**Comment by rubendel** [comment]
The query engine can be used for all sorts of output formats, for that reason it does not by default generate valid IFC files (the same data would for example be valid in an excel file). The problem with the previous query language was that the user did not have enough control over what would be outputted, with this new query language you can (and you also have to).

We have however spent considerable time writing query libraries specifically for generating valid IFC files.

For example a query that will include the linked (and indeed required) OwnerHistory objects:
```json
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "includes": [
    "validifc:OwnerHistory"
  ]
}
```

Another example that will also include the required IfcProject object (and all objects that are on the contains/decomposed path to it):

```json
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]
}
```

Also please note the prefix of the includes: "validifc". These examples are actually in BIMvie.ws, so I am a bit surprised you didn't at least try them out.

**Comment by webdada** [comment]
Thank you Leon for the clarification.

I did try the 'AllWalls', 'All WallsIncludingWindowsAndDoors', queries with
Valid IFC flags, and the results are still invalid IFC files.



Sam

Email: dada.sam@gmail.com

Text:   (703) 794-5716

**Comment by webdada** [comment]
I am including the sample AC11-Institute-Var-2-IFC.ifc file, and the result
invalid IFC file All_Walls_IFC.ifc file.

I understand the BIM Query engine is designed to produce all kinds of
exports (including excel etc), I am just trying to find a way to get valid
IFC export files.

Really appreciate your assistance and great work, Leon.


Regards,

Sam


The file C:\Users\Sam\Downloads\All_Walls_Valid.ifczip contains the
following errors:

The reference to entity #46 is invalid. No such entity in file.
The reference to entity #47 is invalid. No such entity in file.
The reference to entity #48 is invalid. No such entity in file.
The reference to entity #49 is invalid. No such entity in file.
The reference to entity #50 is invalid. No such entity in file.
The reference to entity #51 is invalid. No such entity in file.
...


Sam

Email: dada.sam@gmail.com

Text:   (703) 794-5716

**Comment by webdada** [comment]
[IFCQuery_Test.zip](https://github.com/opensourceBIM/BIMserver/files/875389/IFCQuery_Test.zip)

**Comment by webdada** [comment]
![capture](https://cloud.githubusercontent.com/assets/1613643/24402350/1e90329c-1386-11e7-80e2-680c908436c1.PNG)

**Comment by webdada** [comment]
Okay - making some progress. 

1. Need to use Query Set first, view/check 3D view, and then download.

2.   The following IFC includes should be included in the BIM Query, in a proper way (example below).

 "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]


Example:
{
  "types": [
    "IfcWall",
    "IfcSlab"
  ],
  "includeAllSubtypes": true,
   "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]
}

3. Question: How do I get separate floors via BIM Query? Lets say I want to only have 2nd floor as a separate IFC file.

Thanks !

Sam

**Comment by webdada** [comment]
![capture1](https://cloud.githubusercontent.com/assets/1613643/24402907/944af254-1388-11e7-9fd5-2d9434545f84.PNG)
