### ISSUE TITLE
Information loss after ifc parsed

### ISSUE THREAD

**Issue by hujb2000** [opensourceBIM/BIMserver#499]
hi, @rubendel ：
      I can see four tables use BIM vision 2.14 to show [the ifc model](http://debug.nos-eastchina1.126.net/test.ifc) , but I only see two table use bimviews( All BIMServer version from 1.5.64 to 1.5.69 will lost some element, select IFC2*3tc1 stream as serializer/deserializer)。
     I can't find a way to solve the problem.  Can you help me to fix it ? Thanks.

**Comment by rubendel** [comment]
The linked file is invalid, there are references to non-existing entities. No need to address issues btw.

**Comment by hujb2000** [comment]
hi, @rubendel :

Maybe it's a network problem that causes you to think that this file is not valid, and now I'm uploading it down to github.
[test.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/883935/test.ifc.zip)

Can you keep an eye on this issue?

**Comment by rubendel** [comment]
It's the same file, it has a header and footer, so pretty sure it's not a network problem. The file is still invalid, can't open it in any of the viewers I have.

**Comment by hujb2000** [comment]
@rubendel , [The ifc viewer](http://www.areddo.com/download/Areddo.zip) is ok.  You can try it

**Comment by rubendel** [comment]
No thanks

**Comment by berlotti** [comment]
4 desks in recent version of BIM Surfer

<img width="941" alt="screenshot 2017-04-24 20 04 12" src="https://cloud.githubusercontent.com/assets/356921/25351559/3af6340a-2929-11e7-9cd4-7ac1389d4d8b.png">
