### ISSUE TITLE
"Unexpected end of stream reading first line" while checkin

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#502]
Most of the times, when I try to checkin a model I get the following error:

```
{"__type"=>"SLongActionState", "end"=>1491487806911, "errors"=>["Unexpected end of stream reading first line"], "infos"=>[], "oid"=>-1, "progress"=>0, "rid"=>0, "stage"=>8, "start"=>1491487746722, "state"=>"AS_ERROR", "title"=>"Unexpected end of stream reading first line", "warnings"=>[]}
```
The checkin is done via checkInFromUrl, then I register a progressHandler on that topic. I can see that the geometry generation completes successfully, after that, this exception is thrown (which I also receive via the progress reports)

Some times it works, sometimes I get this error, with the same models....

Any Ideas what the problem could be?

Thanks in advance

**Comment by rubendel** [comment]
Which version of BIMserver are you using?

**Comment by stestaub** [comment]
I'm currently running 1.5.53

**Comment by rubendel** [comment]
Then I am pretty sure it's fixed already: https://github.com/opensourceBIM/BIMserver/issues/452

**Comment by stestaub** [comment]
I can confirm this is fixed in the latest version. Thank you!
