### ISSUE TITLE
Missing object parts.

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#506]
Hi Ruben,
I have an IFC file in which some objects are not displayed completely.
Please look at the attached picture.
I've reduced the attached ifc file to the wrong objects.
Can you please check this?
Thanks.

Regards,
Jo
[Chairs.zip](https://github.com/opensourceBIM/BIMserver/files/935481/Chairs.zip)
![bugchairs](https://cloud.githubusercontent.com/assets/16973608/25187547/9fc3db80-2523-11e7-84aa-cd6869dbb3c6.png)

**Comment by webdada** [comment]
I have also noticed missing IFC object parts, or IFC objects before. Not just this version.

**Comment by rubendel** [comment]
Looks real familiar with https://github.com/opensourceBIM/BIMserver/issues/495. Just started a new build for bimsurfer V1 (0.0.37), pretty sure that will fix this issue.

**Comment by Jo64** [comment]
Well, that's what I thought, too, but it isn't.
In #465 it was an object geometry with parts (geometryType == 3).
The type of the single chair is an IfcFurnishingElement and it is evaluated as geometryType == 1.
So the fixes from #465 don't solve the problem.

**Comment by Jo64** [comment]
Well, that's what I thought, too, but it isn't.
In #495 it was an object geometry with parts (geometryType == 3).
The type of the single chair is an IfcFurnishingElement and it is evaluated as geometryType == 1.
So the fixes from #495 don't solve the problem.

**Comment by rubendel** [comment]
Had another look at this, apparently IfcClosedShells were not included when generating geometry, and those were used for the upper parts of the furniture.

https://github.com/opensourceBIM/BIMserver/commit/215f78e369b9852461a9c79cb260c607ad2be04a

**Comment by Jo64** [comment]
Ruben - Thank you for the changes
![chairs](https://cloud.githubusercontent.com/assets/16973608/25627521/1d24cdca-2f63-11e7-8249-8a0a8c1a7baf.png)
 in BIMserver 1.5.73. This solves the geometry problems.
