### ISSUE TITLE
Upgrade BIMServer to a recent version

### ISSUE THREAD

**Issue by marfusco** [opensourceBIM/BIMserver#507]
Hello,
currently I've installed BIMServer v. 1.5.67 on Windows Server x64 with Tomcat 9; I'd like to upgrade it to version 1.5.69 without losing data and settings.
I searched for "how-to" documentation but I haven't found anything on this issue, could you please help me?
Thanks for the support
Best regards
Marco

**Comment by rubendel** [comment]
Have a look at this issue: https://github.com/opensourceBIM/BIMserver/issues/432#issuecomment-262282660

**Comment by marfusco** [comment]
Thank you for your reply, I'll have a look at this
