### ISSUE TITLE
Mismatched anonymous define() error in bimviews

### ISSUE THREAD

**Issue by FabriceL** [opensourceBIM/BIMserver#508]
Hello,

Running BimServer v. 1.5.72 from jar, I call http://localhost:8082/apps/bimviews/ and the browser (Google Chrome) show "Loading BIMviews" forever. In javascript console I got the following error : 

bimsurfer.min.js?_v=0.0.38:8 Uncaught Error: Mismatched anonymous define() module: function (){return ha}
http://requirejs.org/docs/errors.html#mismatch
    at B (bimsurfer.min.js?_v=0.0.38:8)
    at r (bimsurfer.min.js?_v=0.0.38:8)
    at Object.e [as require] (bimsurfer.min.js?_v=0.0.38:8)
    at requirejs (bimsurfer.min.js?_v=0.0.38:8)
    at Function.h.config (bimsurfer.min.js?_v=0.0.38:8)
    at Object.<anonymous> (bimsurfer.min.js?_v=0.0.38:9)
    at Object.publish (bimsurfer.min.js?_v=0.0.38:9)
    at Object.setConfigs (bimsurfer.min.js?_v=0.0.38:9)
    at Object.SceneJS.configure.SceneJS.setConfigs.SceneJS.setDebugConfigs (bimsurfer.min.js?_v=0.0.38:9)
    at (index):197

Any idea ?

**Comment by Jo64** [comment]
Same behaviour/error message with tomcat.
Ruben please give us a quick workaround.
Thanks
Jo

**Comment by miolfo** [comment]
I have also run in to the same issue with both 1.5.69 and 1.5.72; the bimwie.ws gets stuck in the loading position. I also have an installation of 1.5.69 that I did a few weeks back; it has an older version of bimvie.ws (version 0.0.78), and bimsurfer(0.0.36). In the installations I did today, the plugins are version 0.0.80 and 0.0.38 and bimvie.ws hangs to "Loading bimvie.ws.." indefinitely.

**Comment by Lexile** [comment]
Same problem here, with Tomcat & war and jar. Fix needed urgently!

**Comment by rubendel** [comment]
Problem seems to be in the new version of BIMsurfer, just downgrading to a previous version seems to work fine. No need to try and rush me, usually has the opposite effect.

**Comment by FabriceL** [comment]
OK, do we have to downgrade whole BIMServer or juste BIMSurfer plugin ? And to which version (I have installed BIMServer v 1.5.68 and the error still occured

**Comment by miolfo** [comment]
@FabriceL , I fixed the issue by installing the older version if BimSurfer plugin manually (the .jar file in home/plugins folder) during the installation of the server. When selecting installed plugins, you can manually add a .jar plugin for installation. I un-checked the BimVie.ws plugin and manually uploaded org.opensourcebim.bimsurfer-0.0.36.jar and org.opensourcebim.bimviews-0.0.78.jar. I'm using BIMserver version 1.5.69 and it is now functioning as it should.

**Comment by FabriceL** [comment]
@miolfo , Thanks, using your instructions, I get a login screen :-) 
But after I press the logging button I get a "WebSocket error" and the browser console show a 404  error for the url http://_bim_server_ip_/stream 

Not sure that it is related to the previous problem. Did you succesfully connect on your installation ? (I have also installed BIMServer V.1.5.69)

**Comment by miolfo** [comment]
@FabriceL, yeah, everything is working correctly for me. I have no idea about the cause of the web socket error unfortunately.

**Comment by FabriceL** [comment]
@miolfo OK, so it's not related to the previous problem.

**Comment by miolfo** [comment]
@FabriceL Sorry, I missed your post earlier! While testing out this issue I used both tomcat and the .jar version, and installing the plugins separately fixed the issue in both scenarios.

**Comment by FabriceL** [comment]
@miolfo Thanks for the information. I manage to make BIMSurfer working with the jar version by creating my own Project with the BIMServer API. I suspect the WebSocket Error to be the result of uncompatible versions of plugins (only 66.85% sure about that ;-) ).
