### ISSUE TITLE
Can not check in IFC files....

### ISSUE THREAD

**Issue by a244096658** [opensourceBIM/BIMserver#511]
Hi,
I installed BIMServer 1.5.62, but there were only two plugins(IFCOpenShell and BIMVie.ws) required. However, it says setup successfully.  

But when I try to check in a IFC file, there is an error... What is the reason and how to deal with it? 

![image](https://cloud.githubusercontent.com/assets/20459763/25443897/ef3a60ce-2ab1-11e7-967f-d9398184aef1.png)

And in the console, the error information is:

19:23:02 ERROR [LongStreamingCheckinAction]:                                                                                  (StreamingCheckinDatabaseAction.java:334) 
**java.lang.NoSuchMethodError: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I**
	at org.bimserver.ifc.step.deserializer.StepParser.<init>(StepParser.java:33) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcHeaderParser.parseDescription(IfcHeaderParser.java:44) ~[na:na]
...................

**Comment by rubendel** [comment]
Use a later version, preferrably the latest

**Comment by a244096658** [comment]
Hi,
Thanks for your response! I update the bimserver to the latest version and this error is resolved and IFC model can be checked in now.

But, the 3d model as well as the tree structure can not be showed in BIMvie.ws, the error information are below:

12:37:35 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongStreamingDownloadAction.java:153) 
java.lang.NullPointerException: null
......................
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
......................	
12:37:35 ERROR [org.bimserver.ServiceInterface.download]:       


The bimvie.ws constantly stuck in this status:
![image](https://cloud.githubusercontent.com/assets/20459763/25525954/1e7c4ffa-2c1a-11e7-875c-b8675f86a7cb.png)

What reason would cause this issue? Thanks!

**Comment by rubendel** [comment]
That's another error message, described in https://github.com/opensourceBIM/BIMserver/issues/512
