### ISSUE TITLE
3D rendering, ERROR [org.bimserver.ServiceInterface.download]

### ISSUE THREAD

**Issue by laloutrejoyeuse** [opensourceBIM/BIMserver#512]
On OSX, with a fresh new installed BIMServer (1.5.72) / bimvie.ws (0.0.80) and every Ifc* plugins installed (IfcOpenShell 0.5.22), i'm really unable to render (3D) any IFC file. The checkin cause no error, but when trying to render it, the following error is systematically coming

```
21:30:41 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongAction.java:189) 
java.lang.NullPointerException: null
```

Any idea ? Latest java 8 installed.
Thanks a lot,
Frederic.

**Comment by a244096658** [comment]
I have the same error with yours in issue #511 .  This happened both in my mac and windows10. 
Thanks.

**Comment by rubendel** [comment]
I think this is fixed in https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.73

**Comment by laloutrejoyeuse** [comment]
Yes, works like a charm ! Thanks a lot !
