### ISSUE TITLE
Need the admin account when run in eclipse

### ISSUE THREAD

**Issue by FlyingBamboo** [opensourceBIM/BIMserver#516]
Thanks for the wonderful codes and all the guides.
I have run a BIMserver with some plugins in eclipse successfully.
But I can't use any web API since I can only access anonymously. See below:

![2](https://cloud.githubusercontent.com/assets/3294867/25554660/28a39fe2-2d05-11e7-9f0d-beedfa5a7c92.jpg)
![1](https://cloud.githubusercontent.com/assets/3294867/25554658/222743ee-2d05-11e7-9975-03c65445654b.jpg)

I guess that there's a default admin account for it. Right?

**Comment by berlotti** [comment]
You cannot create an account when you are not logged in.
During setup you are asked to create an account.
When you run it in eclipse, default administrator and password are
admin@bimserver.org
admin

**Comment by FlyingBamboo** [comment]
That's it!
Thanks a lot!
