### ISSUE TITLE
How to deploy bimserver on

### ISSUE THREAD

**Issue by Carraway93** [opensourceBIM/BIMserver#518]
Please use ``` your code ``` to escape code and use the "Preview" button to see whether your issue is readable. Also, when relevant, please note your BIMserver version.
When posting logfiles, please post the actual text, and not screenshots of the log files. Also logfiles with no error messages whatsoever are usually not very useful.

**Comment by Carraway93** [comment]
Hi, I'm trying to deploy bimsever on Tomcat, but I don't know how to get this done. I'm a green hand and I don't have some base knowledge. So, can you help me out? I hope that you can give me some detailed instructions as I may not understand very professional things.
Thank you very much!
Best wishes!

**Comment by rubendel** [comment]
Sorry a little base knowledge is assumed in the documentation.

**Comment by Cpanmac** [comment]
Hi,I'm trying to run LocalDevBimServerStarter on my eclipse,but I found no “**genclasses**” Directory in the "PluginBase".So,can you help me out? what is “**genclasses**”？Why didn't I have this folder in my downloaded code？@rubendel
Thank you very much!
Best wishes!

**Comment by rubendel** [comment]
@Cpanmac  Can you please open a new issue for this because it has nothing to do with deploying on tomcat.
