### ISSUE TITLE
Server Error chekin ifc file of 600Mo

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMserver#519]
Hi Ruben,
We have a 600Mo ifc file IFC2X3.
Trying to checkin with IFC2X3 streaming or without streaming we finally got this server error after 30min of geometry generation :
15:31:04 ERROR [pool-2-thread-3]: Forcefully terminated IfcOpenShell process (IfcGeomServerClient.java:485) 
15:31:04 ERROR [pool-2-thread-1]: Forcefully terminated IfcOpenShell process(IfcGeomServerClient.java:485) 

(...ifc file and detailed server log on demand)

At this point it seems that memory resources may prevent process to complete, but it is not this sure.
Java is taken up to 7Go, and 95% is used, and swap file is at about 40% which is a lot.
Do you think it could be a low resource issue, and if so how much is required for such a file ?

BimServer : bimserverwar-1.5.69
Operating system and it's version = Linux Suse 42.2 - 64bit (but same issue on Win10 64bit)
Amount of system memory = 8GB
Amount of memory assigned to BIMserver = Min Heap Size: -Xms4096m, Max : -Xmx8192m
Full Java version = jdk1.8.0_111 (build 1.8.0_111-b14) 64-Bit

Best regard,
Chris.

**Comment by rubendel** [comment]
Yes you need more memory. I can't tell you how much because it depends on the file content (not file size).

**Comment by Chris-12** [comment]
Well yes, the machine has 8Go, we have tried different distributions between java and what is left for the system : from 1Go on JVM, then 4Go, and then up to all on the JVM, but without success.
So as you suggested, we are going increase memory and perform tests against what is needed.
Best Regards,
Chris.

**Comment by Chris-12** [comment]
Hi,
so, we managed to checkin the ifc file of 600Mo.
We had to do it on a 32Go machine, and it actually took about 15Go max during process.
Regards,
Chris.

**Comment by rubendel** [comment]
It's the amount of entities in the IFC file, so for example 1 for every IfcDoor, IfcWindow etc... Also for example for every IfcCartesianPoint, those usually add up real quick
