### ISSUE TITLE
download bypasses authentication

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#520]
I just realized that calling the download method on the Service interface does not return an authorization error. A valid topic id is returned that can be used for the GET /download interface.

The download returns then just an empty string but there is no indication that it due to a not authenticated request.

Besides that this is pretty confusing, It is also a possible attack vector for DoS I guess.

**Comment by rubendel** [comment]
Thanks for reporting. I have created a new issue to check this for all methods because it will take a while: https://github.com/opensourceBIM/BIMserver/issues/523
