### ISSUE TITLE
Error with bimsurfer

### ISSUE THREAD

**Issue by olivierfaure** [opensourceBIM/BIMserver#528]
Hi, i experiments difficulties to import a model with previous versions, i tried the last 74 version, it's ok to import (unless that checkin doesn't finish geometry progress bar, i have to close but bimvie.ws show 3D model ok. (perhaps navigator timeout ?)

The big problem is : Bimsurfer can't view it, this error occurs and loading graphic stop.

[Error] RangeError: Out of bounds access
	getInt8 (DataInputStreamReader.js:55)
	readByte (DataInputStreamReader.js:55)
	process (BimServerGeometryLoader.js:31)
	(fonction anonyme) (BimSurfer.js:248)
	fire (EventHandler.js:32)
	(fonction anonyme) (xeoViewer.js:160)
	fire (xeogl.js:10962)
	update (xeogl.js:278)
	frame (xeogl.js:228)

Thks

**Comment by olivierfaure** [comment]
I reinstall v69 and import the same project, Bimvie.ws doesn't show 3D (perhaps incompatibility with newer plugins ?) but bimsurfer display well the model.

**Comment by olivierfaure** [comment]
I test v72 too where Bimvie.ws show the 3D model but bimsurfer displays this error and doesn't work :(

[Error] RangeError: Out of bounds access
	getInt8 (DataInputStreamReader.js:55)
	readByte (DataInputStreamReader.js:55)
	process (BimServerGeometryLoader.js:31)
	(fonction anonyme) (BimSurfer.js:248)
	fire (EventHandler.js:32)
	(fonction anonyme) (xeoViewer.js:160)
	fire (xeogl.js:10962)
	update (xeogl.js:278)
	frame (xeogl.js:228)

**Comment by olivierfaure** [comment]
This error is specific to Windows installation of Bimserver 72,73 or 74. I finally tried to install BimServer on a MacOSX server and it works very well on it !

**Comment by rubendel** [comment]
Are you really sure you are using the latest (GIT) version of BIMsurfer V2? The same error occured for somebody who didn't have the latest version.

**Comment by olivierfaure** [comment]
I just install Bimserver from scratch with the plugins by default on the two OS, bimsurfer included. I setup both identically and don't install any different plugins. It works on OS X and not on the Windows one. I'm gonna look to this v2, i saw it but i was afraid it's not official, why V2 (big version ?)

**Comment by olivierfaure** [comment]
You talk about https://github.com/xeolabs/BIMSurfer_v2 ?

**Comment by olivierfaure** [comment]
I just download it, i tried already before, i configure my server (1.5.74) on the exemple and i have this error on index file : 

Can't find this file : http://{server}:8082/js/bimserverapi_BimServerApi.js?bust=2.0

Failed to load resource: the server responded with a status of 404 (Not Found)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bimserverapi_BimServerApi.js, line 0)
[Error] Error: Script error for: bimserverapi_BimServerApi
http://requirejs.org/docs/errors.html#scripterror
	ca (require.js:8:145)
	w (require.js:12:305)
	onScriptError (require.js:30:244)
[Error] TypeError: null is not an object (evaluating 'node.tagName')
	handleContextMenu (injected.js:4)
> Élément sélectionné
< <html lang="en">…</html>

**Comment by rubendel** [comment]
Closing old issues, this one should be on the bimsurfer tracker anyways
