### ISSUE TITLE
Error in examine berkeley db file with db_dump

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#531]
For a debug reason, I want to examine the content of db file located in home/databse. I use the Oracle Berkeley db tool (version 12CR1 6.2.23) `db_dump`. But I have an error `db_dump: BDB5115 open: 00000000.jdb: Invalid argument`. Do you have any idea about this error?

Or what is your recommendation of viewing the content of the db file. Any other tool?

**Comment by rubendel** [comment]
Pretty sure that tool was written for Berkeley DB, not for the Java edition, the file formats of both products are not the same. The keys and values of BDB JE are basically of type byte[], so not sure what you expect to accomplish.

**Comment by xie-qianyue** [comment]
Thanks for your explanation. 

I search a way to examine or manipulate the content of the data file which BIMServer generates, 00000000.jdb in this case. Just like some db client, such as DBVisualizer or Toad do.

**Comment by rubendel** [comment]
Please read the wiki page that explains how this database works and how BIMserver uses it, after you have done that you hopefully understand why it makes no sense to use a db client on a database that has no schema.

**Comment by xie-qianyue** [comment]
Thanks, I understand that it's a key/value pair without schema. But finally I use this [command line tool](https://docs.oracle.com/cd/E17277_02/html/GettingStartedGuide/commandlinetools.html#DbDump) to dump the databases.

**Comment by remiblancher** [comment]
Hi,

I am trying to read a jdb file with the dbdump command line tool. How did you do that ? I also have the same problem invalid argument
db_dump: 0000000.jdb: unexpected file type or format
db_dump: open: 000000.jdb: invalid argument

If you have an idea. Thanks
