### ISSUE TITLE
1.5.74 setup hangs at: Installing ifcopenshellplugin...

### ISSUE THREAD

**Issue by jpstaub** [opensourceBIM/BIMserver#533]
Configuration:
BiMserver = 1.5.74
Tomcat = 8.5
[jwilder/reverse-proxy = 1.13.0](https://github.com/jwilder/nginx-proxy)
Firefox = 53.0.2 (32-bit)

When BiMserver is setting itself up it hangs at:
`Installing ifcopenshellplugin...`

The `bimsurfer` and `bimviews` plugins install normally and the logs say the same. But when it comes to `ifcopenshellplugin` nothing happens. Unlike `bimsurfer` and `bimviews`, there is no log entry suggesting that the installation of `ifcopenshellplugin` has commenced much less failed. 

I had success with BiMserver 1.5.58 at an earlier date so I reinstalled that version just to see if something in my general configuration was broken. 1.5.58 was able to complete a setup sequence without problems. So, it seems there's something not right with 1.5.74.

Eventually a 504 Gateway Time-Out is set on the browser page but up to that point all status codes are 200. Refreshing the page produces the `Server Info` page with a status of `RUNNING`. Clicking on `bimsurfer` produces a `404-Not Found`. Clicking on `bimviews` brings up a page that gets stuck on `Loading BiMviews...` There are two 404 codes set on the page:

1. plugin.version
2. bimserverapi.js?_v=1494357584504

Any assistance would be greatly appreciated.

Regards,
Jake

**Comment by rubendel** [comment]
IfcOpenShell is by far the biggest plugin of them all. On a server that had a really slow internet connection (for a server) I had to explicitly increase the timeout-time of the proxy server I was using (nginx in that case), maybe that works for you too?

If that does not work, try installing BIMserver without IfcOpenShell, at least you'll have a working BIMvie.ws after that so you can use that to install other plugins.

**Comment by jpstaub** [comment]
Hello rubendel,

Thank you for your response.

I tried your second suggestion and it worked straight away. The odd part is that when the IfcOpenShell plugin was subsequently installed it did so with no delay. I did not expect that behavior given your first suggestion. 

Regards,
Jake

**Comment by rubendel** [comment]
I had the same thing, that's because in the background updating the local maven repository will continue. The timeout seems to only be in the request coming from the browser.
