### ISSUE TITLE
creating a BIMsurfer

### ISSUE THREAD

**Issue by azwawmahmoudi** [opensourceBIM/BIMserver#538]
Hello, I have already developed an application that manages the real estate patrimony (in synfony with php, java script).

Now I want to integrate to view IFC files that are stored on my server.

 To do this, I installed a bimserver on my machine. Then I created a project and loaded IFC files.

Now I want to view the IFC files in my application. I used BIMsurfer API for that.

I downloaded the API in my framework. Then I started using the code you offer in this page https://github.com/opensourceBIM/BIMsurfer

The first piece of code is as follows:

Var bimSurfer = new BimSurfer ({
    DomNode: "viewerContainer"
});

The problem is that the BIMsurfer does not want to instantiate itself? I do not understand why!
Is it wrong for me to use the BIMsurfer? Or I skipped a step?
thank you :)

**Comment by ChinmayKshatriya** [comment]
Have you found a solution, If u have please send the code. Thanks!

**Comment by rubendel** [comment]
Cleaning up old issues, this one seems to be for https://github.com/opensourceBIM/BIMsurfer
