### ISSUE TITLE
Question of migration of the data from a database to another database

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#540]
Hello, we need to migrate the data from one database to another. Because the disk of the old database is full, we want to merge the old database to another database in a disk with a larger volume. Our solution is to loop over all the databases, and move every records from the source to the destination.

But we have some problems / questions:

1. We found that there some meta data stored in store_Project which should not(?) be merged. Are the first 3 records the meta data? Can we just skip the first 3 records?
2. Is there any other database like store_Project, which have the meta data stored?
3. We have conflicted Pid, but we have already a solution for this problem.

After all, does this solution work? I mean move every records from one to another.

**Comment by rubendel** [comment]
Not sure if I understand correctly, if you continue to use the same version of BIMserver and the only goal is to move to a larger disk, why don't you just copy the database directory?

**Comment by xie-qianyue** [comment]
We have thought about your solution. It works if the destination disk is empty. But sometimes we want to migrate to a database which is not empty. So in this case, does my solution work?

**Comment by rubendel** [comment]
I am pretty sure that's not going to work. It's way safer to do this one level higher, e.a. have a script download the projects from one server and upload them to the new server using the standard BIMserver API methods. There are many assumptions in the BIMserver database layer that are based on the ordering of identifiers.

Basically all data in the "store" package is metadata.

**Comment by xie-qianyue** [comment]
OK. For the BIMserver API, do you mean the service interfaces, mentioned in this [wiki](https://github.com/opensourceBIM/BIMserver/wiki/Service-Interfaces)? Or is there some docs for the API?

**Comment by rubendel** [comment]
Yes, I see that wiki page is a mess, if you use Java, you can read the documentation in your IDE, or you can use the Console application.

**Comment by xie-qianyue** [comment]
Thank you, I will try to read the JavaDoc in the codes. 

The [Console](https://github.com/opensourceBIM/Console) application is JS web app? It can't be used in the server side, I guess. How can I use it in the migration?

**Comment by rubendel** [comment]
I meant that you can read the documentation on the methods in the API with the Console application.

**Comment by xie-qianyue** [comment]
OK, I got it.
