### ISSUE TITLE
Is there a way to visualize IfcZone with Bimsurfer ?

### ISSUE THREAD

**Issue by olivierfaure** [opensourceBIM/BIMserver#541]
Everything is in title.

**Comment by rubendel** [comment]
If it has geometry, it should already visualize it, so far I have not seen a model that has IfcZones with geometry.

**Comment by rubendel** [comment]
If it has geometry, it should already visualize it, so far I have not seen a model that has IfcZones with geometry.

**Comment by olivierfaure** [comment]
We are new to bimserver and we want to list flats of building in a palette to click and set camera to IfcZone or center on opening door, we only use Javascript API, is there exemples of accessing different objects searching by part of the family or in other information like "Main Door" and get oid to use with bimsurfer ?. we are lost with all console commands, some deprecated or with limited documentation...   Thx :)
