### ISSUE TITLE
Endpoint http://<bimserver>/soap12/AdminInterface?wsdl cannot be reached

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#542]
Running BIMserver 'bimserverwar-1.5.74.war' on Tomcat 
I want to update the web service reference in a .NET solution.
After updating to version 1.5.74 the endpoint cannot be reached.
e.g. http://<bimserver>/soap12/AdminInterface?wsdl
The available SOAP services are listed 'http://<bimserver>/soap12' correctly.
But the wsdl link responds HTTP Status 404 - /soap12/soap12/AdminInterface

Running BIMserver 'bimserverjar-1.5.74.jar' on desktop
The endpoint is reachable.
...
Mai 23, 2017 6:10:56 PM org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean buildServiceFromClass
INFORMATION: Creating Service {org.bimserver}AdminInterfaceService from class org.bimserver.shared.interfaces.AdminInterface
Mai 23, 2017 6:10:56 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFORMATION: Setting the server's publish address to be /soap12/AdminInterface
...

**Comment by rubendel** [comment]
This is fixed in https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.76

**Comment by Jo64** [comment]
It works now. Thank you.
