### ISSUE TITLE
Question of Pid and Poid

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#543]
I find that in Bimserver, Poid is used more often than Pid. Poid is used to reference the SProject object, and the Pid is used to compose the key in the database. Do I understand well?

I find that Pid is increment by 1, but I can't get the rule of the Poid's generation. I notice that the Poid of the first project is always set to a value like 137031(not remember that exactly). So can you show me the code which generate Poid?

**Comment by rubendel** [comment]
Poid's (and all other object ids) are a composition of cid (class id) + oid. It's a long (64bit), the last 12 bits are used for the cid, the remaining 52 for the oid. This way when you have an oid, you can always easily infer the type of the object.

The code where oids are generated: https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/database/Database.java#L242

**Comment by xie-qianyue** [comment]
I got that. But why the oid is added by 65536? If you want to skip the last 12 bits of cid, it should be add by 2^12 = 4096, no?

**Comment by xie-qianyue** [comment]
I have another queation about `Database.STORE_PROJECT_ID`. It is initialized by 1 and never changed. So what it is used for?

**Comment by rubendel** [comment]
It's a constant, your IDE probably has a function to show all references to a variable. All objects in the Store model are stored with this pid (and Integer.MAX_VALUE as it's rid). It's the only pid that does not have a reference from a Project.pid.

**Comment by xie-qianyue** [comment]
>  the last 12 bits are used for the cid
I think that you just make a mistake in your reponse above. The Cid is short type, so it has 16 bits. If so, the fact that the oid is added by 65536 makes sense (2^16=65536).

**Comment by rubendel** [comment]
Ah yes it's 16 bits
