### ISSUE TITLE
BIMsurfer changing-color is unchanged

### ISSUE THREAD

**Issue by yangminqiang** [opensourceBIM/BIMserver#545]
hi,rubendel!

I am following the guide here:
https://github.com/opensourceBIM/BIMsurfer#changing-color-and-transparency-of-objects
download ZIP Project and runing "BIMsurfer demo".

Showing and hiding objects
Hiding three objects by ID:
bimSurfer.setVisibility({ids: ["object3", "object1", "object6"], visible: false });
Setting two objects visible by ID:
bimSurfer.setVisibility({ids: ["object1", "object6"], visible: true });
Hiding all objects of IFC types "IfcSlab" and "IfcWall":
bimSurfer.setVisibility({types: ["IfcSlab", "IfcWall"], visible: false });

I try showing and hiding  objects is OK,
code is :
bimSurfer.setVisibility({ids:["65539:131244","65539:262316"], visible:false});

-----------------------------------------------------------------------
Changing color and transparency of objects
Making two objects pink:
bimSurfer.setColor({ids: ["object3", "object6"], color: [1, 0, 1] })

An optional fourth element may be specified in the color to set opacity:
bimSurfer.setColor({ids: ["object3", "object6"], color: [1, 0, 1, 0.5] })

I tried using the following code, and the color has not changed。
bimSurfer.setColor({ids:["65539:131244","65539:262316"], color:[1, 0, 1]});

In another way, the color remains unchanged。
bimSurfer.setColor({ids:["65539:131244","65539:262316"], color:{r:1, g:0, b:0, a:1}});

The above operation does not have any error information in the Chrome browser console。

Any suggestions? Thanks a lot !

**Comment by rubendel** [comment]
Closing, should be in BIMsurfer tracker
