### ISSUE TITLE
download a part of a model extracted by an query

### ISSUE THREAD

**Issue by berndhahnebach** [opensourceBIM/BIMserver#547]
Hi I do not know it this is the right place to ask since it might be not an issue but an question instead ?!

I use BIMserver 1.5.76 from here https://github.com/opensourceBIM/BIMserver/releases. It works great so far. I used the query to display part of the model in the regard of the query. BTW: this stuff is just unbelievable cool :-) since I can filter the model in the regard of any attributes jus by some lines of code :-)

In the query it is possible to donwload the model, but when I download an IFC2x3 it has only a few entities and only the product entities notthing more. Is it possible to download a "real" useable ifc out of the query? 

Attached the ifc I downloaded. This is quite useless ... 

cheers bernd

`
ISO-10303-21;
HEADER;
FILE_DESCRIPTION ((''), '2;1');
FILE_NAME ('', '2017-05-26T15:16:53', (''), (''), '', 'BIMserver', '');
FILE_SCHEMA (('IFC2X3'));
ENDSEC;
DATA;
#1= IFCBUILDINGELEMENTPROXY('1etyxFp9T3Tgjq3H5cMs1e',$,' ',$,$,$,$,$,$);
#2= IFCBUILDINGELEMENTPROXY('1nuerA0XPBzODXlT0aS1_x',$,' ',$,$,$,$,$,$);
#3= IFCBUILDINGELEMENTPROXY('3eVvdXHoTDqeK8tCc6IGSJ',$,' ',$,$,$,$,$,$);
#4= IFCBUILDINGELEMENTPROXY('0zsQH2c694_BQf_$xCF0Us',$,' ',$,$,$,$,$,$);
#5= IFCBUILDINGELEMENTPROXY('08ZiTAxJ14687cPAZLs46b',$,' ',$,$,$,$,$,$);
ENDSEC;
END-ISO-10303-21;

`

**Comment by berndhahnebach** [comment]
I am wrong here my issue is in the regard of BIMvie.ws I'm gone close and reopen a new one on BIMvie.ws. Sorry guys vor the inconvenience. 

bernd

**Comment by berndhahnebach** [comment]
https://github.com/opensourceBIM/bimvie.ws/issues/87

**Comment by stestaub** [comment]
May this helps: https://github.com/opensourceBIM/BIMserver/wiki/JSON-Queries

Basically you need to explicitly define which objects/elements you want to include in the result. There is a helper attribute in the `includes` section which helps to generate valid ifc files.

**Comment by berndhahnebach** [comment]
Yep it is what I missed, thanks stefan. 

gruss aus winti nach züri ...

**Comment by berndhahnebach** [comment]
but new problems araise ... to download such serialized model a Model Merge Plugin is needed (https://github.com/opensourceBIM/BIMserver/wiki/Model-Merge-Plugin) which seam not part of the standard BIMServer release ...

**Comment by berndhahnebach** [comment]
Is it this one, https://github.com/opensourceBIM/Mergers and how do I install this?

**Comment by berndhahnebach** [comment]
OK I'm another step further BIMServer has an pretty cool plug in manager ... I installed the mergers loaded the Schependomlaan  projekt run the sample code:

`
{
  "type": "IfcWall",
  "includeAllSubtypes": true,
  "includes": [
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory",
    "validifc:Representation",
    "validifc:ObjectPlacement"
  ]
}
`

in viewer only the external wall are shown. I click on download IFC2x3 and it downloads the ifc. In the ifc there seam to be some geometry. If I try to import this IFC into BIMServer it never finishes. BIMsight has 64 boxes all the same. It still does not export propely.

bernd
