### ISSUE TITLE
Erroring during Checkin!Error on line 4496857: IfcBuildingElementProxyType expects 10 fields, but less found (String index out of range: -1)

### ISSUE THREAD

**Issue by lixy-toone** [opensourceBIM/BIMserver#549]
16:28:52 ERROR [LongStreamingCheckinAction]:
                                              (LongAction.java:189)
org.bimserver.shared.exceptions.UserException: Error on line 4496857: IfcBuildin
gElementProxyType expects 10 fields, but less found (String index out of range:
-1)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute
(StreamingCheckinDatabaseAction.java:347)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute
(StreamingCheckinDatabaseAction.java:79)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(Databas
eSession.java:708)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(Databas
eSession.java:685)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStrea
mingCheckinAction.java:62)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.ja
va:43)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on li
ne 4496857: IfcBuildingElementProxyType expects 10 fields, but less found (Strin
g index out of range: -1)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.proc
essRecord(IfcStepStreamingDeserializer.java:356)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.proc
essLine(IfcStepStreamingDeserializer.java:244)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read
(IfcStepStreamingDeserializer.java:179)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read
(IfcStepStreamingDeserializer.java:161)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute
(StreamingCheckinDatabaseAction.java:195)
        ... 6 common frames omitted

When I checked in my ifc file, the error was throwed.Could you tell me why and how to solve it?

**Comment by xie-qianyue** [comment]
related to issue #548

**Comment by yangminqiang** [comment]
#7888078= IFCBUILDINGELEMENTPROXYTYPE('08_4gIP2H2lQH8UDcnLxjz',#41,'807-5-4-1/10KW\X2\FF08686568816BB5FF09\X0\/L/0004*',$,$,(#7888159,#7888161,#7888163),(#7888077),'4655136',$,.NOTDEFINED.);

In this case will be exception(IfcBuildingElementProxyType expects 10 fields, but less found (String index out of range: -1))

**Comment by rubendel** [comment]
Fix will be in in IfcPlugins version 0.0.28

**Comment by yangminqiang** [comment]
hi,rubendel!
when I updated ifcplugins to version 0.0.28,still exception:IfcBuildingElementProxyType expects 10 fields, but less found (String index out of range: -1)

**Comment by rubendel** [comment]
Ah I hadn't noticed I also changed something in the BIMserver project itself. That's checked-in now, I'll make a new release later this week.

**Comment by lixy-toone** [comment]
Could you fix this promble on the new release, please?

**Comment by rubendel** [comment]
I already said I would
