### ISSUE TITLE
Issue in downloading the model JSON data in BIMserver 1.5.76

### ISSUE THREAD

**Issue by miolfo** [opensourceBIM/BIMserver#551]
Hello,

I recently updated my BimServer installation from 1.5.69 to 1.5.76, and after the update I am not able to get the JSON data from the server in a similar manner as before. In the 1.5.69 -version I downloaded the JSON data from the server successfully with the following query: { "type": "IfcObject","includeAllSubtypes": true}. However, after the update this same query returns {"objects":[]}. 
If I take a model with multiple IfcReinforcingBars for example, and change the query to { "type": "IfcReinforcingBar","includeAllSubtypes": true}, I am able to correctly get the data of all IfcReinforcingBar -typed objects, so the query seems to be working fine otherwise. Is it no longer possible to get a JSON with all Ifc objects in the same way as it was before?

Regards,
Mikko

**Comment by rubendel** [comment]
There were a few little changes to the query languages, have a look here: https://github.com/opensourceBIM/BIMserver/issues/526#issuecomment-299137885

**Comment by miolfo** [comment]
Thank you @rubendel, I somehow didn't notice that issue. I got it working now.
