### ISSUE TITLE
Admin interface not found

### ISSUE THREAD

**Issue by ysangkok** [opensourceBIM/BIMserver#552]
https://github.com/opensourceBIM/BIMserver/wiki/Setup says that the admin interface should be at http://host/admin, but I get a 404. Is that documentation page updated?

**Comment by rubendel** [comment]
It's not updated

**Comment by ysangkok** [comment]
I could update it but I don't have rights

**Comment by rubendel** [comment]
You should have an invite

**Comment by ysangkok** [comment]
Thanks
