### ISSUE TITLE
Running the WAR in Jetty Runner doesn't work

### ISSUE THREAD

**Issue by ysangkok** [opensourceBIM/BIMserver#555]
My command line is `java -jar jetty-runner-9.4.5.v20170502.jar --port 8082 /home/janus/.m2/repository/org/opensourcebim/bimserverwar/1.5.77-SNAPSHOT/bimserverwar-1.5.77-SNAPSHOT.war`

After trying to open bimvie.ws, I get a 404 for ws://localhost:8082/stream. It looks like the WarServerInitializer doesn't init the Jsr356Impl. Could that be the reason?

**Comment by studentMa** [comment]
Never met, no problem with Tomcat
