### ISSUE TITLE
Where can I change the domain which is localhost?

### ISSUE THREAD

**Issue by lixy-toone** [opensourceBIM/BIMserver#558]
The bimserver had been deployed successsfully on a server whose IP was 192.168.20.223.After that, I tried to visit the bimserver on another PC, but it failed.I want to change the localhost.Where can I do it?

**Comment by rubendel** [comment]
Not sure what you mean with "changing the localhost". It's usually best to keep it to 127.0.0.1.

What failed? And was there an error message?

**Comment by lixy-toone** [comment]
I mean that the bimserver was installed on a PC which ip is 192.168.20.223.But I visited the bimserver by GoogleChrome on the other PC which ip is 192.168.20.40.Becuse of the setting, when I installed bimserver ,I  set server url is "http://localhost:8080/bimserver".I want to change the "localhost" to ip "192.168.20.223".

**Comment by lixy-toone** [comment]
The error is "POST http://localhost:8080/bimserver/json net::ERR_CONNECTION_REFUSFED"

**Comment by rubendel** [comment]
Ah you have to change the Site Address, you can do this using BIMvie.ws, goto Server Settings.

**Comment by liqiaolin520** [comment]
请问下到底怎么做，能让其他人访问到BIMserver服务。
谢谢
Excuse me what to do, can let others to access the BIMserver service.
thank you
