### ISSUE TITLE
Update to version 1.5.76

### ISSUE THREAD

**Issue by sgeard** [opensourceBIM/BIMserver#559]
I have just tried to upgrade to this version (war) but the resulting installation fails. My update procedure was:
1. tomcat8 stop
2. rename ROOT and ROOT.war to *-old
3. copy bimserverwar-1.5.75.war to ROOT.war
4. tomcat8 start

Reconnecting to bimserver from the clients then fails, server log text below.

[bimserver-log.txt](https://github.com/opensourceBIM/BIMserver/files/1040963/bimserver-log.txt)

Did I miss something in the upgrade process?

Thanks.

**Comment by Jpjob314** [comment]
Please take a look at #432 

Ruben do you have some inputs about managing migrations by ourself ?
For example, from 1.5.74 to 1.5.76 seems only to need Step0032 "Store last login" but I don't know how to use it...

Thanks
