### ISSUE TITLE
Why I cannot find org.bimserver.interfaces.SConverter in PluginBase 

### ISSUE THREAD

**Issue by yangminqiang** [opensourceBIM/BIMserver#563]
hi,
Why I cannot find org.bimserver.interfaces.SConverter in PluginBase ?
Didn't you commit this class ?

Bimserver version :1.5.7.7

**Comment by xie-qianyue** [comment]
In my case, the class SConverter.java is located in the project BimServer, but not PluginBase.

**Comment by yangminqiang** [comment]
I have solved this problem!

**Comment by whatisor** [comment]
No one fix this issue?

**Comment by whatisor** [comment]
BimServer depends PluginBase, PluginBase depends BimServer

**Comment by rubendel** [comment]
Look again, PluginBase does not depend on BimServer.
