### ISSUE TITLE
Question: Physical Delete Project

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#564]
We need to drop all the records of some old projects, because we want to re-use our disk space. BimServer doesn't provide this functionality. I have an idea, but I don't know whether it works or not.

1. Giving a Poid, from this Poid I get the pid of the project in store_Project. 
2. I loop over all the other tables, delete all the records of which the key starts with this pid.

Does it work?

**Comment by studentMa** [comment]
可以尝试，不过感觉行不通，Bimserver不允许删除，删除的话一些潜在错误会出现。最好的方法是进一步将bimserver自主化，有兴趣的话大家以后可以交流。

**Comment by xie-qianyue** [comment]
@studentMa I didn't use the Bimserver Interface to delete the project, but directly use Berkeley DB Java Edition. And I have finished a demo, which seems to be ok, at least throught Bimviewer, the project is deleted, without any impact on the other projects.

**Comment by studentMa** [comment]
@xie-qianyue 这个可以，是个新的途径。请问除了数据库可以直接通过Berkeley DB操作外，您有没有尝试去自主化bimserver？这是我的QQ：294158707@qq.com，可以的话我们可以交流下

**Comment by xie-qianyue** [comment]
@studentMa What do you mean by "自主化bimserver", we have comtumized it a little bit, but not too much. I havn't used QQ for a long time, we can chat by email or wechat if you like to.
