### ISSUE TITLE
error:make clearn install

### ISSUE THREAD

**Issue by Mcc1988** [opensourceBIM/BIMserver#566]
(NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ProjectDeleted
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_UserDeleted
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_PasswordReset
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_DatabaseCreated
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ServerStarted
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ProjectUpdated
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_UserUndeleted
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ProjectUndeleted
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_RevisionUpdated
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_GeoTagUpdated
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_PasswordChanged
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_UserChanged
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_PluginConfiguration
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_SerializerPluginConfi
guration                (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectIDMPluginConfig
uration                 (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_RenderEnginePluginCon
figuration              (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DeserializerPluginCon
figuration              (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DownloadResult
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_CheckoutResult
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DataValue
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DataObject
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_UserSession
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Migration
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ReferenceDataValue
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ListDataValue
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_SimpleDataValue
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DatabaseInformationIt
em                      (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DatabaseInformationCa
tegory                  (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DatabaseInformation
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_PluginDescriptor
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_RevisionSummaryType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_RevisionSummaryContai
ner                     (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_RevisionSummary
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_LongAction
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectIDMPluginDescri
ptor                    (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_CompareItem
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectAdded
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectRemoved
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectModified
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_CompareContainer
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_CompareResult
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_LongActionState
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ServerInfo
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Version
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_File
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ExtendedDataSchema
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ExtendedData
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_QueryEnginePluginConf
iguration               (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_WebModulePluginConfig
uration                 (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ModelMergerPluginConf
iguration               (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ModelComparePluginCon
figuration              (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Service
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Token
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_InternalServicePlugin
Configuration           (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ServiceType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ExtendedDataAddedToRevi
sion                    (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_ExtendedDataAddedToProj
ect                     (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Type
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ObjectType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_PrimitiveType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_LongType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ByteArrayType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_DoubleType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_StringType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_BooleanType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ArrayType
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_Parameter
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ImmediateNotification
Result                  (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: log_RemoteServiceCalled
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_RemoteServiceUpdate
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_PercentageChange
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_SystemInfo
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_JavaInfo
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_BimServerInfo
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_ProjectSmall
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Creating transactional table: store_IfcHeader
                        (NewClassChange.java:45)
11:56:19 INFO  [main]: Upgrading database to version 1
                        (Schema.java:227)
11:56:19 INFO  [main]: Creating 817 transactional tables for package ifc2x3tc1
                        (NewClassBulkChange.java:47)
11:56:21 INFO  [main]: Upgrading database to version 2
                        (Schema.java:227)
11:56:21 INFO  [main]: Upgrading database to version 3
                        (Schema.java:227)
11:56:21 INFO  [main]: Upgrading database to version 4
                        (Schema.java:227)
11:56:21 INFO  [main]: Creating transactional table: store_ModelCheckerResultIte
m                       (NewClassChange.java:45)
11:56:21 INFO  [main]: Creating transactional table: store_ModelCheckerResultHea
der                     (NewClassChange.java:45)
11:56:21 INFO  [main]: Creating transactional table: store_ModelCheckerResultLin
e                       (NewClassChange.java:45)
11:56:21 INFO  [main]: Creating transactional table: store_ModelCheckerResult
                        (NewClassChange.java:45)
11:56:21 INFO  [main]: Creating transactional table: store_ModelCheckerInstance
                        (NewClassChange.java:45)
11:56:21 INFO  [main]: Upgrading database to version 5
                        (Schema.java:227)
11:56:21 INFO  [main]: Upgrading database to version 6
                        (Schema.java:227)
11:56:21 INFO  [main]: Upgrading database to version 7
                        (Schema.java:227)
11:56:22 INFO  [main]: Upgrading database to version 8
                        (Schema.java:227)
11:56:22 INFO  [main]: Upgrading database to version 9
                        (Schema.java:227)
11:56:22 INFO  [main]: Upgrading database to version 10
                        (Schema.java:227)
11:56:22 INFO  [main]: Upgrading database to version 11
                        (Schema.java:227)
11:56:22 INFO  [main]: Upgrading database to version 12
                        (Schema.java:227)
11:56:23 INFO  [main]: Upgrading database to version 13
                        (Schema.java:227)
11:56:23 INFO  [main]: Creating 957 transactional tables for package ifc4
                        (NewClassBulkChange.java:47)
11:56:25 INFO  [main]: Creating transactional table: geometry_GeometryInfo
                        (NewClassChange.java:45)
11:56:25 INFO  [main]: Creating transactional table: geometry_Vector3f
                        (NewClassChange.java:45)
11:56:25 INFO  [main]: Creating transactional table: geometry_GeometryData
                        (NewClassChange.java:45)
11:56:25 INFO  [main]: Upgrading database to version 14
                        (Schema.java:227)
11:56:25 INFO  [main]: Creating transactional table: store_MessagingSerializerPl
uginConfiguration       (NewClassChange.java:45)
11:56:25 INFO  [main]: Upgrading database to version 15
                        (Schema.java:227)
11:56:26 INFO  [main]: Upgrading database to version 16
                        (Schema.java:227)
11:56:26 INFO  [main]: Upgrading database to version 17
                        (Schema.java:227)
11:56:27 INFO  [main]: Upgrading database to version 18
                        (Schema.java:227)
11:56:27 INFO  [main]: Upgrading database to version 19
                        (Schema.java:227)
11:56:28 INFO  [main]: Upgrading database to version 20
                        (Schema.java:227)
11:56:28 INFO  [main]: Creating transactional table: store_Metrics
                        (NewClassChange.java:45)
11:56:28 INFO  [main]: Creating transactional table: store_InterfaceMetric
                        (NewClassChange.java:45)
11:56:28 INFO  [main]: Creating transactional table: store_MethodMetric
                        (NewClassChange.java:45)
11:56:28 INFO  [main]: Upgrading database to version 21
                        (Schema.java:227)
11:56:29 INFO  [main]: Upgrading database to version 22
                        (Schema.java:227)
11:56:30 INFO  [main]: Upgrading database to version 23
                        (Schema.java:227)
11:56:31 INFO  [main]: Creating transactional table: store_PluginBundleVersion
                        (NewClassChange.java:45)
11:56:31 INFO  [main]: Creating transactional table: store_PluginBundle
                        (NewClassChange.java:45)
11:56:31 INFO  [main]: Creating transactional table: store_PluginInformation
                        (NewClassChange.java:45)
11:56:31 INFO  [main]: Upgrading database to version 24
                        (Schema.java:227)
11:56:31 INFO  [main]: Creating transactional table: store_OAuthServer
                        (NewClassChange.java:45)
11:56:31 INFO  [main]: Creating transactional table: store_OAuthAuthorizationCod
e                       (NewClassChange.java:45)
11:56:31 INFO  [main]: Creating transactional table: store_Authorization
                        (NewClassChange.java:45)
11:56:31 INFO  [main]: Creating transactional table: store_SingleProjectAuthoriz
ation                   (NewClassChange.java:45)
11:56:31 INFO  [main]: Upgrading database to version 25
                        (Schema.java:227)
11:56:32 INFO  [main]: Creating transactional table: store_NewServiceDescriptor
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Creating transactional table: store_FormatSerializerMap
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Creating transactional table: store_Action
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Creating transactional table: store_StoreExtendedData
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Creating transactional table: store_CheckinRevision
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Creating transactional table: store_NewService
                        (NewClassChange.java:45)
11:56:32 INFO  [main]: Upgrading database to version 26
                        (Schema.java:227)
11:56:32 INFO  [main]: Upgrading database to version 27
                        (Schema.java:227)
11:56:32 INFO  [main]: Upgrading database to version 28
                        (Schema.java:227)
11:56:33 INFO  [main]: Upgrading database to version 29
                        (Schema.java:227)
11:56:33 INFO  [main]: Upgrading database to version 30
                        (Schema.java:227)
11:56:34 INFO  [main]: Upgrading database to version 31
                        (Schema.java:227)
11:56:34 INFO  [main]: Upgrading database to version 32
                        (Schema.java:227)
11:56:35 INFO  [main]: Non-empty database directory found "home-797237914\databa
se"                     (BerkeleyKeyValueStore.java:86)
11:56:35 INFO  [main]: Changing server state to NOT_SETUP
                        (ServerInfoManager.java:96)
11:56:37 INFO  [main]: Changing server state to RUNNING
                        (ServerInfoManager.java:96)
11:56:37 INFO  [main]: Installing plugins
                        (AllTests.java:104)
11:56:37 INFO  [main]: Installing plugin http://archiva.logic-labs.nl/repository
/snapshots org.opensourcebim.ifcplugins.null (InstallPluginBundle.java:57)
11:56:40 INFO  [main]: Using version 0.0.28 because no version given
                        (InstallPluginBundle.java:61)
11:56:40 INFO  [main]: central (http://central.maven.org/maven2, default, releas
es+snapshots)           (InstallPluginBundle.java:65)
11:56:40 INFO  [main]: 0.0.28
                        (InstallPluginBundle.java:70)
11:56:41 INFO  [main]: Installing plugin http://archiva.logic-labs.nl/repository
/snapshots org.opensourcebim.binaryserializers.null (InstallPluginBundle.java:57
)
11:56:43 INFO  [main]: Using version 0.0.26 because no version given
                        (InstallPluginBundle.java:61)
11:56:43 INFO  [main]: central (http://central.maven.org/maven2, default, releas
es+snapshots)           (InstallPluginBundle.java:65)
11:56:43 INFO  [main]: 0.0.26
                        (InstallPluginBundle.java:70)
11:56:43 INFO  [main]: Installing plugin http://archiva.logic-labs.nl/repository
/snapshots org.opensourcebim.ifcopenshellplugin.null (InstallPluginBundle.java:5
7)

stop here

**Comment by Mcc1988** [comment]
我英文不好，停在这里不不动了，过一会又重复运行一次，又停在这，感觉是一个死循环

**Comment by xie-qianyue** [comment]
@Mcc1988 你试着写英文吧，你写中文作者是看不懂的。另外，多提供一些信息，例如 BimServer 的版本号。我看你的 log 是插件安装问题，服务器应该是启动了的。

**Comment by Mcc1988** [comment]
ifcopenshellplugin is not install.I run command "maven clean install", cmd message is that.

**Comment by Mcc1988** [comment]
@xie-qianyue 你能帮我看看不，可能是我的网络问题，你有什么别不通过网络的方法吗？把插件传给我什么的。

**Comment by rubendel** [comment]
I have no clue as to what you are trying to accomplish. I see maven commands that try to install stuff into the local maven repository and I see a BIMserver log file. Please explain what you want to do? Why not just install the latest already built IfcOpenShell plugin?

**Comment by xie-qianyue** [comment]
@Mcc1988 我也不知道你是什么问题。我印象中只是启动 `maven clean install` 不会安装插件的吧？至于网络问题，你试试用国内的 maven 镜像，或者用 VPN。我传给这个方案不实际。

@rubendel He said that the bimserver try to download the plugins. But the download can't accomplish, and after a while the download restart again and continue the same process. He thought that it may be the network issues. I've told hime to use some maven mirror repos in china or use VPN.

**Comment by rubendel** [comment]
Ah oke thanks for translating. There have been issues with installing plugins and timeouts, I'll have a look at that later (it's a bit hard to reproduce).

**Comment by Mcc1988** [comment]
@rubendel ok,thanks.I 'll try other way.

**Comment by studentMa** [comment]
这个问题我也遇到过，是因为我们在国内内网安装bimserver这个过程中bimserver需要下载并安装其它的开源插件，这些插件是在外网，这样就会导致下载速度非常慢或者停止。建议解决办法：1、VPN翻墙后再安装，2、最好下载最新的bimserver，这样再安装时他会下载与此配对的最新插件

**Comment by Mcc1988** [comment]
@studentMa 谢谢你的回答，你说的有道理，这个常见按日志上说是从这个仓库下载的http://archiva.logic-labs.nl/repository/snapshots ，我用网页根本打不开。我用了一个翻墙工具也不行，是不是一定要用VPN吗？其实再有就是ifcopenshellplugin 0.0.26版本 这个插件为啥去找到那个仓库了呢，始终搞不明白，而且这个版本的插件在许多中央仓库都没有，我想手动下载都不行。
这个仓库在哪里和插件在POM文件中指定的，你知道吗？现在想能不能手动换改工程，换个插件版本试试。我现在没有VPN，你当时用的什么VPN，我用的蓝灯还是不行。

**Comment by Mcc1988** [comment]
@studentMa 我用Maven是新手，等了好长时间，现在出来这个信息了：
17:28:07 INFO  [main]: Using version 0.5.24 because no version given
                        (InstallPluginBundle.java:61)
17:28:08 INFO  [main]: central (http://central.maven.org/maven2, default, releas
es+snapshots)           (InstallPluginBundle.java:65)
17:28:08 INFO  [main]: 0.5.24
                        (InstallPluginBundle.java:70)
org.bimserver.client.DirectBimServerClientFactory@5fbd0979
他这个工程是不是，会动态去确定中央仓库找东西，而且会不断换这个插件的版本，没有0.28，找0.26，有找0.24（找的仓库也换了），这个机制你了解吗？或者在哪里实现的？

**Comment by studentMa** [comment]
绿色VPN可以的，其实bimserver内置的插件都可以手动下载和使用，只是需要经过繁琐的配置，这里就不介绍了太繁琐，涉及到jar包的解压和压缩还要修改它内部的代码。找个靠谱的VPN你这个问题就解决了。
