### ISSUE TITLE
Exemple for searching by Family Name with Javascript API

### ISSUE THREAD

**Issue by olivierfaure** [opensourceBIM/BIMserver#567]
We are new to bimserver and we want to list flats of building in a palette to click and set camera to IfcZone or center on opening door, we only use Javascript API, is there exemples of accessing different objects searching by part of the family name or in other information like "Main Door" and get oid to use with bimsurfer ?

**Comment by rubendel** [comment]
You can iterate over all objects of a certain type (IfcDoor for example) and then examine their properties. Probably not the fastest way, but it'll work.
