### ISSUE TITLE
Starter running error

### ISSUE THREAD

**Issue by peike99** [opensourceBIM/BIMserver#568]
private String getJarFileNameNew() {
		String name = this.getClass().getName().replace(".", "/") + ".class";
		URL urlJar = getClass().getClassLoader().getResource(name);
		String urlString = urlJar.getFile();
		urlString = urlString.substring(urlString.indexOf(":") + 1, urlString.indexOf("!"));

 urlString.substring(urlString.indexOf(":") + 1, urlString.indexOf("!")); has exception ：
urlJar.getFile() value is “/E:/work/BIMserver/BimServerJar/target/classes/org/bimserver/starter/Starter.class”

**Comment by peike99** [comment]
urlString.substring(urlString.indexOf(":") + 1, urlString.indexOf("!")); has exception
please give me ,thanks

**Comment by celiakessassi** [comment]
I got the same issue, any suggestions ?
