### ISSUE TITLE
BimServer login error (WebSocket) 1.5.76

### ISSUE THREAD

**Issue by LordArturo** [opensourceBIM/BIMserver#569]
I have this problem
![tomcat](https://user-images.githubusercontent.com/13532362/26999064-019bd804-4d5f-11e7-9d8d-ecc42cb9640c.PNG

I am using tomcat8 and java8.
I hope you can help me (I'm going crazy)
Regards

**Comment by LordArturo** [comment]
How can I know this in my hosting?

- You are on a corporate network and the system administrators do not allow you to use Web Sockets (either intentionally or not)

Regards

**Comment by studentMa** [comment]
This is your network problem, please contact your network administrator

**Comment by LordArturo** [comment]
Problem of my personal network or the hosting that I am using? 

Thanks for you help!
Regards

**Comment by rubendel** [comment]
Usually the network you are accessing the BIMserver from.

**Comment by LordArturo** [comment]
I have tried another network without a proxy server and I can not connect. It gives me the same error. Could it be that the owners of the hosting block it?

Thanks for you help!
Regards

**Comment by rubendel** [comment]
A little more information about the hosters would be welcome. Are they maintaining Tomcat? Maybe there is a proxy server on their side (I always use one on my servers), you usually have to explicitly tell those proxy servers (apache, nginx, haproxy etc...) to allow websockets.

**Comment by LordArturo** [comment]
Is a vpn, I have installed apache2, tomcat8, and I have modsecurity. Could it be apache2 or modsecurity?

Really Thanks for you help!
Regards

**Comment by rubendel** [comment]
Yes apache was in the list I mentioned...

https://github.com/opensourceBIM/BIMserver/issues/372
https://github.com/opensourceBIM/BIMserver/wiki/Web-socket-error

**Comment by LordArturo** [comment]
Oh thanks. Sorry for the question, but what settings should I add to apache2?

Thanks for you help!
Regards

**Comment by rubendel** [comment]
You need to make sure that "/stream" is forwarded to Tomcat in a websocket-aware way. Consult the documentation of your version of Apache2 to figure out how to do this. A quick google should do wonders.

**Comment by LordArturo** [comment]
Hello,
I have configured apache2 as follows:

`LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
LoadModule proxy_connect_module /usr/lib/apache2/modules/mod_proxy_connect.so
LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
LoadModule proxy_ajp_module /usr/lib/apache2/modules/mod_proxy_ajp.so
#LoadModule proxy_balancer_module /usr/lib/apache2/modules/mod_proxy_balancer.so
LoadModule proxy_express_module /usr/lib/apache2/modules/mod_proxy_express.so
LoadModule lbmethod_byrequests_module /usr/lib/apache2/modules/mod_lbmethod_byr$

ProxyRequests off

ProxyPass /java/stream  ws://111.111.111.111:9090/stream/
ProxyPassReverse /java/stream  ws://111.111.111.111:9090/stream/

ProxyPass /java/ http://111.111.111.111:9090/
ProxyPassReverse /java/ http://111.111.111.111:9090/`


But still not working, could nginx be affecting too?
Thanks for you help!
Regards

**Comment by coryasilva** [comment]
Are you handling the Upgrade Header in the proxy?  I know in NGINX (acting as a reverse proxy) I had to add
```
    proxy_set_header            Upgrade $http_upgrade;
    proxy_set_header            Connection "upgrade";
```

My full nginx config looks like:
```
server {
  listen                        80;
  server_name                   bim.domain.com;
  return                        301 https://$host$request_uri;
}

server {
  listen                        443 ssl;
  server_name                   bim.domain.com;
  ssl_certificate               /etc/nginx/certs/domain.crt;
  ssl_certificate_key           /etc/nginx/certs/domain.key;

  location / {
# TODO    return                      301 https://bim.domain.com/bimserver;
  }

  location /bimserver {
    proxy_redirect          off;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
/etc/nginx/proxy.conf (END)

    proxy_pass                  http://0.0.0.0:8080/bimserver;
    proxy_set_header            Upgrade $http_upgrade;
    proxy_set_header            Connection "upgrade";
  }

**Comment by LordArturo** [comment]
Thanks!! I'll try that 

Why do tomcat websocket examples work and bimserver does not? Is that normal?

Thanks for you help!
Regards
