### ISSUE TITLE
Serviceinterface.download not working

### ISSUE THREAD

**Issue by RanjithSoman** [opensourceBIM/BIMserver#572]
I am able to get the topicid in the step 1 of download method. But the step 2 ,

http://localhost:8082/download?token=9636d2eb64faf7753862c57ba0da28718f5749fc5e68ce16fae2e356746bac4eea54baa8779c36ad015264b16c09efeb&topicId=24

returns no data
{"objects":[]}

16:45:23 INFO  [ServiceInterface.download]: Reading from cache 08db5f2717987c4dee055af493e59374                              (NewDiskCacheManager.java:105)

**Comment by ThomasTian001** [comment]
Hi,

did you found a solution? We have the same Trouble?

Bye
Thomas

**Comment by RanjtihSoman** [comment]
Not yet. It works with older versions of BIM server

**Comment by halmsx** [comment]
@RanjtihSoman which older version working for you?
