### ISSUE TITLE
Not able to install Java Model Checker Plugin v0.0.11 in BimServer v1.5.76

### ISSUE THREAD

**Issue by fumblehool** [opensourceBIM/BIMserver#573]
Hi
I am tying to install Java Model Checker Plugin v0.0.11 on BimServer v1.5.76 but I am getting this error -
```org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.javamodelchecker.JavaModelCheckerPlugin' not found in jar:file:///var/bimserver/home/plugins/org.opensourcebim.javamodelchecker-0.0.11.jar```

Installing v0.0.10 gives the same error. However, I tried installing version 0.0.7 and it was installed successfully. 

What could be the problem?

**Comment by studentMa** [comment]
This problem may be version mismatch, try using the latest bimserver and the latest bimview.

**Comment by fumblehool** [comment]
@studentMa I'm using bimview version 0.0.85 with bimserver version 1.5.76. Is their a version mismatch?

**Comment by cacu100** [comment]
I have the same issue when I try to install this plugin
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.javamodelchecker.JavaModelCheckerPlugin' not found in jar:file:///var/lib/tomcat8/webapps/bimserver/WEB-INF/plugins/org.opensourcebim.javamodelchecker-0.0.11.jar
I'm using BIMServer version 1.5.94

**Comment by Jimmy-Abualdenien** [comment]
I'm having the same issue using "bimserverwar-1.5.90". 
I'm only able to install version 0.0.7, the others are failing with the same error:
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.javamodelchecker.JavaModelCheckerPlugin' not found in jar:file:///bimserverwar-1.5.90/WEB-INF/plugins/org.opensourcebim.javamodelchecker-0.0.11.jar

**Comment by rubendel** [comment]
There is an issue about this on the appropriate issue tracker: https://github.com/opensourceBIM/JavaModelChecker/issues/2
