### ISSUE TITLE
LowLevelCalls - why based on ObjectID instead of GlobalID?

### ISSUE THREAD

**Issue by mansch** [opensourceBIM/BIMserver#574]
Our software uses the low level api calls to fetch structures and object data from the BIMserver.
While we store the global id of objects to keep a reference between revisions, most of the low level api calls require us to use the GlobalID which we need to fetch (or store it but then update it for every new revision).

Why aren't there more methods accepting the Guid too, like getDataObjectByGuid / getDataObjectByOid?
What is the workflow idea behind that? Any recommendations?
Thanks :)

**Comment by rubendel** [comment]
All references in BIMserver internally are by ObjectID. Contrary to it's name a GUID is not unique. For example if you checkin the same file twice in different projects, you'd have the same GUIDs in both projects. Also many objects in IFC don't have a GUID at all.

That being said, we can always add more methods that can handle GUIDs. Just be careful that the getDataObjects calls are going to be removed as they have been deprecated. Have you looked at the new query language? It can handle GUIDs as well and it gives you more flexibility that the getDataObject calls.
