### ISSUE TITLE
Log Config Question

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#576]
Hello Ruben,

I found that the log config file `logback.xml` under "bimserver/src" is removed. In the version of 1.5.74, the log is on the INFO level, when bimserver is updated to 1.5.78, the DEBUG level's logs are also written the log file and the console.

So where I can control the log level now? 

Thanks.

**Comment by rubendel** [comment]
Ah yes I removed it from BIMserver because it's cleaner to have it in the project that has the _main()_ method. I have now added the logback.xml to the BimServerJar project (from which LocalDevBimServerStarter is started).

**Comment by xie-qianyue** [comment]
In the case of that I deploy the project with War in Tomcat, how can I do?

**Comment by rubendel** [comment]
I think if you put a logback.xml file in your home directory BIMserver should pick it up.

**Comment by xie-qianyue** [comment]
Yes. but I did spent a little time in modifying the pom.xml to make it work. In BimServerJar, `logback.xml` should be placed in `target/classes`, in BimServerWar, it should be placed in `WEB-INF/classes`.

If you like, I can make a PR of the above modifications.

**Comment by rubendel** [comment]
I think this is working fine now
