### ISSUE TITLE
error importing ifc file

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#577]
Hello,

when I try to import an ifc file (very classic and simple), I got this error message :
Error on line 685: Incorrect double floating point value: IFCLENGTHMEASURE(2.794956)

the line in the ifc file is :
#4268= IFCQUANTITYLENGTH('NominalHeight','',$,IFCLENGTHMEASURE(2.794956));

thanks by advance...

Olivier

**Comment by rubendel** [comment]
Any chance of sharing the versions of BIMserver/plugins, which deserializer you used and possibly the file?

**Comment by oliviersaintgobain** [comment]
yes Ruben : bimserver version 1.5.74
BinarySerializers 0.0.26
IfcOpenShellPlugin 0.5.24

deserializer selected by interface : ifc2x3tc1 (Streaming)
If I choose : ifc2x3tc1 : it's starting import but block and never stop really...

I attach the file
[IFC Builder - Maison individuelle 2X3.zip](https://github.com/opensourceBIM/BIMserver/files/1097356/IFC.Builder.-.Maison.individuelle.2X3.zip)

**Comment by rubendel** [comment]
Based on section 10.1.6 (Simple defined types) of the ISO 10303-21-2002 specification I'd say that in this case the IFCLENGTHMEASURE is adding redundant information.

This field can only contain an IfcLengthMeasure which is defined to be REAL. So to make this a valid file, the line should be:

```
#4268= IFCQUANTITYLENGTH('NominalHeight','',$,2.794956);
```

Which software is outputting the IFC file?

**Comment by oliviersaintgobain** [comment]
thanks but I have the same file exported from REVIT 2015, and in this file, I have :
#4268= IFCQUANTITYLENGTH('NominalHeight','',$,IFCLENGTHMEASURE(2.794956));
#4269= IFCQUANTITYLENGTH('ClearHeight','',$,IFCLENGTHMEASURE(2.794956));
#4270= IFCQUANTITYAREA('GrossFloorArea','',$,IFCAREAMEASURE(31.176884));
#4271= IFCQUANTITYAREA('NetFloorArea','',$,IFCAREAMEASURE(25.661677));
#4272= IFCQUANTITYVOLUME('GrossVolume','',$,IFCVOLUMEMEASURE(71.723265));
#4273= IFCQUANTITYVOLUME('NetVolume','',$,IFCVOLUMEMEASURE(71.723265));

Olivier

**Comment by rubendel** [comment]
Not sure what you are trying to say with that, can you elaborate?

**Comment by oliviersaintgobain** [comment]
sorry.
actually, I don't knwo which software outputted the ifc version in my first post.

but, if I check the output from REVIT 2015, I have the same kind of format for nominalheight, etc.

and my question is : do you plan to take this kind of format into account, or do I have to check that with the model and to change it in each ifc before uploading it in bimserver ?

Olivier

**Comment by rubendel** [comment]
Revit 2015 is not known for it's good IFC export. I don't plan to change this in BIMserver at the moment. We try to adhere to the standard as much as possible but sometimes it has a lot of room for interpretation.

The header of the file implies that is has been exported on the 20th of Juni this year by a software called "IFC Builder". Maybe you can contact the developer and ask them to change their software?

**Comment by oliviersaintgobain** [comment]
ok thanks

**Comment by oliviersaintgobain** [comment]
Ruben,
I checked the norm you mentionned.
it says that it is replaced by ISO 10303-21:2016.
https://www.iso.org/standard/33713.html

so, are you sure that the information about IFCLENGTHMEASURE is adding redundant information ?

thanks

**Comment by rubendel** [comment]
Ifc2x3tc1 cannot possibly be based on that version (published in 2016), Ifc2x3 is about 10 years older.

Also real sure it's adding redundant information. Look IfcLengthMeasure is always a REAL, and IfcQuantityLength.LengthValue is defined to be of type IfcLengthMeasure, so there is no way adding it to the instance data is going to store more information then we already know (by using the schema).

**Comment by jm-k** [comment]
I had no problem to process the file with IfcOpenShell (IfcConvert). ..I would check the locale environment (that's LC_NUMERIC environment variable on unix platforms)

**Comment by rubendel** [comment]
I fail to see why that's relevant

**Comment by aothms** [comment]
The relevant bit from the standard is:

~~~
A simple defined type is a type defined by an EXPRESS type declaration in which the underlying type
is neither an ENUMERATION nor a SELECT. A simple defined type shall be mapped to the exchange
structure as the data type used in its definition.
~~~

i.e. `IfcQuantityLength.LengthValue` is a `IfcLengthMeasure` [1] which is a simple defined type and must therefore be written as a `REAL` value.

So yes, I agree with that this file does not appear to be valid. Update your software and preferably use the opensource revit ifc exporter from sourceforge.

> had no problem to process the file with IfcOpenShell (IfcConvert)

IfcOpenShell/IfcConvert will parse this file due to its lazily parsed structure. IfcConvert has no business with these quantities so will disregard them. If you were to open the file in e.g. IfcOpenShell-Python and look at these specific entities it will give you similar error messages.

~~~
[1]
TYPE IfcLengthMeasure = REAL;
END_TYPE; 
~~~
