### ISSUE TITLE
Getting java.lang.NullPointerException: null Error.

### ISSUE THREAD

**Issue by fumblehool** [opensourceBIM/BIMserver#578]
Hello

Whenever I try to open <domain>/apps/bimviews/ , I get an error,"java.lang.NullPointerException".
What could be the problem?

**Comment by rubendel** [comment]
Usually null pointer exception come with a stacktrace, it should be in the log file of BIMserver

**Comment by fumblehool** [comment]
@rubendel Here is the bimserver.log - [http://paste.ubuntu.com/24969462/](http://paste.ubuntu.com/24969462/)

Is there some problem with the database?

**Comment by fumblehool** [comment]
@rubendel the problem is in database. How can I reset the database without changing the server configurations?
