### ISSUE TITLE
Installing plugins (gltf serializer by Ruben de Laat)

### ISSUE THREAD

**Issue by rumicuna** [opensourceBIM/BIMserver#579]
We are trying to get the GltfSerializers plugin installed. It was written by Ruben de Laat (thanks Ruben for writing it!!!).

I have bimserver version: bimserverjar-1.5.69.jar

The code is here:
https://github.com/opensourceBIM/GltfSerializers

I downloaded the code and compiled like so:

git clone https://github.com/opensourceBIM/GltfSerializers.git
cd GltfSerializers/Gltf/
mvn package

Then I copied the resulting jar into the plugins folder, this folder was generated when I first ran bimserver:

cp target/gltf-0.0.7-SNAPSHOT.jar ../../home/plugins/

This directory now looks like this:

-rw-r--r--  1 mparedes  staff     20574 Jun 28 17:28 gltf-0.0.7-SNAPSHOT.jar
-rw-r--r--  1 mparedes  staff    146527 Apr  3 12:32 org.opensourcebim.bimserverapi-0.0.112.jar
-rw-r--r--  1 mparedes  staff   2179870 Apr  3 14:21 org.opensourcebim.bimsurfer-0.0.36.jar
-rw-r--r--  1 mparedes  staff    854673 Apr  3 12:31 org.opensourcebim.bimviews-0.0.78.jar
-rw-r--r--  1 mparedes  staff     50434 Apr  3 12:32 org.opensourcebim.binaryserializers-0.0.24.jar
-rw-r--r--  1 mparedes  staff      9868 Apr  3 14:17 org.opensourcebim.cesiumloader-0.0.13.jar
-rw-r--r--  1 mparedes  staff    309418 Apr  3 14:18 org.opensourcebim.citygml-0.0.4.jar
-rw-r--r--  1 mparedes  staff    124388 Apr  3 14:18 org.opensourcebim.collada-0.0.9.jar
-rw-r--r--  1 mparedes  staff    223042 Apr  3 12:32 org.opensourcebim.console-0.0.10.jar
-rw-r--r--  1 mparedes  staff    118387 Apr  3 14:18 org.opensourcebim.demoplugins-0.0.16.jar
-rw-r--r--  1 mparedes  staff  85601354 Apr  3 12:32 org.opensourcebim.ifcopenshellplugin-0.5.22.jar
-rw-r--r--  1 mparedes  staff    120611 Apr  3 12:32 org.opensourcebim.ifcplugins-0.0.23.jar

I now restart bimserver and open a project in bimviews:

http://localhost:8082/apps/bimviews/?page=Projects

Now when I click on Download / Checkout (next to the model), I get a dialog with a list of serializers, I was hoping that "Binary glTF Serializer" would now be listed, but it's not.

What is the proper procedure to install a plugin, and if you know specifically, how would I install this particular plugin (GltfSerializers) so it shows up in the bimviews list of available serializers.

Thank you!
-Martin

**Comment by rubendel** [comment]
You cannot just copy plugins and expect them to work in BIMserver 1.5. You need to install them using the API. You can also use BIMvie.ws to install plugins.
