### ISSUE TITLE
Some parts of the model missing after generating geometry

### ISSUE THREAD

**Issue by miolfo** [opensourceBIM/BIMserver#583]
Hello,

We are trying to upload a 250mb model that has a large amount of small parts to bimserver, and we are running into some issues. The model should look like this (taken from solibri viewer):
![solibri_correct](https://user-images.githubusercontent.com/5992841/28025290-ae537df0-659b-11e7-9b2b-dd6b2f488b28.png)
But sometimes it is missing some parts:
![bimserver_incorrect](https://user-images.githubusercontent.com/5992841/28025872-3a1ac072-659d-11e7-8564-a40c2375ba07.png)

And sometimes the bimvie.ws shows even larger errors:
![bimserver_incorrect2](https://user-images.githubusercontent.com/5992841/28025968-704268da-659d-11e7-8739-24fbc459cc6a.png)

On a local bimserver instance the model seems to work correctly when uploaded, but on our Azure cloud ubuntu machine the model randomly misses some parts. After reuploading the model multiple times, the model will sometimes generate the geometry correctly. Some uploaded versions of the same model also look different in bimvie.ws after refreshing the page. Could the issue be related to having too little processing power or memory on the cloud server, or are there other known issues that could be causing these problems?

**Comment by rubendel** [comment]
Is there anything in the log files at the time of generating the geometry?

**Comment by miolfo** [comment]
During the generation, near to the end of generating geometry, this was printed in the logs:

2017-07-19 10:10:49,095 ERROR [pool-3-thread-3] o.i.IfcGeomServerClient [IfcGeomServerClient.java:467] Invalid command sequence encountered
2017-07-19 10:11:01,718 ERROR [pool-3-thread-3] o.i.IfcGeomServerClient [IfcGeomServerClient.java:502] Forcefully terminated IfcOpenShell process

**Comment by rubendel** [comment]
A lot has been improved in geometry generation lately, so let me know if this is still a problem in for example 1.5.117
