### ISSUE TITLE
Not identifying Deserializer by name.

### ISSUE THREAD

**Issue by ChinmayKshatriya** [opensourceBIM/BIMserver#589]
I want to add ifc to a project via java(eclipse) and then run it on bimsurfer. For the same, I have created the server via eclipse.

1)I want to get the deserializer by name (Ifc2x3tc1).
2)Error: The function getDeserialzer is returing null. So getting null point exception.
3)getSuggestedDeserializerForExtension function is also returning null.
![screenshot 57](https://user-images.githubusercontent.com/30142763/28919668-2636ed24-786c-11e7-9240-fcfa527ba8c9.png)

**Comment by rubendel** [comment]
The error seems to be in line 61, which is not in your screenshot...

Did you load the IfcPlugins pluginbundle?
