### ISSUE TITLE
export ifc model into file

### ISSUE THREAD

**Issue by ManoChanda** [opensourceBIM/BIMserver#591]
I have loaded the ifc file by IfcStepDeserializer then changed it. But unable to write ifc model back to file by IfcStepSerializer. Can anyone guide me how to export ifcModel into file ?

IfcStepSerializer writer = new Ifc2x3tc1StepSerializer(new PluginConfiguration());
Path projectRoot = Paths.get(projectPath);
writer.init( ifcModel , projectInfo, pluginManager, null, null, false);
writer.writeToFile(p.toFile() , null);

**Comment by szyuGH** [comment]
If anyone found a solution for this issue, I'd like to know too, since I'm stuck with the same problem and need a solution as soon as possible for my thesis.

**Comment by rubendel** [comment]
Hi I have added a new example that reads/writes an IFC model: https://github.com/opensourceBIM/IfcPlugins/blob/master/IfcPlugins/test/org/bimserver/test/TestReadWrite.java

**Comment by ManoChanda** [comment]
thanks but the problem is to write the modified ifcmodel back into file. Your previous code worked very well for reading and writing but once model is changed, it will not write the updated one but the last read model before modification.

I am unable to figure out the problem why it is not writing the modified model ?

**Comment by rubendel** [comment]
Your question was "Can anyone guide me how to export ifcModel into file ?". Please be more specific.

I have also added an example that reads, modifies and then writes the model. It works fine for the change I did (edit the names of all walls), it would help to know what you are trying to change.

https://github.com/opensourceBIM/IfcPlugins/blob/master/IfcPlugins/test/org/bimserver/test/TestReadModifyWrite.java
