### ISSUE TITLE
Could the repository be made smaller?

### ISSUE THREAD

**Issue by dopry** [opensourceBIM/BIMserver#594]
I wanted to checkout the repository to see if I could make a few minor changes, and it is 586MB. It takes a long time to clone and takes up a lot of space. I notice most of the files are in a generated folder. Are those necessary for the src? Would it be possible to .gitingore them and maybe prune them from the repo history?

**Comment by rubendel** [comment]
Nope sorry, the generated files are generated by Eclipse and I don't want to enforce every developer to use Eclipse. I already went through the repository a year ago and removed all big files from it's history.

**Comment by dopry** [comment]
Ok, thought I would check. :) 

Are those the files generated by EMF?  Is it possible to generate them using Maven as a part of a build process?

**Comment by rubendel** [comment]
Generating those files was not possible without using the Eclipse IDE, I tried to make it part of the build process a few years ago, but that part of EMF does not work in a "headless" environment.

I might have a look at maybe only checkig in the class files for those generated files, which will at least help with the compile-time (which I think is the biggest problem, not the size on disk)
