### ISSUE TITLE
Can't add a camera to bimviews  : ("BIMSURFER.Camera is not a constructor")

### ISSUE THREAD

**Issue by ChinmayKshatriya** [opensourceBIM/BIMserver#598]
The aim of my project is to save the "selected object", so that the user can later again view the object he/she selected last time.

For the same, I tried to set camera at a particualr coordinates. I have made changes in the bimviews jar file.
In the "3dview.html" file, I made some changes. When a camera was added using the below code, error came that camera is not a constructor. 

Code -

```javascript
	o.camera=new BIMSURFER.Camera(o.viewer,{
        eye: [5, 5, 5],
        active: false
      });
		
```
I have another issue, how to take screenshot of the canvas where model is loaded.
![screenshot 61](https://user-images.githubusercontent.com/30142763/29549872-4da3f940-8728-11e7-8c75-313b9cf5585f.png)
![screenshot 60](https://user-images.githubusercontent.com/30142763/29549874-53c8925e-8728-11e7-8fc9-ba4aacce122b.png)

**Comment by rubendel** [comment]
Please post on BIMsurfer github repo, also please create separate issues for separate questions.
