### ISSUE TITLE
Database Size

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#599]
Hello,
we are working on a version 1.5.74 of bimserver.
we made a lot of test but now, it's difficult because the database is huge and the memory is full at the start of the bimserver...
volume of DB (berkeley database space):
- 2284 jdb files 
- more than 22 Go 

how to proceed to check the content of the berkeley java db ?
how to clean this database ?

thanks a lot

olivier

**Comment by xie-qianyue** [comment]
When you say "clean" the database, do you mean drop the data physically? If so, you can search "delete physically" in the issues, there have been several discussions on that topic.

**Comment by oliviersaintgobain** [comment]
yes correct. but in your post, I don't really see any concrete solution. You mention that you developd your own procedure to "delete" data in the db, but we can't see the source code. is it possible to share it ?
thanks.

**Comment by xie-qianyue** [comment]
My solution is to drop the data by project, not to clean the database. I'm not sure whether it fits your request. Also I remember that the author @rubendel have said that it may have an official "physical delete".

**Comment by oliviersaintgobain** [comment]
ok. so, how to drop the data by project ? (it will fit my request ;))

**Comment by xie-qianyue** [comment]
[Here](https://github.com/xie-qianyue/CustomBimServer/blob/master/DeleteProjectPhysicallyDatabaseAction.java) is the class for the delete function. I couldn't create the whole project on github.

**Comment by oliviersaintgobain** [comment]
it's working fine. thanks
