### ISSUE TITLE
numerous open ports in bimserver.org

### ISSUE THREAD

**Issue by jatan99** [opensourceBIM/BIMserver#600]
Looks like you have numerous open ports that also show service versions. An attacker can leverage this information when trying an attack. Ports should be filtered and banners should be removed/generalized.
 
nmap -sV bimserver.org

21/tcp    open   ftp      Pure-FTPd
22/tcp    open   ssh      OpenSSH 5.3 (protocol 2.0)
25/tcp    open   smtp     Exim smtpd 4.87
80/tcp    open   http     Apache httpd 2.2.29 ((Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4)
110/tcp   open   pop3     Dovecot pop3d
143/tcp   open   imap     Dovecot imapd
443/tcp   open   ssl/ssl  Apache httpd (SSL-only mode)
465/tcp   open   ssl/smtp Exim smtpd 4.87
587/tcp   open   smtp     Exim smtpd 4.87
993/tcp   open   ssl/imap Dovecot imapd
995/tcp   open   ssl/pop3 Dovecot pop3d
3306/tcp  open   mysql    MySQL 5.5.52-cll

**Comment by jatan99** [comment]
hello please tell me why you make this close?

**Comment by rubendel** [comment]
Because it's not about the OpenSource BIMserver

**Comment by rubendel** [comment]
You don't have to test anything, what do you want to use BIMserver for?
