### ISSUE TITLE
Geolocate a BIM Project and bimsurfer error

### ISSUE THREAD

**Issue by BoudBoud47** [opensourceBIM/BIMserver#601]
Hello 
I have bimserver 1.5.85 (WAR version in tomcat)
I see in features, i can geolocate project : How ?
During install, i have choice to install different plugins, i choice to install all. It 's okay.
But in homepage of bimserver when i click on bimsurfer i have 404 not found.

**Comment by studentMa** [comment]
I'm using bimsurfer 1.5.63, which defaults to 404, which is normal. You need to download the bimsurfer separately to access the server model locally.

**Comment by BoudBoud47** [comment]
Ok for bimsurfer. I will look that.
For geolocate project i found this : http://bimserver.org/geolocate/ but i dont find in my bimserver.

**Comment by studentMa** [comment]
I haven't used OpenStreetMap, but I think it should also be a plug-in that can be integrated into bimserver.

**Comment by BoudBoud47** [comment]
I search but i not found anything. 
The same,  0 guide for installation of bimsufer https://github.com/opensourceBIM/BIMsurfer

**Comment by JickYang** [comment]
@studentMa  你好，我想问一下您在使用BimServer的时候在安装插件的那一步有提示过no working outgoing internet connection然后就失败了的问题么？

**Comment by BoudBoud47** [comment]
I found nothing for geolocate on openstreemap

**Comment by BoudBoud47** [comment]
UP.
I see version 1.00 can Geolocate projects using Openstreetmap .  http://bimserver.org/geolocate/ 
Can we in version 1.5.* version ?
