### ISSUE TITLE
how to clean unused plugins 

### ISSUE THREAD

**Issue by wlhm1984** [opensourceBIM/BIMserver#603]
i develop plugin use eclipse by set arguments -plugins "E:\bim\bimserver\demoplugin",but when i delete this argument in eclipse ,then restart, project name still exist  on index page. how can i delete it.

**Comment by rubendel** [comment]
Hmm I don't think you can without removing the database.

**Comment by wlhm1984** [comment]
how to delete the data in Berkeley db，and how can know the data in  which table?thanks

**Comment by rubendel** [comment]
No I meant remove the whole database, there is no special facility to delete just this, I don't think it's really important...

**Comment by wlhm1984** [comment]
remove the whole database?all base data need rebuild?
