### ISSUE TITLE
Bug: Directory Listing and Information Disclosure at http://bimserver.org/wp-includes/

### ISSUE THREAD

**Issue by Cyb3rM0nkey** [opensourceBIM/BIMserver#604]
Hi BIMserver team,

I am a Cyber Security Researcher. I found Directory listing and information disclosure at one of your domains. The following are the screen shots and Details.

Domain: http://bimserver.org/wp-includes/

Vulnerability type:Directory Listing and Banner Grabbing

Description: Web servers can be configured to automatically list the contents of directories that do not have an index page present. This can aid an attacker by enabling them to quickly identify the resources at a given path, and proceed directly to analyzing and attacking those resources. It particularly increases the exposure of sensitive files within the directory that are not intended to be accessible to users.
Banner Grabbing is a technique used to gain information about a remote server and is often used as part of a fingerprinting attack. If an attacker wants to look for vulnerabilities in a system, banner grabbing is an easy way to do it.

Severity: Medium

Remediation:
1.  Configure your web server to prevent directory listings for all paths beneath the web root;
2. Place into each directory a default file (such as index.htm) that the web server will display instead of returning a directory listing.
![screenshot from 2017-08-31 13-37-46](https://user-images.githubusercontent.com/28823495/29923725-2908aa16-8e78-11e7-8a1d-3fb2555e504e.png)
![screenshot from 2017-08-31 13-38-33](https://user-images.githubusercontent.com/28823495/29923729-2dd11506-8e78-11e7-94f6-38f7285e239e.png)

**Comment by Cyb3rM0nkey** [comment]
Also Please Let me know if there is any reward for the above?

**Comment by Cyb3rM0nkey** [comment]
May I know why the issue is closed?

**Comment by rubendel** [comment]
This has been posted many times now, please search for an issue before posting a new one
