### ISSUE TITLE
Can't install plugins when Setup the server

### ISSUE THREAD

**Issue by alilouchka** [opensourceBIM/BIMserver#606]
I got this problem when I setup my server: 
![2017-09-07_10h09_47](https://user-images.githubusercontent.com/26714480/30152885-f1f014d2-93b4-11e7-9b8c-7fb67229f1a2.png)
![2017-09-07_10h10_15](https://user-images.githubusercontent.com/26714480/30152923-0ded17fc-93b5-11e7-9995-30497cbf6e95.png)

when i launch the browser i get only the Runing Statut without the GUI to add projects.

Any solutions please ? 

Thanks

**Comment by rubendel** [comment]
The setup process can only be done once, if for some reason it fails halfway, you need to remove the database and try again. The plugin bundles that have already been installed is in indication of this.
