### ISSUE TITLE
Rebars visibility issue

### ISSUE THREAD

**Issue by cnirbhay** [opensourceBIM/BIMserver#608]
***Hello***, Everyone. ***Greetings*** from ***India***.

We are using recent **1.5.85** version of **BIMserver** on a *dedicated server*. The ***rebars*** are ***not visible***. Earlier in *June*, we were using some *previous version* of it and there was *no such problem*, even with the ***same IFC files***.

Kindly ***suggest*** what could be the ***possible issue***.

Thank you.

With *best regards*,

***Nirbhay Chauhan***

**Comment by rubendel** [comment]
Can you share the IFC file that is missing the rebar? Also I don't think it's really necessary to do self promotion on github by including a list of urls that have nothing to do with the issue.

**Comment by cnirbhay** [comment]
[demobuilding6.zip](https://github.com/opensourceBIM/BIMserver/files/1307091/demobuilding6.zip)

**Comment by rubendel** [comment]
Sorry, finally had a look at this, in the latest version of everything this is the result I get, is it what you expect?

![rebar](https://user-images.githubusercontent.com/377978/33832244-ae31dd68-de7b-11e7-8a7c-8021898c3202.png)

**Comment by cnirbhay** [comment]
Hi,

Even I'm able to get upto this. Please try to isolate the rebars in the
model. I was unable to see them.

Thank you.

Regards,

On 11-Dec-2017 6:31 PM, "Ruben de Laat" <notifications@github.com> wrote:

Sorry, finally had a look at this, in the latest version of everything this
is the result I get, is it what you expect?

[image: rebar]
<https://user-images.githubusercontent.com/377978/33832244-ae31dd68-de7b-11e7-8a7c-8021898c3202.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensourceBIM/BIMserver/issues/608#issuecomment-350717752>,
or mute the thread

**Comment by rubendel** [comment]
But this is the same thing I see in Solibri and DDS-CAD

**Comment by rubendel** [comment]
Just tried this file again, all the rebar is also visible, closing
