### ISSUE TITLE
Adding photos to a model

### ISSUE THREAD

**Issue by ivankrkr** [opensourceBIM/BIMserver#611]
Hi, i have developed a webapp for adding photos to a model:
http://www.dizayna.net
A user just adds a photo by dragging-and-dropping to picture taking position and rotate it.

Here is how it looks with a building model:
http://www.dizayna.net/plant_survey/tesc-3/

How do you think can it be useful for users if i would try to develop a plug-in for BIMServer?

Ivan

**Comment by rubendel** [comment]
Very cool, but I don't think the BIMserver issue tracker is the place for this

**Comment by ivankrkr** [comment]
I have not found any other place to write it, sorry! Could you tell me where it is allowed?
