### ISSUE TITLE
Unable to checkin IFC2x3 model in BIMvie.ws : IfcGasTerminalType and RelatedObjects

### ISSUE THREAD

**Issue by chkkbim** [opensourceBIM/BIMserver#612]
Hi, I am using BIMserver 1.5.85.

I tried to checkin the model "ModernHomePrototype.ifc" from here :
[zipfile](http://download2.nemetschek.net/www_misc/2009/Modern_Home_Prototype.zip)

BIMvie.ws gives me this error message : 
_Error on line 513064 : IfcGasTerminalType cannot be stored in RelatedObjects._

The relevant part of the log is here : 
[error.zip](https://github.com/opensourceBIM/BIMserver/files/1305257/error.zip)

Appreciate if you could look into this issue.
Thank you.

**Comment by hlg** [comment]
This is an error in the IFC file. It sets the attribute `RelatedObjects` (in `IfcRelDefinesByProperties`) to an entity of type `IfcGasTerminalType` which is a subtype of the `IfcTypeObject` type, whereas only `IfcObject` subtypes are allowed for this attribute. The reference should probably lead to an actual terminal instance, that is instance of `IfcFlowTerminal`. This terminal might be of the `IfcGasTerminalType` in question.

**Comment by rubendel** [comment]
Thanks @hlg
