### ISSUE TITLE
Projects by new accounts don't get their geometry generated

### ISSUE THREAD

**Issue by miolfo** [opensourceBIM/BIMserver#613]
Hello,

I just installed BimServer version 1.5.81 on a tomcat8 webserver, and everything seems to work fine as long as I use the main account. But accounts created for other users are unable to add models correctly. If I try to checkin the same model to the same project using a different account, geometry doesn't get generated and the model is not visible in the 3D view. All accounts that I tested with have their user level set to Adminstrator, so that shouldn't be an issue.

Regards,
Mikko Forsman

Edit:
Additionally, the models seem to get correctly uploaded to the server. I can download the models from the server just fine, but the only thing missing is the geometry.

**Comment by rubendel** [comment]
Sorry for the late reply. It could be that the new users have a different default render engine. You can change the default render engine in User Settings.

**Comment by rubendel** [comment]
In recent releases the default render engine was sometimes the "NOP" renderer, which does nothing. This has not been changed to IfcOpenShell if it's available (installed as a plugin). Will be in 1.5.89
