### ISSUE TITLE
checkinFromUrl DecoderException errror

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#614]
hi

need some assistance here. ive no problem with creating projects. but having issues when trying to check in the file.

im getting the following error:

`{ response: 
   { exception: 
      { __type: 'UserException',
        message: 'org.apache.commons.codec.DecoderException: Odd number of characters.' } } }`

example of my params:
`{ token: 'gcheA6f76x0tki-Koe2B9GU2KM0y4pAtph9Vm8Iq_Qs',
request: 
   { interface: 'ServiceInterface',
     method: 'checkinFromUrl',
     parameters: 
      { poid: 12058625,
        comment: 'Revit Project 2',
        deserializerOid: 589865,
        fileName: 'RevitModel5a.ifc',
        url: 'http://localhost.dd:8083/sites/localhost.dd/files/bim/ifc/project-folder/1/RevitModel5a_0.ifc',
        merge: 'false',
        sync: 'true' } } }`

terminal gives me the following:
`12:29:07 INFO  [qtp2128961136-29]: {"token":"roIKUF2yjQYih_J1xxgIy9uNlgvKXeJHIzrEOTqxVRI","request":{"interface":"ServiceInterface","method":"checkinFromUrl","parameters":{"poid": 12058625,"comment":"Revit Project 2'","deserializerOid":589865,"fileName":"RevitModel5a.ifc","url":"http://localhost.dd:8083/sites/localhost.dd/files/bim/ifc/project-folder/1/RevitModel5a_0.ifc","merge":"false","sync":"true"}}} (JsonHandler.java:69) `

i can upload the file using bimvie. and also working in bimservers' console using same param values with both checkin and checkinFromUrl.

am i missing something? thanks in advance

**Comment by halmsx** [comment]
oh..
BIMserver 1.5.85 (jar)

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by halmsx** [comment]
no one?

**Comment by rubendel** [comment]
The token "gcheA6f76x0tki-Koe2B9GU2KM0y4pAtph9Vm8Iq_Qs", how did you get it?

**Comment by halmsx** [comment]
its from the login method. tokens above are just examples from my output. projects can be created without any issues.

using checkin method works fine. but checkinFromUrl is giving me the error above.

**Comment by rubendel** [comment]
I am asking because BIMserver does not give tokens that contains '_' or '-' characters, tokens only contain hexadecimal characters. The error message about the "Odd number of characters" probably is caused by this.

**Comment by halmsx** [comment]
oh. i just copy and paste the values, including token as an example. the terminal output from teh last codes are the actual output.

my "checkin" script works fine. but not checkinFromUrl. could the dash in the url be a problem?

**Comment by rubendel** [comment]
Ah ok, I think the URL should be fine, especially if it's working in BIMvie.ws. You might have to do a urlencode of the URL though.

**Comment by halmsx** [comment]
hmm... no change
`var newRevisionData = {
                    "token": token,
                    "request": {
                      "interface": "ServiceInterface",
                      "method": "checkinFromUrl",
                      "parameters": {
                        "poid": json.oid,
                        "comment": elem.project_title,
                        "deserializerOid": res.oid,
                        "fileName": elem.ifc_file_name.filename,
                        "url": encodeURI(elem.project_files),
                        "merge": "false",
                        "sync": "true"
                      }
                    }
                  }`

**Comment by halmsx** [comment]
here is full response...

IncomingMessage {
  _readableState: 
  ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: false,
    ended: true,
    endEmitted: true,
    reading: false,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    defaultEncoding: 'utf8',
    ranOut: false,
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null },
    readable: false,
    domain: null,
    _events: { end: [Function: responseOnEnd] },
    _eventsCount: 1,
    _maxListeners: undefined,
    socket: 
    Socket {
      connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
        readable: false,
        domain: null,
        _events: 
        { end: [Function: socketOnEnd],
          finish: [Function: onSocketFinish],
          _socketEnd: [Function: onSocketEnd],
          free: [Function: onFree],
          close: [Object],
          agentRemove: [Function: onRemove],
          drain: [Function: ondrain],
          error: [Function: socketErrorListener],
          data: [Function: socketOnData] },
          _eventsCount: 9,
          _maxListeners: undefined,
          _writableState: 
          WritableState {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object] },
            writable: false,
            allowHalfOpen: false,
            destroyed: true,
            _bytesDispatched: 587,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: 
            ClientRequest {
              domain: null,
              _events: [Object],
              _eventsCount: 1,
              _maxListeners: undefined,
              output: [],
              outputEncodings: [],
              outputCallbacks: [],
              outputSize: 0,
              writable: true,
              _last: true,
              upgrading: false,
              chunkedEncoding: false,
              shouldKeepAlive: false,
              useChunkedEncodingByDefault: true,
              sendDate: false,
              _removedHeader: [Object],
              _contentLength: null,
              _hasBody: true,
              _trailer: '',
              finished: true,
              _headerSent: true,
              socket: [Circular],
              connection: [Circular],
              _header: 'POST /json HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: Needle/1.0.0 (Node.js v6.11.3; darwin x64)\r\nContent-Length: 373\r\nContent-Type: application/json; charset=utf-8\r\nHost: localhost:8585\r\nConnection: close\r\n\r\n',
              _headers: [Object],
              _headerNames: [Object],
              _onPendingData: null,
              agent: [Object],
              socketPath: undefined,
              timeout: undefined,
              method: 'POST',
              path: '/json',
              _ended: true,
              parser: null,
              res: [Circular] },
              read: [Function],
              _consuming: true,
              write: [Function: writeAfterFIN],
              _idleNext: null,
              _idlePrev: null,
              _idleTimeout: -1 },
              connection: 
              Socket {
                connecting: false,
                _hadError: false,
                _handle: null,
                _parent: null,
                _host: 'localhost',
                _readableState: 
                ReadableState {
                  objectMode: false,
                  highWaterMark: 16384,
                  buffer: [Object],
                  length: 0,
                  pipes: null,
                  pipesCount: 0,
                  flowing: true,
                  ended: true,
                  endEmitted: true,
                  reading: false,
                  sync: false,
                  needReadable: false,
                  emittedReadable: false,
                  readableListening: false,
                  resumeScheduled: false,
                  defaultEncoding: 'utf8',
                  ranOut: false,
                  awaitDrain: 0,
                  readingMore: false,
                  decoder: null,
                  encoding: null },
                  readable: false,
                  domain: null,
                  _events: 
                  { end: [Function: socketOnEnd],
                    finish: [Function: onSocketFinish],
                    _socketEnd: [Function: onSocketEnd],
                    free: [Function: onFree],
                    close: [Object],
                    agentRemove: [Function: onRemove],
                    drain: [Function: ondrain],
                    error: [Function: socketErrorListener],
                    data: [Function: socketOnData] },
                    _eventsCount: 9,
                    _maxListeners: undefined,
                    _writableState: 
                    WritableState {
                      objectMode: false,
                      highWaterMark: 16384,
                      needDrain: false,
                      ending: true,
                      ended: true,
                      finished: true,
                      decodeStrings: false,
                      defaultEncoding: 'utf8',
                      length: 0,
                      writing: false,
                      corked: 0,
                      sync: false,
                      bufferProcessing: false,
                      onwrite: [Function],
                      writecb: null,
                      writelen: 0,
                      bufferedRequest: null,
                      lastBufferedRequest: null,
                      pendingcb: 0,
                      prefinished: true,
                      errorEmitted: false,
                      bufferedRequestCount: 0,
                      corkedRequestsFree: [Object] },
                      writable: false,
                      allowHalfOpen: false,
                      destroyed: true,
                      _bytesDispatched: 587,
                      _sockname: null,
                      _pendingData: null,
                      _pendingEncoding: '',
                      server: null,
                      _server: null,
                      parser: null,
                      _httpMessage: 
                      ClientRequest {
                        domain: null,
                        _events: [Object],
                        _eventsCount: 1,
                        _maxListeners: undefined,
                        output: [],
                        outputEncodings: [],
                        outputCallbacks: [],
                        outputSize: 0,
                        writable: true,
                        _last: true,
                        upgrading: false,
                        chunkedEncoding: false,
                        shouldKeepAlive: false,
                        useChunkedEncodingByDefault: true,
                        sendDate: false,
                        _removedHeader: [Object],
                        _contentLength: null,
                        _hasBody: true,
                        _trailer: '',
                        finished: true,
                        _headerSent: true,
                        socket: [Circular],
                        connection: [Circular],
                        _header: 'POST /json HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: Needle/1.0.0 (Node.js v6.11.3; darwin x64)\r\nContent-Length: 373\r\nContent-Type: application/json; charset=utf-8\r\nHost: localhost:8585\r\nConnection: close\r\n\r\n',
                        _headers: [Object],
                        _headerNames: [Object],
                        _onPendingData: null,
                        agent: [Object],
                        socketPath: undefined,
                        timeout: undefined,
                        method: 'POST',
                        path: '/json',
                        _ended: true,
                        parser: null,
                        res: [Circular] },
                        read: [Function],
                        _consuming: true,
                        write: [Function: writeAfterFIN],
                        _idleNext: null,
                        _idlePrev: null,
                        _idleTimeout: -1 },
                        httpVersionMajor: 1,
                        httpVersionMinor: 1,
                        httpVersion: '1.1',
                        complete: true,
                        headers: 
                        { date: 'Mon, 02 Oct 2017 17:44:05 GMT',
                          'access-control-allow-headers': 'Content-Type',
                          'content-type': 'application/json;charset=utf-8',
                          connection: 'close',
                          server: 'Jetty(9.3.7.v20160115)' },
                          rawHeaders: 
                          [ 'Date',
                            'Mon, 02 Oct 2017 17:44:05 GMT',
                            'Access-Control-Allow-Headers',
                            'Content-Type',
                            'Content-Type',
                            'application/json;charset=utf-8',
                            'Connection',
                            'close',
                            'Server',
                            'Jetty(9.3.7.v20160115)' ],
                            trailers: {},
                            rawTrailers: [],
                            upgrade: false,
                            url: '',
                            method: null,
                            statusCode: 200,
                            statusMessage: 'OK',
                            client: 
                            Socket {
                              connecting: false,
                              _hadError: false,
                              _handle: null,
                              _parent: null,
                              _host: 'localhost',
                              _readableState: 
                              ReadableState {
                                objectMode: false,
                                highWaterMark: 16384,
                                buffer: [Object],
                                length: 0,
                                pipes: null,
                                pipesCount: 0,
                                flowing: true,
                                ended: true,
                                endEmitted: true,
                                reading: false,
                                sync: false,
                                needReadable: false,
                                emittedReadable: false,
                                readableListening: false,
                                resumeScheduled: false,
                                defaultEncoding: 'utf8',
                                ranOut: false,
                                awaitDrain: 0,
                                readingMore: false,
                                decoder: null,
                                encoding: null },
                                readable: false,
                                domain: null,
                                _events: 
                                { end: [Function: socketOnEnd],
                                  finish: [Function: onSocketFinish],
                                  _socketEnd: [Function: onSocketEnd],
                                  free: [Function: onFree],
                                  close: [Object],
                                  agentRemove: [Function: onRemove],
                                  drain: [Function: ondrain],
                                  error: [Function: socketErrorListener],
                                  data: [Function: socketOnData] },
                                  _eventsCount: 9,
                                  _maxListeners: undefined,
                                  _writableState: 
                                  WritableState {
                                    objectMode: false,
                                    highWaterMark: 16384,
                                    needDrain: false,
                                    ending: true,
                                    ended: true,
                                    finished: true,
                                    decodeStrings: false,
                                    defaultEncoding: 'utf8',
                                    length: 0,
                                    writing: false,
                                    corked: 0,
                                    sync: false,
                                    bufferProcessing: false,
                                    onwrite: [Function],
                                    writecb: null,
                                    writelen: 0,
                                    bufferedRequest: null,
                                    lastBufferedRequest: null,
                                    pendingcb: 0,
                                    prefinished: true,
                                    errorEmitted: false,
                                    bufferedRequestCount: 0,
                                    corkedRequestsFree: [Object] },
                                    writable: false,
                                    allowHalfOpen: false,
                                    destroyed: true,
                                    _bytesDispatched: 587,
                                    _sockname: null,
                                    _pendingData: null,
                                    _pendingEncoding: '',
                                    server: null,
                                    _server: null,
                                    parser: null,
                                    _httpMessage: 
                                    ClientRequest {
                                      domain: null,
                                      _events: [Object],
                                      _eventsCount: 1,
                                      _maxListeners: undefined,
                                      output: [],
                                      outputEncodings: [],
                                      outputCallbacks: [],
                                      outputSize: 0,
                                      writable: true,
                                      _last: true,
                                      upgrading: false,
                                      chunkedEncoding: false,
                                      shouldKeepAlive: false,
                                      useChunkedEncodingByDefault: true,
                                      sendDate: false,
                                      _removedHeader: [Object],
                                      _contentLength: null,
                                      _hasBody: true,
                                      _trailer: '',
                                      finished: true,
                                      _headerSent: true,
                                      socket: [Circular],
                                      connection: [Circular],
                                      _header: 'POST /json HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: Needle/1.0.0 (Node.js v6.11.3; darwin x64)\r\nContent-Length: 373\r\nContent-Type: application/json; charset=utf-8\r\nHost: localhost:8585\r\nConnection: close\r\n\r\n',
                                      _headers: [Object],
                                      _headerNames: [Object],
                                      _onPendingData: null,
                                      agent: [Object],
                                      socketPath: undefined,
                                      timeout: undefined,
                                      method: 'POST',
                                      path: '/json',
                                      _ended: true,
                                      parser: null,
                                      res: [Circular] },
                                      read: [Function],
                                      _consuming: true,
                                      write: [Function: writeAfterFIN],
                                      _idleNext: null,
                                      _idlePrev: null,
                                      _idleTimeout: -1 },
                                      _consuming: true,
                                      _dumped: false,
                                      req: 
                                      ClientRequest {
                                        domain: null,
                                        _events: { prefinish: [Function: requestOnPrefinish] },
                                        _eventsCount: 1,
                                        _maxListeners: undefined,
                                        output: [],
                                        outputEncodings: [],
                                        outputCallbacks: [],
                                        outputSize: 0,
                                        writable: true,
                                        _last: true,
                                        upgrading: false,
                                        chunkedEncoding: false,
                                        shouldKeepAlive: false,
                                        useChunkedEncodingByDefault: true,
                                        sendDate: false,
                                        _removedHeader: { 'content-length': false },
                                        _contentLength: null,
                                        _hasBody: true,
                                        _trailer: '',
                                        finished: true,
                                        _headerSent: true,
                                        socket: 
                                        Socket {
                                          connecting: false,
                                          _hadError: false,
                                          _handle: null,
                                          _parent: null,
                                          _host: 'localhost',
                                          _readableState: [Object],
                                          readable: false,
                                          domain: null,
                                          _events: [Object],
                                          _eventsCount: 9,
                                          _maxListeners: undefined,
                                          _writableState: [Object],
                                          writable: false,
                                          allowHalfOpen: false,
                                          destroyed: true,
                                          _bytesDispatched: 587,
                                          _sockname: null,
                                          _pendingData: null,
                                          _pendingEncoding: '',
                                          server: null,
                                          _server: null,
                                          parser: null,
                                          _httpMessage: [Circular],
                                          read: [Function],
                                          _consuming: true,
                                          write: [Function: writeAfterFIN],
                                          _idleNext: null,
                                          _idlePrev: null,
                                          _idleTimeout: -1 },
                                          connection: 
                                          Socket {
                                            connecting: false,
                                            _hadError: false,
                                            _handle: null,
                                            _parent: null,
                                            _host: 'localhost',
                                            _readableState: [Object],
                                            readable: false,
                                            domain: null,
                                            _events: [Object],
                                            _eventsCount: 9,
                                            _maxListeners: undefined,
                                            _writableState: [Object],
                                            writable: false,
                                            allowHalfOpen: false,
                                            destroyed: true,
                                            _bytesDispatched: 587,
                                            _sockname: null,
                                            _pendingData: null,
                                            _pendingEncoding: '',
                                            server: null,
                                            _server: null,
                                            parser: null,
                                            _httpMessage: [Circular],
                                            read: [Function],
                                            _consuming: true,
                                            write: [Function: writeAfterFIN],
                                            _idleNext: null,
                                            _idlePrev: null,
                                            _idleTimeout: -1 },
                                            _header: 'POST /json HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: Needle/1.0.0 (Node.js v6.11.3; darwin x64)\r\nContent-Length: 373\r\nContent-Type: application/json; charset=utf-8\r\nHost: localhost:8585\r\nConnection: close\r\n\r\n',
                                            _headers: 
                                            { accept: 'application/json',
                                              'user-agent': 'Needle/1.0.0 (Node.js v6.11.3; darwin x64)',
                                              'content-length': 373,
                                              'content-type': 'application/json; charset=utf-8',
                                              host: 'localhost:8585' },
                                              _headerNames: 
                                              { accept: 'Accept',
                                                'user-agent': 'User-Agent',
                                                'content-length': 'Content-Length',
                                                'content-type': 'Content-Type',
                                                host: 'Host' },
                                                _onPendingData: null,
                                                agent: 
                                                Agent {
                                                  domain: null,
                                                  _events: [Object],
                                                  _eventsCount: 1,
                                                  _maxListeners: undefined,
                                                  defaultPort: 80,
                                                  protocol: 'http:',
                                                  options: [Object],
                                                  requests: {},
                                                  sockets: [Object],
                                                  freeSockets: {},
                                                  keepAliveMsecs: 1000,
                                                  keepAlive: false,
                                                  maxSockets: Infinity,
                                                  maxFreeSockets: 256 },
                                                  socketPath: undefined,
                                                  timeout: undefined,
                                                  method: 'POST',
                                                  path: '/json',
                                                  _ended: true,
                                                  parser: null,
                                                  res: [Circular] },
                                                  raw: <Buffer 7b 22 72 65 73 70 6f 6e 73 65 22 3a 7b 22 65 78 63 65 70 74 69 6f 6e 22 3a 7b 22 5f 5f 74 79 70 65 22 3a 22 55 73 65 72 45 78 63 65 70 74 69 6f 6e 22 ... >,
                                                  body: { response: { exception: [Object] } },
                                                  bytes: 134,
                                                  read: [Function],
                                                  parser: 'json' }

**Comment by halmsx** [comment]
tag

**Comment by rubendel** [comment]
That's a bit much, too much to get something useful out of.
