### ISSUE TITLE
BIMvie.ws

### ISSUE THREAD

**Issue by boubechtoula** [opensourceBIM/BIMserver#615]
I have php aplication and i want to use BIMvie.ws in it.
 it'is posssible to do that ?
 and how i can do that ?**

**Comment by rubendel** [comment]
PHP is a serverside technology, BIMvie.ws is completely clientside, so I don't understand your question.

**Comment by boubechtoula** [comment]
OK forgetting PHP my problem is the following  :
how can i use bimvie.ws without installing it as blogin on the bimserver?
because I want to make changes in its source code (to adapt it to my needs).
and when I installed it directly with bimserver like blogin (it works fine) but I can not change the code of bimvie.ws!

so what exactly do I want is to take bimvie.ws and modify it for my needs and do tests on bimserver to see the changes ??
thank you for replying.

**Comment by rubendel** [comment]
Just copy all the BIMvie.ws source code to a place a webserver can serve. Then modify settings.js to your needs.
