### ISSUE TITLE
changing data on bimserver

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#616]
Hi, i am trying to manipulate data on an ifc file on bimserver.
according to api documentation i did:
{
  "token": "sometoken",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "setBooleanAttributes", 
    "parameters": {
      "tid": **number of started transaction**,
      "oid": **one wall object**,
      "attributeName": "**IsExternal**",
      "values": [<<boolean, A list of boolean values>>] **"set to false**"
    }
  }
}

response:
{
  "response": {
    "result": {}
  }
}
after that i commited the transaction.
obviously i did something wrong as i received no result.
what did i miss?

i know that is not a professional's question, but i am trying since days to find an answer myself.
maybe one knows mor insight documentation i could / should consult
thanks peter

**Comment by rubendel** [comment]
IsExternal is not an attribute of "IfcWall" [1]. "IsExternal" is a well known property of objects, for that you'd need to create the appropriate IFC objects like "IfcPropertySet" and "IfcProperty".

[1] http://iaiweb.lbl.gov/Resources/IFC_Releases/R2x3_final/ifcsharedbldgelements/lexical/ifcwall.htm

**Comment by epeter-** [comment]
ok, my error.
but studying the api i didn't find a command to change a data object like "IsExternal" from false to true?
again what am i missing?
