### ISSUE TITLE
How to install plugins from internet?

### ISSUE THREAD

**Issue by RazorWang** [opensourceBIM/BIMserver#618]
I am wondering how to use "Available Plugin Bundles" in BIMViews to install plugins online.

It throws an error message:
Missing parameter: installPluginBundleFromUrl -> installAllPluginsForAllUsers

So I used the PluginInterface.installPluginBundleFromUrl API in Console page. 
But where can I find the plugin's url for installation.
Can anyone show me a demo url?

**Comment by rubendel** [comment]
The URL just has to point to a location where you host your own plugin. All other plugins are available via the registry, so no need to use installPluginBundleFromUrl.

**Comment by rubendel** [comment]
![installplugin](https://user-images.githubusercontent.com/377978/31164209-632776ea-a8e6-11e7-86e8-3d147f88d61a.png)
