### ISSUE TITLE
Your email address has not been validated yet

### ISSUE THREAD

**Issue by boubechtoula** [opensourceBIM/BIMserver#619]
Hello,
can I disable (remove) confirmation of email address after registration?
if yes, where i can change in the bimvie.ws (source) or in the bimserver(source) ?

**Comment by rubendel** [comment]
Yes, it's a server settings and you can find it in BIMvie.ws, it's called "Send confirmation email after registration"

**Comment by boubechtoula** [comment]
ok, thanks
