### ISSUE TITLE
setStringAttribute

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#621]
i query my ifc file for the NominalValue of an String Attribute:
`{

  "token": "8e57e63966df7f466a76db704fab49ff31d3ae0bcd00b40c8ff338b2bc792d307a4d358c99123d8f5f0dbbaa785e73ae",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "getStringAttribute", 
    "parameters": {
      "tid": 4,
      "oid": 4326051,
      "attributeName": "NominalValue"
    }
  }
}`
results as expected:
`{
  "response": {
    "result": "C25/30"
  }
}`

when i try to change the StringAttribute:
1) 1 start a transaction
2) i set attribute like:
`{
  "token": "8e57e63966df7f466a76db704fab49ff31d3ae0bcd00b40c8ff338b2bc792d307a4d358c99123d8f5f0dbbaa785e73ae",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "setStringAttribute", 
    "parameters": {
      "tid": 4,
      "oid": 4326051,
      "attributeName": "NominalValue",
      "value": "Test"
    }
  }
}`

resulting in:

`{
  "response": {
    "result": {}
  }
}`

3) committing the transaction:

`{
  "response": {
    "exception": {
      "__type": "UserException",
      "message": "No attribute with the name \"NominalValue\" found in class \"IfcPropertySingleValue\""
    }
  }
}`

Why that???????

**Comment by epeter-** [comment]
my question is still pending!
why isn't it possible to change an read attribute as described before?????????????????????

**Comment by rubendel** [comment]
You need to call setWrappedAttribute, this way you can also tell BIMserver what the type is of the NominalValue (how else would it know?). Normally the amount of unnecessary question marks is inversely proportional to the speed of answering questions, so this is an exception...

**Comment by epeter-** [comment]
thank you!
both for replying and speed!
peter

Am 2017-10-04 9:17, schrieb Ruben de Laat:
