### ISSUE TITLE
validate Account

### ISSUE THREAD

**Issue by boubechtoula** [opensourceBIM/BIMserver#623]
I want to validate the accounts of new users automatically without doing requestPasswordChange
to do this I try to use this function:
Global.bimServerApi.callWithFullIndication ("AuthInterface", "validateAccount", {uoid: uoid, token: validationtoken, password: password}, function
$ (".indexcontainer") load (Global.baseDir + "login.html", function () {
new Login (address, username);
});
});
but the parameter token (validationtoken) I did not understand how I generate it ????

**Comment by rubendel** [comment]
The whole idea of the validation token is that it can only reach a user via email, thus enforcing a validated email address. You can however call "changePassword", if you do that as an administrator, you won't need the old password (just pass _null_), the account will be validated after that.

**Comment by boubechtoula** [comment]
ok thanks.
