### ISSUE TITLE
new release .86 bimviews not starting

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#625]
installed new war on ubuntu 16.04 and tomcat 8
console running fine.
bimviews will hang at loginscreen

**Comment by rubendel** [comment]
What do you mean with console running fine? Are there any error messages in the BIMserver log? In the browser's development console?

**Comment by nabiljebar** [comment]
hi I have the same issue.

No  error messages in the BIMserver log
no  error messages  in the browser's development console

CentOS release 6.5 (Final)
tomcat 8

**Comment by epeter-** [comment]
there are no error messages.
@ first start you enter user and password, select what shall be 
installed.
everything is installing - bimviews too.
then you get the message to start bimviews.
next screen shows up. message: loading.

that was it.

when accessing the bimserver console: the console app starts as it 
should.

no log created

best
peter

Am 2017-10-10 13:32, schrieb Ruben de Laat:

**Comment by rubendel** [comment]
There was a bug in 1.5.86 with the websockets, there should have been a clear error in the BIMserver log file about websockets not being configured right, but anyways... A new release is in the making, but the maven repository we use has some timeout problems at the moment, so could be a few days. Fix will be in 1.5.88.

**Comment by epeter-** [comment]
thank you!


Am 2017-10-11 11:46, schrieb Ruben de Laat:
