### ISSUE TITLE
DIRECTORY LISTING IMFORMATION DISCLOSURE

### ISSUE THREAD

**Issue by prasanna15540** [opensourceBIM/BIMserver#626]
Dear sir/mam,

i have found a directory listing bug in the particular url:
http://bimserver.org/wp-includes/js/
http://bimserver.org/wp-includes/Requests/
http://bimserver.org/wp-includes/IXR/
http://bimserver.org/wp-includes/ID3/
http://bimserver.org/wp-includes/certificates/
http://bimserver.org/wp-includes/Text/

SECURITY IMPACT:

An attacker can see the files located in the directory and could potentially access files which disclose sensitive information.

ACTIONS TO TAKE :

1.Change your server configuration file. A recommended configuration for the requested directory should be in the following format:

<Directory /{YOUR DIRECTORY}>
	Options FollowSymLinks 
</Directory>

2.Remove the Indexes option from configuration. Do not forget to remove MultiViews, as well.
3.Configure the web server to disallow directory listing requests.
4.Ensure that the latest security patches have been applied to the web server and the current stable version of the software is in use.

HTTP REQUEST SENT :
GET /wp-includes/js/jquery/ HTTP/1.1
Host: bimserver.org
Cache-Control: no-cache
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.16 Safari/537.36
Accept-Language: en-us,en;q=0.5
Cookie: PHPSESSID=160iegrn5ml3l0317heu5k2ml0
Accept-Encoding: gzip, deflate

please patch this vulnerability as soon as possible.

thanking you,
PRASANNA DASH

**Comment by rubendel** [comment]
This github issue tracker has nothing to do with the website you reference
