### ISSUE TITLE
JSON-Query

### ISSUE THREAD

**Issue by Xsoiou** [opensourceBIM/BIMserver#627]
Hello. I have a problem understanding the JSON-Querys implementet on the BIM Server. [Wiki](https://github.com/opensourceBIM/BIMserver/wiki/JSON-Queries)

Currently we are trying to setup a bimviewer using BimSurfer with BimServer 1.5.85. 
We have a very large BIM model that contains over 50 IFC files. Since the building is so large there is no way we can download and render the whole thing inside a browser or phone. 

My plan is to just download and render a IfcSpace and all the objects that are within the IfcSpaces BoundingBox. I have tried many different solutions, but it still does not work. 

Here is one the queries I have been using, and it gives me the IfcSpace and all IfcFurnishingElement and IfcBuldingElementProxy that relates to the space, but nothing else.

Query: 
```
 {               
                 defines: {
                    Representation: {
                        type: "IfcProduct",
                        fields: ["Representation"]
                    },
                    ContainsElementsDefine: {
                        type: "IfcSpatialStructureElement",
                        field: "ContainsElements",
                        includes: [
                            {
                                type: "IfcRelContainedInSpatialStructure",
                                field: "RelatedElements",
                                includes: [
                                    "ContainsElementsDefine",
                                    "Representation"
                                ]
                            }
                        ]
                    },
                    IsDecomposedByDefine: {
            			type: "IfcObjectDefinition",
            			field: "IsDecomposedBy",
            			include: {
            				type: "IfcRelDecomposes",
            				field: "RelatedObjects",
            				includes: [
            					"IsDecomposedByDefine",
            					"ContainsElementsDefine",
            					"Representation"
            				]
            			}
            		}
                },
                queries: [
                    {
                        oids: [1709245301], // oid of the IfcSpace
                        includes: [
                            "ContainsElementsDefine"
                        ]
                    }
                ]
            }
```

Any help, or pointing to the right query to do such a thing would be really helpful.

**Comment by rubendel** [comment]
Just to be clear, with "it gives me the IfcSpace and all IfcFurnishingElement and IfcBuldingElementProxy that relates to the space, but nothing else." What else do you expect to be shown?

**Comment by ArthurSkaug** [comment]
Hi, thanks for reply. 

What i want is to show all objects that is inside the IfcSpace boundingBox. This is IfcWalls, IfcSlabs etc. But restricted to the BoundingBox of the IfcSpace. ( So we dont download and render a lot of unnecessary objects ) 

I know my query is wrong, but i hope maybe there is a way to query a ifcSpace and then ( in some way ) figure out what objects that "should" be present inside the IfcSpace.

**Comment by rubendel** [comment]
Ah that's interesting. At the moment you are limited to the amount of information that is in the model. You are already using the containment of objects, but in most IFC files the containment relation is limited to furniture/piping/ducts etc...

Depending on your model, you might be able to get better results if you also include the space boundaries. Those are in the IfcRelSpaceBoundary relation and from IfcSpace they are linked using the "BoundedBy" reference.

Another route you could take is the following. Query just the IfcSpace you are interested in. In the results of that query is going to be a field "geometry", this object contains the "minBounds" and "maxBounds" fields.

> You might be able to skip the previous step if you already loaded the model before

Those two arrays describe (as the name implies) the minimum bounds and maximum bounds of the (axis aligned) bounding box. You can use this information in a spatial query that is probably not described in the wiki, the following example is taken from the BIMvie.ws examples:

```json
{
  "type": "IfcFurnishingElement",
  "inBoundingBox": {
    "x": 0,
    "y": 0,
    "z": 0,
    "width": 5,
    "height": 5,
    "depth": 5
  }
}
```

If you substitute the x, y, z values and width, height and depth values with the appropriately converted values from the minBounds/maxBounds arrays you should get all objects within the given space. This will do a spatial query on the _generated_ geometry, so on the actual triangles. You can also add the "partial" attribute do include/exclude partially contained objects.

Of course it would be nice if you could do this in just one step with the query language, but that's not possible at the moment, maybe later.

Hope this sort of makes sense.
