### ISSUE TITLE
x.getbimserveraddress returns localhost on server

### ISSUE THREAD

**Issue by felixh85** [opensourceBIM/BIMserver#628]
Hi,
I apologize in advance because I think this topic came up already more then once but when I searched for my problem, I could not find the answer. I want to state in advance that I am not very familiar with server administration.
 
I want to deploy the Bimserver version 1.5.88 on my Tomcat server. After the deploy, when I open the Bimserver in the browser (www.mydomain.de/bimserver) I only see "Loading..." on the page.
This is because  http://www.mydomain.de/bimserver/x.getbimserveraddress returns {"address":"http://localhost:80/bimserver"} instead of {"address":"http://mydomain:80/bimserver"} which results in an error in the request http://localhost/bimserver/json .
My question: where do I have to make changes that x.getbimserveraddress returns my domain instead of localhost. I already changed the server.xml of my Tomcat (Engine -> defaultHost = mydomain and Host -> name=mydomain).
What I read in the posts was that I have to change ther "Server settings". Is this related to bimserver or the Tomcat? Where do I find these settings to make the changes.
Thank you for your support.

**Comment by rubendel** [comment]
The x.getbimserveraddress will always return the value configured in the BIMserver database. This value can be configured in three ways:
- During setup (Site address)
- Using BIMvie.ws (Server | Server Settings | Site address)
- Calling the API method SettingsInterface.setSiteAddress

The "setup" page is the easiest, waybe you went through it without setting the right address? "The address your BIMserver will be available from. It will be pre-filled, but this is not necessarily the right address. If you are using a domain name, make sure to use it here."

**Comment by felixh85** [comment]
Hi Ruben,
thank you for your answer.
My Problem is that I am not getting to the setup where I can enter my Site Address. When I am working locally and I deploy Bimserver I am getting to the Setup Page without a problem. Probably because it returns localhost. Now, I am deploying the bimserver.war for the first time on an external server and I am getting this problem.
After I moved the bimserver.war to the webapps folder and I see in the catalina.out that the bimserver has been deployed successfully, I open bimserver in the browser (www.mydomain.de/bimserver), expecting to perform the Setup steps where I enter the admin credentials and the site address. Unfortunately, the setup page never shows. I only see the "Loading..." on the page and get the described error when I open the developer console in chrome and check the tab "Network".

**Comment by rubendel** [comment]
Hmm I cannot reproduce this (on a remote server), but the only difference here might be that I am not running it on a subpath (/bimserver). Can you try deploying it as "ROOT.war", so it will run on "www.mydomain.de" directly to see if that works?

**Comment by felixh85** [comment]
I am still getting the same error when I deploy it as ROOT.war
It happens when in the index.html the following Code is executed:
` 
var Global = {};	
		$.getJSON("x.getbimserveraddress", function(data){
			Global.api = new BasicApi(data.address)
			Global.api.call("AdminInterface", "getServerInfo", {}, function(serverInfo){
				var state = serverInfo.serverState;
				if (state == "NOT_SETUP") {
					$(".indexcontainer").load("setup.html", function(){
						new Setup($(this), window.location.href);
					});
				} else {
					$(".indexcontainer").load("status.html", function(){
						new Status($(this), serverInfo);
					});
				}
			});
		}).fail(function(){
		});
`

**Comment by felixh85** [comment]
I edited the index.html file and hardcoded my domain name to ` Global.api = new BasicApi('mydomain.de/bimserver');` Now I am getting a 404 Response because the Link which is generated to request the server status is wrong. It generates a link like http://www.mydomain.de/bimserver/mydomain.de/bimserver/json
I compared the requests from my local domain with my server doamin. This request should look like 
http://www.mydomain.de/bimserver/json.  But when I open this link I get a 500 HTTP Error Code. Could it be that my bimserver application is not properly started? I am not seeing any error in the bimserver.log

**Comment by felixh85** [comment]
I still did not manage to find a solution for this problem. I found a temporary fix where I made the setup on my local server (entered there the site address of my domain) and exchanged the WEB-INF folder in the .war file. This way I am able to use the bimserver via the Bimserver Client Application but the BIMvie.ws ist not working properly. I am getting an exception when www.mydomain.de/bimserver/stream is called by the bimserverapi JS script. Any suggestions?
I was thinking, that maybe this is still related to a wrong configuration of my server. When the WAR file is deployed a database is generated. You said that the x.getbimserveraddress is read from the database. Which value for x.getbimserveraddress do you enter before the server is setup (immidiately after the deploy). Do you call some method (maybe this method returns the wrong value because of the misconfiguration of my server) or do you enter "localhoast" as server by default. If you use a method, it would explain why you cannot reproduce it because your server is configured in the right way.

**Comment by felixh85** [comment]
I was able to resolve my issue. As I guessed in my last post it was related to my server configuration. I have an Apache in front of my Tomcat where I perform a redirect. Because I wrote localhost in my rewrite rule in my .htaccess file the method getServername returned localhost. By adding ProxyPreserveHost On to the httpd.conf file of my Apache the issue was resolved.

**Comment by pierrejoye** [comment]
One question:

Why is it needed to store the IP address of the server?

Something is wrong in how it is handler. I use docker,  name servers are used, but BIMserver stores a fixed IP in the config, which does not match (can change on containers restarts, same if it was any kind of hosts/VM).

The setup I use is a nginx as reverse proxy to BIMserver (cache and bugs in BIMvie.ws JS and co paths).

**Comment by rubendel** [comment]
There is no need to store the IP address, where did you see that?

**Comment by pierrejoye** [comment]
Hi Ruben,

Thanks for your reply! 

Whether it is the IP or the actual host name makes little difference in this case. felixh85  explained a case where it has issues and I had the same issues. Also there are plenty of cases where a host can change its address. Is there any technical reason to require it being saved? 

From a frontend point of view, it does not seem necessary as it could rely by default on the current host and path (what I basically know for the Web frontend.

On a side note, the main reason why I use a proxy in front of it is the version of tomcat used. It is not safe to use anymore and I rather prefer to prevempt any issue and add some request filters on top instead of exposing it directly (see https://tomcat.apache.org/tomcat-80-eol.html). The other reason is to stop having to worry about that site address :)

**Comment by rubendel** [comment]
This was indeed not logical. The reason for it working like this was that for some reason people like to run BIMserver on a non-root context-path (e.a. http://host:port/[context]), probably because that's the default in Tomcat. There was no other way for a client to determine the real BIMserver location, or so I thought, we now simply try to recognize the last part of the URL (/apps/[appname]), which works much better.

So in short, this has changed in 1.5.125. The SiteAddress is not used anymore for these purposes. Also x.getbimserveraddress is not used anymore (by Console, BIMvie.ws and BIMsurfer 3) and will be removed in the next version altogether.

You can use Tomcat 8.5 no problem. Putting a proxy in front of something does not all of a sudden make it safe. All data can still pass through and same sorts of hacks can be applied, only a very small attack vector is removed from the equation.

**Comment by pierrejoye** [comment]
On Mon, Mar 11, 2019, 10:40 PM Ruben de Laat <notifications@github.com>
wrote:

> This was indeed not logical. The reason for it working like this was that
> for some reason people like to run BIMserver on a non-root context-path
> (e.a. http://host:port/[context]), probably because that's the default in
> Tomcat. There was no other way for a client to determine the real BIMserver
> location, or so I thought, we now simply try to recognize the last part of
> the URL (/apps/[appname]), which works much better.
>
> So in short, this has changed in 1.5.125. The SiteAddress is not used
> anymore for these purposes. Also x.getbimserveraddress is not used anymore
> (by Console, BIMvie.ws and BIMsurfer 3) and will be removed in the next
> version altogether.
>

Very nicke thanks :)

> You can use Tomcat 8.5 no problem. Putting a proxy in front of something
> does not all of a sudden make it safe. All data can still pass through and
> same sorts of hacks can be applied, only a very small attack vector is
> removed from the equation.
>
Indeed. Also it is a bit more than a simple proxy. I will try 8.5 again, my
last attempt was not so successful.
