### ISSUE TITLE
Querying all metadata from BIMserver

### ISSUE THREAD

**Issue by miolfo** [opensourceBIM/BIMserver#629]
Hello,

I have a question regarding how to query some of the metadata that is visible in the bimvie.ws. For example, when I select one of the objects in an ifc model, I can see properties as follows in the bimvie.ws:
![image](https://user-images.githubusercontent.com/5992841/31724153-9b1af678-b429-11e7-93ed-dbcdbfc7ad21.png)

How can I query the properties such as the "Tekla Reinforcement" from the server? I found no information about it on the wiki, and I went through all of the JSON queries in the Console -application, but I couldn't find a query that can be used for getting the values in the image.

Regards,
Mikko Forsman

**Comment by rubendel** [comment]
The screenshot seems to be from BIMvie.ws. That project is open source, so your best guess is to have a look at how it's done there. Basically what you do is:
- Create a query that will get you the objects and their properties
- Traverse the resulting graph to find you properties

There are no special API calls for getting IFC properties. In IFC, properties are just objects, BIMserver does not treat them any differently than any other object.
