### ISSUE TITLE
New install v1.5.88, unable to load any model

### ISSUE THREAD

**Issue by bastienmenis** [opensourceBIM/BIMserver#630]
I just installed the latest version. I am able to upload a model through the embedded BIMvie.ws, but I am unable to load any geometry. I can expand the tree and see all the properties, so it looks like the model was deserialised properly.

I tried the same from BIMsurfer (lastest) and same issue. The tree gets downloaded but no geometry is sent. I only receive the first 64 bytes on the websocket (starting frame) then nothing.

Can you provide any guidance to help to troubleshoot?

Edit: Here are the API queries, in order, from the browser debug window:
Request: /download?token=[...]
Response: { objects: [...] } (array of 1632 objects)

Request: /json
Request payload: {"request":{"interface":"org.bimserver.PluginInterface","method":"getSerializerByPluginClassName","parameters":{"pluginClassName":"org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializerPlugin3"}},"token":"473c48517d93a97e786f581edf4e239a59257cc296a630afa5eb555e6655529bd73cb7dc4f6c1e69d8eeafca0da55794"}
Response: {"response":{"result":{"__type":"SMessagingSerializerPluginConfiguration","description":"BinaryGeometryMessagingStreamingSerializer3","enabled":true,"name":"BinaryGeometryMessagingStreamingSerializer3","objectIDMId":-1,"oid":526171,"pluginDescriptorId":1835062,"renderEngineId":-1,"rid":1,"settingsId":3539027,"streaming":true,"userSettingsId":-1}}}

Request: /json
Request payload: {"request":{"interface":"org.bimserver.ServiceInterface","method":"download","parameters":{"roids":[196611],"query":"{\"type\":\"GeometryInfo\",\"oids\":[],\"include\":{\"type\":\"GeometryInfo\",\"field\":\"data\"}}","serializerOid":526171,"sync":false}},"token":"473c48517d93a97e786f581edf4e239a59257cc296a630afa5eb555e6655529bd73cb7dc4f6c1e69d8eeafca0da55794"}
Response: {"response":{"result":82}}

Request: /json
Request payload: {"request":{"interface":"org.bimserver.NotificationRegistryInterface","method":"registerProgressHandler","parameters":{"topicId":82,"endPointId":28}},"token":"473c48517d93a97e786f581edf4e239a59257cc296a630afa5eb555e6655529bd73cb7dc4f6c1e69d8eeafca0da55794"}
Response: {"response":{"result":{}}}

Request: /json
Request payload: {"request":{"interface":"org.bimserver.NotificationRegistryInterface","method":"getProgress","parameters":{"topicId":82}},"token":"473c48517d93a97e786f581edf4e239a59257cc296a630afa5eb555e6655529bd73cb7dc4f6c1e69d8eeafca0da55794"}
Response: {"response":{"result":{"__type":"SLongActionState","end":null,"errors":[],"infos":[],"oid":-1,"progress":-1,"rid":0,"stage":1,"start":1508358920597,"state":"STARTED","title":"Done preparing","warnings":[]}}}

**Comment by rubendel** [comment]
Is the default render engine for your user "Ifc Open Shell"?

**Comment by bastienmenis** [comment]
Yes it is. I also tried the other render engine with the same result.

**Comment by rubendel** [comment]
Did you checkin the file when the right render engine was selected?

**Comment by bastienmenis** [comment]
Ha, maybe that was the issue. I didn't realise that the render engine had an effect during check in. I actually re-installed BIMsurfer and it is working fine now
