### ISSUE TITLE
Install a serializer

### ISSUE THREAD

**Issue by frodooon** [opensourceBIM/BIMserver#631]
Hello,

How do you manually install a serializer from within Bimviews? I'd like to install BIMServerOsmSerializer (https://github.com/BIMDataHub/BIMServerOsmSerializer/releases)
I'm using the latest BIMserver version (1.5.86), and if I'm not mistaken I can't simply add the jar file into the plugin folder (?)

Thanks a lot for any advice!!

Arnaud.

**Comment by rubendel** [comment]
This plugin was probably built for version 1.4 of BIMserver. In that version you could actually copy/paste the plugin to a folder. In 1.5 this has changed, you now have to install plugins using BIMvie.ws (or the BIMserver API if you feel adventurous). A plugin for 1.5 has to specifically be built for 1.5 or else it won't work.

**Comment by frodooon** [comment]
Hello, 
Actually it's even for BIMserver **1.3.4**., which I downloaded. In that version of BIMserver you can just paste the .jar file in the plugin folder, right? Because when I put the Bimviews jar file in the plugin folder for BIMserver 1.3.4, Bimviews isn't loaded at startup, I got just a page telling me that I can download Bimviews. See the picture.
![bimserver134](https://user-images.githubusercontent.com/32676510/31807742-37362392-b570-11e7-862e-7064aa22d9ee.jpg)
I did try to install earlier versions of BIMserver, including the ones that were released on the same period or a bit earlier. Am I missing something?

Thanks a lot,
Arnaud

**Comment by rubendel** [comment]
Wow that's very old software. Yes you should be able to put the plugin.jar in the plugin folder. You definitely would need an old version of BIMvie.ws as well. Other than that, if there are no error messages, I don't really remember what could be the issues in such an old version.

**Comment by frodooon** [comment]
Yep, it's old ;) Ok no worries, thank you for the quick replies!
