### ISSUE TITLE
How to implement BIM diagram on JavaScript client

### ISSUE THREAD

**Issue by wxxtqk** [opensourceBIM/BIMserver#632]
requirejs.config({
	    baseUrl: address + "/js", // address should be the address of your bimserver, including optional port
	    urlArgs: "bust=" + version // the version you use here will be used for caching
	});

	requirejs(["bimserverapi_BimServerApi", "bimserverapi_BimServerApiPromise"], function(BimServerApi, BimServerApiPromise) {
		if (address.endsWith("/")) {
			address = address.substring(0, address.length - 1);
		}
		if (BimServerApi != null) {
			var bimServerApi = new BimServerApi(address, notifier);
			bimServerApi.init(function(){
				// This function gets called on success, you can use bimServerApi now
			});
		} else {
			// error
		}
	}, function (err) {
		// Error
	});

i think this demo code is not  complete，can you give me a detailed document

**Comment by rubendel** [comment]
Would be useful if you would tell is where this example comes from. If you are trying to run on NodeJS or similar, that's not working at the moment.
