### ISSUE TITLE
BIMserver can import ifc model but can't render it

### ISSUE THREAD

**Issue by cnyzgkn** [opensourceBIM/BIMserver#635]
I am able to importifc model using latest version of BIMserver and BIMvie.ws, but can't render the model.

Clicking the eye, the console shows: preload the model successfully, but after clicking the eye icon, no model is loaded at all:
![image](https://user-images.githubusercontent.com/5706598/31982854-3e7a67c8-b98d-11e7-8d94-0632eb266037.png)

if I click the query itself, the console showed:

_Uncaught TypeError: object.getGeometry is not a function
    at Properties.selected (eval at globalEval (bimviews.js?_v=0.0.87:338), <anonymous>:59:11)
    at eval (eval at globalEval (bimviews.js?_v=0.0.87:338), <anonymous>:45:4)
    at Array.forEach (<anonymous>)
    at EventRegistry.trigger (bimviews.js?_v=0.0.87:16470)
    at Project.selected (eval at globalEval (bimviews.js?_v=0.0.87:338), <anonymous>:44:25)
    at Node.ProjectTree.treeItemClick [as onClick] (eval at globalEval (bimviews.js?_v=0.0.87:338), <anonymous>:265:11)
    at Node.linkClick (bimviews.js?_v=0.0.87:15441)
    at HTMLAnchorElement.dispatch (bimviews.js?_v=0.0.87:4732)
    at HTMLAnchorElement.elemData.handle (bimviews.js?_v=0.0.87:4544)_

![image](https://user-images.githubusercontent.com/5706598/31983372-a3c312e0-b98f-11e7-9818-79b4efe4651b.png)

I also tried to switch to another render engine, but it seems the list menu can't be selected at all:
![image](https://user-images.githubusercontent.com/5706598/31982920-6de5b74c-b98d-11e7-9350-9997d576557f.png)

1. How can I render the imported ifc model? 
Shall I switch to different versions of plugins?

Now I am using these versions:
bimserverapi-0.0.121
bimsurfer-0.0.42
bimviews-0.0.87
binaryserializers-0.0.27
console-0.0.10
ifcengine-0.0.16
ifcopenshellplugin-0.5.24
ifcplugins-0.0.32

2. I found similar plugins inside https://oss.sonatype.org/content/groups/public/org/opensourcebim/
IfcEngine vs ifcengine
IfcOpenShellPlugin vs ifcopenshellplugin
..
What's the difference?

**Comment by rubendel** [comment]
**IfcEngine**
IfcEngine seems to not be actively developed anymore. I have updated the wiki page of the plugin and removed it from the repository project (https://github.com/opensourceBIM/BIMserver-Repository/blob/master/plugins.json), so it won't show up anymore.

**Regenerate geometry**
This functionality is not implemented yet

**Changing the render engine**
You can change the render engine under User Settings | Render Engines. Most probably simply the "NOP" renderer is selected, which is a renderer that does nothing (NO Operation). After you change the default render engine, you need to checkin again.

**Comment by rubendel** [comment]
Just an update to these issues.

**IfcEngine**
Has now been removed from the repository

**Regenerate geometry**
Has now been implemented, will be available in the next release

**Default render engine**
The default render engine is now always IfcOpenShell (if it's available)
