### ISSUE TITLE
Hello, please upload the IFC file, there is no corresponding string device, how to solve?

### ISSUE THREAD

**Issue by lustres159** [opensourceBIM/BIMserver#637]
Hello, please upload the IFC file, there is no corresponding string device, how to solve?

**Comment by lustres159** [comment]
Sorry, you can get the serializer after you download the plugin. Now I have a new problem: I don't have eyes after importing the IFC file, and how do I see it 3D rendering?

**Comment by lustres159** [comment]
It has been solved by myself, thank you. But encounter new problems: rendering problems, only lines

**Comment by rubendel** [comment]
Please create a new issue for new issues. A little more info would be useful.
