### ISSUE TITLE
Can we have option to delete project permenently via admin login ?

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#64]
Hello,

I am looking for a solution of permanently deletion of the projects on disk.  Can we delete project permanently via system or from installed BIMServer directory ?? If  via system directory then can you tell me which folder to delete on that path? 

Please let me know if we can achieve this then.

**Comment by tomvanoost** [comment]
We are also in need of this feature (permanent project deletion). Like vpanchal we want to use the base of BIMserver as a viewer for IFC files (in combination with BIMsurfer). For this we need clean-up or delete operations on project level.
I can also imagine that in test environments it is very useful to have this feature.
Permanent deletion of a project could be limited, for example no deletion possible when the project is branched.

**Comment by rubendel** [comment]
For these purposes you don't really need BIMserver, just use one of the available Ifc Engines to convert IFC to usable geometry and then feed that to a WebGL viewer. But I'll discuss with more people as this has been requested multiple times now.

**Comment by tomvanoost** [comment]
Our current implementation works like this, we just convert each IFC file into a format compatible with WebGL. And show that to the end-user.
The reason to use BIMserver for this:
- view a combination of multiple IFC files in one viewer;
- query the IFC database to give the user more information.
Probably this can be achieved somehow without BIMserver, but I think it's (a lot) more work. We will have to merge multiple IFC files in one WebGL geometry.
BIMserver+BIMsurfer provides these features out-of-the-box.
