### ISSUE TITLE
What's the difference between 1.4 and 1.5?

### ISSUE THREAD

**Issue by RafaelLei** [opensourceBIM/BIMserver#641]
I'm wonder about the difference between 1.4 and 1.5?For me ,i think that bimserver1.4 is more convenient than 1.5.

**Comment by rubendel** [comment]
1.4 is considered the latest stable release, it has it's bugs though. 1.5 has been in development for a while not, but not yet released as the new stable version. It's main features include:
- Less memory used
- A language to query the model by filtering
- Plugins can now be installed via the API, no need to download files yourself
- Generating geometry is multicore and overall faster
