### ISSUE TITLE
How to get a snapshot of the 3D model area?

### ISSUE THREAD

**Issue by zhutianrui** [opensourceBIM/BIMserver#642]
I just put the 3D model area to my own home page, and the model shows correct. 
But when I try to get a snapshot of the model by taking a snapshot of the canvas,  
it just returns an empty image to me. 
Is anybody knows how to take a 3D model snapshot from the 3D model area?
It would be very thankful if anybody can give me some advise or sample source codes.

--Best Regards

**Comment by rubendel** [comment]
Not a BIMserver issue, if you are using BIMsurfer, try the issue tracker of that project.
