### ISSUE TITLE
Tomcat 9.0 error

### ISSUE THREAD

**Issue by RafaelLei** [opensourceBIM/BIMserver#643]
I put bimserver.war in tomcat,and i can access the service normally .But the computer in  local area network cannot acess my bimserver , but they can access my tomcat. What's wrong with my tomcat or my bimserver? 
![qq 20171103103005](https://user-images.githubusercontent.com/33283197/32358563-06856506-c082-11e7-96fe-e9c37c53d8aa.png)
![qq 20171103103012](https://user-images.githubusercontent.com/33283197/32358564-06c1710e-c082-11e7-83c8-9af1f85582aa.png)

**Comment by rubendel** [comment]
Did you set the Site Address correctly during setup?

**Comment by RafaelLei** [comment]
I have solved my problem according to your advice,thank you very much
