### ISSUE TITLE
Where can I download to the latest jar files

### ISSUE THREAD

**Issue by RebootYX** [opensourceBIM/BIMserver#644]
I want to upload jar files myself.Where can I download to the latest jar files?
![q](https://user-images.githubusercontent.com/33157708/32360310-7e108012-c08f-11e7-8bc2-0051bcb85ed6.png)

**Comment by rubendel** [comment]
https://mvnrepository.com/artifact/org.opensourcebim?sort=popular

or

https://oss.sonatype.org/content/groups/public/org/opensourcebim/

Anything with uppercase letters in the artifact name should be ignored.
