### ISSUE TITLE
Unable to Download from Console

### ISSUE THREAD

**Issue by csydora** [opensourceBIM/BIMserver#645]
When Trying to Download through the Console I get the following error on the BIMServer Starter:

13:38:41 ERROR [Download]:                                                                                  (LongAction.java:189) 
java.lang.ClassCastException: org.bimserver.models.store.impl.ConcreteRevisionImpl cannot be cast to org.bimserver.models.store.Revision
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:109)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:57)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Unknown Source)
13:38:41 ERROR [Download]:                                                                                  (LongDownloadAction.java:62) 
java.lang.ClassCastException: org.bimserver.models.store.impl.ConcreteRevisionImpl cannot be cast to org.bimserver.models.store.Revision
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:109)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:57)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Unknown Source)

Here is the copied JSON:
`"{
  "token": "8b78d2a43557a9e679f1f64422b2090e1f8481cc8e4d8820d7eba3849467240f43438302681b88fa0c10b86dd57a0ff3",
  "request": {
    "interface": "ServiceInterface", 
    "method": "download", 
    "parameters": {
      "roids": ["65540"],
      "query": "",
      "serializerOid": 524326,
      "sync": "false"
    }
  }
}"`

Is there some step I should be taking before downloading or when I set up? The result returns the topicId but no data is downloaded in getDownloadData.
I am following the instructions in the link: https://github.com/opensourceBIM/BIMserver/wiki/Downloading-models
Please let me know if this is already addressed or solved and where I can find the solution. I am using Version 1.5.88. Thanks in advance.

**Comment by rubendel** [comment]
The roid you are sending is probably not a "roid", but a "croid" (Concrete Revision ID). Where did you get the "roid" you are sending?

**Comment by csydora** [comment]
Yes you are correct I was using the croid from `ServiceInterface.getAllRevisionsOfProject`
I changed it to oid and fixed my query and it is working now. What is the purpose of the croid? I must have assumed that it was the latest revision.
Thanks for your help!

**Comment by rubendel** [comment]
It's an internal thing. A Revision can consist of multiple ConcreteRevisions. This is for example the case when checking in a new revision in a subproject, in that case a Revision is also created in the parent project, linked to the ConcreteRevision checked in + all concrete revisions from other subprojects. The ConcreteRevisions is what's used as the unique identifier in the database, but you rarely ever need it in the API.

**Comment by re1995** [comment]
when I use get download method in console, nothing happened...what is the problem?
in BIMviews also i can't download files
