### ISSUE TITLE
BIMserver github source not working

### ISSUE THREAD

**Issue by grmc144** [opensourceBIM/BIMserver#650]
error in maven dependencies on github BIMserver source

**Comment by rubendel** [comment]
If it is not too much trouble for you, would you care sharing the error message?

**Comment by grmc144** [comment]
i attached my error file here.please help to reslove this error as soon as possible.


![bimserver_error](https://user-images.githubusercontent.com/22959292/32710638-e0f714ac-c85f-11e7-9423-49e34558100b.png)

**Comment by rubendel** [comment]
Usually right-clicking on any project having these kind of errors and selecting `Maven` | `Update project...` | `OK` will fix these errors (I would call it an eclipse bug).

**Comment by grmc144** [comment]
now its working fine..thanks for the guide

**Comment by rubendel** [comment]
NP
