### ISSUE TITLE
SSL with self-signed certificates

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#652]
I have extended `JsonBimServerClientFactory` and `JsonSocketReflectorFactory` to allow for connections over SSL to servers that present a self-signed certificate. You can specify which certificate to trust when instantiating the client factory: https://github.com/hlg/bimservershell/tree/master/src/main/java 

Maybe this could be integrated into the original factories?

**Comment by hlg** [comment]
Alternatively, instead of passing in the trusted certificate, the HttpClient could be created with `HttpClients.createSystem()` or a builder with `HttpClients.custom().useSystemProperties()`. Then the location of a Java keystore with trusted certificates can be specified via system properties `javax.net.ssl.trustStore` and possibly `javax.net.ssl.trustStorePassword`.

**Comment by rubendel** [comment]
Thansk @hlg, any chance you could provide a pull request for these upgrades?

**Comment by hlg** [comment]
Yes, I can. But since I do not understand all the design decisions there, I worried that I might not overview the consequences of certain changes and break something. Because of that I did not touch the original factories and the result is a bit awkward. You may want to review and improve the code once I have sent the request.
