### ISSUE TITLE
Too many stack frames processed ( > 100000000), probably a bug, please report

### ISSUE THREAD

**Issue by Xsoiou** [opensourceBIM/BIMserver#655]
We are getting this error when we try to checkin a relative large model. The Ifc file is 370 MB. But the strange thing is that we have a file width 430 MB and that one imports without problems. 

Anyone have an ide how to solve this issue?

Error message from the logs: 
_org.bimserver.BimserverDatabaseException: org.bimserver.BimserverDatabaseException: Too many stack frames processed ( > 100000000), probably a bug, please report_

**Comment by berlotti** [comment]
Same issue on the test server....

**Comment by rubendel** [comment]
This has been fixed on november the 11th in commit https://github.com/opensourceBIM/BIMserver/commit/8988edb039ac073ac2c14b92f23b86e77c5bb53a. It's in releases after 1.5.89 (use 1.5.92 because previous versions had logging issues).

**Comment by rubendel** [comment]
The test server had already been updated at the time of your comment @berlotti
