### ISSUE TITLE
Bimserver jar file is not starting (MacOS high sierra)

### ISSUE THREAD

**Issue by alabrazi** [opensourceBIM/BIMserver#656]
Hi,
I am unable to get bimserverjar-1.5.90.jar and other versions to work on my MacOS high sierra. This problem happened after I updated JDK version to 9. I uninstalled the JDK and installed it again. I tried many versions of JDKs 7, 8 and 9 and also many versions of JREs 7,8 and 9.
Bimserver user interface was working before installing newer version of java. However during the installation of plugins I got an error which stopped the sever. Thus I thought it is probably caused by older version of Java.

**Comment by berlotti** [comment]
Can other sites connect to your computer during the setup/installation?

**Comment by alabrazi** [comment]
I suppose yes. It is working now. I deleted Java folder and followed instructions on how to remove java from MacOS. Then installed jdk8u151. Maybe installing jdk 9 caused this issue somehow.
