### ISSUE TITLE
Migrating to another server! Help!

### ISSUE THREAD

**Issue by alfredorods** [opensourceBIM/BIMserver#659]
Hey BimServer i'm using bim server from 6 month, bim server is ok and i integrate bimSurfer in my application too, in this moment i need migrate bim server and all my projects to another server, the reason is that i've  a server with low characteristics and i'm buying a better server.. the problem is that i've a lot of projects uploaded in my current server.

I need made a backup or migration to the other server without change de ID's of projects or revisions.. is this possible? i don't wanna upgrade the bim server version. In this moment i'm working with the 1.5.76 and i think install the same version in my new Server.

Can someone tell your experiences migrating the projects and users to another server?

Thanks..

**Comment by rubendel** [comment]
Yes, just copy the whole `home` directory to that server and make sure you use the exact same version of BIMserver/plugins on the new server.
