### ISSUE TITLE
Cannot open BIMViews

### ISSUE THREAD

**Issue by tomyzhou77** [opensourceBIM/BIMserver#661]
I have installed BIMServer with working internet, All remote plugins have been installed.
But I cannot open BIMViews.
The BIMViews page is always loading BIMViews, and I get the chrome console windows error information:

Uncaught ReferenceError: BimServerClient is not defined
    at othis.loadBimServerApiFromAddress ((index):223)
    at (index):311
    at Object.success (settings.js?_v=1511433531508:60)
    at fire (bimviews.js?_v=0.0.90:3182)
    at Object.fireWith [as resolveWith] (bimviews.js?_v=0.0.90:3312)
    at done (bimviews.js?_v=0.0.90:8754)
    at XMLHttpRequest.<anonymous> (bimviews.js?_v=0.0.90:9120)

**Comment by husamettinor** [comment]
I have the same problem on my computer. I have checked all the requirements and installed version 1.5.92 following Quick Guide but the problem still continues.

**Comment by dandmanster** [comment]
I also am facing this issue, any help would be most welcome.

**Comment by stonecompass** [comment]
Same issue here.

**Comment by bdamay** [comment]
Same issue here

**Comment by kurb70** [comment]
Unfortunately, I am also affected. The web browser shows that the resources cannot be loaded. Seems to be a MIME type problem.

![screenshot 2017-11-26 um 16 01 58](https://user-images.githubusercontent.com/1941141/33241310-df4dd5a0-d2c3-11e7-8809-80574251a961.jpg)

My environment

```
Commands:
java
-Xmx8589m
-Xss2048k
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger
-classpath
.:lib:lib/javax-websocket-server-impl-9.3.7.v20160115.jar:lib/javax.ws.rs-api-2.1-m02.jar:lib/websocket-common-9.3.7.v20160115.jar:lib/quartz-2.3.0.jar:lib/aether-connector-basic-1.0.2.v20150114.jar:lib/cxf-rt-ws-policy-3.1.11.jar:lib/xmlbeans-2.6.0.jar:lib/aether-api-1.0.2.v20150114.jar:lib/commons-logging-1.2.jar:lib/cxf-core-3.1.11.jar:lib/javax.websocket-api-1.1.jar:lib/je-7.4.5.jar:lib/plexus-utils-3.0.22.jar:lib/guava-19.0.jar:lib/jetty-util-9.3.7.v20160115.jar:lib/plexus-interpolation-1.21.jar:lib/activation-1.1.jar:lib/slf4j-api-1.7.22.jar:lib/aether-util-1.0.2.v20150114.jar:lib/maven-model-3.3.9.jar:lib/commons-cli-1.3.1.jar:lib/org.apache.oltu.oauth2.common-1.0.2.jar:lib/aopalliance-1.0.jar:lib/org.eclipse.core.resources-3.8.101.v20130717-0806.jar:lib/maven-settings-3.3.9.jar:lib/javax.json-1.0.4.jar:lib/protobuf-java-2.6.1.jar:lib/jersey-common-2.26-b01.jar:lib/logback-core-1.1.9.jar:lib/junit-4.10.jar:lib/websocket-server-9.3.7.v20160115.jar:lib/jetty-http-9.3.7.v20160115.jar:lib/jetty-xml-9.3.7.v20160115.jar:lib/maven-model-builder-3.3.9.jar:lib/org.apache.oltu.oauth2.dynamicreg.server-1.0.2.jar:lib/org.eclipse.emf.ecore-2.11.1-v20150805-0538.jar:lib/websocket-servlet-9.3.7.v20160115.jar:lib/jackson-annotations-2.8.0.jar:lib/json-20140107.jar:lib/plexus-cipher-1.4.jar:lib/jetty-plus-9.3.7.v20160115.jar:lib/antlr-runtime-3.5.2.jar:lib/websocket-api-9.3.7.v20160115.jar:lib/javassist-3.12.1.GA.jar:lib/xmlschema-core-2.2.1.jar:lib/bcf-0.0.13.jar:lib/plexus-sec-dispatcher-1.3.jar:lib/cdi-api-1.0.jar:lib/commons-collections-20040616.jar:lib/javax.servlet-api-3.1.0.jar:lib/jetty-server-9.3.7.v20160115.jar:lib/maven-core-3.3.9.jar:lib/rome-utils-1.7.1.jar:lib/aether-transport-file-1.0.2.v20150114.jar:lib/antlr-complete-3.5.2.jar:lib/jackson-databind-2.8.9.jar:lib/validation-api-1.1.0.Final.jar:lib/ST4-4.0.8.jar:lib/websocket-client-9.3.7.v20160115.jar:lib/hk2-api-2.5.0-b31.jar:lib/guice-4.0-no_aop.jar:lib/jackson-core-2.8.9.jar:lib/jersey-container-servlet-core-2.26-b01.jar:lib/jettison-1.3.8.jar:lib/cors-filter-2.5.jar:lib/wsdl4j-1.6.3.jar:lib/aether-impl-1.0.2.v20150114.jar:lib/javax.annotation-api-1.2.jar:lib/asm-commons-5.0.1.jar:lib/maven-builder-support-3.3.9.jar:lib/jaxb-core-2.2.11.jar:lib/javax-websocket-client-impl-9.3.7.v20160115.jar:lib/commons-codec-1.9.jar:lib/java-getopt-1.0.13.jar:lib/jersey-client-2.26-b01.jar:lib/org.eclipse.emf.ecore.xmi-2.11.1-v20150805-0538.jar:lib/org.eclipse.emf.codegen-2.11.0-v20150806-0404.jar:lib/jersey-server-2.26-b01.jar:lib/org.apache.oltu.oauth2.client-1.0.2.jar:lib/contenttype-3.4.200-v20140207-1251.jar:lib/httpclient-4.5.1.jar:lib/jersey-guava-2.26-b01.jar:lib/jcl-over-slf4j-1.6.2.jar:lib/xml-resolver-1.2.jar:lib/org.apache.oltu.oauth2.resourceserver-1.0.2.jar:lib/osgi-resource-locator-1.0.1.jar:lib/stax2-api-3.1.4.jar:lib/c3p0-0.9.5.2.jar:lib/velocity-1.7.jar:lib/hk2-utils-2.5.0-b31.jar:lib/javassist-3.20.0-GA.jar:lib/common-3.6.200-v20130402-1505.jar:lib/javax.mail-1.5.6.jar:lib/fastutil-7.0.13.jar:lib/commons-fileupload-1.3.2.jar:lib/jetty-io-9.3.7.v20160115.jar:lib/registry-3.5.400-v20140428-1507.jar:lib/jetty-security-9.3.7.v20160115.jar:lib/jul-to-slf4j-1.7.22.jar:lib/buildingsmartlibrary-1.0.11.jar:lib/org.apache.oltu.oauth2.dynamicreg.common-1.0.2.jar:lib/javax.inject-2.5.0-b31.jar:lib/org.apache.oltu.oauth2.authzserver-1.0.2.jar:lib/commons-io-2.2.jar:lib/java-property-utils-1.9.1.jar:lib/asm-5.0.1.jar:lib/maven-settings-builder-3.3.9.jar:lib/pluginbase-1.5.92.jar:lib/hamcrest-core-1.1.jar:lib/jaxb-impl-2.2.11.jar:lib/jetty-annotations-9.3.7.v20160115.jar:lib/rome-1.7.1.jar:lib/cxf-rt-databinding-jaxb-3.1.11.jar:lib/jobs-3.6.0-v20140424-0053.jar:lib/jersey-container-servlet-2.26-b01.jar:lib/shared-1.5.92.jar:lib/jetty-servlet-9.3.7.v20160115.jar:lib/HikariCP-java6-2.3.13.jar:lib/stringtemplate-3.2.1.jar:lib/aether-spi-1.0.2.v20150114.jar:lib/org.eclipse.sisu.inject-0.3.2.jar:lib/maven-plugin-api-3.3.9.jar:lib/cxf-rt-bindings-soap-3.1.11.jar:lib/org.eclipse.jdt.core-3.9.1.v20130905-0837.jar:lib/cxf-rt-wsdl-3.1.11.jar:lib/neethi-3.0.3.jar:lib/antlr-3.5.2.jar:lib/osgi-3.10.0-v20140606-1445.jar:lib/org.apache.oltu.oauth2.dynamicreg.client-1.0.2.jar:lib/plexus-component-annotations-1.6.jar:lib/stax-api-1.0.1.jar:lib/runtime-3.9.100-v20131218-1515.jar:lib/commons-lang-2.4.jar:lib/maven-repository-metadata-3.3.9.jar:lib/hk2-locator-2.5.0-b31.jar:lib/bimserver-1.5.92.jar:lib/jersey-media-jaxb-2.26-b01.jar:lib/aether-transport-http-1.0.2.v20150114.jar:lib/aopalliance-repackaged-2.5.0-b31.jar:lib/org.eclipse.emf.codegen.ecore-2.11.0-v20150806-0404.jar:lib/gson-2.5.jar:lib/antlr-2.7.7.jar:lib/cxf-rt-ws-addr-3.1.11.jar:lib/cxf-rt-bindings-xml-3.1.11.jar:lib/jetty-webapp-9.3.7.v20160115.jar:lib/jdom2-2.0.6.jar:lib/plexus-classworlds-2.5.2.jar:lib/asm-tree-5.0.1.jar:lib/jetty-jndi-9.3.7.v20160115.jar:lib/preferences-3.5.200-v20140224-1527.jar:lib/org.eclipse.sisu.plexus-0.3.2.jar:lib/gunit-3.5.2.jar:lib/httpcore-4.4.3.jar:lib/cxf-rt-transports-http-3.1.11.jar:lib/cxf-rt-frontend-simple-3.1.11.jar:lib/bimserverclientlib-1.5.92.jar:lib/commons-lang3-3.4.jar:lib/javax.inject-1.jar:lib/woodstox-core-asl-4.4.1.jar:lib/maven-aether-provider-3.3.9.jar:lib/httpmime-4.5.1.jar:lib/cxf-rt-frontend-jaxws-3.1.11.jar:lib/mchange-commons-java-0.2.11.jar:lib/jsr250-api-1.0.jar:lib/maven-artifact-3.3.9.jar:lib/app-1.3.200-v20130910-1609.jar:lib/org.eclipse.emf.common-2.11.0-v20150805-0538.jar:lib/cxf-rt-javascript-3.1.11.jar:lib/logback-classic-1.1.9.jar:lib/commons-pool2-2.4.2.jar
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=/Users/kuba/dev/projects-bim/bimserver/home
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
15:39:22 INFO  [main]: Starting BIMserver                                   
```

When I try to open `http://localhost:8082/apps/bimviews/`
at I sse in web browser console that:

```
http://localhost:8082/apps/bimserverjavascriptapi/js/plugin.version
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by yiqunc** [comment]
same symptom I experienced today, downloaded v1.5.92, installed all plug-ins as default settings suggested and all installed successfully. The application is clearly up and running but it shows "404 - Not Found" when accessing web module "/apps/bimsurfer/" and hang on there forever showing "Loading BIMviews..." when visiting "/apps/bimviews/" url.

I guess the bimsurfer plugin version is not right?

![capture](https://user-images.githubusercontent.com/2689849/33257268-b0641dd0-d3a9-11e7-8a73-42f1fef7a38c.JPG)

**Comment by hlg** [comment]
To me, this seems to be a bug in the BIMserver Javascript API. Not sure though. As a workaround you could try to do uninstall the current Javascript API plugin (or BIMvie.ws if that is where the error turns out to be originating) and then install an earlier version. You can use the REST API via curl or whatever or try the Console webapp. I think the Console webapp does not depend on the JS client plugin and should be accessible. However, you would have to manually grab the jar URL for your desired version from Maven central and then use the API call `PluginInterface.installPluginBundleFromUrl`.

**Comment by rubendel** [comment]
This was an issue in the BIMserver JS API, been fixed, see also: https://github.com/opensourceBIM/bimvie.ws/issues/97#issuecomment-347214959

**Comment by tomyzhou77** [comment]
I have installed the BIMServer V1.5.92 again, but the bimviews is still in Loading BimViews.... 
The chrome console show an error: 
Unexpected token import.

Thanks

**Comment by rubendel** [comment]
Which version of Chrome?

**Comment by rubendel** [comment]
Ah I only now noticed that in my Chrome 62 I had enabled javascript-harmony. Apparently EcmaScript 6 is still not supported by default, that sucks... I'll try and see if I can get the transpiler to work

**Comment by yiqunc** [comment]
Thank you Ruben for the quick investigation!

Best,
Benny

On 28 Nov 2017, at 10:35 pm, Ruben de Laat <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah I only now noticed that in my Chrome 62 I had enabled javascript-harmony. Apparently EcmaScript 6 is still not supported by default, that sucks... I'll try and see if I can get the transpiler to work

**Comment by Xsoiou** [comment]
FYI: Tested with 64.0.3269.3 (Official Build) dev (64-bit) (cohort: Dev). Bimviews works on that version.

**Comment by rubendel** [comment]
Alright, sorry for the hassle. The newest builds of BIMvie.ws and the JavaScript API will work again, it was just a bit too early for using the EcmaScript 6 module system so using a transpiled version for now.

**Comment by rubendel** [comment]
This means the requirement of > Chrome 62 is also not there anymore.

**Comment by yiqunc** [comment]
Will give it a go this morning and let you guys know. Again, much appreciate Ruben’s huge efforts !

Best,
Benny

On 29 Nov 2017, at 3:07 am, Ruben de Laat <notifications@github.com<mailto:notifications@github.com>> wrote:


This means the requirement of > Chrome 62 is also not there anymore.

**Comment by stonecompass** [comment]
Thank you for the hard work, Ruben!
Unfortunately I still get the error "SyntaxError: expected expression, got keyword 'import'", when doing a fresh install of BIMServer with all plugins :-(

The following versions are installed.
Is the bimserverapi-version too low?
![screen shot 2017-11-29 at 08 18 44](https://user-images.githubusercontent.com/6901364/33362906-69cf5e12-d4de-11e7-8b47-6cf106d54ec6.png)

**Comment by bdamay** [comment]
Hi Ruben, Thanks fo the quick answer ! 
Seems to me there is some issues left in the jar downloaded this morning after installing
- Version 62.0.3202.94 (Build officiel) (64 bits) => error unexpected token import in bimview on line 123
- Version 64.0.3278.0 (Build officiel) dev (64 bits) => (index):37 GET http://localhost:8082/apps/bimserverjavascriptapi/bimserverapitranspiled.js net::ERR_ABORTED

Yesterday, as Xsoiou said earlier, bimview was working fine in chrome 64. 

Thank you again for the effort. 
Best,
Benoit

**Comment by yiqunc** [comment]
Hi all, just tested it again, I exactly got the same results (installation logs and symptom) as @stonecompass posted above.

**Comment by yiqunc** [comment]
Could anyone point it out why I always get "404 - Not Found" when clicking on the "apps/bimsurfer/" web module? thanks heaps?

**Comment by tomyzhou77** [comment]
Now I installed 1.5.92 again, and get the same error in chrome 62.0.3202.94.

Thanks for your effort.

**Comment by rubendel** [comment]
Just to check, when reinstalling, do you remove the home directory as well? Because this time I really can't reproduce the error.

**Comment by stonecompass** [comment]
Yeah, I've made sure to delete any generated folder/file before doing a new install.

**Comment by bdamay** [comment]
Yes, started from a brand new empty directory, and executed the jar file from there.

**Comment by stonecompass** [comment]
Seems like it can't find the transpiled js-file.
![screen shot 2017-11-30 at 10 40 09](https://user-images.githubusercontent.com/6901364/33424050-ef955128-d5ba-11e7-854f-43448f2878ba.png)

**Comment by stonecompass** [comment]
But that's what I'm seeing in Chrome 64.

**Comment by bdamay** [comment]
I experience exactly what @stonecompass describe. On chrome 64 (canary or dev version) transpiled js file is not found. In chrome 62 syntax error (probably due to EcmaScript 6  syntax ).

Happens to be the same either on jar and war version.

**Comment by rubendel** [comment]
Oke third time's a charm: 0.0.97. It still had (never called) static import statements, which of course are syntax errors for non ES6 browsers.

This also means it's impossible to come up with a version that works in both cases, so for now we'll keep using the old style.

**Comment by stonecompass** [comment]
Thanks for your quick updates, Ruben! I really appreciate it!
As expected I don't get the error anymore, but still have a missing transpiled version of the bimserverapi. I tried doing a clean install.

**Comment by hlg** [comment]
Somehow the change in https://github.com/opensourceBIM/BIMserver-JavaScript-API/commit/12443d8ac9ca9411f8b133d30d7b3c35406832d6 did not end up in the 0.0.133 release, the version in Maven Central is older as the commit and has `bimserverapi.js` in it insted of `bimserverapitranspiled.js`.

**Comment by rubendel** [comment]
Ah that one was not built somehow... new version of API: 0.0.133

**Comment by stonecompass** [comment]
Still getting the same error with a missing transpiled version. Did I try too early? Is the new version not up yet?

**Comment by bdamay** [comment]
Hi Ruben, i have the same error here.  
Seems bimview is installed in v 0.0.97 (war version on tomcat8)
Should it be 0.0.133 as i understand from your previous post? I'm a bit confused. 

Bimserverapi is in v0.0.135 as described below. 

... /tomcat8/webapps/bimserverwar-1.5.92/WEB-INF/plugins/org.opensourcebim.bimserverapi-0.0.135.jar
... /tomcat8/webapps/bimserverwar-1.5.92/WEB-INF/plugins/org.opensourcebim.bimviews-0.0.97.jar

Thank you again for the effort

**Comment by rubendel** [comment]
0.0.135 for the API yes

**Comment by bdamay** [comment]
Looks like the error still occurs though.
bimserverapitranspiled.js  is not found and then BimserverAPI fails to load. 

I'm using chrome canary Version 64.0.3282.0 (Build officiel) canary (64 bits)

**Comment by hlg** [comment]
I can't confirm that the error persists. With BIMserver API 0.0.135, BIMvie.ws works again.

**Comment by bdamay** [comment]
Thanks for the feedback. 
I'll retry from the beginning and let you know what happens.

**Comment by bdamay** [comment]
OK i've got it working on my local machine with the jar bundle. 
It might have something to do with my browser's cache i had to flush. 
Note that It is working fine with chrome 62 and 64 so that is Pretty cool. 

As i didn't manage to make it work with the war version on my tomcat server 
I'm redeploying the war on my server and let you know what happened. 

Thanks

**Comment by dandmanster** [comment]
I have this working now with the jar files on my raspi3 and windows, so far so good. However, I need to work with this on my ec2 server but after installing tomcat7 and adding as a war I am back to square one. Exactly the same issues I faced when running as a jar file, no bimViewer or bimSurfer. Has anyone been able to run this via tomcat successfully and, if so, any advice? Thanks in advance.

**Comment by bdamay** [comment]
Same for me. jar is OK now as i said before.
But not with the war file on my server (tomcat8) 
My plugin repository shows a  org.opensourcebim.bimserverapi-0.0.135.jar that seems to be the good version but ...  


I don't know if this has an incidence but i see older versions of bimserverapi that have been extracted in maven/org/opensourcebim directory . '3 of them that i list below 

`/var/lib/tomcat8/webapps/bimserver/WEB-INF/maven/org/opensourcebim/bimserverapi/0.0.131
/var/lib/tomcat8/webapps/bimserver/WEB-INF/maven/org/opensourcebim/bimserverapi/0.0.133
/var/lib/tomcat8/webapps/bimserver/WEB-INF/maven/org/opensourcebim/bimserverapi/0.0.135`

**Comment by dandmanster** [comment]
I tried the final release version (14) and it crashed the tomcat server compiling. I had to kill it!
 :-0

**Comment by hlg** [comment]
@bdamay , did you delete the home directory before redeploying? I guess you would either have to do this or otherwise you would need to update the javascript API plugin kind of "blind", that is without BIMvie.ws.

**Comment by bdamay** [comment]
Thanks for feedback @hlg:
I'm not sure to understand what home repertory it is for war deployement. I have a WEB-INF directory and it is newly extracted from the war archive (i guess its new so). 
I didnt understand what you mean by "update  the javascript API plugin kind of "blind"". I may be to new to bimserver. I guess it's a bit like a workaround the problem but don't really know how to proceed.  

In case, here is what i did to deploy the war.  
1. stopped the service
2. removed every previous installation (war and repertory) from my /var/lib/tomcat/webapps directory. 
3. wget the last release of the bimserver war from github and copied it in the tomcat/webapps directory as "bimserver.war"
4. restarted the tomcat service
From there tomcat extracted a new bimserver directory into the webapp folder. 
Wait until everything is finished 
5. Then I connected to bimserver in chrome and proceeded with the default installation process (default plugins as in the jar installation process) .

The error occurs when i try to connect to bimview.  Don't even get the login view.

Thanks for your help

**Comment by hlg** [comment]
Ah, if you have not configured a separate home directory, the `WEB-INF` of your exploded war directory  is essentially the `homedir` of your BIMserver. Sorry for the confusion. Your process seems correct then. I have no idea what is wrong.

**Comment by bdamay** [comment]
OK. i finally manage to get what i did wrong. (beginner mistake :-)) 
Bimserver app must be the ROOT app on the tomcat server otherwise the js links are not working. 

I had to rename the bimserver.war as ROOT.war as mentionned somewhere in the bimserver wiki. I didn't get immediately that it was that important. (Now i know)

Thank you for helping on that issue (special mention to @rubendel and @hlg )

**Comment by letis33** [comment]
With BIMserver API 0.0.135, BIMvie.ws works again.

Thanks @rubendel and @hlg

**Comment by tomyzhou77** [comment]
Thanks @rubendel and @all.
The BIMServer has worked successfully.
