### ISSUE TITLE
GeometryException due to DB changes

### ISSUE THREAD

**Issue by Jpjob314** [opensourceBIM/BIMserver#664]
Hi Ruben,

For your info, since the recent changes on the geometries, ClientIfcModel processGeometryInputStream crashes :

`org.bimserver.client.GeometryException: Unsupported version 10 / 11
	at org.bimserver.client.ClientIfcModel.processGeometryInputStream(ClientIfcModel.java:372)
	at org.bimserver.client.ClientIfcModel.loadGeometry(ClientIfcModel.java:333)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:285)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:96)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:207)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:1)`

Is it easy to update the InputStream reader to fits to the new model ? 

Thanks

**Comment by rubendel** [comment]
You need to update the "BinarySerializers" plugin as well, that is the plugin that generates the binary geometry at version 10 in your version.

**Comment by hlg** [comment]
But the error appears in the client. I think, the updated serializer produces geometry version 11, but the client only consumes version 10. I tried to fix that, but found it too difficult without documentation of the binary geometry format. That is why we are currently not working with the latest versions.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/blob/master/BimServerClientLib/src/org/bimserver/client/ClientIfcModel.java#L372 (line number taken from the stacktrace) clearly shows that "10" is what the client is getting from the server and 11 is what it expects. So you need to update BinarySerializers for this to work.

**Comment by hlg** [comment]
Yes, sorry, you are right.

**Comment by Jpjob314** [comment]
updating BinarySerializers did the job ! thank you !
