### ISSUE TITLE
/apps/bimsurfer link shows 404-not found

### ISSUE THREAD

**Issue by bdamay** [opensourceBIM/BIMserver#665]
Is this normal behavior ? 

I use bimserver 1.5.92 with its default plugins installed

**Comment by xie-qianyue** [comment]
I think it's a supposed behaviour. Because the `index.html` isn't packaged into the bimsurfer jar.

**Comment by bdamay** [comment]
Thanks for the reply. I guess so too.
 It's was bit confusing for me before i understood bimsurfer is not meant to be an enduser app. 
Anyway, it could be nice to have the bimsurfer demo at index.html.

**Comment by epeter-** [comment]
hi, do you have a solution for the index.html?
tx peter



Am 2017-12-13 9:24, schrieb XIE Qianyue:

**Comment by bdamay** [comment]
I'm afraid not.  
Is that the index is supposed to lead anywhere ? seems not.
Looks like installing the Bimsurfer module on Bimserver let Bimview use bimsurfer library by importing js  from  /apps/bimsurfer/bimsurfer.min.js?_v=0.0.43 (in my installation)
Nothing is then provided on the index and that appears to be the desired behaviour. (as i understand) 
That's why i closed th issue.
