### ISSUE TITLE
Oids for projects are not unique

### ISSUE THREAD

**Issue by sindreamundsen** [opensourceBIM/BIMserver#669]
Creating new project using: (1.5.85)
`SProject sproject = bimServerClient.getServiceInterface().addProject(ifcProject.getProjectName(), "ifc2x3tc1");`

Cleaning all, installing new version, createing project again (based on the same IFC-file) 1.5.92:
`SProject sproject = bimServerClient.getServiceInterface().addProject(ifcProject.getProjectName(), "ifc2x3tc1");`

I can see that _sproject.getOid()_ has a tendency to repeat the oid even when \home-directory is created from scratch.. why?
This is a huge problem when I'm using the oid in external DB for linking other data.

This causes a problem when upgrading version (when home-directory is empty)..

How is oid created?

**Comment by rubendel** [comment]
What would you think it would do? Magically remember the last oid when you delete your database?

**Comment by sindreamundsen** [comment]
Hehe.. no, I'm expecting no magic here :-)
But it weird that oid for project occurs with the same value so soon.
I had 6-7 projects in bimserver, changed version (and started with empty home-directory) and both 1st and 2nd oid for the projects after upgrade was among the oids from the 6-7 projects with previous bimserver-version.

**Comment by rubendel** [comment]
It's not weird, it's deterministic (well almost, as you noticed). I would suggest using another method to link to the project, for example the project name (which is also unique, on the root-level). You could also use the generated BIMserver ID as a prefix for the id's you store in your system, so you'd get something like "unique-bimserver-id+object-id".
