### ISSUE TITLE
Javascript Client App :  Unexpected Token, BimServerClient is not defined 

### ISSUE THREAD

**Issue by alilouchka** [opensourceBIM/BIMserver#671]
Hey, 

I am trying to test a client wab app  using BimServerClient api. 

Everything is Ok when i load the librairies from : 

![2017-12-20_14h16_47](https://user-images.githubusercontent.com/26714480/34209202-88426f10-e591-11e7-90ab-41d6f95dfd1e.png)

I got in the console : 

![image](https://user-images.githubusercontent.com/26714480/34209225-9a2cc23e-e591-11e7-9369-3538302a1c23.png)

But when i try to load them locally from : 

![2017-12-20_14h17_33](https://user-images.githubusercontent.com/26714480/34209367-17d6ebec-e592-11e7-9fae-ded374d8609c.png)

or from my local host : 

![image](https://user-images.githubusercontent.com/26714480/34209263-bab44efa-e591-11e7-98e9-9afe3fac2575.png)

I get the unexpected token error and BimServerClient is not defined : 

![image](https://user-images.githubusercontent.com/26714480/34209304-defcfd34-e591-11e7-86f4-c2c13c537e3a.png)

Can you help me please !? 

Thanks

**Comment by bdamay** [comment]
Few days ago i experienced that thisisanexperimentalserver was not serving the same files than the api installed with bimserverv1.5.92.
The bimserver install is serving modules so you need to specify `<script type="module" ..>` instead of `text/javascript` .
You might need to explicitly `import BimServerClient from js/bimserverclient.js` in your app, but i'm not sure of this.

**Comment by alilouchka** [comment]
Thabks bdamay for your answer, i did all of this but it stills not working : 

![2017-12-22_13h16_03](https://user-images.githubusercontent.com/26714480/34297790-83872ddc-e71a-11e7-914e-d4c97d61301a.png)

Result: 

![2017-12-22_13h18_17](https://user-images.githubusercontent.com/26714480/34297812-9d970fa8-e71a-11e7-84ef-59ccaf262c98.png)

![2017-12-22_13h18_25](https://user-images.githubusercontent.com/26714480/34297818-a052c656-e71a-11e7-8c95-5ee6a1b6a092.png)

Any solution please ? : ) 

Thanks

**Comment by alilouchka** [comment]
can you try the code by your self and tell me if it's working or not please ? 

<head>
	<script type="module" src="js/bimserverapiwebsocket.js"></script>
	<script type="module" src="js/bimserverclient.js"></script>
	<script type="module" src="js/bimserverapipromise.js"></script>
	<script type="module" src="js/ifc2x3tc1.js"></script>
	<script type="module" src="js/ifc4.js"></script>
	<script type="module" src="js/model.js"></script>
	<script type="module" src="js/translations_en.js"></script>
</head>
<body>
		<script>
		// Create a new API, the path given should point to the base path of a BIMserver. This can also be a full URL like "http://bimserveraddress"
		import BimServerClient from 'js/bimserverclient.js'
		window.addEventListener('DOMContentLoaded', () => {
			var api = new BimServerClient("http://localhost:8082");
		api.init((client, version) => {
			console.log(version.version);
		});
		});
		</script>
</body>


// Thanks : )

**Comment by bdamay** [comment]
did you try defining the type of the script itself with type="module" ? 
line 13 `<script type="module">`

**Comment by alilouchka** [comment]
Yes that's what i did buy with no success
