### ISSUE TITLE
bimserverapi is not defined on new server.

### ISSUE THREAD

**Issue by alfredorods** [opensourceBIM/BIMserver#672]
Hi comunity, i instaled bimserver a few times and always bimserver work great, but in this moment i'm trying to install it in a new server and i get this error:

bimserverapi is not defined

when i saw the installation the plugin was installed successfully.

![bimapi](https://user-images.githubusercontent.com/16584082/34312165-7c6ce460-e738-11e7-83cd-94ef1a881351.png)

**Comment by rubendel** [comment]
Are you using your own version of GUI?

**Comment by alfredorods** [comment]
Hi Ruben, not i'm using the war file donwloaded from the releases page.

**Comment by rubendel** [comment]
If you go to the base address, does it list the javascriptapi?

**Comment by alfredorods** [comment]
This list? yes it is.

![image](https://user-images.githubusercontent.com/16584082/34615431-4730deb8-f20b-11e7-871f-4a6059302093.png)

**Comment by rubendel** [comment]
1.5.76, that is a very old version, every new installation will download the latest versions of every plugin you select. Those are probably not compatible with 1.5.76.

**Comment by rubendel** [comment]
Also the subpath has a tendency to not work, deploying as ROOT.war is the preferred way.

**Comment by Erbrand** [comment]
Hi,

here I get the same issue running the 1.5.92 :  

![image](https://user-images.githubusercontent.com/28804876/34725094-35c64148-f550-11e7-8461-3aee45a15fe7.png)
![image](https://user-images.githubusercontent.com/28804876/34725140-4f14f072-f550-11e7-9d11-666242dd44d4.png)

the web-container is Tomcat 8.5.24

**Comment by rubendel** [comment]
Deploy as ROOT.war

**Comment by rubendel** [comment]
Newest version of BIMvie.ws and the JavaScriptAPI now support running on non ROOT path as well.

**Comment by alfredorods** [comment]
Hey Rubendel thanks for your help.. i'have another doubt.. how can i install and old plugin of javascript api? because when i install i only can see 3 versions of the javascript API.. and i need see and install an old version.. i see in the repository the releases and i can download the version that i need but i don't know how can i install this version.

Thanks.

**Comment by rubendel** [comment]
You could do that using the API of BIMserver, but I don't recommend it because usually only the latest version of everything kind of works together.
