### ISSUE TITLE
some sloping components are missing?

### ISSUE THREAD

**Issue by mushroom0V0** [opensourceBIM/BIMserver#673]
HI~We encountered some problems. Some oblique components could not be displayed. The model should look like this:
![h ecw h 53o4ecq vi91hu9](https://user-images.githubusercontent.com/31752037/34336208-482cd192-e990-11e7-91b6-c71b665ff28d.png)
but, after I imported my IFC file,some sloping components on the edge are not shown(purple arrowheads), while others were no problem(red arrowhead). 
![3iiu1ic20t3a5xc m5nhlmb](https://user-images.githubusercontent.com/31752037/34336444-2b731ea6-e992-11e7-94fd-40be7bd7b86c.png)
And this is the ifc file:
[test.zip](https://github.com/opensourceBIM/BIMserver/files/1585600/test.zip)
What's the reason, please? How can I deal with it?
(Wow,This is the first time I write a letter to a real person in English, not in the English writing practice.Hope that I don't have too many grammatical mistakes(*￣︶￣))

**Comment by rubendel** [comment]
The IfcEllipse objects were losing their position in translation. This has now been fixed and will be in the 1.9.94 release.

**Comment by mushroom0V0** [comment]
I’m thrilled to hear that !!! Now we are using the version released in May,maybe easier~if we update it directly, will there be some compatibility problems?

**Comment by rubendel** [comment]
Yes most probably, in most cases easiest will be to remove your database, remember you are on a development version.

**Comment by mushroom0V0** [comment]
fine, thank you very much~!
