### ISSUE TITLE
Admin page for BIMserver

### ISSUE THREAD

**Issue by YukioCYH** [opensourceBIM/BIMserver#674]
Hello, I am using BIMserver to create admin so that I could import IFC files from sketch up make 2017 to Open studio version 2.3.0. As stated in the instructions on [https://nrel.github.io/OpenStudio-use...] ,I downloaded Java JDk 1.7 but the JDK 1.7 is not available on Oracle anymore. Hence, I downloaded JDK 1.7 on other web.

After downloaded all softwares needed for this BIMserver and I run the program, It stated server successfully started. Download the latest OSMSerializer and copy the OSMSerializer.jar file into the plugins subfolder under the bimserver-[version] folder as said in the instructions as well.

So I proceed to click on start again and it also shows 'Server started successfully'. 
![image](https://user-images.githubusercontent.com/34933205/34431032-155a0aaa-eca6-11e7-9598-ab6a9617f9c2.png)

But when I launch the browser and click on to go to admin page, it stated browser is not connected or 404-page error. 
![image 2](https://user-images.githubusercontent.com/34933205/34431040-299a86e8-eca6-11e7-8e43-628416269b7e.png)
![image 3](https://user-images.githubusercontent.com/34933205/34431042-377d7162-eca6-11e7-8423-e4211ba16f77.png)

Is there someone out there that can solve this problem? Thank you!

**Comment by berlotti** [comment]
Hi,

Looks like your server is nog running.
The screenshot says 'server has been shut down'.

On another note: a newer version of Java should also work, so it would probably be a better option to use an official newer version.

**Comment by YukioCYH** [comment]
Hi, 

Thanks for replying. It really works!
<img width="960" alt="screenshot 2018-01-03 09 15 18 1" src="https://user-images.githubusercontent.com/34933205/34506660-c94d0a8c-f069-11e7-9880-961f25b6b3b4.png">
