### ISSUE TITLE
Is it possible to filter a query by PSet property value?

### ISSUE THREAD

**Issue by malinkody** [opensourceBIM/BIMserver#675]
I have been trying to figure out if it is possible to filter a query by a specific PSet and property value. I know you can filter by name, oid and guid. Lets say I want to query all **IfcBeam** objects that have a PSet named "**Materials**" which has a property named "**type**" which in turn has a value of "**Steel**". 

- How would I go about doing this? 
- Is it possible using the current javascript client and serializer?
- If not, can I write a Serializer that can process a filter and output the required result? I have experimented with the SerializerPlugin, but so far I don't see how I can access the query parameters during Serialization.

**Comment by rubendel** [comment]
You can do this already with the embedded query/filter language:
```json
{
  "type": {
    "name": "IfcBeam"
  },
  "properties": {
    "type": "Steel"
  }
}
```

The only thing this is not filtering on is the PSet name "Materials", so if there are multiple PSets with the property name "type" this will fail. For that I have created a new issue: https://github.com/opensourceBIM/BIMserver/issues/678

**Comment by malinkody** [comment]
Thank you for the quick answer. This seems to work well. I tested several queries using the Query tab in BIMvie.ws and came upon another issue. My use case is as follows:

In our model we have objects of type IfcBuildingElementProxy. These objects inherit values and properties from IfcBuildingElementProxyType which is related to IfcBuildingElementProxy via IfcRelDefinesByType objects. Now if I were to use the following filter I will only get objects of type IfcBuildingElementProxy that have explicitly defined this property in their own PSets. But it is possible to have an IfcBuildingElementProxy with an undefined "type" where the related IfcBuildingElementProxyType object has defined the "type" property as "steel" for all its children. 
Is it possible to expand the following query to include all objects of type IfcBuildingElementProxy where their relating IfcBuildingElementProxyType might have the "type" value set as "steel"?

`{
  "type": {
    "name": "IfcBuildingElementProxy"
  },
  "properties": {
    "type": "Steel"
  }
}`

I also ran into the issue that you mentioned of duplicate property names. The proposed solution in issue #678 would solve this issue for us. I would love to know if there is a development timetable and if so, when this solution will be implemented.

**Comment by rubendel** [comment]
That makes sense, this should be implemented generically for all objects that have a "*Type" variant. I'll leave this issue open for that specific implementation.

No timetables.

**Comment by malinkody** [comment]
Thank you for the quick reply. I'm looking forward to these features.

**Comment by rubendel** [comment]
Depending on your situation, you might be able to recreate this feature in the mean time by doing multiple queries. For example first query the "*Type" objects having the properties and then use the relation to get the related "IfcBeam" objects in a second query.

**Comment by rubendel** [comment]
This has now been implemented
