### ISSUE TITLE
Unable to Open IFC file from Openstudio

### ISSUE THREAD

**Issue by YukioCYH** [opensourceBIM/BIMserver#682]
Hi, I had some problem here regarding importing IFC to Open Studio. I followed all the steps on [https://nrel.github.io/OpenStudio-user-documentation/tutorials/tutorial_ifcimport/](url) also able to upload the IFC files onto Open studio as shown below.
![image](https://user-images.githubusercontent.com/34933205/34810176-acc4b600-f6d4-11e7-81c7-848ce031ad15.png)
After clicking 'Download OSM file', Open studio will prompt a message to save or discard the original file that you opened previously. (usually I clicked discard)

But after discarding the original file, another file will automatically reopened again. And I assumed that it is the IFC file that I imported in previously. It do not open the IFC file that I imported but opened an empty file.

So I am not sure what is happening and probably something wrong with the format of my IFC file? But I export it from Sketch Up make 2017.

![image](https://user-images.githubusercontent.com/34933205/34810193-bdbbd312-f6d4-11e7-972d-ef85f3fd36fb.png)
Can someone please help? Thank you
Regards,
YH

**Comment by rubendel** [comment]
It's probably a better idea to post this on the issue tracker of OpenStudio
