### ISSUE TITLE
Server refused connection during Log-in due to wss:// Content Security Policy

### ISSUE THREAD

**Issue by kurb70** [opensourceBIM/BIMserver#684]
I'm using BIMserver 1.5.94 WAR in Tomcat 8.0 (I remamed bimserverwar-1.5.94.war to ROOT.war). I deployed ROOT.war under a separate URL (configured with a host entry server. xml). The BIMserver could be started and configured as expected.

But when I try to log in  under BIM Views for the first time, I get the following message in the WebBrowser console:

I receive this message regardless of whether I access the server at http:// or https://

```
Refused to connect to wss://dev.myserver.com/stream because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.

[Error] SecurityError (DOM Exception 18): The operation is insecure.
[native code]
connect — bimserverapiwebsocket.js:25
(anonyme Funktion) — bimserverclient.js:168
(anonyme Funktion) — bimserverclient.js:877
(anonyme Funktion) — bimserverclient.js:653
onload — bimserverclient.js:538

	connect (bimserverapi.umd.js:296)
	(anonyme Funktion) (bimserverapi.umd.js:37732)
	(anonyme Funktion) (bimserverapi.umd.js:38517)
	(anonyme Funktion) (bimserverapi.umd.js:38277)
	onload (bimserverapi.umd.js:38159)
```

**Comment by rubendel** [comment]
Which browser (version)? Did you configure the "Site address" during BIMserver setup to be exactly the URL you are accessing it on (e.a. http[s]://[sitename][:portname]?

**Comment by kurb70** [comment]
I tried Safari 11.0.2 and Firefox 57.0.4. Both are coming up with the same behaviour.

Yes I configured the URL. I reinstalled to be sure.
My setup is  Apache (providing TSL) <-> Tomcat with BIMserver as WAR
Apache and Tomcat are on the same maschien.

Do I really have to config the port with BIMserver setup as well? With my setup do I have to use 80 or 443?

**Comment by rubendel** [comment]
You probably did not configure Apache to allow websockets. Also in BIMvie.ws only Google Chrome is supported (others might work though).

https://github.com/opensourceBIM/BIMserver/wiki/Web-socket-error

**Comment by kurb70** [comment]
I'm afraid you're right. I have not read this WebSockets notice.

To make sure that WebSockets work on my server, I have installed the examples that come with Apache-Tomcat. The violation of the Content Security Policy is also displayed here. Therefore I have to work on the web server configuration.
