### ISSUE TITLE
Invalid username/password combination

### ISSUE THREAD

**Issue by mushroom0V0** [opensourceBIM/BIMserver#685]
I downloaded the latest version，but when I run the project，there are some questions....I can't login in, Do I forget anything？

1) Install the bimserverwar  and rename it to 'ROOT.war'
2) Put it in the webapp folder and Run the tomcat
3) Run the test code
![zo04o_6 2 k cx 8p4 iix](https://user-images.githubusercontent.com/31752037/34979309-e7a93b32-fadb-11e7-8440-e7cbc76b77a2.png)

Uh...It's normal if I  open it in web directly
![image](https://user-images.githubusercontent.com/31752037/34979424-336b8dfe-fadc-11e7-863f-469f05b645c3.png)
Do I need to configuration some parameters or add some codes？

**Comment by rubendel** [comment]
Yes you need to configure your BIMserver first, that's what the setup screen is for you posted as the last image...

**Comment by mushroom0V0** [comment]
![u 606420692 3875965808 fm 27 gp 0](https://user-images.githubusercontent.com/31752037/34982098-6667727e-fae4-11e7-808a-814456869822.jpg)
It works！
