### ISSUE TITLE
Local plugin bundles missing after server restart

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#686]
When BIMserver is restarted, previously locally installed plugin bundles are missing, while they are technically still there - probably not loaded. A similar behaviour was described in #494.

The jar in the plugin folder is still there. Reinstallment fails until the jar is manually deleted ("This plugin has already been installed ").

In bimvie.ws they are not listed, but their settings pages are there (but showing no settings). Also the functionality they were adding seems to be there but does not work (e.g. serializer is listed in drop-down). 

Throught the API, the plugins are included in the result of the `AdminInterface.getAllPlugins` and in the lists of specific plugin types, e.g. `PluginInterface.getAllSerializers`. Bundle information can be obtained from the `PluginInterface` with `getInstalledPluginBundle` and `listPluginsInBundle` after taking the bundle ID from `getAllPlugins`, but it is not included in `getInstalledPluginBundles`. `installPluginBundleFromFile` fails with Userexception ("already installed"), same as `getPluginBundle`.

**Comment by rubendel** [comment]
I just tried a few plugin bundles and restarted my development BIMserver, seems to work. Is there a specific plugin I can try on a clean BIMserver database to reproduce this?

**Comment by hlg** [comment]
I found the corresponding error message in the log file and could trace that back to the reason of the failure: I had no maven repository specified in the pom, but dependencies declared. On first install the dependencies seem to be resolved against some other default repository. On reload of the plugins however, it is done differently and fails fast although the dependencies are already downloaded to the local repository and the repository declaration is thus not really important.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.bimserver.plugins.PluginManager.loadFromPluginDir(PluginManager.java:1369)
        at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1114)
        at org.bimserver.BimServer.start(BimServer.java:719)
        at org.bimserver.JarBimServer.start(JarBimServer.java:142)
        at org.bimserver.JarBimServer.main(JarBimServer.java:62)
```

The issue can be closed for my part, but I'll leave this open, in case you want to improve something.

Great thing, this new plugin system, by the way.

**Comment by rubendel** [comment]
I think this is fixed now, not sure why it was expecting there to always be a repository declared in de plugin pom.xml. I anyone's plugins stop working after this commit, let me know.
