### ISSUE TITLE
JSON Query - select all IfcWalls with a particular IfcWallType

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#687]
I'm trying to select all the `IfcWall` typed by a `IfcWallType` given the type's GUID.
So far, taking as a reference the bimvie.ws predefined query, i've tried with:

```JavaScript
{
  "type": "IfcWall",
  "include": {
    "type": "IfcWall",
    "field": "IsDefinedBy",
    "include": {
      "type": "IfcRelDefinesByType",
      "field": "RelatingType",
      "include": {
        "type": "IfcWallType",
        "include": {
            "type": "IfcWallType",
            "guid": "0PCbHKYgRGAubJOUrMHhEK"
        }
      }
    }
  }
}
```

but the query result includes all the walls of the project, instead of only the external walls (that particular `IfcWallType` is associated only to the external walls).

![schermata 2018-01-17 alle 09 29 12](https://user-images.githubusercontent.com/6218623/35032918-0c0f2d50-fb69-11e7-9ba4-1e96e4df88ae.png)

I'm using BIMServer `v1.5.69` (bimvie.ws `0.0.78`) but also with the latest version i get the same result.
The file schema is`Ifc2x3`.

**Comment by rubendel** [comment]
The query language does not work in this direction. It starts at the top query (all walls), so those are already included from the beginning, all that comes after that can only include more objects. So in this case what you could try and do is reverse your query, start with the IfcWallType/GUID part and then possibly include the reference to the IfcWalls that are linked to the type.

**Comment by GiacomoManzoli** [comment]
Thank you, i was able to achive the desired result with
```javascript
{
  "type": "IfcWallType",
  "guid": "0PCbHKYgRGAubJOUrMHhEK",
  "include": {
    "type": "IfcWallType",
    "field": "ObjectTypeOf",
    "include": {
      "type": "IfcRelDefinesByType",
      "field": "RelatedObjects",
      "outputType": "IfcWall",
      "include": {
        "type":"IfcWall"
      }
    }
  }
}
```

**Comment by rubendel** [comment]
Cool, thanks for posting the final query
