### ISSUE TITLE
where is the  class "IfcFileReader" and the package "org.bimserver.ifc.file.reader"

### ISSUE THREAD

**Issue by teimanLu** [opensourceBIM/BIMserver#690]
We are trying to convert BDB in BIMserver to mysql, so we are learning the "ifc2db.java" in tests, but can't find the corresponding ifcfilereader. How should I find it? Or is there a better conversion of mysql examples for our reference, thank you.

**Comment by rubendel** [comment]
I'll remove that file, it's not commented out for no reason... 

MySQL is not going to work, we researched it almost 10 years ago, makes no sense to try and store an object model like IFC in a relational database (not without extreme simplifications in the model).

**Comment by teimanLu** [comment]
Thanks rubendel answer, we also give up convert mysql, but due to our need for further optimization of the performance of the database, we also need to try to choose the other which has the function of distributed storage library, now find the Apache Geode may we use the right. Do you know the feasibility of turning BerkeleyDB into Apache Geoder? If so, will you share your experience with us?

**Comment by rubendel** [comment]
Are you running BIMserver in production and running into performance issues? How many 100's of gigabytes is your database? You many concurrent users?

My current view on converting to a scalable database: https://github.com/opensourceBIM/BIMserver/issues/422
