### ISSUE TITLE
error after running out of memory

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#695]
Error on line 29: (Key exists: pid: 8, oid: 36428120584, rid: 1) #6= IFCCARTESIANPOINT((0.,0.,0.));

i receive above message after trying to checkin a file and running out of memory.
after that i increased heap size and now i get that error message.
don't know if it matters, just wanted to report. the checkin proceed though

**Comment by rubendel** [comment]
That is an inconsistency and it should be fixed.

Note to self (or anyone wanting to fix this issue ;)):

> IFC data is not stored transactionally anymore to improve speed, the Store model (transactional) should guard it (and it does), but on failed transactions like this (out of memory) the server should cleanup the non-transactional data.
> 
> This should be easy because all unreferenced data can safely be deleted.

**Comment by rubendel** [comment]
Fixed in https://github.com/opensourceBIM/BIMserver/commit/51ed644b12061e60f843987d7e17af8c4292b7ee

Another note to self:

> The process checking whether cleanups are required can potentially take a long time on BIMserver startup when databases get really large, also it sort of primes the whole cache, which can be bad for old databases with a lot of unused projects.
