### ISSUE TITLE
JSON Query - Query with an Ifc4-base project fails

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#696]
When i try to use "complex" queries in a project based on an Ifc4 model, the server (`v1.5.69` bimvie.ws `0.0.78`) crashes.

For instance, the query above causes a server error ([Error log](https://github.com/opensourceBIM/BIMserver/files/1667610/server_log.txt)).

```javascript
{"type":"IfcWall", "guid":"3GVvoXwi40HAubBs_U13ct"}
```
while a simpler query, like:

```javascript
{"type":"IfcWall"}
```
works fine.

The same query in a Ifc2x3 based project works fine.

**Comment by rubendel** [comment]
A lot of problems with IFC4 have been fixed in later versions of BIMserver so I suggest trying the latest developers release.

**Comment by GiacomoManzoli** [comment]
With `v1.5.95` works fine, thanks!
