### ISSUE TITLE
Performance problems？

### ISSUE THREAD

**Issue by mushroom0V0** [opensourceBIM/BIMserver#697]
We find that the new version seems to require higher performance than it used to be(1.5.73). If we try to checkin a large IFC file, it will throw this errror:
![rcl qr c2e2svcdwhp 3 m](https://user-images.githubusercontent.com/31752037/35467328-07a23e92-0348-11e8-86e1-4001e861dc93.png)

I split the model into multiple IFC files and it's ok, but previous versions can correctly checkin the same file directly.

Is it possible to do some optimization？

In addition, can we choose not to run some function, like store IFC files and log files in bimserver... we want to be faster, only enable it when the problem is real.

Thank you all the way

**Comment by rubendel** [comment]
What part of this error indicates a performance problem? If you don't want to store IFC files, why use BIMserver? Logging of files has no effect on performance, those are streamed directly to disk.

Are there other errors before this error?

**Comment by mushroom0V0** [comment]
Sorry, I didn't describe it clearly.

I'm not sure, it just looks like a performance problem... 
First, when I open several applications at the same time, checkin a not too large IFC file(6000kb) will throw this error, and when I close other applications, just checkin it,i t's no problem.
Next, I closed other applications, and try to checkin a larger IFC file, it throw this error again.

This problem hasn't appeared before, so I guess the consumption of memory or somthing is getting higher. 

This error occurred at the same time as the above :
![p9xfuu a_adrs 4sck v 74](https://user-images.githubusercontent.com/31752037/35469880-d33d1316-0379-11e8-8e47-2f047a8b308b.png)

and it is one of my test IFC files :
[test.zip](https://github.com/opensourceBIM/BIMserver/files/1669886/test.zip)

------A Not gorgeous split line-----
About don't store IFC files, It's not used, our platform does not provide this function, but that's not the point... 
I'm very depressed, too. My leader said the function "getModel()" is slower... so he asked me is there anything we can annotate, even if I don't think it's a little affected. It's about speed, not performance.
maybe I shouldn't have put these two questions together.

**Comment by rubendel** [comment]
Both stacktraces you provide do not describe a checkin. The file you provided checks in fine though. I am sorry you are depressed. You should never put two questions together on any issue tracker, the language barrier is confusing enough. Assumptions are not necessary, Java throws very clear exception when the memory limit has been reached.

Are you perhaps running a BIMserver separately from your own application? In that case it's useful to have a look at the BIMserver log as well, maybe it is indeed a memory error, in that case there is a simple solution.

**Comment by mushroom0V0** [comment]
Oh I will try it. If there are some new discoveries I will submit it.
I just found out I'm mixed up. 
The error occured when I getModel after checkin, just as shown in the picture.

**Comment by rubendel** [comment]
Oh well I guess mixed-up is better than depressed
