### ISSUE TITLE
ifc file size version 1.5.95

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#699]
hi i am failing to checkin an ifc 2x3 sized 726 923 KB.
system debian 9
physical memory 10gb
in /etc/init.d/tomcat
JAVA_OPTS are set to -Xms6g -Xmx8g 
any suggestions?
thanks

**Comment by rubendel** [comment]
Any error messages?

**Comment by epeter-** [comment]
unfortunately no.
progress bar eventually just stops. that was it (1st third of progress)
ifc file opens in solibri without errors.
best peter

**Comment by epeter-** [comment]
an addon: after failing checking in the file the bimserver is not reachable anymore (apache running)

**Comment by rubendel** [comment]
It most probably ran out of memory. There should definitely be an error in the logfile of BIMserver or Tomcat's logfile, have you looked at that?
