### ISSUE TITLE
Remove object implementation

### ISSUE THREAD

**Issue by PatriceMoreau56** [opensourceBIM/BIMserver#702]
Hi,

It seems that the remove object execution of the _RemoveObjectChange_ class has not been implemented yet:
```
@SuppressWarnings("rawtypes")
@Override
public void execute(Transaction transaction) throws UserException, BimserverLockConflictException, BimserverDatabaseException {
    throw new UserException("Not implemented");
}
```
Is there another way to delete an object from a project than by using the LowLevelInterface function _removeObject_?

Thank you for your reply

**Comment by rubendel** [comment]
Fixed, unit test is working again. Just be aware that the lowlevelcalls have been rewritten, and probably are not super stable. I haven't tested anything to do with ordering of calls (for example deleting a modified object etc...)
