### ISSUE TITLE
CreateObject does not generate Global Id

### ISSUE THREAD

**Issue by PatriceMoreau56** [opensourceBIM/BIMserver#703]
Hi,

When I use the function LowLevelInterface.createObject with the parameter generateGuid set to true:
`relId = client.getLowLevelInterface().createObject(tid, "IfcRelDefinesByProperties", true);`
The objects I create does not have a Global Id:
![image](https://user-images.githubusercontent.com/34338280/35730595-f47df872-0812-11e8-8ecb-7bd1cb02457e.png)

As you can see I created a property set and a property single value, both have no Global Id.

Is there a method to call before commit to generate the global Ids?

**Comment by rubendel** [comment]
A this feature was lost while translating to a new system, it's been added now.

**Comment by PatriceMoreau56** [comment]
Thanks for the fix.

I noticed that if the object has no global ID in its definition, the bimserver generates an error if I asked to generate a global ID. So the client has to know if the object it tries to create has a global ID or not.

The bimserver knowing the object and its properties, do you think it could handle these case? (As generate a warning if the object does not have a global ID but not an error when commiting?)
