### ISSUE TITLE
3D model not correctly rendered

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#707]
I'm having trouble with the rendering of an Ifc4 file exported with Allplan 2018.
In particular, some walls and other object of the project are not displayed in the BIMvie.ws client (`0.0.102`).
The missing elements are corretcly displayed with Solibri Model Viewer and their correctly defined in the IFC filte.

The file size is ~31Mb, the server version is `1.5.95` with 8gb of RAM.
There are no error in the server logs and with this BIMserver configuration i was able to correctly display bigger files.

Below there is a semple of the results, with both BIMvie.ws and Solibri.
For copyright reasons i can't directly upload the IFC file, but i can send it by email.

![BIMvie.ws](https://user-images.githubusercontent.com/6218623/35927194-6b02381c-0c2a-11e8-9ec5-f80e1c89981b.png)

![Solibri](https://user-images.githubusercontent.com/6218623/35927328-c5077264-0c2a-11e8-98bb-7d0836967941.png)

**Comment by rubendel** [comment]
The more interesting part of the logfile is the part that's written during checkin.

A "Geometry generation report" is generated for every checkin in the last few versions of BIMserver. It should be attached as extended data to the revision, can you have a look and see whether there are any errors in it?

Please be advised that IFC4 is not supported by the current version of IfcOpenShell we are using. A new version will be coming. This is only true if your model uses any of the new geometry types in IFC4.

If you could send (a link to the) file to ruben@logic-labs.nl I'll see if I can find anything interesting.

**Comment by GiacomoManzoli** [comment]
In fact there are several error during the Geometry generation.
Below there are the logs files.

[bimserver.log](https://github.com/opensourceBIM/BIMserver/files/1706493/bimserver.log)
[generation_logs.zip](https://github.com/opensourceBIM/BIMserver/files/1706494/generation_logs.zip)

I've also sent to you an email with the IFC file.

**Comment by rubendel** [comment]
All the errors are indeed new types in IFC4 (IfcOpeningStandardCase, IfcSlabStandardCase, IfcOpeningStandardCase, IfcColumnStandardCase, IfcBeamStandardCase). I hope we have an IFC4-capable version of IfcOpenShell soon.

**Comment by GiacomoManzoli** [comment]
Ok! Thank you for the help!
I'll keep the issue open for reference, ok?
