### ISSUE TITLE
The IFC rendering result isn't complete

### ISSUE THREAD

**Issue by boundaryfree** [opensourceBIM/BIMserver#709]
I used BIMserver and BIMSurfer (latest version 1.5.95) to render the IFC file [terrain_missing.ifc.zip] (https://github.com/opensourceBIM/BIMserver/files/1722442/terrain_missing.ifc.zip) . But some components (e.g. the terrain object) were missing in the render result (the first attached picture).
I tried to convert the IFC file to glTF file by IfcOpenShell and COLLADA2GLTF tools. And open the glTF file in one viewer, the result was correct ((the second attached picture)).

<img width="860" alt="result_by_bimserver_surfer" src="https://user-images.githubusercontent.com/8002244/36185597-060a6402-1175-11e8-9509-537088be2bb5.png">
<img width="727" alt="result_by_ifcopenshell" src="https://user-images.githubusercontent.com/8002244/36185598-063b71f0-1175-11e8-8096-fcc992f84e71.png">

**Comment by rubendel** [comment]
The object that is missing here is the IfcSite. The IfcSite in this model has two representations, one of them is 2D. The other representation is an IfcRepresentationItem object with the "RepresentationIdentifier" set to "Facetation". The Streaming checkin only allowed "Body" in this field. The IfcSite documentation says it can also be "Facetation", so I changed this in the code. Thanks for reporting.
