### ISSUE TITLE
ServiceInterface.compare not working in several cases

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#711]
Hi!

The API `ServiceInferface.compare` (BIMServer 1.5.95) with the `Name based` compare plugin  gives a `NullPointerException` when used within an IFC4 project, but works fine with an IFC2X3 project.

Also, the same API with the `GUID based` comparsions crashes with an IFC2X3 project, but works fine with an IFC4 project.

[compare_error_files.zip](https://github.com/opensourceBIM/BIMserver/files/1740373/compare_error_files.zip) contains the IFC files used in both cases and the server error logs.

**Comment by rubendel** [comment]
These problems should be fixed in 1.5.96. Thanks a lot for the IFC files, it made testing this a lot easier.

Are you OK with me adding the test files to https://github.com/opensourceBIM/TestFiles? That way other people can run/improve the unit tests I have added.

**Comment by GiacomoManzoli** [comment]
Of course! No problem at all, these IFCs where build with the intent to provide a simple test case!

**Comment by GiacomoManzoli** [comment]
Little update: i've tried the 1.5.96 server version.
The name-based compare now works fine with IFC4 files, but i keep getting an error with the GUID-based on the IFC2X3 case:
```
15:24:38 ERROR [qtp752011518-35]:                                                                                  (JsonHandler.java:178) 
java.lang.NoSuchMethodError: org.bimserver.emf.IfcModelInterface.getByGuid(Ljava/lang/String;)Lorg/bimserver/models/ifc2x3tc1/IfcRoot;
```
This is the full error log
[compare_by_guid_bimserver.log](https://github.com/opensourceBIM/BIMserver/files/1775421/compare_by_guid_bimserver.log).

Could it be a problem of the IFC2X3 files?

**Comment by rubendel** [comment]
The plugins need a little more time to be distributed to maven, your IfcPlugins should be at 0.0.34

**Comment by GiacomoManzoli** [comment]
Ah ok 😅!
Now it works fine! Thanks a lot!
