### ISSUE TITLE
direcotry browsing enables

### ISSUE THREAD

**Issue by x73x61x6ex6ax61x79** [opensourceBIM/BIMserver#715]
http://bimserver.org/wp-content/uploads/
http://bimserver.org/wp-includes/

An attacker is able to  see the directory structure

**Comment by rubendel** [comment]
Scary

**Comment by Lawri-van-Buel** [comment]
@reubendel I have seen you close these type of tickets for quite a long while now. 
and while there not tickets about BIMserver, they are exposing a serious misconfiguration on the wordpress site opensourceBIM uses. 

Industry standards and practises requires that you disable the index listings in web applications (such as wordpress) as it makes it trivial to abuse any injection vulnerability. (they can just go to the file and execute it) automated bots abuse these features for any number of unwanted / bad things.
Can you please kick who ever is doing System administration for you to get that site up to par with current Internet Security standards? These tickets / this situation looks bad and does not offer confidence in proper security practises for the BIMserver 'product'.

**Comment by x73x61x6ex6ax61x79** [comment]
http://bimserver.org/about/bug-bounty/

Do i get any swag or bounty for this vulnerability?

**Comment by x73x61x6ex6ax61x79** [comment]
Found three more entries for directory browsing enabled.

http://bimserver.org/wp-content/plugins/buddypress/
http://bimserver.org/wp-content/plugins/jetpack/
http://bimserver.org/wp-content/plugins/wp-super-cache/

**Comment by rubendel** [comment]
This isssue tracker still has nothing to do with that website. If the website causes you to become inconfident about the bimserver project, don't use it.

**Comment by Lawri-van-Buel** [comment]
@rubendel while your correct in that this issue tracker is not for the website, 
> If the website causes you to become inconfident about the bimserver project, don't use it.
Here you are basically saying that none should trust you, your work or this (or any) project from opensourcebim.  
In my opinion this is a very _**bad**_ statement to make **_ever_**! Trust on the internet is something you have to treasure, as its hard to get and easy to lose.

**Comment by rubendel** [comment]
I don't see why anyone would not trust me by me closing issues not related to a project. My job is to develop BIMserver and other opensource BIM projects. People can judge those efforts themselves, I don't think many are going to have a look at the website and see whether it has open directory listings.
