### ISSUE TITLE
Proxy Basic authorisation via user and password not supported (?)

### ISSUE THREAD

**Issue by Elsa-E4-user** [opensourceBIM/BIMserver#716]
Environment:
- CentOS Linux release 7.4.1708 (Core) Kernel version 3.10.0-514.26.2.el7.x86_64
- java:
	- openjdk version "1.8.0_161"
	- OpenJDK Runtime Environment (build 1.8.0_161-b14)
	- OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
- jetty: jetty-distribution-9.4.8.v20171121
- BIMServer 1.5.95 

ISSUE:
- installation stop with the following message ``` Installing all extended data schemas... ``` (image attached)
- relevant error in the log file: (log attached)
```2018-02-23 13:18:19,984 INFO [qtp670700378-12] o.b.JsonHandler [JsonHandler.java:72] {"request":{"interface":"ServiceInterface","method":"getAllRepositoryExtendedDataSchemas","parameters":{}},"token":"a77202bc55327ec52beebd196f495bd465ae600fde9d7f35e2817f822f2b930f27ea120dde47a9f41126f820b969361b"}
2018-02-23 13:18:19,985 INFO [qtp670700378-12] o.b.JsonHandler [JsonHandler.java:73]
org.bimserver.shared.exceptions.ServerException: Unhandled exception (java.io.IOException): Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required". See the server log for more details
```

ANALYSIS:
- verified network tracing - connection rejected due to ```missing credential``` (see file Network.log)
- JAVA properties ```http[s].proxyUser``` and  ```http[s].proxyPassword``` seems to be ignored 
(no Authenticator implemented? attached an example of possible implementation - zip file
[testAuthenticator.zip](https://github.com/opensourceBIM/BIMserver/files/1766667/testAuthenticator.zip)
)
cfr:
https://docs.oracle.com/javase/8/docs/technotes/guides/net/http-auth.html
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html 

Attachments:
[ProxyConnectionRefused.log](https://github.com/opensourceBIM/BIMserver/files/1766634/ProxyConnectionRefused.log)
[Network.log](https://github.com/opensourceBIM/BIMserver/files/1766637/Network.log)
![proxyfailure](https://user-images.githubusercontent.com/34245289/36782304-d4427de2-1c78-11e8-899b-b0dd8416224a.jpg)

**Comment by rubendel** [comment]
As noted in another issue [1], this is just too much work to support/test etcetera. I am working on a build that does not need the internet connection.

[1] https://github.com/opensourceBIM/BIMserver/issues/413
