### ISSUE TITLE
i can not found bimserver login page 

### ISSUE THREAD

**Issue by mohamedelbadry** [opensourceBIM/BIMserver#721]
hello .
 when i install bimserverjar-1.5.96.jar  and this page in this link only appear and i can't  go to login page [??](https://drive.google.com/file/d/1XuNnkGVXmqKK1ZonpuSgCjeLd8OJwQcn/view?usp=sharing)

**Comment by rubendel** [comment]
Seems like no plugins were installed during setup, can you try the setup process again and post the errors you see if there are any?
