### ISSUE TITLE
How does notification operate from JavaScript API ?

### ISSUE THREAD

**Issue by letis33** [opensourceBIM/BIMserver#724]
What's the procedure to be notified of a modification into BimServer project (new revision of an object for example) from a client using JavaScript API ?

Thanks

**Comment by rubendel** [comment]
The JavaScript API has a few methods, the arguments I think should speak for themselves. You can search for them in the BIMvie.ws code for an example.

Available calls:
BimServerClient.registerNewRevisionOnSpecificProjectHandler
BimServerClient.registerNewExtendedDataOnRevisionHandler
BimServerClient.registerNewUserHandler
BimServerClient.registerNewProjectHandler

etcetera

**Comment by Tristamoff** [comment]
How to add endpoint? Or get endpoint list?
