### ISSUE TITLE
POM snapshot missing for upcoming version

### ISSUE THREAD

**Issue by ger08061959** [opensourceBIM/BIMserver#725]
The POM for org.opensourcebim:bimserver:jar:1.5.99-SNAPSHOT is missing, no dependency information available.

Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600

Maven repository doesn't show any snapshots nor a version 1.5.99. Available is a 2.0.0 version POM

**Comment by rubendel** [comment]
The 2.0.0 was a mistake, it's an old version, we can't delete anything from Maven.
