### ISSUE TITLE
Compare 2 revisions

### ISSUE THREAD

**Issue by lmdat** [opensourceBIM/BIMserver#727]
How to compare 2 revisions in BimServer 1.5.96. I have 2 files ifc(called v1 & v2) and I need to know which are the objects in v1 file are deleted, edited or added in the v2 file?

**Comment by rubendel** [comment]
BIMserver provides the ability to write plugins that implement a compare algorithm. There are a few example compare algorithms in the IfcPlugins project.

You can execute the compare in two ways:
- https://thisisanexperimentalserver.com/apps/console?interface=ServiceInterface&method=compare This will return the results of the compare algorithm as structured data
- https://thisisanexperimentalserver.com/apps/console?interface=ServiceInterface&method=downloadCompareResults This will generate a topicId, which you can use to download a serialized version of the combined IFC model in which additions/removals are colored differently
