### ISSUE TITLE
BimServer Checkin Fails with IFC

### ISSUE THREAD

**Issue by alfredorods** [opensourceBIM/BIMserver#728]
Hi, ruben, my team works with navisworks.. they use a plugin to convert from navisworks to ifc but when i try to upload the modal if fails.. it returns null..

the plugin is:

http://www.codemill.fi/

what do u think about it? 

in my server i'm using the version 1.5.76 because we have another projects here.. but i download the last version to my local but doens't work.

Thanks.

**Comment by rubendel** [comment]
More info would be useful. Are there any errors in the BIMserver logfile (of the new version, the old version is too old to do fixes on anyways)? Can you perhaps share the IFC file, I don't have (or intend to) install Navisworks.

**Comment by alfredorods** [comment]
[Prueba 4.ifc.zip](https://github.com/opensourceBIM/BIMserver/files/1844544/Prueba.4.ifc.zip)

This is my file annd the error that i see is:

10:51:49 ERROR [LongCheckinAction]:                                                                                  (CheckinDatabaseAction.java:260) 
java.lang.NullPointerException: null
	at org.bimserver.ifc.IfcModel.fixInverseMismatches(IfcModel.java:989)
	at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:133)
	at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:65)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:713)
	at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:55)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:748)
10:51:49 ERROR [LongCheckinAction]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: null
	at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:261)
	at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:65)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:713)
	at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:55)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.bimserver.ifc.IfcModel.fixInverseMismatches(IfcModel.java:989)
	at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:133)
	... 6 common frames omitted
10:51:49 ERROR [Notifications processor]:                                                                                  (ProgressTopic.java:85) 
java.lang.NullPointerException: null
	at org.bimserver.notifications.ProgressTopic.updateProgress(ProgressTopic.java:61)
	at org.bimserver.notifications.ProgressNotification.process(ProgressNotification.java:36)
	at org.bimserver.notifications.Notification.run(Notification.java:45)
	at org.bimserver.notifications.NotificationsProcessor.run(NotificationsProcessor.java:39)
10:51:58 INFO  [org.bimserver.AdminInterface.getBimServerInfo]: Fetching online version info                                                     (VersionChecker.java:115)

**Comment by alfredorods** [comment]
i test it in the last version.

**Comment by gds2000** [comment]
same problem here (release 1.5.96)

reproducible with https://github.com/opensourceBIM/TestFiles/tree/master/TestData/data/example.ifc

seems that the fixes' "attribute" value is always null, so the attribute will be null as well, in method fixInverseMismatches()

in IfcModel.java @ line ~1051:

Fix(String relation, String attribute, String inverse, String[] subclasses){
	this.relation = relation;
	this.inverse = inverse;
	this.subclasses = subclasses;
}

**Comment by hlg** [comment]
If you are talking about line 989 in the current version of IfcModel.java, note that the attribute field is always set, just some lines before line 989.

Here however, I guess we are talking about line 989 in the 1.5.96 release code, not the line in the current version of the code.
https://github.com/opensourceBIM/BIMserver/blob/55373f877f948752847c780434eeca0518b95cc6/Shared/src/org/bimserver/ifc/IfcModel.java#L989

I can have a look into this.

**Comment by hlg** [comment]
Indeed. You are right. There is also a typo in the class names to be fixed and the fixes list is not exhaustive. As a temporary workaround you can use the streaming deserializer. It uses other code to fix the inverse relations.

**Comment by alfredorods** [comment]
If i use streaming deserializer i got this error:

![image](https://user-images.githubusercontent.com/16584082/37909274-15997488-30d0-11e8-9a03-cd132ca33d30.png)

**Comment by hlg** [comment]
There is an error in your IFC file, which you should file with Codemill.

    #4=IFCORGANIZATION($,$,$,$,$);
    #5=IFCPERSONANDORGANIZATION(#3,#4,$);
    #7=IFCORGANIZATION($,'Codemill Oy',$,$,$);

IfcPersonAndOrganization (`#5`) references an invalid IfcOrganization (`#4`, it has the mandatory label attribute not set) . There is an unused valid IfcOrganization (`#7`) which should probably be referenced instead.

**Comment by marknelissen** [comment]
Is there some additional check that has been recently added to BimServer? I am in the same situation, result of using the codemill conversion tool is not loading in 1.5.96. I don't say there isn't an issue with the generated IFC file, I'm just wondering why the same file is actually accepted and loaded by BimServer 1.4.0-FINAL-2015-11-04

**Comment by marknelissen** [comment]
@alfredorods , codemill seems to have published a fix for the generated data error. I am currently unable to verify the fix. Would you be able to test it?

You can download it at http://www.codemill.fi/download/IFCExporter2018.2.zip

**Comment by cacu100** [comment]
Hi @rubendel 
I'm trying to checkin a ifc model using the API with json options. I'm using the information provided on this link:
https://github.com/opensourceBIM/BIMserver/wiki/Checkin According with instructions on this. I'm using this typescript code to encode the file 
` public getBase64(file : File) : Promise<any> {`
`        return new Promise((resolve, reject) => {`
`         const reader = new FileReader();`
`         reader.readAsDataURL(file);`
`         reader.onload = () => resolve(reader.result);`
`         reader.onerror = error => reject(error);`
`       });`  
BIMserver says that the IFC header is wrong and the process doesn't stop. The checking process is still running. How can I kill or abort this process to restart the process, because while the current process is running I can't try again. If I try, the server says :
{"response":{"exception":{"__type":"UserException","message":"Checkin in progress on this project (topicId: 1), please try again later"}}}

**Comment by rubendel** [comment]
Seriously, this is a completely different issue, why are you hijacking old and closed issues?

**Comment by cacu100** [comment]
Thanks @rubendel, sorry for my mistake. I'm trying to solve this issue and I didn't find an answer on Bimserver documentation. I removed the thread.
