### ISSUE TITLE
ifcopenshell plugin fails to install from linux platform

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#729]
ruben, i have analysed the problem installing ifcopenshell plugin.
1) install fails from within bimserver or at the first run setup.
error message is "no executable found for the linux platorm" 

- OS name (from ServerInfo) = Linux
2) if i understand the plugin code right The lowercase OS name is compered as filter.
should be "linux"

error is reported in log file
best peter

**Comment by rubendel** [comment]
Can you please indicate which part of the sourcecode you are referring to? It seems to be alright here: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/blob/master/src/org/ifcopenshell/IfcOpenShellEnginePlugin.java#L84

**Comment by epeter-** [comment]
exactly the line of code i am referring to.
bimserver should - according to the code - recognize the linux platform while fetching ifcopenshell plugin.
in my version of bimserver (the latest) the error message during installation is like described before.
the plugin does not install.
serverinfo (OS) reports correctly
best peter

**Comment by rubendel** [comment]
Not sure why this issue auto-closed

**Comment by rubendel** [comment]
This has been overhauled lately, executes are now downloaded, please re-open if the problem persists.
