### ISSUE TITLE
How to get multiple geometries by dragging mouse

### ISSUE THREAD

**Issue by lzhoubimfoo** [opensourceBIM/BIMserver#731]
hello, I want to implement such a function: drag the mouse to get multiple geometries in this range. For example i opened a project that is a building model, I drag out a rectangle on the screen, how can I get all the geometries in the rectangular range. I know bimsurfer support mouse "pick", but I didn't found muti-select by dragging mouse. What should I do if I want to do this? Thanks!

**Comment by rubendel** [comment]
Please post this on the BIMserver issue tracker.
