### ISSUE TITLE
cant download je-7.4.5.jar with maven

### ISSUE THREAD

**Issue by Folgerjun** [opensourceBIM/BIMserver#734]
`		<dependency>
			<groupId>com.sleepycat</groupId>
			<artifactId>je</artifactId>
			<version>7.4.5</version>
		</dependency>`
**Missing artifact com.sleepycat:je:jar:7.4.5**

**Comment by rubendel** [comment]
This dependency is available on a maven repository hosted by Oracle. This is defined in https://github.com/opensourceBIM/BIMserver/blob/master/pom.xml#L16
```
<repository>
	<id>oracleReleases</id>
	<name>Oracle Released Java Packages</name>
	<url>http://download.oracle.com/maven</url>
	<layout>default</layout>
</repository>
```

Make sure you can access http://download.oracle.com/maven

**Comment by Folgerjun** [comment]
Thanks for your guidance

**Comment by shiyeling** [comment]
I got an error page from Oracle when accessing http://download.oracle.com/maven

![image](https://user-images.githubusercontent.com/3395635/40711379-99d052cc-642d-11e8-8335-5304e050cf40.png)


Seems the URL is accessible but the content has been moved? Any idea?

**Comment by nitin1706** [comment]
this page gives 404 error. @rubendel : can you please guide me for this dependency:
com.sleepycat:je:jar:7.4.5 
For me, this is coming from:
[INFO] +- org.apache.qpid:qpid-broker:jar:7.0.6:test
[INFO] |  +- org.apache.qpid:qpid-bdbstore:jar:7.0.6:test
[INFO] |  |  \- com.sleepycat:je:jar:7.4.5:test

**Comment by rubendel** [comment]
@shiyeling It's not an address that is supposed to be visited by a browser.

@nitin1706  We are not using qpid, are you sure your question has anything to do with BIMserver?

**Comment by DaddyMoe** [comment]
> This dependency is available on a maven repository hosted by Oracle. This is defined in https://github.com/opensourceBIM/BIMserver/blob/master/pom.xml#L16
> 
> ```
> <repository>
> 	<id>oracleReleases</id>
> 	<name>Oracle Released Java Packages</name>
> 	<url>http://download.oracle.com/maven</url>
> 	<layout>default</layout>
> </repository>
> ```
> Make sure you can access http://download.oracle.com/maven

Or for Gradle:

```
repositories {
    maven { url 'http://download.oracle.com/maven' } // to resolve com.sleepycat:je dependency
}
```

**Comment by tianjin500w** [comment]
who can share me a copy of  je-7.4.5.jar ? 3q

**Comment by libofeng** [comment]
https://download.oracle.com/maven/com/sleepycat/je/7.5.11/je-7.5.11.jar

**Comment by libofeng** [comment]
@tianjin500w 

https://download.oracle.com/maven/com/sleepycat/je/7.5.11/je-7.5.11.jar
