### ISSUE TITLE
The quantities list entries are not returned - IFCELEMENTQUANTITY.QUANTITIES

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#735]
Query:

{
	"types": ["IfcSpace"],
	"includes": ["validifc:AllProperties", "validifc:ContainedInStructure"]
}
...
#40= IFCRELDEFINESBYPROPERTIES('2yYYEXqATADA0l0w8n$9mn',$,$,$,(#1),#41);
#41= IFCPROPERTYSET('2yYYEXqATADA0l0g8n$9mn',$,'Abh\X\E4ngigkeiten',$,(#42,#43,#44,#45));
#45= IFCPROPERTYSINGLEVALUE('Versatz unten',$,IFCLENGTHMEASURE(0.),$);
#44= IFCPROPERTYSINGLEVALUE('Versatz Oberkante',$,IFCLENGTHMEASURE(2.4384),$);
#43= IFCPROPERTYSINGLEVALUE('Obergrenze',$,IFCLABEL('Ebene: EG00'),$);
#42= IFCPROPERTYSINGLEVALUE('Ebene',$,IFCLABEL('Ebene: EG00'),$);

#46= IFCRELDEFINESBYPROPERTIES('3CsEKq3M93puXUNLN6kgm6',$,$,$,(#1),#47);
#47= IFCELEMENTQUANTITY('1aiEYRoZz0eR6o32e8$bU1',$,'BaseQuantities','',$,());
...
The line shoul be
#47= IFCELEMENTQUANTITY('1aiEYRoZz0eR6o32e8$bU1',$,'BaseQuantities','',$,(#353827,#512092,#512093,#353828,#509009));

The quantities list entries are not returned. However, these are available.
What else must be added to the query so that the list is completely filled?

**Comment by rubendel** [comment]
Hi, this was missing from the "AllProperties" include, it's been added now
