### ISSUE TITLE
Issues installing online bimsever

### ISSUE THREAD

**Issue by CedricBell** [opensourceBIM/BIMserver#738]
I have installed a local bimserver with a .jar release but i don't know how to do it with a .war file ....
Is a .war version correctly installed will make project or files available for everyone who has a navigator ? 

Thanks in advance,

**Comment by rubendel** [comment]
Functionality is exactly the same, it's just the installation that's different. There are plenty of tutorials online if you want to run the WAR file for example on Tomcat.

**Comment by rubendel** [comment]
Just like any other server system, you have to bind to the right interface/ip, and in the case of BIMserver, set the "Site Addresss" setting accordingly (you can do that in the setup procedure).

**Comment by CedricBell** [comment]
so yes i have tried to change the site adress to http://pidrbellroudaut/bimserver but nothing happens on this page.

I have also tried to change it to http://myipadresse:8080/bimserver and i have make changes in server.xml to make my engine become not local but nothing happens...

I just can't manage to find a good tutorial :'(
