### ISSUE TITLE
Error Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror

### ISSUE THREAD

**Issue by CedricBell** [opensourceBIM/BIMserver#739]
I have this error when i try to go to : http://localhost:8080/bimserver/

Error Error: Script error for: bimserverapi_BimServerApiPromise http://requirejs.org/docs/errors.html#scripterror

And i wanted to know if i can have not a localhost version of a bimserver ?
Thank you for your help (i'm a beginner in bimserver)...

**Comment by CedricBell** [comment]
So i solved this roblem reading other issues but my second question about having a bim server "online " and not only in local still stand  ...

**Comment by rubendel** [comment]
Sure just bind to a public ip
