### ISSUE TITLE
Can not start bimserver from the bimserver.jar gui --> NoClassDefFoundError, JVM could not be loaded

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#744]
This is the error message I am getting
(Did not find a logfile so I had to screenshot it)
![screenshot_2](https://user-images.githubusercontent.com/1222525/38735481-308ebc14-3f29-11e8-9110-4049409d8429.png)
Thanks in advance!

**Comment by qc529491527** [comment]
Me too. NoClassDefFoundError. Have you solved this problem??

**Comment by Dakki97** [comment]
@qc529491527  As far as I know since that was a long time ago I either did not have the jvm path to default or I did not have Java 8 installed. This does not work if you do not use Java 8
