### ISSUE TITLE
BIMvie.ws Chechin -- there is no Deserializer can be used and no Upload Revision Button

### ISSUE THREAD

**Issue by LimingXu-notts** [opensourceBIM/BIMserver#745]
I have successfully started the BIMserver (bimserver-combined-1.5.100.jar), and add BIMvie.ws by manually uploading bimviews and its dependencies in the process of BIMserver installation because of "cannot connect to outside internet" error. 

The versions of plugins are (I use the latest versions at this moment): 
Bimvie.ws: bimviews-0.0.106.jar
Bimsurfer: bimsurfer-0.0.43.jar
Bimserverapi: bimserverapi-0.0.140.jar 

I can connect to the server by using: localhost:8082 and click bimviews link to enter the BIMvie.ws home page, then new a project, but when I click checkin, this is no Deserizalier options and Upload revision button, the screenshot is as follows: 

<img width="600" alt="screen shot 2018-04-16 at 10 41 50" src="https://user-images.githubusercontent.com/22269768/38788017-fbfaf9da-4163-11e8-8184-eaedab33a95c.png">

No other errors found either in javascript console and server console. I use Google Chrome. 

Can someone help me? Really appreciated.

**Comment by LimingXu-notts** [comment]
I reinstalled the combined version with and without checked the suggesting plugins, all output the information that "no plugin installed. 

When I checked the plugins (using the default options), it also outputs "no plugins installed because of no working out internet". I can find these plugins in the unzip folder of bimserver, but in the folder plugins under the "home" of bimserver, there are no plugins found. 

When I select "upload plugins from the file system", plugins can be successfully installed and accessed, but have the reported checkin problem. BTM, I am using below machine: 

<img width="468" alt="screen shot 2018-04-18 at 15 34 51" src="https://user-images.githubusercontent.com/22269768/38917690-19f5ad70-431e-11e8-9882-df050baddc8c.png">


Please see these screenshots: 

<img width="949" alt="screen shot 2018-04-18 at 15 27 40" src="https://user-images.githubusercontent.com/22269768/38917551-ad989d22-431d-11e8-88a7-afbf8a50ad31.png">
<img width="458" alt="screen shot 2018-04-18 at 15 25 24" src="https://user-images.githubusercontent.com/22269768/38917553-b14a50a0-431d-11e8-9aa2-bb3be759ad02.png">
<img width="527" alt="screen shot 2018-04-18 at 15 23 48" src="https://user-images.githubusercontent.com/22269768/38917558-b44281f6-431d-11e8-809b-db5286b401d3.png">
<img width="538" alt="screen shot 2018-04-18 at 15 18 42" src="https://user-images.githubusercontent.com/22269768/38917561-b756de64-431d-11e8-8e19-31a547cf3e51.png">

**Comment by sophiegonzalez3** [comment]
Hi there,

Was this p solve ? 

I'm also trying to install BIM server without internet connexion. Installation of package seemingly work at the set up (cf picture) but not all the plugins are present (cf picture) and when trying to explore in BIMvie.ws the following error keep coming :
 _ERROR [qtp898695324-61] o.b.JsonHandler [JsonHandler.java:178] org.bimserver.shared.json.ConvertException: java.lang.NumberFormatException: For input string: "false"_

By taking a closer look at the log during the set up process I notice that an error actually came along : 
_ERROR [PluginInterface.installPreBuiltPlugins] o.b.d.a.InstallPluginBundleFromBytes [InstallPluginBundleFromBytes.java:68]  java.lang.Exception: Required dependency ch.qos.logback:logback-classic is not installed_

I'm a java (and BIM for that matter)  neophyte but it seems like a dependencies pb and looking at the pom I don't see any call to any dependencies, also the file location BIMserver/home/mavench/qos/logback/logback-classic/1.2.3 is empty, when i guess something like the logback-classic-1.2.3.jar shall be ??

Is there something I did wrong or is it and installer pb ? 
I would really appreciate some help :)

Kind regards

![set succesful](https://user-images.githubusercontent.com/34275916/40001180-ed442fde-578d-11e8-9c3e-d90f6866664f.PNG)
![some plug in](https://user-images.githubusercontent.com/34275916/40001181-ed641556-578d-11e8-89c8-ff40424da6db.PNG)
