### ISSUE TITLE
Getting geocoordinates of all vertices

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#747]
Hi, so I am currently working on aquiring the geo coordinates from all vertices of parts such as walls etc. and was not able to find a method to aquire them. What i tried so far : getting the float matrices of 
`getData().getVertices` and `getGeometry().transformation` and transforming the vertices according to the corresponding matrix did not work. Next i tried working recursively through the relative placements but I don't really know how i should approach this. My approaches were taken from past issues.
Is there a simple way of achieving this or a simple workaround or do I have to learn linear algebra now ?
Thanks in advance!

**Comment by rubendel** [comment]
Any vertex transformed by the transformation matrix of the object will result in the final location of the given vertex within the model, nothing more is required, all the relative stuff is already accumulated in the matrix. You said it does not work, can you elaborate?

**Comment by Dakki97** [comment]
Thank you for the quick answer,

The code I used to transform my vertices is as follows:

```
            List<IfcWall> products = model.getAll(IfcWall.class);
            float[] coordinatematrix = null;
            for (IfcWall product : products) {
                exporter += product.getGlobalId() + "\n";
                if (product.getGeometry() != null) {
                    //  Transformation Matrix
                    float[] transformationmatrix = GeometryUtils.toFloatArray(product.getGeometry().getTransformation());
                    //  Coordinate matrix
                    coordinatematrix = GeometryUtils.toFloatArray(product.getGeometry().getData().getVertices());

                    //  Apply Transformation
                    Transform3D transform = new Transform3D(transformationmatrix);
                    for (int i = 2; i < coordinatematrix.length; i = i + 3) {
                        Point3f p = new Point3f(coordinatematrix[i - 2], coordinatematrix[i - 1], coordinatematrix[i]);
                        transform.transform(p);
                        exporter += p.x + ", " + p.y + ", " + p.z + "\n";
                    }
                }
            }
```
My transformation matrix for one object looks like this and for every other it is similar:
1zztGAbpPAFe7iHU1R3Vx7
0.0
0.0
0.0
1.875
0.0
0.0
0.0
0.0
0.0
-1.875
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.875
0.0
0.0
0.0
2.9296875
0.0
3.0078125
0.0
-2.625
0.0
1.875
My coordinatematrix for one element looks something like this:

7.0416665
0.22916667
0.0
7.0416665
0.22916667
50.0
0.0
0.22916667
0.0
0.0
0.22916667
50.0
0.0
0.22916667
0.0
0.0
0.22916667
50.0
0.0
-0.22916667
0.0
0.0
-0.22916667
50.0
0.0
-0.22916667
0.0
0.0
-0.22916667
50.0
7.0416665
-0.22916667
0.0
7.0416665
-0.22916667
50.0
7.0416665
-0.22916667
0.0
7.0416665
-0.22916667
50.0
7.0416665
0.22916667
0.0
7.0416665
0.22916667
50.0
7.0416665
0.22916667
0.0
0.0
0.22916667
0.0
0.0
-0.22916667
0.0
7.0416665
-0.22916667
0.0
7.0416665
0.22916667
50.0
0.0
0.22916667
50.0
0.0
-0.22916667
50.0
7.0416665
-0.22916667
50.0
This is the result for the first object:
1zztGAbpPAFe7iHU1R3Vx7
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, -0.4296875
1.875, 0.0, 0.4296875
1.875, 0.0, 0.4296875

**Comment by Dakki97** [comment]
My bad, wrote the issue as if it was a bug but it is more of a "how to" question 

What i further tried was changing the matrices to double arrays and changing the orientation of the matrix which resulted in a more logical output but some coordinates are absurdly high while some others are correct:
This is the current code:
```
            project = client.getServiceInterface().getProjectByPoid(project.getOid());
            ClientIfcModel model = client.getModel(project, project.getLastRevisionId(), true, false, true);
            List<IfcWall> products = model.getAll(IfcWall.class);
            for (IfcWall product : products) {
                exporter += product.getGlobalId() + "\n";
                if (product.getGeometry() != null) {
                    //  Transformation Matrix
                    double[] transformationmatrix = GeometryUtils.toDoubleArray(product.getGeometry().getTransformation());
                    //  Coordinate matrix
                    double[] coordinatematrix = GeometryUtils.toDoubleArray(product.getGeometry().getData().getVertices());
                    //  Apply Transformation
                    transformationmatrix=Matrix.changeOrientation(transformationmatrix);
                    Transform3D transform = new Transform3D(transformationmatrix);
                    for (int i = 2; i < coordinatematrix.length; i = i + 3) {
                        Point3d p = new Point3d(coordinatematrix[i - 2], coordinatematrix[i - 1], coordinatematrix[i]);
                        transform.transform(p);
                        exporter += p.x + ", " + p.y + ", " + p.z + "\n";
                    }
                }
            }
            ExportData("Edgevertices.txt");
```
The output now is 
-35471.15625, 33.000000049670554, 2.0615846215333334E11
27.5, 33.00000004967055, 2.0615846215333334E11
27.5, 33.00000004967055, 2.0615846215333334E11
27.5, 32.99999995032945, 2.0615852768933334E11
27.5, 32.99999995032945, 2.0615852768933334E11
-35471.15625, 32.999999950329446, 2.0615852768933334E11
-35471.15625, 32.999999950329446, 2.0615852768933334E11
-35471.15625, 33.000000049670554, 2.0615846215333334E11
27.5, 33.000000049670554, -12.0
-35471.15625, 32.99999995032945, -12.0
27.5, 33.000000049670554, 2.0615846215333334E11
-35471.1643409729, 32.99999995032945, 2.0615852768933334E11
2EsPdH4lT48RyaCrX1ZPuz
27.5, 32.99999995032945, 2097140.4876302085
27.5, 33.00000004967055, 2097141.4876302085
1.6106127635E9, 32.999999950329446, -12.0
5.3687106925E8, 32.999999950329446, 32756.007619222008
1.146443155E8, 32.999999950329446, -12.0
4.0544963609375E7, 32.999999950329446, 32756.007619222008
27.5, 32.999999950329446, -12.0
3.4672911735E9, 32.99999995032945, 2097140.4876302085
4.05449555E7, 33.00000004967055, -12.0
1.1464433171875E8, 33.000000049670554, 32756.023244222008
5.368709395E8, 33.000000049670554, -12.0
1.610613023E9, 33.000000049670554, 32756.023244222008
3.4672906515E9, 33.000000049670554, -12.0
27.5, 33.000000049670554, 2097141.4876302085
4.05449555E7, 33.000000049670554, -12.0
27.5, 33.00000004967055, -12.0
27.5, 32.999999950329446, 2097140.4876302085
3.4672911735E9, 33.00000004967055, 2097141.4876302085
3.4672906515E9, 33.000000049670554, -12.0
1.6106127635E9, 33.000000049670554, -12.0
1.610613023E9, 33.000000049670554, 32756.007619222008
1.6106127635E9, 33.000000049670554, -12.0
5.3687106925E8, 33.000000049670554, 32756.007619222008
1.610613023E9, 33.000000049670554, 32756.007619222008
5.368709395E8, 33.000000049670554, -12.0
5.3687106925E8, 33.000000049670554, 32756.007619222008
5.368709395E8, 33.000000049670554, -12.0
1.146443155E8, 33.000000049670554, -12.0
1.1464433171875E8, 33.000000049670554, 32756.007619222008
1.146443155E8, 33.000000049670554, -12.0
4.0544963609375E7, 33.000000049670554, 32756.007619222008
1.1464433171875E8, 33.000000049670554, 32756.007619222008
4.05449555E7, 33.000000049670554, -12.0
4.0544963609375E7, 33.000000049670554, 32756.007619222008
3.4672906515E9, 33.000000049670554, 2097141.4876302085
3.4672906515E9, 32.999999950329446, 2097140.4876302085
