### ISSUE TITLE
Json schema for serviceinterface?

### ISSUE THREAD

**Issue by ackerball** [opensourceBIM/BIMserver#748]
hi,
is there a json schema for the interfaces which are used in the console (webservice url: /json) ?
where can i get a template or how can you generate a template for the request for each interface method?

thanks in advance for an answer or a hint.

frank

**Comment by rubendel** [comment]
The Console application is a perfect place to start looking for this information. Just have a look at the calls that are done during startup (hint, only one call is used: MetaInterface.getAllAsJson). All the calls you might need for this are in the "MetaInterface" interface.

**Comment by akuckartz** [comment]
Will JSON-LD be supported ?

**Comment by rubendel** [comment]
No, I don't see how that would work since "JSON-LD is a method of encoding Linked Data using JSON". The original data is not linked data...

**Comment by akuckartz** [comment]
Depending on the JSON documents they can be converted to Linked Data by "simply" providing JSON-LD contexts.

**Comment by rubendel** [comment]
Yet I still don't see how a JSON based RPC API would become more useful if linked to Linked Data contexts (those would have to be created first because I don't think there are already "Revision", "Project", "User" etcetera linked data concepts).
