### ISSUE TITLE
Query stack size > 10000, probably a bug, please report

### ISSUE THREAD

**Issue by rflsc** [opensourceBIM/BIMserver#752]
BIMserver 1.5.100 returned "Query stack size > 10000, probably a bug, please report" when I tried to checkin an IFC file. The same file works on previous versions of the server like 1.5.85. Is that a bug? I can send my file.

![erro_bimserver](https://user-images.githubusercontent.com/6164096/39344643-ee483c7c-49b9-11e8-8dfe-2822d4ff3222.png)

**Comment by rubendel** [comment]
That would be great, can you send it (or a link to it) to ruben@logic-labs.nl?

**Comment by rubendel** [comment]
I don't think I received a file, please correct me if I am wrong.

**Comment by rflsc** [comment]
Sorry, I forgot to send the file to you. The problem still remain on the last version of BimServer. By the way, congratulations for the awesome work.

Thanks from Brazil.



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Ruben de Laat <notifications@github.com>
Enviado: Monday, May 14, 2018 4:47:14 AM
Para: opensourceBIM/BIMserver
Cc: rflsc; Author
Assunto: Re: [opensourceBIM/BIMserver] Query stack size > 10000, probably a bug, please report (#752)


That would be great, can you send it (or a link to it) to ruben@logic-labs.nl<mailto:ruben@logic-labs.nl>?

**Comment by rubendel** [comment]
Thanks, it looks like a bug in BIMserver indeed, might take some time to fix this one.
