### ISSUE TITLE
how to storage the information read from ifc file using redis/MySQL 

### ISSUE THREAD

**Issue by zyjiang0571** [opensourceBIM/BIMserver#759]
Please use ``` your code ``` to escape code and use the "Preview" button to see whether your issue is readable. Also, when relevant, please note your BIMserver version.
When posting logfiles, please post the actual text, and not screenshots of the log files. Also logfiles with no error messages whatsoever are usually not very useful.

**Comment by rubendel** [comment]
You would use a programming language to write a program that reads the information from the IFC file using a parser. Then you'd use the appropriate database drivers for Redis/MySQL to store the data. For all this you'd first need to learn to write software. No idea what this generic programming question has to do with BIMserver.
