### ISSUE TITLE
Not able to run  Checkin IFC file code

### ISSUE THREAD

**Issue by vikaskallidantheyil** [opensourceBIM/BIMserver#762]
Hi i am new to bim server but was not able to run  Checkin IFC file code 
 i am getting error while importing ;
import org.bimserver.plugins.services.Flow;
 and below is a link of the code

https://github.com/opensourceBIM/BimServerJavaClientDemo/blob/master/BimServerJavaClientDemo/src/org/opensourcebim/clientdemo/CheckinIfcFile.java

**Comment by berlotti** [comment]
That code is from 2016. It is not updated to the latest version of the API.
