### ISSUE TITLE
How to start the Stand-alone BIMserver

### ISSUE THREAD

**Issue by wnstss** [opensourceBIM/BIMserver#763]
Hello, everyone

I am interested in BIMserver. Referring to the Get Started Quick Guide, I started  the Stand-alone BIMserver as shown in the following figure. 
![bimserver_starter](https://user-images.githubusercontent.com/28221136/41035948-48e7a292-69c9-11e8-8c12-4cb83639cd78.png)
Because no HOME folder was created, I created a new Home folder- C:\BIMServer\home. 

How to fill in the JVM field? How to start the BIMserver?
Could anyone give me some help?

With Best Regards,

Lei

**Comment by berlotti** [comment]
Maybe try to use \ instead of ¥ ?

**Comment by wnstss** [comment]
Hi, berlotti
Thank you very much for your reply.
When I clicked the Browse button, It seemed I can not input \ in the Home directory field.
As there is no file in the C:\BIMServer\home directory. Should I copy some  folders under the following directory?
C:\BIMServer\bimserverjar-1.5.101

What does the JVM mean?

Could you give me some more help?

Thanks in advance.

Best regards,

Lei

**Comment by berlotti** [comment]
use the 'browse' button to select the directory.
Manually copying files is not a good idea
