### ISSUE TITLE
Checkin with multiple ifc files one time

### ISSUE THREAD

**Issue by m7567** [opensourceBIM/BIMserver#764]
Hi,
Now we can only upload one single file with Checkin function , I'm wondering how to do with multiple files.
let's say 1000 files . That's not easy to  upload and then download 1000 times

**Comment by rubendel** [comment]
I assume you are using the API? Most programming languages provide the concept of loops...

**Comment by m7567** [comment]
Hi,rubendel

Thank you so much for your reply.  Actually I don't know how to use the API till now and it does not give me any example. 
Do you have any codes about this?

http://localhost:8080/bimserverwar/apps/console/
