### ISSUE TITLE
How does BimSurfer Or BimVie.ws  can render multiple models on same scene or canvas?

### ISSUE THREAD

**Issue by dishesh** [opensourceBIM/BIMserver#766]
Hello BimTeam !
- it is not an issue, only kind of question.

In BimVie.ws page when a project has multiple models , we can download them either separately clicking on each of the eye or we can download ( may be merge ? ) by clicking on eye associated with main project name. In both the case it seems that the canvas is same. I want to know how can we share one canvas between multiple scene ? 

Is there a hierarchy of canvases or scenes ? Any one who knows please help me understand this. If possible please share some code. 

Thanks and regards,
Dishesh.

**Comment by rubendel** [comment]
Not a BIMserver issue
