### ISSUE TITLE
what does VirtualObject.eUnset do?

### ISSUE THREAD

**Issue by hanl754** [opensourceBIM/BIMserver#768]
hey, professor. could you please explain this code? I dont understand...thanks!
```java
if (useUnsetBit(feature)) {
	int pos = featureCounter / 8;
	byte b = buffer.get(pos);
	b |= (1 << (featureCounter % 8));
	buffer.put(pos, b);
} 
```

**Comment by rubendel** [comment]
This puts a bit at the right position in "buffer" that indicates whether the given "feature" is set or unset. Later on, this saves us from potentially allocating space for features that are not set (which happens a lot in IFC). When not doing this, a null-reference for example would take up 8 bytes (long), now it only takes us 1 bit.

**Comment by hanl754** [comment]
oh, yes!thank you very much.

**Comment by hanl754** [comment]
hi，professor!
Could you please tell me why we put a '-rid' here?
``` java
private ByteBuffer fillKeyBuffer(ByteBuffer buffer, int pid, long oid, int rid) {
	buffer.position(0);
	buffer.putInt(pid);
	buffer.putLong(oid);
	buffer.putInt(-rid);
	return buffer;
}
```

**Comment by rubendel** [comment]
Sure, all keys in BerkeleyDB are ordered lexicographically. The rid's count up in value for each revision. When traversing the database, we are usually interested in the latest version of each object (e.a. latest revision), so by storing them negated, we have to look at less objects (which improves performance).
