### ISSUE TITLE
Specific IFC config for AutoCAD MEP files?

### ISSUE THREAD

**Issue by acgut** [opensourceBIM/BIMserver#771]
Hello, currently using v1.5.76. 

I'm trying to upload 2 IFC files: 
- AMEP 
- Revit

The files upload and I can see them with no problems by separate, but when I try to upload both files to the same project the elements from the dwg don't show. 

Do I need an specific config when exporting from dwg to IFC?

Thanks!

**Comment by rubendel** [comment]
Uploading 2 files to the same project will make 2 revisions. By default only the last revision is shown. What you could do is create 1 project with 2 subprojects and checkin the 2 files in the two respective subprojects. When you now visualize the main project, both should show.
