### ISSUE TITLE
Run the LocalDevBimServerStarter method to start the bimserver

### ISSUE THREAD

**Issue by lihongju** [opensourceBIM/BIMserver#773]
The first time I can go to the Settings page and no plug-ins are installed.But I forgot the username and password.I want to go back to the Settings page,delete the generated tmptestdata folder,contains the database folder.And then run the LocalDevBimServerStarter method again.But skipped the Settings page I first entered.
Run the LocalDevBimServerStarter method,What should I do to reset the bimserver?

**Comment by rubendel** [comment]
The LocalDevBimServerStarter is meant for developers, who are lazy. So what it does is setup a generic BIMserver for you, with a default username/password. If you are really fast though, you can get to the setup screen before LocalDevBimServerStarter starts the setup procedure, so I guess that's what happened the first time. You can also disable this code in LocalDevBimServerStarter if you want to go through the setup procedure.
