### ISSUE TITLE
Websocket error on login

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#778]
Version .101

configuration apache2 with ajp13 workers installed
bimserver is subdomain.
as an example: 
https://serverfault.com/questions/740534/apache-webserver-tomcat-runing-multiple-tomcat-webapps-and-apache-webserver

1) enter username & pwd = login successful, a blink later websocket error.

what shall i consider in my installation?
tx peter

**Comment by rubendel** [comment]
Have you enabled websockets in Apache?
