### ISSUE TITLE
Getting error when trying to use 3D option for a test project in BIMvie.ws

### ISSUE THREAD

**Issue by azOn2018** [opensourceBIM/BIMserver#783]
This is somewhat a continuation of a previously posted issue https://github.com/opensourceBIM/BIMserver/issues/774#issuecomment-404032135 . The error I am referring to is coming up in BIMserver development mode. Please note the following version info:

Chrome v67.0.3396.99 by running LocalDevBimServerStarter from Eclipse (BimServer v1.5.103-SNAPSHOT) and including three plugins using -plugins in Arguments: bimviews-0.0.106, bimsurfer-0.0.43 and BIMserver-JavaScript-API. Some other plugins were installed through BIMvie.ws as well.

For a sample project, a two storey office building, when I try to view the geometry by clicking on the 3D option, 'Loading Two storey office....' message came up but noting happened afterwards. The BIMserver
Console shows the following error: 

**ERROR [Streamer 2]:                                                                                  (BimServer.java:221) 
java.lang.AbstractMethodError: org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.close()V
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:134)**

Please see the attached screen shot

![3d-option-bimvie ws- error](https://user-images.githubusercontent.com/40860221/42944891-c6d9ed98-8b5e-11e8-8437-b0c55db9f9b9.png)

Please note, in a different BIMserver mode i.e. using executable BIMserver jar v1.5.101, I didn't have the same problem.

**Comment by phiqus** [comment]
I've encountered the same problem, tried several versions for the deserialiser plug-in, still no solution. Any progress? Cheers

**Comment by azOn2018** [comment]
Due to recent hard disk failure I had to reinstall everything on the new hard disk. I went through the steps but the reported issues are still there. So this time, for a sample project, a two storey office building, when I try to view the geometry by clicking on the 3D option, 'Loading Two storey office building....' message came up but nothing happened afterwards. There are no error messages on the web browser Chrome console but BIMserver Console shows the following error (quite similar to the one previously reported):

**ERROR [pool-1-thread-2]:                                                                                  (BimServer.java:224) 
java.lang.AbstractMethodError: org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.close()V
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)**

Frustrating really.

**Comment by rubendel** [comment]
So you are running a BIMserver from GIT master, with older plugins. Then you get a very clear exception that says that a method is missing (the close method). This method has been added to the BinarySerializers (git master) 4 months ago... The latest release of the BinarySerializers plugin is somewhere in 2017...

In other words: Use the latest version (from GIT) of BinarySerializers.

**Comment by azOn2018** [comment]
OK to test this option, I cloned the BinarySerializers plugin and added it using -plugins in the Arguments. The plug-in v0.0.28-SNAPSHOT was installed but the issue is still there. However, the error message coming up now in BIMserver console is the following:

**ERROR:                                                                                  (BimServer.java:226) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeGeometryData(BinaryGeometryMessagingStreamingSerializer.java:506)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeData(BinaryGeometryMessagingStreamingSerializer.java:388)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeMessage(BinaryGeometryMessagingStreamingSerializer.java:291)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)**

**Comment by phiqus** [comment]
I tried all configurations since Friday, I just don't understand how in a deployed version is works just fine no errors, with older versions of the code, just made this thread when using those older versions, getting stuck before the geometry step #800. I also just realised you were experiencing a very similar problem #774 .

**Comment by rubendel** [comment]
Ah this last error I worked on today, was introduced a week ago

**Comment by azOn2018** [comment]
Thanks Ruben. After updating BIMsurfer v1, 3D view option is now working.
