### ISSUE TITLE
checking with API

### ISSUE THREAD

**Issue by re1995** [opensourceBIM/BIMserver#785]
I'm a beginner programmer...I don't know how to checkin with the second way of this page:
[https://github.com/opensourceBIM/BIMserver/wiki/Checkin](url)
I use c# for programming and this is a sample of my code for login:
` 

private void button1_Click(object sender, EventArgs e)
        {
         var baseAddress = "http://IPAddress/json";
         var requ = @"{""request"":{""interface"":""AuthInterface"",""method"":""login"",""parameters"":{""username"":""(((username)))"",""password"":""(((password)))""}}}";
        var http = (HttpWebRequest)WebRequest.Create(new Uri(baseAddress));
        http.Accept = "application/json";
        http.ContentType = "application/json";
        http.Method = "POST";

        string parsedContent = requ.Replace("(((username)))", textBox3.Text).Replace("(((password)))", textBox4.Text);
        ASCIIEncoding encoding = new ASCIIEncoding();
        Byte[] bytes = encoding.GetBytes(parsedContent);

        Stream newStream = http.GetRequestStream();
        newStream.Write(bytes, 0, bytes.Length);
        newStream.Close();

        var response = http.GetResponse();

        var stream = response.GetResponseStream();
        var sr = new StreamReader(stream);
        var content = sr.ReadToEnd();
        textBox2.Text = content;
        int responselength = content.Length;
        string response1 = content.Substring(23, responselength - 26);
        textBox7.Text = response1;
            }
`
please send a sample code like this for checkin!

**Comment by rubendel** [comment]
Try reformatting your issue so it's readable, this will increase the changes of somebody responding to it. So far I haven't seen any C# developers on this issue tracker though...

**Comment by rubendel** [comment]
Closing for now, I don't think there are any C# devs reading this tracker.
