### ISSUE TITLE
drupal 7 module

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#795]
im releasing the drupal module i have been developing for my project. its a trimmed down version from the version i actually have which has lotsa project specific requirements and 3rd party libraries. if you enabled all module and submodules, you can already create a project in drupal and have them created and ifc file checkin to your bimserver. its work in progress. codes are still messy. still trying to figure out the best workflow to checkin and show the progress.

comments are more than welcome.

[sandbox project](https://www.drupal.org/sandbox/halmsx/2988066)

**Comment by akuckartz** [comment]
What about Drupal 8 ?

**Comment by halmsx** [comment]
at the moment still busy with current project and we are expecting our 2nd baby anytime soon. so earliest could be 3-4 months.

**Comment by rubendel** [comment]
Cool! Closing this issue though because it's not a "todo" item
