### ISSUE TITLE
Error with console 

### ISSUE THREAD

**Issue by ihabhamzi** [opensourceBIM/BIMserver#797]
I kindly ask some body to help me get this request with console 

![image](https://user-images.githubusercontent.com/37119958/43789471-53038444-9a70-11e8-852d-d3db5008721b.png)

**Comment by rubendel** [comment]
The number 1 (one) is definitely not a valid roid. Roid stands for Revision ObjectID. You can get this ID using various methods, for example ServiceInterface.getProjectByPoid (the field is called revisionId).
