### ISSUE TITLE
BIMserver the memory of the server is not released

### ISSUE THREAD

**Issue by jiajiapang** [opensourceBIM/BIMserver#798]
After the upload model is resolved, the memory of the server is not released. The background is 24G memory.

**Comment by jiajiapang** [comment]
Somebody help me

**Comment by rubendel** [comment]
Which version? Are you actually hitting the 24GB limit? Does it crash with an OutOfMemory error?

**Comment by jiajiapang** [comment]
1.5.100，Opening a model page, background memory will be occupied, even if the page is closed, memory is still occupied, can only manually free memory.

**Comment by rubendel** [comment]
Your sentences make no sense, what is background memory? You realize you are posting on the BIMserver issue tracker right? So what do you mean with pages?

**Comment by jiajiapang** [comment]
background memory is Linux memory,page is 3D Model Display Page,and When I upload the IFC model file, there is also a problem of not releasing large amounts of memory
