### ISSUE TITLE
Geometry is mess

### ISSUE THREAD

**Issue by guci314** [opensourceBIM/BIMserver#80]
I create a  parent project ,and add two child project ,upload this file http://pan.baidu.com/s/1gdkk5Th  to  child1 project,  and upload this file http://pan.baidu.com/s/1cLymk  to child2 project,  then  in parent project click view 3d model, child2's shape is disappeared in the parent 3d model.

How can fix this.

**Comment by howlDream** [comment]
guci314，可以把能用的版本发给我吗？？
