### ISSUE TITLE
BIMviews not loading on localhost [Eclipse debug]

### ISSUE THREAD

**Issue by phiqus** [opensourceBIM/BIMserver#800]
Hi guys,
See below and let me know if you have any ideas:
_**Context description**_
I’ve been trying to get the basic setup in Eclipse running the BIMserver in debug mode, and have been following the instructions on the wiki. 
We have already a deployed BIMserver [1.5.95] instance on Linux, with tomcat, which works just fine (with the plug-ins versions shown below). The idea is to simulate the same environment (so same versions of modules) on Eclipse so I can develop and test a new plug-in.

![pic1](https://user-images.githubusercontent.com/42200050/43851642-80ac7772-9b3b-11e8-8587-3feead707510.png)

_**Problem encountered**_
BIMviews module stuck at loading.... see below
When I set up the same configuration in eclipse (see figure below), I then run the “LocalDevBimServerStarter” java app, no errors, runs fine when I check it in “localhost:8080”. 

![pic2](https://user-images.githubusercontent.com/42200050/43851647-859d2c86-9b3b-11e8-9799-2f38c33bcdea.png)

_**Observations so far**_
As soon as I click on BIMviews, the application is stuck at the loading page:

1)	Related to bimserverclient.js
Failed to load resource: the server responded with a status of 404 (Not Found):
http://localhost:8080/bimserverjavascriptapi/bimserverclient.js?_v=0.0.140

2)	Related to localhost/
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module:
http://localhost:8080/bimserverjavascriptapi/bimserverclient.js?_v=0.0.140 

![pic3](https://user-images.githubusercontent.com/42200050/43851656-8a10dc40-9b3b-11e8-9505-97ec299f65f6.png)

We can also notice that the BIMviews app is not fully loadead (no javascript files present), as opposed to the deployed version, where all modules load and work correctly together. Same version of jre [1.8.0_151] is used in both cases. Running Chrome Version 66.0.3359.181 (Official Build) (64-bit).

_### Why not use newer versions of modules you ask?_
-	I have tried using the [master] branches from git, then the problem is solved. However, I then get stuck at the point when the geometry is not rendered. As discussed in this thread #783 
-	However, I am constrained to use these older versions for future deployment. 

**_Thanks for your time, any help would be much appreciated._**

**Comment by rubendel** [comment]
Is the BIMserverJavaScript API installed?

**Comment by phiqus** [comment]
yes, just checked. it seems to be intalled okay, all .js files are present in the app on chrome. however it's not loaded when I try to load the BimViews plugin, as shown above in the chrome console.

**Comment by rubendel** [comment]
It is looking in the wrong place, it should be at http://localhost:8080/apps/bimserverjavascriptapi/, but it's trying to load from http://localhost:8080/bimserverjavascriptapi/.

It seems as if you checked out a specific version of the JavaScript API (0.0.140), any reason for that?

**Comment by rubendel** [comment]
I don't think it is different. Are you using a specific version of BIMvie.ws as well? Because the GIT version uses the setting in the settings.js, which is "/apps/bimserverjavascriptapi"

**Comment by phiqus** [comment]
yes, I was trying BIMvie.ws [0.0.106], I just chaged to [master] and works fine.
It seems to have solved the geometry generation step I was experiencing previously, where the engine would not render the model. see the current configuration below:

![pi6_repositories](https://user-images.githubusercontent.com/42200050/43887193-58f70c96-9bbe-11e8-98c6-3012b9d128f0.png)


I think this solves my problems just fine.

Thanks Rubendel so much! 👍 

**Summary of solving the problem:**

Running BIMserver [1.5.95] with all its dependent plug-ins, it works in the git configuration above,
also works fine with BIMserverJavaScriptAPI [0.0138].
It loads the interface [encountered problem] only with BIMvie.ws [0.0.107] and any BIMserverJavaScriptAPI package, BUT it doesn't load geometry at all, unless BIMserverJavaScriptAPI [0.0139] or lower is used, in this configuration setup.

Thanks again Rubendel for your help, much appreciated.
