### ISSUE TITLE
where can find the describe of the query(String)

### ISSUE THREAD

**Issue by ideabobo** [opensourceBIM/BIMserver#801]
the query parameter of the download method like "queries": [
    {
      "type": "IfcProject",
      "includes": [
        "IsDecomposedByDefine",
        "ContainsElementsDefine"
      ]
    },
    {
      "type": {
        "name": "IfcRepresentation",
        "includeAllSubTypes": true
      }
    },
    {
      "type": {
        "name": "IfcRepresentationItem",
        "includeAllSubtypes": true
      }
    },
    {
      "type": {
        "name": "IfcProductRepresentation",
        "includeAllSubtypes": true
      }
    },
    {
      "type": "IfcPresentationLayerWithStyle"
    },
    {
      "type": {
        "name": "IfcProduct",
        "includeAllSubtypes": true
      }
    },
    {
      "type": "IfcProductDefinitionShape"
    },
    {
      "type": "IfcPresentationLayerAssignment"
    },
    {
      "type": "IfcRelAssociatesClassification",
      "includes": [
        {
          "type": "IfcRelAssociatesClassification",
          "field": "RelatedObjects"
        },
        {
          "type": "IfcRelAssociatesClassification",
          "field": "RelatingClassification"
        }
      ]
    },
    {
      "type": "IfcSIUnit"
    },
    {
      "type": "IfcPresentationLayerAssignment"
    }
  ] 

I want known the describe of types like IfcRepresentationItem 
thanks!

**Comment by rubendel** [comment]
We'll write the documentation once there is a 1.5 release, until then it's under development.

**Comment by ideabobo** [comment]
thanks
