### ISSUE TITLE
How to call javascrptapi out side of bimserver?

### ISSUE THREAD

**Issue by sathishsanthoshsusidhar** [opensourceBIM/BIMserver#802]
Hai,

I run BIMServer port8082 and i call js files my another web site but its not working. It shows below errors

"Access to Script at 'http://localhost:8082/apps/bimserverjavascriptapi/bimserverapipromise.js' from origin 'null' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:8082' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access."

**Comment by rubendel** [comment]
This is a very generic error, not specific to BIMserver. Search for CORS in a search engine and you'll find an explanation.
