### ISSUE TITLE
Where are these HTML page templates?

### ISSUE THREAD

**Issue by somebodyZw** [opensourceBIM/BIMserver#805]
Who can tell me in which code these HTML pages are generated,I'd like to make some adjustments to what's in use;
![20180816093616](https://user-images.githubusercontent.com/42363949/44182074-d72b1c00-a137-11e8-83e5-3629a03a16fa.png)

**Comment by somebodyZw** [comment]
i finde it ,but now ,I have a new problem：I changed the HTML template. How do I import it into BIMServer？

**Comment by SubashJanarthanan** [comment]
@somebodyZw Can you please explain us how did you find those HTML pages like basicserversettings.html and others, because we were not able to find those in server code. Thanks in advance

**Comment by somebodyZw** [comment]
@SubashJanarthanan  They're in the jar called bimviews,Unzip it,You will find them.

**Comment by SubashJanarthanan** [comment]
@somebodyZw Thanks ..
