### ISSUE TITLE
Acquiring IfcCartesianPoint of IFCSite

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#806]
I am trying to get the position of IfcSite. This is the correct 
![image](https://user-images.githubusercontent.com/1222525/44211265-dbbbf880-a168-11e8-9f59-e3d9edc4ab34.png)
My approach is           

```
  List<IfcSite> site = model.getAll(IfcSite.class);
            double elevation = site.get(0).getRefElevation();
            IfcAxis2Placement3D placement= (IfcAxis2Placement3D) site.get(0).getObjectPlacement().getReferencedByPlacements().get(0).getRelativePlacement();
            IfcPlacement place = placement;
            System.out.println(place.getLocation());
            placement.getLocation().getCoordinates().forEach((value) -> {
                System.out.println(value);
            });


```
but this returns 0,0,0 for some reason.
I followed the description and tree of buildingsmart-tech

**Comment by rubendel** [comment]
Have you verified that the relative placement tree is exactly this deep and not deeper?
You could throw in a loop or some recursion for example

**Comment by Dakki97** [comment]
In my case the relative placement tree does not stop

I tried to use this approach

   ```
         List<IfcSite> sitelist = model.getAll(IfcSite.class);
            IfcSite site = sitelist.get(0);
            IfcLocalPlacement placement = site.getObjectPlacement().getReferencedByPlacements().get(0);
            while(placement.isSetPlacementRelTo()){
                 placement = placement.getPlacementRelTo().getReferencedByPlacements().get(0);
            }
            IfcPlacement place = (IfcAxis2Placement3D)placement.getRelativePlacement();
            place.getLocation().getCoordinates().forEach((value) -> {
                System.out.println(value);
            });
```

**Comment by hlg** [comment]
`ReferencedByPlacement` is the inverse attribute of `PlacementRelTo`. You code seems to go in circles. Try to remove the ` getReferencedByPlacements()` calls.

**Comment by Dakki97** [comment]
Thanks for the tip!
I checked the relations
![image](https://user-images.githubusercontent.com/1222525/44526730-2f888d80-a6e5-11e8-857b-7339c0900d7e.png)
and edited my code according to the relations
```
            IfcSite site = sitelist.get(0);
            IfcLocalPlacement localplace = (IfcLocalPlacement)site.getObjectPlacement();
            IfcPlacement place = (IfcAxis2Placement3D)localplace.getRelativePlacement();
            place.getLocation().getCoordinates().forEach((value) -> System.out.println(value));

```
It now prints out the correct values.
