### ISSUE TITLE
How do I upgrade the bimserver and keep the data

### ISSUE THREAD

**Issue by ideabobo** [opensourceBIM/BIMserver#809]
How do I upgrade the bimserver and keep the data,i want to upgrade the bimserver and keep the data.Seamless upgrade

**Comment by ideabobo** [comment]
thanks ,I found the method to migration data from old bimserver at #432 ,but the poid is changed,how can i make poid the same ,because i want use poid to do many things

**Comment by rubendel** [comment]
Not possible, as described in multiple issues
