### ISSUE TITLE
how can i install plugins offline

### ISSUE THREAD

**Issue by ideabobo** [opensourceBIM/BIMserver#810]
How do I install plug-ins offline ,because in setup page i have an network error "Your BIMserver does not seem to have a working outgoing internet connection." so i want to install plugins off line ,please help me thinks

**Comment by ideabobo** [comment]
i means if on the setup page,i don't select the plugins jar pakage,Where will I find the installation interface in the future

**Comment by ideabobo** [comment]
In other words, how to reinstall the plugin

**Comment by rubendel** [comment]
It's not available afterwards (not if you didn't install BIMvie.ws). So after that it's only available as an API call, which requires programming to install plugins. The only other option is to just remove the home directory and do the setup process again.
