### ISSUE TITLE
getAvailableClassesInRevision ClassCastException

### ISSUE THREAD

**Issue by ideabobo** [opensourceBIM/BIMserver#811]
when i call getAvailableClassesInRevision this method i found {
  "response": {
    "exception": {
      "__type": "ClassCastException",
      "message": "The value of type 'org.eclipse.emf.ecore.impl.EClassImpl@3f3c7bdb (name: IfcElementAssembly) (instanceClassName: null) (abstract: false, interface: false)' must be of type 'org.eclipse.emf.ecore.impl.EClassImpl@4c060c8f (name: IfcSpatialStructureElement) (instanceClassName: null) (abstract: false, interface: false)'"
    }
  }
}

**Comment by rubendel** [comment]
Thanks for reporting, this has now been fixed, will be in the next release.
