### ISSUE TITLE
Missing objects in model in IFC4

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#815]
In some of our IFC4 models, we have a lot of missing geometries, most of them are `IfcPipeSegment``. 

In the geometry generation report, it says:

```
java.lang.Exception: Missing objects in model (145, 147, 149, 134, 151, 137, 153, 139, 141, 143)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:583)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

I checked the generated debug IFC files. If I generate the geometries for those using IfcOpenshell, it results in a correct geometry. But in BimServer they are all missing.

The model renders correctly with solibri model viewer, Although I'm not sure if its completely valid.

I've attached the Geometry Generation report.

[Projekt_Lueftung_IFC4_generation_report.zip](https://github.com/opensourceBIM/BIMserver/files/2347596/Projekt_Lueftung_IFC4_generation_report.zip)

**Comment by rubendel** [comment]
Can you share the IFC4 file? IfcOpenShell has recently been updated in BIMserver, a lot less errors.

**Comment by rubendel** [comment]
Can you please confirm this is still a problem in 1.5.109?

**Comment by stestaub** [comment]
The issue seems to be fixed now, thank you very much!
