### ISSUE TITLE
InvalidGuidException

### ISSUE THREAD

**Issue by achudov** [opensourceBIM/BIMserver#823]
Hello, I have deployed bimserverwar-1.5.101 on tomcat. Trying to checkin .ifc file using web console interface (json). I get same exception everytime "org/bimserver/shared/InvalidGuidException". I have tried a couple of different models and from official business smart website as well.

**Comment by shubhambansal500** [comment]
i get the same exception in 1.5.101

**Comment by shubhambansal500** [comment]
@rubendel can you please provide some solution ? even i am facing this issue while uploading any IFC file , the default one or by checking through the code. "InvalidGuidException"

**Comment by rubendel** [comment]
Does it work in BIMvie.ws?

**Comment by shockk** [comment]
Hi, i have same trouble and on Bimvie.ws too
<img width="587" alt="2018-09-19 10 06 45" src="https://user-images.githubusercontent.com/447902/45728806-dcc2c880-bbf3-11e8-9c86-d6ba2b91c83e.png">

**Comment by shubhambansal500** [comment]
no its not working both ways , niether through BIMvie.ws nor through code , same error invalidGUidexception

**Comment by rubendel** [comment]
@shockk You seem to be uploading an IFC2x3 file to an IFC4 project with an IFC4 streaming deserializer, that is not going to work for sure.

@shubhambansal500 I cannot reproduce this, can you share one of the models you are trying to upload?

**Comment by shubhambansal500** [comment]
@rubendel i am using bimserverjar-1.5.101 and trying to upload the default one something schenal(sorry i forgot the name) even then i get the same exception

**Comment by Jimmy-Abualdenien** [comment]
Unfortunately, after updating my server's plugin bundles got the same issues. I'm not able to check in or visualize any IFC file.

**Comment by rubendel** [comment]
I think this is actually caused by updating the plugins. This has been a problem for a while now which I am trying to fix. A new release is coming later this week that should fix these plugin issues.

https://github.com/opensourceBIM/BIMserver/wiki/Plugin-problems

**Comment by bovepm** [comment]
@rubendel I had the same issue on my docker instance and was very confused at the first place. until I realized that the plugins are going to be installed at runtime. thanks for providing a solution!

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.108

**Comment by Jimmy-Abualdenien** [comment]
Thanks @rubendel the issue is fixed after using v1.5.108

**Comment by shubhambansal500** [comment]
works great thank you so much
