### ISSUE TITLE
IfcReinforcingBar without geometry

### ISSUE THREAD

**Issue by rflsc** [opensourceBIM/BIMserver#824]
On this model, the objects with type IfcReinforcingBar, aren't rendered. The JSON returned from BIMSERVER v101 shows that the objects with that type doesn't have the "_rgeometry", so theirs geometries didn't download. 
Is there some preload query configuration that I`m missing? 
The IFC file is on the attachment.

![captura de tela 57](https://user-images.githubusercontent.com/6164096/45433110-d6779e00-b681-11e8-9133-e6cce0a5caf6.png)
![captura de tela 54](https://user-images.githubusercontent.com/6164096/45433129-dbd4e880-b681-11e8-815b-052683fc6bd1.png)
[Dubal Herrera limpio.zip](https://github.com/opensourceBIM/BIMserver/files/2375650/Dubal.Herrera.limpio.zip)

**Comment by rubendel** [comment]
This problem has been fixed in a recent version of IfcOpenShell, I just tested this model and the rebar shows up. BIMsurfer was showing it in a default color, I have also added a better color for it in BIMsurfer V1. The next release of BIMserver will have this fixed.

**Comment by rubendel** [comment]
Please re-open this issue if the problem still exists in https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.108
