### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by sigurdne** [opensourceBIM/BIMserver#827]
Hi
eclipse claims that there is a missing file - like:
`BimServer/src/org/bimserver/database/actions/GetProjectByUuidDatabaseAction.java`

reference added here:
https://github.com/opensourceBIM/BIMserver/commit/573b0209e081fa1d52b38a655e93a4cfa27611d3

Regards

**Comment by sigurdne** [comment]
1.5.108-SNAPSHOT

Error message:

> GetProjectByUuidDatabaseAction cannot be resolved to a type	ServiceImpl.java	/BimServer/src/org/bimserver/webservices/impl	line 747	Java Problem

**Comment by rubendel** [comment]
The file is there: https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/database/actions/GetProjectByUuidDatabaseAction.java
