### ISSUE TITLE
About xeogl and Threejs, how to correctly select and use?

### ISSUE THREAD

**Issue by WeiHuuu** [opensourceBIM/BIMserver#828]
As title, I would like to know the advantages of them. I can get Threejs information breezily so that use it. Do u have any idea about how to select? Thanks.

**Comment by WeiHuuu** [comment]
Sorry, I mean why not use threejs to show model. And whether the bimServer supports threejs.

**Comment by rubendel** [comment]
ThreeJS is a generic web based 3D visualization library, you can use it to build something that can load models from BIMserver, sure.
