### ISSUE TITLE
Microservice by multiple project-containers

### ISSUE THREAD

**Issue by sigurdne** [opensourceBIM/BIMserver#829]
Hi
I am exploring the idea of setting up a swarm of docker-containers as microservices – one container per building/project.
So far, I have a docker-image based on tomcat (8.5) with persistent data storage.
https://github.com/sigurdne/DockerBIMserver

Question: 
Would it be possible (and desirable) to run the BIMserver directly as `java - jar ...`  without the tomcat in a container?
Is it possible to start BIMserver as java directly from commandline without the pop-up ui-config-box?

Regards

**Comment by rubendel** [comment]
Performance-wise it wouldn't make a difference. It is possible to start BIMserver this way (you'd need the unpacked JAR build), the command-line would be quite long (you can copy-and-paste it from the JAR-runner's log file). Be aware that the command-line would change from version to version as dependencies come and go.

**Comment by sigurdne** [comment]
Yess - it works !

made a start-script:
```
#!/bin/bash 

java \
-Xmx8345m \
-Xss1024k \
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger \
-classpath \
.:lib:lib/jersey-common-2.26-b01.jar:lib/hk2-utils-2.5.0-b31.jar:lib/javax.websocket-api-1.1.jar....more....
org.bimserver.JarBimServer \
address=localhost \
port=8082 \
homedir=/opt/bimserver/home_101
```

Regards
