### ISSUE TITLE
cache control & rederction

### ISSUE THREAD

**Issue by sdeepusasidharan** [opensourceBIM/BIMserver#831]
1. cache control is not available. 
2. if we put "admin" after http://bimserver.org/  (http://bimserver.org/admin), it redirects to a login page which is not available in the actual home page.
![1](https://user-images.githubusercontent.com/42574647/45864301-33b4d300-bd97-11e8-9518-2b25348ca654.png)

**Comment by rubendel** [comment]
This issue tracker has nothing todo with the website bimserver.org. It is about the opensource BIMserver.
