### ISSUE TITLE
Model data is not available,console logged no info

### ISSUE THREAD

**Issue by xiaohujing** [opensourceBIM/BIMserver#833]
Click the "eye" button to indicate the loading success, but the model does not show. It was normal before, but the problem has occurred in recent days, hope to get help.
![qq 20180925135611](https://user-images.githubusercontent.com/34702186/45995572-27988080-c0cb-11e8-8aac-0ba2b8f8d64e.png)

**Comment by rubendel** [comment]
Versions please

**Comment by xiaohujing** [comment]
1.5.108

**Comment by rubendel** [comment]
An errors in the BIMserver logfile during checking/loading? Can you share the IFC file?

**Comment by xiaohujing** [comment]
There were no errors. I tried to change three models, all of them the same problem.
I asked someone else to help me test it. He chose ifc2x3tc1(Streaming), which showed the following problems
![111](https://user-images.githubusercontent.com/34702186/45999816-57e71b80-c0d9-11e8-9afd-dd80684d2b4e.png)

**Comment by xiaohujing** [comment]
How do I share the model with you

**Comment by rubendel** [comment]
You can just drag/drop files here, maybe zip it first. ifc2x3tc1(Streaming) is the right deserializer.

**Comment by xiaohujing** [comment]
[ifc.zip](https://github.com/opensourceBIM/BIMserver/files/2414237/ifc.zip)

**Comment by rubendel** [comment]
Model works fine here on 1.0.108. Are you really sure there are no errors in the BIMserver console? Just to be sure, the BIMserver console is not in your browser, but it's a logfile (and also shown in the BIMserver starter if you are using that).

Also, which platform are you on, and which browser?

**Comment by xiaohujing** [comment]
Bimserver is deployed on tomcat-8.5.32，Java 1.8.0.181，Google Chrome 69.0.3497.100， has just seen the log and there is no error

**Comment by rubendel** [comment]
Ah with the WAR install I am getting errors (strange that you don't...). This is now fixed in https://github.com/opensourceBIM/BIMserver/commit/020364d0a91646f2b75b429785a9c5dba0e1a45a so will be in the next release.

**Comment by xiaohujing** [comment]
Well, I'll reload it and see if it improves

**Comment by xiaohujing** [comment]
After the redeployment, it seemed to run, but it was stuck in the loading process, and I began to wonder if it was my hardware problem. My friend  loaded a little bit more than mine.
mine:
![3](https://user-images.githubusercontent.com/34702186/46005597-2de92580-c0e8-11e8-8c35-436c9efb7e44.png)
I'll find out for myself what the problem is, and I'm sure it's working well on your side.
Thank you for your help

**Comment by rubendel** [comment]
I'll just repost me earlier reply, just wait for the next release.

> Ah with the WAR install I am getting errors (strange that you don't...). This is now fixed in 020364d so will be in the next release.
