### ISSUE TITLE
some models show incomplete

### ISSUE THREAD

**Issue by litenk** [opensourceBIM/BIMserver#835]
The new version of the code seems to have some bugs, resulting in some models show incomplete.It is hoped that this bug can be repaired as soon as possible,thank you very much.
Problem pictures（new version 1.5.109）：
![8 _d qt_3 h2muwlu mx8](https://user-images.githubusercontent.com/32788523/46244592-7cadfc80-c413-11e8-9fd0-b862a1b914e4.png)

Normal picture（old version  1.5.96）：
![tntlxv75k3jr6gfkyl086rv](https://user-images.githubusercontent.com/32788523/46244647-7d935e00-c414-11e8-812e-a3411fdca8ad.png)

ifc file：
[电机合族优化.zip](https://github.com/opensourceBIM/BIMserver/files/2430528/default.zip)

**Comment by rubendel** [comment]
This has been fixed in the latest release(s) of BIMsurfer/BinarySerializerPlugin
