### ISSUE TITLE
getPluginBundle leads to UserException: Plugin bundle already installed org.opensourcebim.bimsurfer

### ISSUE THREAD

**Issue by JonasManuelKonstruktum** [opensourceBIM/BIMserver#836]
BimserverVersion: 1.5.109

I am trying to initialize a bimserver in an automated way and I also want to check if all necessary plugins are installed.
However when calling `getPluginBundle ` i get a UserException like `Plugin bundle already installed org.opensourcebim.bimsurfer`.

I would only expect this exception if i want to install an already installed version.
In this case i just want to query IF the plugin is installed or not or if there is a newer version.

**Comment by rubendel** [comment]
It'll now always return the plugin bundle information, also when already installed.
