### ISSUE TITLE
How to get organized tree of ifc and gltf model files using layers data?

### ISSUE THREAD

**Issue by dishesh** [opensourceBIM/BIMserver#840]
Hi there. Its me again. I am trying to implement a tabular view some like bimviews have "layers" tab. for that I need to dig info of elements organized as layer wise structure or as per children of each layers. I know I can find for each element by using low level interface but it will be a tedious job ( I have done for accessing properties of an element, there are multiple calls to get few property values!).

So can anyone help me with this it will really be helpful.
Thanks in advance!

**Comment by rubendel** [comment]
Have a look at how BIMvie.ws does this, it does so without too many calls to the BIMserver. Basically a "preload" query is used to prepopulate the JavaScript BIM Model with the objects/references that you are going to use later on. All objects/references that have been loaded this way will not have to be resolved in subsequent calls.

For example:
```javascript
	// object here has been retrieved via the BimServer JavaScript API
	object.getContainedInStructure(function(struc){
		struc.getRelatingStructure(function(relatingStructure){
			console.log(relatingStructure);
		});
	});

```

Without preloading the model, each call to `getContainedInStructure` and `getRelatingStructure` as well would result in an HTTP call to BIMserver (and with that the latency and asynchronicity), with the right preload query this can be avoided.

glTF is not meant for this anything other than assets without semantic meaning.
