### ISSUE TITLE
The latest version  seem to be unable to parse the model.

### ISSUE THREAD

**Issue by litenk** [opensourceBIM/BIMserver#841]
The latest version seem to be unable to parse the model.I thought the plug-in was incompatible at first, and the same problem still occurred after several redeployments. I hope this problem can be solved. Thank you.
![20181009112255](https://user-images.githubusercontent.com/32788523/46645294-dd2cfe80-cbb6-11e8-92be-ea6d30812903.png)

**Comment by rubendel** [comment]
A bit more information would be useful. For example the stacktrace that is undoubtedly in the log file. Also information about the system it's running on would be useful.

**Comment by litenk** [comment]
> A bit more information would be useful. For example the stacktrace that is undoubtedly in the log file. Also information about the system it's running on would be useful.

OK,thanks.

**Comment by litenk** [comment]
> A bit more information would be useful. For example the stacktrace that is undoubtedly in the log file. Also information about the system it's running on would be useful.

The problem has been solved. Yesterday my network is not good leading to plug-in loading failure.Thank you very much.
