### ISSUE TITLE
getDataObjectsByType is Deprecated

### ISSUE THREAD

**Issue by ideabobo** [opensourceBIM/BIMserver#843]
I found the "getDataObjectsByType" and "getDataObjectByOid" tips Deprecated,what is the Recommended approach

**Comment by rubendel** [comment]
You can use the query/filter language of BIMserver. For example to get all IfcWall objects (query by type):

```json
{
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  }
}
```

To get an object by it's Oid:

```json
{
  "oids": [
    12845937
  ]
}
```

**Comment by motjokk** [comment]
Im trying to get data without using the getDataObject-calls. Having trouble seeing how I can get the oid of IfcSite. A 'IsDecomposedBy' on the SProject level would do the trick.
