### ISSUE TITLE
Geometry Exception when calling getModel()

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#847]
trying to getModel() throws GeometryException ->"GeometryInfo not found id xxx" as well as UTFFormatException->"malformed input around byte 0" or GeometryException: Protocol != BGS (L^)

I installed the newest version of the Bimserver and all its plugins that are recommended on setup (Binary Serializer 0.0.36)

![image](https://user-images.githubusercontent.com/1222525/47089388-0be34e80-d221-11e8-96af-fb934f8c114b.png)

I use Bimserver 1.5.109
Please help :(

**Comment by rubendel** [comment]
Pretty sure this is fixed, can you try in 1.5.117?
