### ISSUE TITLE
Support of additional languages

### ISSUE THREAD

**Issue by tmuell01** [opensourceBIM/BIMserver#849]
Due to the fact, that still many users rarely use the englisch language their is an inhibition threshold. Therefor I have to have the opportunity to translate the GUI into my local language to maximize the value as well as the user acceptance of the BIMserver.

If you have further questions to this issue, please do not hesitate to contact me.

**Comment by rubendel** [comment]
Which GUI are we talking about?

**Comment by tmuell01** [comment]
The whole software

**Comment by rubendel** [comment]
Have you looked at the project? This is a server, there is no UI,

**Comment by tmuell01** [comment]
Sorry I meant bimvie.ws
