### ISSUE TITLE
updated BIMserver 1.5.101 to updated via DataImport - IFC Files not importing

### ISSUE THREAD

**Issue by sanriavictor** [opensourceBIM/BIMserver#854]
We used the DataImport option to import our data from  BIMserver 1.5.101 to  BIMserver 1.5.109, we were able to view the list of users & the Project names but the projects are empty. they do not contain the IFC files. Please let us know how to fix this or is there any safe way to upgrade the releases versions.
@rubendel @

**Comment by rubendel** [comment]
There should be some error messages, please not this code is marked experimental, most definitely not something we test regularly.

**Comment by rubendel** [comment]
Please have a look at https://github.com/opensourceBIM/BIMserver/wiki/BIMserver-Database-Migration#current-policy
