### ISSUE TITLE
upload ifc

### ISSUE THREAD

**Issue by jkfhto** [opensourceBIM/BIMserver#859]
How to upload ifc model file in bimvie.ws, is there a specific tutorial?

**Comment by Dakki97** [comment]
first you create a project, then you  go to show projects and click on your created project, the empty viewer should open. on the left side you have the project with a arrow down.
If you click on that arrow down the dropdown list is opening and it has an item called "checkin", click on it and upload your ifc.

**Comment by jkfhto** [comment]
Error uploading ifc file
![image](https://user-images.githubusercontent.com/27767452/47693388-7b4f3a00-dc34-11e8-9def-0fb80786a310.png)

**Comment by rubendel** [comment]
Can you copy and paste the error message _as text_, so I don't have to manually retype it... and other people can actually search for this.

**Comment by rubendel** [comment]
I guess not
