### ISSUE TITLE
IfcPlugins installation failed

### ISSUE THREAD

**Issue by jkfhto** [opensourceBIM/BIMserver#861]
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found

![image](https://user-images.githubusercontent.com/27767452/47699318-6e8b1000-dc4d-11e8-85c1-b7b5990a80f9.png)

**Comment by rubendel** [comment]
Banning because of crossposting
