### ISSUE TITLE
Problem with View

### ISSUE THREAD

**Issue by rediumbv** [opensourceBIM/BIMserver#863]
Hi help,

I have update yesterday all plugins and now i see every time in the log.

14:44 | 1 second | Unknown field: "loaderSettings" | Error |  
-- | -- | -- | -- | --
14:44 | 1 second | Unknown field: "loaderSettings" | Error |  
14:44 | 1 second | Unknown field: "loaderSettings" | Error

It shows nothing in the viewer how can i fix it.

**Comment by rubendel** [comment]
Did you also update BIMserver itself?

**Comment by rediumbv** [comment]
Hi no when i update the BIMServer self i have a empty database and loose all my imports.
How ca i update it self without losing anything.

**Comment by rubendel** [comment]
Have a look at https://github.com/opensourceBIM/BIMserver/wiki/BIMserver-Database-Migration

Also maybe here: https://github.com/opensourceBIM/BIMserver/wiki/Plugin-problems
