### ISSUE TITLE
going back to previous BIMServer version with corresponding plugin versions

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#866]
I would like to go back to BimServer 1.5.101 with the corresponding plugins. How is this achieved? bimviews always installs the latest plugin and I am not able to install previous plugin version from the plugin bundle window.

**Comment by rubendel** [comment]
Please have a look at this page: https://github.com/opensourceBIM/BIMserver/wiki/Plugin-problems

In short: This is possible for versions after 1.5.108 (and from version 1.5.111 also during the initial setup)
