### ISSUE TITLE
Is there a way to manipulate bim objects and make them into smaller ones and restore them to bimServer?

### ISSUE THREAD

**Issue by dishesh** [opensourceBIM/BIMserver#875]
Hi there. It's me again. I have a new query related to manipulating bim-objects.
Is there any way we can change the properties of a bim object. per se If I want to change height width or any dimension of an IfcDoor or any other IfcElement and store it back again?

It would be really helping if apart from visualizing, bim Server provides such functions so that at a small scale we can edit models.
Requesting @xeolabs @rubendel for help.
Thanks.

**Comment by rubendel** [comment]
Sure, except IFC has a lot of different ways of representing geometry, so depending on the original type of geometry of your model, you might be able to do this, or not. For most types of geometry you unfortunately would need a specialized authoring tool to help you.
