### ISSUE TITLE
Wrong type of IfcCartesianPointList2D.coordList twodimensional array

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#877]
On checking in an IFC4ADD2 file with `IfcCartesianPointList2D` I get the error 

    IfcCartesianPoint expected, but got "6.05"

For `IfcCartesianPointList3D` checkin works well though. I think this is caused by just a tiny error in the code that generates the ecore from the Express files:

The IfcCartesianPointList2D.coordList should be a List of List of IfcLengthMeasure, not of IfcCartesianPoint. 
https://github.com/opensourceBIM/BIMserver/blob/b17a097ae1f2f5cb5e011737648c14db5d88cd36/BimServer/src/org/bimserver/schemaconverter/Express2EMF.java#L660-L661

It is done right for IfcCartesianPointList3D:
https://github.com/opensourceBIM/BIMserver/blob/b17a097ae1f2f5cb5e011737648c14db5d88cd36/BimServer/src/org/bimserver/schemaconverter/Express2EMF.java#L644-L645

This then ripples through to the ecore and all generated classes, of course.

Here is a test file: 
[IfcSurfaceOfLinearExtrusion.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/2565482/IfcSurfaceOfLinearExtrusion.ifc.txt)

**Comment by hlg** [comment]
I would create a pull request, but I don't know how to generate the EMF stuff. Anyway, you would have a hard time to check the changes and make sure I did not introduce odd things, so you probably want to do that yourself.

**Comment by rubendel** [comment]
Nice observation, it's fixed now in git head master.
