### ISSUE TITLE
Geometry Data is null 

### ISSUE THREAD

**Issue by mhdfahadCS** [opensourceBIM/BIMserver#878]
I want to get geometry data to explore AREA via indices, vertices and matrix. But I am getting null geometry data, Can you please tel me why I am getting NULL as geometry data. My code is below: 
geometry.forceLoad();
GeometryInfo geometry = ifcProduct.getGeometry();
GeometryData geometryInfoData = geometry.getData().forceLoad(); ..............................it is null 

But  geometry.getMinBounds().getX()  is not null, I dont need X Y and Z min max.

**Comment by mhdfahadCS** [comment]
Reference code in the bim server is below: 
package org.bimserver.utils;  Class: IfcTools2D  
Function public static Area get2D(IfcProduct ifcProduct, double multiplierMillimeters)

I want to do the same but getting null as geometry data

**Comment by rubendel** [comment]
What does your `getModel` invocation look like?
