### ISSUE TITLE
I have installed BIMServer with working internet, All remote plugins have been installed. But I cannot open BIMViews. The BIMViews page is always loading BIMViews, and I get the chrome console windows error information:

### ISSUE THREAD

**Issue by nickydev100** [opensourceBIM/BIMserver#883]
Please use ``` your code ``` to escape code and use the "Preview" button to see whether your issue is readable. Also, when relevant, please note your BIMserver version.
When posting logfiles, please post the actual text, and not screenshots of the log files. Also logfiles with no error messages whatsoever are usually not very useful.

**Comment by rubendel** [comment]
Please try again
