### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by siriuszyx** [opensourceBIM/BIMserver#886]
Hi I'm still new to programming - and recently my boss is asking me to set up this BIM server together with bimvie.ws. List down some issues here:

Q1. I tried bimserver 1.5.117 with its Java client. When it's launched it says MIGRATION_REQUIRED on the page.
Q2. Then I switched back to 1.5.113. 
a. When I am using the Java client to launch, I am missing bimvie.ws and bimsurfer. Since from this version onwards I cannot simplly put .jar files into lib directory - so I am lost. 
b. When I do this by eclipse, with bimvie.ws and BIMsurfer imported from Git, I can see it's BIMserver version 1.5.118_SNAPSHOT. I have bimvie.ws here but constantly cannot login. It simply stuck on the "loading bimvie.ws" page.
c. Then I get into bimsurfer2 from here and then go in to https://thisisanexperimentalserver.com. Now I am in version 1.5.116-SNAPSHOT and I have bimserverjavascriptapi, bimsurfer, bimviews and console. I can go in bimviews, but I cannot login: It prompts "Your email address has not been validated yet". And when I want to register, it will show "A user with the username XXX already exists".
d. Then I go back to the console. 
I try to addUser as an ADMIN, but it is either
{
  "response": {
    "exception": {
      "__type": "UserException",
      "message": "A user with the username XXX already exists"
    }
  }
}

OR 

{
  "response": {
    "exception": {
      "__type": "UserException",
      "message": "Error sending email Couldn't connect to host, port: localhost, 25; timeout -1"
    }
  }
}

OK. Then I want to validateAccount, but I need a uoid which I never see. 
getAllUsers will give me 
Response
{
  "response": {
    "exception": {
      "__type": "NullPointerException",
      "message": "java.lang.NullPointerException"
    }
  }
}
e. Lastly I also tried to use Tomcat to deploy .war. I can get into localhost:8080 but it always failed to start bimserver from Manage App page. The prompt is "FAIL - Application at context path [/bimserverwar-1.5.117] could not be started" Yes I have added the package in conf\server.xml as 
<Context path="/" docBase="bimserverwar-1.5.117.war" debug="0" priviledged="true" reloadable="true"/>

Hope as a novice I can get some helpful advise from you. Thank you.

**Comment by rubendel** [comment]
Please format your issues so they are readable. Also give issues a title that explains the problem. Also use 1 issue per ehm... issue.
