### ISSUE TITLE
Install bimvie.ws and how to view uoid

### ISSUE THREAD

**Issue by siriuszyx** [opensourceBIM/BIMserver#888]
I understand from version 1.5 onwards I cannot simply drag the .jar into the ```\plugins``` directory. 
I ran the installation before but at that time bimvie.ws failed. Now I cannot go back to the initialisation page. So, is there other way to install bimvie.ws? I know I can use eclipse to set up the whole thing, but is there a basic way of doing this?

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/wiki/Eclipse
