### ISSUE TITLE
Setup by eclipse and unable to start bimvie.ws

### ISSUE THREAD

**Issue by siriuszyx** [opensourceBIM/BIMserver#889]
Followed this video (https://www.youtube.com/watch?v=3Era8HUmyPU).

After I ran, I was at this page:

![image](https://user-images.githubusercontent.com/31344240/49413706-c9afa580-f7ab-11e8-9e8d-07cdebe69fc5.png)

Then I entered the ```bimviews``` and it's stuck like this:

![image](https://user-images.githubusercontent.com/31344240/49413732-e2b85680-f7ab-11e8-8e21-bd46ab4197a2.png)

Then I tried to use ```bimsurfer2```

![image](https://user-images.githubusercontent.com/31344240/49413766-fc599e00-f7ab-11e8-839e-275ab7a5782a.png)

I went to the first URL at this page. 

![image](https://user-images.githubusercontent.com/31344240/49413845-2f9c2d00-f7ac-11e8-8ef5-9a617733191f.png)

Ok ```bimviews``` can start but I was stuck at the login page: 

![image](https://user-images.githubusercontent.com/31344240/49413878-4d699200-f7ac-11e8-891c-a7b0d8fc7a77.png)

which lead me to the second part of question #888 

Any suggestions?

Thank you

**Comment by rubendel** [comment]
You are missing the BIMserver JavaScript API
