### ISSUE TITLE
THANK YOU and MERRY CHRISTMAS 2019

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#894]
Hi @rubendel  and @aothms  and all other contributors,

thank you for you enormous efforts for the BIMserver and IfcOpenshell. We have last week updated to the latest version of BIMserver and this went very smoothly and is working good. Your results are great!

We wish you all a merry christmas and a happy new year!

Klaus

**Comment by rubendel** [comment]
Thank you Klaus, belated happy new year!
