### ISSUE TITLE
Unable to load partial model via query

### ISSUE THREAD

**Issue by Bigwangjing** [opensourceBIM/BIMserver#897]
Hello, I can't load the model when I use bimview to query a node through query.
![image](https://user-images.githubusercontent.com/23251633/50471388-4ae70a80-09ef-11e9-98b4-9618796d5679.png)
I only got the node information, but it was not loaded into the corresponding model.
![image](https://user-images.githubusercontent.com/23251633/50471449-98637780-09ef-11e9-96c2-d34a66a7ff2d.png)
Excuse me, how do I set the query if I get a model corresponding to a guid?
By the way, there is a problem that the model is loaded via Cesium, or the model is downloaded directly from the bimview page. The model has no texture.
![image](https://user-images.githubusercontent.com/23251633/50471726-f6dd2580-09f0-11e9-9b2d-76a50df9aea4.png)
![image](https://user-images.githubusercontent.com/23251633/50471820-458abf80-09f1-11e9-95d0-08d92925e33d.png)
The export model format is glb format, and the serializer uses Binary glTF Serializer 2
Looking forward to your reply

**Comment by hlg** [comment]
The entity with the GUID you have queried for is of type `IfcBuildingStorey` and does likely not have any geometry defined. Thus the viewer cannot show anything.
