### ISSUE TITLE
Get IfcProduct which is child of IfcProduct

### ISSUE THREAD

**Issue by whatisor** [opensourceBIM/BIMserver#900]
Hi, I try to analysis tree of Ifc model. My code work well with normal case. However, it does not work if an ifcproduct is a child of another ifcproduct like below image.
As you can see from this image(captured from bimviews)
![screenshot 14](https://user-images.githubusercontent.com/6780177/50737907-8d36f580-1200-11e9-8995-1e5e5d70fbd2.png)

(Railing is the child of Stair).
Can you explain a bit about this special case?
Thank you.

**Comment by rubendel** [comment]
Please have a look at the IFC documentation. This is not a BIMserver issue.
