### ISSUE TITLE
IfcLineIndex and IfcArcIndex missing from ecore

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#902]
When I try to check in a file containing `IfcIndexedPolyCurve` with the optional `Segments` attribute set, e.g. [this one](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/annex/annex-e/slab-standard-case.htm), then I get the following error.

    Error on line 49: IFCLINEINDEX is not an existing IFC entity

IFC4 files with this kind of geometry should be accepted. The missing types in the ecore file are `IfcLineIndex` and `IfcArcIndex`, both of which are defined types (lists of integers) and choices of `IfcSegmentIndexSelect`. These [triad of types](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/ifcsegmentindexselect.htm) is only used for `IfcIndexedPolyCurve`, nowhere else.

The offending line in the [example IFC](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/annex/annex-e/slab-standard-case.htm) is

    #308= IFCINDEXEDPOLYCURVE(#307,(IFCLINEINDEX((1,2)),IFCARCINDEX((2,3,4)),IFCLINEINDEX((4,5)),IFCARCINDEX((5,6,1))),.F.);

The error was reproduced with versions 1.5.117 and 1.5.121-SNAPSHOT.

**Comment by rubendel** [comment]
The example file links to the Ifc4Add2Tc1 version, but I see those are also available for Ifc4Add2. Will look into this, and possibly make sure all those example files work.

**Comment by rubendel** [comment]
@hlg Do you have a feeling about the quality of the example files (are they all correct according to the spec)? Is it worth settings up automated tests for these files specifically?

**Comment by hlg** [comment]
Since they are integrated in the specs I would expect these files to conform to the standard, but honestly I don't know how well-curated they are. According to their headers they are of varying provenance, some seem to be hand-written, some generated with various tools. For instance, I saw GeometryGym, which I believe appeared in some BIMserver issue as the generator of an erroneous file earlier last year. Also, at least one of the IFC4 example files has an IFC2x3 header.

If not fully automated, it may be worth (less effort) to use these as a base for a test file repository rather than creating examples from scratch.
