### ISSUE TITLE
Opening the Bimserver with its plugins in Eclipse.

### ISSUE THREAD

**Issue by GravTrainee** [opensourceBIM/BIMserver#906]
So I followed the instructional video on Youtube and saw some earlier issues, tried to install and uninstall the repo a few times, but I never get further than the example screen. The downloadable Jar file does not work, even when I try to fix every problem it gives me. The issue cannot be in the hardware, since this a brand new computer. Is there a new tutorial somewhere, step by step? Something that would show me how to connect to the newest version of BimServer?

**Comment by whatisor** [comment]
You should open BimserverJar project with Eclipse,too.
Then, use this argument for BimServerJar running from Elipse:
-plugins <plugin source folder which contains plugin.xml> -home <somewhere>\data

**Comment by hlg** [comment]
If you just want to try out a BIMserver, use the JAR version from relases. Double-click and run locally, no need for an IDE like Eclipse. If you want to develop BIMserver or plugins, you need some previous experience. We do not have any step-by-step programming introductions.
