### ISSUE TITLE
Setup aborted while installing ifcopenshellplugin, ifcplugins, gltf, mergers on local bimserver 1.5.120 pre-release

### ISSUE THREAD

**Issue by NagendraChikkanna** [opensourceBIM/BIMserver#910]
**Issue** : Setup aborted while installing ifcopenshellplugin, ifcplugins, gltf, mergers

**Reference Package** :  Bimserver pre-release v1.5.120 ( cloned from https://github.com/opensourceBIM/BIMserver/tree/v1.5.120)

**Current Package** : https://github.com/NagendraChikkanna/BimServerThreeDModel_1.5.120
We are facing a problem on current package. Please suggest on this issue.

**Steps to reproduce.**
**1). **Followed the steps as per the youtube video "https://www.youtube.com/watch?v=Vb6gokSBA0I".
**2).** while setting up bimserver not able to install the ifcopenshellplugin, ifcplugins, gltf, mergers plugins. we are getting an error as shown below.

Installing ifcopenshellplugin...
Method org/ifcopenshell/IfcOpenShellEnginePlugin.getSystemSettingsDefinition()Lorg/bimserver/models/store/ObjectDefinition; is abstract
Setup aborted

Installing ifcplugins...
Method org/bimserver/serializers/JsonSerializerPlugin.init(Lorg/bimserver/plugins/PluginContext;Lorg/bimserver/plugins/PluginConfiguration;)V is abstract
Setup aborted

Installing gltf...
Method org/bimserver/gltf/BinaryGltfSerializerPlugin.init(Lorg/bimserver/plugins/PluginContext;Lorg/bimserver/plugins/PluginConfiguration;)V is abstract
Setup aborted

Installing mergers...
Method org/bimserver/merging/IntelligentNameBasedModelMergerPlugin.getSystemSettingsDefinition()Lorg/bimserver/models/store/ObjectDefinition; is abstract
Setup aborted

**Screenshots attached**

![bimserver_setup_gltf_issue](https://user-images.githubusercontent.com/46588424/51902674-8dca4280-23e0-11e9-824a-d7efdefd9f68.png)
![bimserver_setup_ifcopenshellplugin_issue](https://user-images.githubusercontent.com/46588424/51902675-8e62d900-23e0-11e9-8715-d0f82008c222.png)
![bimserver_setup_ifcplugins_issue](https://user-images.githubusercontent.com/46588424/51902677-8e62d900-23e0-11e9-8471-1f804420806c.png)

**Comment by rubendel** [comment]
Hmm this is indeed a problem, also present in 1.5.121, working on a fix. Apparently the oldest plugin is installed instead of the newest.

**Comment by NagendraChikkanna** [comment]
@rubendel , Thanks for the update.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.122
