### ISSUE TITLE
debugger statement in setup.html

### ISSUE THREAD

**Issue by pierrejoye** [opensourceBIM/BIMserver#911]
```
                       var latestVersion = pluginBundle.latestVersion;
                        debugger;
                        if (latestVersion == pluginBundle.installedVersion) {

```

On line 511 of setup.html (v.120)

**Comment by pierrejoye** [comment]
Also check issue #912 it may be related (looks like at least when I look at the code)

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/commit/46a0dbe3101316ffbb3cacc68c94baa4477917e4#diff-a4b047a6c3170bc3bb9602b6bc2c3fca

**Comment by pierrejoye** [comment]
Thanks a lot!
