### ISSUE TITLE
No release available for plugin

### ISSUE THREAD

**Issue by pierrejoye** [opensourceBIM/BIMserver#912]
Hello,

While it was working well using .120, now the setup fails on:

```
		Installing bimviews...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

```
Thoughts?

**Comment by pierrejoye** [comment]
Installed using the API works, I added org.opensourcebim.bimviews-0.0.119.jar and it seems to be fine.

works and interestingly enough, bimvie.ws works now without error :)

**Comment by rubendel** [comment]
Same issue probably as https://github.com/opensourceBIM/BIMserver/issues/910

This is now fixed in 1.5.122

**Comment by pierrejoye** [comment]
and here too! amazing work and such a good quick response! Amazing :)
thanks a lot. If all go well I hope to be able contribute back soon!

**Comment by RussellGrew** [comment]
FYI this is happening again with the 1.5.137 release.
