### ISSUE TITLE
Not able to upload dwg files to Bimserver

### ISSUE THREAD

**Issue by NagendraChikkanna** [opensourceBIM/BIMserver#913]
Hi Team,

Currently using BimServer version : **v1.5.109**
And BimVie version    :  **0.0.95**

**Issue Description :** 
I am trying to upload dwg files but getting an error.
What is the deserializer to checkin the dwg autocad file.
Please suggest is it possible to view autocad DWG file on top of IFC file.

**Comment by rubendel** [comment]
BIMserver does not support DWG
