### ISSUE TITLE
Setup fail BIMserver 1.5.125 SceneJS is not defined

### ISSUE THREAD

**Issue by TristanLecallier** [opensourceBIM/BIMserver#921]
Hi,
I have cloned  the BimServer, the BIMserver-JavaScript-API, BIMsurfer, bimvie.ws projects on my eclipse : 

 ![package explorer](https://user-images.githubusercontent.com/46968115/52199146-7e764980-2865-11e9-81ac-8400189765f2.png)

I have added the plugins in the LocalDevBimServerStarter configuration

 
![image](https://user-images.githubusercontent.com/46968115/52199180-9948be00-2865-11e9-9dce-396c7a936579.png)

When I launch the java application I arrived as planned at the Following caption :

 
![image](https://user-images.githubusercontent.com/46968115/52199187-a49be980-2865-11e9-9874-1f529f38f508.png)

But when I click on bimviews link I have another error : » SceneJS is not defined »

 
![image](https://user-images.githubusercontent.com/46968115/52199198-ad8cbb00-2865-11e9-9a3a-7a305b3aecd5.png)

I have seen the same issue there : https://github.com/opensourceBIM/BIMserver/issues/226 but to me I have done all that was asked…
I don't understand what I dit wrong, someone does ?
I would be very grateful.

Thanks,

Tristan

**Comment by TristanLecallier** [comment]
It seems that in the BimSurferV2 version (master branch), the api folder which contains the ScenJS.js file is missing in the project... Is this normal ?

**Comment by tchegito** [comment]
Hi ! Actually I had the same problem a week ago, and the cause is BimsurferV2 (master branch) is not compatible with Bimviews. You have to checkout the V1 branch, as stated here:
https://github.com/opensourceBIM/BIMserver/wiki/Eclipse

**Comment by rubendel** [comment]
I can confirm that BIMvie.ws is using V1 of BIMsurfer.
