### ISSUE TITLE
Walls are not cut with the roof

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#923]
Walls are not cut with the roof
Hi,
I reduced the 3D model to the problem.
Can you please check why the wall is completely rendered?
Please have a look at the attached pictures and the IFC file. The color representation is unimportant.
SolibrViewer - OK
BIMserver - Wrong

Regards,
Jo

![roof](https://user-images.githubusercontent.com/16973608/52238704-f88de900-28cc-11e9-9e2b-e000c0a8fb0c.png)

![roofshouldbe](https://user-images.githubusercontent.com/16973608/52238721-05124180-28cd-11e9-9826-a9a429bf0ae8.png)

[Roof.zip](https://github.com/opensourceBIM/BIMserver/files/2829885/Roof.zip)

**Comment by rubendel** [comment]
This is what I get with 1.5.125:

![image](https://user-images.githubusercontent.com/377978/52795088-58c11f80-3071-11e9-86f9-b6016b9b5105.png)

It's not shaded, but since you said it's unimportant, I assume that's the model. It does appear to be cut-off correctly though.

**Comment by Jo64** [comment]
Yes the colors are not so important in the representations of the different viewers - BIMserver vs. SolibriViewer. But they should be the same between the BIMserver versions. 
So something has changed between 1.5.117 and 1.5.125. in the representation of the geometry and the colors. We need an update to the latest version.

**Comment by rubendel** [comment]
I don't agree. If everything stays the same between versions, then there is nothing left to develop. The updates are available for download.
