### ISSUE TITLE
Produce valid IFC file with query

### ISSUE THREAD

**Issue by ejmulman** [opensourceBIM/BIMserver#924]
Hi,

Installed bimserver 1.5.124 and I am struggling to extract an partial valid IFC file from an larger model.

I have searched for creating valid IFC files and I think this query could provide it?

Using the query;
{
"types": [
"IfcWall",
"IfcSlab"
],
"includeAllSubtypes": true,
"includes": [
"validifc:ContainedInStructure",
"validifc:OwnerHistory",
"validifc:Representation",
"validifc:ObjectPlacement"
]
}

Results in the fault;
org.bimserver.database.queries.om.QueryException: Could not find 'validifc' namespace in predefined queries

With installation all available plugins are installed.

Should this work for this version?

**Comment by rubendel** [comment]
"validifc" has been renamed to "ifc2x3tc1-stdlib". This change still has to be reflected in the BIMvie.ws examples, which I'll do next week.

**Comment by rubendel** [comment]
BIMvie.ws examples have been updated, if you know of any other places where "validifc" is used, please let me know.

https://github.com/opensourceBIM/bimvie.ws/commit/8c6e05ae0090ab0734843ea8004fe48a463879c0
