### ISSUE TITLE
Is there any way to read ifc file and create a project instead of uploading

### ISSUE THREAD

**Issue by npurushotham** [opensourceBIM/BIMserver#925]
I have a problem with ifc , As i am having very large ifc files (minimum is >1GB ) . is there any way some thing like there is a folder i keep in server , server will automatically creates project with ifc files. because over http there is some limitations while uploading files. can you also tell me what is the best practices to avoid issues during upload.

**Comment by rubendel** [comment]
HTTP has no such limitations. The best practice is to correctly configure any systems between the client and the server (for example proxy servers).

To answer your main question, no BIMserver does not have this functionality.
