### ISSUE TITLE
Cannot see any reference to implement plugin with json query

### ISSUE THREAD

**Issue by whatisor** [opensourceBIM/BIMserver#928]
I want to modify some plugin to response with JSON query(For example, return only sub-model name list)
However I cannot see any reference for java side development.
All I found is client-side standard:
https://github.com/opensourceBIM/BIMserver/wiki/JSON-Queries

**Comment by rubendel** [comment]
Which plugin do you want to modify? You need to check-it-out, as described here: https://github.com/opensourceBIM/BIMserver/wiki/Eclipse

**Comment by whatisor** [comment]
Thank for reply. I have already known how to modify  a plugin. 
I just do not know how to get JSON query data from client code because it goes through bimserver firstly.
