### ISSUE TITLE
Unable to compare

### ISSUE THREAD

**Issue by tchegito** [opensourceBIM/BIMserver#929]
I can't compare 2 revisions.

I created a simple project, with 5 revisions of an IFC file. 3D render is ok, I can see revisions in the left panel, and the right (without ROID that being said)

First of all, when I click on "Compare" on the left panel, that does nothing. I saw that "compare.html" exists and might be called, but nothing on screen.

When I call the service ServiceInterface#downloadCompareResults everything seems allright, a topicId is returned. I have a result calling NotificationRegistryInterface#getProgress with the previous topicId saying "STARTED" but when I call "download" console says "Invalid topicId 67" and nothing is returned. I tried with sync at true or false: same result.

Am I doing something wrong ? Maybe I missed a plugin ?

**Comment by tchegito** [comment]
Note: when I call ServiceInterface#compare with similar parameters, a result is returned.

**Comment by rubendel** [comment]
The compare dialog has been fixed in BIMvie.ws (https://github.com/opensourceBIM/bimvie.ws/commit/98fde6b7fe8225f1d532bb06d86acc90a5e5b2b5)

**Comment by rubendel** [comment]
A few more notes:
- You have to select a non-streaming serializer, in 1.5.126 an exception will be thrown when not providing the correct serializer type
- A default model merger must be selected for you user, otherwise an exception will be logged
