### ISSUE TITLE
 IFC file does checkin and doesn't render in version 1.5.125

### ISSUE THREAD

**Issue by rflsc** [opensourceBIM/BIMserver#935]
I usually use this sample IFC file with Bimserver. But in this latest version 1.5.125 the file does the checkin and does not render the 3d model. The "_rgeometry" attribute is missing on the json return of the objects by the server. I would like to know the reason, whether it is a new specification or a bug in the new version. The file is in the attachment below. Thank you.

[Teste_Escala.zip](https://github.com/opensourceBIM/BIMserver/files/2861301/Teste_Escala.zip)

![image](https://user-images.githubusercontent.com/6164096/52728472-7cfffc00-2f9e-11e9-9f3c-16d2311acaae.png)

**Comment by rubendel** [comment]
I can confirm no geometry is generated. I suspect this is a problem with IfcOpenShell (used for generating the triangles). I have contacted the developer of IOS, will report back here.

**Comment by rubendel** [comment]
Thanks to @aothms. This IFC file is simply invalid.

Offending entity
```
#24=IFCSURFACESTYLE($,$,(#23));
```

The second argument is not optional. Contact the provider of the software that exported this IFC if you want it fixed.

http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcpresentationappearanceresource/lexical/ifcsurfacestyle.htm

**Comment by rubendel** [comment]
A note from @aothms: 

It seems unlikely this would have worked before. The loc to check Side is at least three years old: https://github.com/IfcOpenShell/IfcOpenShell/blame/v0.6.0/src/ifcgeom/IfcGeom.h#L372 But can't entirely be sure either.
