### ISSUE TITLE
How to change the bimserver address?

### ISSUE THREAD

**Issue by totaljfb** [opensourceBIM/BIMserver#936]
Hello, 

I'm having trouble with configuring the bimserver address.  I have searched and looked into several similar issues but haven't found a clear solution to my case. I appreciate any help from you guys.

Here is the case, a computer is cloned from a bimserver computer, now the cloned computer has a new computer name.  When I run the http request http://[cloned computer host name]/bimserver/x.getbimserveraddress, it returns the previous bimserver computer name.  

There are three ways to change the bimserver address, which is mentioned in #628  :
1 During setup (Site address)
2 Using BIMvie.ws (Server | Server Settings | Site address)
3 Calling the API method SettingsInterface.setSiteAddress

Currently it seems like that 1 and 2 is not available because the previous bimserver has been decommissioned. I tried to visit http://[cloned computer host name]/bimserver/?page=login and there is an error message "net::ERR_NAME_NOT_RESOLVED".
![bimserver configuration page error](https://user-images.githubusercontent.com/17803244/52731688-546f0680-2f8c-11e9-9bda-26816b61e0ea.png)

So I tried to use Java client to change the bimserver address and here is another problem, I cloned the project from https://github.com/opensourceBIM/BimServerJavaClientDemo and run the Connecting.java to test, the error message is "org.bimserver.shared.exceptions.UserException: Method login not found on AuthInterface (suggestion: Bimsie1AuthInterface)", which is mentioned in #332. I guess there is a mismatch between client API version and bimserver version. 

Can you give me some suggestions? The goal is to change the bimserver address using either of the ways provided above. Thank you.

The bimserver version is bimserver-1.4.0-FINAL-2015-11-04, settings in pom.xml in Java client project is:
		<groupId>org.opensourcebim</groupId>
		<artifactId>bimserverclientlib</artifactId>
		<version>1.5.102</version>

**Comment by rubendel** [comment]
You can use the Console app, which allows you to call all BIMserver API calls regardless of the configured SiteAddress. You can also use the API itself, but if you use the BimServerJavaApi you indeed need to use the same version as the deployed BIMserver.

In 1.5.125 the problem with the SiteAddress is not there anymore for BIMvie.ws, it now uses other means of determining the address of BIMserver.

**Comment by totaljfb** [comment]
Hi Ruben,

Thank you for the reply.  I'm new to bimserver and I appreciate it your help. 

The bimserver version is bimserver-1.4.0-FINAL-2015-11-04, what version of the client API should I use?

Thank you.
Jason

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-11-04

bimserver-client-lib-1.4.0-FINAL-2015-11-04.zip

**Comment by totaljfb** [comment]
Thank you Ruben, I appreciate it!
