### ISSUE TITLE
Can not checkin model in 1.5.125

### ISSUE THREAD

**Issue by gujia1088** [opensourceBIM/BIMserver#937]
Description
1.I download BIMserver 1.5.125.jar, and installed all recommended plugins.
2.In the checkin page, after select a IFC file, the "Check new revision" does not show, and no deserializer can be selected.
3.In the bulk checkin page, I check in a IFC file successfully, but can not see the 3D view. 

Screenshots:
![bulkcheckin](https://user-images.githubusercontent.com/18138674/52766267-9cac2880-3061-11e9-9a0c-cccec9cd1735.jpg)
![checkin-nodeserializer](https://user-images.githubusercontent.com/18138674/52766271-9e75ec00-3061-11e9-8865-9ebf22042f71.jpg)

**Comment by rubendel** [comment]
Duplicate
