### ISSUE TITLE
Could't get ifc wall vertices

### ISSUE THREAD

**Issue by zaizou** [opensourceBIM/BIMserver#940]
HI,
I am trying to get the vertice of the spaces and the walls inside storey in order to apply the TIN technique, the, The code wich I used to extract vertices from IfcSpace (I got it from floor generator plugin ) object is working, but when I try to use it it don't work and stay in an infinite loop, the same thing when I try to get IfcWall vertice using "ifcWall.getGeometry().getData().getVertices();".

**To Reproduce**
1. Gotting an IfcWall element
2. call getVertices method "ifcWall.getGeometry().getData().getVertices();"

**Expected behavior**
Having the ifcWall vertices.

**  ***
Link of the code I used to get IfcSpaces Vertices :
[https://github.com/opensourceBIM/floorplan-generator/blob/master/src/org/bimserver/cobie/graphics/VertexExtractor.java](url)

**Comment by rubendel** [comment]
The link is not working here. Can you specify exactly where the infinite loop happens? Does it happen in BIMserver or your own code?

**Comment by zaizou** [comment]
I am creating a new plugin 
Here is the right link of the code which I am using : 
https://github.com/opensourceBIM/floorplan-generator/blob/master/src/org/bimserver/cobie/graphics/VertexExtractor.java

Event when I try this code, the second println is not called.
`
List<IfcWall> walls =  model.getAll(IfcWall.class);
        if(walls.size()>0)
            System.out.println(walls.get(0).getGeometry().getData().getVertices());
        System.out.println("Wall vertices printed");

I also tried to set the parameters "deep" and "get geometry" of the method getModel but I am facing the same issue.
`

**Comment by rubendel** [comment]
Is it not simply running out of memory? Can you pause the thread and see what it's doing?
