### ISSUE TITLE
BimServer Starter wont work and shows this

### ISSUE THREAD

**Issue by LefterisFets** [opensourceBIM/BIMserver#945]
After following all the written steps, Im starting the starter but it wont work..
The thing is that Im a a student and cant translate the messages shown.
A have a project in uni and i need to upload my ifc model online somehow and i have 5 days left, guys i really need your help!
Thanks everyone in advance!
Have a nice day!
![screenshot_4](https://user-images.githubusercontent.com/48316469/53949431-b2e25d00-40d2-11e9-9f15-b3760d0e4499.png)
![screenshot_12](https://user-images.githubusercontent.com/48316469/53949432-b37af380-40d2-11e9-8b39-b105ecdd0038.png)
![screenshot_3](https://user-images.githubusercontent.com/48316469/53949434-b37af380-40d2-11e9-88f6-95eb17fac567.png)

**Comment by tchegito** [comment]
Hi ! I'm not from the BIM server team, but I would suggest to specify heap size in "Mb" instead of "k". Indeed, 1024k means 1Mb, and this clearly isn't enough !
Actually, recommendation is 4gb (from here: https://github.com/opensourceBIM/BIMserver/wiki/Eclipse )
