### ISSUE TITLE
 Model fails to checkin

### ISSUE THREAD

**Issue by isandyas** [opensourceBIM/BIMserver#948]
model checkin fails at the last phase and getting a negative reference oid (-1)  
the error message:
Writing a reference with oid -1, this is not supposed to happen, referenced: -1 org.bimserver.models.geometry.impl.BufferImpl@397552f6 from 164169578 org.bimserver.models.geometry.impl.GeometryDataImpl@4c7a5719

- BIMserver v.15109/ ubuntu- tomcat 8
- schema IFC3.
i appreciate your help
thanks

**Comment by rubendel** [comment]
Does it also happen with 1.5.125? Can you share your model?

**Comment by isandyas** [comment]
thanks Rubendel for response, no I didn't test the last version on Ubuntu remote server yet, however both working well on my own computer. Actually the version 15109 since last Sep. was tested with several models. recently I want to test more models (Ifc4/Ifc2x3) each time I got the same msg. I mean this problem is model-independent. more information
![bimserver_failer zur Verglichen](https://user-images.githubusercontent.com/7805610/54901744-b13cd580-4ed7-11e9-87e3-5005da984a6d.JPG)
, I' have sometime ago updated IfcOpenShell plugin. also the CreateObject method was tested. I'm using JSON API to call BIMServer for my application. thanks again.

**Comment by rubendel** [comment]
Can you try the Streaming deserializer? It's tested more often (and performs much better)

**Comment by isandyas** [comment]
thank you! with streaming deserializer it works for me. as I understand the only different between streaming and non-streaming is the amount of memory in use, right? I have read somewhere here that non streaming JSON serializer, for example will be no more supported in future is that will also applicable on other serializer?. thanks once more for your support. I'm still intensive testing BIMserver release and I wanna post my finding for further development.

**Comment by rubendel** [comment]
There are still a few use cases for the non-streaming serializers/deserializers, that's why we haven't removed them yet. But we also have not maintained them lately, so for the final release we'll make a decision about this.
