### ISSUE TITLE
ClientIfcModel.loadGemoetry not working

### ISSUE THREAD

**Issue by szyuGH** [opensourceBIM/BIMserver#951]
Hi,

I try to load object geometries separately after commiting a model to the bimserver (version 1.5.125).
After calling the getModel method of the BimServerClientInterface with the includeGeometry parameter set to true, the loadGeometry method in the ClientIfcModel class is triggered, but it seems like no geometry is loaded.
After some fiddling and debugging I found that this part of the method is never reached and so the method returns before doing anything with geometry...
![image](https://user-images.githubusercontent.com/12794711/54755194-b81ccd00-4be5-11e9-88e2-3d9005c41346.png)

When bypassing this by changing the if condition to "... || geometry.getData().getIndices().getData()" (since getIndices is a buffer and the buffer always seems to be empty -> null), all objects are put into the list and an InputStream is loaded. 

However, this leads me to another observation I made:
when going into the processGeometryInputStream method, for geometryType == 0 the fomatVersion must be 16, but for me it is 17.. Where is the 17 coming from and why is it not equal to the necessary version?
If I change the required version to 17, it seems to run fine to the point, where geometryType == 5... 

![image](https://user-images.githubusercontent.com/12794711/54755776-01215100-4be7-11e9-8801-b73482ebd7e8.png)
I understand, that in this block the geometryInfoOid is used to determine the ifc class implementation. However, for me the result is always that the class implementation cannot be found, thus attempting to create a new one. But after that, the same oid is used to try to get a product oid, resulting in a GeometryException here:
![image](https://user-images.githubusercontent.com/12794711/54755905-5c534380-4be7-11e9-876e-f43fdb5ca3dd.png)

Any idea what could possibly go wrong? Because it seems to me like the whole process is taking place on your end. For the ifc model I use an IFC2x3 schema file.

Thanks for any help

**Comment by rubendel** [comment]
The protocol version has been fixed in 9da23858d57f8b6834409b69c58eb2792002a131, which will be in 1.5.126.

**Comment by szyuGH** [comment]
Thanks for the answer.
So this will solve the problem with the wrong version, but I still don't know if the issue with the geometry not being able to be loaded is a bug on your side, too, or if it is a problem with our ifc model. On the other hand, we used the same ifc model for older versions and it worked just fine.
So I guess this will also be resolved in 1.5.126?

**Comment by rubendel** [comment]
Since the version did not match, no geometry was loaded, so I guess so.
