### ISSUE TITLE
Trouble getting IfcSite without getDataObjects-calls

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#954]
ref: #843 
Im trying to get data without using the getDataObject-calls. Having trouble seeing how I can get the oid of IfcSite. A 'IsDecomposedBy' on the SProject level would do the trick.

**Comment by rubendel** [comment]
You should first get the IfcProject object, of which there should always be only one, from there, walk the decomposes tree.

**Comment by motjokk** [comment]
I was meaning to say IfcProject. The problem remains..
