### ISSUE TITLE
"Download" method from Json API turns into JsonParseException: Unrecognized token

### ISSUE THREAD

**Issue by Spirit30** [opensourceBIM/BIMserver#961]
**Describe the bug**

Error is returned by sending Json like this:

{"token":"MY_TOKEN","request":{"interface":"ServiceInterface","method":"download","parameters":{"roids":[11665411],"query":"ewogICJ0eXBlIjogewogICAgIm5hbWUiOiAiSWZjRG9vciIsCiAgICAiaW5jbHVkZUFsbFN1YlR5cGVzIjogdHJ1ZQogIH0sCiAgImd1aWRzIjogWwogICAgIjJ6czl2TmwyWEZDOXNOc1ZpcHlNYTkiCiAgXQp9","serializerOid":"1441830","sync":false}}}

MY_TOKEN is an actual Token obtained from Login in Console.
"query" Text is:
{
  "type": {
    "name": "IfcDoor",
    "includeAllSubTypes": true
  },
  "guids": [
    "2zs9vNl2XFC9sNsVipyMa9"
  ]
}
Serializer oid is from: GLTF 2 Serializer

**To Reproduce**

1. Send Json above from Http request of App or from Console API.
2. Get response (topicId).
3. Read Error by request to NotificationRegistryInterface.getProgress

**Expected behavior**

There is no Error in getProgress output and BIM Server allows to download my IFC model with GLTF 2 Serializer.

**Screenshots**

See NotificationRegistryInterface.getProgress output bellow.

**Additional context**

{
  "response": {
    "result": {
      "__type": "SLongActionState",
      "end": 1554817082916,
      "errors": [
        "com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'ewogICJ0eXBlIjogewogICAgIm5hbWUiOiAiSWZjRG9vciIsCiAgICAiaW5jbHVkZUFsbFN1YlR5cGVzIjogdHJ1ZQogIH0sCiAgImd1aWRzIjogWwogICAgIjJ6czl2TmwyWEZDOXNOc1ZpcHlNYTkiCiAgXQp9': was expecting ('true', 'false' or 'null')\n at [Source: (String)\"ewogICJ0eXBlIjogewogICAgIm5hbWUiOiAiSWZjRG9vciIsCiAgICAiaW5jbHVkZUFsbFN1YlR5cGVzIjogdHJ1ZQogIH0sCiAgImd1aWRzIjogWwogICAgIjJ6czl2TmwyWEZDOXNOc1ZpcHlNYTkiCiAgXQp9\"; line: 1, column: 321]"
      ],
      "infos": [],
      "oid": -1,
      "progress": 0,
      "rid": 0,
      "stage": 3,
      "start": 1554817082915,
      "state": "AS_ERROR",
      "title": "com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'ewogICJ0eXBlIjogewogICAgIm5hbWUiOiAiSWZjRG9vciIsCiAgICAiaW5jbHVkZUFsbFN1YlR5cGVzIjogdHJ1ZQogIH0sCiAgImd1aWRzIjogWwogICAgIjJ6czl2TmwyWEZDOXNOc1ZpcHlNYTkiCiAgXQp9': was expecting ('true', 'false' or 'null')\n at [Source: (String)\"ewogICJ0eXBlIjogewogICAgIm5hbWUiOiAiSWZjRG9vciIsCiAgICAiaW5jbHVkZUFsbFN1YlR5cGVzIjogdHJ1ZQogIH0sCiAgImd1aWRzIjogWwogICAgIjJ6czl2TmwyWEZDOXNOc1ZpcHlNYTkiCiAgXQp9\"; line: 1, column: 321]",
      "topicId": 136,
      "warnings": []
    }
  }
}

Any suggestions?
I didn't get why "query" was expecting ('true', 'false' or 'null')?

**Comment by rubendel** [comment]
Sorry, it seems the documentation is not correct for this method. The query does not need to be Base64 encoded, only encoded as a valid json string. Documentation has been updated in git master.

**Comment by Spirit30** [comment]
Thanks.
I'll check it out in my morning.

**Comment by Spirit30** [comment]
It worked perfect now. Thanks.
