### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by bimmodel** [opensourceBIM/BIMserver#968]
As there is no step-by-step text instructions watch the video and repeat
[https://www.youtube.com/watch?v=Vb6gokSBA0I](https://www.youtube.com/watch?v=Vb6gokSBA0I)
34:42 get a similar picture
![Screenshot2](https://user-images.githubusercontent.com/49679816/56413002-b00c8780-628e-11e9-9ba8-aa4988f05238.png)
next, you need to comment out the lines 46-54 in the file
/BimServerJar/src/org/bimserver/LocalDevBimServerStarter.java
but I do not have these lines, tell me what to do next?
![Screenshot_7](https://user-images.githubusercontent.com/49679816/56413151-2f9a5680-628f-11e9-9376-c234f5947472.png)

I understand that the video is old but this is the only clear instruction I found

**Comment by tchegito** [comment]
I'm not in the BIMServer team, but some months ago, when I started to work on it, I followed instructions there:
https://github.com/opensourceBIM/BIMserver/wiki/Eclipse

And it worked.

**Comment by bimmodel** [comment]
> And it worked.
Deleted that, started to do it again and get the link
[http://localhost:8080/apps/bimviews](http://localhost:8080/apps/bimviews)
now faced with another problem I can not upload the ifc file

A similar problem is described here 
[https://github.com/opensourceBIM/bimvie.ws/issues/124](https://github.com/opensourceBIM/bimvie.ws/issues/124)
but it is not solved((((

**Comment by rubendel** [comment]
First make sure everything compiles, makes no sense to try and run something that doesn't compile.
