### ISSUE TITLE
JRE Oracle Corporation/12.0.1 is not supported, advanced source lookup disabled.

### ISSUE THREAD

**Issue by bimmodel** [opensourceBIM/BIMserver#969]
the second question I installed java 12 and got in the console
**_JRE Oracle Corporation/12.0.1 is not supported, advanced source lookup disabled._**
tell me I did the right thing or do I need to install java 8

**Comment by bimmodel** [comment]
[https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/opensourceBIM/BIMserver/wiki/Requirements-1.5](https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/opensourceBIM/BIMserver/wiki/Requirements-1.5)

**Comment by bimmodel** [comment]
installed 8 then eclipse, and everything stopped working

**Comment by rubendel** [comment]
That's a pretty useless comment. Java 8 is supported. Java 11 will be in the next release.
