### ISSUE TITLE
.war file not found

### ISSUE THREAD

**Issue by danilosilva87** [opensourceBIM/BIMserver#973]
I am creating a bimserver docker image in version 1.5.127 and it is working correctly.
My dockerfile is basically a `wget` in the github url that has the `.war` file and places it in the tomcat folder, but in the
the latest versions (1.5.137) of bimserver do not have the .war file

I do not have much knowledge in java, is there any article or material on how to generate this .war file

**Comment by motjokk** [comment]
The last build is 1.5.125 i believe.

**Comment by danilosilva87** [comment]
ok @motjokk , and how do I get version 1.5.35 ? why is there this release in github

**Comment by rubendel** [comment]
I don't think there is a 1.5.137 release in github, only a tag

**Comment by danilosilva87** [comment]
> I don't think there is a 1.5.137 release in github, only a tag

Here for me, these releases appear @rubendel 

![Captura de tela de 2019-04-26 14-25-11](https://user-images.githubusercontent.com/7196041/56825535-ce92f580-682f-11e9-838a-ebb9526063f5.png)


Well, I assumed that with every release ready, there would be an `.war` archievo too, but I do not think so.

Is the latest version actually 1.5.125?

**Comment by rubendel** [comment]
1.5.125 is the latest yes, https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.125
