### ISSUE TITLE
Error on bent IfcReinforcingBar

### ISSUE THREAD

**Issue by omkvinde** [opensourceBIM/BIMserver#974]
An IfcReinforcingBar may have straight segments with circular fillets in between. The fillets are represented as IFCTRIMMEDCURVE. 

For a 90 degrees bend / fillet the definition look like this: 
**#33=IFCTRIMMEDCURVE(#211,(IFCPARAMETERVALUE(270.)),(IFCPARAMETERVALUE(360.)),.T.,.PARAMETER.);**     specifying angle from 270 to 360 degrees. 

When exporting IfcRebars as IFC 2x3 from **BIM server 1.5.125** using **BIMvie.ws**, the IfcTrimmedCurve are exported with blank angle parameters like this:
**#33=IFCTRIMMEDCURVE(#34,(),(),.T.,.PARAMETER.);**

With no angle parameters the entire IfcRebar becomes corrupted and are skipped by most viewers. 

If I manually add angle parameters to the exported IFC file the rebars becomes OK. 

Please see the attached sample IFC source file (containing only 1 IfcRebar with 5 straight segments and 4 90 deg. fillets. 

**To Reproduce**

1. Import the attached source IFC file to BIM server
2. Export IFC 2x3 using a query like this:
{
  "type": {
    "name": "IfcReinforcingBar",
    "includeAllSubTypes": true
  }, 
  "includes": [
    "ifc2x3tc1-stdlib:ContainedInStructure",
    "ifc2x3tc1-stdlib:OwnerHistory",
    "ifc2x3tc1-stdlib:Representation",
    "ifc2x3tc1-stdlib:ObjectPlacement"
  ]
}

3. Compare the IFCTRIMMEDCURVE lines of the exported file with the source file. The angle parameters are blank /missing.  

![image](https://user-images.githubusercontent.com/7466225/56851844-fb203d80-6913-11e9-9539-fc4ac1f9c42e.png)

[exportFromServer.txt](https://github.com/opensourceBIM/BIMserver/files/3124055/exportFromServer.txt)
[1RebarSourceIFC.txt](https://github.com/opensourceBIM/BIMserver/files/3124057/1RebarSourceIFC.txt)

**Comment by rubendel** [comment]
Are you sure the image corresponds with the 1RebarSourceIFC attachment? Because I only see one bend in all the viewers I tried.

**Comment by omkvinde** [comment]
Hello Ruben, 
Sorry, I edited the IFC compositecurve line (#223) to include only one bend and 2 straight segments in the file, to simplify the debugging. Please see the attached file which should correspond to the image. 
[1RebarSourceIFCrevised.txt](https://github.com/opensourceBIM/BIMserver/files/3126422/1RebarSourceIFCrevised.txt)



The file exported from BIM server contains all 9 segments.

**Comment by omkvinde** [comment]
Closed by mistake. Sorry.

**Comment by rubendel** [comment]
Which serializer are you using? I cannot reproduce this with the streaming ifc step serializer.

**Comment by omkvinde** [comment]
Hi, I have been using the IFC2x3tc1 serializer (BIMVie pulldown). I have now been testing on the IFC2x3tc1 (streaming) serializer, and it seems to work OK on both the small sample file and a much bigger file, which is VERY promising. 
I will do some more testing on bended rebars with angles smaller / bigger than 90 degrees. 

What is the main difference bwt these 2 serializers?

reg Ole M

**Comment by rubendel** [comment]
The streaming one is faster and uses much less memory, that's why it's also tested a lot better. The other one will be removed when all uses cases can be solved with the new one.

**Comment by omkvinde** [comment]
Works fine on non-90 degrees bends as well. Thanks a lot !
