### ISSUE TITLE
No PackageMetaData found for ifc2x3tc1 when start serverJar

### ISSUE THREAD

**Issue by dingrui** [opensourceBIM/BIMserver#976]
bimserverjar-1.5.137-SNAPSHOT 
![error](https://user-images.githubusercontent.com/5811864/57205687-c9cdfe80-6ff2-11e9-996e-b2b082f86759.png)

**Comment by rubendel** [comment]
I don't think there is a 1.5.137 release. Can you try 1.5.138? Which OS? Which Java version?

**Comment by dingrui** [comment]
> I tried 1.5.136, but it was the same error. os--win10 X64 , java version--1.8

**Comment by dingrui** [comment]
> I don't think there is a 1.5.137 release. Can you try 1.5.138? Which OS? Which Java version?

I tried 1.5.136, but it was the same error. os--win10 X64 , java version--1.8

**Comment by rubendel** [comment]
I don't think there is a 1.5.136 release either, next one before 1.5.138 is 1.5.125.

**Comment by dingrui** [comment]
> I don't think there is a 1.5.136 release either, next one before 1.5.138 is 1.5.125.

When I turned on the debug log as maven suggests, the following error message was reported.Need an oracle database？
![error](https://user-images.githubusercontent.com/5811864/57274141-d161d600-70cc-11e9-904a-2db70f2f3461.jpg)

**Comment by dingrui** [comment]
@rubendel   I have solved it, thank you very much

**Comment by rubendel** [comment]
Thanks for sharing what the problem was.
