### ISSUE TITLE
java.lang.NoSuchMethodError:javassist.ClassPool.toClass  with bimserverclient 1.5.138

### ISSUE THREAD

**Issue by sameepkaranjkar** [opensourceBIM/BIMserver#981]
Hi,
  I have deployed my bimserver version 1.5.38  inside Tomcat 8  and using bimserverclientlib 1.5.138 for connecting to bimserver via client.I am using the same code given in the wiki page for connecting to bimserver and check in the ifc file there.Code as below : 
`   try (JsonBimServerClientFactory factory = new JsonBimServerClientFactory(
                BIM_SERVER_ADDRESS)) {
              try (BimServerClient client = factory
                .create(new UsernamePasswordAuthenticationInfo(USER_NAME, PASSWORD))) {
                if (!client.isConnected()) {
                    client.connect();
                }
                ServiceInterface serviceInterface = client.getServiceInterface();
                SProject project = serviceInterface.addProject(projectName, "ifc2x3tc1");
                long poid = project.getOid();
               
                SDeserializerPluginConfiguration deserializer = client.getServiceInterface()
                    .getSuggestedDeserializerForExtension("ifc", poid);
                // Make sure you change this to a path to a local IFC file
                Path demoIfcFile = Paths.get(filePath);
                String comment = demoIfcFile.getFileName().toString();
                // Here we actually checkin the IFC file.
                client.checkinSync(poid, comment, deserializer.getOid(), false, demoIfcFile);
                return project.getUuid();
            } catch (Exception ex) {
                throw ex;
            }
        } catch (Exception ex) {
            throw ex;
        }`

Received below error : 
![Method_Not_Found_Error](https://user-images.githubusercontent.com/33112197/57846593-3d36f380-77dd-11e9-8467-246d8520cc0a.JPG)

Is this a known bug as i could see some commits there in recent version with comment
Use own ClassLoader to load classses from as well because it's not always the same as the system ClassLoader.

https://github.com/opensourceBIM/BIMserver/commit/e9e2bbd30f36cd3f9cb689c18c5f61d24661e127#diff-388d73b0a8838a49bbdadd482301196e

 Any workaround or help really appreciated.

**Comment by rubendel** [comment]
This is probably something else. It looks like different versions of JavaAssist have been loaded. Is you own application perhaps also using a version of JavaAssist in one of it's dependencies?

**Comment by sameepkaranjkar** [comment]
I checked my own application and it does not use JavaAssist (need to verify for external application packages) dependencies as i am not able to find those classes if i remove bimserverclientlib dependency.As a quick workaround i explicitly added dependency for javassist <dependency org="javassist" name="javassist" rev="3.4.GA"/> and updated org.bimserver.shared.reflector.RealtimeReflectorFactoryBuilder.java file which was giving error.
Just removed those - Neighbour class argument.
Previous : 
 `Class<?> class1 = this.pool.toClass(reflectorFactoryImpl, NeighbourClass.class,
					this.getClass().getClassLoader(), this.getClass().getProtectionDomain());`

Updated one : 
` Class<?> class1 = pool.toClass(reflectorFactoryImpl, getClass().getClassLoader(),
                    getClass().getProtectionDomain());`

**Comment by rubendel** [comment]
Those neighbour arguments were added to JavaAssist in order for it to work on Java 11. BIMserver now also supports running on Java 11, so that's why we upgraded to a newer JavaAssist.

Maybe something is wrong in the BIMserver dependencies. If you could check for external dependencies that would be great (in Eclipse you can just select you own pom.xml file and open the "Dependency Hierarchy" tab) to see all dependencies.

**Comment by sameepkaranjkar** [comment]
I am using ivy instead of maven in my project setup , not sure how to check those all dependency in ivy.But if i could see all the JARs in Ivy library from eclipse the javassist JAR is not there in my application.

**Comment by rubendel** [comment]
Thanks for the update
