### ISSUE TITLE
FireExit for IfcDoor

### ISSUE THREAD

**Issue by jbenni** [opensourceBIM/BIMserver#982]
Is FireExit implemented on BIMServer ? It's a Pset_DoorCommon property but doesn't appear on BIM view. I think it would be nice to locate easily all the fire exit.

**Comment by rubendel** [comment]
BIMserver only knows about the IFC schema. All properties are stored, so also all Pset data is stored.

BIMvie.ws just lists all the properties there are (maybe not the complex ones, but I don't thinj Pset_DoorCommon uses complex properties). Can you perhaps share the model?
