### ISSUE TITLE
Type Missing artifact org.opensourcebim:ifcplugins:jar:0.0.64-SNAPSHOT	

### ISSUE THREAD

**Issue by geolocus** [opensourceBIM/BIMserver#984]
Description	Resource	Path	Location	Type
Missing artifact org.opensourcebim:ifcplugins:jar:0.0.64-SNAPSHOT	pom.xml	/Tests	line 55	Maven Dependency Problem

Get this on Eclipse Mars with JDK 8,
 
also:
Exception in thread "BIMserver Starter Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(String.java:1967)
	at org.bimserver.starter.Starter.getJarFileNameNew(Starter.java:675)
	at org.bimserver.starter.Starter.expand(Starter.java:625)
	at org.bimserver.starter.Starter.access$3(Starter.java:623)
	at org.bimserver.starter.Starter$4$1.run(Starter.java:258)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rubendel** [comment]
The first seems to be a compilation error that I cannot reproduce when using all the git master heads (which I assume you also tried). IfcPlugins is indeed at 0.0.64-SNAPSHOT in git master head.

Why do you try to start the JarStarter from Eclipse? Are you going to do changes to it?

Eclipse Mars is from June 2015... I'd upgrade to something newer.

**Comment by geolocus** [comment]
I couldnt manage to launch from desktop so I was watching vids whole day with Eclipse. I am newby. Need this for ifc2b3dm. 




Gauti „Outlook“, skirtą „Android“







On Thu, May 23, 2019 at 10:32 PM +0200, "Ruben de Laat" <notifications@github.com> wrote:












The first seems to be a compilation error that I cannot reproduce when using all the git master heads (which I assume you also tried). IfcPlugins is indeed at 0.0.64-SNAPSHOT in git master head.


Why do you try to start the JarStarter from Eclipse? Are you going to do changes to it?


Eclipse Mars is from June 2015... I'd upgrade to something newer.

**Comment by geolocus** [comment]
Tried launching on Latest Eclipse with JDK 12. Does not support it says. 




Gauti „Outlook“, skirtą „Android“







On Thu, May 23, 2019 at 10:52 PM +0200, <lukas@geolocus.lt> wrote:










I couldnt manage to launch from desktop so I was watching vids whole day with Eclipse. I am newby. Need this for ifc2b3dm. 




Gauti „Outlook“, skirtą „Android“







On Thu, May 23, 2019 at 10:32 PM +0200, "Ruben de Laat" <notifications@github.com> wrote:












The first seems to be a compilation error that I cannot reproduce when using all the git master heads (which I assume you also tried). IfcPlugins is indeed at 0.0.64-SNAPSHOT in git master head.


Why do you try to start the JarStarter from Eclipse? Are you going to do changes to it?


Eclipse Mars is from June 2015... I'd upgrade to something newer.

**Comment by geolocus** [comment]
Rubendel, which JDK fits with latest BIM server?

**Comment by rubendel** [comment]
JDK 8, 9, 10 and 11
