### ISSUE TITLE
disable geometry generation

### ISSUE THREAD

**Issue by orashkenazi** [opensourceBIM/BIMserver#985]
Hello, Im using bimserver 1.5.138.

For some reason it seems that some ifc files get stucked in geometry generation stage. (without showing any error on bimserver's log.. it is if it is still working).

The same ifc file that have this problem actually worked with no problem on 1.5.101.. 
maybe it is due to the newer ifcopenshell plugin? 

Anyway, for my case i dont really need bimserver to generate geometries.
I saw the option for "Generate geometry on checkin" on the server settings in bimviews,
I tried to disable it but it seems that the geometry generation is still initiated when im doin checkin. ( both with bimview, and with the Javascript-api in my app).

is disabling the "Generate geometry on checkin" suppose to work??

thanks
Or

**Comment by rubendel** [comment]
Fixed in git head master, will be in the next release.
