### ISSUE TITLE
any solution to export units of measurements from revit to ifc

### ISSUE THREAD

**Issue by danialb** [opensourceBIM/BIMserver#990]
Bimvision reads Ifc from revit, and  parameters appear with  units of measurements. But units of measurement don't appear  like parameters in bim server.

![Selección_502](https://user-images.githubusercontent.com/34541539/59201642-2ba5f900-8b9b-11e9-9664-dc2c836a2c75.jpg)

Is it possible that Bimserver treats units of measurements?
How can we export  units of measurement from Revit to Ifc?
Does exit any call to obtain  units of measurement through poid?

for example, the length in meter...

![Selección_503](https://user-images.githubusercontent.com/34541539/59201764-6c9e0d80-8b9b-11e9-8457-1b44d61e1600.jpg)

thanks

**Comment by rubendel** [comment]
I'd suggest reading the IFC spec. Units are stored in IFC (and Revit does indeed export them). They are however usually stored on a project-level, not on a per-property bases.
