### ISSUE TITLE
IfcCartesianTransformationOperator3D ignored on objects

### ISSUE THREAD

**Issue by aurelien-gille** [opensourceBIM/BIMserver#992]
**Describe the bug**
It may be my fault but, when I use IfcCartesianTransformationOperator3D (Uniform or nonUniform) it don't seems to work well.

**To Reproduce**
1. Import ifc [this file](https://we.tl/t-yY0awehy4a) on BimServer
2. Compare given geometry with other ifc viewers

**Expected behavior**
Same geometry as other viewers

**Screenshots**
![TOBIMSERVE](https://user-images.githubusercontent.com/1969437/59508272-afb6f400-8ead-11e9-8469-7db85322bbbc.png)

**Additional context**
I don't see any error on console logs
I used BimServer 1.5.147 version
Other viewers used are : 
     - [BIMer.eu](http://bimer.eu/)
     - [IfcOpenShell blender plugin](http://ifcopenshell.org/ifcblender.html)
     - [BIM Vision](https://bimvision.eu/)
     - [AutoDesk Online Viewer](https://viewer.autodesk.com/)

[Used file here](https://we.tl/t-yY0awehy4a)

**Comment by rubendel** [comment]
Here is what I get with Solibri, DDS-CAD and Areddo

![screenshot](https://user-images.githubusercontent.com/377978/59562190-de59d980-9029-11e9-8241-09ba77340841.png)

And with BIMvie.ws
![bimvie](https://user-images.githubusercontent.com/377978/59562201-034e4c80-902a-11e9-9a66-5f18d3f60c75.png)

So the interesting things here I think are the facts that:
- Our BIMvie.ws representations differ
- All the viewers you used do it differently than the viewers I used

**Comment by aurelien-gille** [comment]
Wrong file, sorry, [here is the one](https://we.tl/t-YfFJeiIJBr)

**Comment by rubendel** [comment]
Closing issue, taking up too much time

![weirdfile](https://user-images.githubusercontent.com/377978/59586640-a9aa5880-90e3-11e9-91a6-a5eac3fc9020.png)
