### ISSUE TITLE
GetAllUsers returns NullPointer Exception instead of access denied when not logged in

### ISSUE THREAD

**Issue by Noranius** [opensourceBIM/BIMserver#994]
**Describe the bug**
The result of the call, when the user is not logged in
```
{
  "request": {
    "interface": "ServiceInterface", 
    "method": "getAllUsers", 
    "parameters": {
    }
  }
}
```
shows a NullPointerException
```
{
  "response": {
    "exception": {
      "__type": "NullPointerException",
      "message": "java.lang.NullPointerException"
    }
  }
}
```

**To Reproduce**
1. Open the Console plugin
2. Click on 'getAllUsers' in the navigation bar
3. Click on Send

**Expected behavior**
The result should say: Access denied instead of a null pointer exception

**Screenshots**
![BimserverGetAllUsers](https://user-images.githubusercontent.com/29037766/59588299-8f727980-90e7-11e9-92cf-05ca062cfd86.JPG)

**Additional context**
nothing

**Comment by Noranius** [comment]
The problem was, that i wasn't logged in. Click the login button on the upper right and login. After that getAllUsers returns the users.

But instead of throwing a nullpointer exception an access denied or something should occur.

**Comment by rubendel** [comment]
Fixed
