### ISSUE TITLE
NoSuchMethodError on sending reset password

### ISSUE THREAD

**Issue by Noranius** [opensourceBIM/BIMserver#995]
**Describe the bug**
When sending a password request, I don't receive a mail and an error occurs in the log file.
[BimServerLog.txt](https://github.com/opensourceBIM/BIMserver/files/3296477/BimServerLog.txt)

**To Reproduce**
1. Setup a SMTP server
2. Configure BimServer to use that SMTP server
3. Send Password reset (see screenshot)
    a) open the user list
    b) clicl on "action" next to the user
    c) select "send password reset"

**Expected behavior**
Send a mail to reset password

**Screenshots**
![BenutzerBimServer](https://user-images.githubusercontent.com/29037766/59599186-38c46a00-90fe-11e9-904b-c8d6e59bf2d2.JPG)

**Additional context**
#989

**Comment by rubendel** [comment]
Which version of BIMserver and JRE?

**Comment by Noranius** [comment]
BIMserver: 1.5.147
Java: OpenJDK 11.0.3

**Comment by rubendel** [comment]
This is now fixed in git master head, was a dependency problem
