### ISSUE TITLE
Error while uploading proper IFC file

### ISSUE THREAD

**Issue by Noranius** [opensourceBIM/BIMserver#997]
**Describe the bug**
When importing a simple IFC file with a wall, the owner history is faulty:
"Error on line 102: Field OwnerHistory of IfcRoot is no aggregation"

**To Reproduce**
1. Go to Console
2. Log in
3. Click on CheckInSync
4. Fill in the parameters like in the screenshot
5. click on send

**Expected behavior**
Chek in the ifc file properly

**Screenshots**
![UploadError](https://user-images.githubusercontent.com/29037766/59610361-81d5e780-9119-11e9-81e0-7c1e9f4d5d13.JPG)

**Additional context**
The file is consistent to the IFC specification (checked against https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcutilityresource/lexical/ifcownerhistory.htm)

BIMServer version: 1.5.147
Java: OpenJDK 11.0.3
[IFC_Wall_example.zip](https://github.com/opensourceBIM/BIMserver/files/3297285/IFC_Wall_example.zip)

**Comment by rubendel** [comment]
The file is invalid.

```
#115= IFCBUILDING('1gvEmoy7D5LeA4LlFNhyb8',(#41),'',$,$,#32,$,'',.ELEMENT.,$,$,#111);
```

The second argument cannot be an aggregation, the valid line would be:
```
#115= IFCBUILDING('1gvEmoy7D5LeA4LlFNhyb8',#41,'',$,$,#32,$,'',.ELEMENT.,$,$,#111);
```

I have improved the errors message a little bit, it now reads:
```
[IFC_Wall_example.ifc] Error on line 102: Field OwnerHistory of IfcBuilding is no aggregation
```
