### ISSUE TITLE
Autostart on system start

### ISSUE THREAD

**Issue by Noranius** [opensourceBIM/BIMserver#998]
Is it possible to start BIMServer automatically on start up? Problem is, that the jar file opens a JFrame and needs a mouseclick on "Start". Is it possible to automate this last click?

**Comment by rubendel** [comment]
That's exactly what the WAR version of BIMserver is for. There is plenty of information on the internet about how to run a WAR file (usually people use Apache Tomcat). On all distro's Tomcat can be auto started.
