### ISSUE TITLE
Updating BIM server

### ISSUE THREAD

**Issue by Neurokey** [opensourceBIM/BIMserver#999]
Hey,

I am trying to update my BIM server from version 1.5.101 to the latest version 1.5.147.
The most important thing I want to achieve is that the database data is not lost while updating.
Unfortunately, I am not exactly sure how to achieve that. I tried to backup the old database and copy it into the latest version, howerver this does not seem to work. The database still needs to be migrated, but this should be done automatically, right?
Am I doing something wrong or is there another solution?

**Comment by motjokk** [comment]
ref. #809 
This seems to only be available on major releases

**Comment by rubendel** [comment]
Also: https://github.com/opensourceBIM/BIMserver/wiki/BIMserver-Database-Migration
